### ISSUE TITLE
태풍 이동 완료 후 이벤트 발생 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#10]
안녕하세요. 바이브컴퍼니입니다.

태풍 이동 완료 후 이벤트가 발생하지 않는거 같습니다.
확인 부탁 드립니다.
(아래 동영상 참조)

https://user-images.githubusercontent.com/38479834/119458746-06a2f480-bd78-11eb-9093-f352c330b4ed.mp4

그럼, ...

**Comment by YunSumin** [comment]
첨부해주신 영상 확인하여 태풍 이동 이벤트가 정상적으로 발생하도록 엔진이 수정되었습니다.
수정 된 새 엔진 적용 부탁드립니다.

감사합니다.

**Comment by HyunSeongKil** [comment]
확인했습니다
