### ISSUE TITLE
그림자 시뮬레이션 흔들림 현상

### ISSUE THREAD

**Issue by giwon1130** [EgisCorp/XDWorld#100]
https://user-images.githubusercontent.com/92919334/139432557-75f9ef89-f25c-4335-a9b5-ac7782afba20.mp4

그림자 시뮬레이션 흔들림 현상 문제 입니다.

**Comment by hjaejae** [comment]
3차원 건물과 그림자와의 Z-Fighting 현상입니다.
카메라와 객체와의 거리가 멀 수록 심하게 발생합니다.
현재 여러각도로 Z-Fighting 현상을 줄일 수 있게 개발중에 있습니다.
