### ISSUE TITLE
격자기능(개별 격자 외곽라인 입력기능)&파이프데이터(타일데이터 단순화 표현 기능) 요청

### ISSUE THREAD

**Issue by plusvolt** [EgisCorp/XDWorld#101]
안녕하세요. 서울사무실 김상민 차장입니다.

1. 격자 생성기능 관련하여 스타일 부분에 수정요청
 기존 격자는 개별 격자의 채움 색상은 지정이 가능하고 외곽 라인은 일괄로만 적용되었는데
외곽 라인에 대해서도 개별 스타일을 넣어줄 수 있도록 기능 수정 요청 드립니다.

2. 파이프 데이터 단순표현 거리설정 기능추가 요청
 현재 관로데이터 가시화 관련해서 사용자 레이어로 생성하는 방법과 타일레이어 사용하는 방식이 있는데
사용자 레이어에 있는 setSimplifyRange기능으로 거리 별 표현방식을 지정할 수 있는데 타일 레이어에도
해당 함수 적용 요청 드립니다.

감사합니다.

**Comment by YunSumin** [comment]
안녕하세요, 차장님

금번 업데이트 관련하여 API 상세내용 전달드립니다.

1. 격자 생성기능 관련하여 스타일 부분에 수정요청

   그리드 생성 시 셀 단위로 라인 색상 지정이 가능하도록 API가 추가되었습니다.
   bool SetGridCellLineColor(number cellIndexX, number cellIndexY, JSColor color)
     * [Class] JSColorGrid3D
     * [Parameter]
        * cellIndexX : 색상을 지정하고자 하는 셀 X 인덱스 
        * cellIndexY : 색상을 지정하고자 하는 셀 Y 인덱스 
        * color : 라인 색상
     * [Return] 설정 성공 여부
      ```
      // 각 셀의 그리드 색상 배치
      for(var i=0; i < rowNum;i++) {
      	for(var j=0; j < colNum;j++){
		
      		// 셀 색상 설정
      		if (typeof _data.cells[grididx] != 'undefined') {
      				
      			gridValue = parseFloat(_data.cells[grididx].VALUE);
      				
      			var color = null;
      
      			if(gridValue > 50) 		color = gridCellColor[5];
      			else if(gridValue > 40) 	color = gridCellColor[4];
      			else if(gridValue > 30)	color = gridCellColor[3];
      			else if(gridValue > 20) 	color = gridCellColor[2];
      			else if(gridValue > 10) 	color = gridCellColor[1];
      			else 			color = gridCellColor[0];
      
      			colorGrid3D.SetGridCellColor(j, i, color);
      			colorGrid3D.SetGridCellLineColor(j, i, color);
      
      		} else {
      			gridValue = 0;
      			colorGrid3D.SetGridCellColor(j, i, gridCellColor[0]);
      		}
      	}
      }
      ```

2. 파이프 데이터 단순표현 거리설정 기능추가 요청
   타일 레이어 단위 단순 표현 거리 설정 API가 추가되었습니다.
   bool SetVectorPipeSimplyRange(number simplyRange)
     * [Class] JSLayer
     * [Parameter]
        * simplyRange : 라인 변환 기준 거리 (디폴트 값은 1000.0 입니다.)
     * [Return] 설정 성공 여부
   ```
   var layerList = new Module.JSLayerList(false);
   var layer = layerList.nameAtLayer("vector_ufl_pipe_dduck");
   layer.SetVectorPipeSimplyRange(100.0);
   ```

최신 엔진 파일 적용후 API 활용 부탁 드립니다.

감사합니다.

**Comment by plusvolt** [comment]
과장님 배포해주신 기능 테스트 결과 둘 다 작동은 잘 됩니다.

다만 격자 생성 기능에서 사용 안하는 격자에는 투명 값을 부여해야만 
강조하려는 격자가 보이는 형태다 보니 렌더링시에 성능이 저하되는 것 같습니다.

현재 시스템에서는 180*160개 정도 되는 격자로 데이터 적용 중 입니다.
아무래도 속도 이슈가 조금 개선되어야 실제 서비스에서 사용이 가능할 것 같습니다.

해당 이슈에 대한 확인 좀 부탁드리겠습니다! 감사합니다!

**Comment by YunSumin** [comment]
안녕하세요, 차장님

금일 투명 값이 부여 된 셀이 많은 격자에 대해
렌더링 부담을 덜 수 있도록 엔진이 업데이트 되었습니다.

이전에는 색상 값 상관 없이 모든 셀을 생성하였지만,
이번 엔진에서는 색상 투명 값이 0인 셀, 라인은 생성하지 않아
투명 값이 많은 셀의 그리드는 다소 가볍게 렌더링 될 수 있도록 수정 되었습니다.

업데이트 적용 부탁 드립니다.
감사합니다.
