### ISSUE TITLE
위경도 좌표값으로 해당 위치 높이값 구하는 방법

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#102]
안녕하세요!

위경도만 가지고 있을 때 해당 위치의 높이값을 구할 수 있을까요?

**Comment by avamk2** [comment]
안녕하세요 

해당부분에 대해서는 API적으로는 아래와 같은 API로 동작합니다.
` JSMap::getTerrHeightFast(double _dLon, double _dLat) `

단 위에 API 기능 자체는 **현재 메모리상에 로딩된 DEM 기준** 으로 동작하기에 좀더 정확한 높이를 측정하기 위해서는 해당 지역을 로딩한 시점에서 호출해줘야 정확도가 올라갑니다.

**Comment by giyoon99** [comment]
작동 확인했습니다 감사합니다!

DEM 로딩이 덜 되었을 경우 조금 차이가 있긴합니다..

DEM 로딩이 끝나는 시점을 알 수 있는 방법이 있을까요?..

**Comment by YangHeeBong** [comment]
DEM은 기본적으로 0~15레벨로 구성되면
  - 0 레벨 : 50
  - 1 레벨 : 200
  - 2 레벨 : 800
 
이러한 방법으로 레벨이 증가 할수록 4배씩 증가 합니다. DEM 생성 완료 이벤트를 반환 시 갱신 된 DEM 요청 이벤트가 발생함으로 랜더링 속도에 안좋은 영향을 주게 됩니다. 

혹시 고도값을 통해 오브젝트를 생성이 필요하신 부분이라면 미리 고도값을 설정 또는 저장하여 필요한 시점에서 반환 받아 처리 하는 방법이 가장 일반적으로 사용 되고 있습니다.
