### ISSUE TITLE
addGhostSymbolBy3DSbyJson 지우는법

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#103]
안녕하세요! Module.getGhostSymbolMap().addGhostSymbolBy3DSbyJson로 생성된 객체를 지우고 싶습니다.
removeGhostSymbolBy3DSbyJson은 없나요...?
감사합니다!

**Comment by YunSumin** [comment]
안녕하세요, 

Module.getGhostSymbolMap().addGhostSymbolBy3DSbyJson 은 3DS 모델을 엔진에 등록하는 API로
객체 생성은 Module의 createGhostSymbol API 를 통해 이루어지므로 객체 삭제와는 무관합니다.

createGhostSymbol API 로 생성하신 객체를 레이어에 등록하여 가시화 후
삭제하고 싶으실 때에는 레이어 객체의 removeAtIndex, removeAtObject, removeAtKey API를 활용하시면 됩니다.
위 API로 생성한 객체를 삭제하실 수 있습니다.

또한 금일 고스트 심볼 API 구성이 개편되어 
샌드박스에 개편 사항이 반영되었으니 참조 부탁 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit
