### ISSUE TITLE
에니메이션 없이 특정 위치로 이동하는 함수 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#104]
안녕하세요. 바이브컴퍼니입니다.

에니메이션 없이 특정 위치로 이동하는 함수 문의합니다.

move... 나 setLocation()을 사용해 봤는데, 모두 에니메이션 같은 기능이 있었습니다.

이동하는 에니메이션 없이 바로 해당 위치 딱! 나오게 하는 기능 있는지 문의합니다.

그럼, ...

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

해당 기능을 할 수 있는 방법은 2가지 있습니다.

1. Module.getViewCamera().moveLonLatAlt(128.555323, 35.874567, 1000, false);
   - parameter 정보: 경도, 위도, 고도, 애니메이션 효과 여부
   - 카메라 현재 Tilt, Direct에서 위치 이동

2. Module.getViewCamera().move(new Module.JSVector3D(128.555323, 35.874567, 1000), 80, 0, 0);
   - parameter 정보: JSVector3D(경도, 위도, 고도), Tilt, Direct, Speed ( 0 일 경우 애니메이션 효과 없이 이동 )
   - 카메라 현재 Tilt, Direct도 같이 조작하여 이동

감사합니다.
