### ISSUE TITLE
텍스처 이미지 화질 개선 방법

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#105]
안녕하세요, 대구 사무실에 김선옥 주임입니다^^
작년에 진행한 프로젝트 중에서, 3D 모델링 텍스처 이미지 화질이 좋지 않아 
두 가지 방법을 통해 개선시킨 적이 있었습니다.

1. 텍스처 이미지 4096 사이즈 제한 해제
  - 성능 상의 문제로 기존에 제한 걸려있던 사이즈(4096*2048)를 8192사이즈로 완화
2.  저사양(모바일지원) 렌더 모드 조정
  - Module.Start 호출 전 Module.SetMobileMode(0) 호출

현재 진행 중인 다른 프로젝트에서 Module.SetMobileMode(0) 호출하는 부분을 넣어줬지만 변화가 없습니다.
텍스처 이미지 사이즈가 제한되어 있어서 그런걸까요?
참고로 작년 프로젝트의 엔진은 깃이 생기기 전이라, 그 프로젝트 맞춤 엔진이였고,
현재 엔진은 깃에 업로드된 엔진입니다!

**Comment by YunSumin** [comment]
안녕하세요,

작년 사업에서는 부득이 8192*8192 크기 텍스쳐를 사용하였으나,
시스템 부하가 커 원활한 프레임의 렌더링이 어려운 관계로
현재 엔진에서는 4096*4096 사이즈의 이미지만 허용 하고 있습니다. 

또한 Module.SetMobileMode(0) API는 내부적으로 테스트를 위해 활용된 API이기 때문에
고화질 텍스쳐 LOD 세팅은 JSLayer의 lod_object_detail_ratio 프로퍼티를 사용하시면 될 것 같습니다.

아래 샌드박스의 setTileTextureLOD 함수 참조 부탁 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_texture_lod

LOD 값을 조절하시면 먼 거리에서 고화질 텍스쳐 로드가 가능합니다.

**Comment by KIMSEONOK** [comment]
올려주신 샌드박스의 함수를 사용해보았는데, 적용이 되지 않는 것 같습니다.ㅠㅠ
XDEmapCreateLayer API를 호출 할 때, 7번째 파라미터(레이어 타입)를 20번이 아닌 9번으로 호출하는 레이어여서 그런걸까요?

**Comment by YunSumin** [comment]
lod_object_detail_ratio 속성은 9번 Real3D 레이어와 20번 드론 LOD 레이어 모두 공통적으로 적용되는 속성이라
적용되지 않는 다른 원인이 있는 것 같습니다.
혹시 로드하시는 모델의 텍스쳐 이미지가 4096 이상의 이미지가 아닌지 확인 부탁 드립니다.
