### ISSUE TITLE
드라이빙 기능에서 이동하는 방향이 아닌 다른 방향을 보며 이동하는 기능 문의

### ISSUE THREAD

**Issue by giwon1130** [EgisCorp/XDWorld#106]
드라이빙 기능에서 이동하는 방향이 아닌 
다른 방향을 보며 이동하는 기능이 가능한지 문의 드립니다.

**Comment by YunSumin** [comment]
게시하신 내용 상으로는 구현하시는 기능에 사용하시는 API가 어떤 것인지 알기 어렵습니다.
사용하시는 API에 대한 상세 내용 말씀 부탁 드립니다.

**Comment by giwon1130** [comment]
https://user-images.githubusercontent.com/92919334/140635474-2a0c74e2-ef2b-4e09-bad1-046e89863e0a.mp4

드라이빙 기능을 실행하면 다음 도착지를 바라보며 이동하게 됩니다.
다음 도착지가 아닌 다른 방향을 보며 이동할 수는 없는지 궁금합니다.

**Comment by YunSumin** [comment]
금번 샌드박스 업데이트에 경로 이동 관련 샘플이 새로 추가되어 안내 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=camera_trace_path_moving

특정 오브젝트를 카메라 타겟팅 하는 기능을 응용한 것으로
오브젝트는 일정한 시간 간격으로 지정한 경로를 이동하고, 카메라는 오브젝트를 따라서 이동합니다.

이 과정에서 카메라가 오브젝트를 바라보는 틸트, 방향 각도를 마우스 이벤트와 외부API로 조절 할 수 있습니다.

샌드박스 코드 참조 부탁 드립니다.
감사합니다.
