### ISSUE TITLE
배경영상을 투명화시키고 정사영상은 띄우는 방법

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#107]
안녕하세요, 대구 사무실 김선옥 주임입니다!
Module.XDESetPlanetTransparecny(0.0) 을 통해 배경영상을 끈 상태에서 
png 형식의 정사영상 이미지는 띄우게 할 수 있는 방법이 있을까요?

**Comment by YunSumin** [comment]
안녕하세요, 주임님

정사영상 이미지는 렌더링 시 지형 텍스쳐 위에 그려지기 때문에
지형 투명처리와 정사영상 표출은 동시에 적용하기는 불가능합니다.

만약 아래 그림과 같이 일부 지역의 배경영상만 단독으로 띄우신다면,
![image](https://user-images.githubusercontent.com/82925313/141077617-dac0cdba-6251-48e1-91ea-1eebd5d3565d.png)

엔진의 mapBox 기능을 활용하실 수 있습니다.
위 이미지는 지형을 렌더링하되, 지정한 영역 외 지형은 까맣게 처리하는 기능을 포함하고 있습니다.
단, 이 경우에도 아파치 서버로 접근 가능한 DEM 데이터가 별도로 존재해야 합니다.

검토해보셔서 추가로 문의가 있으신 경우 말씀 부탁 드립니다.

**Comment by KIMSEONOK** [comment]
넵 답변 감사합니다!
