### ISSUE TITLE
V-World 2D 지도 처럼 만드는법

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#108]
안녕하세요!
V-World와 같이 2D 지도로 만들고 간단히 폴리곤을 그리고 싶습니다..
가능할까요...?
감사합니다!

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

http://sandbox.dtwincloud.com/code/main.do?id=layer_vworld_wmts

브이월드 API Key를 발급 받으신 후 샌드박스 예제를 참고하시면 가능합니다.

샌드박스 예제를 사용하여 브이월드 2D 지도를 매핑한 후 폴리곤 생성하실 수 있습니다.

감사합니다.
