### ISSUE TITLE
3ds 편집 기능 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#109]
안녕하세요. 바이브컴퍼니입니다.

3ds 편집 기능 문의입니다.

**아래 이미지처럼 ui에서 rotation값을 변경했습니다.
js 코드에 console로 관련 값을 표시했습니다.
but, ui상의 값과 console에 찍힌 y, z 값이 서로 다릅니다.**
이게 맞는건가요???

![image](https://user-images.githubusercontent.com/38479834/140240535-44f1772a-f3dc-4c0d-81f3-33553ddf198b.png)

**Comment by YunSumin** [comment]
보내주신 내용을 확인해 본 결과 모델의 Y축 값과 Z축 값이 반대로 반환되는 현상을 확인하였습니다.
금일 업데이트를 통해 기능 수정하였습니다.

아울러 금번 업데이트에서 고스트 심볼 API 구성이 개편되어
샌드박스에 개편 사항이 반영되었으니 참조 부탁 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit
