### ISSUE TITLE
반경 그리는 기능이 있는지 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#11]
안녕하세요. 바이브컴퍼니입니다.

보통 반경 측정같은거 할 때 사용되는...
반경(원) 그리는 기능이 있는지 문의합니다.

원 그리는 api는 존재하는거 확인했습니다.
거리측정, 면적측정처럼 마우스 이벤트에 의해 반경을 그리는 기능이 있는지 알고 싶습니다.
(중심점을 마우스로 클릭하고 드래그하던가 마우스를 움직이면 해당 반경만큼 원이 그려지는 기능)

그럼,...

**Comment by SeongRyong-Choi** [comment]
반경 측정 기능 추가하였습니다. 수정 된 새 엔진 적용 부탁드립니다.

샌드박스에도 적용하였으며 아래 링크로 접속하면 확인하실 수 있습니다.

http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=analysis_measure_radius
