### ISSUE TITLE
sandbox의 라인 그리는 방법 차이 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#110]
안녕하세요. 바이브컴퍼니입니다.

sandbox에 라인 생성하는 예제가 2개 있습니다.

이 둘의 차이가 궁금합니다.

두 가지 방법 모두로 구현해 보았는데 선의 품질(?) 차이가 있더라구요.

용도에 따라 다르게 사용해야 하는건가요?

![image](https://user-images.githubusercontent.com/38479834/140262395-685e2576-6a51-4889-8013-8aec540f7ccf.png)

**Comment by hjaejae** [comment]
첫 번째 샘플과 두 번째 샘플의 차이는 단지 API 사용에 있습니다.
품질에는 다른 점이 없구요

첫 번째는 파라미터를 이용한 생성 방법이고
두 번째는 Json형태의 객체를 넘겨 라인을 생성하는 방법입니다.

**Comment by YunSumin** [comment]
본 이슈를 통해 개발 시 혼선이 발생할 수 있다고 판단되어 첫번째 예제는 샌드박스에서 삭제되었습니다.
개선 된 두번째 샘플의 API 사용을 부탁 드립니다.
