### ISSUE TITLE
중앙을 기준을 회전시 카메라 흔들림

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#111]
안녕하세요!
http://sandbox.dtwincloud.com/code/main.do?id=camera_move_round_path
기능을 이용중입니다. 카메라가 회전하면서 세로로 흔들리는데.. 혹시 개선안이 있을까요...?
감사합니다!

**Comment by YunSumin** [comment]
안녕하세요,
카메라 회전 이동 실행 시 JSCamera의 setAnimationSpeed API 를 사용하셔서
카메라 이동 속도를 느림으로 설정하시면 떨림 현상을 보정하실 수 있습니다.
(기본 이동 속도 값은 10 입니다)

해당 문제를 보완하여 샌드박스 코드를 수정하였습니다.
아래 샌드박스 URL 참조 부탁드립니다.

http://sandbox.dtwincloud.com/code/main.do?id=camera_move_round_path

감사합니다.

**Comment by YunSumin** [comment]
카메라 회전 이동 관련하여 API가 개편되어 안내 드립니다.

금일 업데이트를 통해 카메라 이동 속도 설정 API가 추가되었습니다.
```
Module.getViewCamera().SetAutoMoveSpeed(1.0);
```

0.0에서 1.0 사이 부동소수점 값으로 설정이 가능하며 값이 클 수록 이동 속도가 빨라집니다.
위 API가 새로 추가 됨에 따라,  기존 안내 드렸던
- JSCamera의 setAnimationSpeed
- JSCamera의 setAutoMoveWaitFrame

는 동작에 활용되지 않으니 활용하시는 코드에서 제외 부탁 드립니다.

위 변경 사항에 따라 샌드박스 코드가 업데이트 되었습니다.
실제 동작은 아래 샌드박스 URL 참조 부탁 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=camera_move_round_path

감사합니다.
