### ISSUE TITLE
강낭콩 모양의 폴리곤 표현이 가능한지 궁금합니다.

### ISSUE THREAD

**Issue by giwon1130** [EgisCorp/XDWorld#112]
![image (1)](https://user-images.githubusercontent.com/92919334/140462654-ca6bd782-a809-460b-8d57-702eddbff978.png)

강낭콩 모양의 폴리곤 표현이 가능한지 궁금합니다.

**Comment by YunSumin** [comment]
위 형상 좌표를 적용하신 폴리곤 객체를 생성하여 가시화 할 수 있을 것 같습니다.
버텍스는 가급적 작은 수로 지정하시는 것이 속도 및 최적화에 좋습니다.

아래 예제 참조 부탁 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_polygon_create
http://sandbox.dtwincloud.com/code/main.do?id=object_polygon_color

**Comment by loeaf** [comment]
혹시 wms로 서비스되는 타일에 alpha 값을 줄 수 있을까요?
