### ISSUE TITLE
Line 그리기 오작동 문의

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#113]
안녕하세요
http://sandbox.dtwincloud.com/code/main.do?id=object_line_Json
여기에 있는 라인으로 아래 구역을 그리니... 끝이 얇아지는 현상이 나옵니다

어떻게 해결이 가능한가요??
    const data = {
      coordinates,
      type: 1,											// 그라데이션 선 생성
      union: true,										// 지형 결합 유무
      depth: true,										// 오브젝트 겹침 유무
      color: new Module.JSColor(200, 255, 0, 100),		// fill ARGB 설정
      strokecolor: new Module.JSColor(200, 100, 0, 255),	// stroke ARGB 설정
      strokewidth: 6.0,									// stroke 굵기 설정
      width: 10,											// 선 굵기( type 3 일떄 width 1로 설정 시 화살표 X)
    };
    
![image](https://user-images.githubusercontent.com/3315478/140607091-19d1ce78-0d8e-407d-8571-75a0929d1897.png)

**Comment by loeaf** [comment]
버텍스 정보입니다.
감사합니다
'[{"lon":127.173448289742,"lat":37.6185091128109,"alt":0},{"lon":127.173423173383,"lat":37.6185858603701,"alt":0},{"lon":127.173416447772,"lat":37.6186082681712,"alt":0},{"lon":127.173336494727,"lat":37.6186083856414,"alt":0},{"lon":127.173292395415,"lat":37.6186366512348,"alt":0},{"lon":127.173270120445,"lat":37.6187273657243,"alt":0},{"lon":127.173251896463,"lat":37.6188186505764,"alt":0},{"lon":127.173237746329,"lat":37.6189103913653,"alt":0},{"lon":127.173227687796,"lat":37.6190024730938,"alt":0},{"lon":127.173221733485,"lat":37.6190947803364,"alt":0},{"lon":127.173219890878,"lat":37.619187197385,"alt":0},{"lon":127.17322099488,"lat":37.6196630482259,"alt":0},{"lon":127.173261115833,"lat":37.6196948440162,"alt":0},{"lon":127.173334338941,"lat":37.6196947364817,"alt":0},{"lon":127.173334569032,"lat":37.6197938446856,"alt":0},{"lon":127.173261345827,"lat":37.6197939522205,"alt":0},{"lon":127.173221372632,"lat":37.6198258655972,"alt":0},{"lon":127.173223520263,"lat":37.620751505231,"alt":0},{"lon":127.173303763379,"lat":37.6208150967814,"alt":0},{"lon":127.173336939937,"lat":37.6208150480518,"alt":0},{"lon":127.174601142743,"lat":37.6208131842479,"alt":0},{"lon":127.174648478369,"lat":37.6208125705527,"alt":0},{"lon":127.174695771987,"lat":37.6208108700626,"alt":0},{"lon":127.174742984165,"lat":37.6208080841953,"alt":0},{"lon":127.174790075541,"lat":37.6208042152737,"alt":0},{"lon":127.174837006853,"lat":37.6207992665234,"alt":0},{"lon":127.174892126989,"lat":37.6207920437447,"alt":0},{"lon":127.174946905785,"lat":37.6207833315614,"alt":0},{"lon":127.175001279649,"lat":37.6207731400874,"alt":0},{"lon":127.175055185458,"lat":37.6207614811538,"alt":0},{"lon":127.175108560635,"lat":37.6207483682952,"alt":0},{"lon":127.175161343217,"lat":37.6207338167343,"alt":0},{"lon":127.175213471931,"lat":37.6207178433637,"alt":0},{"lon":127.175264886262,"lat":37.6207004667266,"alt":0},{"lon":127.175315526523,"lat":37.6206817069952,"alt":0},{"lon":127.175365333929,"lat":37.6206615859475,"alt":0},{"lon":127.175414250659,"lat":37.6206401269414,"alt":0},{"lon":127.175462219927,"lat":37.6206173548884,"alt":0},{"lon":127.175509186049,"lat":37.620593296224,"alt":0},{"lon":127.175555094503,"lat":37.6205679788775,"alt":0},{"lon":127.175599891997,"lat":37.620541432239,"alt":0},{"lon":127.175643526526,"lat":37.620513687126,"alt":0},{"lon":127.175685947439,"lat":37.6204847757471,"alt":0},{"lon":127.175727105491,"lat":37.6204547316646,"alt":0},{"lon":127.175766952905,"lat":37.6204235897559,"alt":0},{"lon":127.175805443425,"lat":37.6203913861727,"alt":0},{"lon":127.175842532369,"lat":37.620358158299,"alt":0},{"lon":127.175878176686,"lat":37.6203239447082,"alt":0},{"lon":127.175912334997,"lat":37.6202887851174,"alt":0},{"lon":127.175944967654,"lat":37.6202527203423,"alt":0},{"lon":127.175976036774,"lat":37.620215792249,"alt":0},{"lon":127.176005506295,"lat":37.6201780437058,"alt":0},{"lon":127.176033342008,"lat":37.6201395185336,"alt":0},{"lon":127.176059511603,"lat":37.6201002614546,"alt":0},{"lon":127.176083984704,"lat":37.6200603180404,"alt":0},{"lon":127.176848600169,"lat":37.6187563888867,"alt":0},{"lon":127.175032990976,"lat":37.6181299926206,"alt":0},{"lon":127.175003825383,"lat":37.6181194430156,"alt":0},{"lon":127.174975142639,"lat":37.6181080866256,"alt":0},{"lon":127.174946978004,"lat":37.6180959374107,"alt":0},{"lon":127.174919366098,"lat":37.6180830103052,"alt":0},{"lon":127.174892340864,"lat":37.6180693212,"alt":0},{"lon":127.174865935521,"lat":37.6180548869224,"alt":0},{"lon":127.174840182529,"lat":37.6180397252158,"alt":0},{"lon":127.174815113544,"lat":37.6180238547178,"alt":0},{"lon":127.173933890801,"lat":37.6174456097792,"alt":0},{"lon":127.173554522794,"lat":37.6180339195599,"alt":0},{"lon":127.173505103771,"lat":37.6181179105078,"alt":0},{"lon":127.173459466029,"lat":37.6182032446164,"alt":0},{"lon":127.173417667165,"lat":37.618289814212,"alt":0},{"lon":127.173379759935,"lat":37.6183775100615,"alt":0},{"lon":127.173345792184,"lat":37.6184662215107,"alt":0},{"lon":127.173387010861,"lat":37.6185092028656,"alt":0},{"lon":127.173448289742,"lat":37.6185091128109,"alt":0},{"lon":127.173448289742,"lat":37.6185091128109,"alt":0},{"lon":127.173423173383,"lat":37.6185858603701,"alt":0},{"lon":127.173416447772,"lat":37.6186082681712,"alt":0},{"lon":127.173336494727,"lat":37.6186083856414,"alt":0},{"lon":127.173292395415,"lat":37.6186366512348,"alt":0},{"lon":127.173270120445,"lat":37.6187273657243,"alt":0},{"lon":127.173251896463,"lat":37.6188186505764,"alt":0},{"lon":127.173237746329,"lat":37.6189103913653,"alt":0},{"lon":127.173227687796,"lat":37.6190024730938,"alt":0},{"lon":127.173221733485,"lat":37.6190947803364,"alt":0},{"lon":127.173219890878,"lat":37.619187197385,"alt":0},{"lon":127.17322099488,"lat":37.6196630482259,"alt":0},{"lon":127.173261115833,"lat":37.6196948440162,"alt":0},{"lon":127.173334338941,"lat":37.6196947364817,"alt":0},{"lon":127.173334569032,"lat":37.6197938446856,"alt":0},{"lon":127.173261345827,"lat":37.6197939522205,"alt":0},{"lon":127.173221372632,"lat":37.6198258655972,"alt":0},{"lon":127.173223520263,"lat":37.620751505231,"alt":0},{"lon":127.173303763379,"lat":37.6208150967814,"alt":0},{"lon":127.173336939937,"lat":37.6208150480518,"alt":0},{"lon":127.174601142743,"lat":37.6208131842479,"alt":0},{"lon":127.174648478369,"lat":37.6208125705527,"alt":0},{"lon":127.174695771987,"lat":37.6208108700626,"alt":0},{"lon":127.174742984165,"lat":37.6208080841953,"alt":0},{"lon":127.174790075541,"lat":37.6208042152737,"alt":0},{"lon":127.174837006853,"lat":37.6207992665234,"alt":0},{"lon":127.174892126989,"lat":37.6207920437447,"alt":0},{"lon":127.174946905785,"lat":37.6207833315614,"alt":0},{"lon":127.175001279649,"lat":37.6207731400874,"alt":0},{"lon":127.175055185458,"lat":37.6207614811538,"alt":0},{"lon":127.175108560635,"lat":37.6207483682952,"alt":0},{"lon":127.175161343217,"lat":37.6207338167343,"alt":0},{"lon":127.175213471931,"lat":37.6207178433637,"alt":0},{"lon":127.175264886262,"lat":37.6207004667266,"alt":0},{"lon":127.175315526523,"lat":37.6206817069952,"alt":0},{"lon":127.175365333929,"lat":37.6206615859475,"alt":0},{"lon":127.175414250659,"lat":37.6206401269414,"alt":0},{"lon":127.175462219927,"lat":37.6206173548884,"alt":0},{"lon":127.175509186049,"lat":37.620593296224,"alt":0},{"lon":127.175555094503,"lat":37.6205679788775,"alt":0},{"lon":127.175599891997,"lat":37.620541432239,"alt":0},{"lon":127.175643526526,"lat":37.620513687126,"alt":0},{"lon":127.175685947439,"lat":37.6204847757471,"alt":0},{"lon":127.175727105491,"lat":37.6204547316646,"alt":0},{"lon":127.175766952905,"lat":37.6204235897559,"alt":0},{"lon":127.175805443425,"lat":37.6203913861727,"alt":0},{"lon":127.175842532369,"lat":37.620358158299,"alt":0},{"lon":127.175878176686,"lat":37.6203239447082,"alt":0},{"lon":127.175912334997,"lat":37.6202887851174,"alt":0},{"lon":127.175944967654,"lat":37.6202527203423,"alt":0},{"lon":127.175976036774,"lat":37.620215792249,"alt":0},{"lon":127.176005506295,"lat":37.6201780437058,"alt":0},{"lon":127.176033342008,"lat":37.6201395185336,"alt":0},{"lon":127.176059511603,"lat":37.6201002614546,"alt":0},{"lon":127.176083984704,"lat":37.6200603180404,"alt":0},{"lon":127.176848600169,"lat":37.6187563888867,"alt":0},{"lon":127.175032990976,"lat":37.6181299926206,"alt":0},{"lon":127.175003825383,"lat":37.6181194430156,"alt":0},{"lon":127.174975142639,"lat":37.6181080866256,"alt":0},{"lon":127.174946978004,"lat":37.6180959374107,"alt":0},{"lon":127.174919366098,"lat":37.6180830103052,"alt":0},{"lon":127.174892340864,"lat":37.6180693212,"alt":0},{"lon":127.174865935521,"lat":37.6180548869224,"alt":0},{"lon":127.174840182529,"lat":37.6180397252158,"alt":0},{"lon":127.174815113544,"lat":37.6180238547178,"alt":0},{"lon":127.173933890801,"lat":37.6174456097792,"alt":0},{"lon":127.173554522794,"lat":37.6180339195599,"alt":0},{"lon":127.173505103771,"lat":37.6181179105078,"alt":0},{"lon":127.173459466029,"lat":37.6182032446164,"alt":0},{"lon":127.173417667165,"lat":37.618289814212,"alt":0},{"lon":127.173379759935,"lat":37.6183775100615,"alt":0},{"lon":127.173345792184,"lat":37.6184662215107,"alt":0},{"lon":127.173387010861,"lat":37.6185092028656,"alt":0},{"lon":127.173448289742,"lat":37.6185091128109,"alt":0},{"lon":127.173448289742,"lat":37.6185091128109,"alt":0}]'

**Comment by HyunSeongKil** [comment]
참고
sandbox에서 테스트한 결과

![image](https://user-images.githubusercontent.com/38479834/140688799-b1dc445b-5bc5-4c03-816c-6d632dec1048.png)

**Comment by loeaf** [comment]
최옥규 차장님의 가이드대로 처리하기로 했습니다 감사합니다
