### ISSUE TITLE
드라이빙 결함 문의

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#115]
안녕하세요
http://sandbox.dtwincloud.com/code/main.do?id=object_line_interpolate_curved
1. 최신 버전으로 업데이트 되면서 마우스 left 이벤트를 줄때 자동차 위치가 초기화 되는 결함이 있습니다
2. 샌드캐슬에 대하여 마우스 이중 클릭에 대한 예제가 잘려있습니다 
![image](https://user-images.githubusercontent.com/3315478/140610616-e56eb99d-1c32-4db1-abcd-0a6c99aa8797.png)
![image](https://user-images.githubusercontent.com/3315478/140610506-48cd5f55-0b22-48fb-9a6e-15e23cfbad10.png)

감사합니다

**Comment by YunSumin** [comment]
안녕하세요,

안내 해 주신 사항을 참조하여
move API 호출 시 고스트 심볼 위치가 갱신 되지 않고 기존 자리에 머무는 것을 확인,
해당 기능을 수정 후 엔진 파일을 업데이트 하였습니다.

또한 샌드박스에서는 마우스 클릭 Down/Move/Up은 오브젝트 뷰 방향 조정,
키 버튼 Press Down/Up 이벤트는 오브젝트 이동 기능이 동작하도록 구성되어 있습니다.
기타 다른 이벤트에 대한 조작은 구현하시는 기능에 맞춰 추가 구현이 필요할 것 같습니다.

금일(2021-11-10) 릴리즈 된 엔진 파일로 업데이트 부탁 드립니다.

감사합니다.

**Comment by loeaf** [comment]
안녕하세요! 터레인에 자동차가 반쯤 파묻힙니다... 높이를 줘도 초기화가 되는데 개선이 가능할까요?

**Comment by YunSumin** [comment]
setBasePoint API를 사용하여 모델 중점을 조정하실 수 있습니다.
(디폴트 위치는 모델 정 중앙입니다.)

```
object.setBasePoint(0.0, -0.2, 0.0);
```
중점을 모델의 아랫부분에 두시면 모델을 위로 띄우실 수 있습니다.
