### ISSUE TITLE
객체 미선택 발생하는 이벤트 있나요?

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#116]
안녕하세요. 바이브컴퍼니입니다.

객체 선택 관련 문의입니다.

객체 선택시 이벤트가 발생하는데.... 
객체 미선택시(근까....객체가 아닌 지도상의 엄한곳을 선택했을 때) 발생하는 이벤트는 어떻게 잡을 수 있나요?

객체가 선택되지 않았을 때 다른 처리를 하고 싶어서요...

Fire_EventUnSelectedObject ...뭐 이런거 있으면 좋겠는데...

![image](https://user-images.githubusercontent.com/38479834/140695868-7ccfd942-59c6-4d3b-b04d-00304332e4a3.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

객체 미선택 이벤트는 웹에서 기존 API로 구현가능하기 때문에 엔진내부에 따로 기능이 없습니다.

웹에서 mouseup 이벤트 발생시 Module.getMap().getSelectObject(); (null: 선택객체 없음) 를 활용하시면 될것같습니다.

감사합니다.
