### ISSUE TITLE
setMinDistance 최댓값문제

### ISSUE THREAD

**Issue by Kiwoohyun2** [EgisCorp/XDWorld#117]
레이어를 생성함에 있어서 setMinDistance 를 설정해줄 때 setMinDistance 값이 3001이상이 되면 안먹는 현상이 있는데 확인부탁드립니다

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

우선 확인해주셔야할 사항이 2가지 있습니다.

1. setMinDistance(); 반환값이 false인지 true인지 확인이 필요합니다.
2. getMaxDistance(); 를 사용하여 현재 설정된 MaxDistance를 확인해주시기 바랍니다.

엔진 내부에서 MinDistance를 MaxDistance보다 크게 설정하려하면 false를 반환합니다.

확인부탁드립니다.

**Comment by Kiwoohyun2** [comment]
<setMinDistance 값이 3000 이하일때>
  
![image](https://user-images.githubusercontent.com/82200069/141030343-8e8c7728-9deb-4a2a-9462-e9434ba3c1a0.png)

 <setMinDistance 값이 3001 이상일때>
![image](https://user-images.githubusercontent.com/82200069/141030375-f6d23d22-09ef-4f52-b974-41f7e473255b.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

엔진 내부에서 MinDistance가 MaxDistance보다 크게 설정하려하면 false를 반환합니다.

- MinDistance의 초기값: 1
- MaxDistance의 초기값: 3000
위와 같이 설정되어 있는 상황에서 setMinDistance(3001); 로 할 경우 현재 MaxDistance의 값이 3000이기 때문에 적용되지 않는 현상인것 같습니다. 

우선 setMaxDistance(18000);  로 MaxDistance 를 설정하신 후 setMinDistance(3001); 로 MinDistance 를 설정하시면 될것같습니다.

**Comment by Kiwoohyun2** [comment]
감사합니다
