### ISSUE TITLE
폴리곤 그라데이션 remove 기능 확인 요청

### ISSUE THREAD

**Issue by giwon1130** [EgisCorp/XDWorld#118]
![image](https://user-images.githubusercontent.com/92919334/140845013-c59592d6-6b45-4e12-b8b1-473193ef6360.png)

폴리곤 그라데이션 기능은 create기능 이외의 remove기능은 없는지 궁금합니다!

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 

샌드박스 예제를 기준으로 말씀드리겠습니다. 

폴리곤 생성 후 레이어에 삽입하기 때문에 결국 레이어에 삽입된 객체를 삭제하면 됩니다.

레이어에 삽입된 객체를 삭제하는 API는 다음과 같습니다.

Layer.**removeAtObject**(Object);

<샌드박스 예제 기준>
colorPolygonlayer.removeAtObject(colorPolygon);
lineLayer.removeAtObject(baseLine);

**Comment by giwon1130** [comment]
감사합니다:)
