### ISSUE TITLE
객체선택 api 에 관한 질문드립니다

### ISSUE THREAD

**Issue by Kiwoohyun2** [EgisCorp/XDWorld#119]
http://sandbox.dtwincloud.com/code/main.do?id=object_select

해당 '객체선택' api에서 객체를 선택했을 때 object Key, lon, lat, alt 값을 반환받습니다

반대로 object Key를 보내면 그object Key에 해당하는 객체 선택이 되는 기능이 가능한지 궁금합니다

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

Module.getMap().setSelectObject(object);  API를 사용하시면 해당 기능을 할 수 있습니다.

아래는 샘플코드입니다.

var layerList = new Module.JSLayerList(false);
var layer = layerList.nameAtLayer("facility_build");
var object = layer.keyAtObject("263500000000000005230205");

if(object.getSelectable()) {  // object가 선택가능 상태이면
     Module.getMap().setSelectObject(object);   // object 선택
}

**Comment by Kiwoohyun2** [comment]
답변 감사합니다.  위코드를 실행하고 아래와 같은 deletelayer 함수를 타면  해당 layer만 지워지는 게 아닌 객체선택됐던것도 풀리는 현상이 있는데 확인부탁드립니다!
new Module.JSLayerList(true).delLayerAtName(layerName);

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

delLayerAtName 시 해당 layer가 아닌 객체의 선택상태가 해제되는 현상을 수정하여 엔진업데이트 하였습니다.

Git에서 새로 엔진을 받으셔서 적용하시면 감사하겠습니다.

추가적으로 object Key로 객체를 안보이게 하거나 삭제하는 API는 다음과 같습니다.

1. 객체 가시화 off
var layerList = new Module.JSLayerList(false);
var layer = layerList.nameAtLayer(레이어명);
var object = layer.keyAtObject(객체키값);
object.setVisible(false);	// true: 가시화 on, false: 가시화 off

2. 객체 삭제
var layerList = new Module.JSLayerList(true);
var layer = layerList.nameAtLayer(레이어명);
layer.removeAtKey(객체키값);

감사합니다.
