### ISSUE TITLE
wms 결함?

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#12]
안녕하세요. 바이브컴퍼니입니다.

제공해 주신 wms 적용했습니다.

geoserver에 스타일 적용했습니다.
scale별로 심볼이 변경되도록 스타일을 적용 했습니다.

코딩 후 지도이동, 확대/축소를 할 때 아래 이미지와 같은 현상이 발생합니다.
일부는 scale별 심볼이 적용되었고, 일부는 적용되지 않는 현상?

확인해 주시기 바랍니다.

![image](https://user-images.githubusercontent.com/38479834/120257123-97bf2180-c2ca-11eb-8770-ef17cff4a9a2.png)

![image](https://user-images.githubusercontent.com/38479834/120257351-0c925b80-c2cb-11eb-8aac-03ea2f0142fa.png)

**Comment by YangHeeBong** [comment]
카메라 거리에 따른 출력 Level 이 달라 생기는 현상입니다.

![그림1](https://user-images.githubusercontent.com/82924515/120267691-6ef55700-c2df-11eb-95cb-9438c5dc5989.png)

윗 이미지와 같이 카메라 거리에 따른 WMS 요청 Level 이 다름으로 결함이 아닌 정상적인 결과 입니다.

위와 같은 방식은 3D에서 자주 사용되는 기술로 가시화 성능 및 네트워크 요청 수를 줄여 자원 관리에 용이 합니다.

**Comment by HyunSeongKil** [comment]
흠.....
그렇다고 해도 뭔가...쫌....이상합니다.





https://user-images.githubusercontent.com/38479834/120269039-fb087e00-c2e1-11eb-9ce7-9c1f14a0db87.mp4




https://user-images.githubusercontent.com/38479834/120269036-f93eba80-c2e1-11eb-91f7-0a37bac0e933.mp4

**Comment by HyunSeongKil** [comment]
이게 정상이라고 하면....

이런 현상이 발생하지 않게 하려면 제가 어떻게 구현해야 하나요?


일반 사용자가 볼때는....
이상한 현상으로 볼 수 있을것 같네요,.

**Comment by YangHeeBong** [comment]
위와 같은 기술을 3D에서 LOD 기술이라고 합니다.
이 기술은 OpenLayer에서 사용되고 있으면 비슷한 형태로 나타나고 있는데 다른 WMS를 보면 상위 레벨부터 하위 레벨 까지 유사 색상으로 구성된 이미지를 제공해 이질감 없이 서비스를 하고 있습니다.

**Comment by HyunSeongKil** [comment]
알겠습니다.
