### ISSUE TITLE
맵 움직임을 감지하는 이벤트 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#120]
안녕하세요!

지도를 드래그하여 이동하거나 휠로 확대, 축소 등

지도가 움직일 때마다 발생하는 이벤트가 있는지 문의드립니다.

마우스 무브, 휠 등 마우스 이벤트 보다 더 발생빈도가 높은 이벤트가 필요하여 문의드립니다!

**Comment by YunSumin** [comment]
안녕하세요,

엔진에서 자체 이벤트를 다수 발생 하게 되면
이벤트 발생에 연산이 집중되어 렌더링 시 프레임이 떨어지는 현상이 나타나므로
대부분 마우스와 키보드 이벤트를 활용하시는 것을 권장하고 있습니다.

가능한 엔진 자체 이벤트 사용보다 외부 이벤트 사용을 부탁 드립니다.
