### ISSUE TITLE
마우스 특정 영역 zoom out, zoom in 및 tilt 제어 방법

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#121]
안녕하세요 
구현하고 싶은 기능이 2가지 있습니다
1. zoom 제어
마우스 휠스크롤 제어했을때 땅밑으로 들어가는 현상과 너무 멀리가는 현상을 막고싶습니다.
setZoomPrevent(10, 5000) => 10 과 5000 고도 사이로만 줌 가능...이런 기능 을 구현하고 싶은데 어떤 함수를 써야하나요...?
![image](https://user-images.githubusercontent.com/3315478/141073035-2cbae653-0584-46d2-8777-db5e37085285.png)

2. tilt 제어
땅과 가까이 갔을때 사람의 시점에서 카메라 tilt 값을 -10~10 정도로 제어해서 위쪽을 바라보고 싶은데... tilt 값이 10으로 제어 되있던데.. 해당 기능도 역시 어떤 기능을 통해서 구현해야하나요..?
![image](https://user-images.githubusercontent.com/3315478/141073216-38039ea0-d2a7-4bf7-b4b2-19d851a3fb1f.png)

감사합니다!

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

1. 카메라가 지형아래로 내려가거나 지형아래에서 줌을 했을 경우 지구반대편이나 멀리 이동되는 현상이 발생되는것으로 파악됩니다. 이럴경우 카메라가 지형아래로 내려가지 못하도록 설정하는 API가 있습니다.
Module.getViewCamera().setPermitUnderGround(false);   // true: 지형아래 허용, false: 지형아래 허용하지 않음

2. 카메라의 Tilt 조절 API를 사용하시면 될것같습니다.
Module.getViewCamera().setTilt(-10);

감사합니다.
