### ISSUE TITLE
라인 보간 문의

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#122]
지형 만이 아니라 xdserver로 업로드 된 건물도 포함해서 작동이 가능한가요?

http://sandbox.dtwincloud.com/code/main.do?id=object_line_interpolate_curved

**Comment by YunSumin** [comment]
안녕하세요,

해당 샘플은 코드 내용 중 
```
map.getTerrHeight(pos.x, pos.y)
```
지형 고도를 반환하는 API 값을 고도 값으로 사용하므로
건물, 고스트심볼 객체 등 레이어 오브젝트는 계산 시 고려하지 않고 있습니다.
