### ISSUE TITLE
멀티 라인 색상 오작동 문의

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#123]
색깔이 이상하게 나옵니다... 감사합니다
![image](https://user-images.githubusercontent.com/3315478/141415041-eaf99087-b248-415d-a69d-c18cc89445c5.png)
![image](https://user-images.githubusercontent.com/3315478/141415055-b4c3cdeb-999e-45ea-bc1c-4fa8c57987f2.png)
function createOutLineJson(_coordinates) {
	let data = {
		coordinates: _coordinates,
		type: 1,											// 그라데이션 선 생성 		
		union: false,										// 지형 결합 유무
		depth: true,										// 오브젝트 겹침 유무
		color: new Module.JSColor(114, 176, 32, 255),		// fill ARGB 설정
		strokecolor: new Module.JSColor(200, 100, 0, 255),	// stroke ARGB 설정
		strokewidth: 6.0,									// stroke 굵기 설정
		width: 10,											// 선 굵기( type 3 일떄 width 1로 설정 시 화살표 X)
	}
	return data;
}
http://sandbox.dtwincloud.com/code/main.do?id=object_line_Json

**Comment by avamk2** [comment]
안녕하세요
색상에 대한 기준이 RGBA로 생각하시고 작성하신거 같습니다.
엔진쪽은 모든 색상 기준이 ARGB로 통일되어 있습니다.
new Module.JSColor( Alpha, Red, Green, Blue )

**Comment by loeaf** [comment]
감사합니다!
