### ISSUE TITLE
터레인 아래로 카메라가 내려가지 않게 하는 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#124]
안녕하세요.

**터레인 아래로 카메라가 내려가지 않게 하는 방법 문의합니다.**

setLimitAltitude()를 찾아봤는데
이건 터레인 높이와 관계없이 높이 제한하는 것으로 알고 있습니다.

그럼, ...

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

카메라가 지형아래로 내려가지 못하도록 설정하는 API입니다.

Module.getViewCamera().setPermitUnderGround(false); // true: 지형아래 허용, false: 지형아래 허용하지 않음

감사합니다.
