### ISSUE TITLE
WMS 활용하여 layer표출시 옵션 문의입니다.

### ISSUE THREAD

**Issue by giwon1130** [EgisCorp/XDWorld#125]
WMTS 처럼 타일로 wms를 받고 싶은데 
wms 옵션에서 tiled 설정을 하면 되는것으로 알고 있습니다.
몇번의 테스트를 해보았는데 tilde옵션이 적용이 안됩니다. 

혹시 tiled옵션을 주는 방법이 있을까요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

tiled 옵션을 파라미터에 추가하는 방법은 다음과 같습니다.

http://sandbox.dtwincloud.com/code/main.do?id=layer_wms

위 샘플에서 parameters 에 TILED: true 를 추가하시면 됩니다.

	let slopeoption = {
		url: strUrl,
		layer: strLayer,
		minimumlevel: numMinlevel,
		maximumlevel: numMaxlevel,
		tilesize: numTileSize,
		crs: strCrs,
		parameters: {
			version: strVersion,
			**TILED: true**
		}
	};	

감사합니다.

**Comment by mykim1024** [comment]
인코딩문제는 해결됐습니다! 위 사진처럼 요청했는데 실제 파라미터값이 다르게 넘어가는 경우는 혹시 어떻게 해결해야될까요?
![image](https://user-images.githubusercontent.com/109206050/205833294-bba8a3ea-22f5-46a2-a6e4-397de42839d1.png)
![image](https://user-images.githubusercontent.com/109206050/205833315-6e689ccb-1d1b-4a6f-ab61-083b999b7bc5.png)
