### ISSUE TITLE
Module.setvisibleRange의 두 번째 파라미터 속성

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#126]
안녕하세요. Module.setVisibleRange() API에서 
첫 번째 파라미터는 레이어명, 세 번째 파라미터는 가시화가 될 수 있는 거리를 타나내는 걸로 알고 있는데,
두 번째 파라미터는 무슨 기능을 하는지 알고 싶습니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

Module.setVisibleRange() API 파라미터 정보입니다.

첫번째: 레이어명
두번째: LOD ratio
세번째: 가시화 최대 거리

**Comment by KIMSEONOK** [comment]
LOD ratio의 최대 최소 범위를 좀 알 수 있을까요?

**Comment by SeongRyong-Choi** [comment]
LOD ratio는 카메라거리에 따른 LOD를 설정하는 값이며 0 이상의 실수값을 입력받습니다. 

0 일 경우에는 가시화되지 않으며 현재 엔진에서 초기값은 0.7 입니다.

너무 멀리있는 객체까지 가시화하면 불필요한 랜더링으로 자원낭비가 발생합니다.

그래서 보통 0.7 ~ 2.5 사이의 값을 사용하고 있습니다.

하지만 개개인의 의견이 다르기에 값을 변경하시면서 원하시는 값을 찾으시면 될것같습니다.

감사합니다.
