### ISSUE TITLE
지형에 붙는 폴리곤 생성하는 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#127]
안녕하세요.

지형에 붙는 폴리곤 생성하는 방법 문의합니다.

sandbox에 폴리곤 생성하는 예제가 여러개 있는데... 어떤걸 봐야할지 모르겠네요.
제일 비슷한게 
http://sandbox.dtwincloud.com/code/main.do?id=object_polygon_rtt_image_changing
이거 같은데...이미지 없이 색으로 표시하고 싶습니다.

그럼, ...

**Comment by avamk2** [comment]
안녕하세요 
지형 높이값 보간에 대해서는 https://github.com/EgisCorp/XDWorld/issues/23#issuecomment-855717881 내용을 확인해 주세요

**Comment by HyunSeongKil** [comment]
음..... 높이값  보간 질문이 아닌데...ㅡㅡ;;

RTT 라고 하는거...
그걸 폴리곤에 적용하고 싶은건데....

**Comment by HyunSeongKil** [comment]
유선으로 문의하여 답을 들었습니다.
