### ISSUE TITLE
고스트 심볼 문의

### ISSUE THREAD

**Issue by Kiwoohyun2** [EgisCorp/XDWorld#128]
http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit

위 url에서 
 position alt(높이) 값의 기준은 객체의 밑부분인지 중심부분인지 기준과 그 부분에서도 중심점의 기준인지 궁금합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

현재 고스트 심볼 객체는 객체 중심을 기준으로 높이값을 적용하고있습니다.

감사합니다.

**Comment by Kiwoohyun2** [comment]
감사합니다
