### ISSUE TITLE
3차원건물 hide기능 문의

### ISSUE THREAD

**Issue by giwon1130** [EgisCorp/XDWorld#129]
3차원 건물을 create하고 remove하는 기능을 사용하여, 3차원 건물을 컨트롤하고 있습니다.
3차원 건물을 remove하고 다시 create하는데 너무 많은 시간이 소요되는 문제가 있습니다.
혹시 3차원건물을 제거하지 않고, 숨기는(hide)기능이 있는지 문의드립니다.
remove 예) Module.XDEMapRemoveLayer(layer);

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

layer 클래스에 setVisible() API를 사용하시면 해당 기능을 할 수 있습니다.

아래는 샘플코드입니다.

var layerList = new Module.JSLayerList(false);
var layer = layerList.nameAtLayer("facility_build");
layer.setVisible(false);   // 레이어 vidible off
