### ISSUE TITLE
moveLonLatBoundary() 확인 요청

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#13]
안녕하세요. 바이브컴퍼니입니다.

moveLonLatBoundary()를 사용하는데...
어느 경우에는 위치로 이동하는데 어느 경우에는 이동하지 않습니다.

브라우저>개발자도구>콘솔에서 직접 코딩했는데 이동하지 않습니다.
sandbox에서 해당 코드를 추가하고 실행했는데도 이동하지 않습니다.

아래 이미지에서 빨간색 네모부분 확인 요청합니다.

![image](https://user-images.githubusercontent.com/38479834/120312327-8c441880-c313-11eb-84f7-13fe589e552f.png)

**Comment by SeongRyong-Choi** [comment]
말씀하신 내용 확인하여 정상적으로 동작하도록 엔진이 수정되었습니다.
수정 된 새 엔진 적용 부탁드립니다.

**Comment by HyunSeongKil** [comment]
확인했습니다.
