### ISSUE TITLE
POI 클릭 관련 문의입니다

### ISSUE THREAD

**Issue by wiserabi** [EgisCorp/XDWorld#130]
Canvas 위에 있는 POI 객체를 클릭하는 방법에 대해 문의 드립니다. 
POI 객체를 클릭하면 클릭한 POI의 정보가 나타나게 만들고 싶습니다.
이를 위해 어떤 이벤트를 사용해야 하는지 궁금합니다.
또한 그 예시가 있으면 더 좋을 것 같습니다.

**Comment by avamk2** [comment]
안녕하세요 
객체 선택에 관련된 샘플은 : http://sandbox.dtwincloud.com/code/main.do?id=object_select

객체를 마우스로 선택하게 되면 선택된 객체의 이벤트 Fire_EventSelectedObject 가 발생하며 이벤트 파라메터에는 등록된 객체의 레이어 명과 키 값이 포함되어 있어서 생성된 객체를 찾을 수 있습니다.

**Comment by wiserabi** [comment]
답변 감사합니다!
