### ISSUE TITLE
생성된 고스트심볼 삭제 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#131]
안녕하세요.

아래 기능으로 고스트심볼을 생성했습니다.

http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit

**생성된 고스트심볼 삭제는 어떻게 하는 건가요?**

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 

http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit

샘플코드를 바탕으로 객체 삭제 API를 말씀드리겠습니다.

GLOBAL.ghostSymbolLayer.removeAtKey("object_tree");

removeAtKey(오브잭트 key) API를 사용하시면 객체를 삭제하실수 있습니다.

감사합니다.
