### ISSUE TITLE
lon,lat,alt로 이동 완료 후 콜백 받는 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#132]
안녕하세요.

lon, lat, alt값으로 카메라 이동 하려고 합니다.

이동 완료 후 콜백을 받고 싶은데 방법이 있는지요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 

현재 엔진내부에 카메라 이동 완료 이벤트 Fire_EventCameraMoveEnd 가 있습니다. 

해당 이벤트를 사용하시면 될것같습니다.

var _canvas = document.getElementById('canvas');
_canvas.addEventListener("Fire_EventCameraMoveEnd", function(e){
	console.log(e); 
});

감사합니다.

**Comment by HyunSeongKil** [comment]
moveLonLatAlt() 함수에 콜백함수 추가하는건 어려울까요?

예) 
Module.getViewCamera().moveLonLatAlt(127, 36, 100, (e)=>{
  console.log(e);
});

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

Fire_EventCameraMoveEnd 이벤트는 카메라 이동 완료 후 발생하는 이벤트입니다.

해당 이벤트로 말씀하신 기능이 가능할것으로 파악됩니다.

혹시 콜백함수가 따로 필요하신 이유를 말씀해주시면 감사하겠습니다.

**Comment by HyunSeongKil** [comment]
1. Fire_EventCameraMoveEnd 이벤트는 모든 카메라 이동에 대해 발생할 것 같음
2. 해당 기능에서 바로 콜백함수가 호출된다면... 업무단 기능이 간단하게 처리될 것 같음

**Comment by YangHeeBong** [comment]
카메라 이동 처리에 대한 부분을 설명이 필요할 것 같습니다.

카메라 이동 UI, API 동작 시 목표 좌표는 타켓 좌표가 되고 랜더링 시 카메라를 타켓 위치로 이동 하는 형태로 제공 되고 있습니다.

현재 콜백 추가 시 아래와 같은 문제점이 있습니다.

1. 카메라 이벤트는 종료되는 시점은 Fire_EventCameraMoveEnd 와 동일
2. 콜백 처리 시 Fire_EventCameraMoveEnd 기능과 중복 기능 발생
3. Fire_EventCameraMoveEnd , 콜백 함수 동시 발생

또한 웹 부분에서 플래그 처리와 조건 처리로 충분히 처리 가능합니다.

**Comment by HyunSeongKil** [comment]
알겠습니다.
