### ISSUE TITLE
카메라 이동제한 기능 문의

### ISSUE THREAD

**Issue by Kiwoohyun2** [EgisCorp/XDWorld#133]
안녕하세요 
 createLayer() 함수로 만들어진 line또는 그 line으로 이루어진 polygon이 있다면 카메라가 line또는 polygon의 영역 너머로 이동이 제한되는 기능을 구현하고 싶습니다. 가능한 api가 있는지 궁금합니다

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 

[146번 이슈](https://github.com/EgisCorp/XDWorld/issues/146)와 동일한 문의로 판단됩니다

- 카메라 영역 제한 설정
Module.getViewCamera().setLimitRectAlt(좌하단 경도, 좌하단 위도, 우상단 경도, 우상단 위도, 최대 고도);

- 카메라 영역 제한 실행
Module.getViewCamera().setLimitCamera(true);

- 카메라 영역 제한 해제
Module.getViewCamera().setLimitCamera(false);

감사합니다.
