### ISSUE TITLE
지도 및 폴리곤 투명도 문의입니다.

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#134]
안녕하세요.

Module.XDESetPlanetTransparecny()을 이용해서 지도의 투명도를 조절하면 
폴리곤 스타일로 투명도를 0을 준 폴리곤 면이 투명했다가 검은색으로 표시되는데 투명하게 표시할 방법이 있나요? 
그리고 지도의 투명도에 따라 wms도 투명하게 변하는데 구분할 방법이 있을까요?

![2](https://user-images.githubusercontent.com/91519109/143998616-a6c81219-990f-4569-a9af-b9a8c04cec1b.PNG)
![1](https://user-images.githubusercontent.com/91519109/143998622-70c0037e-a558-44cf-be59-68c4d5d1c784.PNG)

**Comment by YunSumin** [comment]
안녕하세요,

투명도를 0을 준 폴리곤 면이 검게 표시되는 부분은 알파 블렌딩의 렌더 순서와 관련된 현상으로
해당 객체를 폴리곤이 아닌 외곽의 라인으로 표시하신다면 면이 검게 표시되는 것을 방지하실 수 있습니다.

WMS의 경우 지형의 텍스쳐에 그려지는 방식으로 렌더링 되기 때문에 (RTT방식)
알파 값도 지형의 알파 값을 따르게 되므로
WMS 대신 WFS 라인 방식으로 표출하시는 경우 지형과 독립적으로 렌더링 될 수 있습니다.

단, 지형 DEM과 결합되지 않기 때문에 지형을 뚫거나 묻히는 현상이 발생합니다.
