### ISSUE TITLE
카메라 1인칭 시점모드 질문

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#136]
카메라가 제자리에서만 회전하는 Module.getViewCamera().setMoveMode(true); 가 어느순간부터 갑자기 안먹는데 확인부탁드립니다

**Comment by avamk2** [comment]
안녕하세요 

API의 기능적으로 JSCamera의 setMoveMode는 회전동작과는 무관한 1/3인칭 시점 전환 기능입니다.

**Comment by Kiwoohyun** [comment]
네 해결되었습니다
