### ISSUE TITLE
물흐름 효과 오작동

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#137]
물흐름 효과 이상하게 작동합니다...

direction map 도 이상하게 작동합니다...

참고 소스코드 올립니다
[sandbox_object_flowpolygon.zip](https://github.com/EgisCorp/XDWorld/files/7659148/sandbox_object_flowpolygon.zip)

저희 앱에는 물흐름 효과에 거리가 조금만 멀어져도... 물효과 적용이 멈춥니다
감사합니다 ㅠㅠ..

**Comment by YunSumin** [comment]
안녕하세요,

업로드 해 주신 소스 코드는 기본 엔진 배포 파일인 것 같습니다.

오류 수정을 위한 현상 재현이 어려운 관계로
구현 중 오류가 발생한 코드와 이미지를 함께 첨부 해 주시면 수정에 재현 후 수정하겠습니다.
