### ISSUE TITLE
방위표, 이동, 확대/축소 기능 표시/미표시 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#14]
안녕하세요. 바이브컴퍼니입니다.

아래 이미지처럼...
방위표, 이동, 확대/축소 기능을 표시/미표시하고 싶습니다.
관련 함수가 어떤것이 있는지 알려주시면 고맙겠습니다.

![image](https://user-images.githubusercontent.com/38479834/120408573-44140d00-c38a-11eb-9455-585082cebc4d.png)

**Comment by SeongRyong-Choi** [comment]
Module.getNavigation().setNaviVisible(Module.JS_VISIBLE_OFF);

위 API를 이용하여 네비게이션을 on/off 하실 수 있습니다.

<인자값 정보>
- JS_VISIBLE_OFF : 네비게이션 숨김 설정
- JS_VISIBLE_ON : 네비게이션 보기 설정(활성화)
- JS_VISIBLE_AUTO : 네비게이션 보기 설정(간소화)

감사합니다.

**Comment by HyunSeongKil** [comment]
확인했습니다.
