### ISSUE TITLE
바닥 DEM 적용안했을 시 기본 건물 뜨는 문제

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#141]
![image](https://user-images.githubusercontent.com/3315478/149718822-7b148b7d-0122-473d-952f-00eb1455577e.png)
![image](https://user-images.githubusercontent.com/3315478/149718937-367d59ec-31c6-4178-8b55-8df1b1e7fcee.png)
안녕하세요.. DEM 없앤 기본 맵 상태에서
Module.XDEMapCreateLayer("facility_build", "http://xdworld.vworld.kr:8080", 8080, true, true, false, 9, 0, 15);
 Module.getMap().setSimpleMode(true);
해당 코드를 반영시키면 건물들이 모두 떠있습니다... 
감사합니다

**Comment by avamk2** [comment]
안녕하세요

해당 사항은 VWorld의 서비스 건물들은 모두 DEM 기반에 맞춰져서 모델 자체가 독립적으로 지형높이를 가진 모델들입니다.
이는 모든 건물이 지형 높이를 실시간으로 인지하고 배치하기에는 성능적인 문제가 발생하기에 기본적으로 높이값을 그대로 적용합니다.
그래서 API 레벨에서 건물을 배치하는 경우는 높이값을 설정하면서 배치할 수 있지만 서비스되는 건물들은 모두 독립적인 높이를 가지고 배치되기에 뜰수 밖에 없습니다.
