### ISSUE TITLE
HTML 미디어 적용 API 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#144]
참고 api: http://sandbox.dtwincloud.com/code/main.do?id=object_html

해당 api에서 이미지나 텍스트를 띄운 상태에서
다른 지도 클릭이벤트(마우스로 지도클릭시 해당좌표구하는 메서드 등)가 안먹는데 방법이 있을까요?

**Comment by YangHeeBong** [comment]
현재 DIV를 구현하기 위해서 container를 생성하고 있습니다.
container는 지도 전체 영역을 포함하는 HTML 컨트롤 입니다.

![image](https://user-images.githubusercontent.com/82924515/150747358-f2b585b6-63d0-46fd-ba1a-c583b6b8cf91.png)

지도 클릭 이벤트가 안되는 이유는 지도 위에 현재 container 가 생성되어 클릭 이벤트가 container에서 처리 되는 것 같습니다.

container 보다 지도 우선 순위를 높게 잡거나 container이벤트를 지도 이벤트 연동 하는 방법을 사용하시면 됩니다.

**Comment by Kiwoohyun** [comment]
해결됐습니다
