### ISSUE TITLE
특정 지도 영역 밖으로 벗어나지 못하게 하는 설정이 있는지 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#146]
안녕하세요.

지도상에 가상의 좌표(minx, miny, maxx, maxy)를 설정해 놓고, 그 영역 밖으로 지도가 벗어나지 못하게 하고 싶습니다.

예를들면... 
세종시로 영역을 설정해 놓으면, 사용자가 지도를 panning해도 서울이나 대전같은 곳으로 이동하지 못하게 하려고 합나다.

이런 경우에 사용할 수 있는 함수가 있는지 문의합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 

해당 기능 추가하여 엔진 업데이트되었습니다.

업데이트된 엔진을 새로 적용하여 아래 API를 활용해주시면 감사하겠습니다.

- 카메라 영역 제한 설정
Module.getViewCamera().setLimitRectAlt(좌하단 경도, 좌하단 위도, 우상단 경도, 우상단 위도, 최대 고도);

- 카메라 영역 제한 실행
Module.getViewCamera().setLimitCamera(true);

- 카메라 영역 제한 해제
Module.getViewCamera().setLimitCamera(false);

감사합니다.
