### ISSUE TITLE
HTML 미디어 적용 API 가시화 이슈

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#147]
참고 api: http://sandbox.dtwincloud.com/code/main.do?id=object_html

해당 api로 이미지를 표출했을 때 가까이서 봤을 때와 달리 멀리서 봤을 떄 이미지의 위치가 해당위치에서 벗어나는 현상이 있습니다
해결 방법이 있을까요?

![캡처2](https://user-images.githubusercontent.com/80441700/150709391-1d0482de-b568-4fc7-8801-68273b0a7c66.PNG)
![캡처](https://user-images.githubusercontent.com/80441700/150709399-9b8a66b5-7936-475f-9236-e5be475810c0.PNG)

**Comment by avamk2** [comment]
안녕하세요.
해당 객체의 위치정보에서 높이값을 혹시 0으로 넣으셨는가요?

**Comment by YangHeeBong** [comment]
샌드박스 소스에서 

		//verticalAlign: "middle",	// 수직 정렬 (top, middle, bottom, px 지원 )	 || 태그 미설정 시 [Default top]
		//horizontalAlign: "center",	// 수평 정렬 (left, center, right, px 지원 ) || 태그 미설정 시 [Default left]

이 부분이 주석 처리되어있습니다. div 객체 중심 좌표 옵션으로 태그 미설정 시 좌상단으로 설정됩니다. 
올려주신 2개의 이미지를 보면 좌상단을 기준점으로 div 생성된 것 같습니다.

또한 샌드박스 소스 부분에 태그에 대한 설명을 첨부하였고 한번 확인해 보시면 도움이 되실 것 같습니다.

**Comment by Kiwoohyun** [comment]
해결됐습니다
