### ISSUE TITLE
도넛모양의 멀티폴리곤 레이어를 생성하는 법 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#148]
기존coordinates값으로 멀티폴리곤을 그리는 방식으로는 

폴리곤의 내부(hole)값을 넣는  함수파라미터가 존재하지 않는데 혹시 도넛모양의 멀티폴리곤을 그리는 방법이 있을까요?

**Comment by YunSumin** [comment]
안녕하세요,

금일 업데이트로 폴리곤 홀 입력 기능이 개선되어 안내 드립니다.
JSPolygon의 setPartCoordinates API를 사용하여 버텍스 입력 시, 홀 버텍스 입력이 가능하도록 엔진이 개선되었습니다.

이와 관련하여 높이가 있는 폴리곤 생성 시 홀 값을 적용하는 코드가 추가되었습니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_polygon_height

API 상세 활용은 위 샘플코드 참조 부탁드립니다.

감사합니다.

**Comment by Kiwoohyun** [comment]
혹시 Outside Circle 과 Inside Circle 관련 코드를 넣는 규칙이 어떻게 되는지 알 수 있을까요?
createPolygon함수로 보내는 파라미터 리스트를 보면 하위리스트가 4개인데 처음 두리스트가 Outside Circle 자리이구 끝에 두리스트가 Inside Circle인건지 규칙을 잘모르겠습니다..!

**Comment by YunSumin** [comment]
안녕하세요,

Outside&Inside 판별은,
각 하위 리스트를 이루는 점들이

- 시계 방향(CW) 정렬인지 : Outside로 판별되어 폴리곤 외곽을 구성
- 반시계 방향(CCW) 정렬인지 : Inside로 판별되어 폴리곤 내부 Hole 생성

에 따라 결정됩니다.
![image](https://user-images.githubusercontent.com/82925313/155465811-ddcef732-95e0-4291-b901-7708ad06d275.png)
하위 리스트들의 순서는 자유롭게 설정해 주셔도 되며,
각 하위리스트 점들의 정렬 방향에만 유의하시어 설정해주시면 됩니다.
(또한, 적어도 하위리스트 중 하나는 폴리곤의 외곽을 형성할 수 있도록 시계 방향(CW)으로 구성되어 있어야 합니다.)

감사합니다.

**Comment by Kiwoohyun** [comment]
해결됐습니다. 답변감사합니다
