### ISSUE TITLE
DEM없는경우 DEM높이값 질문

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#149]
DEM이 없는 경우에 DEM의 높이값이 일정할 거라고 생각했는데
Module.getMap().getLonLatHeight(lon, lat);
로 높이값을 구해보면 좌표마다 높이값이 다 다르게 뜹니다.

혹시 이유가 있을까요?
그리고 DEM이 없는경우 DEM높이값을 일정하게 줄 수 있는 방법이 있는지 궁금합니다

**Comment by avamk2** [comment]
안녕하세요 

해당 API의 기능은 경위도를 통해서 높이값을 받는 API이지만 이 API는 단지 지형에 높이만 반환하는게 아닌 공간에 객체가 존재하면 (예를들어 3D 모델링, 3D 도형 등)이 존재하면 해당 높이를 우선적으로 받게 되어 있습니다.

DEM이 없는 서비스라면 애초에 계산할 필요도 없이 0이 됩니다만 실수 변수의 특성상 완전한 0이 아닌 미세한 소수값이 존재할수도 있습니다. 

지형의 높이값만 받을려고하는 경우는 
`var terrainHeight = Module.getMap().getTerrHeight(lon,lat);`  
를 사용해서 지형의 높이정보만 받을 수 있습니다.

**Comment by Kiwoohyun** [comment]
해결완료했습니다. 답변감사합니다
