### ISSUE TITLE
면적 측정

### ISSUE THREAD

**Issue by Ryu-Joon-Hyuck** [EgisCorp/XDWorld#15]
최근 엔진 적용 후에 면적을 나타내는 부분이 주변 지형의 영향을 받습니다.

https://user-images.githubusercontent.com/85206804/120433333-0f1daf80-c3b6-11eb-9a84-50f3f03030a8.mp4

샌드박스에는 문제가 없어 보입니다.

https://user-images.githubusercontent.com/85206804/120433388-1e9cf880-c3b6-11eb-9dc3-7b6056ba2035.mp4

DIGITAL TWIN CLOUD는 라인 등에 영향을 받는 거 같습니다.

https://user-images.githubusercontent.com/85206804/120433464-36747c80-c3b6-11eb-9303-ab134a9ffaeb.mp4

https://user-images.githubusercontent.com/85206804/120433468-383e4000-c3b6-11eb-99b7-f756d05f35e0.mp4

답변 부탁 드립니다.

**Comment by SeongRyong-Choi** [comment]
말씀하신 내용 확인하여 정상적으로 동작하도록 엔진이 수정되었습니다.

수정 된 새 엔진 적용 부탁드립니다.

**Comment by HyunSeongKil** [comment]
엔진 버전 : Version 1.3.15.7.2 (2021-05-31)

수정된 엔진 적용했습니다.
아래 이미지처럼 보이는게 맞는 건가요?

![image](https://user-images.githubusercontent.com/38479834/120745725-b88cae80-c538-11eb-9d67-6040df30a272.png)

**Comment by SeongRyong-Choi** [comment]
엔진 버전 : Version 1.3.15.7.2 (2021-06-04)

웹 브라우저 캐쉬 삭제 후 실행해주시면 감사하겠습니다.

![20210604_133522](https://user-images.githubusercontent.com/70614782/120746304-df97b000-c539-11eb-970f-3f197dda321b.png)

**Comment by SeongRyong-Choi** [comment]
샌드박스 샘플코드에 z-buffer 를 설정하는 코드가 있습니다.
http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=analysis_measure_area

SetAreaMeasurePolygonDepthBuffer(false);

혹시 z-buffer 설정이 안되어 있는건 아닌지 확인 부탁드립니다.
