### ISSUE TITLE
바이브스퀘어 DB 관련 질문 및 요청사항

### ISSUE THREAD

**Issue by giwon1130** [EgisCorp/XDWorld#151]
1. 필지 테이블이 여러개(lsmd, lsmd_0125_filter등등) 존재하는데 실제 사용하는 필지 테이블명을 알고 싶습니다.
2. 생성하신 테이블에 관한 테이블 정의서 요청
3. 필지 테이블에 buy_at(구매여부) 컬럼 추가 요청 => y/n으로 구분
4. 추후에는 서울뿐만 아니라 부산도 들어와야 하는데 그 부분은 어떤 식으로 테이블이 생성되는지에 대해 알고 싶습니다.

**Comment by YunSumin** [comment]
안녕하세요

전달해 주신 내용 만으로는 문의 내용 파악이 어려워 자세한 답변이 어려운 점 양해 부탁 드립니다.

사업 관련 문의의 경우 관련 직원에게 문의 부탁 드리며,
엔진 API 관련 문의의 경우 테스트 중인 코드 및 관련 영상을 첨부해주시면 첨부 내용 참조하여 답변 드리겠습니다.

**Comment by giwon1130** [comment]
네 알겠습니다

**Comment by avamk2** [comment]
안녕하세요 

문의주신사항에 대해서는 XDWorld의 깃허브는 3D 엔진에 관련된 문의와 피드백으로 한정됩니다.
이는 여기 깃사이트는 EGIS의 모든 부서에서 QnA를 제공하는게 아닌 EGIS 연구소 개발 제품인 XDWorld Web 3D 엔진의 SDK 관련된 지원만 하기 때문입니다.

추가적으로 이야기드리면 데이터가 어떻게 준비되고 무엇이 제공되었는지도 연구소와 별도로 진행하며 이에 대한 자료제공사항이나 데이터 사본을 공유받지 않습니다. 이는 저희가 프로젝트의 일선에서 같이 개발이 아닌 이선에서 지원이기 때문에 일선에서 개발에 관련되어 3D엔진에 관련된 사항이 아닌 정보는 대부분 제공받진 않습니다.

개발하시는 프로젝트에 종속된 데이터 및 서비스에 연결되어서 수행하는 엔진 기술 문의에 대해서는 해당 정보를 포함하여 질문 또는 공개하기 어려운 경우는 프로젝트 담당자에게 미리 정보를 제공하고 해당 정보건에 대한 질문임을 알려주시면 저희 답변에 대한 포커스도 프로젝트에 밀착해서 드릴수 있습니다.

그럼 좋은 하루되세요
