### ISSUE TITLE
외부경로에 있는 dds 데이터 가시화 방법

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#152]
안녕하세요. 대구 사무실 김선옥입니다.

이전에 XDServer가 설치되어있는 개발서버의 layer.xml에 dds 데이터 정보를 정의해주고,
script 단에서 Module.XDESetSatUrlLayerName([개발서버], [레이어명]); 으로 선언해줌으로써 
dds 데이터를 가시화 시킨 적이 있습니다.

현재 외부 경로에 있는 dds 데이터를 바로 호출하고 싶은데, 가능한가요?

**Comment by YunSumin** [comment]
안녕하세요, 

현재 엔진에 가시화 되는 서비스 데이터는 XDServer를 통해 수신 하고 있습니다.
XDServer 환경 구축 후 사용하시고자 하는 데이터를 XDServer에 업로드 후 활용 부탁 드립니다.

감사합니다.
