### ISSUE TITLE
base map완료 후 콜백받는 방법

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#153]
안녕하세요.

Module.SetPlanetImageryType()함수를 사용하여
base map(osm,네이버지도 등)을 설정한 뒤에 
지도업로드가 완료되면 콜백을 받고 싶은데 방법이 있을까요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

아래 API를 사용하여 지형 로딩 완료시 마다 callback 처리를 할 수 있습니다.

function completeCallback(...args) {
    console.log(args);
}
Module.getMap().requestMeshLoadCallback(completeCallback);

**Comment by Kiwoohyun** [comment]
답변 감사합니다
