### ISSUE TITLE
배경지도 설정 api 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#154]
참고 api: http://sandbox.dtwincloud.com/code/main.do?id=layer_basemap

혹시 아래와 같은 현상의 해결방법이 있는지 궁금합니다

1. 줌인을 했을 때 텍스트화질이 너무 흐린 현상
2. DEM으로 인해 OSM 텍스트가 굴곡이 발생하는 현상
![image](https://user-images.githubusercontent.com/80441700/152718956-ddb5e5db-96d5-4c2b-8b7a-d872bbf8b351.png)

3. 몇몇 텍스트는 줌레벨에 따라 사라지는 현상
![image](https://user-images.githubusercontent.com/80441700/152719327-067e2573-e405-495b-8c9d-027d4f3614e0.png)
![image](https://user-images.githubusercontent.com/80441700/152719249-b7782d87-8407-474a-94bb-4a75ac3bbb03.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 현재 OSM이 어떻게 서비스되는 비교하시는게 도움이 될것 같습니다.

https://www.openstreetmap.org/#map=19/37.52171/126.98934

1. 줌인을 했을 때 텍스트화질이 너무 흐린 현상
  =>  최대 레벨의 이미지는 정해져 있는데 이것을 계속 확대를 했을 경우에는 화질이 안좋게 보입니다.  OSM 사이트를 보시면 줌 레벨을 제한하여 해당 현상을 해결하였습니다. 줌 레벨 제한을 해도 화질이 만족스럽지 못할 경우 배경지도 품질을 "high"로 설정하시면 됩니다.

2. DEM으로 인해 OSM 텍스트가 굴곡이 발생하는 현상
  => 2D 이미지를 3D 지도에 오버랩할 경우 지형으로 인해 굴곡이 발생할수있습니다. 빔프로젝터를 평면이 아닌 울퉁불퉁한 면에 투영하면 굴곡되는 현상과 동일합니다. 만약 지형이 필요하지 않다면 지형을 요청하지 않는 방법이 있습니다. Module.XDESetDemUrlLayerName("", "");  API를 사용하여 지형요청 URL과 레이어명을 공백처리하시면 됩니다.

3. 몇몇 텍스트는 줌레벨에 따라 사라지는 현상
  => 배경지도 서비스는 현재 카메라 영역을 바탕으로 데이터를 요청하여 이미지를 받아와 지도에 오버랩하고 있습니다. 텍스트가 사라지는 현상은 실 데이터가 그렇기에 정상적인 동작입니다. OSM 사이트를 보시면 동일한 현상이 발생하고 있습니다.

**Comment by Kiwoohyun** [comment]
답변 감사합니다
