### ISSUE TITLE
배경지도 설정 api 관련 질문 2

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#155]
참고 api: http://sandbox.dtwincloud.com/code/main.do?id=layer_basemap

배경지도를 OSM 1로 설정하고
배경지도 옵션을 high이나 middle로 설정 (특히 high) 하고
줌인을 하거나 카메라이동 api로 특정지점으로 빠르게 줌인 이동을 하면
아래 사진과 같은 오류가 발생합니다.
해결방법이 있을까요?
![image](https://user-images.githubusercontent.com/80441700/152928294-852da734-1198-4ae5-85de-33775050df10.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

zerolevelOffset 으로 인한 메커니즘 오류가 있어 우선 zerolevelOffset을 0으로 고정해서 사용하시면 에러문제는 해결될것같습니다.

추후 zerolevelOffset 메커니즘 오류에 대해 업데이트하여 답변드리겠습니다.

**Comment by Kiwoohyun** [comment]
해결완료했습니다. 감사합니다
