### ISSUE TITLE
createWMSLayer 도중 basemap 변경문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#156]
new Module.JSLayerList(false).createWMSLayer(); 로 생성한 지오서버에서 가져온  레이어가 
없는상태에서는 basemap을 변경하더라도 문제가 없는데
있는상태에서는 basemap을 변경하면 화면이 멈춰버리는 버그가 있습니다

deletewmslayer를 날려서 필지레이어를 없애고 basemap을 변경하더라도 createwmslayer했던 요청은 여전히 가고 있는 상태여서 이요청(약 30초)이 끝나기전에 basemap을 변경하면 멈춥니다. 방법이 있을까요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 

말씀하신 내용을 바탕으로 아래와 같이 테스트 하였습니다.

1. WMS레이어 생성 후 배경지도 변경 그리고 WMS레이어 삭제
![20220223_162450](https://user-images.githubusercontent.com/70614782/155276734-d1cc65d1-fc87-4e6e-a827-4ab27c7dccc6.png)
![20220223_162501](https://user-images.githubusercontent.com/70614782/155276789-ea796618-4eef-41d5-adf4-e74da2d5ba7f.png)
![20220223_162509](https://user-images.githubusercontent.com/70614782/155276909-c5b74e7d-dbb6-4031-89ea-2af67c2dd5bd.png)

2. 배경지도 변경 후 WMS레이어 생성
![20220223_162530](https://user-images.githubusercontent.com/70614782/155276880-1468e897-ed4c-4597-944e-0b62f5450504.png)
![20220223_162540](https://user-images.githubusercontent.com/70614782/155276885-54679675-e514-408d-b02e-f18dbedd2d67.png)

화면이 멈추는 버그없이 정상적으로 동작하는것을 확인하였습니다.

추측하기로는 geoserver 통신에 의한 오류일 가능성도 있을것 같습니다.

혹시 어떤 부분에서 오류가 발생하는지 말씀해주시면 비슷한 환경에서 테스트 진행해보겠습니다.

감사합니다.

**Comment by SeongRyong-Choi** [comment]
데이터가 큰 WMS 레이어생성 후 요청이 끝나기전에 배경지도를 변경했을 때 오류가 발생하는것을 확인하였습니다.

해당부분에 대해서 엔진 작업 후 업데이트하면서 다시 답변 드리겠습니다.

감사합니다.

**Comment by Kiwoohyun** [comment]
알겠습니다!
