### ISSUE TITLE
zeroLevel 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#157]
참고 url : http://sandbox.dtwincloud.com/code/main.do?id=layer_wmts

관련 api의  zeroLevel이 위url에서는 3으로 설정되어 있는데 예전에 zeroLevel은 0~2라고 답변을 받은 기억이 있습니다

현재 올라와 있는 엔진버전이 Version 1.3.15.7.2 (2022-02-14)가 최신인데 해당버전에서는 zeroLevel을 2~3으로 설정하면

카메라를 바닥에 가까이 줌인했을 시 아래 사진처럼 wmts레이어를 기존바닥이 뚫고나오는? 현상이 있습니다

 zeroLevel이 1일 때는 해당 현상이 발생하지 않습니다.

(dem은 현재 Module.XDESetDemUrlLayerNameEX("", "", "");로 처리했고

http://sandbox.dtwincloud.com/code/main.do?id=layer_wmts 관련하여 wmts를 깔아놓은 상태입니다.)

샌드박스에 있는 Version 1.3.15.7.2 (2022-02-17)로 업데이트해야 zeroLevel을 3으로 설정할 수 있는건지

궁금합니다.

![image](https://user-images.githubusercontent.com/80441700/155954164-87f2bc4d-fa1c-4bea-b749-cc2739f2750e.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

zeroLevel은 서로 다른 타일구조의 이미지를 매핑하기 위한 변수입니다.

엔진 내부적으로는 현재 브이월드 레벨 + zeroLevel로 요청 URL을 구성하고있습니다.

그래서 어떤 구조로 타일링을 했는지에 따라 zeroLevel이 변경될 수 있습니다.

하지만 말씀하신 오류사항은 serviceLevel의 max 설정 문제로 파악됩니다.

실제로 15레벨까지 타일링되어있는데 max를 14레벨로 제한한다면 15레벨 데이터는 기존 브이월드 데이터로 대체됩니다.

serviceLevel: {
	min: 3,
	max: 18
}

serviceLevel의 max 확인부탁드립니다.

**Comment by Kiwoohyun** [comment]
해결됐습니다!
