### ISSUE TITLE
테두리 부분 이슈

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#158]
샌드박스 맵을 보면 테두리부분이 리뉴얼?이 안되는 버그가 있습니다 확인부탁드립니다

![image (1)](https://user-images.githubusercontent.com/80441700/156486139-867b6393-9dcc-4c3f-8899-62dde02b5fb2.png)
![image (2)](https://user-images.githubusercontent.com/80441700/156486145-22c71c5b-d690-40fa-9278-83d76298e193.png)
![image](https://user-images.githubusercontent.com/80441700/156486147-dddaf17a-16c7-41f7-b58f-6390a16ba3e5.png)

**Comment by hjaejae** [comment]
안녕하세요~
문의주신 내용은 버그가 아닌 3차원 지도의 특성입니다.

2차원 지도에서는 한 화면에 그려지는 영역이 레벨별로 고정되어져있어 같은 레벨로 그려지는것이 가능합니다.
그러나 3차원에서는 카메라가 바라보는 각도에 따라서 무한정 늘어날수있기 때문에
[LOD라는 알고리즘](https://copynull.tistory.com/321)을 이용하여 렌더링 하고있습니다.

현재 보이는 영역에서 최대한 이질감이 없게 보이게 하기 위한 연구가 진행중이지만 원천적으로 완벽하게 그렇게 그리는것은 힘들것으로 보입니다.
