### ISSUE TITLE
태풍 자동 이동시 예외 발생 현상?

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#16]
안녕하세요. 바이브컴퍼니입니다.

태풍 자동이동 시킬 때 아래 이미지와 같은 예외가 발생합니다.
업무 로직상으로는.....변경된게 없는데...

혹시 엔진쪽에 뭔가 이슈가 있는지 확인 요청합니다.
만약, 엔진에 문제가 없다면.... 
업무 로직쪽 다시 확인해야죠,뭐...

![image](https://user-images.githubusercontent.com/38479834/120462064-87e03400-c3d5-11eb-838d-62a7d6386359.png)

**Comment by YunSumin** [comment]
오류 원인 테스트를 위해, 문제가 발생하는 자동 이동 좌표 경로가 필요할 것 같습니다.
좌표 리스트를 알려주시면 참조해서 엔진 내부 원인을 파악해보겠습니다.

**Comment by YangHeeBong** [comment]
태풍 처리 부분 처리한 샌드박스 주소입니다. 개발 시 참조 하시면 됩니다.

샘플 예제
http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol

엔진 교체 
https://github.com/EgisCorp/XDWorld/tree/main/Release/v_0.1.1
