### ISSUE TITLE
WMTS관련 질문

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#160]
참고 API: http://sandbox.dtwincloud.com/code/main.do?id=layer_wmts

해당 샌드박스에서는 잘 작동하지만
프로젝트에 적용하면
"일반지도" 인 경우에만 아래쪽 wmts가 생성되지 않는 현상이 있습니다

zeroLevel이 2이고 해상도가 middle이거나 high일 떄
![image](https://user-images.githubusercontent.com/80441700/156720568-8940da7f-d96a-4241-98a2-35beb5fcfa60.png)

zeroLevel이 3이고 해상도가 middle이거나 high일 때
![image](https://user-images.githubusercontent.com/80441700/156720849-645707eb-13e3-4aef-a63c-f3c46a0da3bb.png)

zeroLevel이 1일 떄나 그외 경우는 해당 현상없이 잘 뜨는데 혹시 제가 놓치고 있는부분이 있을까요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

해당 문제에 대하여 엔진 업데이트 되었습니다. 

기존 API가 사용하기 복잡하여 일부 수정되었습니다.

새로운 엔진으로 업데이트 후 [샌드박스](http://sandbox.dtwincloud.com/code/main.do?id=layer_wmts)를 참조하여 수정 부탁드립니다.

감사합니다.

**Comment by Kiwoohyun** [comment]
업데이트 후 테두리부분이 리뉴얼?이 안되는 부분이 발생하였습니다.

엔진 업데이트 전 기존 WMTS를 적용했을 때
![image](https://user-images.githubusercontent.com/80441700/156731184-2281c771-c286-4768-9104-5faa00a87501.png)

엔진 업데이트 후 변경된 WMTS API를 적용했을 때
![image](https://user-images.githubusercontent.com/80441700/156731433-6f82eaf9-eab1-4e5c-8711-d80abbd44592.png)

**Comment by Kiwoohyun** [comment]
네 알겠습니다 감사합니다.
