### ISSUE TITLE
카메라 영역설정 api 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#161]
현재 프로젝트 내에서 wmts적용한 상태입니다
wmts를 적용한 상태에서는 카메라 영역설정 api를 이용한 카메라이동이 매우 느려지는 점을 발견하였습니다.
해당 api는  높은 고도로 한번 이동 후 해당지점으로 이동하는 특징이 있는데 이 때문에 이동시간이 오래걸려 해당지점으로 이동하는 동안 이동경로에 있는 모든 wmts타일을 업로드하여 성능이슈가 발생합니다.
( 카메라 영역설정 api: http://sandbox.dtwincloud.com/code/main.do?id=camera_set_viewrect )

때문에 Module.getViewCamera().move처럼 카메라 영역설정 api도
해당영역으로 바로 이동할 수는 없는지 궁금합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

말씀하신 애니메이션 on / off 기능 추가하여 엔진업데이트했습니다.

새로운 엔진으로 업데이트 후 테스트 부탁드립니다.

http://sandbox.dtwincloud.com/code/main.do?id=camera_set_viewrect

감사합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

말씀하신 애니메이션 on / off 기능 추가하여 엔진업데이트했습니다.

새로운 엔진으로 업데이트 후 테스트 부탁드립니다.

http://sandbox.dtwincloud.com/code/main.do?id=camera_set_viewrect

감사합니다.
