### ISSUE TITLE
최대높이제한 질문

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#162]
카메라의 최저높이 제한은     Module.getViewCamera().setLimitAltitude();로 컨트롤이 가능한데
최대높이 제한은 
Module.getViewCamera().setLimitRectAlt() 모듈과 같이 lon,lat을 통한 영역제한과함께 최대높이를 제한하는 모듈밖에 안보이더라구요

최저높이 제한 처럼 
최대높이 제한으로 imput parameter가 높이값만 들어가는 함수가 있을까요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

현재 최대높이만 따로 제한하는 API는 없습니다.

해당 부분에 대해서 property로 지원할 예정입니다.

추후 엔진 적용 후 다시 답변드리겠습니다.

감사합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

JSCamera 클레스에 limit property가 추가되었습니다.

새로운 엔진으로 업데이트 받으신 후 사용하실 수 있습니다.

1. 현재 설정된 limit 값 확인
```
Module.getViewCamera().limit;
```

2. (영역, 고도) limit 설정하기
```
let limitOption = {
	// 영역 제한
	bound: {
		max: {
			lon: 127.06488139128804,
			lat: 37.4884208071822		
		},
		min: {
			lon: 127.05008916368347,
			lat: 37.47908194194946
		},
                enable: true	// false: 영역 limit 설정 적용하지 않음
	},

	// 높이 제한
        altitude:{
		max: 10000,
		min: 100,
                enable: true	// false: 높이 limit 설정 적용하지 않음
	}
};

Module.getViewCamera().limit = limitOption;
```

아래는 문의하신 최대높이 제한기능의 예시입니다.
```
let limitOption = {
        // 최대 높이 제한
       altitude:{
		max: 10000,
                enable: true
	}
};
Module.getViewCamera().limit = limitOption;
```

감사합니다.
