### ISSUE TITLE
반경 그리기 질문

### ISSUE THREAD

**Issue by yuuki9** [EgisCorp/XDWorld#163]
라인을 그려주는 마우스 모드( MML_INPUT_LINE)로 라인을 렌더링 한 후  
반경을 분석 마우스 모드(MML_ANALYS_AREA_CIRCLE)로 전환 하여 반경을 그리면, 
그전에 그려졋던 라인들이 모두 지워지는 현상이 있는데 이유가 궁금합니다. 
반경 기능 내부에 라인을 초기화 하는 함수가 적용되어 있는건가요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

높이측정, 거리측정, 면적측정, 반경측정등 측정기능으로 전환할때 입력점에 대해 초기화를 하고 있습니다.

예를들어, 거리측정을 하고 면적측정을 할 때 입력점이 초기화되어 거리측정때 입력한 점은 삭제됩니다.

감사합니다.

**Comment by avamk2** [comment]
구체적으로 이야기드리면 엔진에서에 마우스 모드를 통해서 사용되는 UI는 내부적으로 좌표정보 구성이 공유되어 관리됩니다.
이는 기능적으로 `JSVec3Array JSMap::getInputPoints()` 를 통해서 마우스 등으로 입력된 경로를 외부에서 받도록 설계되어 있습니다.  다만 마우스 모드 변경만으로 초기화가 되지는 않습니다. 해당 기능 전환을 할때 API 적으로 초기화를 수행하고 전환합니다.
이는 기능적으로 지형을 타고 가는 라인생성과 그렇지 않은 생성, 끝점을 처리하는 로직이 달라서 모드 전환시 완전하게 잘 수행되지는 않기 때문입니다. 그래서 초기화를 넣는 것을 적극적으로 권장합니다.

그리고 모드 변경 후에 CIRCLE 관련 모드들은 사용자 드래그를 통해서 첫클릭이 중심점 드래그 상태에서 반경 지름이 동작하고 버튼을 놓게되면 위에 2값과 세그먼트라는 다각형 수의 속성 3가지를 바탕으로 새로운 원을 만들어 냅니다. (실질적으로는 점수 많은 다격형입니다.) 때문에 동작 특성상 초기화가 자동으로 진행됩니다.

![image](https://user-images.githubusercontent.com/82994540/157593334-6f8b5f50-d293-406d-9088-73285bb3523d.png)

요약하면 UI별로 입력된 자료가 각 모드별 관리하는 것이 아니라서 모드변한은 해당 동작에 대해서 취소 또는 완료로 간주하는 것으로 설계되어 있습니다.
