### ISSUE TITLE
현재 지도 배경화면이 어떤 배경화면으로 사용되고 있는지 알 수 있는 방법이 있을까요?

### ISSUE THREAD

**Issue by jdevil0313** [EgisCorp/XDWorld#164]
샌드박스 예제에 WMTS예제 http://sandbox.dtwincloud.com/code/main.do?id=layer_wmts 를 통해 korean_map() 함수를 이용하여 바로e맵(국토지리정보원) 일반 지도로 지도 배경지도를 변경했는데요?
현재 설정된 배경지도가 어떤 배경지도로 사용되고 있는지 알 수 있는 방법이 있을까요?
예를 들면 wms 같은 경우는 레이어 리스트통해 nameAtLayer() 함수를 이용하면 레이어 이름으로 불러와서 
getVisible()를 통해 visible상태를 알 수 있듯이 방법이 있는지 궁금합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

WMTS 배경지도의 경우 레이어와는 별개로 지도의 기존 영상을 교체합니다.

그렇기에 레이어처럼 여러개를 생성할 수 없고 교체하는 방식이며 하나의 지도 서비스입니다.

그러므로 현재 서비스중인 지도가 어떤 지도인지 파악하는것은 웹에서 리스트로 관리해야할것 같습니다.

감사합니다.

**Comment by jdevil0313** [comment]
감사합니다
