### ISSUE TITLE
3D 카메라 기울기 문의

### ISSUE THREAD

**Issue by Parster** [EgisCorp/XDWorld#165]
안녕하십니까.  이지스 박규호입니다.

Module.getViewCamera()에서 카메라 이동 기능을 사용하고 있습니다.
카메라 이동시 기울기 90을 줬을 때 카메라로 바라보는 영역과  
기울기 30을 줬을 때 카메라로 바라보는 모습이 동일하게 하려고합니다.

![30](https://user-images.githubusercontent.com/86399390/158498400-f06a9db6-8659-4db6-8c84-318dc675b52c.PNG)
샌드박스 카메라 기능 30줬을때 
![60](https://user-images.githubusercontent.com/86399390/158498363-aa365412-082c-4d6b-92cb-22602d1a07a7.PNG)
샌드박스 카메라 기능 90줬을때 

카메라가 바라보는 중앙의 경위도를 구하는 기능이나 이동 함수를 문의드립니다.
감사합니다.

**Comment by YunSumin** [comment]
안녕하세요,

문의 주신 내용을 확인하여 카메라의 바라보는 지점을 고정하는 Tilt 각도 설정 코드를 전송드립니다.

```
function setTilt(_targetTilt) {

    if (_targetTilt < -90.0 || _targetTilt > 90.0) {
        return;
    }
    
    // 화면 중앙 지도 좌표 반환
    var map = Module.getMap();
    var screenCenterX = parseInt(window.innerWidth * 0.5);
    var screenCenterY = parseInt(window.innerHeight * 0.5);
    var mapCenter = map.ScreenToMapPointEX(new Module.JSVector2D(screenCenterX, screenCenterY));
    
    // 현재 방위 각도과 거리를 유지하되 지정한 Tilt 각도를 적용한 카메라 위치 계산 
    var camera = Module.getViewCamera();
    var targetTilt = _targetTilt * (Math.PI / 180.0);
    var distance = map.GetPointDistance(mapCenter, camera.getLocation(), false);
    var t = distance * Math.cos(targetTilt);
    var cameraPosition = map.getPositionByAngleDistance3D(mapCenter, t, camera.getDirect()+180.0);
    var altitude = distance * Math.sin(targetTilt);
    cameraPosition.Altitude += altitude;
    
    // 카메라 이동
    camera.look(cameraPosition, mapCenter);
}
```

위 함수에서 사용된 주요 엔진 API의 파라미터 내용은 다음과 같습니다.
> number GetPointDistance(JSVector3D _vFrom, JSVector3D _vTo, bool _bUnionTerrain) 
> * Class : JSMap
> * Parameter
>   * _vFrom : 거리 계산 시작 점
>   * _vTo: 거리 계산 끝점
>   * _bUnionTerrain : 거리 계산 시 지형 고도 반영 여부
> * Return : 두 지점 간 거리 값 (m단위)

> JSVector3D getPositionByAngleDistance3D(JSVector3D _center, number _distance, number _angle)
> * Class : JSMap
> * Parameter
>   * _center : 기준점
>   * _distance : 기준점으로부터 거리
>   * _angle : 정북방향 0도를 기준으로 하는 방위각
> * Return : 기준점(_center)을 기준으로 일정한 거리(_distance) 및 방위각도(_angle)에 위치하는 지점 반환

함수 실행은 아래 영상 참조 부탁 드립니다.

https://user-images.githubusercontent.com/82925313/158503000-eb70ceb2-e325-4e94-a18d-b81bcce8a8b8.mov


감사합니다.

**Comment by Parster** [comment]
빠른 답변 주셔서 감사합니다.
