### ISSUE TITLE
카메라 각도제한 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#167]
각도제한은 현재 카메라 z축?에 대한 각도제한은 있는걸로 아는데
x,y(수평)에 대한 각도제한은 없는걸로 알고 있습니다
수평각에 대한 각도제한이 구현되있는 api가 있을까요?

**Comment by YunSumin** [comment]
틸트(z축) 각의 경우 지면과 수평한 방향으로 이동 반경이 제한되므로 조작 시 자연스러우나,
방위(x, y) 각의 경우 영역 제한 기능과 혼동 될 수 있어 현재 지원하지 않고 있습니다.
