### ISSUE TITLE
미니맵 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#168]
엔진 내에 기본으로 존재하는 
Module.getNavigation().setNaviVisible(nvt);
위코드의 네비게이션 툴처럼

혹시 기본으로 내장되있는 미니맵기능이 있는지 궁금합니다

**Comment by YunSumin** [comment]
엔진 내 인덱스 맵 기능이 내장되어 있습니다.

```
Module.getIndexMap().SetVisible(true);
```

![image](https://user-images.githubusercontent.com/82925313/160574818-e2e651b8-1178-4882-8d85-fcb3f0858a25.png)

화면 좌측 하단에 인덱스 맵이 렌더링 됩니다.

자체 기능을 내장하고 있으나 현재 구체적인 개발 일정이 없으며
인덱스 맵 보다 iframe을 이용한 별도 2D 지도를 미니맵으로 사용하시는 것을 권장 드립니다.

**Comment by loeaf** [comment]
어... 혹시 화면에 그려진 폴리곤 정보라던가 이런것들은 저기에 표현이 힘든가요..?
그리고 크기나 위치를 조정할 수 있을까요?

**Comment by YangHeeBong** [comment]
네 질문에 대해 답변 하겠습니다. 

1. 화면에 그려진 폴리곤 정보라던가 이런것들은 저기에 표현이 힘든가요..?
     - 인덱스 맵은 미니맵기능이 아님으로 표현이 가능해도 제한이 많은 기능입니다. 원하시는 미니맵 기능은 web canvas를 통해 폴리곤 정보를 가시화 방법이 더 효율적입니다.
     
2. 그리고 크기나 위치를 조정할 수 있을까요
     -  WebGL에서 제공 하는 뷰포트를 통해 크기 조정은 가능하지만 Web UI와 연동은 불가 합니다.(z-index로 인해 UI 아래로 그려집니다.)
   
3. 미니맵안에 건물을 disable 하는건 가능한가요??
    - 인덱스맵을 이야기 하시는건가요?? 아니면 새로 생성한 미니맵에서 건물을 disable 이야기 하시는건가요??
    - 인덱스 맵은 인덱스 맵에서만 특정 폴리곤을 disable 기능은 제공하지 않습니다.

5. 90도 탑뷰 보다는 약간 75도 80도 느낌인대... 완전 탑뷰로는 힘들까요?
    - 인덱스 맵은 탑뷰로 가능합니다.
