### ISSUE TITLE
vworld다운시 예외처리 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#169]
vworld관련 오류가 발생했을 경우에 요청을 아래사진처럼 무한으로 보내고 있는데 혹시 저희 클라이언트단쪽에서 예외처리를 할 수 있는 방법이 있는지, 아니면 엔진쪽에서 수정해야하는 부분인지 문의드립니다.

![image](https://user-images.githubusercontent.com/80441700/158726056-e72888b1-4ca6-442d-bf33-81bf82afdeef.png)

**Comment by YunSumin** [comment]
현재 엔진은 기본 지형 데이터(DEM, 정사영상)로 브이월드 데이터를 사용하고 있습니다.

연구소 내부에는 보유한 별도 지형 데이터가 없는 관계로 브이월드 데이터 외 대안이 없으나,
만약 별도 XDServer기반 지형 데이터를 보유하신 경우
아래 API를 사용하셔서 XDServer 지형 요청 경로를 수정하실 수 있습니다.


**[지형 DEM]**
```
Module.XDESetDemUrlLayerName("http://new.server.url:8080", "NEW_DEM");
```
> 지형 DEM 요청 URL은 아래와 같이 변경됩니다.
> (예) h**ttp://new.server.url:8080**/XDServer/requestLayerNode?Layer=**NEW_DEM**&Level=13&IDX=69798&IDY=28976


**[지형 영상]**
```
Module.XDESetSatUrlLayerName("http://new.server.url:8080", "NEW_SAT");
```
> 지형 영상 요청 URL은 아래와 같이 변경됩니다.
> (예) h**ttp://new.server.url:8080**/XDServer/requestLayerNode?Layer=**NEW_SAT**&Level=13&IDX=69798&IDY=28976

XDESetDemUrlLayerName API와 XDESetSatUrlLayerName API는
엔진을 초기화 하는 Module.Start API 전에 호출하시는 것이 좋습니다.
Module.Start API가 초기 0레벨의 지형 요청 기능을 포함하기 때문입니다.
```
Module.XDESetDemUrlLayerName("http://new.server.url:8080", "NEW_DEM");
Module.XDESetSatUrlLayerName("http://new.server.url:8080", "NEW_SAT");
Module.Start(window.innerWidth, window.innerHeight);
```
