### ISSUE TITLE
moveLonLatBoundary() 이동속도 조절 또는 완료시 콜백함수 호출 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#17]
안녕하세요. 바이브컴퍼니입니다.

예)
...전략
moveLonLatBoundary(); //지도 이동
blinkBuilding(); //건물 깜빡깜빡
...후략

지도 이동이 완료되기 전에 건물 깜빡임이 먼저 완료되서 깜빡임이 사용자 눈에 표시되지 않는 경우가 있습니다.

해서,...
지도 이동 속도 조절이 가능한지 문의합니다.(꼭, moveLonLatBoundary() 사용해야 합니다)
아니면, 지도 이동 완료 후 콜백 함수를 호출할 수 있는지도 문의합니다.

예)
moveLonLatBoundary(xy, xy, speed);

또는

moveLonLatBoundary(xy, xy, ()=>{
  blinkBuilding();
});

**Comment by SeongRyong-Choi** [comment]
말씀하신 내용 확인하여 기능을 추가하였습니다.

1. 카메라 이동 완료 이벤트
 Fire_EventCameraMoveEnd 이벤트를 등록하여 사용하시면 됩니다.
반환값으로 경도, 위도, 높이 값을 반환합니다.
canvas.addEventListener("Fire_EventCameraMoveEnd", function(e) {
	console.log(e.longitude, e.latitude, e.altitude);
});


2. 카메라 이동 속도 제어 API
Module.getViewCamera().setCameraSpeed(1); 
초기값으로 1이 세팅되어있으며 인자값(int형)을 입력하여 속도 제어가 가능합니다.

**Comment by HyunSeongKil** [comment]
엔진 버전 : Version 1.3.15.7.2 (2021-05-31)


2. 카메라 이동 속도 제어 API
  - setCameraSpeed()의 파라미터를 변경해 가며 테스트하고 있으나, 속도 차이를 모르겠습니다.
  - 1과 12345 두개의 값으로 테스트해 보고 있습니다.
  - 큰값을 넣으면 빨라지는 건가요?

  - 그리고
  - getCameraSpeed() 함수가 없는거 같습니다.
  - 함수 추가 요청 드립니다.

**Comment by HyunSeongKil** [comment]
엔진 버전 : Version 1.3.15.7.2 (2021-05-31)

 콜백함수 호출하는건 불가능한가요?


1. 카메라 이동 완료 이벤트
  - 2번으로 테스트중이라 아직 1번은 테스트전입니다.

  - 그런데...
  **- 콜백함수 호출하는건 불가능한가요?**
  - 보통...js는 비동기 처리를 위해 callback, promise, async/await등을 사용하는데
  - 엔진은 이것과는 다른 방법으로 처리가 되서....
  - 지도를 이동시키는 함수와 이벤트 처리하는 함수가 서로 달라서, 파라미터 전달등의 귀찮음(?)이 있습니다...쩝

**Comment by SeongRyong-Choi** [comment]
말씀하신 내용 확인하여 기능을 추가하였습니다. 수정 된 새 엔진 적용 부탁드립니다.

콜백함수 호출 방안에 대해서는 엔진 내부적으로 묶여있어 논의 후 답변드리겠습니다.

**Comment by SeongRyong-Choi** [comment]
말씀하신 callback 함수 추가하여 샌드박스에 업데이트 하였습니다.

수정 된 새 엔진 적용 부탁드립니다.

http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=camera_set_viewrect
