### ISSUE TITLE
WMTS 영상지도 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#170]
http://sandbox.dtwincloud.com/code/main.do?id=layer_wmts

영상지도 선택하면 흐릿하게 제대로 뜨지 않습니다

확인부탁드립니다

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

국토정보플랫폼 영상지도의 경우 다른지도와는 다르게 proxy를 사용하고있습니다.

그렇기에 국토정보플랫폼 내부적으로 proxy서버 오류가 발생할 경우 영상지도가 제대로 서비스되지 않는 현상이 있습니다.

해당 문제는 국토정보플랫폼 내부적으로 proxy서버 오류가 해결되어야 가능합니다.

감사합니다.
