### ISSUE TITLE
WMTS 영상지도 문의 2번째

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#171]
참고 url:  http://sandbox.dtwincloud.com/code/main.do?id=layer_wmts

이지스 엔진을 최초 실행하면 기존으로 깔려있는 지도가 있습니다
위 url의 api를 사용하여 일반지도를 올렸다면
다시 최초 기존 깔려있는 지도로 기존지도를 change하는 방법이 있을까요?
위 url의 영상지도기능이 국토정보플랫폼문제로 쓰기 어려워서 기존 깔려있는 지도로 대체하려고 합니다

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

초기화의 경우 기존에 구글, 빙맵, 아크맵, OSM등의 배경지도 초기화 API를 활용하고 있습니다.

따라서 배경지도 초기화와 동일하게 **Module.SetPlanetImageryType(0);**  를 사용하시면 초기화 할 수 있습니다.

감사합니다.
