### ISSUE TITLE
DEM이 올라왔을때 Billboard, poi 높이 자동계산

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#172]
안녕하세요.
저희가 지금 3기 신도시에 시설물을 가시화 하는데 가지고 있는 데이터는 아래 포멧과 같습니다
[[lon, lat], [lon, lat], [lon, lat]]
해당 데이터를 가지고 아래와 같은 로직을 구현하여 특정위치에 시설무를 가시화 하는데 문제점이 2가지가 있습니다.
arrList[i].alt = map.getTerrHeightFast(arrList[i].lon, arrList[i].lat) + 3;
const p = new Module.JSVector3D();
(p.Longitude = arrList[i].lon), (p.Latitude = arrList[i].lat), (p.Altitude = arrList[i].alt);
billboard.set(p, icon, 2.0, 3.0); //set here that icon's 'width & height(2,3)

1. 특정 lod Level에서 height를 알 수가 없어 하드로 넣을 수없다.
2. 런타임에 계산해서 넣자고 하니 DEM(LOD 레벨이 낮아지는중) -> getTerrHeightFast가 인터넷이 느려 getTerrHeightFast -> DEM(LOD 레벨이 낮아지는중) 상태로 호출이 되면 DEM레벨이 높았을때 높이 값을 가지고 시설물을 배치하게 되니 DEM의 LOD 레벨이 상세해졌을때 시설물이 붕뜨는 현상이 일어나고 있습니다
![image](https://user-images.githubusercontent.com/3315478/160569498-0b486e62-5fa9-49b0-a8cc-8c615b257395.png)

DEM이 바뀔때마다 Billboard의 POI가 자동으로 계산되어 땅에 붙는 API가 있을까요?

**Comment by avamk2** [comment]
안녕하세요

DEM 자동결합부분에 대해서 이야기를 들이면 결론적으로는 **현재는 실시간 결합기능을 갖고 있지 않습니다.**
해당기술은 저희 과거 제품인 엑티브X에서는 갖고 있는 기술인데 WebGL 엔진으로 넘어오면서 반영되지 않았습니다.
해당사유는 현 WegGL에서 멀티쓰레딩 환경으로 쓰기 어려운 구조라서 저러한 실시간 보간작업을 메인쓰레드에 올리니 보간시점때 마다 지형데이터 로딩후 보간작업을 일괄적인 수행을 하다보니 보간할 객체의 수가 어느정도되면 성능적인 문제가 발생하기 때문입니다.

현재 실시간 지형결합에 대한 R&D는 예정에 있지만 만족할 성능이 나오기 전까지는 SDK 환경적, 저희 기술적 탐구가 더 필요한것으로 보입니다. 위에 언급했듯 100개 미만에서 쓴다면 의도한 기능이 잘 동작할지 모르지만 이것이 500개, 천개, 5천개 수준에 객체를 넣고 동작할때 성능에서 치명적인 저하가 발생하면 실무적으로는 쓸모없는 기능이 됩니다.

현재의 시점에서 가장 최선은 서비스용 데이터를 준비하는 것으로 수집한 2차원 데이터를 높이값을 맵핑하여 3차원 데이터로 만들어 이를 DB화 해두고 사용하는 것을 권장합니다. 서버기반에서 높이값 참조는 런타임에서 쓰기에는 느린것이지만 데이터 자체가 잘못된것은 아니기에 3D 포인트를 만들기위한 사전작업에서 사용하여 xx를 xyz로 DB에 기록후에 사용하면 런타임에서는 높이값이 계산된 데이터로 사용되니 높이값 참조 과정이 빠져서 더 최적화되게 됩니다.

DEM 실시간 결합기술은 단기적으로는 어렵지만 중장기적로 만족할 성능이 되는 시점에서 도입할 예정입니다.

**Comment by loeaf** [comment]
setTerrLodRatio 를 통해 정적값을 취득하고 db화하여 가시화 하는식으로 해결했습니다~!
