### ISSUE TITLE
해당 맵컨트롤만 활성

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#173]
해당 맵컨트롤만 활성화 가능할까요?
고객이 정북방향 위치를 알고싶답니다 ㅡㅡ... 그런데 밑에있는 컨트롤과는 기능 및 디자인이 상충되서 숨겨야 할꺼 같아요~
![image](https://user-images.githubusercontent.com/3315478/161224730-c3e41ee8-5f60-4ac7-9dc8-0b8279a84b2f.png)

**Comment by YunSumin** [comment]
해당 모듈을 한 셋으로 구성되어 있어 부분적인 활성화는 불가능합니다.
대신 맵 컨트롤을 전체 off 시킨 후
마우스 드래그 이동 시 카메라 방향 값을 받아 이미지를 회전 시키는 방식으로 구현 가능할 것 같습니다.

1. 정북 방향을 표시할 적절한 이미지를 페이지에 추가합니다.
```
<img id="direction" style="width:100px;height:100px;" src="방위표시이미지URL">
```

2. 지도 캔버스 지도 드래그 조작 시 카메라 방향 값으로 이미지를 회전.
```
var mouse_button_press = false;

Module.canvas.onmousedown = function(e){
    mouse_button_press = true;
};

Module.canvas.onmouseup = function(e){
    mouse_button_press = false;
};

Module.canvas.onmousemove = function(e){
    if (mouse_button_press) {
        document.getElementById("direction").style.transform = "rotate("+Module.getViewCamera().getDirect()+"deg)";
    }
};
```

**Comment by loeaf** [comment]
감사합니다!
