### ISSUE TITLE
두점이 있을때 마지막 점을 바라보게 DIRECT를 구하는 API

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#175]
안녕하세요!
두점이 있을때 시작점에서 마지막 점을 바라보게 하기 위한 Camera DIRECT를 구하는 API가 있을까요??
감사합니다!

**Comment by YunSumin** [comment]
안녕하세요,
두 경위도 지점의 방향 각도를 계산하는 함수는 이슈 #166 에서 안내 된 함수를 활용하실 수 있습니다.

혹시 이슈 #173, #174 와 연계하여 특정 지점을 중심으로 방향 각도를 지정하는 함수가 필요하시다면
아래 함수를 활용하실 수 있습니다.
특정 지점에서 특정 방향을 바라보도록 카메라를 이동시키는 함수입니다.

```
function setDirect(_center, _targetDirect) {

    // 설정 방향 각도는 -180도~180도 내로 설정(정북 방향 0도 기준)
    if (_targetDirect < -180.0 || _targetDirect > 180.0) {
        return;
    }

    // 현재 카메라 위치 반환
    var camera = Module.getViewCamera();
    var cameraPosition = camera.getLocation();

    // 지정한 중심점(_center)에서 지정한 방향(_targetDirect)에 위치하는 좌표 계산
    var map = Module.getMap();
    var distance = map.GetPointDistance(
        _center,
        new Module.JSVector3D(cameraPosition.Longitude, cameraPosition.Latitude, _center.Altitude),
        false
    );
    var lookFrom = map.getPositionByAngleDistance3D(_center, distance, _targetDirect+180.0);
    lookFrom.Altitude = cameraPosition.Altitude;
        
    // 카메라 이동
    camera.look(lookFrom, _center);
}
```

API getPositionByAngleDistance3D, GetPointDistance 에 대한 상세 설명은 이슈 #165 상세 내용에서 확인하실 수 있습니다.
감사합니다.

**Comment by YunSumin** [comment]
위에 게시 된 setDirect는 아래와 같이 호출하여 사용하실 수 있습니다.
```
setDirect(new Module.JSVector3D(127.49221428383773, 37.49729869843215, 46.841232187114656), 0);
```

**Comment by loeaf** [comment]
두점만 알고있고 direct는 모르는 상황입니다.
질문한것과 답변한것 내용이 다른거 같아요 ㅠㅠ...
0,0,0 1,1,1 이라고 하면 0,0,0 에서 1,1,1을 바라보게 하기 위하여 setDirect()를 하고 싶은데 setDirect안에 들어가는 direct값을 어떻게 구할 수 있는지를 질문드리고 있습니다 ㅠㅠ...

**Comment by YunSumin** [comment]
단순 방향 각도만 필요하시다면
위에서 안내 드린 이슈 #166 함수로 경위도 좌표 간 방향 값을 구하신 후 setDirect API에 적용하시면 됩니다.

**Comment by loeaf** [comment]
감사합니다!
