### ISSUE TITLE
Openlyaer에서 이지스 맵 WMS 사용

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#176]
안녕하세요 Openlayers에서 WMS로 이지스 Vworld 맵과 2D 레이어 맵을 쓰고 싶습니다
가능할까요??

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 

브이월드 및 Openlayers는 저희 서비스가 아닙니다.

그러므로 Openlayers에서 VWorld맵을 사용하기 위해서는 

https://www.vworld.kr/dev/v4api.do 사이트를 참조하시면 좋을것 같습니다.

감사합니다.

**Comment by loeaf** [comment]
안녕하세요!
전달이 약간 잘못된거 같아용
현재 이지스로부터 2D레이어를 발행받아 레이어를 가시화 하고 있는데 해당 2D 조감도(바닥 영상)을 WMS로 어떻게 받아와 openlayer에서 서비스가 가능한지를 물어보는거에용!
![image](https://user-images.githubusercontent.com/3315478/162344322-ded6dbfb-fb8c-4b1c-8ce2-84d62b8c2eaf.png)

**Comment by YunSumin** [comment]
안녕하세요,
엔진 API 외 다른 작업에 대한 배경이 없는 상태라 문의 드립니다.
2D 레이어를 발행 받으신 것과 관련하여 자세한 말씀 부탁 드립니다.

XDWorldEM 엔진에서 지오서버 WMS 레이어를 사용하는 방법에 대해서는 안내 드릴 수 있으나,
수급 받으신 데이터를 WMS로 받아오거나 오픈레이어즈에서 WMS 데이터를 서비스하는 방법은 저희가 자세히 안내 드리기 어렵습니다.

**Comment by YunSumin** [comment]
연구소 내 관련 직원을 통해 연락 드리도록 내부 협의 되었습니다.
