### ISSUE TITLE
LOD 드론영상 아래의 객체가 묻히는 현상

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#178]
![image](https://user-images.githubusercontent.com/49426364/164184426-bd0f1663-af87-4ca3-aff1-eb251d6b7114.png)

안녕하세요.

MML_INPUT_LINE, MML_INPUT_RECT, MML_INPUT_CIRCLE로 마우스 모드를 변경하여
지도 상에 객체를 그렸을 때 그려진 객체 위에 LOD 드론영상이 있으면 드론영상의 높이값 때문에
위의 이미지와 같이 드론영상 아래의 객체들은 묻히게 됩니다. 

그려진 객체들이 위에 레이어가 떠있어도 레이어 위에 표출될 수 있도록
그려줄 수 있는 방법이 있을까요..?

**Comment by YunSumin** [comment]
안녕하세요,

MML_INPUT_LINE, MML_INPUT_RECT, MML_INPUT_CIRCLE 모드의 인터페이스는
모두 지형을 대상으로 동작하도록 구성되어 있어 객체 위로 라인을 띄우는 것은 힘들 것 같습니다.

단, 마우스 모드가 아닌 일반 라인으로는 생성이 가능합니다.
아래 코드는 연구소 내 테스트용으로 작성한 코드를 일부 발췌한 코드로

1. 입력 점 추가
2. 입력 점을 일정한 간격으로 분절한 좌표 리스트 반환
3. 각 좌표 리스트의 지형, 드론 LOD 고도 값 반환

과정을 거쳐 드론 LOD 를 고려한 좌표 리스트를 반환합니다.

```
function getCrossSections(_pathPoints) {

	var pointCount = _pathPoints.count();
	if (pointCount < 2) {
		return;
	}

	var result = {
		positions : [],	// 지점 위치
		drone : [],	// 드론 LOD 고도
		dem : []	// 지형 고도
	};

	var map = Module.getMap();
	var layerList = new Module.JSLayerList(false);
	var layer = layerList.nameAtLayer("tile_LOD_yangp");
	
	for (var i=0; i<pointCount; i++) {

		// 고도 값을 계산 할 경위도 좌표 반환
		var position = _pathPoints.get(i);
		result.positions.push(position);

		// DEM 고도 반환
		result.dem.push( map.getTerrHeight(position.Longitude, position.Latitude) );

		// 레이어와의 충돌지점 반환 
		if (layer != null) {

			// 지면과 수직한 라인을 만들어 드론LOD 객체와의 충돌지점 반환 
			var pickPosition = layer.getPickInfoAtView(
				new Module.JSVector3D(position.Longitude, position.Latitude, 10000.0),
				new Module.JSVector3D(position.Longitude, position.Latitude, -10000.0)
			);
			
			if (pickPosition == null) {
				result.drone.push(0);	// 충돌 점이 없는 경우 고도 값 0으로 처리
			} else {
				result.drone.push(pickPosition.position.Altitude);
			}
		}
	}

	return result;
}
```

위 단계를 거쳐 생성된 좌표 값을 활용해 JSLineString 오브젝트를 생성하면
아래와 같이 드론 LOD 레이어의 고도 값도 함께 적용하실 수 있습니다.

![image](https://user-images.githubusercontent.com/82925313/165439263-cbc7463c-1f27-4554-9bac-a3badf9f18a2.png)

활용 된 API는 아래 문서 참조 부탁드립니다.

[JSMap] getTerrHeight 
https://egiscorp.gitbook.io/xdworld-webgl-manual/map/jsmap#getterrheight-lon-lat-number 참조

[JSLayer] getPickInfoAtView
입력한 라인과 레이어 객체 간 충돌점을 반환합니다.
  * Parameter : 충돌 라인 시작점과 끝점
  * Return : 충돌 지점 (충돌 지점이 없는 경우 null 반환)
