### ISSUE TITLE
객체의 좌표를 확인하는 부분 문의 (JSLingString)

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#179]
안녕하세요.

객체를 클릭해서 그 클릭한 객체의 좌표를 화면에 표출하고자 합니다.
JSPoint나 JSPolygon는 문제없이 좌표를 잘 가지고 오는데
JSLineString는 좌표값이 이상한 값으로 표출이 되네요.

1. line 객체 생성 [*inputPoint = map.getInputPoints()]
function createLine(inputPoint){
	// 점 수가 2점 이상인 경우 진행
	var inputPointCount = inputPoint.count();
	if (inputPoint < 2) {
		return;
	}

	// 라인 객체를 저장할 레이어 생성 (이미 생성한 경우 레이어 반환)
	var layerList = new Module.JSLayerList(true);
	var layer = layerList.nameAtLayer("LINE_LAYER");
	if (layer == null) {
		// 레이어가 없는 경우 새로 생성
		layer = layerList.createLayer("LINE_LAYER", Module.ELT_3DPOINT);
	}

	// 라인 객체 생성
	var currentLayerObjectCount = layer.getObjectCount();
	var line = Module.createLineString("LINE_" + currentLayerObjectCount);
	
	var lineCoordinate = [];
	for (var i=0; i<inputPointCount; i++) {
		lineCoordinate[i] = [inputPoint.get(i).Longitude, inputPoint.get(i).Latitude, inputPoint.get(i).Altitude];
	}
		
	//라인 형태
	line.createbyJson({
		coordinates: {
            coordinate: lineCoordinate,
            style: 'XYZ'
		},
	    type: 0, 	
	    union: false, 
	    depth: false, 
	    color: new Module.JSColor(255, 255, 0, 0), 
	    width: 5
	});
	
	// 레이어에 객체 추가
	layer.addObject(line, 0);
}

2. 객체 조회 부분
// 레이어 반환
	var layerList = new Module.JSLayerList(true);
	var layer = layerList.nameAtLayer(layerName);

	if (layer == null) {
		return;
	}
	
	// 오브젝트 반환
	var object = layer.keyAtObject(objkey);
	if (object == null) {
		return;
	}

var coorText = "";
		
		for (var i=0; i < object.getCoordinates().count; i++) {
			var vCoord = object.getCoordinates().item(i);
			
			coorText += "<br>" + (i+1) + "." 
			+ "<br>LON : " + parseFloat(vCoord.Longitude).toFixed(6) 
			+ "<br>LAT : " + parseFloat(vCoord.Latitude).toFixed(6)
			+ "<br>ALT : " + parseFloat(vCoord.Altitude).toFixed(3);
		}
		
여기서 object.getType가 JSLineString 인 object의 Coordinates() 값이 그 위치의 값이 나오지 않습니다.

- 라인 객체를 추가한 화면
![image](https://user-images.githubusercontent.com/104063285/164189422-3be4a2ea-f65f-4816-a570-d4dd4ec253b5.png)

- 추가한 객체의 좌표 정보를 조회하는 화면
![image](https://user-images.githubusercontent.com/104063285/164190286-8650505e-0a21-4a66-8ba6-9957845c7b89.png)

혹시 버그인지 확인 좀 부탁드립니다.

**Comment by YunSumin** [comment]
안녕하세요,

문의 주신 내용을 토대로 JSLineString 오브젝트 생성 부분에서 오류 원인을 확인하여 수정하였습니다.
현재 배포 된 최신 엔진으로 교체 부탁 드립니다.

감사합니다.
