### ISSUE TITLE
wms 갯수 이슈???

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#18]
안녕하세요. 바이브컴퍼니입니다.

wms 5개 추가하면 동영상과 같은 현상이 발생합니다.

엔진단에 이슈 있는지 확인 요청 드립니다.
저도, 업무 로직단 확인해 보겠습니다.

https://user-images.githubusercontent.com/38479834/120482494-2a0b1680-c3ec-11eb-96e7-00a77dc29601.mp4

https://user-images.githubusercontent.com/38479834/120482508-2bd4da00-c3ec-11eb-9130-b73111cfb266.mp4

**Comment by YangHeeBong** [comment]
지형 타일 텍스쳐 랜더링 가능 갯수는 아래와 같습니다.
기본 영상 이미지 1개, wms, hybrid 4개 입니다.
이미지 제한을 둔 이유는 메모리 사용량을 조절하기 위해서 입니다.

**Comment by SeongRyong-Choi** [comment]
여러개의 레이어를 사용하기 위해서 geoServer에서 지원해주고 있습니다.
WMS요청시 레이어명을 레이어1,레이어2,레이어3 으로 콤마를 구분자로 하여 여러개의 레이어를 하나의 레이어처럼 호출할 수 있습니다. 스타일도 레이어와 마찬가지로 콤마를 이용하여 여러개의 스타일을 하나의 스타일처럼 호출할 수 있습니다.

**Comment by HyunSeongKil** [comment]
알겠습니다.
