### ISSUE TITLE
안녕하세요 3ds 폴리곤 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by jdevil0313** [EgisCorp/XDWorld#183]
안녕하세요.
http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit
여기 예제 보시면 스케일을 변경 할 수 있는데

http://sandbox.dtwincloud.com/code/main.do?id=object_file_3ds
여기 예제에는 다른 방식으로 3ds를 심볼을 등록하긴 하는데 위에 예제처럼 scale를 변경할 수 있는 방법이 있나요?

**Comment by YangHeeBong** [comment]
안녕하세요 질문에 대해서 답변드리겠습니다.

일단 첫 번째, 두 번째 샘플은 다른 기능을 담당하고 있습니다.

고스트 심볼은 오브젝트 복사, 수정, 이동과 같은 기능을 첨부하여 조작할 수 있지만

폴리곤으로 생성한 오브젝트는 이동 기능만 제공하여 빠른 가시화를 위해서 다른 수정 기능이 빠져 있습니다.

3DS 수정 기능이 필요하시다면 고스트 심볼 방식으로 작성하여 주시면 됩니다.

**Comment by jdevil0313** [comment]
감사합니다!
