### ISSUE TITLE
3DS 강제 선택(빨간색)되도록 하는 방법

### ISSUE THREAD

**Issue by jdevil0313** [EgisCorp/XDWorld#184]
안녕하세요. 대구 사무실 이준호입니다.

http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit
위의 샘플을 참고하여 3DS 레이어를 표출하였는데,
3DS 객체를 마우스 클릭했을 때 빨갛게 변하는 것처럼,
함수를 통해 특정 객체를 빨갛게 선택되도록 할 수 있는 방법이 있을까요?><

![image](https://user-images.githubusercontent.com/25459278/168967327-52ece53b-9073-4f40-97db-6c3b88b24d34.png)
![image](https://user-images.githubusercontent.com/25459278/168967384-6be1072c-833d-42d3-a9f4-3615d88f12ac.png)

**Comment by YangHeeBong** [comment]
안녕하세요 질문에 대해서 답변드리겠습니다.

API 기능을 통해 오브젝트를 선택 모드로 변경하는 API는 

JSMap 클래스에서 제공하는 setSelectObject( JSObject )으로 변경 할 수 있습니다.

전체적인 흐름은

1. 오브젝트가 포함된 레이어 지정
2. 지정된 레이어에서 오브젝트 반환
3. 반환 된 오브젝트를 통해 선택 모드 변환 입니다.

[메뉴얼](https://egiscorp.gitbook.io/xdworld-webgl-manual/layer/jslayer)을 통해 내용을 확인 하실 수 있습니다.
- 메뉴얼은 지속적으로 업데이트 중입니다.

 ```javascript
// 사용 예제
let layerList = new Module.JSLayerList(false);
let layer = layerList.nameAtLayer("오브젝트가 포함된 레이어 명칭");
let object = layer.keyAtObject("선택 모드 변경  오브젝트 ID");
Module.getMap().addSelectObject(object);
```
