### ISSUE TITLE
DDS 로드 관련 문의

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#185]
안녕하세요.

처음엔 여러 개의 하이브리드 이미지를 배경영상으로 on/off 하며 쓰려고 했지만, 
하이브리드 이미지는 최대 7개까지 밖에 가시화가 안된다고 하여
통으로 묶어 DDS를 생성하여 지도 호출 시 Module.Start 전에 
Module.XDESetSatUrlLayerName을 사용하여 DDS를 호출하고 있습니다.

만약 배경으로 사용되어지는 DDS가 버전이 여러 개 있고, 그 버전을  선택하며 보고 싶을 때
일반 layer처럼 여러 개의 DDS를 호출하여 사용가능한지,
setVisble과 같이 가시화 여부를 결정할 수 있는 API가 있는지 알고 싶습니다.

**Comment by hjaejae** [comment]
안녕하세요~
질문해주신 내용을 보니 기본 지도가 있고 그 기본지도를 바꾸고 싶어하시는것 같습니다.

하이브리드 이미지가 최대 7장만 가능하다는것은 겹쳤을때 그런것이라서
교체하는 방식으로도 하이브리드 방식이 가능 할듯합니다.
하이브리드 샘플 : http://sandbox.dtwincloud.com/code/main.do?id=layer_wmts_hybrid(서버 사정상 작동 안되는 url도 있습니다.)

아니면 WMTS 방식으로 하시면 가능할듯합니다.
WMTS 서비스 : http://sandbox.dtwincloud.com/code/main.do?id=layer_vworld_wmts
