### ISSUE TITLE
고스트 심볼 관련 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#186]
안녕하세요.

고스트 심볼 생성 시 콘솔창에 아래와 같은 오류가 뜨는데 원인을 모르겠어요.

		Module.getGhostSymbolMap().insert({
			id : id,
			number: i,
			url : "./images/poi/3ds/SL251.3ds",
			callback : function(e) {

				console.log('e : ', e);

				// 텍스쳐 설정
				Module.getGhostSymbolMap().setModelTexture({
					id : e.id,
					//face_index : 0,
					url : "./images/poi/3ds/SL251.JPG",
					callback : function(e) {
						console.log(e.id);
					}
				});

				// 오브젝트 생성 및 레이어 추가

				var position = [data[e.number].lon, data[e.number].lat, data[e.number].alttd];
				var object = _this.createGhostSymbol(e.id, e.id, position);

				GLOBAL.PoiLayer.addObject(object, e.number);
			}
		});

![1](https://user-images.githubusercontent.com/91519109/177103739-29f40717-7942-4418-8da6-47aba829a3eb.png)

**Comment by YunSumin** [comment]
안녕하세요!

해당 현상은 1.37.9 버전에서 오류 접수되어 1.37.10 버전에서 패치 되었습니다.
1.37.10 버전 엔진으로 교체 부탁 드립니다!

감사합니다.

**Comment by suhwna** [comment]
감사합니다!
