### ISSUE TITLE
경사도 분석 / 라인 그데이션

### ISSUE THREAD

**Issue by YenaYena** [EgisCorp/XDWorld#187]
안녕하세요, 아래와 같이 경로에 대한 고도와 경사도 그래프를 표출하고자합니다.
지점 사이 경사도 값을 불러오거나 경로의 좌표 배열로 경사도를 한꺼번에 가져올 수 있는 방법이 있는지 문의드립니다.

![고도프토필문의](https://user-images.githubusercontent.com/34873103/177263171-6c168d19-b52f-427b-9213-8e997b285923.jpg)

또한 라인 생성시 시작점과 끝점에 색상을 그라데이션 하여 표출할 수 있는지 문의드립니다.

감사합니다.

**Comment by hjaejae** [comment]
안녕하세요~
현재 입력된 점에 대한 경사도를 바로 가져오는 API는 없습니다.
행당 기능은 아래 소스 처럼 입력된 점을 받아와서 직접 경사도를 구하시면 됩니다.

var map = Module.getMap();
var inputPoint = map.getInputPoints();
var inputPointCount = inputPoint.count();
for (var i=0; i<inputPointCount-1; i++) {
	var point1 = inputPoint.get(i);
	var point2 = inputPoint.get(i+1);
        // 두 점 경사도 구하기
}

두 점의 거리와 높이값을 알고 있으면 경사도를 구할수있습니다.

**Comment by YenaYena** [comment]
답변 감사드립니다.
혹시 두점 사이 경사도가 아닌
구글어스의 elevation profile(https://www.youtube.com/watch?v=FxmnI6D0Mg4) 기능처럼
지점 사이의 지형 단면도의 그래프를 가져올수 있는지 문의드립니다.

**Comment by hjaejae** [comment]
해당 기능은 UI 및 컨트롤 문제 등으로 엔진에서의 역활이 아니여서
점 리스트를 가져온 후 웹에서 해당 기능을 구현하셔야 합니다.

**Comment by minochae** [comment]
안녕하세요. 서울 사무실 채민호 입니다.
정예나 대리가 문의한 경사도는 경사도 그래프를 그릴수 있는 기반데이터를 제공하는 API를 요청드린것입니다.
기존 브이월드에서 제공하던 API인데 웹에는 없나요? 없으면 추가 가능한지 검토 부탁드립니다.

**Comment by hjaejae** [comment]
일정 라인을 입력한 후 단위 거리(예 1m) 대한 높이 값을 가져 올 수는 있습니다.
현재 로딩되어져있는 상태(메모리) 기반에서 가져올 때랑 서버의 최상위 데이터를 가져 올 때랑의 값이 다른데
서버 기반의 데이터가 필요하신듯합니다.
서버 기반의 데이터를 가져오는 내용에 대해서는 팀 내부적으로 논의가 필요할듯합니다.

라인의 색상에 그라데이션 효과를 넣는 부분은 추후에 기능 업데이트 할수 있도록 하겠습니다.
