### ISSUE TITLE
시계열 폴리곤 데이터값 문의

### ISSUE THREAD

**Issue by kkang222** [EgisCorp/XDWorld#188]
안녕하세요. 이지스 한유경주임입니다.
시계열 폴리곤기능을 사용하려합니다.
샌드박스에 있는 해당 데이터(csv파일)를 다운받으면 아래와같이 나오는데, 이 값들의 의미가 무엇인지,
또 csv 파일들 (1.csv, 2.csv ... )의 차이점이 무엇인지 알고싶습니다. 
![image](https://user-images.githubusercontent.com/107455219/177920595-63205e07-efed-4356-b3d5-01e3105758fa.png)

**Comment by avamk2** [comment]
안녕하세요 
http://sandbox.dtwincloud.com/code/main.do?id=effect_time_visualization 예제에서 사용되는 csv 데이터에 대한 내용을 문의 주시는 것인가요?

질문에 답을 드리면
데이터 자체는 섬진강 지역의 강쪽 관련된 샘플 데이터 입니다.

해당 표현을 위한 기본적인 그리드 정보 설정은 function parseData(_data)의 초기 코드부분에 상수로 정의되어 있습니다.
그리고 그리드 각 셀정보가 1차원 배열로 구성되어서 나열되어 있습니다. 이중 -9999는 분석결과에 nodata 구역이 됩니다. 셀에 값들을 정리하여 각 위치별 높이 및 색상을 적용하게 되는게 해당 기능입니다.

시계열 데이터이기 때문에 각시간 흐름별로 파일이 존재하며 이것이 1.csv, 2.csv 식으로 시간흐름별 격자 데이터를 분리되어 있습니다. 현재는 애니메이션을 위해서 8개의 데이터를 로딩 후에 1~8까지의 변화 추이를 보여주는 기능에 대한 데모입니다.

**Comment by kkang222** [comment]
타지역에 대한 시계열 폴리곤기능(SandBox의 가시화형상)을 구현하고 싶은데 
csv파일없이 DB에서 불러온 값으로 바로 가시화 가능한지, 
불가능하다면 해당 그리드 영역과  백데이터(CSV 격자 데이터)로 가공하는 방법이 무엇인지,
또 function parseData(_data)의 초기 코드부분에 상수로 정의되어있는 ncols, nrows, xpos, ypos, cellSize 의 값들이 정확히 무엇을 의미하는지 궁금합니다!
