### ISSUE TITLE
가시권 분석 2D 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#189]
안녕하세요.

가시권 분석 2D 기능 사용 시, 사진과 같이 건물과의 높이가 일치하지 않는데 왜 이런 건가요?

![화면 캡처 2022-07-20 133138](https://user-images.githubusercontent.com/91519109/179897859-6b94beb5-a2fe-4d3a-ba7e-41de9f2da32e.png)
![화면 캡처 2022-07-20 133003](https://user-images.githubusercontent.com/91519109/179897869-9a6d4994-d516-4e06-9e60-d4fd9bb63cdc.png)

**Comment by YangHeeBong** [comment]
안녕하세요 

가시권 분석(2D) 기능 테스트 중 현재와 같은 문제는 나타나지 않아 몇 가지 질문이 있습니다.

1. 엔진 로드 시 출력 되는 엔진 버전은 몇버젼으로 구성되나요?
2. 현재 건물은 서비스 타일 레이어 서비스 인가요? 아니면 고스트 심볼이나 오브젝트를 따로 출력하신건가요?
3. 서비스 타일 레이어 라면 레이어 타입은 어떻게 되나요?

샌드박스 테스트 기준으로 아래와 같은 결과가 나왔습니다. 

테스트 결과(샌드박스 가시권분석)
![image](https://user-images.githubusercontent.com/82924515/179900024-98f2c93a-ab9f-4248-bf11-9833224e3b8e.png)
테스트 기본 정보
- 엔진 버전 : 1.37.11
- 테스트 서비스 타일 레이어 명칭 : facility_build
- 테스트 서비스 타일 레이어 타입 : Module.ETLT_REAL3D (9)
- 테스트 마우스 모드 타입 : Module.MML_ANALYS_VIEWSHED (82)

**Comment by suhwna** [comment]
1. 엔진 버전은 1.36.5입니다.
2. 타일 레이어입니다.
3. 타입은 Module.ETLT_REAL3D (9)입니다.

Module.XDEMapCreateLayer("pcg_facility_build2", mapServer, 0, true, true, false, 9, 0, 14); // 일반건물

**Comment by YangHeeBong** [comment]
알려주신 버전은 4개월 전 엔진으로 최신화 후 테스트를 부탁드립니다.

만약 동일한 문제가 발생한다면 서비스 타일 레이어 데이터에서 기술 검증이 필요할 것 같습니다.

**Comment by suhwna** [comment]
![화면 캡처 2022-07-22 102017](https://user-images.githubusercontent.com/91519109/180341303-bfa9f1bc-7ee4-4a8e-8649-7f153cf76f0d.png)
![화면 캡처 2022-07-22 102042](https://user-images.githubusercontent.com/91519109/180341305-55a97c6a-4472-4df8-b497-da5e0f261b5f.png)

사진처럼 분석 위치가 건물 높이 오차만큼 지면과 떨어져있는데 원래 이런건가요?

**Comment by YangHeeBong** [comment]
동일한 증상 확인 결과 다음과 같은 결과를 확인 하였습니다.

- 카메라가 고도에 따라 가시화 지형 레벨은 동적으로 변경
- 가시권 분석 2D는 현재 가시화 지형 레벨에 설정된 고도를 기준점으로 생성
입니다.

위 문제는 지형 레벨이 갱신 되고 분석하는 방법으로 테스트를 부탁 드리고 이 문제에 대해서 가시권 분석 담당자에게 내용을 전달하여 수정 하도록 하겠습니다.

**Comment by YangHeeBong** [comment]
![image](https://user-images.githubusercontent.com/82924515/180938084-5315d69a-10ec-440e-90f7-030eed3ce9f9.png)
 
엔진 버전 : 1.37.17

위 엔진 버전은 초기 입력 고도값을 참조하지 않고 건물 절대고도 값으로 가시권 분석을 처리 하도록 하여 2~3미터 유격(지형레벨 갱신에 따른 고도값)이 발생해도 기존 지붕 형태가 올라가는 현상이 없습니다.

**Comment by suhwna** [comment]
감사합니다!
