### ISSUE TITLE
3ds파일 가시화 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#19]
안녕하세요. 바이브컴퍼니입니다.

간단하게 3ds파일 가시화 테스트 해 보려고 합니다.

어떻게 하면 될까요?

**Comment by YunSumin** [comment]
샌드박스에 고스트 심볼 샘플페이지를 참조하실 수 있을 것 같습니다.
http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=object_ghost_symbol

하나의 3DS 파일을 로드하고 위치, 방향, 스케일 등을 다르게 주어 배치한 샘플입니다.

**Comment by HyunSeongKil** [comment]
알려주신 링크로 들어갔는데 아래 이미지와 같은 오류가 발생했습니다.
(사이트 접속만 했는데 바로 오류 발생했습니다)

제가 전에 올린 태풍 이동시 발생했던 오류와 같은 것으로 생각됩니다.

![image](https://user-images.githubusercontent.com/38479834/120613415-31383000-c491-11eb-9258-daef14c83ed3.png)

**Comment by YangHeeBong** [comment]
몇가지 사항을 알려주시면 좋겠습니다.

1. OS 종류
2. 브라우저 종류

소스코드 수정 없이 위와 같은 오류가 뜬다면 브라우저 일 가능성이 높습니다.

저희쪽에서 위와 같은 오류가 발생하는지 확인 결과 동일 증상은 없었습니다.

지금 개발하신 환경과 비슷한 조건으로 테스트 해야 정확히 알 수 있을 것 같습니다.

**Comment by HyunSeongKil** [comment]
이지스에서도 동일한 현상이 발생하신다는 얘기죠?
현재 관련 조치를 하고 계신거죠?

**Comment by YangHeeBong** [comment]
3ds 부분 처리한 샌드박스 주소입니다. 개발 시 참조 하시면 됩니다.

샘플 예제
http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol

엔진 교체 
https://github.com/EgisCorp/XDWorld/tree/main/Release/v_0.1.1
