### ISSUE TITLE
건물레이어 고려한 고도값 가져오기 문의

### ISSUE THREAD

**Issue by YenaYena** [EgisCorp/XDWorld#190]
안녕하세요, 서울사무실 정예나 대리입니다.

getTerrHeight(pos.x, pos.y) 지형고도 가져오는 API처럼

특정 지점의 고도값을 
xdserver로부터 건물레이어(facility_build)를 고려하여 가져올수 있는 API가 있는지 문의드립니다.

**Comment by avamk2** [comment]
안녕하세요. 
결론을 미리 이야기 드리면 XDServer의 부담문제로 해당 기능을 넣지 않았습니다.

참고로 
`getTerrHeight(pos.x, pos.y)`
는 현재 클라이언트에서 이미 로딩된 지형의 DEM 데이터를 기반으로 계산하고 있습니다. xdserver의 서버기준에서 이를 처리하기 하기에 지형같은 정형화 데이터를 해석해서 처리하는 부분도 서버 부담이 있는 편입니다. 그나마 지형의 DEM은 지도 서비스상 하나의 타일공간에 하나만 존재하고 데이터 규격도 동일한 배열 값을 사용하기 때문에 산출시간이 일정하기에 사용여부에 대해서 그나마 참고가 가능합니다.

문제는 3D 건물 또는 시설물 레이어에서는 검출하고자 하는 구역에 모델 데이터가 있는지 여부부터 1개 이상의 모델이 있는 경우 각 모델 정보를 수집하고 이에 높이 값을 체크해야하며 이중 가장 높은 값을 찾는 등에 연산들이 더 부과됩니다. 여기서 3D 건물은 3D 구성 점의 수가 데이터 정밀도 수준에 따라서 다르며 클라이언트에서 이러한 요청 후 서버에서 계산 후에 이를 반환할때까지 생각보다 많은 시간이 걸리며 이에 따른 서버 부담이 커서 현재까지는 도입하지 않았습니다.

위에 이유로 단순 기능구현으로 적용하기 어려우며 연구소에서 장기간 R&D를 바탕으로 서비스 부분에 대해서 계속 검토를 할 예정입니다. 

그럼 좋은하루 되세요

**Comment by minochae** [comment]
안녕하세요. 서울 사무실 채민호 입니다.
이 문의에서 요청하고 싶은 기능은 드론이 비행할 경로 상에 위치한 건물의 바운더리 영역입니다.
해당 바운더리 영역을 구해진 경사도 그래프와 조합하여 사용자들에게 드론 비행의 정보를 제공하고자 합니다.(아래 이미지 참조)
해당 건물에 대한 바운더리는 정확한 정보를 위해 서버 기반으로 계산되기를 원하나 서버 부하가 문제 될 경우 아래와 같은 방법은 어떤가요?
> 입력된 경로에 해당하는 건물데이터를 미리 다운받아서 로컬에서 해당 정보를 계산할 수는 없을까요?
> 해당 계산을 위해 데이터 다운로드등 비동기로 시간이 소요되는 것은 문제 없습니다.
> 또한 다운로드된 데이터를 계산에만 사용하고 렌더링 하지 않았으면 합니다.

![image](https://user-images.githubusercontent.com/6679342/180889319-6e3924ea-ba04-4c54-a3d9-55ff6441cae9.png)
