### ISSUE TITLE
안녕하세요, POI 관련 문의드립니다

### ISSUE THREAD

**Issue by ren1302** [EgisCorp/XDWorld#191]
![ndvi](https://user-images.githubusercontent.com/78583075/181421198-7850c427-1c12-46a3-9108-07bfcb838869.png)
[일반 사이즈]         

![ndvi2](https://user-images.githubusercontent.com/78583075/181421212-279654bd-c59b-48ba-8496-32db47ec0926.png)
[맵 축소 사이즈]

특정 좌표 지점에 NDVI 이미지를 올렸을 때 맵 확대 축소 여부에 따라 이미지 크기가 변하는 것을 고정으로 할 수 있는 지가 궁금합니다.
아니면 저렇게 맵 레이어 느낌으로 이미지를 올렸을 때 더 좋은 구현 방법이 있으면 알려주시면 감사하겠습니다.
 
감사합니다.

**Comment by YunSumin** [comment]
안녕하세요,

해당 기능은 빌보드(JSBillboard) 객체를 활용하시면 좋을 것 같습니다.
빌보드는 아래와 같이 고유의 크기를 가질 수 있습니다.

[가까운 거리]
![image](https://user-images.githubusercontent.com/82925313/181422067-70d63a69-8b36-485a-851b-3ab0e096332b.png)

[먼 거리]
![image](https://user-images.githubusercontent.com/82925313/181422120-f2c7c41d-0b9d-4a8a-9649-99403336d7d0.png)


아래 URL에서 API 코드를 확인하실 수 있습니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_billboard_fix_size

감사합니다.
