### ISSUE TITLE
빌보드객체 관련해서 문의드립니다

### ISSUE THREAD

**Issue by ren1302** [EgisCorp/XDWorld#192]
빌보드아이콘이 수직으로 되있는걸 수평으로 눕힐수도있을까요?

**Comment by avamk2** [comment]
안녕하세요

현재 엔진에서 빌보드는 2가지 형태의 회전모드를 지원합니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_billboard_rotation

Y축 회전모드는 이미지화 된 시설물을 3D상 세워진걸 쓰기 위한 형태로 주로 나무, 풀, 가로등, 표지판 같은 곳에 사용합니다.
X-Y-Z축 회전모드는 카메라가 보는 방향을 정면으로 모든 방향이 회전해서 보여주는 모드입니다.
질문에 대한 사항이 X-Y-Z축 회전 모드인지 확인해주시기 바라며 혹시나 내용과 다르다고 생각되면 좀더 구체적인 질문으로 댓글 달아주시면 확인해서 답변드리겠습니다.
