### ISSUE TITLE
기능 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#193]
안녕하세요!

1. 특정 지역만 보이게 하고 나머지 지역은 투명하게 만드는 방법이 있을까요? 

2. 폴리곤 색상 설정 시 윗면과 아랫면만 다른 색상으로 가능한가요?

**Comment by YangHeeBong** [comment]
네 답변 드리겠습니다.

1번 특정 지역만 보이게 하고 나머지 지역은 투명하게 만드는 방법이 있을까요?
 비슷한 기능은 있지만 현재 지형 영상 정보를 서버에서 따로 요청받아 브이월드 데이터를 검은색으로 표현하는 기능은 존재하면 그 외 기능은 존재하지 않습니다. 

2번 폴리곤 색상 설정 시 윗면과 아랫면만 다른 색상으로 가능한가요?
 어떤 조건에서 어떤 상황인지에 대한 정확한 설명이 필요합니다.
현재 폴리곤은 양면 랜더링 방식이 아닌 CCW 방식으로 은면처리가 들어가 있습니다. 그래서 평면, 형상일 경우 처리 방법이 달라지게됩니다.

먼저 평면 폴리곤 일 경우 윗면 폴리곤과 아래면 폴리곤을 입력좌표 반향을 반대로 생성하여 처리하면 윗아래 다른 색상 처리가 가능합니다.
현상 폴리곤일 경우 아래 그림과 같이 밑면을 볼 경우는 거희 없습니다.
![image](https://user-images.githubusercontent.com/82924515/182529724-858f955a-2da0-4303-b094-138e04de379a.png)
시야조건(1) : 내부 에서 밑면을 볼 수 없다
시야조건(2) : 외부 옆면과 윗면으로 기본적으로 밑면을 볼 수 없다

지금 주신 질문 정보로는 질문의 요지 판단이 불가합니다. 질문에 대한 상세 정보를 첨부해 주시면 상세한 답변을 드릴 수 있습니다.

**Comment by suhwna** [comment]
답변 감사합니다.

1번 
특정 지역만 잘라내서 가시화 하는 기능은 혹시 추후에 혹시 가능한가요 아니면 불가능한가요?

2번
죄송합니다 윗면 아랫면이 아니라 옆면입니다.
폴리곤 내부 안을 볼 수 있어야 합니다. 그래서 옆면만 반투명하게 하거나 가능하다면 선들도 안보이게 하고싶습니다.

![제목 없음](https://user-images.githubusercontent.com/91519109/182543647-13670b7b-10a7-4304-aa01-2bf9a5414bc5.png)

혹시 이 기능도 가능한가요 아니면 불가능한가요?

**Comment by YangHeeBong** [comment]
1번 특정 지역만 잘라내서 가시화 하는 기능은 혹시 추후에 혹시 가능한가요 아니면 불가능한가요?
 - 기능 개발은 가능하지만 개발 시간이 필요합니다. 급한 부분이라면 연구소로 문의 부탁드립니다.

2번 죄송합니다 윗면 아랫면이 아니라 옆면입니다.
 - 투명, 반투명 객체가 혼합된 부분에 대한 처리는 webGL에서 아래와 같은 현상을 유발합니다.
![image](https://user-images.githubusercontent.com/82924515/182548777-a14f3260-8b7f-48de-97c3-7b3c69ff6e03.png)
이를 해결하기 투명 객체 보다 3D 모델 객체를 먼저 출력해야 문제를 해결할 수 있지만 몇가지 오브젝트만 처리할 수 없는 문제점이 있습니다. 만약 위와 같은 문제를 해결하기 위해서 는 아래 그림처럼 처리 하시는 방법을 염두해 두시면 됩니다.
![image](https://user-images.githubusercontent.com/82924515/182549062-5dd97505-4da6-41be-b4ba-732ea59b480d.png)

**Comment by suhwna** [comment]
네 감사합니다.
