### ISSUE TITLE
레이어 or 오브젝트 우선순위 문의

### ISSUE THREAD

**Issue by YenaYena** [EgisCorp/XDWorld#194]
안녕하세요,

서울사무실 정예나 대리입니다.

아래의 그림처럼 3ds드론, 포인트 오브젝트와 레이어가 있는데 
포인트가 3ds드론을 가리지 않게 표출하려 합니다.

레이어와 오브젝트 생성은 포인트->드론 순서대로 생성하였고 높이는 동일합니다.

혹시 레이어나 오브젝트에 Z-index와 같이 우선순위를 줄수 있는 방법이 있는지 문의드립니다.

![image](https://user-images.githubusercontent.com/34873103/182735181-bb249add-d009-48a0-83fd-fc7b2f4d3b00.png)

**Comment by YunSumin** [comment]
안녕하세요,

드론 오브젝트가 포인트 클라우드 위에 항상 위치하도록 하기 위해서는
드론을 렌더링 할 시 z버퍼를 끄는 방식이 필요할 것 같습니다.

z 버퍼를 끄게 된다면 오브젝트는 거리감을 전혀 반영하지 않게 되고,
오직 렌더링하는 순서에 따라서 오브젝트가 겹쳐지게 됩니다.

(카메라와 가깝더라도 먼저 그려지는 경우 맨 뒤에,
카메라와 멀더라도 마지막에 그려지는 경우 맨 앞에 위치하도록 그려집니다.)

이미지 상의 드론은 고스트심볼을 활용하여 생성된 것 같습니다.
다만 현재는 고스트심볼의 z 버퍼를 끄는 API가 존재하지 않아 엔진 기능 업데이트가 필요할 것 같습니다.
API는 금주 중 업데이트 가능합니다.

z 버퍼 설정이 가능해지면 고스트심볼 오브젝트가 항상 위로 보이도록 표현하실 수 있습니다.
아래는 테스트 코드로 만든 z 버퍼 on/off 화면 이미지 입니다.

[z 버퍼 on]
![image](https://user-images.githubusercontent.com/82925313/182749845-703b66a8-7338-438c-bd0e-75b3290ff293.png)

[z 버퍼 off]
![image](https://user-images.githubusercontent.com/82925313/182749994-65cc3d21-b278-4d0d-b707-08b0e29b071c.png)

** z 버퍼를 끄게 된다면 거리감이 반영되지 않으므로
카메라를 이동시켰을 때 물체가 조금 이질적으로 느껴지실 수 있는 점 유의 부탁드립니다.

API가 업데이트 되는 대로 코멘트 드리겠습니다.

**Comment by YenaYena** [comment]
답변감사드립니다.
금주 중에 업데이트 해주시면 z-버퍼를 설정하여 활용하겠습니다.!

**Comment by YunSumin** [comment]
해당 프로퍼티(zBufferOff)를 추가하여 1.37.20 버전으로 엔진 릴리즈 하였습니다.
 ```javascript
var object = Module.createGhostSymbol("MY_OBJECT");
object.zBufferOff = true;
 ```
업데이트 및 적용 부탁드립니다.
