### ISSUE TITLE
카메라 자동 이동 일시정지 후 해당 위치에서 다시 이동 문의입니다.

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#195]
안녕하세요!

카메로 자동 이동 기능을 사용중에
일시정지 기능이 필요한데..

일시정지까지는 GLOBAL.Camera.pauseAutoMove(false); 함수를 사용해서 잘 작동 합니다.

그 후 다시 재개할때는 따로 이어서 시작하는 함수가 따로 없어서
처음부터 진행이 되고 있습니다.

멈췄던 위치에서 다시 실행되려면 어떻게 해야할까요??

**Comment by hjaejae** [comment]
안녕하세요~
문의하신 기능은
GLOBAL.Camera.pauseAutoMove(false); API에서
false와 true를 각각 넣어주시면 멈췄다가 다시 출발 합니다.

아래의 샌드박스를 참고 하시면 됩니다.
http://sandbox.dtwincloud.com/code/main.do?id=camera_move_path

**Comment by giyoon99** [comment]
감사합니다! 해결되었습니다~~~!
