### ISSUE TITLE
폴리곤 UV 텍스쳐 좌표 관련해서 문의드립니다

### ISSUE THREAD

**Issue by ren1302** [EgisCorp/XDWorld#196]
http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=object_polygon_rtt_image_changing 참조해서 
작업중에 궁금증이 생겨서 질문드립니다.

        // 폴리곤 좌표 지정
	var vertices = new Module.JSVec3Array();
	vertices.push(new Module.JSVector3D(129.1358795548428, 35.18151285035436, 0.0));
	vertices.push(new Module.JSVector3D(129.13910102131005, 35.18321779745, 0.0));
	vertices.push(new Module.JSVector3D(129.1412129025496, 35.18069414863917, 0.0));
	vertices.push(new Module.JSVector3D(129.13782351349964, 35.17887462859219, 0.0));
	
	// 폴리곤 UV 텍스쳐 좌표 설정
	var uv = new Module.JSVec2Array();
	uv.push(new Module.JSVector2D(0.0, 1.0));
	uv.push(new Module.JSVector2D(0.0, 0.0));
	uv.push(new Module.JSVector2D(1.0, 0.0));
	uv.push(new Module.JSVector2D(1.0, 1.0));

1. 위부분에서 push한 좌표수만큼 UV 텍스쳐도 push 해줘야되던데 안해주면 불러온 이미지가 뜨지가않아서 이유가 궁금합니다.
2. .JSVector2D(0.0, 1.0) 에서 안의 (x,y) 가 의미하는바가 궁금합니다.
3. new Module.JSVector2D(0.0, 1.0) 다음에 똑같이 new Module.JSVector2D(0.0, 1.0) 를 push 하면 이미지가 뜨지않던데 그 이유도 궁금합니다. 

항상 친절한 답변 감사합니다.

**Comment by hjaejae** [comment]
1. 답변
- 텍스쳐를 붙히기 위해서는 점과 UV좌표는 한쌍으로 이루어져야 합니다.

2. 답변
 -다수개의 점으로 이루어진 면에 이미지를 붙히기 위해서는 UV좌표계가 필요합니다.
UV좌표는 이미지 한 장을 0.0~1.0으로 정규화해서 입력합니다.
256X128의 크기를 가진 이미지라면
(0.5, 0.5)의좌표는 그 이미지의 128, 64좌표를 가지게 됩니다.

링크에 보시면 4각형 한장에 이미지 한장 전체를 붙히기 위해서
사각형의 좌상단, 좌하단, 우하단, 우상단의 좌표가 필요하므로
(0,1), (0,0), (1,0), (1,1) 이런씩의 좌표를 넣게 예제가 되어있습니다.

3. 답변
- 이미지가 뜨지 않는다기보단 같은 점으로 보간 하다보니 같은 색상이 입혀져있을것 같습니다.
- 주신 링크로 테스트를 해보셨다면 그 부분은 아마 투명처리가 되어있어서 보이지 않았을것 같습니다.
