### ISSUE TITLE
오브젝트 생성할 때 setDescription() 에러 발생 문제

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#197]
var poi = Module.createPoint("POI");
poi.setDescription("가나다");

위 처럼 오브젝트를 생성할 때
![image](https://user-images.githubusercontent.com/104063285/185008984-3dd42527-72ef-4a4a-aa8e-64042d7ff77f.png)
에러가 발생합니다.

1. 
알파벳이나 숫자를 처리할 때에는 나지않는데 한글을 넣으면 에러가 나는 것 같습니다.
혹시 setDescription에 한글을 넣는 방법이 있을까요?

2. 
아니면 setDescription 이 아니더라도
오브젝트 생성시 오브젝트에 data를 넣어두고 클릭할 때마다 그 data를 가지고 올 방법이 있을까요?
넣고 싶은 데이터는 문자열입니다.

3.
아, 혹시 setText를 넣었지만 생성된 poi 오브젝트 아래에 text가 표출이 안되도록 가리는 방법이 있나요?

**Comment by YangHeeBong** [comment]
네 안녕하세요 현재 이슈에 대해서 답변 드리겠습니다.

1. 알파벳 및 숫자는 정상적이지만 한글 에러 나는 이유?
   - setDescription 기능은 현재 utf-8만 가능하도록 되어 있어 한글 입력은 가능하지 않습니다. 이부분은 연구소에서 utf-16 또는 utf-32 지원 유무에 대해서 이야기 해보겠습니다.

2. data를 가져오는 방법
   - 엔진은 가시화 엔진으로 따로 데이터를 저장하지 않습니다. 
위 설명 방법을 처리하기 위해서는 오브젝트 클릭을 통해 반환받은 오브젝트 키값을 통해 배열 및 json 데이터를 참조 받는 방법이 일반적입니다.

3. setText 넣었지만 Text 표출이 안되는 방법?
   - poi에서 Text를 입력하고 출력 안하게 하는 하는 기능 보다 [샌드박스 샘플](http://sandbox.dtwincloud.com/code/main.do?id=object_point) 내용을 확인하시면 텍스트 없이 아이콘 출력 하는 방법에 대해서 설명되어 있습니다.

**Comment by Kor-eunae** [comment]
해결됐습니다~~ 답변 감사합니다!

**Comment by YangHeeBong** [comment]
엔진 1.37.21 버전 기준으로 uft16 지원 가능하도록 수정했습니다
