### ISSUE TITLE
HTML 컨트롤 적용 시 태그 생성되는 시점 문의드립니다.

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#198]
안녕하세요!

http://sandbox.dtwincloud.com/code/main.do?id=object_html_control

해당 기능을 사용 중인데, 좌표상 화면에 포함되지 않으면 html 내용들이 생성되지 않더라구요!

html 생성 후 다른 함수를 사용하여 내용을 수정하거나 반영해야 하는데

html 태그들 생성되는 시점이나 생성 후 콜백 함수가 있을까요??

**Comment by YangHeeBong** [comment]
안녕하세요 html 객체에 대해 설명드리겠습니다.

html 객체를 연동 후 생성 하는 과정은

let object = Module.createHTMLObject("div_object");
let complet = object.createbyJson(parameter);

createbyJson에서 메모리 상으로 html5 element를 생성하고 카메라 가시화 영역에 포함된 좌표에 해당되는 HTMLObject일 경우 html body에 등록, 비 가시화 상태일 때 html body에서 삭제하는 구조로 속도 향상을 목적으로 이러한 과정을 가지고 있습니다.

또한 html body에서 삭제 되더라도 실제 element 내용은 메모리상으로 가지고 있으므로 수정된 내용을 그대로 가지고 있습니다.

- 가시화 상태일 떄
![화면 가시화 영역](https://user-images.githubusercontent.com/82924515/185258801-9d835d8d-9ce5-467f-a110-9e7d0945c0a4.JPG)

- 비 가시화 상태일 떄
![화면 비 가시화 영역](https://user-images.githubusercontent.com/82924515/185258852-7f8ad16d-e706-4f03-b378-89cc758aaeb0.JPG)

위 이슈에 대해 궁금하신 내용으로 생성 후 다른 함수를 통해 내용을 수정하는 부분을 언급하셨는데 
질문내용중에 나오는 샌드박스 url을 보시면

```
	if (complet.result == 1) {
		layer.addObject(object, 0);
		// element 태그에 해당되는 HTML Element에 UI Element 추가
		createUI(element);		
	}
```
이 내용을 있고 createUI를 통해 스타일 및 내용을 수정하고 있습니다. 
createUI를 참조 하시면 될 것 같습니다.

또한 랜더링 시 콜백 이벤트를 사용하는 방법에 대해 설명 드리겠습니다. 
아래 소스에서 moveChange를 통해 콜백 기능 사용이 가능합니다.

콜백 기능 조건문
 - 가시화 상태일 때
 - 스크린 좌표 변경이 발생 했을 때

위 조건을 모두 만족했을 경우 동작하고 callback 매개 변수 구성은 아래와 같습니다.
- element : html element
- viewDistance : 카메라와의 거리
- x : 현재 출력되는 화면 좌표(X축)
- y : 현재 출력되는 화면 좌표(Y축)
```
	let parameter = {

		container: "divcontainer",	// div를 담을 Container 명칭 지정(명칭에 해당되는 div가 없다면 createHTMLObject 작업중 생성)
		canvas: Module.canvas,	// 화면 사이즈 설정을 위한 canvas 설정
		element: element,	// 엔진 오브젝트와 연동할 HTML Element
		position: new Module.JSVector3D(129.13782351349964, 35.17887462859219, 400.0),	// 위치 지점
		moveChange: callback,
		minAltitude: 1000,
		maxAltitude: 50000,
		verticalAlign: "middle",	// 수직 정렬 (top, middle, bottom, px 지원 )	|| 태그 미 설정 시 [Default top]
		horizontalAlign: "center",	// 수평 정렬 (left, center, right, px 지원 )	|| 태그 미 설정 시 [Default left]

	};

....

function callback(e) {
	let distance = e.viewDistance;
	distance *= 0.01;

	let size = Math.ceil(distance);
	if (size < 60) size = 60;
	else if (size > 300) size = 300;
	let px = size + "px";
	let box = e.element.getElementsByClassName("box");

	e.element.style.width = px;
	e.element.style.height = px;
	box[0].style.width = px;
	box[0].style.height = px;
}
```

**Comment by giyoon99** [comment]
해결되었습니다~~ 항상 감사드립니다!! :)
