### ISSUE TITLE
카메라 경로 이동 기능 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#199]
안녕하세요.

카메라 경로 이동 기능(http://sandbox.dtwincloud.com/code/main.do?id=camera_move_path) 사용 시 , 
가까이서/ 멀리서 보는 기능을 추가하고 싶은데 경로 이동 시 z값만 수정할 방법은 없을까요?

**Comment by YunSumin** [comment]
안녕하세요,

말씀하신 가까이/멀리 화면을 보는 기능은 화면의 시야각을 조정하는 것으로 적용 가능합니다.

경로 이동 시 좌표의 값을 수정하게 되면 시점의 위치가 바뀌므로
해당 경우는 좌표는 고정하되, 화면의 시야각을 조정하여
보이는 범위를 조정하는 방법이 적용되어야 할 것 같습니다. 

아래는 같은 위치에서 서로 다른 시야각을 적용한 화면입니다.

![image](https://user-images.githubusercontent.com/82925313/185840521-325d34a7-8ca4-488a-8808-79f8f4f13e89.png)
시야각 조정 API는 아래 문서 참조 부탁드립니다.
https://egiscorp.gitbook.io/xdworld-webgl-manual/camera/jscamera#setfov-fov

감사합니다.

**Comment by suhwna** [comment]
감사합니다~
