### ISSUE TITLE
활용 중 질의 사항은 이곳으로 업로드 부탁드립니다.

### ISSUE THREAD

**Issue by YunSumin** [EgisCorp/XDWorld#2]
이슈 란에 문의사항을 기술해주시면 기술하신 내용을 참고하여 상세히 답변드리겠습니다.
감사합니다.

**Comment by seepieex** [comment]
안녕하세요
XDSetMouseState(101) MML_FIGURE_RECT
XDSetMouseState(102) MML_FIGURE_ELLIPSE
XDSetMouseState(88)  MML_ANALYS_AREA_PLANE을 가시화 한 후
필요에 의해 객체를 선택 하여 지울 수 있는 방법은 없나요?
또 XDSetMouseState(88)을 한 후 만들어진 AREA가 지표면에 묻히는 결과가 나타나는데 높이 조절을 할 수 있는 방법이 있나요?

감사합니다^^
