### ISSUE TITLE
polygon RTT 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#20]
안녕하세요. 바이브컴퍼니입니다.

polygon RTT관련 문의입니다.

wms로 레이어 표시하고, 동일(비슷한) 위치에 polygon rtt 표시합니다.
근데, 이 polygon이 wms 레이어 뒤로 들어가는거 같습니다.

이것들 사이에 표시 순서가 있나요?
있다면.... 순서 조정을 어떻게 할 수 있나요?

(흰색 사각형이 polygon입니다)
![image](https://user-images.githubusercontent.com/38479834/120638161-c1cf3a00-c4aa-11eb-9c9b-6e602fc10752.png)

**Comment by avamk2** [comment]
안녕하세요 RTT 객체가 베이스 영상 항목 바로 위에 그려지기 때문에 WMS 및 하이브리드 레이어등의 이미지 오버레이에서 의심하신대로 기본영상 단계에서 그려지기 때문에 실질적으로 아래로 묻히는 현상이 있습니다.

이미지 오버레이를 개별로 올리는 부분에 3D 렌더링 구조에서 갯수의 제한이 있기 때문에 레이어별로 RTT 오버레이를 따로 둘수 없는 문제가 있습니다. ( #18 이슈와 동일한 문제) 때문에 개별적 위상을 조정하는 기능은 불가능합니다.

결과적으로 RTT에 대한 표출수준을 이미지 오버레이에서 ( 기본영상, WMS, 하이브리드 ) 가장 높은 수준으로 하여 표출수준을 변경할 예정입니다. 이는 UI 및 사용자 등록객체가 오버레이 아래 깔려서 보이지 않는 사항에 대해서도 필요한 부분이라고 판단합니다. 현재 작업공정에 들어 갔으며 해당기능은 시스템전반적으로 사용하는 3D 지형에 영향을 주며 성능적 영향에 중요한 영향을 주는 기능이라서 최장 2주내로 업데이트 할 예정입니다.

**Comment by HyunSeongKil** [comment]
네~
