### ISSUE TITLE
터치스크린에서 지도를 띄웠을 때 문의점

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#200]
터치가 가능한 기기에서 지도를 띄웠을 때

레이어의 오브젝트는 클릭이 가능하지만

두 손가락으로 화면을 확대, 축소, 회전하는 것을 막는 기능이 있을까요?

**Comment by YunSumin** [comment]
안녕하세요,

현재 터치 조작의 enable/disable 기능은 아직 API로 구현되지 않아 기능 추가가 필요한 상태입니다.
금주 중 설정할 수 있는 API를 추가하여 다시 코멘트 드리겠습니다.

**Comment by YunSumin** [comment]
금일 해당 기능이 업데이트 되었습니다. (버전 1.37.22)

Module.getControl() API를 통해 반환되는 JSControl의 프로퍼티 값을 설정하여
터치 동작 시 확대/축소 및 회전 기능을 설정하실 수 있습니다.

(*터치 이동 활성화 기능도 함께 추가가 되었습니다. 참고 부탁 드립니다.)

```javascript
// 터치 이동 활성화(true), 비활성화(false)
Module.getControl().touchPanEnable = true; 

// 터치 회전 활성화(true), 비활성화(false)
Module.getControl().touchRotateEnable = true; 

// 터치 줌 인&아웃 활성화(true), 비활성화(false)
Module.getControl().touchZoomEnable = true; 

```

감사합니다.

**Comment by Kor-eunae** [comment]
적용했더니 해결되었습니다!
답변 감사합니다!
