### ISSUE TITLE
WFS 텍스트 표출 시 한글 깨짐 현상

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#203]
![image](https://user-images.githubusercontent.com/88410545/186828671-fcf281b6-15db-450a-ae61-f1ac3fa2c96d.png)

안녕하세요!

WFS로 텍스트 표출 중에 일부 한글 텍스트가 인코딩이 깨지는 현상이 있어서 문의드립니다

**Comment by YangHeeBong** [comment]
네 안녕하세요 현재 이슈에 대해서 답변 드리겠습니다.

WFS에서 요청 받은 텍스트는 utf-8이며 가시화엔진 내부에서 utf-16으로 인코딩 변경 후 사용하여 처리 됩니다.
위 문제는 인코딩 변경에서 생긴 문제인 듯 합니다.
또한 모든 한글에 대한 부분이 아닌 일부 한글에서 발생하는 문제 같은데 혹시 위 텍스트에 한글 정보를 알려 주시면 기능 테스트 후 수정이나 원인에 대해서 알려드리겠습니다.

**Comment by YangHeeBong** [comment]
현재 이슈 #204 으로 인코딩 문제 확인 결과 크게 문제가 없음을 확인하였습니다.
혹시 문자 출력 문제가 발생하는 geoServer 정보를 회사 메일로 회신으로 보내 주실 수 있나요?

**Comment by YangHeeBong** [comment]
원인 분석 결과 utf8에서 utf16 변환 시 문자열 2자리 이하인 문자열에서 발생하는 걸 확인하여 이 부분을 수정하였습니다.
해결 릴리즈 엔진은 2022년 09월 02일 16시 전후로 업데이트 예정입니다.

엔진 정보( 엔진 로드 시 제공되는 로그 정보)
Released 2022-09-02
Version : 1.37.26


- 기존
![기존](https://user-images.githubusercontent.com/82924515/188064995-3c79b5b2-11ef-4552-ad9c-544653122d38.JPG)

- 수정

![한글수정 완료](https://user-images.githubusercontent.com/82924515/188065034-7644582d-725f-40d1-a57e-b7fdf817c948.JPG)
<한글 정상 출력>
![영어](https://user-images.githubusercontent.com/82924515/188065043-7cb610f1-1c05-4ccf-aaa8-1228d4fa3911.JPG)
<영어 정상 출력>
![숫자](https://user-images.githubusercontent.com/82924515/188065048-469a3b2a-05fd-4e72-bd56-4472c6498729.JPG)
<숫자 정상 출력>
