### ISSUE TITLE
WFS 텍스트 표출 시 개수 제한이 있나요??

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#204]
안녕하세요!
WFS 텍스트 표출 중 일부 데이터가 표출이 안되는 것 같아서 문의 드립니다.

![image](https://user-images.githubusercontent.com/88410545/187138246-147a7016-4813-4638-8287-bb201f82cba0.png)
[엔진 화면]

![image](https://user-images.githubusercontent.com/88410545/187138314-430d0cb2-bb9e-4c00-a0d7-5c3404e67439.png)
[pgadmin DB 데이터 조회 화면]

DB에서 조회한 데이터와 화면상에 표출된 데이터를 봤을 때 일부 표출이 덜 되고 있습니다.

혹시 개수가 제한되어 있을까요??

**Comment by YangHeeBong** [comment]
네 안녕하세요 현재 이슈에 대해서 답변 드리겠습니다.

가시화 엔진 자체에서 개수 제한은 없습니다.
요청 받은 GML(WFS 요청 데이터) 데이터를 구성하는 오브젝트 개수 만큼 wfs 오브젝트를 생성합니다.
위 처럼 일부 지역이 나타나지 않는 문제는 GML을 구성하는 라벨(텍스트) 정보가 없고 위치 좌표만 있을 경우 POI 데이터 안되는
것처럼 보이는 경우일 것 같습니다.

개발자 모드에서 네트워크 항목을 통해 해당 지역 GML 포맷을 확인 하신 후 라벨 유무 확인 부탁드립니다.

**Comment by giyoon99** [comment]
![image](https://user-images.githubusercontent.com/88410545/187359741-4d4fc3b6-145d-4434-b183-17b1c2e29ecb.png)
[지오서버 미리보기 화면]

![image](https://user-images.githubusercontent.com/88410545/187359782-3a089448-891c-4e43-ad9d-7580459db039.png)
[엔진 화면]


지오서버에서 확인 했을 때는 텍스트가 표출되고 있습니다 ㅜㅜ 


도움이 되실진 모르겠지만 URL도 같이 남깁니다!

http://211.178.39.228:8088/geoserver/kwaterleader/wms?service=WMS&version=1.1.0&request=GetMap&layers=kwaterleader%3Alsmd_adm_sect_ri_t&bbox=126.88282012939453%2C33.978641510009766%2C127.86637115478516%2C35.80588150024414&width=413&height=768&srs=EPSG%3A4326&styles=&format=application/openlayers#toggle

**Comment by YangHeeBong** [comment]
혹시 WMS가 아닌 WFS 요청 URL 이나 요청 URL로 받은 GML 데이터 부탁드립니다.
이미지 데이터로는 확인이 어려움이 있습니다. 
데이터는 개발자모드 -> 네트워크에서 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/82924515/187360484-ef12c506-4f9f-4c35-aa14-6588dab4c617.png)

**Comment by giyoon99** [comment]
http://211.178.39.228:8088/geoserver/kwaterleader/wfs?TYPENAME=kwaterleader:lsmd_adm_sect_ri_t&BBOX=126.000000,18.000000,144.000000,36.000000&MAXFEATURES=512&SERVICE=WFS&REQUEST=GetFeature&SRSNAME=EPSG:4326&OUTPUT=text/xml;subType=gml/3.1.1/profiles/gmlsf/1.0.0/0&VERSION=1.0.0&EXCEPTIONS=text/xml

WFS 요청 URL 입니다!

**Comment by YangHeeBong** [comment]
감사합니다
관련 내용 확인 후 2~4일 안으로 답변 드리겠습니다.

**Comment by YangHeeBong** [comment]
현재 테스트 결과 한 타일에 요청 개수가 있으면 이 부분을 1024로 수정 후 테스트 결과 아래와 같이 출력
하지만 요청 개수 증가로 파일 파싱 및 가시화에 영향을 줌으로 적절한 개수 설정이 필요합니다.

![image](https://user-images.githubusercontent.com/82924515/187861035-75eab890-c834-4dde-8c41-cc2bfa07a111.png)

설정 소스
```
	wfslayer.setConnectionWFS("URL문자열", 0, "파라미터 문자열");
	wfslayer.setLayersWFS("geoServer Layer 명칭");
	wfslayer.setCrsWMS("EPSG 코드", 8080);
	wfslayer.setWMSVersion("버전");
	wfslayer.setBBoxOrder(true);
	wfslayer.setLevelWMS("최소 가시화 레벨", "최대 가시화 레벨");
	wfslayer.setProxyRequest(false);

	wfslayer.setWFSPointName("POI 출력 태그 명칭");
	// 요청 갯수 설정  default 512 설정     
	wfslayer.setRequestFeatureCount(1024);
```

**Comment by giyoon99** [comment]
해결되었습니다 감사합니다!
