### ISSUE TITLE
고스트심볼 텍스처 일부분만 들어가는 현상

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#206]
```
onClickLibraryButton: function (_mlid) {
		// 선택한 건물을 고스트심볼 라이브러리로 지정
		 var category = $('#edit-building1 .select-btn').text();
		 
		 switch (category) {
		 	case "건물" : 
		 		category = "building";
		 		break;
		 	case "시설물" : 
		 		category = "facility";
		 		break;
		 	case "기타" : 
		 		category = "etc";
		 		break;
		 }
		
		if(_mlid == null){
			return false;
		}
		if(Module.getGhostSymbolMap().isExistID(_mlid)){
			M_EDITBUILDING.selectLibrary(_mlid);
		}else{
			Module.getGhostSymbolMap().insert({
				id : _mlid,
				url : "./3ds/" + category + "/" + _mlid + ".3ds",
				format : "3DS",
				callback : function(e) {
					// 텍스쳐 설정
						Module.getGhostSymbolMap().setModelTexture({
							id : e.id,
							face_index : 0,
							url : "./3ds/" + category + "/" + _mlid + ".jpg",
							callback : function(e) {
								M_EDITBUILDING.selectLibrary(_mlid);
							}
						});
				}
			});
		}
	}
```

![화면 캡처 2022-09-02 133357](https://user-images.githubusercontent.com/91519109/188059611-671e89f2-fa03-459a-8183-18e55938c5d8.png)

![화면 캡처 2022-09-02 133828](https://user-images.githubusercontent.com/91519109/188060093-e70d4d02-d875-4eaa-a4e9-c44fa6747f19.png)

위 사진처럼 고스트 심볼 생성 시, 텍스쳐 일부만 적용되는데 이유를 알수있을까요?

**Comment by YangHeeBong** [comment]
네 안녕하세요 현재 이슈에 대해서 답변 드리겠습니다.

혹시 나무 UV 좌표가 설정된 3ds 형상 정보 데이터 인가요? 3ds 뷰어를 통해 텍스쳐가 정상적으로 출력이 되는 모델인지 검증이 필요할 것 같습니다.

**Comment by suhwna** [comment]
3ds 파일 모두 UV 좌표는 모두 잘 잡혀있고 3ds 뷰어로 조회 시 정상적으로 출력이 됩니다.

나무는 faceCount가 2개여서 반복문으로 텍스쳐를 설정해주는 방식으로 해결했습니다.

풍력발전기는 faceCount가 하나고 UV 좌표도 정상인데 텍스처가 일부만 적용됩니다.

![화면 캡처 2022-09-05 111833](https://user-images.githubusercontent.com/91519109/188348273-486d223a-9640-45e8-a955-6336c052e5ce.png)

**Comment by YangHeeBong** [comment]
지금 올리신 풍력 발전기 이미지 2장으로 정상적으로 적용된 것처럼 보입니다. 이를 확인하기 위해서는 3DS 파일을 연구소 양희봉 차장 메일로 보내주시면 확인이 가능할 것 같습니다.

**Comment by YangHeeBong** [comment]
확인 결과 텍스쳐 가시화는 문제없는 걸 확인하였습니다. 
기존에 주신 텍스쳐가 흰색 계열이라 확인이 어려워 아래와 같이 색상 줄을 넣어 출력한 결과입니다.
위 문제는 충분히 데이터 검증이 미리 가능하기 때문에 좀 더 확인 작업을 부탁드립니다.

![6SU_18](https://user-images.githubusercontent.com/82924515/189008911-c63e1e58-cefd-4457-b9a8-80dd59e0d1ae.jpg)
![3dviewer 화면](https://user-images.githubusercontent.com/82924515/189008922-b437d404-dbe4-4e00-bbfa-28d116dfb9ae.JPG)
<Viewer 결과>
![engine화면](https://user-images.githubusercontent.com/82924515/189008939-b1ba8ce4-0aee-4001-be09-b2cd0f51f0c1.JPG)
<Engine 결과>

사용 소스
```
function load3DS(_url, _position) {

	// 폴리곤 레이어 생성
	var layerList = new Module.JSLayerList(true);
	var layer = layerList.createLayer("레이어명칭", Module.ELT_POLYHEDRON);
	var polygon = Module.createPolygon("POLYGON_3DS_LOAD");
	polygon.loadFile({
		position: _position,
		url: _url,
		align: "bottom"
	});
	layer.addObject(polygon, 0);
	return polygon;
}
```

**Comment by suhwna** [comment]
감사합니다.
