### ISSUE TITLE
네비게이션 기능도 있나요?

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#207]
안녕하세요^^

혹시 입력된 좌표 2개의 위치간의 최적 경로를 바로 알 수 있는 기능도 있을까요?

**Comment by YangHeeBong** [comment]
네 안녕하세요 현재 이슈에 대해서 답변 드리겠습니다.

엔진에서 도로와 길에 대한 형상데이터를 통한 최단거리 알고리즘은 지원하고 있지 않습니다.

**Comment by Kor-eunae** [comment]
아, 네 알겠습니다.
답변 감사합니다.
