### ISSUE TITLE
터치 스크린에서 줌, 회전 이벤트 문의

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#208]
터치 스크린에서 지도 엔진을 사용하고 있습니다.

터치로 줌 인, 줌 아웃할 때 현재 줌 레벨을 표시하고 싶습니다. 
지도 이동 이벤트처럼
1. 터치로 줌 인, 줌 아웃할 때 발생하는 이벤트가 있나요?

줌과 마찬가지로 회전할 때도 방향을 표시하고 싶은데
2. 터치로 회전을 할 때 발생하는 이벤트도 같이 문의하고 싶습니다.

혹시 이벤트가 없으면 기능을 추가해주실 수 있으신가요?ㅜㅜ

**Comment by hjaejae** [comment]
안녕하세요~
문의 주신 내용을 보았을 때 아래 2개의 이벤트를 사용하시면 어떨까 합니다.
우선 3차원에서는 줌 레벨이 Tilt 각도에 따라서 지형과 건물에 여러 레벨이 같이 있을 수 있습니다.
그래서 줌 레벨이라기 보다 아래 이벤트의 "경도, 위도, 높이"를 활용해서 표현 하시면 어떨까 생각합니다.

EX1) 경도, 위도, 높이 이벤트 (이동이 끝났을 때 이벤트 발생)
_canvas.addEventListener("Fire_EventCameraMoveEnd", function(e){
		console.log(e.latitude+", "+ e.longitude+", "+ e.altitude);
	});

그리고 회전했을때 현재 북쪽 기준으로 각도를 보여주는 이벤트가있어 이 이벤트를 활용하시면 방향을 표시 할 수 있을것 같습니다.

EX 2) 방향 (회전했을 때 이벤트 발생)
_canvas.addEventListener("Fire_EventRotateCompass", function(e){
			console.log("Angle : "+e.dCameraHeadAngle);
	});
각도(-180~180)는 북쪽 기준으로 오른쪽으로 회전하면 +, 왼쪽으로 회전하면 - 입니다.

**Comment by Kor-eunae** [comment]
아 감사합니다. 알려주신 방법으로 한번 시도를 해보고 안되면 또 다시 문의드리도록 하겠습니다.
