### ISSUE TITLE
setLimitAltitude() 문의

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#210]
현재 지도를 확대, 축소할 때.
특정 높이가 되면 더이상 확대, 축소가 되지 않도록 제어하고 싶습니다.

그래서 기존에 있는 아래 함수를 사용했는데
Module.getViewCamera().setLimitAltitude();
설정한 limitAltitude와 관계없이 계속 지도가 확대, 축소되고 멈추지 않습니다.

1. Module.getViewCamera().setLimitAltitude(); 기능 안됨
2. Module.getViewCamera().setLimitAltitude(); 이 최대 높이 설정인지 최소 높이 설정인지 알려주세요.
3. Module.getViewCamera().setLimitAltitude(); 가 최대 높이 설정이면 최소 높이 설정은 어떻게 하는지,
그 반대일 경우, 최대 높이 설정은 어떻게 하는지 알려주세요.

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 카메라 높이 제한 기능은 아래와 같이 구현하시면 됩니다.

```
let limit = {
	altitude: {
		enable: true,	// 높이 제안 사용 유무 true는 제한 사용 false는 기본 모드
		max: 5000,	// 최대 고도 제한
		min: 1000	// 최소 고도 제한
	},
};

Module.getViewCamera().limit = limit;
```

**Comment by Kor-eunae** [comment]
해결됐습니다! 감사합니다~
