### ISSUE TITLE
카메라 상/하 이동 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#211]
안녕하세요.

마우스 오른쪽 버튼 클릭한 상태로 위아래로 드래그 하는 것처럼 카메라가 바라보는 위치는 고정으로 카메라 기울기만 변경하는 기능은 없을까요?

```
/* 카메라 상하  */
function setRotate(type) {
	
	var screenX = parseInt(window.innerWidth * 0.5);
	var screenY = parseInt(window.innerHeight * 0.5);
        var tilt = GLOBAL.Camera.getTilt();
        var mapCenter = GLOBAL.Map.ScreenToMapPointEX(new Module.JSVector2D(screenX, screenY));
	var zoomValue = $(".zoom-bar").slider("value");
	
	switch(zoomValue){
		case 6 : alt = (mode ? 600 : 400); break;
		case 5 : alt = 1000; break;
		case 4 : alt = 3000; break;
		case 3 : alt = 10000; break;
		case 2 : alt = 15000; break;
		case 1 : alt = 20000; break;
		case 0 : alt = 35000; break;
	}
    
    if(type == true && tilt <= 90) {
    	GLOBAL.Camera.moveLookAt(mapCenter, tilt + 2, GLOBAL.Camera.getDirect(), alt);
    } else if(type == false && tilt >= 20) {
    	GLOBAL.Camera.moveLookAt(mapCenter, tilt - 2, GLOBAL.Camera.getDirect(), alt);
    }
	
}
```

현재는 이런식으로 사용하고 있는데 문제는 기울기가 너무 낮아지면 너무 먼 곳을 보고 있어서 전혀 다른 곳으로 이동하게되어 
사용할 수가 없습니다.

**Comment by YunSumin** [comment]
안녕하세요,

이전 이슈 #165 가 현재 구현 중이신 기능과 유사 부분이 많은 것 같아
해당 이슈의 답변이 구현에 도움이 될 것 같습니다.

또한 업로드 해 주신 setRotate 함수를 실행해 본 결과,
현재 ScreenToMapPointEX API는 피킹 지점이 없는 경우 카메라와 먼 값이 표출 되는 부분은
별도로 수정이 필요할 것 같습니다.

만약 API를 수정한다면 아래와 같이 업데이트가 가능합니다.

**[충돌 지점이 있을 때] 해당 지점의 맵 좌표 표출(기존 기능과 동일)**
**[충돌 지점이 없을 때] null 반환**

만약 ScreenToMapPointEX 실행 값이 null로 반환 되는 경우
화면 중앙점(=카메라가 바라보는 정 중앙점)이 허공 지점을 바라보는 것으로 간주하고
회전 기능을 실행하지 않도록 분기 처리가 가능합니다.

해당 업데이트는 내일 9/22 업로드 가능합니다.

검토해 보신 후 추가로 필요하신 사항이 있으시다면 말씀 부탁 드립니다.

**Comment by YunSumin** [comment]
[1.37.29 릴리즈](https://github.com/EgisCorp/XDWorld#2022%EB%85%84-9%EC%9B%94-23%EC%9D%BC-13729) 버전에서 ScreenToMapPointEX API 관련하여,
화면 피킹 점이 없는 경우 null 값이 반환 되도록 루틴이 추가되었습니다. 

![image](https://user-images.githubusercontent.com/82925313/192173192-11af6f65-aca0-4075-bf54-81534c342e30.png)

엔진 업데이트 및 관련 API 확인 부탁 드립니다.

**Comment by suhwna** [comment]
감사합니다.
