### ISSUE TITLE
타일맵 최대 레벨 이상 확대 시 사라지는 현상

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#212]
안녕하세요!

타일맵으로 레이어를 그려서 사용하던 중 지정한 레벨보다 더 지도를 확대하면

레이어가 사라져서 막을 방법이 있는지 문의드립니다!

![image](https://user-images.githubusercontent.com/88410545/192778475-2d2a9bf3-e7fa-4b0e-8f03-44ba9bca6f0f.png)
[타일맵 생성 소스]

여러가지 시도 중 지형과 항공사진을 주석 처리하니 사라지진 않더라구요...
![image](https://user-images.githubusercontent.com/88410545/192778559-cd5886e0-46fa-4ee4-b0a0-b9298fb3975b.png)
[지형, 항공사진 생성 소스]

부탁드리겠습니다!

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

원인은 기본 지형 영상 Level과 타일맵 영상 Level이 달라 생기는 문제입니다.

예를 들어 아래와 같은 조건일 경우

기본 지형 영상 Level : 15
타일맵 영상 Level : 12

기본 지형 영상 Level 13이 가시화 시 타일맵 영상에 대한 13레벨 영상을 요청하지만, 데이터가 없으므로 기본 지형 영상만 가시화됩니다.

이를 해결하기 위해서 타일맵 영상을 동일한 Level로 맞추거나 기본 지형 영상을 타일맵, 영상레벨로 고정하는 방법이 있습니다.

기본 지형 영상 레벨 제한 방법은 아래 API를 통해 가능합니다.

```
Module.getTerrain().SetMaxLevel(13);
```
