### ISSUE TITLE
레이어 중심 좌표를 조회하는 API 

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#213]
안녕하세요.

건물 등의 오브젝트로 이루어진 레이어의 위치를 알 수 있는 API가 있나요?

XDEMapCreateLayer를 통해 레이어를 생성하였고, 
현재는 급한대로 아래 소스와 같이 해당 레이어의 오브젝트들을 반복문으로 돌려
경위도 좌표의 평균값을 계산하여 사용중이었습니다.
그런데 이 방법은 visible을 false인 상태로 레이어를 생성할 경우,
layer.getObjectCount()가 계속 0인 상태로 유지되어 반복문을 돌지 않는 걸 확인했습니다.

레이어의 중심 좌표를 조회하는 API가 있을까요?

```
var layerList = new Module.JSLayerList(false);
var layer = layerList.nameAtLayer(레이어명);
var cnt = layer.getObjectCount();
var center = 0;
var center = 0;
		
for(var i = 0; i < cnt ; i++){
	var obj = layer.indexAtObject(i);
	var lon = obj.getPosition().Longitude;
	var lat = obj.getPosition().Latitude;
			
	centerLon += lon;
	centerLat += lat;
}

centerLon /= cnt ;
centerLat /= cnt ;

```

**Comment by YunSumin** [comment]
해당 부분은 연구 검토 중입니다.
추후 기능 업데이트 시 다시 코멘트 드리겠습니다.
