### ISSUE TITLE
그림자 생성 가능 시간대가 따로 있나요?

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#214]
안녕하세요.

https://user-images.githubusercontent.com/49426364/197318701-78b3dbac-3235-4b8c-9a2b-ca392150542f.mp4

시작 시간을 새벽 일찍, 종료 시간을 밤 늦게로 설정한 상태로 그림자 시뮬레이션을 돌리면
위 영상처럼 처음엔 그림자가 안 보이다가, 어느 순간 갑자기 나타났다가
종료 시간이 되기 전에 갑자기 그림자가 사라지는 증상이 나타납니다.

해가 떠 있는 시간에만 그림자 효과를 보여줘서 생기는 증상이라면,
혹시 해당 날짜에 그림자가 몇 시부터 몇 시까지 있는지 확인할 수 있는 방법이 있을까요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 

그림자 시뮬레이션 동작 방법에 대해 그림으로 설명드리겠습니다.

![그림1](https://user-images.githubusercontent.com/70614782/197457438-3493c5cc-fbee-4fc6-9e7f-46e585b49865.png)

위 이미지 처럼 태양벡터가 건물을 지나 지형과 만나는 지점을 찾아내 그림자를 생성하고 있습니다.

하지만 일출전에는 태양이 지형아래에 있기때문에 태양벡터가 지형과 만나는 지점이 생길수 없습니다.

![그림2](https://user-images.githubusercontent.com/70614782/197457441-34272540-662a-4621-8c4b-7b7f4a6bbca8.png)

그리고 해당 날짜의 일출일몰 시간을 알려주는 API는 현재 엔진에 없으며 일출일몰 OpenAPI를 사용하시는 것을 추천드립니다.

**Comment by KIMSEONOK** [comment]
넵 감사합니다~!

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 답변에 누락된 부분이 있어 추가 답변드립니다.

엔진에서 제공하는 일출, 일몰 API입니다.

일몰: Module.getAnalysis().GetSunset(2022, 10, 28);
반환값: 시간(double)

일출: Module.getAnalysis().GetSunrise(2022, 10, 28);
반환값: 시간(double)

감사합니다.
