### ISSUE TITLE
dem 관련 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#216]
안녕하세요.

혹시 dem도 레이어처럼 on/off가 가능한가요?

**Comment by YunSumin** [comment]
안녕하세요,

현재 엔진에서는 해당 기능이 구현되어 있지 않아 기능 추가가 필요합니다.
기능 추가 후 다시 코멘트 드리겠습니다.

**Comment by YunSumin** [comment]
안녕하세요,

DEM on/off 관련 샘플코드가 업데이트 되어 안내 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=terrain_slope_rate

좌측 상단의 바 조정 시 DEM 고도 비율을 조정하실 수 있습니다.
JSTerrain 클래스의 demRate 프로퍼티 입니다.
```javascript
Module.getTerrain().demRate = parseFloat(_value);
```

1.0으로 설정하실 경우 DEM의 원래 높이를 그대로 표현되고
0.5로 설정하실 경우 그 절반을,
0.0으로 설정하시는 경우 완전 평면으로 렌더링 됩니다.

값이 0.0인 경우 고도는 해발고도(0.0m)가 적용됩니다.

실 데이터의 가시화 부분만 변경하는 것이므로
분석용으로는 적합하지 않기 때문에 가시화 편의 기능으로 활용 부탁 드립니다.

감사합니다.

**Comment by suhwna** [comment]
감사합니다!
