### ISSUE TITLE
화면 분할 투명도 조절 기능 오류

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#217]
안녕하세요.

화면 분할 기능을 오래 전부터 사용중이었는데, 
어느 순간 엔진 업데이트 이후 투명도 기능이 적용되지 않는 것 같습니다.

아래는 동일한 소스에서 엔진만 교체해서 캡처한 사진입니다.
가지고 있는 엔진 버전들로 테스트해보니 1.37.9와 1.37.15 사이에 바뀐 것 같습니다.

![image](https://user-images.githubusercontent.com/49426364/198072693-6192d00e-f49b-409f-a9a9-1b30aa201222.png)
![image](https://user-images.githubusercontent.com/49426364/198074013-e4bff45b-0714-44d0-831a-c4108094c00b.png)

http://sandbox.dtwincloud.com/code/main.do?id=effect_screen_split
위 샌드박스 예제에서도 테스트해보았는데, 적용이 되지않는 것 같아 확인 부탁드리겠습니다!

```
/* 화면 분할 설정 */
function setSplitScreen(_screenCount) {

	if (GLOBAL.option == null) {
		return;
	}
	
	// 분할 화면 수 설정
	GLOBAL.option.setSlideScreenCount(_screenCount);
	
	// 각 화면마다 표출할 레이어 설정
	if (_screenCount > 1) {
		
		var serverLayerList = new Module.JSLayerList(false);
		var memoryLayerList = new Module.JSLayerList(true);
		
		GLOBAL.option.setTwoSlideScreenDivideRate(
			parseFloat(document.getElementById("splitRange").value)
		);
		GLOBAL.option.setTwoSlideScreenLayerList(
			"facility_build",
			""
		);
		
		document.getElementById("splitMapScreen").style.display = "block";
		
	} else {
		document.getElementById("splitMapScreen").style.display = "none";
	}
    
    /////////////////// 추가한 부분 ///////////////////
    var layerList = new Module.JSLayerList(false);
    var layer = layerList.nameAtLayer("facility_build");
    
    if(layer != null){
        layer.setAlpha(100);
    }   
    /////////////////////////////////////////////////////////	

	// 화면 갱신
	Module.XDRenderData();
}

```

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

투명도 편집 관련하여 랜더링 옵션 기능이 내부적으로 변경되었습니다.

최신 엔진 1.37.39 버전을 업데이트 후 테스트 확인 부탁드리겠습니다.

감사합니다.

**Comment by KIMSEONOK** [comment]
최신 버전으로 업데이트 후 정상적으로 잘 작동하는 것을 확인하였습니다.
감사합니다!
