### ISSUE TITLE
키보드를 이용한 지도화면 조작 문의

### ISSUE THREAD

**Issue by melacola** [EgisCorp/XDWorld#218]
키보드로 화면을 확대/축소/이동 하고자 합니다.

동시에 여러키를 눌러서 컨트롤 하고 싶은데 지원 가능할까요?

EX_1) 확대하면서 경사를 조정
EX_2) 지도를 회전하면서 확대

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

말씀하신 기능은 웹에서 키 이벤트로도 구현이 가능합니다.

엔진 내부적으로는 중복키에 대한 예외처리가 되어있지 않아 현재 구현이 필요한 상태입니다.

다음 엔진 버전에서 기능이 업데이트 될 예정이며, 기능 추가 후 다시 코멘트 드리겠습니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

중복키 이벤트 처리 기능이 업데이트 되었습니다.

엔진버전 : 1.38.0 을 다운로드 후 테스트 부탁드립니다.

감사합니다.

**Comment by melacola** [comment]
p{margin-top:0;margin-bottom:0}
    


    응. 성룡씨 고마워.
즐거운 하루 보냉.

--------- 원본 메일 ---------

    
        보낸사람: SeongRyong-Choi ***@***.***>
        받는사람: EgisCorp/XDWorld ***@***.***>
        
            참조: melacola ***@***.***>, Author ***@***.***>
        
        날짜: 22.12.07 16:32 GMT +0900
        제목: Re: [EgisCorp/XDWorld] 키보드를 이용한 지도화면 조작 문의 (Issue #218)
        
        
    
    
        

안녕하세요.

중복키 이벤트 처리 기능이 업데이트 되었습니다.

엔진버전 : 1.38.0 을 다운로드 후 테스트 부탁드립니다.

감사합니다.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
�
