### ISSUE TITLE
gwc 캐시 제공

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#22]
안녕하세요!
vector, rest geoserver wms 캐시는 구축해두었고 client단에서 캐시만 받아오면 될 꺼 같은데 ㅎㅎ... 
geoserver 캐쉬 받아서 wms 서비스 하고싶은데  적용이 가능할까요?

**Comment by loeaf** [comment]
스펙관련해서는 WMTS 내용을 참고해주시면 될꺼 같습니다
https://docs.geoserver.org/stable/en/user/community/wmts-multidimensional/index.html

**Comment by loeaf** [comment]
![image](https://user-images.githubusercontent.com/3315478/121159782-73dd7c00-c886-11eb-9446-46e43f6d9213.png)

http://192.168.0.1:8080/geoserver/gwc/service/wmts?layer=vaiv:korea_lots2&style=&tilematrixset=EPSG:4326&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/png&TileMatrix=EPSG:4326:7&TileCol=219&TileRow=36

**Comment by loeaf** [comment]
![image](https://user-images.githubusercontent.com/3315478/121160229-dc2c5d80-c886-11eb-83ed-d38e84031759.png)
http://OOO.OOO.OOO.OOO:OOOO/geoserver/gwc/service/wmts?layer=vaiv:korea_lots2&style=&tilematrixset=EPSG:4326&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/png&TileMatrix=EPSG:4326:7&TileCol=219&TileRow=36

보안 정책으로 인하여 외부로 열려고하면 번거로워서 쉽지 않을꺼 같습니다 ㅠㅠ... 요게 최선 원격으로는 최선일꺼 같내요! 수고 많으십니다! 감사합니다

**Comment by loeaf** [comment]
서버 외부로 확인할 수 있게 열어드리는것은 회사 보안으로 인하여 쉽지 않을꺼 같습니다... 복잡해서..
![image](https://user-images.githubusercontent.com/3315478/121160585-2e6d7e80-c887-11eb-97b5-b97f980de351.png)

http://OOO.OOO.OOO.OOO:OOOO/geoserver/gwc/service/wmts?layer=vaiv:korea_lots2&style=&tilematrixset=EPSG:4326&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/png&TileMatrix=EPSG:4326:7&TileCol=219&TileRow=36
고생많으십니다! 감사합니다

**Comment by YangHeeBong** [comment]
참고 자료로 충분합니다.  
감사합니다

**Comment by YangHeeBong** [comment]
현재 내용을 검토하여 두 가지 논의 사항이 있습니다.

1. 생성 시 TileCol,TileRow 구성 방식
2. 생성 시 TileCol,TileRow 구성 변경 가능
입니다.

![image](https://user-images.githubusercontent.com/82924515/123891863-81bd8300-d994-11eb-9771-e5b47df6236a.png)
위 방식처럼 Tile을 정해진 조건으로 구성하여 하위로 내려가는 Tile 방식으로 많이 사용하는데 어떤 구성인지 확인이 필요하고

저희와 다른 구성 방식이라면 wmts 구성 시 저희 타일 방식으로 재 생성이 필요해 보입니다.
저희는 5*10으로 나사의 월드 윈드 방식과 동일한 방법으로 구성되어 타일 레벨별 아래 데이터로 구성됩니다.

0 level : 5*10
1 level : 10*20
.
.
15 level : 163840*327680

![image](https://user-images.githubusercontent.com/82924515/123892032-c5b08800-d994-11eb-8da0-373638533d09.png)
wmts 방식으로 작성 시 5*10형태로 이미지를 작성 하시면 기술적으로 무리 없이 진행이 가능합니다.
하지만 다른 방식으로 구성 시 타일 TileCol, TileRow 가 달라 다른 이미지가 출력 되거나 잘못된 요청 처리가 됩니다.

**Comment by loeaf** [comment]
기존 wms레이어를 처리할때 256x256 입력에 대해서 처리를 하고 계시는대 wmts도 256x256 기반으로 처리가 불가능할까요?

**Comment by EgisCorp** [comment]
저희 엔진에서 하이브리드라는 기능이 있습니다.
기존 wms와 차이는 미리 만들어진 이미지 파일을 서버에 요청 후 이미지를 가시화 하는 방법으로
wmts 방식과 유사 합니다. 
하지만 윗 답글 내용처럼 이미지를 타일 방식으로 생성 하지 않는다면 정상적인 위치에 이미지가 생성 되지 않습니다.

**Comment by loeaf** [comment]
WMS와 WMTS의 차이는 dynamic과 캐쉬라는 것에 동의합니다
하지만 타일을 만들 때의 타일에 대한 스펙은 WMS나 WMTS 동일한 게 맞지 않는지요?
혹시 샘플로 만들어둔 타일 데이터를 보내드리려고 하는데 해당 부분에 대해서 검토해서 API를 만들어 주실 수 있으신가요?

**Comment by YangHeeBong** [comment]
이 내용은 다음 주 회의 시 내용 정리가 필요하다고 판단되었습니다. 
관련 내용은 회의에서 정리 하도록 하겠습니다.
