### ISSUE TITLE
막대 그래프 관련 문의

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#220]
안녕하세요.

샌드박스를 참고하여 2D 및 3D 막대 그래프 구현하던 중 몇 가지 질문 사항이 있어 문의드립니다!

1. 숫자 소수점 자릿수 설정(2D, 3D)
 수치값, y축 값 등 숫자를 소수점 표시 없이 1의 단위로 표현하고 싶은데, 소수점 자릿수를 설정할 수 있는 API가 있나요?

2. 값이 0인 데이터는 수치 안보이는 현상(2D)
값이 0인 데이터는 수치도 표시되지 않는데, 막대는 표시가 안되더라도 수치는 표시되게 가능할까요?
![image](https://user-images.githubusercontent.com/49426364/201510870-47f2704d-2190-42af-88e6-82271f2cdc59.png)

**Comment by YunSumin** [comment]
안녕하세요,
기능 수정 후 메일을 통해 개별 전달 드렸으나, 다른 참조하시는 분들을 위해 안내 드립니다.
해당 이슈 건은 1.37.40 전에 업데이트 되었으므로 참고 부탁 드립니다.

감사합니다.
