### ISSUE TITLE
moveLookAt 기능 문의 

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#223]
안녕하세요.

현재 폴리곤 중심 좌표로 카메라를 이동하기 위해 moveLookAt  기능을 사용하여 카메라 이동 시, 지도가 깨져서 보입니다.

처음 moveLookAt 을 사용하여 이동 시에만 지도가 깨지고 여러번 사용할 때는 문제가 없습니다.

그런데 지도가 깨진 후  마우스 휠로 조작하면 다시 지도가 정상으로 돌아옵니다. 해결 방법이 있을까요?

https://user-images.githubusercontent.com/91519109/203451914-e6200869-130a-4ef4-9955-8581c19efbc7.mp4

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

moveLookAt 사용 시 입력 인자가 어떻게 되는지 확인이 필요할 것 같습니다. 

현재 화면이 깨진다고 하는 현상은 지형과 지형을 연결하는 커튼 폴리곤이 존재하면 이 폴리곤이 가시화 되어 있는걸 봐서는
지금 look 위치가 땅 밑으로 설정된 것 같습니다.

**Comment by suhwna** [comment]
moveLookAt 사용 시 입력 인자입니다.

GLOBAL.Camera.moveLookAt(new Module.JSVector3D(127.10295918439704, 37.513892220438564, 7.27586614806205), 45, 0, 100);

**Comment by YangHeeBong** [comment]
관련 내용은 엔진 1.37.42 버전으로 업데이트 하시면 해결됩니다.

**Comment by suhwna** [comment]
감사합니다.
