### ISSUE TITLE
오브젝트 선택 좌표 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#224]
안녕하세요

지하에 있는 오브젝트 선택 시, 오브젝트 표면의 좌표 값을 구하고 싶습니다. 현재는 ScreenToMapPointEX를 사용하여 화면 -> 지도 좌표로 변환하여 사용하고 있는데 오브젝트가 지하에 있어서 오브젝트가 아닌 투명하게 만든 지도 위치의 좌표가 반환됩니다. 
오브젝트를 클릭한 위치의 자표를 구할 방법이 있을까요?

![화면 캡처 2022-11-23 213350](https://user-images.githubusercontent.com/91519109/203548104-9f3a3114-1bae-4d85-808f-79fc2ae1932a.png)

![화면 캡처 2022-11-23 213402](https://user-images.githubusercontent.com/91519109/203548107-18df880a-1ecb-4552-ba2b-1ed1773c1796.png)

**Comment by YunSumin** [comment]
안녕하세요,

해당 기능과 관련된 API가 없어 현재 구현이 필요한 상태입니다.
다음 엔진 버전에서 기능이 업데이트 될 예정이며, 기능 추가 후 다시 코멘트 드리겠습니다.

**Comment by YunSumin** [comment]
안녕하세요, 문의 주신 기능이 1.38.0 버전에서 업데이트 되어 안내 드립니다.

 ScreenToMapPointEX API 경우 지형, 레이어 등을 고려하여 최종 맵 좌표 위치를 반환하지만,
아래 API는 레이어 별로 화면 피킹 결과를 반환하는 API 이므로
단일 레이어를 대상으로 활용하실 수 있습니다.

**object pick(unsinged int screenX, unsigned int screenY)**
* class : JSLayer
* parameter
    * screenX : 화면 x 좌표
    * screenY : 화면 y 좌표
* return : 피킹 지점이 없는 경우 null 반환, 피킹 지점이 있는 경우 충돌한 오브젝트 키와 위치 좌표 반환함
```
var result = layer.pick(e.x, e.y);
console.log(result.objectKey);
console.log(result.position.Longitude);
console.log(result.position.Latitude);
console.log(result.position.Altitude);
```

리턴 값으로 피킹 충돌이 일어난 오브젝트의 키, 충돌 지점을 반환합니다.

감사합니다.

**Comment by suhwna** [comment]
감사합니다.
