### ISSUE TITLE
1.37.42 버전 오류

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#225]
안녕하세요.

이슈 #223 와 동일한 문제로 엔진을 업데이트했는데,
Module.Start 실행 시 아래 캡처와 같은 오류가 발생합니다.

![image](https://user-images.githubusercontent.com/49426364/204415271-f22d45d2-bc4b-4652-80e4-6dac4f70a718.png)
![image](https://user-images.githubusercontent.com/49426364/204415303-0211d096-bd53-4c9b-8ef6-2c8e204d5088.png)

Module.Start 이전에는 DEM과 DDS를 선언하는 두 명령어 밖에 실행되지 않습니다.
확인 한 번만 부탁드리겠습니다!

**Comment by YangHeeBong** [comment]
![image](https://user-images.githubusercontent.com/82924515/204416255-33bcc95c-4b48-4903-bf4b-d999595b5f50.png)

지금 로그 내용 확인 결과 캔버스 생성 후 Module.Start가 되어야 하는데 캔버스 생성 유무를 확인해 주시기 바랍니다.

**Comment by YangHeeBong** [comment]
![image](https://user-images.githubusercontent.com/82924515/204416770-a535d030-b0ee-4f02-9219-4a4be56d3ada.png)
지금 릴리즈 버젼을 바로 동작 시킨결과 위와 같은 결과가 나오고 있습니다.

**Comment by KIMSEONOK** [comment]
화면 캡처 기능 때문에 canvas를 만들 때 버퍼 설정을 해주는 부분이 있었는데,
이 부분을 빼고 하니 정상적으로 실행되는걸 확인했습니다!

![image](https://user-images.githubusercontent.com/49426364/204417292-8c424d0b-ed97-4af9-a12c-7e1f82db0960.png)
