### ISSUE TITLE
라인 생성하기(튜토리얼)

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#227]
안녕하세요, "라인 생성하기" 튜토리얼에서 요청할 사항이 있어 문의 올립니다.

1. union과 depth 등의 속성을 설명하는 예시 이미지를 보면, 실제 산과 건물을 활용한 모습을 볼 수 있습니다. 테스트를 위해, 샌드박스의 기본 좌표값을 변경하거나 해당 위치의 좌표을 알려주시면 좋을 것 같습니다.
2. 예시 이미지의 오른쪽 위를 보면 나침반을 비롯한 인터페이스가 있는데, 해당 기능은 샌드박스의 어느 항목에서 볼 수 있는지 궁금합니다.
![image](https://user-images.githubusercontent.com/119284901/204438443-7b1fcc8d-b24e-475b-b30d-75c89fa7cd60.png)

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

1. 튜토리얼은 간략한 사용 방법에 대한 내용을 공지하고 라인에 대한 상세 사용 방법은 샌드박스 [라인](http://sandbox.dtwincloud.com/code/main.do?id=object_line_Json)에서 확인이 가능합니다 좌표에 대한 정보를 반환 받고 싶다면 샌드박스 [화면>지도좌표변환](http://sandbox.dtwincloud.com/code/main.do?id=coordinate_screen_to_map)로 원하는 좌표를 추출 가능합니다.
2. 기본적으로 나침판은 엔진 내부에서 고정적으로 사용하는 부분으로 수정 및 변경은 불가합니다. 혹시 필요하시다면 div를 이용하여 이벤트 등록하는 방법을 추천해 드립니다.

**Comment by HeoTaeYang** [comment]
`Module.XDEMapCreateLayer("facility_build", "https://xdworld.vworld.kr", 0, true, true, false, 9, 0, 15);` 코드를 초기화 함수에 추가해서, 건물에도 테스트해보고 있습니다.
답변 고맙습니다.
