### ISSUE TITLE
shp파일을 xdworld 맵에 적용시킬 방법이 있을까요?

### ISSUE THREAD

**Issue by mykim1024** [EgisCorp/XDWorld#228]
shp파일을 xdworld를 통해 3d로 표출하고싶습니다. 우선 geoserver에 shp파일을 올려 나오는 wms을 적용시켰더니 에러가 납니다. 혹시 다른 방법이 있을까요? 
![image](https://user-images.githubusercontent.com/109206050/204479708-9da2948b-8ae8-4bd6-b69e-7df7cad9f4f1.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

현재 shp파일을 geoserver에 올려서 wms로 서비스가 가능합니다.

사용하신 소스를 첨부해 주시면 정확한 오류처리가 가능할것 같습니다.

**Comment by mykim1024** [comment]
인코딩 문제는 해결됐습니다. 아래 사진처럼 요청했는데 실제 파라미터값이 다르게 넘어가는 경우는 무슨 문제일까요? 또한 wfs 요청을 했더니 에러가 발생합니다 혹시 요청 소스에 문제가 있을까요?
(wms)
![image](https://user-images.githubusercontent.com/109206050/205835148-ac106596-b7be-4df9-b54b-7e3c4f33826d.png)
![image](https://user-images.githubusercontent.com/109206050/205835158-73b12702-87bf-4273-b689-51b895179276.png)
(wfs)
![image](https://user-images.githubusercontent.com/109206050/205835305-4306681e-d1bd-4928-bd51-48df99a49c2a.png)

**Comment by YangHeeBong** [comment]
#### crs 5186 설정 시
![image](https://user-images.githubusercontent.com/82924515/205835983-91a35d20-e0e5-45ff-863c-644ccc1745e6.png)
#### crs 4326 설정 시
![image](https://user-images.githubusercontent.com/82924515/205836552-561b9b06-a03d-469d-9a85-2fd6e634df95.png)

현재 엔진결과 정상적으로 입력된 값이 적용된 부분을 확인할 수 있습니다.

엔진 버전 : Version : 1.37.42

**Comment by mykim1024** [comment]
감사합니다 해결됐습니다. 궁금사항이 두가지 있는데
1. wms를 3d로 띄울 방법이 있을까요?
2. wfs 호출 시 이러한 에러가 납니다 혹시 어떤부분이 문제 인지 알 수 있을까요?
![image](https://user-images.githubusercontent.com/109206050/205843603-f2e0d1cb-165d-4cb6-ab98-399b8d0bd916.png)
![image](https://user-images.githubusercontent.com/109206050/205843884-5832c850-eff6-49be-8f68-356c9975c159.png)

**Comment by YangHeeBong** [comment]
wms는 geo server에서 이미지로 반환됩니다. 
geo server에서 반환되는 이미지 데이터로 엔진 내부에서 3D로 만들수 없고 형상정보는 wfs로 만들어야 할것 같습니다.
wms와 wfs에 대한 구분이 필요한 부분입니다.

또한 wfs에러 메시지는 메시지에 명시된 요청 거부로 인한 메시지로
엔진 내부에서 가시화된 영역을 geo server에 feature를 요청하는데 해당 영역에 feature가 없는 경우 반환되는 메시지 입니다.

**Comment by YangHeeBong** [comment]
web workers or 데이터 경량화 or 영역별 데이터 재분배 등 다양한 방법이 존재할 것 같습니다.

**Comment by mykim1024** [comment]
감사합니다
