### ISSUE TITLE
건물 오브젝트 출력 함수 사용 방법

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#229]
안녕하세요.
현재 XDEMapCreateLayer() 함수를 활용하여, 주변 구조물과 함께 시각화 테스트를 하고 있습니다.
XDEMapCreateLayer()의 매개변수 옵션을 알 수 있을까요?

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

XDEMapCreateLayer()의 기본 사용방법은 아래와 같습니다.
```Javascript
Module.XDEMapCreateLayer("facility_build", "server.url", 0, true, true, false, 9, 0, 15);
```

#### @param (utf-8 String)"facility_build" : 레이어 이름 (XDServer 에서 서비스 되는 레이어 이름을 적용합니다)
#### @param (utf-8 String)"server.url" : 서비스 URL
#### @param (Number)"0" : URL 사용 port 번호(현재 미사용)
#### @param (Boolean)"ture" : 레이어 오브젝트 선택 가능 여부
#### @param (Boolean)"ture" : 레이어 가시화 여부
#### @param (Boolean)"false" : XDServer로 서비스 되는 경우 false, 그렇지 않을 경우 true로 설정
#### @param (Number)"9" : 레이어 타입
#### @param (Number)"0" : 레이어 최소 가시화 레벨
#### @param (Number)"15" : 레이어 최대 가시화 레벨

**Comment by OceanShape** [comment]
가시화 레벨에서 최소/최대 용어가 쓰이는 이유를 잘 모르겠습니다.
가시화 레벨과 가시 거리는 같은 의미인가요?

**Comment by HeoTaeYang** [comment]
레이어 최소/최대 가시화 레벨의 의미를 잘 모르겠습니다.
"레이어 설정" 튜토리얼을 살펴보면,
최소/최대를 사용하는 부분은 <2-2. 가시 거리 설정>이고,
레벨 용어를 사용하는 부분은 <2-4. 레이어에 객체 추가>였습니다.
```javascript
var object = 객체 생성;
userlayer.addObject(object, 0);	// (객체, 삽입할 레벨)
```
특정 레이어에서 레벨을 나누는 기준은 무엇인가요?
가시화 레벨과 가시 거리는 같은 의미인가요?

**Comment by YunSumin** [comment]
안녕하세요.

addObject 의 두번째 파라미터 0은 현재 사용하지 않는 값 입니다.

코드의 직관성을 위해 삭제되어야 마땅하나,
현재 사용되고 있는 곳이 많아 즉각 수정이 불가능한 점 양해 부탁 드립니다.

**1. 특정 레이어에서 레벨을 나누는 기준은 무엇인가요?**

>  레이어의 데이터는 공간을 정의하는 트리 형식으로 구성되어 있고  **레벨은 공간 트리의 깊이**를 의미합니다.
>
>  현재 XDWorld의 레이어 타입은 크게 두 가지가 있습니다.
>
> - 사용자 레이어 (사용자가 필요에 의해 생성하는 옥트리 타입 레이어)
> - 타일 레이어 (=XDServer에서 서비스 되는 타일 형식 레이어)
> 
> 트리의 깊이를 레벨 값으로 정의하는 것은 두 타입 모두 동일하나, 트리의 형식이 다르기에 각각 나누어 설명 드립니다.
>  
> * 사용자 레이어
>![image](https://user-images.githubusercontent.com/82925313/204986847-0d283939-19c2-49bb-ac99-98507c8a18e9.png)
>
>    * 오브젝트를 추가하면서 공간 구조를 생성하는 형식입니다.
>    * 각 트리의 노드는 부모 노드를 기준으로 8분할 되어 공간을 구성합니다.
>    * 사용자 레이어의 레벨을 나누는 기준은 분할 된 공간 트리의 깊이를 의미합니다.
>    * Root의 경우 0레벨이며, 하위 단으로 내려갈 수록 1레벨씩 레벨 값이 증가합니다. 
>    * 서버 기반으로 데이터를 서비스하기 때문에 오브젝트의 삭제, 이동 등 수정이 어렵습니다.
>    * 세계 단위로 규격화 되어있어 타일 범위가 고정되어 있고 주로 큰 용량의 객체를 서비스하는 곳에 사용됩니다.
>
>  * 타일 레이어  
>![image](https://user-images.githubusercontent.com/82925313/204987094-55722216-264c-427e-a9da-89ed6a0a51fc.png)
>
>     * 세계 공간을 50개의 0레벨 타일로 사전 분할 후 세계 공간 내 오브젝트를 추가하는 형식입니다.
>     * 50개의 0레벨 타일들은은 4분할되어 좀더 세부적인 하위 타일을 구성합니다
>     * 하위 단으로 내려갈 수록 1레벨씩 레벨 값이 증가합니다.
>     * 오브젝트가 메모리 상에 존재하기 때문에 자유롭게 생성하고 지울 수 있습니다.
>     * 타일 범위가 오브젝트 위치와 크기에 따라 결정됩니다.

**2. 가시화 레벨과 가시 거리는 같은 의미인가요?**
> 서로 다른 의미를 가집니다.
> * 가시화 레벨
>   * XDEMapCreateLayer 의 마지막 두 파라미터로 명시한 레벨은 서버로부터 요청하는 레벨의 범위를 나타냅니다.
>   * 주로 타일 레이어에서 사용되는 개념입니다.
>   * 0에서 16레벨까지 존재하는 타일 데이터가 있다고 할 때, 0과 15 값으로 파라미터를 설정하는 경우 16레벨은 서비스 되지 않습니다.
> * 가시화 거리
>   * 튜토리얼에서 설명하는 레이어는 사용자 레이어에 대한 설명입니다.
>   * 범위가 고정된 타일을 사용하지 않기 때문에 오브젝트 간 거리를 기준으로 가시화 범위를 지정합니다.

**Comment by HeoTaeYang** [comment]
설명 고맙습니다.
