### ISSUE TITLE
선그리기 - 지글거리는 현상, 표시/미표시되는 현상 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#23]
안녕하세요. 바이브컴퍼니입니다.

첨부된 동영상 확인해 주세요.

선그리기를 한 영상인데... 
확대/축소에 따라 선이 지글거리는 현상(?)과 표시/미표시되는 현상의 이유를 알고 싶습니다.
alt값이나 zoom level과 관련이 있을까요?

https://user-images.githubusercontent.com/38479834/120975371-1e34a100-c7ac-11eb-9057-d428029875cd.mp4

아래 이미지는 선그리기에 사용된 코드입니다.

![image](https://user-images.githubusercontent.com/38479834/120975356-18d75680-c7ac-11eb-85c5-5751e712e9cb.png)

**Comment by avamk2** [comment]
안녕하세요. 

SKY_LINE 형태의 라인으로 생성해서 사용하시는 경우에는 3D 라인의 높이값이 지혀에 영향을 받게됩니다.

3D 지도인 경우에는 LoD (Level of Detail) 이라는 중심부는 정밀도가  높은 데이터를 주변에는 점점 정밀도가 낮아지는 방식으로 자원을 관리합니다. 때문에 지도를 축소하면 정밀도가 떨어지는 지형의 DEM 형상을 갖게되며 확대하면 점점 자세한 DEM 형상을 현재보시는 지도 중심부로부터 갱신됩니다. 

위 현상은 이과정에서 높이값이 지면에 밀착되어 있거나 지면 아래로 심어진 경우에 라인이 지면 아래로 깔려서 보이지 않게 됩니다.

이를 방지하기 위해서는 

`
let pMap = Module.getMap();
let tMargin = 1.5;  // 지형에서부터 띄우는 마진
let vertex = Module.JSVec3Array();
vertex.push(new Module.JSVector3D(127.2781, 36.4701, pMap.getLonLatHeight( 127.2781, 36.4701) + tMargin));	// 현재 지형높이에 마진으로 살짝 띄움
vertex.push(new Module.JSVector3D(127.29, 36.49, pMap.getLonLatHeight( 127.2781, 36.4701) + tMargin));
`

위와 같은 방식으로 3D 지형의 높이를 산출하고 이에 대한 높이여유값 [ LOD 적용으로 높이의 편차가 약간씩 생기기 때문 ]을 주고 반영하시면 지형아래로 깔리는걸 방지하실수 있습니다.

**Comment by HyunSeongKil** [comment]
답변 고맙습니다.

줌 레벨에 따라 선의 일부가 보이고 안보이고 하는 현상은 LoD 때문이라는 말씀이신거죠?

**Comment by avamk2** [comment]
네 그렇습니다. 
지형이 정밀도가 갱신되면서 위 사항은 점점 지형높이가 LoD 변화로 차츰 위로 올라가면서 라인이 묻히는 문제로 보입니다.

**Comment by HyunSeongKil** [comment]
네~~

**Comment by YunSumin** [comment]
금일 오후 미팅 후 라인 설정 옵션 관련하여 추가 답변 드립니다.

현재 엔진에서는 라인 그리는 옵션을 RTT로 그리는 방식과 일반 라인 방식으로 제공하고 있고,
일반 라인 그리는 방식은 다시 지형 결합 방식과 지형 미결합 방식으로 제공됩니다.

열거하면
1. RTT로 그리기
2. 일반 라인
   1) 지형 결합 라인
   2) 지형 미결합 라인

참조 가능하신 샘플 URL은 다음과 같습니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_line_Json

금일 회의에서 보여주신 이미지는 RTT로 그려진 이미지이기 때문에,
지형 이미지 해상도에 따라 라인 선명도가 달라질 것으로 생각됩니다.

가장 선명하게 출력 되는 방안으로는
일반 라인이면서, 고도 값을 가진 좌표로 만든 지형 미결합 라인이
지형 묻힘 현상 없이 선명히 표현될 것이라고 생각되나,
RTT로 표현이 필요하신 경우 지형 LOD Ratio를 조정해보시는 방안도 사용하실 수 있을 것 같습니다.

Module.getMap().setTerrLODRatio(설정값);

설정값은 float 타입이며, 디폴트 값은 4.0 입니다.
티폴트 이상의 값을 입력하시면 더 먼 거리에서 높은 레벨이 지형을 불러오기 때문에 픽셀의 디테일이 더 커집니다.

다만 먼 거리에서 높은 레벨 지형을 불러오는 경우 DEM 버텍스 수가 배가 된 상태에서 렌더링이 되기 때문에
렌더링 프레임이 낮아질 수 있는 점 참조 부탁드립니다.
