### ISSUE TITLE
건물에 사용하는 Layer Type

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#231]
안녕하세요.

지난 번 [이슈 문의](https://github.com/EgisCorp/XDWorld/issues/229)를 통해,
XDEMapCreateLayer()에서 건물 오브젝트를 출력하기 위해 사용하는 레이어의 타입은 9번 다용도 타입임을 알게 되었습니다.

또한, 튜토리얼의 Layer Type List를 살펴보면, 3차원 심볼과 유령 심볼 타입도 존재함을 알 수 있었습니다.

건물 오브젝트를 출력할 때 3차원 심볼과 유령 심볼 대신, 다용도 타입을 사용하는  이유가 궁금합니다.

**Comment by YunSumin** [comment]
안녕하세요,

우선 튜토리얼에 해당 값에 대한 안내가 잘못 기재되어 사과 말씀 드립니다.
현재 1.37.42 버전 기준 9번 레이어 타입은 Real3D 건물 레이어 타입으로, 다용도 레이어 타입은 8번을 사용하고 있습니다.
향후 개발 방향에 따라 레이어 타입 값이 달라질 수 있음을 안내 드립니다.

감사합니다.

**Comment by HeoTaeYang** [comment]
감사합니다.
