### ISSUE TITLE
폴리곤 높이 설정 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#232]
안녕하세요.

현재 폴리곤 생성 시, 폴리곤 오브젝트 자체에 높이 값을 설정합니다. 
혹시 폴리곤의 vertex마다 각각의 높이 값을 부여하는 게 가능한가요?

**Comment by avamk2** [comment]
안녕하세요

폴리곤 생성에서 각 vertex마다 별도의 높이값을 적용하였다면 객체 생성후 JSPolygon::setUnionMode(bool)를 false 입력하시면 지형결합되지 않은 3차원 폴리곤 형상으로 나오게됩니다. 

다만 3차원 폴리곤은 형상에 따른 폐합 여부를 따지게 됩니다. 그래서 임의로 정의한 모든 점에 대해서 처리되는 것은 아니며 특정 축으로 삼각분할 조검이 맞아야만 가능합니다.

폴리곤 삼각분할 자료 : https://en.wikipedia.org/wiki/Polygon_triangulation

![image](https://user-images.githubusercontent.com/82994540/205583164-6411bd67-0e86-4d2e-9647-ebc8a717b9f9.png)

입력에 따라서 위와 같은 기하모델까지는 가능합니다.

더 궁금한 사항이 있으면 댓글 남겨주시기 바랍니다.

**Comment by suhwna** [comment]
polygon.setHeights()로 해결하였습니다. 

감사합니다.
