### ISSUE TITLE
위치 좌표를 이용한 면적 구하기가 가능할까요?

### ISSUE THREAD

**Issue by EGIS-KimGyeongSik** [EgisCorp/XDWorld#233]
안녕하세요.

현재 위치 좌표만을 가지고 면적을 구하는 것이 필요한데 엔진에서 구현이 가능할까요?
샌드박스에서는 마우스 클릭된 이벤트 처리를 이용해서 면적을 구하는 것만 있어서 확인이 힘들어서요.
아래와 같이 좌표들만 있을 경우 면적 구하는게 가능한지 궁금합니다. 구현이 꼭 필요한 부분이라 문의드립니다.
이미지 좌표는 5174 입니다. 엔진 15번 좌표계입니다.

![image](https://user-images.githubusercontent.com/119863057/205639118-8f9e2042-8c18-4eae-8d0e-15ba3411caa7.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

해당 기능은 외부에서도 계산 공식을 활용하여 할 수 있기때문에 따로 API가 없습니다.

EPSG:5174 의 경우 1 meter 단위이므로 좌표 그대로 면적 계산 공식을 이용하여 구현할 수 있습니다.

감사합니다.
