### ISSUE TITLE
카메라 Tilt 속성에 낮은 값 적용시 고도가 고정되는 이유

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#234]
안녕하세요.
카메라를 활용하여 테스트 코드를 작성하던 중, 궁금한 게 생겨 질문 올립니다.

현재 `moveLonLatAlt()`와 `setTilt()`, `setDirect()`를 활용하여 카메라 방향을 설정하고 있습니다.
그런데 `setTilt()`에서 설정한 `tilt`의 값이 낮을수록, 위아래로 시점을 회전해도 고도가 잘 바뀌지 않는다는 것을 알게 되었습니다(굉장히 크게 움직였을 때에만 바꿀 수 있었습니다). 이렇게 동작하는 이유가 궁금합니다.

https://user-images.githubusercontent.com/119284901/206064139-7110fc3c-3fe5-439f-a30d-9524906a01f9.mp4

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

엔진 내부적으로 Tilt 값을 제한하고 있으면 제한 이유는 조작 문제로 볼 수 있습니다. Tilt 제한이 없을 경우 제자리 360로 회전되거나 오일러 각도에 의한 문제 발생 가능성도 있습니다.

JSCamera.setLimitTilt를 통해 지정된 각도를 해제 가능하지만 최소 7도를 유지 합니다.

**Comment by HeoTaeYang** [comment]
답변 고맙습니다.
