### ISSUE TITLE
브이월드 하이브리드 지도 적용 시 문제

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#235]
브이월드 맵 적용시 문제가 생겨 문의드립니다.

브이월드의 다른 맵을 적용할 때는 이런 문제가 안생기는데 하이브리드 지도를 적용하니까
지도가 이렇게 표출이 됩니다.

혹시 하이브리드 지도 적용시에는 다른 방법으로 적용을 해야하나요?

문제 화면은 아래 이미지입니다.

![image](https://user-images.githubusercontent.com/104063285/206340142-a8fa0765-d084-46a7-9ed0-b03e2da5229c.png)

**Comment by YunSumin** [comment]
안녕하세요,

첨부하신 이미지 상으로는 지형이 투명하게 처리되어 대기 아래 부분이 노출되는 현상으로 보입니다.

다만 하이브리드 이미지의 경우 지형 영상 이미지 위에 얹어 렌더링 되기 때문에
하이브리드 이미지가 투명하다고 해서 배경 이미지까지 투명해지지 않습니다.

혹시 WMTS를 통해 지도 배경 이미지를 교체하신 상태이신가요?

해결을 위해
- WMTS를 통해 배경 이미지가 교체 되었는지 여부
- 요청하시는 이미지의 배경이 투명 처리되었는지 여부

에 대하여 추가 확인이 필요하므로 해당 부분 확인 후 말씀 부탁 드립니다.
