### ISSUE TITLE
Trace target y축 방향으로 이동시키기

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#236]
안녕하세요.

Trace target으로 지정한 모델이 위/아래 방향(y축)까지 움직이도록 조작하고 싶습니다.
y축 방향도 조작하는 move()함수가 있을까요?

**Comment by YunSumin** [comment]
안녕하세요,

현재 Trace target의 수직 이동 기능은 없는 관계로
다음 주 정기 업데이트에 반영 후 다시 코멘트 드리겠습니다.

**Comment by YunSumin** [comment]
1.39.0 엔진이 릴리즈 되어 안내 드립니다.

https://github.com/EgisCorp/XDWorld#1390-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8-2022%EB%85%84-12%EC%9B%94-14%EC%9D%BC

Trage target 이동을 위한
* void moveTarget(object options)

API가 새로 추가되었습니다.

기존 API는 지면과 수평한 평면 공간 이동만 가능했으나,
새로 추가 된 moveTarget API의 up 속성을 활용하시면 지면 수직 이동이 가능합니다.

엔진 업데이트 부탁 드립니다.

감사합니다.

**Comment by HeoTaeYang** [comment]
확인했습니다. 기능 추가 감사합니다.
