### ISSUE TITLE
마우스 이격 오류

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#237]
안녕하세요

1.38.0 버전으로 엔진을 교체하였는데 마우스 이격이 발생하여 문의드립니다.

https://user-images.githubusercontent.com/91519109/206377515-766a85f0-f4d8-4f4d-bb85-1508c2e77e21.mp4

**Comment by YunSumin** [comment]
안녕하세요,

만약 Module.Start API 실행 후 canvas에 별도로 left, top 마진을 주신 상태라면
canvas 속성 변경 후 applyCanvasPosition API 호출 부탁 드립니다.

```javascript
Module.applyCanvasPosition();
```

위 API는 지도 canvas의 left와 top의 css 속성을 엔진에 반영하는 API 입니다.

감사합니다.

**Comment by suhwna** [comment]
감사합니다 해결했습니다.
