### ISSUE TITLE
마우스 이격 오류

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#238]
안녕하세요.

버전 1.38.0 으로 엔진 업데이트 후 마우스 이격 오류가 있어서 #237 을 참고하여 
Module.applyCanvasPosition();를 실행했는데도 마우스 이격이 계속해서 발생하여 문의드립니다!

https://user-images.githubusercontent.com/49426364/206710552-4aa3dd3c-0dd1-49ef-b05d-2a21a37832e8.mp4

#237 의 답변에서 이 API가 left, top 값을 계산한다고 설명해주셨는데,
아마 현재 엔진에서는 부모 요소를 기준으로 값이 계산되어서 그런 것으로 예상됩니다.
아래 캡처는 Document를 기준으로 계산하는 offset()과 부모 요소를 기준으로 하는 position()으로
top, left 값을 콘솔로 출력한 결과와 상단 및 하단 영역의 크기를 캡처한 이미지입니다.
(주황색은 화면 전체 영역이고, canvas의 위치는 fixed로 고정시켜 놓은게 아닌 하단 영역의 전체영역으로 생성하도록 한 상태입니다.)

해당 API에서 left, top 계산 시 Document를 기준으로 계산하는 방법을 사용할 수 있도록 업데이트 가능할까요?

![image](https://user-images.githubusercontent.com/49426364/206715999-0ca9c5de-45fe-4399-98ed-ca8fc2bd7c88.png)

![image](https://user-images.githubusercontent.com/49426364/206717804-edd116c3-4331-4f0d-8ce0-ba7678c9a598.png)

**Comment by YangHeeBong** [comment]
이 문제는 추후 canvas를 포함한 container에 Event target을 주고 container 내부에 입력 이벤트를 캡쳐링 할 예정입니다.

**Comment by YangHeeBong** [comment]
2023년 1월 11일 엔진 업데이트를 통해 마우스 포인트 이격과 이벤트 캡쳐링, 버블링 해결하였습니다.

[README.md 1.43.0 업데이트(2023년 1월 11일) 참조](https://github.com/EgisCorp/XDWorld)

외부에서 캔버스 설정하는 방법에서 div에 해당되는 Container를 생성 후 Module.initialize 내부에서 캔버스를 설정합니다.
