### ISSUE TITLE
지도 분할 및 싱크 기능

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#239]
안녕하세요.

![image](https://user-images.githubusercontent.com/49426364/207028663-598d2fbf-93e5-43c0-9dd3-c05084b29a34.png)

위 캡처처럼 지도를 2개의 화면으로 분할하여 각각의 화면에 표출할 레이어를 설정하여 가시화하는 기능을 구현하려고 합니다.
마우스 및 키보드로 지도 컨트롤 시 두 화면의 위치, 방향, 각도 모두 싱크를 맞춰야 하는데,
엔진 자체에 이와 관련된 기능이 있는 지 문의드립니다!
기능이 없다면, iframe으로 지도를 하나 더 호출하는 방식을 썼을 때
두 지도(Module) 간에 충돌이 나지 않도록 컨트롤이 가능한가요?

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 화면 분할 기능은 포함되어 있지 않습니다.

2개 이상의 화면을 구성하기 위해서는 iframe으로 구성하시고 싱크에 대한부분은 HTML에서 제공하는 버블링과 캡쳐링을 참조하시면 해결 가능할 것 같습니다.

**Comment by KIMSEONOK** [comment]
넵 감사합니다!
