### ISSUE TITLE
createWMSLayerSet 관련 오류 메시지 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#24]
Version 1.3.15.7.2 (2021-06-07)

안녕하세요. 바이브컴퍼니입니다.

프로그램 실행했는데 아래와 같은 오류가 발생합니다.
이미지의 상단은 관련 소스, 하단은 오류 메시지입니다.

업무 로직이 조금 수정되긴 했지만, 이런 오류가 발생할 정도는 아닌거 같아 이곳에 글을 올립니다.
확인 부탁 드립니다.

![image](https://user-images.githubusercontent.com/38479834/121111351-a87f1280-c849-11eb-9455-81484a5d6c5e.png)

[내용추가]
최신 버전에서 createWMSLayerSet 이 사라졌습니다???

![image](https://user-images.githubusercontent.com/38479834/121112728-c51c4a00-c84b-11eb-885b-67851ad0e392.png)

**Comment by YangHeeBong** [comment]
네 현재 변경 되었습니다. 

http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=layer_wms
이곳에서 참조 하시면 될 것 같습니다.

추후 변경된 부분에 대해서 공지부분에 첨부 하겠습니다.
