### ISSUE TITLE
지도 캡쳐 기능 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#240]
안녕하세요

현재 1.38버전 엔진 사용중인데 캡쳐 기능 사용 시, 정상적으로 캡쳐가 되지 않아 문의드립니다.

샌드박스에서도 검은 화면으로 캡쳐가됩니다.

**Comment by YunSumin** [comment]
안녕하세요
문의 주신 내용을 확인하여 샌드박스의 샘플코드를 수정하였습니다.

#### 변경 전
```javascript
var context = canvas.getContext("experimental-webgl", {
    preserveDrawingBuffer: true
});
```

#### 변경 후
```javascript
var context = canvas.getContext("webgl2", {
    preserveDrawingBuffer: true
});
```

컨텍스트 설정을 "experimental-webgl" 에서 "webgl2"로 변경 부탁 드립니다.

감사합니다.
