### ISSUE TITLE
화면 분할 기능 적용 가능 레이어 타입

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#241]
안녕하세요.

http://sandbox.dtwincloud.com/code/main.do?id=effect_screen_split

위 샌드박스 예제에 있는 화면 분할 기능을 사용중입니다.
건물 형태의 레이어는 분할 기능이 잘 먹히는데,
WMS이나 하이브리드 영상은 기능 효과가 적용되지 않는 것을 확인하였습니다.

바닥에 붙은 레이어도 분할 기능이 적용될 수 있도록 가능한지 문의드립니다!

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

샌드박스에서 WMS 레이어를 생성하여 화면 분할 기능을 테스트했습니다.

사진과 같이 WMS 레이어와 건물 레이어가 화면 분할되는것을 확인할 수 있습니다.

![20221219_093626](https://user-images.githubusercontent.com/70614782/208328067-5bfb2221-218c-429c-840d-9ab43112d553.png)

혹시 사용하신 API와 엔진 버전을 알려주시면 원인 파악이 수월할것 같습니다.

감사합니다.

**Comment by KIMSEONOK** [comment]
1.39.0 버전을 사용하였고,  WMS 호출 함수는 아래와 같습니다.

![image](https://user-images.githubusercontent.com/49426364/208364909-817949e8-11c6-4865-94a0-17ec40a4f510.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

혹시 화면 분활 옵션에 생성한 wms 레이어를 추가하셨나요?

[샌드박스 예시]
GLOBAL.option.setTwoSlideScreenLayerList(
	"facility_build",
	"wmslayer"
);

**Comment by KIMSEONOK** [comment]
실수로 "A, B" 이런 식으로  두 레이어명 사이에 띄어쓰기를 넣어서 실패했던 것 같습니다!
잘 되는 거 확인했습니다 ㅎㅎ 감사합니다!
