### ISSUE TITLE
객체 선택 이벤트 MML_SELECT_POINT 이외의 선택 모드 활용법

### ISSUE THREAD

**Issue by seepieex** [EgisCorp/XDWorld#243]
안녕하세요
예제 사이트를 보면 
Module.XDSetMouseState(Module.MML_SELECT_POINT)와 Module.canvas.addEventListener("Fire_EventSelectedObject", function(e)를 
사용하여 건물 레이어에서 건물 object의 속성을 알아내고 있습니다.

MML_SELECT_CIRCLE등을 사용하여 반경 선택을 한 후에 반경 안에 있는 건물 object들을 선택할 수 있는 방법이 있나요?

감사합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

해당 기능과 관련된 API가 없어 현재 구현이 필요한 상태입니다.

다음 엔진 버전에서 기능이 업데이트 될 예정이며, 기능 추가 후 다시 코멘트 드리겠습니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요. 

이번 엔진 정기 업데이트로 Module.MML_SELECT_CIRCLE 반경 선택 기능이 추가되었습니다.

감사합니다.
