### ISSUE TITLE
getFov() 반환값의 자료형

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#244]
안녕하세요. 
API 문서에 따르면, getFov()의 반환값의 타입은 JSVector2D 입니다.
하지만 typeof를 통해 확인해보면, fov 값으로 추측되는 단일 number 데이터 한 개가 출력되었습니다.
문서에 나온 대로 x와 y를 반환받고자 한다면, 어떤 API를 사용하여야 하나요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

문의주신 getFov API는 JSCamera, JSViewFrustum 클래스 에서 사용하고 있습니다.

JSCamera 클래스의 getFov() 는 number 타입으로 반환되며
JSViewFrustum 클래스의 getFov()는 JSVector2D 타입으로 반환됩니다.

[JSViewFrustum](https://egiscorp.gitbook.io/xdworld-webgl-manual/object/jsviewfrustum)

number 타입으로 반환이 되었다면 JSCamera 클래스 API를 사용하신것으로 추측됩니다.

감사합니다.

**Comment by HeoTaeYang** [comment]
답변 고맙습니다.
