### ISSUE TITLE
풍력 2D WebGL 버퍼 오버플로우 

### ISSUE THREAD

**Issue by DAVE2404** [EgisCorp/XDWorld#245]
안녕하세요. 
(주) 포도 안중원입니다.
보내주신 바람길 데이터를 올렸을때, 풍력 2D에서만 
![image](https://user-images.githubusercontent.com/52440145/208597136-e3bf6463-c829-4609-bd87-7660af6094b0.png)
이러한 오류가 발생하고 있습니다.

전에 보내주신 마린시티쪽 바람길 파일로 테스트 하였을때는 잘 나왔는데, 너무 넓은 영역을 표출하려고 해서 나타나는 문제인가요?

**Comment by avamk2** [comment]
안녕하세요 답변이 늦어서 죄송합니다.

2D 출력 범주가 한계가 있습니다. 그리드 데이터의 해상도가 한계가 있으며 위 사항은 데이터 수용범주가 넘어간 사항으로 확인됩니다. 해당 기능에 대해서 여러가지 검토를 진행하고 있습니다. 현재는 분석파일을 엔진에서 다운로드 및 파싱과 Rasterizing까지 내부에서 진행 하는 것을 대신해서 Web코드에서 분석 결과를 image 클래스로 Rasterizing을 한 후에 이미지를 바로 교체 하는 방식으로 해상도와 용량적 한계를 해소하고자 합니다. 분석 서버부터 렌더링하는 엔진까지 범주가 넓어서 시간이 필요하지만 업데이트 되면 공지 하도록 하겠습니다.
