### ISSUE TITLE
POI 가시거리 설정

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#247]
안녕하세요.
카메라 위치를 조작하면서, POI를 둘러보는 기능을 만들고 있습니다.
그런데, 일정 거리보다 멀어지거나 가까워지면 POI가 보이지 않는 경우가 있었습니다.
POI와의 거리에 관계없이 항상 POI를 보이게 하는 함수가 있을까요?

**Comment by YunSumin** [comment]
안녕하세요.

POI가 소속 된 레이어가 오브젝트 레이어인 경우
JSLayer의 setMinDistance, setMaxDistance API로 오브젝트의 가시거리 설정이 가능합니다.
setMinDistance 값을 0.0 으로 두시고 setMaxDistance 값을 충분히 큰 값으로 설정하시면 됩니다.

다만 안내 드린 기능을 확인 하는 중에
1.40.0 버전에서 값이 정상적으로 적용되지 않는 오류가 발견되었습니다.
현재 해당 오류가 수정되었으며, 다음 주 1.41.0 버전 업데이트에 반영될 예정입니다.

1.41.0 버전 업데이트 후 코멘트 드리겠습니다.

**Comment by HeoTaeYang** [comment]
답변 고맙습니다.

**Comment by YunSumin** [comment]
해당 기능이 수정 된 엔진 1.41.0 버전이 릴리즈 되어 안내 드립니다.
(https://github.com/EgisCorp/XDWorld/blob/main/README.md#1410-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8-2022%EB%85%84-12%EC%9B%94-28%EC%9D%BC)
 오브젝트 레이어의 setMinDistance, setMaxDistance 값이 설정되지 않는 오류를 수정하였습니다.
엔진 최신화 부탁드립니다.

감사합니다.
