### ISSUE TITLE
미니맵에 사용할 캔버스에 화면 그리기

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#248]
엔진 버전
: v_1.41.0

문의 내용
: 안녕하세요.
미니맵 구현을 위해, 별도의 캔버스를 작성하고 있습니다.

Module에서는 사전에 등록한 canvas 객체와 XDEMapCreateLayer() 함수를 통해 맵 화면을 그리는 것으로 알고 있습니다.
직접 만든 canvas에 별도의 맵을 하나 더 만들려면, 어떤 함수를 사용해야 하나요?

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

canvas는 엔진에서 자체적으로 생성한 html element가 아닌 html에서 자체적으로 제공하는 element로 별도의 맵을 더 만들고 싶다면 html에 새로운 canvas를 document에 등록하셔야 합니다.

등록 후 html canvas에서 제공하는 그리기 기능을 이용하시면 됩니다.
