### ISSUE TITLE
엔진 문의사항

### ISSUE THREAD

**Issue by tstshan** [EgisCorp/XDWorld#249]
엔진 버전
:

문의 내용
: 안녕하세요 한택수 입니다.
몇가지 엔진 관련 문의사항을 보내오니 목록확인하셔서 답변 부탁드릴게요.

1. 3D맵에서 축척을 조회할 수 있는 기능 존재 유무, 존재하지 않는다면 대신할 수 있는 기능의 존재 유무
2. 네비게이션 및 나침반 기능의 스타일 변경 가능 여부
3. 지도 렌더링 속도를 개선할 수 있는 방법 존재 유무
4. 측정 동작에 사용되는 이벤트(callBackCompletePoint) 이외에 JSOption등을 통해 정의된 다른 callback함수 존재 유무
ex) 마우스 모드 MML_SELECT_POLY(폴리곤 선택)에서 폴리곤을 그린 후에 정의된 callback 함수 들이 있는지
5. 마우스 모드에 있는 이벤트 method들의 소스 코드를 볼 수 있는지
ex) Module.XDSetMouseState(Module.MML_SELECT_CIRCLE) / Module.XDSetMouseState(Module.MML_FIGURE_RECT)
등의 마우스 모드 등이 어떤 클래스와 이벤트를 사용하는지 궁금합니다. 가능하면 소스 코드도 보고 싶습니다.
6. MML_SELECT_POINT에는 Fire_EventSelectedObject 이벤트가 적용 되지만 다른 SELECT 모드에는 적용이 안 되는 걸로 파악이 됩니다. 
MML_SELECT_CIRCLE 등에도 Fire_EventSelectedObject와 유사한 이벤트가 있는지 없다면 반경이나 폴리곤 선택을 이용하여 건물 오브젝트들을 한꺼번에 어떤 식으로 선택할 수 있는지 궁금합니다.
7. 배경지도의 해상도가 변경 되는 카메라의 고도 및 시야각의 기준 수치가 있는지, 기준 수치가 있다면 기준 수치 설정 가능 여부 
8. 건물 레이어의 object가 3D로 보이는 카메라의 고도 및 시야각의 기준 수치가 있는지, 기준 수치가 있다면 기준 수치 설정 가능 여부
9. 거리 측정 기능 Module.MML_ANALYS_DISTANCE 옵션에서 마우스를 클릭을 여러번 하면서 거리를 측정했을 때,
Uncaught abort(112). Build with -s ASSERTIONS=1 for more info.와 같은 에러가 발생하며 모듈이 멈추는 현상이 발생합니다
문제 해결 방안이 있는지 궁금합니다.
10. 맵에서 geoserver에 존재하는 레이어를 WFS로 호출하는 예제 존재 유무
2. XDWorld API를 통해 WFS(레이어)를 호출 하는 방법이 궁금합니다.

**Comment by avamk2** [comment]
안녕하세요 문의사항에 대해서 번호별 댓글로 답변드리겠습니다.

### Q 3D맵에서 축척을 조회할 수 있는 기능 존재 유무, 존재하지 않는다면 대신할 수 있는 기능의 존재 유무

해당질문 사항에 대해서는 과거동일한 질문에 대한 답변으로 링크로 대체됩니다.

https://github.com/EgisCorp/XDWorld/issues/67

**Comment by avamk2** [comment]
### 네비게이션 및 나침반 기능의 스타일 변경 가능 여부

엔진에 내장된 네비게이션 컨트롤 및 나침반 UI는 내부코드와 결합되어서 이미지와 기능이 일체형이라 커스트마이징이 되지 않습니다. 대신에 웹에서 카메라 API를 적용하여 조작 UI를 구현하며 나침반은 아래와 링크의 내용으로 Web Code로 구현가능합니다.

* 카메라 제어 API 샘플
http://sandbox.dtwincloud.com/code/main.do?id=camera_set
* 나침반 이미지 적용 예시
https://github.com/EgisCorp/XDWorld/issues/173

**Comment by avamk2** [comment]
### 지도 렌더링 속도를 개선할 수 있는 방법 존재 유무

포괄적인 부분이라 분야별 답변으로 이야기 드리겠습니다.

**서비스 인프라 부분**
데이터 요청에 대한 서버와 네트워크 병목에 대한 해소로서 지도 서버 구축의 경우 L7 어플리케이션 서버 단(apache,nginx,haproxy 등)에서 로드밸런싱을 통한 request 분산 처리를 통해 성능을 향상 시키는 방법이 있습니다.

**지도사용 설정 부분**
기본적으로 PC와 네트워크 환경에 따른 성능차이가 존재하며 사용목적에 따른 데이터 표출량과 품질에도 영향을 받게됩니다.
API 단에서는 불필요한 레이어 가시화는 지양해주시고, 표출하는 데이터 품질 및 오브젝트 가시거리와 Ratio 조정을 API를 통해 일정수준 최적화 할 수 있습니다

**엔진의 개선**
기술적으로 현재 엔진에서 최적화 및 신기술 도입등으로 진행되며 이는 저희쪽에 R&D 및 개발사항으로 계속적으로 보고 있습니다. 때문에 현재버전보다 개선된 기술도입을 통해서도 지속적으로 향상될 것입니다.

**Comment by avamk2** [comment]
### 측정 동작에 사용되는 이벤트(callBackCompletePoint) 이외에 JSOption등을 통해 정의된 다른 callback함수 존재 유무
ex) 마우스 모드 MML_SELECT_POLY(폴리곤 선택)에서 폴리곤을 그린 후에 정의된 callback 함수 들이 있는지

마우스 모드에 콜백 함수를 반환하는 경우도 있지만 기능에 따라 반환하지 않는 모드도 존재합니다.
다양한 마우스 모드가 존재하므로 필요하신 기능을 문의해주시면 관련 모드에 대해 안내드리겠습니다. 
**이는 다음 답변에 연결됩니다.**

**Comment by avamk2** [comment]
### 마우스 모드에 있는 이벤트 method들의 소스 코드를 볼 수 있는지
ex) Module.XDSetMouseState(Module.MML_SELECT_CIRCLE) / Module.XDSetMouseState(Module.MML_FIGURE_RECT)
등의 마우스 모드 등이 어떤 클래스와 이벤트를 사용하는지 궁금합니다. 가능하면 소스 코드도 보고 싶습니다.

**마우스 모드 리스트**
https://egiscorp.gitbook.io/xdworld-webgl-manual/etc/type-list#mouse-type-list

**내장 이벤트 리스트**
https://egiscorp.gitbook.io/xdworld-webgl-manual/etc/event

소스 문의인 경우 API의 활용법에 대한 문의를 주신 것으로 파악됩니다. 관련 기능을 문의해주시면 사용 샘플코드 및 샌드박스 URL을 안내드리겠습니다.

**Comment by avamk2** [comment]
### MML_SELECT_POINT에는 Fire_EventSelectedObject 이벤트가 적용 되지만 다른 SELECT 모드에는 적용이 안 되는 걸로 파악이 됩니다. MML_SELECT_CIRCLE 등에도 Fire_EventSelectedObject와 유사한 이벤트가 있는지 없다면 반경이나 폴리곤 선택을 이용하여 건물 오브젝트들을 한꺼번에 어떤 식으로 선택할 수 있는지 궁금합니다.

현재 엔진에서는 단일 단위로 선택 오브젝트 정보를 반환하는 API만 존재합니다. (1.42.1 버전 기준)
API 레벨에서 다수 객체 선택에 관련된 인터페이스 반환하는 API 부분에 대해서는 추가로 개발 중에 있으며 API 개발 및 배포시에 이를 공지해 드리겠습니다.

**Comment by avamk2** [comment]
### 배경지도의 해상도가 변경 되는 카메라의 고도 및 시야각의 기준 수치가 있는지, 기준 수치가 있다면 기준 수치 설정 가능 여부
### 건물 레이어의 object가 3D로 보이는 카메라의 고도 및 시야각의 기준 수치가 있는지, 기준 수치가 있다면 기준 수치 설정 가능 여부

지도서버에 연결하여 처리되는 서비스 데이터의 LOD(Level of detail)는 지형의 경우 지형 DEM의 타일의 3차원 박스와 카메라 간 거리를 통해 결정되며, 오브젝트의 경우도 동일하게 3차원 오브젝트 박스와 카메라 간 거리를 통해 결정됩니다. 건물 레이어 object 가시화 여부도 해상도와 같은 방식으로 결정됩니다. 이 데이터는 정적 정보가 아니라 데이터 구축시 정보와 API를 통한 LOD 비율 설정에 따라서 가변성을 갖고 있습니다. 이는 지형 타일 및 object와 가시화 여부를 판별한 후, 가시화 해야 하는 경우 세부적으로 해상도(LOD)를 결정하게 됩니다.

사용자 등록 객체(인스턴스 객체)는 서비스 레이어와 달리 지역적 데이터를 취급하기 때문에 아래 2개의 API를 통해서 가시거리 (m)를 직접 설정합니다.
https://egiscorp.gitbook.io/xdworld-webgl-manual/layer/jslayer#setmindistance-distance-boolean
https://egiscorp.gitbook.io/xdworld-webgl-manual/layer/jslayer#setmaxdistance-distance-boolean

**Comment by avamk2** [comment]
### 거리 측정 기능 Module.MML_ANALYS_DISTANCE 옵션에서 마우스를 클릭을 여러번 하면서 거리를 측정했을 때,
Uncaught abort(112). Build with -s ASSERTIONS=1 for more info.와 같은 에러가 발생하며 모듈이 멈추는 현상이 발생합니다
문제 해결 방안이 있는지 궁금합니다.

에러 사항에 대한 적용 코드 또는 샘플 코드와 실제 조작 정보를 제공해 주시면 확인하여 문제해결을 지원해 드리겠습니다.
이부분 문의는 새로 이슈로 상세히 보내주시면 해당 건을 구체적으로 논의 하면 좋겠습니다.

**Comment by avamk2** [comment]
### 맵에서 geoserver에 존재하는 레이어를 WFS로 호출하는 예제 존재 유무 및 XDWorld API를 통해 WFS(레이어)를 호출 하는 방법이 궁금합니다.

원래는 해당 부분에 기능을 제공하였었는데 운영중 성능과 안정성 이슈가 있어서 해당 기능을 잠시 중단 하였습니다.
현재 WFS의 경우 POI(포인트) 정보를 요청 처리하는 기능이 존재합니다. 조만간 샌드박스에 해당 부분의 샘플링을 제공할 예정입니다.
이 외 Polygon, line 객체 가시화에 관련되어서는 해당 부분이 보완되면 배포 및 코드 샘플과 함께 제공예정입니다.
