### ISSUE TITLE
polygon 생성 성능 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#25]
안녕하세요. 바이브컴퍼니입니다.

시도단위의 폴리곤 생성 테스트중입니다.
성능관련 문의입니다.

세종시를 테스트로 구현했습니다.
아래 이미지처럼 8초 가까이 시간이 소요되었습니다.

폴리곤이 더 많거나 복잡하면 훨씬더 오래 시간이 소요되었습니다.

질문)
로직중에 틀린 부분이 있나요?
로직중에 성능 향상을 위해 수정할 부분이 있나요?

[관련 로직]
![image](https://user-images.githubusercontent.com/38479834/121309292-f6287780-c93c-11eb-8ab4-77ef18a11f88.png)

[세종시 폴리곤 모양]
![image](https://user-images.githubusercontent.com/38479834/121309376-135d4600-c93d-11eb-8499-04cce474bd6c.png)

[개발자 도구 콘솔 로그]
![image](https://user-images.githubusercontent.com/38479834/121309608-561f1e00-c93d-11eb-90f1-3081ffe272d7.png)

**Comment by YangHeeBong** [comment]
충분히 오래 걸릴수 있는 사항입니다. 현재 객체를 생성하기 위해서 
1) 경위도좌표 -> 구면좌표 변환 작업
2) 구면 좌표 -> 삼각 분할
3) 정점 리스트, 삼각 분할 인덱스 구성 생성

작업 이후 객체를 생성하게 됩니다.

속도 향상을 위해서는 선 가공된 데이터를 만드는 방법이 가장 빠릅니다.
