### ISSUE TITLE
JSArrow API 문서의 CreateArrow() 매개변수 수정

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#251]
엔진 버전
: 1.41.0

오류 발생 API
: Create(position, pan, tilt, distance, radius, arrow_radius, color) → boolean

오류 내용
: 안녕하세요. 해당 API 매개변수 설명과 샌드박스를 확인해보니, 매개변수 하나에 대한 설명이 빠져있다고 생각해 문의 올립니다.
```javascript
    // 화살표 객체 생성
    var arrow = Module.CreateArrow("ARROW");
    arrow.Create(new Module.JSVector3D(126.49688669773418, 33.49872890745448, 100.0),
                 180.0, 0.0, 300, 5, 0.1, 5.0,
                 new Module.JSColor(255, 255, 0, 0));
```
문서에서 Create()의 매개변수는 7개인데, 샌드박스에서는 8개입니다.
0.1은 radius/arrow_radius와 관계없으며, 현재는 화살표에서 화살촉이 차지하는 비율을 0.0~1.0사이로 조절하는 매개변수라고 추측하고 있습니다.

Create() 함수의 6번째 변수는 무엇을 나타내나요? 만약 특정 변수에 대한 설명이 빠져있다면, 추가 부탁드립니다.

**Comment by YunSumin** [comment]
안녕하세요,

문의 주신 내용으로 문서의 여섯 번째 파라미터 head_rate 변수 누락을 확인하였습니다.
해당 값은 추측 하신 대로 화살촉이 차지하는 비율을 설정하는 값 입니다.

해당 문서 내용을 보완하였습니다. 확인 감사드립니다.

**Comment by HeoTaeYang** [comment]
수정 고맙습니다.
