### ISSUE TITLE
직선과 닿는 오브젝트 확인하는 방법

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#252]
엔진 버전
: 1.43.0

문의 내용
: 안녕하세요. 특정 방향을 가리키는 반직선과 접촉하는 가장 가까운 오브젝트(건물, 지면)의 ID를 알고 싶습니다.
해당 기능을 가진 API가 있을까요?

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

API JSLayer.getPickInfoAtView를 사용하시면 특정 직선으로 가장 가까이 교차판정이 되는 오브젝트를 반환합니다.

```javascript

let pick = "오브젝트 교차 판정 레이어".getPickInfoAtView(new Module.JSVector3D(longitude, latitude, altitude), new Module.JSVector3D(longitude, latitude, altitude));
```

#### API 매개 변수
  *  @param (JSVector3D) : 교차판정 할 라인 시작 경위도 지점
  *  @param (JSVector3D) : 교차판정 할 라인 끝 경위도 지점

#### API 반환 변수
  * JSObject 반환

**Comment by HeoTaeYang** [comment]
답변 감사합니다.
