### ISSUE TITLE
특정 위치의 고도 확인

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#254]
엔진 버전
: v_1.44.0

문의 내용
: 안녕하세요. 위도/경도로 특정된 위치의 해발고도/지면고도를 구하고 싶습니다.
해당 기능을 가진 API가 있을까요?

**Comment by YunSumin** [comment]
안녕하세요,

아래 API를 통해 엔진 내에서 특정 위치 고도 반환이 가능합니다.

``` javascript
var altitude = Module.getMap().getTerrHeightFast(경도, 위도);
```

단, 엔진에 로드 된 레벨의 DEM 고도만 반환이 가능합니다.

DEM의 경우 0레벨부터 기본 15레벨까지 존재하는데, 레벨이 커질수록 DEM이 디테일하게 표시됩니다.
카메라 고도가 너무 높아 충분한 레벨의 DEM이 로드 되지 않았을 경우
정밀한 고도 값 반환이 어려우므로 이 점 유의 부탁 드립니다.

**Comment by HeoTaeYang** [comment]
알려주셔서 감사합니다.
