### ISSUE TITLE
facility_build layer 호출하는 방법

### ISSUE THREAD

**Issue by HeoTaeYang** [EgisCorp/XDWorld#255]
엔진 버전
: v_1.44.0

문의 내용
: 안녕하세요. 지난 번 올렸던 [직선과 닿는 오브젝트 확인하는 방법](https://github.com/EgisCorp/XDWorld/issues/252)에 대한 추가적인 문의입니다. 이슈를 통해 레이어에서 반직선과 충돌하는 오브젝트를 확인할 수 있음을 알게 되었습니다.

이번에는 이 API를 사용하여 건물 오브젝트와의 충돌여부도 알고 싶습니다.
건물 오브젝트가 담겨 있는 XDEMap의 "facility_build" layer 객체를 호출하는 방법이 궁금합니다.

**Comment by YunSumin** [comment]
안녕하세요,
건물 레이어는 타일 레이어 리스트에서  레이어 이름을 통해 반환 받으실 수 있습니다.
``` javascript
var layer = Module.getTileLayerList().nameAtLayer("facility_build");
```

반환 받은 JSLayer 오브젝트를 활용하시면 됩니다.

**Comment by HeoTaeYang** [comment]
타일 레이어에서 찾을 수 있었군요. 알려주셔서 감사합니다.
