### ISSUE TITLE
폴리곤 체적 기능

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#256]
엔진 버전
: 1.38.0

문의 내용
: 안녕하세요.
 폴리곤 객체를 지도 상에서 선택했을 때 해당 객체의 체적을 구하는 API가 있나요?

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

선택된  Object Type이 JSPolygon이라면 평면기준 getArea() 함수를 통해 면적을 반환 할 수 있습니다.
