### ISSUE TITLE
FIGURE 선택 삭제 문의

### ISSUE THREAD

**Issue by seepieex** [EgisCorp/XDWorld#258]
엔진 버전
:v0.0.0.1

문의 내용
안녕하세요
XDSetMouseState(101) MML_FIGURE_RECT
XDSetMouseState(102) MML_FIGURE_ELLIPSE
XDSetMouseState(88) MML_ANALYS_AREA_PLANE을 가시화 한 후
필요에 의해 객체를 선택 하여 지울 수 있는 방법은 없나요?
또 XDSetMouseState(88)을 한 후 만들어진 AREA가 지표면에 묻히는 결과가 나타나는데 높이 조절을 할 수 있는 방법이 있나요?

감사합니다^^

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

1. MML_FIGURE_RECT, MML_FIGURE_ELLIPSE 등 객체 생성 후 삭제 기능
``
// 현재 선택된 객체 반환
var selObject = Module.getMap().getSelectObject();

// 객체를 생성한 레이어 탐색
var LayerList = new Module.JSLayerList(true);
var Layer = LayerList.nameAtLayer("객체를 생성한 레이어명");

// 해당 레이어에서 객체 삭제
Layer.removeAtObject(selObject);
``

2. MML_ANALYS_AREA_PLANE 객체가 지형에 묻히는 상황
  area 가시화 방법이 아래와 같이 2가지가 있습니다.
  상황에 맞춰 원하시는 기능을 사용하시면됩니다.

  * MML_ANALYS_AREA_PLANE : 3D 평면
  * MML_ANALYS_AREA : RTT 객체

감사합니다.

**Comment by seepieex** [comment]
안녕하세요 자세한 설명 감사합니다
제가 XDSetMouseState(101)을 통해 MML_FIGURE_RECT 객체를 생성한 후 
var LayerList = new Module.JSLayerList(true)를 선언해서 안에 LayerList.count()를 하니 0이라는 값이 나옵니다
XDSetMouseState(101)를 통해 생성된 FIGURE 객체는 어떤 레이어 위에 올라가는 건가요?

그리고 MML_ANALYS_AREA를 이용해서 생성한 객체를  마우스로 선택(Select)하는 방법이 있나요?

감사합니다^^

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

1. MML_FIGURE_RECT로 객체 생성시 입력되는 레이어
    [샌드박스](http://sandbox.dtwincloud.com/code/main.do?id=object_figure)
    샌드박스 예제 22 line을 보시면 레이어를 편집 상태(setEditable)로 할 경우 해당 레이어로 삽입됩니다.
    만약 레이어를 편집 상태로 설정하지 않을 경우 기본 레이어(Temporary)로 삽입됩니다.
    ```javascript
    GLOBAL.LayerList = new Module.JSLayerList(true);
    GLOBAL.Layer = GLOBAL.LayerList.createLayer("TestLayer", 0);
    GLOBAL.Layer.setEditable(true);
    ```
   
2. MML_ANALYS_AREA로 생성한 객체 선택
    해당 기능은 RTT객체를 선택하는 기능으로 현재 검토 중입니다.
    추후 기능 업데이트 시 다시 코멘트 드리겠습니다.

감사합니다.

**Comment by seepieex** [comment]
답변 감사합니다^^

샌드박스에서는 기능 확인 했습니다.
근데 제가 개발 하고 있는 곳에서는
Layer.setEditable(true)을 하게 되면 도형이 그려지지 않고

또 XDSetMouseState(101)을 사용하면 도형은 그려지고 편집 상태를 설정하지 않아서 LayerName은 Temporary로 확인 됐습니다
근데 이 JSLayer가 어느 JSLayerList 위에 생성 된건가요?

제가 const LayerList = new Module.JSLayerList(true)
LayerList.count()를 하면 0이라는 숫자가 나옵니다.

현재 올라와 있는 사용자 레이어 전체를 검색 할때 이렇게 하는게 아닌가요?
사용자 JSLayerList 갯수가 0인데 Temporary라는 JSLayer가 생성 될수 있는건가요?

감사합니다!

**Comment by SeongRyong-Choi** [comment]
Temporary 임시 레이어는
```javascript
var LayerList = new Module.JSLayerList(true);
console.log(LayerList.count());
var layer = LayerList.nameAtLayer("Temporary");
console.log(layer);
```
소스로 확인가능합니다.

1.43.0 최신 엔진 버전으로 테스트 결과

편집 상태 활성화, 비활성화 모두 객체가 정상 생성되는것을 확인하였습니다.

현재 사용중이신 엔진 버전을 v0.0.0.1로 작성하셨는데 정확한 엔진 버전 확인 후 말씀해주시면 감사하겠습니다.

**Comment by seepieex** [comment]
넵 자세한 답변 감사합니다
확인해보겠습니다!
