### ISSUE TITLE
여러 객체 선택 기능

### ISSUE THREAD

**Issue by seepieex** [EgisCorp/XDWorld#259]
엔진 버전
:1.41.0

문의 내용
:안녕하세요 
예제를 통해 Module.MML_SELECT_POINT을 통해 건물 객체를 하나 선택하는 것을 봤습니다.

MML_SELECT_RECT, MML_SELECT_CIRCLE, MML_SELECT_POLY을 이용하여 여러 객체를 선택 할 수 있는건가요?
여러 객체를 선택 할 수 있다면 예제를 제공 받을 수 있을까요?

감사합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

현재 MML_SELECT_CIRCLE 반경선택 기능만 제공되고있습니다.

추후 MML_SELECT_RECT,  MML_SELECT_POLY 선택 기능은 엔진 정기 업데이트에서 추가하겠습니다.

감사합니다.

**Comment by YangHeeBong** [comment]
1.45.0 엔진 릴리즈를 통해 사용 가능합니다.
