### ISSUE TITLE
WMS Layer 가시화 개수 제한

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#26]
4개 이상 넘어가면 문제가 생기는데... 혹시 요거 WMS에 ,로 묶어서 개발자가 보내는 것도 좋지만 API쪽에서 자원을 관리해주었으면 합니다.
Cesium이나 Mago같은 타 플랫폼에서도 WMS 레이어 중첩 도시에 개수 제한을 두지 않는데... 방법이야 어떻곤 API를 지원할때 해당 내용을 반영해서 신규 API를 혹시 만들어 주실 수 있으신가요?
단기적으로 보았을때는 힘드실 수 있지만 장기적으로 보았을때 EGIS 엔진을 쓰는 개발자로써는 꼭 필요한 기능으로 느껴집니다

**Comment by SeongRyong-Choi** [comment]
네 해당부분에 대해서 내부적으로 회의를 통해 추후 엔진 업데이트 하겠습니다.

감사합니다.

**Comment by YangHeeBong** [comment]
현재 요청 하신 부분에 대해서 2가지 방법으로 지원 예정입니다.
동일한 geoserver에서 다중 레이어 처리 방법과 출력 wms 레이어 수 변경 입니다.

1. geoserver 다중 처리
![image](https://user-images.githubusercontent.com/82924515/123890454-31ddbc80-d992-11eb-92aa-842ccc710072.png)
  위 이미지 처럼 동일 옵션 서버에 레어어 명칭, 스타일 (1:1 매칭)을 이용하여 다중 처리 가능하게 처리 하였습니다.

2. wms 레이어 출력 수 변경
 현재 4개 지원에서 7개 지원으로 변경 되어 있습니다.
 
webGL 텍스쳐 스테이지는 
https://webglreport.com/?v=1 사이트에서 명시하듯 최대 16개 입니다.
분석, 그림자, rtt, 베이스 이미지 등을 정리하여 WMS 갯수를 최대한으로 늘렸으며 추후 속도 문제를 확인하여 이미지 합쳐서 하나의 텍스쳐 스테이지를 사용하는 방법도 고려중 입니다.
