### ISSUE TITLE
오브젝트 selectable 설정 

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#260]
엔진 버전
: 1.43.0

문의 내용
: 

안녕하세요.

레이어 내의 각 오브젝트마다 selectable를 다르게 주려고 합니다.  

obj.setSelectable()를 사용하였는데 적용되지 않아서 혹시 layer 자체에만 selectable이 가능한지 문의드립니다.

obj.getSelectable()를 사용하니  true, false가 아닌 274가 반환됩니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

setSelectable() API는 객체 선택기능 활성화/비활성화 API입니다.
  * true : 선택 가능
  * false : 선택 불가능

객체 선택은 아래 API를 사용하시면 됩니다.
``javascript
Module.getMap().addSelectObject(JSObject);
```

감사합니다.

**Comment by suhwna** [comment]
답변 감사합니다.

재가 질문을 잘못 드린거 같습니다.

특정 오브젝트에만 setSelectable() true, false가 가능한가요?

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

setSelectable의 경우 JSObject 클래스로 객체마다 설정가능합니다.

사용법은 아래와 같습니다.

```javascript
object.setSelectable(Module.JS_SELECTABLE_ON);   // 선택 가능 상태로 전환
object.setSelectable(Module.JS_SELECTABLE_OFF);  // 선택 불가능 상태로 전환
```

감사합니다.

**Comment by suhwna** [comment]
답변해주신 api 사용해도 선택 불가능 상태로 바뀌지 않습니다. 

확인 부탁드립니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

해당 API 확인 결과 일부 객체 타입에 오류가 발생하는것을 확인하였습니다.

엔진  정기 업데이트에 해당 기능 수정 반영하겠습니다.

감사합니다.

**Comment by YangHeeBong** [comment]
1.45.0 엔진 릴리즈를 통해 오류 수정했습니다.
업데이트 릴리즈를 참조 부탁드립니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

기존 API 파라미터 정보가 변경되어 사용방법 안내드립니다.

[변경전 사용법]
object.setSelectable(Module.JS_SELECTABLE_ON);   // 선택 가능 상태로 전환
object.setSelectable(Module.JS_SELECTABLE_OFF);  // 선택 불가능 상태로 전환

[변경후 사용법]
object.setSelectable(true);   // 선택 가능 상태로 전환
object.setSelectable(false);  // 선택 불가능 상태로 전환

감사합니다.

**Comment by suhwna** [comment]
감사합니다.
