### ISSUE TITLE
벡터 지도 사용

### ISSUE THREAD

**Issue by seepieex** [EgisCorp/XDWorld#261]
엔진 버전
:1.41.0

문의 내용
:안녕하세요 지금 배경 영상으로 항공영상을 사용하고 있습니다.
항공영상 대신 벡터 지도를 사용할 수 있는 방법이 있을까요?

**Comment by hjaejae** [comment]
안녕하세요~
현재 배경영상으로는 WMTS 형식으로 사용 가능하게 되어있습니다.
혹시 WFS를 말씀하시는거라면 그 내용은 현재 Point 형식만 지원하고 있으며
추후 line 및  polygon에 대해서는 기능 제공 방식을 논의 중에 있습니다.

**Comment by seepieex** [comment]
네 답변 갑사합니다
그럼 지금 기본 지도로 벡터 지도를 사용 할 수 없다는 건가요?
