### ISSUE TITLE
egis 엔진 위 폴리곤 객체 선택

### ISSUE THREAD

**Issue by seepieex** [EgisCorp/XDWorld#264]
엔진 버전
:1.41.0

문의 내용
:
안녕하세요 제가 egis 엔진 위에 폴리곤 layer(건물관련) 하나를  wms로 얹었습니다
그 폴리곤을 선택할 수 있는 방법이 있나요?

감사합니다.

**Comment by seepieex** [comment]
docs를 읽어보니 ew Module.JSLayerList(false)로 만들어진 WMS 레이어는 편집레이어로 변경이 불가능한걸로 파악 했습니다.

그럼 서비스레이어로 올라간 레이어에서 객체를 선택할 수 있는 방법은 어떤게 있나요?
감사합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

wms 레이어는 이미지를 지도에 매핑하는 하이브리드입니다.

특정 폴리곤(실제는 폴리곤이 아닌 이미지)선택하여 선택효과 가시화하는 방법을 사용하기 위해서는 wfs를 이용하시면 좋을것 같습니다.

현재 wfs는 point만 지원하고 있으며 추후 line, polygon 지원할 예정입니다.

감사합니다.

**Comment by seepieex** [comment]
네 알겠습니다 자세한 답변 감사합니다
