### ISSUE TITLE
HTML POI setSizeFix 기능

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#265]
엔진 버전
: 1.45.0 

문의 내용
: 안녕하세요. 
Billboard에는 화면 확대 축소에 따라 크기 고정여부를 결정하는 setSizeFix기능이 있던데
혹시 HTML POI에도 이 기능을 사용할 수 있는 API가 있나요?
없다면 기능추가가 가능한가요?

![image](https://user-images.githubusercontent.com/49426364/219528257-f623a8f4-a844-4484-b16c-ce5d16aa0115.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

calback함수를 이용한 div 사이즈 조절이있습니다.
```javascript
function callback(e) {
	let distance = e.viewDistance;   // 객체와 카메라 사이 거리
	distance *= 0.01;

	let size = Math.ceil(distance);
	if (size < 60) size = 60;
	else if (size > 300) size = 300;
	let px = size + "px";
	let box = e.element.getElementsByClassName("box");

	e.element.style.width = px;
	e.element.style.height = px;
	box[0].style.width = px;
	box[0].style.height = px;
}
```

HTML POI의 경우 WebGL에 종속되지 않고 HTML에 종속되어있어 엔진 내부처리가 어렵습니다.

스케일 고정된 객체를 사용하기 위해서는 WebGL에 종속된 billboard객체를 사용하시는게 좋습니다.

감사합니다.

**Comment by KIMSEONOK** [comment]
감사합니다~!
