### ISSUE TITLE
거리 측정, 면적 측정 종료 후 마우스 이벤트 문제

### ISSUE THREAD

**Issue by JYKim-w** [EgisCorp/XDWorld#266]
엔진 버전
- 1.44
- 1.45

오류 발생 API
```
Module.XDSetMouseState(Module.MML_ANALYS_DISTANCE_STRAIGHT);
Module.XDSetMouseState(Module.MML_ANALYS_AREA);
```

오류 내용

- 거리측정, 면적측정 더블클릭으로 종료 후, 마우스 다운 시 커서가 블락되면서 
마우스 down 상태로 홀드되어 드래그(지도이동) 조작이 제대로 동작하지 않습니다.
확인부탁드립니다.

![캡처_2023_02_20_14_44_49_730](https://user-images.githubusercontent.com/89620738/220020331-0980dcc9-509e-4673-a9cc-be1bbb008544.png)

**Comment by avamk2** [comment]
안녕하세요

해당 버전으로 대상 기능을 단위 테스트 해보았지만 언급하신 오류가 발생하지 않았습니다.

개발코드에서 Draggable 같은 속성 같은것이 변경되었는지 확인부타드립니다.

**Comment by JYKim-w** [comment]
답변 감사합니다.

3D 지도 canvas 및 상위 element에 draggable 및 다른 속성 변화는 없는 상태에서 동일현상이 계속 발생합니다.
프로젝트에 포함된 라이브러리 충돌이 의심됩니다.

부모 element에 `user-select : none` 적용하여 해결했습니다.

감사합니다.
