### ISSUE TITLE
layer 위에 있는 getObjects() 활성화

### ISSUE THREAD

**Issue by seepieex** [EgisCorp/XDWorld#268]
엔진 버전
:1.41

문의 내용
:
안녕하세요 현재 건물 레이어에 있는 건물들을 폴리곤으로 선택 하고 폴리곤 안에 있는 건물들의 색상을 바껴주는 기능을 개발 하고 있습니다.

건물 레이어 위에 객체를 getObjects()로 선택할 경우 3D 가시화가 된 건물들만 선택이 get 가능해서 카메라가 멀리 있는 경우 선택이 불가능 한 것으로 확인 했습니다 해결 방법이 있을까요?

제가 생각한 방법은

1. 카메라가 멀리 있는 경우에도 3D 건물들이 활성화 되게 한다.
2. getObjects() 대신 다른 method가 있다면 그 method를 사용하여 활성화 되지 않은 건물들도 선택할 수 있다

이 정도입니다.

getObjects() 대신 사용할 method가 있을까요??
감사합니다.

**Comment by avamk2** [comment]
안녕하세요

해당 부분에 대한 사항은 넓은지역을 서비스하는 3D 공간데이터를 취급하는 부분에서 스트리밍 데이터를 처리하는 과정에서 발생합니다. 

API를 통해서 객체 클래스 인스턴스를 제공은 하지만 라이프타임이 존재합니다.

이는 3D 공간데이터 서비스의 전체용량을 클라이언트가 적제하지 못하기에 스트리밍형식으로 현재 가시화에 필요한 데이터를 수집하고 반대로 가시화 범위가 벗어난 데이터를 삭제하여서 메모리량을 유지할 수 있습니다. 그렇지 않으면 브라우저에서 사용 가능한 메모리 한도가 넘어가며 사이트가 새로고침 되어서 휘발됩니다.

객체 공간 검색에 관련해서도 클라이언트에서 서비스되는 객체들의 인덱스(리스트)정보를 갖고 있지 않습니다. 예를들어 전국 서비스 건물 데이터라고 한다면 전국에 모든 건물의 ID 정보만 등록해도 7백만건 이상을 등록해야됩니다.

현재 해당 부분을 구현하기 위해서는 아래와 같은 절차를 통해서 가능한 부분이 있습니다.

1. 3D 건물객체의 Key와 매칭되는 2D 건물 폴리곤를 GeoServer를 통해서 서비스
2. WFS의 공간쿼리를 통해서 3D 건물객체의 Key를 조회
3. 특정한 이벤트 타이밍(카메라 이동 완료, 마우스 버튼업 등)에서 Key를 통한 `JSObject JSLayer::keyAtObject(_objectKey)` 객체 인스턴스가 null이 아니면 (null은 대상 key의 객체가 없거나 현재 로딩되지 않은 상태) 색상을 설정

이러한 방식으로 기능을 적용할 수 있습니다. 만약 공간검색범위가 고정이라면 WFS 공간검색 대신 3D 건물 Key들을 바로 대입해도 됩니다.

**Comment by avamk2** [comment]
1. 데이터 생성과 수집단계에서 가능한 부분입니다. 서비스 건물 데이터 기준으로는 배치 및 검증을 위해서 3D 모델과 함께 SHP 데이터를 같이 받게 되는데 이 SHP가 매칭정보로 사용할 수 있습니다. 서비스 사용만을 대상으로 한다면 이부분은 어려울 수 있습니다.

XDServer에서는 공간 검색을 수행하진 않습니다. 해당 수행시 서버 자원이 2D보다 비약적으로 많아 데이터 스트리밍 서비스 수행에도 영향을 줄수 있기에 이를 병렬적으로 구성하는 부분에서 GeoServer를 권유하는 부분이며 공간DB를 통한 공간 검색이 가능하다면 PostSQL이나 오라클등의 DB를 직접 쿼리해도 관계는 없습니다.

**Comment by seepieex** [comment]
네 알겠습니다
자세한 설명 감사합니다^^
