### ISSUE TITLE
지도 로드 후 초기화면에서부터 레이어 선명하게 볼 수 있는 방법

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#269]
엔진 버전
: 1.45.0

문의 내용
: 안녕하세요.

아래 이미지는 XDSERVER로부터 타일링된 데이터를 호출한 행정경계 레이어와
GEOSERVER에서 WMS로 호출한 지하철노선도 레이어를 표출한 화면입니다.
첫번째 이미지는 처음 지도를 로드했을 때 초기화면이고, 
두번째 이미지는 한 번 지도를 확대를 하고 다시 초기위치화면으로 이동했을 때 화면입니다.

두번째 이미지처럼 처음 지도를 로드했을 때부터 더 높은 레벨의 레이어를 호출하듯이
레이어가 더 선명하게 보일수 있게하는 방법이 있을까요?

![image](https://user-images.githubusercontent.com/49426364/221777675-26c2038e-fc5a-4ab9-b87c-57b64b925451.png)
![image](https://user-images.githubusercontent.com/49426364/221777856-3c27194a-0097-4169-bb92-9cc5857bd1ed.png)

**Comment by hjaejae** [comment]
안녕하세요~
높은 레벨의 지형을 보기 위해서는 아래와 같이 지형의 레벨을 결정 하는 변수중 하나인 LOD Ratio 값을 높여주면 됩니다.

```javascript
var pMap = Module.getMap();
pMap.setTerrLODRatio(3.0);
```
그러나 지형의 LOD Ratio 값을 올릴수록 지형 호출양이 많아져서 속도에 영향을 미칠 수 있습니다.
값을 적당히 조절해보면서 값을 찾으시면 될것 같습니다.

**Comment by KIMSEONOK** [comment]
terrLODRatio 디폴트값은 몇인가요?

**Comment by hjaejae** [comment]
디폴트 값은 1.0이며 1.0보다 클수록 높은 해상도의 지형을 불러오게 됩니다.

**Comment by KIMSEONOK** [comment]
넵 감사합니다~ ㅎㅎ
