### ISSUE TITLE
이건 무슨 현상일까요????

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#27]
안녕하세요. 바이브컴퍼니입니다.

엔진을 0.1.1로 변경하였습니다.

업무 화면에 접속했는데 아래 영상과 같은 메시지가 무한으로 계~~~속 나옵니다.

(이전 엔진으로 오류 없는거 확인한 후 엔진를 교체 했습니다)

확인해 주시기 바랍니다~

https://user-images.githubusercontent.com/38479834/121345329-b030db00-c95f-11eb-9087-e8fc9d4f37c0.mp4

**Comment by HyunSeongKil** [comment]
엔진을 Version 1.3.15.7.2 (2021-06-07) 이것으로 교체하니깐 위와 같은 현상 없습니다.

**Comment by YunSumin** [comment]
안녕하십니까, 이지스입니다.
전달해주신 영상을 토대로 로그가 반복적으로 출력 되는 부분을 제거 후 수정된 엔진 파일을 업로드하였습니다.
파일 교체 부탁 드립니다.
감사합니다.
