### ISSUE TITLE
createVerticalPlane => SetCullMode 문의

### ISSUE THREAD

**Issue by HooYoungJyeon** [EgisCorp/XDWorld#270]
안녕하세요! 

참조한 링크 :
https://egiscorp.gitbook.io/xdworld-webgl-manual/object/jscolorpolygon
http://sandbox.dtwincloud.com/code/main.do?id=object_colorpolygon_gradation

1. SetCullMode에서 type 값에 따라 컬링옵션이 변경될때 0, 1 값이 둘 다 양면이라고 적혀있는데,
두 차이점이 무엇인지 알 수 있을까요?

2. 아래 두 이미지는 SetCullMode type을 0 또는 1로 설정한 후 두 개의 JSColorPolygon을 생성했을때 
사용자의 보는 방향에 따라 생성된 다른 JSColorPolygon이 투영되어 보이거나 보이지 않는 경우가 발생합니다.
어느 방향에서 보던  생성된 다른 JSColorPolygon이 다 투영될 수 있게 설정하는 방법이 있을까요?

![image](https://user-images.githubusercontent.com/98065800/222331494-46d110a2-68de-4354-901a-54176711577c.png)
![image](https://user-images.githubusercontent.com/98065800/222331564-c00478a8-7629-4773-826b-f22d9bc10a28.png)

![image](https://user-images.githubusercontent.com/98065800/222331996-fba3b487-19e1-408c-aa34-5f09225d1bf8.png)
![image](https://user-images.githubusercontent.com/98065800/222332028-dac3fa94-3651-4af3-9e31-febfdc13a06f.png)

**Comment by YunSumin** [comment]
안녕하세요

**1. SetCullMode에서 type 값에 따라 컬링옵션이 변경될때 0, 1 값이 둘 다 양면이라고 적혀있는데,
두 차이점이 무엇인지 알 수 있을까요?**

: 0, 1값 둘 다 동작의 차이점은 없습니다. 모두 양면으로 렌더링 되도록 동작합니다.

**2. 아래 두 이미지는 SetCullMode type을 0 또는 1로 설정한 후 두 개의 JSColorPolygon을 생성했을때
사용자의 보는 방향에 따라 생성된 다른 JSColorPolygon이 투영되어 보이거나 보이지 않는 경우가 발생합니다.
어느 방향에서 보던 생성된 다른 JSColorPolygon이 다 투영될 수 있게 설정하는 방법이 있을까요?**

: 해당 부분은 폴리곤의 알파 블렌딩 렌더링 시 나타나는 현상으로, 투영을 위해 카메라로부터 가장 먼 거리의 삼각형을 차례로 그림으로써 해결이 가능한 부분입니다.
(https://learnopengl.com/Advanced-OpenGL/Blending 페이지의 Blending 항목에서 구체적인 설명을 확인하실 수 있습니다.)

이를 위해 모델을 삼각형 단위로 분할하여 카메라 간의 거리 별로 정렬하는 과정이 필요하나,
성능적인 부분에 영향이 있을 수 있어 이를 보완할 수 있도록 기술 개발 중 입니다.

감사합니다.

**Comment by HooYoungJyeon** [comment]
답변 감사합니다!
