### ISSUE TITLE
반경 draw

### ISSUE THREAD

**Issue by seepieex** [EgisCorp/XDWorld#271]
엔진 버전
:1.41.0

문의 내용
: 
안녕하세요 
반경 원 그리기 할때 미리 반경을 정해놓고(입력)하고 정해진 반경으로 반경 원을 그릴 수 있는 api 기능이 있나요?
감사합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

위치, 반경으로 객체 생성하는 샘플이 있습니다.

[반경그리기](http://sandbox.dtwincloud.com/code/main.do?id=object_polygon_circle)

감사합니다.

**Comment by seepieex** [comment]
참고하겠습니다

감사합니다.
