### ISSUE TITLE
그리기 시작/종료 이벤트 지원 여부 문의

### ISSUE THREAD

**Issue by JYKim-w** [EgisCorp/XDWorld#273]
엔진 버전
: v1.45.0

문의 내용
: 
1. 그리기를 활용해 공간검색기능을 구현하고 있습니다.
도형을 그린 후, 그려진 도형의 형상정보로 공간검색을 수행 하려고 하는데,
```
        Module.XDSetMouseState(Module.MML_INPUT_POINT);        
        Module.XDSetMouseState(Module.MML_INPUT_LINE);
        Module.XDSetMouseState(Module.MML_INPUT_RECT);
        Module.XDSetMouseState(Module.MML_INPUT_CIRCLE);
```
각 기능들의 그리기 시작/종료시점 이벤트를 제공하는지 문의드립니다.

2. `Module.XDSetMouseState(Module.MML_INPUT_POINT); `  의 경우 화면을 클릭해도 점이 생성되지 않습니다. 확인 부탁드립니다.

감사합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

1. 그리기를 활용해 공간검색기능을 구현하고 있습니다. 도형을 그린 후, 그려진 도형의 형상정보로 공간검색을 수행 하려고 하는데, 각 기능들의 그리기 시작/종료시점 이벤트를 제공하는지 문의드립니다.
    => 해당 이벤트는 html에서 제공하는 마우스 이벤트를 활용하여 확인할 수 있습니다.


2. Module.XDSetMouseState(Module.MML_INPUT_POINT);  의 경우 화면을 클릭해도 점이 생성되지 않습니다. 확인 부탁드립니다.
    => 해당 기능은 이번 엔진 정기 업데이트에 추가되었습니다. ( v_1.47.0 )

감사합니다.
