### ISSUE TITLE
가시권 분석 기능 사용시

### ISSUE THREAD

**Issue by yuuki9** [EgisCorp/XDWorld#275]
엔진 버전
:

문의 내용
:
![image](https://user-images.githubusercontent.com/101304194/224191151-c2461182-4463-4d7e-ba6f-dda413dfe53e.png)
	Module.getAnalysis().setVFMode(true);				
	Module.getAnalysis().setVFCreateClickMode(true);
위와 같이 설정한 후 마우스 클릭시 생성 되는 가시권 분석 모델에 생성될 시  높이값을 줄수 있는 옵션이 있는지 궁금합니다

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

가시권 분석 3D 방법은 두가지가 있습니다.

1. 마우스 클릭된 지점에 분석
   지형으로부터 2m 높이(사람의 시야)에서 가시권 분석 실행

2. 사용자가 직접 좌표를 입력하여 분석
   입력된 좌표로 가시권 분석 실행  
```javascript
Module.getAnalysis().setVFMode(true);		// 가시권 3D 표현 여부 설정
Module.getAnalysis().setVFPosition(new Module.JSVector3D(129.14244969702094, 35.15567356140572, 100));
```

만약 좌표를 모르고 클릭한 지점의 높이만 변경하고 싶을 경우
```javascript
Module.getAnalysis().setVFMode(true);		// 가시권 3D 표현 여부 설정
Module.XDSetMouseState(30);           // 클릭지점 경위도 좌표 반환 (MML_RETURN_ANALYSISPOS)

// MML_RETURN_ANALYSISPOS 경위도 좌표 반환 이벤트
canvas.addEventListener("Fire_EventAnalysisPos", function(e){
   Module.getAnalysis().setVFPosition(new Module.JSVector3D(e.lon, e.lat, e.alt + 설정할 높이));
});
```

감사합니다.

**Comment by yuuki9** [comment]
![image](https://user-images.githubusercontent.com/101304194/224220284-53930e19-bd8a-4adb-8a58-7aecdf7c5c9b.png)
추가로 질문 하나만 더 드리겠습니다!
건물 오브젝트를 제외한 일반 산이나 지형지물은 가시권 분석이 적용이 안되는 것 같은데 확인 한 번 부탁드리겠습니다!!

**Comment by yuuki9** [comment]
> 안녕하세요.
> 
> 가시권 분석 3D 방법은 두가지가 있습니다.
> 
> 1. 마우스 클릭된 지점에 분석
>    지형으로부터 2m 높이(사람의 시야)에서 가시권 분석 실행
> 2. 사용자가 직접 좌표를 입력하여 분석
>    입력된 좌표로 가시권 분석 실행
> 
> ```js
> Module.getAnalysis().setVFMode(true);		// 가시권 3D 표현 여부 설정
> Module.getAnalysis().setVFPosition(new Module.JSVector3D(129.14244969702094, 35.15567356140572, 100));
> ```
> 
> 만약 좌표를 모르고 클릭한 지점의 높이만 변경하고 싶을 경우
> 
> ```js
> Module.getAnalysis().setVFMode(true);		// 가시권 3D 표현 여부 설정
> Module.XDSetMouseState(30);           // 클릭지점 경위도 좌표 반환 (MML_RETURN_ANALYSISPOS)
> 
> // MML_RETURN_ANALYSISPOS 경위도 좌표 반환 이벤트
> canvas.addEventListener("Fire_EventAnalysisPos", function(e){
>    Module.getAnalysis().setVFPosition(new Module.JSVector3D(e.lon, e.lat, e.alt + 설정할 높이));
> });
> ```
> 
> 감사합니다.

한가지만 더 여쭈어 보겠습니다
![image](https://user-images.githubusercontent.com/101304194/224222978-d9ceebe9-040b-4403-adfe-20b764cd785f.png)
건물 오브젝트가 아닌 지형지물에 가시권 분석모델을 올려놓으면 빨간색으로 분석이 되지 않는데 일반 건물 오브젝트를 제외하곤 지형지물에 가시권 분석 기능이 구현이 안되있는 것인가요?

**Comment by SeongRyong-Choi** [comment]
해당 기능은 현재 엔진에 적용되어있으나 API로 지원되지 않습니다.

정기 업데이트에 해당 API를 지원하도록 하겠습니다.

감사합니다.

**Comment by SeongRyong-Choi** [comment]
해당 기능이 엔진 정기 업데이트에 추가되었습니다.

분석 전 지형 분석 여부를 설정하여 해당 기능을 확인할 수 있습니다.

Module.getAnalysis().setTerrainAnalysis(true);

감사합니다.
