### ISSUE TITLE
레이어 속 object 제거 중 오류

### ISSUE THREAD

**Issue by HooYoungJyeon** [EgisCorp/XDWorld#276]
참조링크: https://egiscorp.gitbook.io/xdworld-webgl-manual/layer/jslayer#removeatkey-name-boolean

오류 발생 API
:  JSLayer => removeAll(), removeAtKey() 등

오류 내용
:
안녕하세요.
생성된 레이어 내의 오브젝트 중 특정 오브젝트만 제거하려하는데, 지속적으로 abort 에러가 발생합니다.
해당 에러가 발생되는 조건이나 이유가 궁금합니다.

![image](https://user-images.githubusercontent.com/98065800/225163879-1ae3d88e-33a7-46b9-95a6-88f003b33472.png)
![image](https://user-images.githubusercontent.com/98065800/225164272-de936e0d-9c90-4991-869f-c97b016d2edb.png)

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

저희 쪽에서 관련 내용으로 삭제 결과 다음과 같은 결과를 확인하였습니다.

  * 환경
    * version : 1.46.0
    * layer Type : Module.ELT_POLYHEDRON
    * object Type : polygon


![이슈 기본화면](https://user-images.githubusercontent.com/82924515/225170267-1ee91582-ae4f-4970-90b1-00b2d21b9f12.JPG)
<기본화면>
![깃이슈 삭제완료](https://user-images.githubusercontent.com/82924515/225170305-f317615c-4d97-41df-8eb2-a3806dc1ba60.JPG)
<removeALL 동작 시>
![단일 삭제](https://user-images.githubusercontent.com/82924515/225170336-19bef538-0c3b-43f1-b06c-fd480c637073.JPG)
<removeAtKey 동작 시>

``` javascript
// 레이어 생성
var layerList = new Module.JSLayerList(true);
GLOBAL.layer = layerList.createLayer("POLYGON_LAYER", Module.ELT_POLYHEDRON);

// 폴리곤 생성
var polygon = Module.createPolygon("POLYGON_" + _objectkey);
// 폴리곤 생성 코드 생략
GLOBAL.layer.addObject(polygon, 0);
```

위 조건으로 데이터 삭제 시 문제가 없음을 판단하였습니다.
정확한 원인 규명을 위해서는 현재 문제가 발생하는 부분에 대해서 간단한 샘플 형식으로 입력값, 간략한 생성 코드 등을 기재해 주시면 원인 해결에 도움이 됩니다.

**Comment by HooYoungJyeon** [comment]
// 레이어 생성
var layerList = new Module.JSLayerList(true);
GLOBAL.layer = layerList.createLayer("POLYGON_LAYER", Module.ELT_POLYHEDRON);

// 폴리곤 생성
var polygon = Module.createPolygon("POLYGON_" + _objectkey);
// 폴리곤 생성 코드 생략
GLOBAL.layer.addObject(polygon, 0);

**Comment by HooYoungJyeon** [comment]
참조한 링크: http://sandbox.dtwincloud.com/code/main.do?id=object_colorpolygon_gradation

상단 링크를 참조하여
baseLine 대신 setCircle로 원 생성 후 createVerticalPlane 함수 따라 만들어진 다중 폴리곤들 obj중 삭제를 실행하였었을때 발생했었습니다.

혹시 버전 문제일 가능성도 있을까요?

![image](https://user-images.githubusercontent.com/98065800/225183283-9ccf142b-de47-4b0b-9547-25d9723c11b2.png)

**Comment by YangHeeBong** [comment]
말씀하신 대로 참조 링크를 기준으로 테스트 결과 아래와 같습니다.

![이슈 답변2 기본](https://user-images.githubusercontent.com/82924515/225208837-4f9476e0-de87-49ef-88dd-cac082abd7bb.JPG)
<기본화면>
![이슈 답변2 전체삭제](https://user-images.githubusercontent.com/82924515/225208855-ac533283-868e-4017-9af0-c58e584b89e1.JPG)
<removeALL 동작 시>
![이슈 답변2 단일삭제](https://user-images.githubusercontent.com/82924515/225208862-c472cb35-39ca-49ed-8d93-14cb8f0e8b64.JPG)
<removeAtKey 동작 시>

질문하신 버전 문제일 가능성이 없더라고 말씀드리기 힘들지만, 해당 버전 시 동일한 이슈 및 질문 사항에 존재해야 하지만 과거 버전에서 동일한 질문 및 이슈를 전달받은 적이 없습니다.

**Comment by HooYoungJyeon** [comment]
아니면 혹시 
![image](https://user-images.githubusercontent.com/98065800/225778420-b0c06c27-1bbc-4edc-9130-da99fd1a27e4.png)
해당 오류가 발생하는 조건이나 이전에 접수된 적이 있는지 알 수 있을까요

**Comment by heotaein** [comment]
안녕하세요. 

저희도 샌드박스나 Spring 환경에서는 정상 작동하는 것을 저희도 확인되었고 해당 엔진을 Angular 프레임워크에서 작동하였을 때 나타는 현상으로 엔진의 내부 소스와 Angular의 환경에서 충돌 나서 오류가 생기는 것으로 보입니다.

Angular에서 엔진의 POI나 LINE 등의 오브젝트 삭제, 레이어 삭제는 문제가 없이 정상 작동되는 것도 확인되었습니다.
(현재까지 확인된 부분은 Polygon을 삭제할 때만 생기는 오류로 보입니다)

저희 쪽에서는 엔진의 내부 소스까지 확인이 불가능하여 Angular 환경의 테스트용 프로젝트를 드리면 테스트를 해줄 수 있는지 문의드립니다.

**Comment by YangHeeBong** [comment]
저희가 사용 중인 pc에 여러 라이브러와 환경 설정이 되어 있어 동일한 환경에서 테스트하기 어려움이 있습니다.
