### ISSUE TITLE
지면 아래 객체 고도 측정 기능

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#277]
엔진 버전
: 1.45.0

문의 내용
: 안녕하세요.

아래와 같이 지면 아래에 3D 폴리곤을 만들고,
마우스를 고도측정모드로 변경한 후 폴리곤을 선택하면 폴리곤에 포인트가 찍히지 않고
지면에 포인트가 찍히게 됩니다.

지면 아래에 있는 폴리곤의 고도를 측정할 수 있는 방법이 있나요?

![image](https://user-images.githubusercontent.com/49426364/225845328-6ff64af0-3359-42e5-87de-1aa308a50c1e.png)
![image](https://user-images.githubusercontent.com/49426364/225845401-67a706f5-c162-41c5-93d9-8f51c6ccd672.png)

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

예전 이슈와 동일한 이슈로 판단되어 링크 안내드립니다.

[지형아래picking](https://github.com/EgisCorp/XDWorld/issues/224)

감사합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

지형 아래 객체 picking 기능은 추후 엔진 정기 업데이트에 추가할 예정입니다.

지형 아래 객체 picking 기능이 추가되면 해당 좌표를 기반으로 거리측정API를 사용할 수 있습니다.

하지만 현재 면적 측정 API는 제공되지 않습니다.

혹시 면적 측정 API도 필요하신건가요?

**Comment by KIMSEONOK** [comment]
넵! 총 거리, 면적, 고도, 체적 기능에 이 기능들이 필요한데 고도, 체적은 기존에 있던 기능을 응용해서 사용가능할 것 같고, 거리와 면적 기능은 따로 필요할 것 같습니다!

**Comment by SeongRyong-Choi** [comment]
현재 엔진에서 거리측정 API는 다음과 같습니다.

Module.getMap().GetPointDistance(시작 좌표, 끝 좌표, 지형 결합 여부)
- 시작좌표 (JSVector3D)
- 끝좌표 (JSVector3D)
- 지형 결합 여부 (bool) : true로 설정 시 시작-끝 경로점을 지형결합하여 계산

면적 측정 API는 이번 엔진 정기 업데이트에 추가하도록 하겠습니다.

감사합니다.

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

이번 엔진 정기 업데이트에 면적측정 기능이 추가되었습니다.

면적측정 API 예시
```javascript
1. 이벤트를 활용한 면적 측정
// 면적측정 시작 (마우스 모드 변경)
Module.XDSetMouseState(Module.MML_RETURN_ANALYSISPOS);

// 입력되는 점 리스트에 push
var vertex = new Module.JSVec3Array();
_canvas.addEventListener("Fire_EventAnalysisPos", function(e) {
     vertex.push(new Module.JSVector3D(e.lon, e.lat, e.alt));
});

// 면적측정 계산 실행
Module.getMap().GetPointsVolume(vertex);

// 면적측정 초기화
Module.XDSetMouseState(Module.MML_MOVE_GRAB);	// 마우스 모드 초기화
Module.getMap().clearInputPoint();

/////////////////////////////////////////////////////////////////////////////////////////////////

2. 이벤트를 활용하지 않고 면적 측정
// 면적측정 시작 (마우스 모드 변경)
Module.XDSetMouseState(Module.MML_RETURN_ANALYSISPOS);

// 면적측정 계산 실행
var vList = Module.getMap().getInputPoints();		
var vertex = new Module.JSVec3Array();		
for (var i=0; i<vList.length; i++) {
     vertex .push(new Module.JSVector2D(vList[i].Longitude, vList[i].Latitude, vList[i].Altitude));
}

// 면적측정 초기화
Module.XDSetMouseState(Module.MML_MOVE_GRAB);	// 마우스 모드 초기화
Module.getMap().clearInputPoint();
```

지형아래 객체 picking 예시
```javascript
function pickingSetting()
{
     Module.XDSetMouseState(Module.MML_RETURN_ANALYSISPOS);	// 클릭 지점 경위도 반환
     Module.getMap().setPickTerrain(false);					// 지형 picking 잠금
     Module.getOption().SetPointsDepthBuffer(false);			// point zbuffer 끄기
}

function pickingClear()
{
     Module.XDSetMouseState(Module.MML_MOVE_GRAB);	// 마우스 모드 초기화
     Module.getMap().clearInputPoint();				// 입력 포인트 삭제
     Module.getMap().setPickTerrain(true);			// 지형 picking 가능하도록 변경
     Module.getOption().SetPointsDepthBuffer(true);	// point zbuffer 켜기
}
```

감사합니다.

**Comment by KIMSEONOK** [comment]
이번 주 금요일에 업데이트되는 엔진에서 확인가능한게 맞나요?

**Comment by egiskorea-ryong** [comment]
안녕하세요.

안내드린 샘플소스에 등록되지 않은 MML_RETURN_ANALYSISPOS 있어 수정했습니다.

현재 1.49.0 버전이 최신 엔진 업데이트이며, 해당 기능은 1.48.0 버전 이후부터 사용 가능합니다.

안내드린 샘플소스에서 Module.MML_RETURN_ANALYSISPOS 부분은 다음 정기 업데이트에 등록될 예정입니다.

감사합니다.

**Comment by suhwna** [comment]
안녕하세요.
 
Module.XDSetMouseState(30);	// 클릭 지점 경위도 반환 (정기 업데이트 후 Module.MML_RETURN_ANALYSISPOS 등록) 
Module.getMap().setPickTerrain(false);					// 지형 picking 잠금
Module.getOption().SetPointsDepthBuffer(false);			// point zbuffer 끄기 

사용 시, 지면 아래를 클릭하면 영상과 같은 문제가 발생하는데 해결 방법이 있을까요? 
![image](https://user-images.githubusercontent.com/91519109/230272471-f36e85fe-d55a-45d0-9e9f-6c674e1dab1f.png)

https://user-images.githubusercontent.com/91519109/230272340-9ba0723d-c5dd-4685-948a-bee55cc5418a.mp4

**Comment by egiskorea-ryong** [comment]
해당 기능 확인 결과 오류가 발견되어 엔진 업데이트(Hotfix) 하였습니다.

감사합니다.
