### ISSUE TITLE
줌인,줌아웃 속도 조절

### ISSUE THREAD

**Issue by seepieex** [EgisCorp/XDWorld#278]
엔진 버전
: 1.41.0

문의 내용
:
안녕하세요 api를 쓰다가 갑자기 안 나던 오류가 나는 상황입니다.
줌인 줌아웃을 하면 
VM25801:1 Uncaught abort(10). Build with -s ASSERTIONS=1 for more info.
이라는 오류가 나오고 있는 상황입니다. 
금방 해결할 수 있는 오류는 아닌거 같아서 일단
줌인,줌아웃 속도만 천천히 바꿀 수 있는지 궁금합니다

감사합니다.

**Comment by seepieex** [comment]
마우스 delta 속성을 바껴봤는데 오류가 계속 나는데 혹시 해결책이 있을까요??

**Comment by YunSumin** [comment]
안녕하세요,

VM25801:1 Uncaught abort(10). Build with -s ASSERTIONS=1 for more info.
메시지는 통상적으로 메모리와 관련하여 오류가 발생했을 때 출력 되는 경우가 많습니다.

오브젝트 삭제, 레이어 삭제, 삭제된 오브젝트의 참조 등 다양한 경우에 발생하는 메시지이기에
제보해주신 메시지 만으로는 구체적인 원인을 알기 어려운 문제가 있습니다.

마우스 줌 인/아웃 기능과 동시에 동작하는 루틴에서 오류가 발생한 것으로 보이므로
번거로우시겠지만 해당 동작 시 실행되는 모듈들의 체크가 필요할 것 같습니다.

마우스 휠 동작 시 실행되는 기능 리스트 및 영상을 첨부해주신다면 원인을 확인해보겠습니다.
오류 내용이 제한적이라 빠른 해결 방안 전달이 어려운 점 양해 부탁 드립니다.

감사합니다.
