### ISSUE TITLE
html poi z-index 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#279]
엔진 버전
: 1.45.0

문의 내용
:

안녕하세요.

html poi 생성 시, z-index가 생성된 순서대로 들어가는데 z-index를 직접 설정하는 방법은 없을까요?

poi가 겹치는 경우가 있어서 나중에 생성된 poi를 상위로 올리고 싶습니다.

![image](https://user-images.githubusercontent.com/91519109/228401535-d3b0dbfe-bc6f-4d3e-8eaa-a5bc92eeaa87.png)

![image](https://user-images.githubusercontent.com/91519109/228401552-aaf4f051-1756-4f1b-b249-f371a9f1e04f.png)

**Comment by EgisCorp** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

먼저 createHTMLObject으로 생성된 Object가 z-index가 설정되는 과정에 대해서 설명드리겠습니다.

## HTMLObject z-index 설정 과정
질문 내용인 "html poi 생성 시, z-index가 생성된 순서대로 들어가는데" 순서 대로 진행하는게 아닌 거리에 따라 z-index가 설정됩니다.

![image](https://user-images.githubusercontent.com/84553395/228410743-02f98e47-3bac-4354-9d6b-63688c21299a.png)

이 그림을 기준으로 z-index 설정된 값은 아래와 같습니다.
> DIV 1 : 2
> DIV 2 : 1

먼거리를 시작으로 가까운 값으로 z-index가 설정됩니다.

그럼 createHTMLObject으로 생성된 z-index 변경방법은 html element를 불러와서 z-index를 직접적으로 수정하시면 가능합니다.
하지만 카메라 이동이 있을 경우 "HTMLObject z-index 설정 과정"이 동작 됨으로 마우스 이벤트를 조절하시면 됩니다.

**Comment by EgisCorp** [comment]
혹시 createPoint와 createHTMLObject으로 생성된 오브젝트에 대한 z-index에 대한 문의라면 서로간 z-index를 분류가 불가능합니다.

createPoint은 WEBGL로 그리는 영역으로 createHTMLObject과 전혀 다른 영역입니다.

이부분에 대해서는 캔버스와 WebGL 대한 정의와 HTML Element에 대한 정의를 명확히 구분하셔야 합니다.

**Comment by suhwna** [comment]
답변 감사드립니다. 

두 개의 createHTMLObject 오브젝트에 대한 문의였습니다.

alt 값을 다르게 주는 방식으로 해결하였습니다.
