### ISSUE TITLE
getLonLatHeight() 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#28]
안녕하세요. 바이브컴퍼니입니다.

Module.getMap().getLonLatHeight() 함수가 있습니다.
특정 좌표(lon,lat)의 높이값 구하는 함수로 알고 있는데...

맞나요?

**Comment by SeongRyong-Choi** [comment]
네 Module.getMap().getLonLatHeight(lon, lat); 함수를 사용하면 높이값이 반환됩니다.

**Comment by HyunSeongKil** [comment]
**사용 방법이 이게 맞나요???**

세종시청의 위치인데
리턴값이 -6378137이라고 표시가 됩니다.


![image](https://user-images.githubusercontent.com/38479834/121626965-6ce68180-cab1-11eb-8c8a-c8adafd00c2e.png)

**Comment by SeongRyong-Choi** [comment]
해당 문제를 확인하여 엔진 기능 보완중입니다.

추후 엔진 업데이트 완료되면 다시 답변드리겠습니다.

**Comment by HyunSeongKil** [comment]
네

**Comment by SeongRyong-Choi** [comment]
원인 결과 해당 기능은 메모리 베이스 DEM을 참조하기 때문에 로딩되지 않은 지형에 대해서는 지구반경(-6378137)을 반환합니다.

현재는 고도에 대한 서버요청처리가 되어있지 않습니다.
