### ISSUE TITLE
JSVector3DArray는 배열인가요 리스트 인가요?

### ISSUE THREAD

**Issue by yuuki9** [EgisCorp/XDWorld#280]
엔진 버전
:

문의 내용
: 개발을 하다가 JSVector3DArray 객체를 사용하게 되었습니다. 내부 요소에 접근하는 방법이나 사용법은 리스트인데 
명칭이 배열인 이유가 따로 있을까요?

**Comment by hjaejae** [comment]
해당 객체는 연속적인 메모리로 관리되고 임의 접근이 가능한 배열형식입니다.

**Comment by EgisCorp** [comment]
내용을 추가로 설명 드리겠습니다.

JSVec3Array는 좌표 목록을 관리하는 목적으로 엔진 내부에서 만들어진 클래스 입니다.

단순히 get, push는 일반적으로 많이 쓰는 명칭으로 JavaScript에서 사용되는 array, list와는 다른 클래스로 인지 하시면 됩니다.
