### ISSUE TITLE
엔진 최초 Init하는 부분 질문있습니다.

### ISSUE THREAD

**Issue by HooYoungJyeon** [EgisCorp/XDWorld#281]
엔진 버전
:1.47.0

문의 내용
: 
안녕하세요.

1. 엔진 내 함수 중 XDESetDemUrlLayerName 과 XDESetDemUrlLayerNameEX의 차이점을 알 수 있을까요?

2. 엔진을 최초 Init할때
```
(<any>window)["Module"].XDESetDemUrlLayerName()
(<any>window)["Module"].XDESetSatUrlLayerName ()
(<any>window)["Module"].Start(window.innerWidth, window.innerHeight);
(<any>window)["Module"].SetAPIKey();
(<any>window)["Module"].XDRenderData();
```
해당 흐름에서 XDESetDemUrlLayerName에서 가져오는 내부 값을 변경 또는 제외시킬 수 있는 함수나 방법이 있을까요?
(ex. 기존에 불러온 dem을 다른 dem데이터로 변경)

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

"엔진 내 함수 중 XDESetDemUrlLayerName 과 XDESetDemUrlLayerNameEX의 차이점을 알 수 있을까요?"
대한 답변은 api 옵션 추가 유무 입니다. 기존 "XDESetDemUrlLayerName"으로 XDServer설정이 가능했지만 XDServer 메인 인자 값 변경으로 인해 "XDESetDemUrlLayerNameEX"이 추가되었습니다.

### XDESetDemUrlLayerName(String url, String layerName)
> url : 서버 URL
> layerName : 해당 레이어 명칭
### XDESetDemUrlLayerNameEX(String url, String root, String layerName)
> url : 서버 URL
> root : 서버 명칭
> layerName : 해당 레이어 명칭

"엔진을 최초 Init할때"
대한 답변은 드리기가 힘듭니다 어떤한 부분을 가지고 이야기 하시는지 명확하지 않습니다. API 자체를 안나오게 하시기 원하시는건지 아니면 XDESetDemUrlLayerName API 내부 어떤값을 제외하신다는건지? 좀더 명확한 설명이 필요할 것 같습니다.

**Comment by HooYoungJyeon** [comment]
2번에 대한 질문을 잘못 드린 것 같습니다.

`var Module = {
	TOTAL_MEMORY: 256*1024*1024,
	postRun: [init]
};`

postRun에서 실행한 Init함수 안에서,

XDESetDemUrlLayerName, XDESetDemUrlLayerNameEX 로 불러온 dem데이터를 postRun 이후 수정하거나 삭제할 수 있을까요?

**Comment by YangHeeBong** [comment]
네 가능합니다

``` javascripten
Module.XDESetDemUrlLayerName("서버주소", "레이어명칭")
Module.XDEPlanetRefresh(); // 지도 초기화
```
방식을 사용하시면 됩니다.

**Comment by HooYoungJyeon** [comment]
위에 설명드렸던 postRun 내의 Init에서 

`Module.XDESetDemUrlLayerName("서버주소","레이어명칭")
Module.XDESetSatUrlLayerName("서버주소","레이어명칭")
Module.Start(window.innerWidth, window.innerHeight);
Module.SetAPIKey("api_key");
Module.XDRenderData();`

로 랜더링 한 이후,

알려주신 답변의 'Module.XDEPlanetRefresh(); // 지도 초기화' 를 사용하여 
기존 "레이어명칭"을 다른 "새로운레이어명칭"으로 교체를 할 경우

`Module.XDESetDemUrlLayerName("서버주소","레이어명칭")
Module.XDEPlanetRefresh(); //지도 초기화
Module.XDESetDemUrlLayerName("서버주소","새로운레이어명칭");
`
이렇게 사용하면 될까요?

**Comment by YangHeeBong** [comment]
``` javascript
Module.XDESetDemUrlLayerName("서버주소", "새로운레이어명칭");
Module.XDEPlanetRefresh(); // 지도 초기화
```
하시면 지정된 주소로 dem 요청합니다.

**Comment by HooYoungJyeon** [comment]
감사합니다.
