### ISSUE TITLE
이미지 오버랩 RTT 정비율 늘리기 기능 추가 요청

### ISSUE THREAD

**Issue by yoonee25** [EgisCorp/XDWorld#283]
엔진 버전
: 1.49.2

문의 내용
: 안녕하세요.
![image](https://user-images.githubusercontent.com/48304523/232361746-1742cd80-1c46-4676-a584-055a2d4b772d.png)
이미지 오버랩 RTT 생성 후 파란 점을 클릭해서 크기를 조절할 수 있는데 
shift나 다른 옵션을 두고 정비율로 늘리기 기능이 추가되었으면 좋겠습니다.

**Comment by avamk2** [comment]
안녕하세요

의견주신 정비율 조작에 대해서 기능 리뷰 후에 업데이트 할 수 있도록 하겠습니다.

**Comment by egiskorea-ryong** [comment]
안녕하세요.

해당 기능은 엔진 1.50.0 버전에 업데이트되었습니다.

감사합니다.
