### ISSUE TITLE
고스트 심볼 오브젝트 생성 시 색감 차이

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#284]
엔진 버전
: 1.49.2

오류 발생 API
: getGhostSymbolMap

오류 내용
: 원본 텍스쳐와 엔진에 올라간 모델링의 색감 차이가 조금 있는 듯 합니다..!
확인 한번 부탁드리겠습니다.

참고 URL : http://203.228.54.41:8999/mapTest/us_carbon/

[비교 이미지]
![20230419_134858](https://user-images.githubusercontent.com/88410545/232973226-c34eb6df-f17c-4d46-abb9-d9a2af4f2ac7.png)

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

"tree_006.3ds", "tree_006.png" 가시화 시 파란색으로 나온다는 부분 내부적으로 확인 후 답변 하겠습니다.

**Comment by giyoon99** [comment]
답변 감사드립니다!

조명 색상 변경 API가 필요할 것 같습니다...

지원해 주시면 감사드리겠습니다!

**Comment by YangHeeBong** [comment]
네 다음 엔진 배포에 관련 기능 개발 지원하겠습니다.

**Comment by giyoon99** [comment]
감사합니다!

**Comment by YangHeeBong** [comment]
관련 기능은 엔진 1.50.0 release 에서 처리 완료 했습니다.

상세 내용은 릴리즈 노트 1.50.0 업데이트 (2023년 4월 28일)  8번 항목을 참고 하시면 됩니다.

최종 결과
![image](https://user-images.githubusercontent.com/82924515/235547903-fa72c1fb-2f2d-48fe-a19c-1bb3e1a3bfc0.png)
// 라이트 (0,0,0)
![image](https://user-images.githubusercontent.com/82924515/235548654-88b79d66-fcae-4274-a58b-e53cb804c657.png)
// 라이트 (128,128,128)
![image](https://user-images.githubusercontent.com/82924515/235548677-4cc49ff0-d9dc-495e-9b63-721c6187541a.png)
// 라이트 (255,255,255)

``` javascript
var object = Module.createGhostSymbol("명칭');
// 고스트 심볼 설정
object..lightColor = new Module.JSColor(255, 0, 0, 0);   // 라이트 색상 사용안함으로 어두워짐
object..lightColor = new Module.JSColor(255, 128, 128, 128);   // 라이트 일반 설정으로 원본색상 출력
object..lightColor = new Module.JSColor(255, 128, 128, 128);   // 라이트 강하게 설정으로 밝은 색상 출력
```

**Comment by giyoon99** [comment]
확인이 늦어서 죄송합니다!
적용 잘 됩니다 ㅎㅎ 감사합니다!!
