### ISSUE TITLE
3ds 모델링 텍스쳐 투명처리 관련 문의드립니다.

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#285]
엔진 버전
: 1.49.2

오류 발생 API
: getGhostSymbolMap().setModelTexture

오류 내용
: 수목과 같이 잎 부분 표현을 위한 텍스쳐가 png로 되어있는
3ds 모델링 표출 시 아래와 같이 투명처리가 다소 어색하게 나타나는데, 혹시 개선이 가능 할까요?
![image](https://user-images.githubusercontent.com/88410545/233008333-6593fd37-ee6a-4b52-bae6-3c69a43f8f53.png)

**Comment by YangHeeBong** [comment]
네 안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

현재 관련 문제는 아래 이슈를 참조 하시면됩니다.

https://github.com/EgisCorp/XDWorld/issues/193

위와 관련된 문제를 해결하기 위해서는 Render 시 잎에 대한 폴리곤 객체 위치와 카메라 거리를 연산하여 그리기 순서 조정이 필요합니다.

이를 위해서 필요한 몇가지 필요한 부분이 있습니다.

### 1. 잎과 나무 부분에 대한 분리
### 2. 잎과 잎에 대한 구분

이 2가지 문제는 랜더링 시 처리하기에는 연산량이 많아 어느정도 데이터가 구조화 되어 있어야 연산량을 줄일 수 있습니다.
