### ISSUE TITLE
면적 측정 계산 시 DEM 반영 여부

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#287]
엔진 버전
: 1.49.2

문의 내용
: 안녕하세요. 

현재 엔진에서 사용되는 면적 측정 기능과 관련하여 문의드립니다.

1. 면적 측정 시 DEM을 고려하여 계산되나요?
2. 포인트 좌표를 여러 개 던져서 해당 영역의 DEM이 반영된 면적 값을 불러오는 기능이 있나요?
3. 없다면 기능 추가가 가능한가요?

**Comment by egiskorea-ryong** [comment]
안녕하세요.

1. 면적 측정 시 DEM을 고려하여 계산합니다.

2. 현재 포인트 좌표를 입력하여 면적을 구하는 API는 존재합니다. Module.getMap().GetPointsVolume(); 다만 이미 로딩된 지형의 DEM 데이터를 기반으로 계산하고 있습니다. XDServer에 최대 레벨 DEM으로 계산 할 수 있도록 기능이 있었으나 지형 같은 정형화 데이터를 해석해서 처리하는 부분이 서버 부담이 있어 해당 기능은 지원하지 않고있습니다.

감사합니다.

**Comment by KIMSEONOK** [comment]
넵 감사합니다!
