### ISSUE TITLE
HTML 오브젝트 생성 시 수직 라인 적용 방법

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#288]
엔진 버전
: 1.50.0

문의 내용
:
안녕하세요!

HTML 오브젝트 생성 시 아래 샌드박스 링크처럼 라인을 생성할 수 있을지 문의 드립니다!
http://sandbox.dtwincloud.com/code/main.do?id=object_point_line

**Comment by avamk2** [comment]
안녕하세요

HTML 오브젝트를 생성시에 지정하는 좌표 (경위도와 높이)와 동일한 경위도에 높이만 지하를 두는 좌표 2개를 준비하여

http://sandbox.dtwincloud.com/code/main.do?id=object_line_Json

3D 라인객체를 추가로 생성하면 동일한 형상을 만들 수 있을 겁니다. 
HTML 오브젝트 자체는 3D 영역이 아닌 지도 캔버스의 밖에 그려지는 div 영역이라 지도내에 그려지는 3D 라인보다 받드시 위에 그려지게 됩니다.

**Comment by giyoon99** [comment]
넵 감사합니다!
