### ISSUE TITLE
화면 분할 기능, 폴리곤

### ISSUE THREAD

**Issue by DuHyeon2** [EgisCorp/XDWorld#289]
엔진 버전
: 1.50.0

문의 내용
: 
안녕하세요!

다름이 아니라 

화면 분할 기능 사용 중 

폴리곤은 분할 기능이 적용되지 않는 이슈가 발생되어 문의 남깁니다.

1.50.0 엔진으로 업데이트 전엔 확인되지 않은 이슈입니다.

폴리곤 생성
`const comparePolygonCreate = (_coordinate, layerName, height)`

화면 분할
`setSplitScreen(2);`

이 두 기능 적용 중 발생된 이슈 사항입니다.

감사합니다.

![레이어](https://user-images.githubusercontent.com/83499405/236965728-5e924a88-871a-41d3-83e9-d51bc7854be3.jpg)

**Comment by hjaejae** [comment]
안녕하세요~
문의 주신 내용에 대해서 확인해보았습니다.


샌드 박스의 내용을 보시면 아래 API가  있습니다.
setTwoSlideScreenLayerList(string _leftLayerNames, string _rightLayerNames)
해당 API는 **왼쪽에 보일 레이어**와 **오른쪽에 보일 레이어**를 정하는 API 입니다.
명시 하지 않은 레이어에 대해서는 둘 다 보이게 됩니다.

아래와 같이 왼쪽에만 보일 레이어를 추가해 주시면 기능이 정상 작동 되는것을 확인 하였습니다.
```javascript
GLOBAL.option.setTwoSlideScreenLayerList(
			"facility_build,POLYGON_LAYER",
			""
		);
```
![20230511_091755](https://github.com/EgisCorp/XDWorld/assets/82991868/b88754b9-79c9-4610-8909-f7e4b1fb102f)

샌드박스 주소 : http://sandbox.dtwincloud.com/code/main.do?id=effect_screen_split

**Comment by DuHyeon2** [comment]
안녕하세요! 자세한 설명과 답변 감사합니다!

답변 해 주신 API와 소스 참고하여 적용 해봤습니다

저런 식으로 소스 작성을 하니 폴리곤은 분할되어 표시되는것을 확인 하였습니다.

허나 제가 처음 문의드린 질문에 누락된 부분이 있는거 같아 다시 문의 드립니다.

위 사진처럼 폴리곤 **객체**에 대해서는 분할 적용이 되지 않는것으로 확인됩니다!

위 API 기능으로 인해 생성되는 폴리곤 **객체**에 대해선 분할되는 방법 없는지 다시 문의 드립니다!

아래는 해당 폴리곤 객체 생성 API 입니다
```

	// 폴리곤을 저장할 레이어 생성 / 초기화
	let layerList = new Module.JSLayerList(true);
	var compareLayerName = "polygon_"+layerName;
	let layer = layerList.nameAtLayer(compareLayerName) ? layerList.nameAtLayer(compareLayerName) : layerList.createLayer(compareLayerName, Module.ELT_POLYHEDRON);
	layer.removeAll();
	
	layer.setVisible(true);
...

	const polygon = Module.createPolygon("multiPolygon_" + pnu);
	polygon.setPartCoordinates(vertex, part);
	polygon.setHeight(height);
	
	// 폴리곤 색상 설정
	const polygonStyle = new Module.JSPolygonStyle();
	
	var a = layerInfo[layerName]['opacity'] * 255 / 100;
	var rgb = layerInfo[layerName]['rgb'].replace("rgb(","").replace(")","").split(",");
	var r = parseInt(rgb[0]);
	var g = parseInt(rgb[1]);
	var b = parseInt(rgb[2]);
	
	// JSColor ARGB(255, 255, 255, 255)
	polygonStyle.setFillColor(new Module.JSColor(a, r, g, b));
	polygonStyle.setOutLineWidth(2.0);
	polygonStyle.setOutLineColor(new Module.JSColor(r, g, b));
	polygon.setStyle(polygonStyle);
	
	// 생성한 폴리곤을 레이어에 저장
	layer.addObject(polygon, 0);


```

**Comment by hjaejae** [comment]
소스는 제가 테스트한 것과 다를게 없어보입니다.
```
var compareLayerName = "polygon_"+layerName;
```
여기에서 생성되는 명칭과 아래 **POLYGON_LAYER** 의 명칭이 같아야 합니다.
POLYGON_LAYER 대신 compareLayerName 명칭을 넣으면 될것 같습니다.
```
GLOBAL.option.setTwoSlideScreenLayerList(
			"facility_build,POLYGON_LAYER",
			""
		);
```

**Comment by hjaejae** [comment]
문의 주신 상황에 대해서 확인 되었습니다.
현재 엔진에서 투명 객체에 대해서 다르게 처리하는 부분이 있어서 생기는 현상같습니다.
문제되는 부분을 수정해서 다음 업데이트에 반영 하도록 하겠습니다.

**Comment by YunSumin** [comment]
해당 부분을 개선한 엔진이 5월 26일 배포되었습니다. (1.51.0 버전)
업데이트 내용 참고 부탁 드립니다.
