### ISSUE TITLE
3ds 재질 가시화 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#29]
안녕하세요. 바이브컴퍼니입니다.

sandbox의 샘플을 참고해서 저희가 보유하고 있는 3ds 파일을 가시화해 보았습니다.

### 아니면, 재질 가시화를 위한 코드를 추가해야 하는 건가요?

해당 폴더에 재질관련 jpg 파일들은 존재합니다.

https://user-images.githubusercontent.com/38479834/121469550-a8bd1080-c9f7-11eb-8761-99aaf34c2d79.mp4

[cesium ion에서 확인한 이미지]
![image](https://user-images.githubusercontent.com/38479834/121469830-25e88580-c9f8-11eb-80bf-7e4895353064.png)

**Comment by SeongRyong-Choi** [comment]
보통 3ds파일에 정의된 텍스쳐 파일명과 실제 파일명이 달라서 해당문제가 발생하기도 합니다.

사용하신 파일을 보내주시면 정확하게 문제를 파악할 수 있을것 같습니다.

**Comment by HyunSeongKil** [comment]
파일의 용량이 큽니다.

어느분에게 메일로 전달하면 될까요?

**Comment by SeongRyong-Choi** [comment]
csr2480@egiskorea.com 로 보내주시면 감사하겠습니다.

**Comment by HyunSeongKil** [comment]
이메일 보냈습니다.
