### ISSUE TITLE
경사도 분석 기능 중 progress 문의

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#290]
엔진 버전
: 1.50.0

문의 내용
:
경사도 분석 기능에서 progress 부분 문의드립니다.

![image](https://github.com/EgisCorp/XDWorld/assets/104063285/1c0fb5d2-d888-4d94-afec-e73450b9d9de)

![image](https://github.com/EgisCorp/XDWorld/assets/104063285/f0ad26cb-9385-4cc5-a94f-45d7e30ad81c)

위와 같은 소스를 정의했을 때,
console.log(_arg[0)); 는 잘 실행이 되는데, input 태그의 값을 바꾸거나 스타일을 수정 등의 이벤트는 잘 안되고
완료됐을 때만 u_progress 값이 변경됩니다.

slopoption에서 분석의 시작과 끝에 특정 함수를 실행하려는데 progress 외에 다른 방법이 없나요?

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

2가지 질문에 대한 답은 아래와 같습니다.
1. "console.log(_arg[0)); 는 잘 실행이 되는데, input 태그의 값을 바꾸거나 스타일을 수정 등의 이벤트는 잘 안되고
완료됐을 때만 u_progress 값이 변경"

먼저 Web Browsers 기본 구조에 대해서 먼저 아셔야 할 것 같습니다. 
Web Browsers는 Single Thread를 기반으로 구성되어 있으므로 작업량이 큰 기능 수행 시 화면 갱신을 하지 않습니다.
이를 해결하기 위해서는 새로운 Thread를 생성하여 처리하는 방법을 통해 Progress를 표현하는 Element를 갱신할 수 있습니다.

2. "slopoption에서 분석의 시작과 끝에 특정 함수를 실행하려는데 progress 외에 다른 방법이 없나요?"

분석 시작과 끝은 "analysisTerrainSlope" 기준으로 잡으시면 됩니다. 
"analysisTerrainSlope"가 실행 전 상태가 분석 시작으로 "analysisTerrainSlope" 실행 후 상태가 분석 끝으로 처리하시면 됩니다.
