### ISSUE TITLE
시작과 끝점 사이 경로 계산하는 함수 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#291]
엔진 버전
: 1.50.0

오류 발생 API
: Module.getMap().GetPathIntervalPositions

오류 내용
:
안녕하세요!

경도, 위도, 높이 좌표가 저장되어 있는 배열을 사용하여
좌표 사이의 경도, 위도, 높이를 추출 후 이동 경로 수집이 필요한 상황입니다

GetPathIntervalPositions 함수를 사용해 꼭짓점 사이 경도, 위도 값들을 구하는건 가능 하지만
높이 값이 계산이 안되어 추출 되고 있습니다

3D 경로가 필요한 상황이라 높이값도 계산이 되어야 하는데 혹시 가능 할까요...??
아래는 참고 이미지 입니다!

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/edbe631f-6f5d-4e4d-b09e-527efba91c14)
[꼭짓점 배열, 경로 생성 함수 호출]

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/1832adfa-4fda-4f65-ad58-0561298590e8)
[이동 경로 생성 함수]

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/04966015-85e4-499f-8fcc-8860259dd270)
[경로 생성 후 높이값]

**Comment by hjaejae** [comment]
안녕하세요~
문의주신 내용에 답변 드리겠습니다.

GetPathIntervalPositions 함수에서  3번째 파라메터는 지형 결합 여부입니다.
사용하신 소스를 보니 false로 주셨는데 true로 주시면 지형 결합된 좌표를 구하실수 있습니다.

단, 지형은 LOD 처리로 인해 다양한 레벨이 존재하고 그 높이값은 다 다르게 됩니다.
GetPathIntervalPositions 사용하신 시점에서의 지형 레벨 기준으로 지형 높이값을 구하게 됩니다.

**Comment by giyoon99** [comment]
확인이 늦어서 죄송합니다 ㅜㅜ

해당 false 부분을 true로 변경해서 적용해 보니 -값은 안나오지만

여전히 계산은 잘 안되고 있는 것 같습니다...

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/3c8c34f0-3fe8-4959-9144-b5eee53cf9c3)

위 사진과 같이 모든 높이 값이 11로 나오고 있는 상황입니다 ㅜㅜ

**Comment by hjaejae** [comment]
위 좌표의 값을 넣은 후 테스트해본 결과 정상 적인 값이 출력되는걸 확인하였습니다.

이전에 설명해드린봐와 같이 지형은 LOD 처리로 인해 다양한 레벨이 존재하고 그 높이값은 다 다르게 됩니다

현재 메모리상에 존재하는 지형의 높이 값에 따라 값이 다 다르게 나올수도 있습니다.
- 테스트 1
![캡쳐1](https://github.com/EgisCorp/XDWorld/assets/82991868/ac93018a-2a23-4c42-b1c2-cebbf9b636f4)
결과 값
128.03542691202247 35.161785286222816 29.85433578491211
128.03542769615132 35.16177632601006 29.47763442993164
128.03542848027996 35.16176736579729 29.47763442993164
128.03542926440846 35.16175840558452 29.47763442993164

- 테스트 2
![캡쳐2](https://github.com/EgisCorp/XDWorld/assets/82991868/a7f16a2a-f5d2-43be-9e16-718617c35334)
결과 값
128.03542691202247 35.161785286222816 26.31027603149414
128.03542769615132 35.16177632601006 26.31027603149414
128.03542848027996 35.16176736579729 26.31027603149414
128.03542926440846 35.16175840558452 26.31027603149414

-테스트 3
![캡쳐3](https://github.com/EgisCorp/XDWorld/assets/82991868/01504fa6-692b-4325-9683-122130dcbc1b)
결과 값
128.03542691202247 35.161785286222816 23.120128631591797
128.03542769615132 35.16177632601006 23.120128631591797
128.03542848027996 35.16176736579729 23.120128631591797
128.03542926440846 35.16175840558452 23.120128631591797

위의 결과 처럼 보이는 지형 레벨에 따라서 결과 값이 달라지게 됩니다.
테스트상황을 위 화면 처럼 보이는 상태 스크린 샷과
소스를 스크린샷이 아닌 문자로 적어주시면 그대로 한번 테스트 해보겠습니다.

**Comment by hjaejae** [comment]
엔진(1.51.2) 업데이트 했습니다.
확인 부탁드립니다.

**Comment by giyoon99** [comment]
너무 잘 작동 합니다! 감사합니다!!
