### ISSUE TITLE
절성토 분석 기능의 결과값 문의 

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#292]
엔진 버전
: 1.50.0

오류 발생 API
: 절성토 분석 기능

오류 내용
: 
지도에서 분석 영역을 지정한 후, 분석을 진행하면 절토의 값은 잘 나오는데
성토의 값이 0.000으로 나옵니다.

절토 : getSubVolume(editResultIndex).toFixed(3);
성토 : getAddVolume(editResultIndex).toFixed(3);

어느 영역을 지정해도 값이 0이 리턴이 되는데 기능 오류인가요?

아니면 실제로도 성토의 값이 잘 없는건가요??

![image](https://github.com/EgisCorp/XDWorld/assets/104063285/9b82a9ab-65c8-4888-b0e3-45a36ee73e2c)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

먼저 성토와 절토의 개념 확립이 필요한 내용인 것 같습니다.

상세 내용을 관련 내용을 검색하시면 나오는 내용으로 간단하게 설명하면

땅을 평평하게 만들기 위해서 파내는 것을 "절토"이며 반대로 땅을 메우는 것을 "성토"라고 합니다.

올리신 이미지를 보면 절토가 진행되어 성토가 없음을 알 수 있습니다.

**Comment by Kor-eunae** [comment]
앗 넵. 높이값을 주니까 성토값이 나오네요! 감사합니다!
