### ISSUE TITLE
시계열 폴리곤 예제의 폴리곤을 테두리 좌표값으로 만들기

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#293]
엔진 버전
: 1.50.1

문의 내용
: 안녕하세요.

http://sandbox.dtwincloud.com/code/main.do?id=effect_time_visualization
위 링크에서 확인할 수 있는 폴리곤을 만들고 싶은데, 
해당 예제에서 사용되는 grid 형태의 데이터가 아닌
아래 그림과 같이 테두리 경위도 좌표값을 던져 폴리곤을 만들 수 있는 기능이 있나요?
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/d43734b5-8b34-4a8d-a4fb-231de1ba582b)

**Comment by hjaejae** [comment]
안녕하세요~ 
문의 주신 내용의 예제는 **그리드 분석** 관련 예제입니다.

테두리 경위도 좌표값으로 폴리곤을 그리는 API는 아래와 같습니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_polygon_create

폴리곤 데이터를 이용해서 시계열을 표현하고싶으신지요?
어떠한 데이터로 어떻게 표현을 하고싶으신지 정확히 이해하기가 힘듦니다.

**Comment by kseonok** [comment]
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/ba55dfc0-b4a9-49b1-87ec-489c1b1fd6ce)

예로 들어 아래와 같이 테두리 좌표 배열과 높이값을 넘기면 시계열 예제에서 볼 수 있는 폴리곤처럼
해당 영역을 텐트를 친듯한 형태의 3D 오브젝트가 생성되었으면 좋겠습니다.
```
[
	new Module.JSVector3D(128.6749865838419, 35.21747871165077, 15.0),
        new Module.JSVector3D(128.6766521087808, 35.217156208884654, 15.0),
	new Module.JSVector3D(128.6766521087808, 35.216556208884654, 15.0),
	new Module.JSVector3D(128.67549083083478, 35.215182532505146, 15.0),
	new Module.JSVector3D(128.6737961604245, 35.21600773598272, 15.0)
]
```
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/b812b630-0b05-4334-aa18-d31872a64aa3)

이해를 돕기 위해 그림을 그려보았습니다.... 그래도 이해하는데 어려운 부분이 있으시면 말씀 부탁드립니다ㅠㅠ

**Comment by hjaejae** [comment]
정해진 영역을 텐트 모양.. 삼각뿔 형태로 연속적으로 그리고 싶다는 말씀이신지요?
현재 폴리곤 형태로는 가능합니다.
삼각뿔형태로 그리기 위해서는 추가 API가 필요할것 같습니다.

**Comment by kseonok** [comment]
정확히는..
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/93cfba94-6fde-447e-ac5b-9781286bcf2b)


위 사진같은 삼각뿔 형태보다는 아래 사진과 같이 지붕 중간에 라인이 있는 텐트형태입니다..! 가능할까요..?

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/082161ba-dc41-4d82-95d1-3c61ea8ff81c)

**Comment by hjaejae** [comment]
네~ 이해했습니다~
내부 논의 후 API 추가 계획을 잡겠습니다.

**Comment by hjaejae** [comment]
[샌드박스(오브젝트 -폴리곤 글라데이션)](http://http://sandbox.dtwincloud.com/code/main.do?id=object_colorpolygon_color_gradation)
위 샌드박스를 참고하고 Index 값을 조절 하면 가능 할 것 같습니다.
더 궁금한 점 있으시면 답글 남겨 주세요
