### ISSUE TITLE
폴리곤 그라데이션 수평 적용

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#294]
엔진 버전
: 1.50.1

문의 내용
: 안녕하세요.

http://sandbox.dtwincloud.com/code/main.do?id=object_colorpolygon_gradation
위 샌드박스 예제에 있는 폴리곤에서 그라데이션을 수직이 아닌 수평 방향으로 줄 수 있는 방법이 있나요?

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/dc58fafd-ee85-426a-88ea-6a618a5fd265)

**Comment by hjaejae** [comment]
안녕하세요~
현재 API상으로는 수평방향으로 글라데이션을 줄 수는 없습니다.
논의 후 필요하다고 판단될 경우 기능을 추가하도록 하겠습니다.

**Comment by kseonok** [comment]
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/e5c05846-ff9c-4c7b-9eec-954c7a799c15)


위 사진처럼 라인별로 자동차 속도가 있고, 속도별로 색상을 표시하고자 합니다.
이 때 각 속도별 폴리곤이 부드럽게 이어지는 효과를 주고 싶습니다!

**Comment by kseonok** [comment]
추가적으로 수직 벽면의 굵기도 설정이 가능한가요?

**Comment by hjaejae** [comment]
벽면의 굵기가 생기면 객체가 면이 아닌 폴리헤드론이 되어야합니다.
굵기가 필요하십니까?

**Comment by YunSumin** [comment]
안녕하세요,

아래 이미지는 문의 주신 내용을 토대로
엔진 내에서 아래와 같이 오브젝트 생성 부분을 테스트 한 결과입니다.
![gradation_line](https://github.com/EgisCorp/XDWorld/assets/82925313/a189671d-e59d-45eb-a087-1c65e6a51537)

위 이미지에는 두 가지 오브젝트가 렌더링 되고 있습니다.
 * 수평 방향 그라데이션 색상 폴리곤
 * 두께가 있는 그라데이션 라인

폴리곤 상단에 라인을 배치함으로써,
카메라를 지면과 수직하게 기울여도 벽면의 경로가 보일 수 있도록 하였습니다.

벽면의 굵기를 적용하게 된다면
평면이 아닌 육면체로 오브젝트를 구현해야 하기에 필요 버텍스 수가 다소 많아지고,
카메라를 줌 아웃 하였을 경우 크기가 줄어드는 현상이 발생하므로

벽면의 경로를 가시화 하고자 하신다면
두께가 있는 라인을 상단에 배치하는 부분을 추천 드립니다.

위 기능은 현재 엔진에는 구현되어 있지 않은 기능이며
내부적으로 논의한 결과 그라데이션 라인 기능이 추가적으로 필요하다 판단하였기에

 * 그라데이션 수평 벽면과 라인 생성 기능을 포함한 새 엔진
 * 위 테스트 이미지를 구현한 샘플 코드

를 내일(6/2, 금요일) 중 업데이트 할 예정입니다.

새 기능 업데이트 후 다시 코멘트 드리겠습니다.

**Comment by kseonok** [comment]
넵 감사합니다!

**Comment by YunSumin** [comment]
해당 기능이 1.51.1(Hotfix) 버전으로 업데이트 되어 안내 드립니다. [(상세 내용)](https://github.com/EgisCorp/XDWorld#1511hotfix-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8-2023%EB%85%84-6%EC%9B%94-2%EC%9D%BC)
관련 샘플은 [샌드박스](https://sandbox.dtwincloud.com/code/main.do?id=object_colorpolygon_color_gradation)에서 확인하실 수 있습니다.

감사합니다.

**Comment by kseonok** [comment]
확인했습니다. 감사합니다!
