### ISSUE TITLE
산 영역으로 카메라 이동시 배경 까맣게 표출되는 문의

### ISSUE THREAD

**Issue by EgisEunae** [EgisCorp/XDWorld#295]
엔진 버전
: XDWorld Version : 1.50.1 (Released 2023-05-12)

오류 발생 API
:

오류 내용
:
특정 영역으로 카메라를 이동했을 때, 배경화면(하늘)이 까맣게 되는 문제가 발생합니다.

예를 들어
![image](https://github.com/EgisCorp/XDWorld/assets/134260650/5cbe97a8-9671-498d-a6b3-659ea041542f)

조망점 1로 카메라를 이동했을 때

![image](https://github.com/EgisCorp/XDWorld/assets/134260650/50c215f2-5902-4c03-9b80-2822a3715469)
이런 식으로 배경이 까맣게 보입니다.

Camera.setPermitUnderGround(false); 로 기본 카메라 설정을 dem 아래로 가지 않도록 설정하고 있습니다.

산에 가까이 카메라를 이동했을 때도 배경이 까맣게 되지않으려면 어떻게 해야하나요?

**Comment by egiskorea-ryong** [comment]
안녕하세요.

말씀하신 오류에 대해 확인하였습니다.

다음 엔진 정기 업데이트에 수정되어 배포될 예정입니다.

감사합니다.

**Comment by egiskorea-ryong** [comment]
안녕하세요.

오류 수정되어 엔진 1.151.2(Hotfix)버전에 업데이트되었습니다.

감사합니다.
