### ISSUE TITLE
카메라를 빠르게 이동 시켰을 때, 화면 오류 문의

### ISSUE THREAD

**Issue by EgisEunae** [EgisCorp/XDWorld#296]
엔진 버전
:  1.50.1 (Released 2023-05-12)

오류 발생 API
: camera

오류 내용
: 
지도상에 여러가지 경로를 지정해두고 그 경로에 따라 카메라를 이동시키고 있습니다.

그런데 카메라 이동시 간헐적으로 지도 화면이 깨져서 나타나는 문제가 발생합니다.

![image](https://github.com/EgisCorp/XDWorld/assets/134260650/6315dff4-37f6-4db5-ab4a-52696e7d908b)

이렇게 화면이 깨져보이는데 살짝 줌인/줌아웃을 하면 아래와 같이 정상적인 화면이 표출됩니다.

![image](https://github.com/EgisCorp/XDWorld/assets/134260650/d77c013d-2ecf-4271-9391-b0c5c44ee33d)

이런 오류를 발생시키지 않기 위해 카메라 옵션을 지정해야할 것이 있나요?

아니면 엔진 버그인가요?

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

현재 주신 질문에 대한 정보로는 문제점 파악이 불가능합니다.

정확한 결론 도출을 하기 위해서는 적어도 아래와 같은 정보가 필요합니다.

1. 사용 API
2. 사용 API에 입력 정보

**Comment by EgisEunae** [comment]
// 이동경로 설정
let vpRtApList = new Module.JSVec3Array();
vpRtApList.push(new Module.JSVector3D(127.04688504820506, 37.773683388635185, 400.0));
vpRtApList.push(new Module.JSVector3D(127.04609471099393, 37.7917084578853, 400.0));
vpRtApList.push(new Module.JSVector3D(127.04153451631608, 37.778198351270916, 400.0));
vpRtApList.push(new Module.JSVector3D(127.0433459461219, 37.78098062846679, 400.0));

// 자동 이동 좌표 설정
Module.getViewCamera().setAutoMovePosition(vpRtApList);
Module.getViewCamera().setTilt(30);
Module.getViewCamera().setAutoMoveWaitFrame(3);  // 자동 이동 실행 주기 설정

// 카메라 자동 이동 시작
Module.getViewCamera().startAutoMove();

위와 같이 자동이동 경로를 지정하여 카메라 자동 이동을 합니다.

**Comment by YangHeeBong** [comment]
위 현상이 나타나는 조건은 아래와 같았습니다.

1. 카메라 이동 위치와 거리가 먼 곳에서 클릭 이벤트(이동, 회전 등등) 발생
2. 카메라 이동 이벤트 발생

위 조건이 충족된 상태에서 질문과 같은 문제점이 발생됨을 확인하여 원인 분석 후 처리 완료 했습니다.

https://github.com/EgisCorp/XDWorld/assets/82924515/115f2197-7aec-4728-8ed6-28ee31ec6bc6
<원인 발생>

https://github.com/EgisCorp/XDWorld/assets/82924515/295d66dd-8433-483c-9e63-7aebeb683d7f
<원인 해결>

엔진은 이번주 금요일 오후에 업데이트 하겠습니다.

**Comment by EgisEunae** [comment]
네 감사합니다~

**Comment by YangHeeBong** [comment]
엔진(1.51.2) 업데이트 했습니다. 
확인 부탁드립니다.
