### ISSUE TITLE
건물 투명도 조절 

### ISSUE THREAD

**Issue by SungJinA0813** [EgisCorp/XDWorld#297]
엔진 버전
:1.45.0

문의 내용
: 
안녕하세요 

건물 투명도 조절시 투명도를 줄이면 처음에는 건물이 투명해지다가 검은색으로 변했다가 
투명도 0이 되면 건물이 아예 사라지게 됩니다.

확인 부탁드립니다.
감사합니다. 

![image](https://github.com/EgisCorp/XDWorld/assets/134262028/9887d65e-521d-415f-80f3-b828eb1926dd)

**Comment by YunSumin** [comment]
안녕하세요,

해당 현상은 지형 투명도를 1.0 미만으로 설정한 상태에서
건물 투명도를 줄이는 경우 발생하는 현상으로 확인되었습니다.

관련 원인을 확인하여 엔진 수정이 완료되면 안내 드리겠습니다.

감사합니다.

**Comment by YunSumin** [comment]
문의 주신 오류 사항이 수정되어 안내 드립니다.

오늘자(6/30) 업데이트 된 1.52.0 엔진에 해당 부분이 수정되었습니다.
![image](https://github.com/EgisCorp/XDWorld/assets/82925313/f6eab841-bd5d-4641-b319-219461955eef)

해당 오류는 건물이 반투명 처리 시 모든 타일 레이어가 지하 내부에 있다고 가정되어 발생된 이슈로,
이를 구분하기 위해서 레이어가 지상에 존재하는지, 지하에 존재하는지 구분하는 설정 값이 추가되었습니다. [(업데이트 내용)](https://github.com/EgisCorp/XDWorld#1-%EB%A0%88%EC%9D%B4%EC%96%B4%EC%9D%98-%EC%A7%80%EC%83%81%EC%A7%80%ED%95%98-%EB%A0%8C%EB%8D%94%EB%A7%81-%EA%B5%AC%EB%B6%84-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0-%EC%B6%94%EA%B0%80-%EC%9D%B4%EC%8A%88-297)

감사합니다.
