### ISSUE TITLE
HTML POI 드래그 시 지도 포커스 해제하는 방법

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#298]
엔진 버전
: 1.50.0

문의 내용
: 안녕하세요.

현재 HTML POI를 드래그하여 위치를 변경하는 기능을 구현하고 있습니다.
POI 클릭 후 드래그를 완료했을 때 해당 위치에 새로 POI를 그리는것까지는 완료했으나,
HTML POI 클릭 후 드래그 종료 시 지도가 계속 움직이고, 클릭했던 지점으로 카메라가 이동되는 이슈가 있습니다.

HTML POI 드래그로 위치이동을 더 쉽게 구현할 수 있는 방법이나, 위 문제를 해결할 수 있는 방법이 있나요?

https://github.com/EgisCorp/XDWorld/assets/118805328/e9f1c941-e42c-4722-9247-7328e57127be

**Comment by YunSumin** [comment]
안녕하세요,

해당 현상은 HTML POI에 mouseover 이벤트가 발생했을 때 엔진에서 마우스 동작을 비활성화 시킨 후
mouseout 이벤트 발생 시 다시 마우스 동작을 활성화 하는 방법으로 해결하실 수 있습니다.

``` javascript
function initEvent() {

	var movingButton = document.getElementById("moving");
	movingButton.onmousedown = function() {
		GLOBAL.BUTTON_PRESSED = true;	// 버튼 눌림 상태 on
	};

	movingButton.onmouseup = function(){
		GLOBAL.BUTTON_PRESSED = false;	// 버튼 눌림 상태 off
	};

	Module.canvas.onmouseup = function(e){
		
		if (GLOBAL.BUTTON_PRESSED) {

			// 마우스 드래그 위치에 맞추어 이동 버튼 재배치
			var movingButton = document.getElementById("moving");
			movingButton.style.left = (e.clientX-15) + 'px';
			movingButton.style.top = (e.clientY-15) + 'px';
		}
	};

	movingButton.onmouseover = function(e){

		// 오브젝트 이동 버튼 사용할 때 마우스 지도 조작 off
		Module.getControl().activeMouse(false);
	};

	movingButton.onmouseout = function(e){
		
		// 오브젝트 이동 버튼 사용하지 않을 때 마우스 지도 조작 off
		Module.getControl().activeMouse(true);
	};
}
```

위 코드에서는 이동 버튼("moving")의 누름 상태(movingButton.onmousedown, movingButton.onmouseup)를
별도 플래그(GLOBAL.BUTTON_PRESSED)로 관리한 후, 
지도 마우스 up 이벤트 발생 시(Module.canvas.onmouseup) 버튼의 누름 여부를 확인하여
버튼이 이동하도록 구성되어 있습니다.

마우스가 버튼 위에 올려졌을 경우와 벗어나는 경우(movingButton.onmouseover, movingButton.onmouseout) 를 감지하여
마우스 컨트롤을 on/off 설정하는 부분을 포함하면
버튼 이동 중 원치 않게 지도가 함께 이동 되지 않도록 설정할 수 있습니다.

아래는 위 이벤트를 적용한 지도 조작 영상입니다.

https://github.com/EgisCorp/XDWorld/assets/82925313/9ea37571-a438-4700-8636-20694c4b5cee

(해당 영상은 [고스트심볼 오브젝트 이동](https://sandbox.dtwincloud.com/code/main.do?id=object_ghostsymbol_move) 샌드박스 샘플을 기반으로 생성하였습니다.)

안내 드린 이벤트 설정 코드 참고 부탁드립니다.
 
감사합니다.

**Comment by kseonok** [comment]
activeMouse를 사용하여 해결했습니다. 감사합니다!
