### ISSUE TITLE
그리드 크기 조절 문의

### ISSUE THREAD

**Issue by mykim1024** [EgisCorp/XDWorld#299]
엔진 버전
: v_1.50.1

문의 내용
:
안녕하세요.
grid3D 크기 조절에 관해서 문의 드립니다.
셀의 수 가로세로가 각각 10일 때와 20일 때 그리드의 크기를 동일하게 하고싶습니다. 셀의 수와 상관없이 그리드 전체크기를 조절할 수있는 방안이 있을까요?  아니면 셀 하나의 크기를 조절 할 수 있는 방법이 있을까요?

**Comment by YunSumin** [comment]
안녕하세요,

기존 API는 전체 영역을 기준으로 지정한 셀 개수를 고려하여 개별 셀 크기를 계산하고 있습니다.
문의 주신 방식은 기본 셀을 기반으로 전체 영역을 계산하는 방식으로 확인됩니다. 맞으신가요?

**Comment by mykim1024** [comment]
넵 맞습니다

**Comment by YunSumin** [comment]
현재 grid3D 오브젝트는 전체 영역을 기반으로 세부 셀의 크기를 결정하도록 구성되어 있습니다.

위와 같은 방식을 적용하는 경우 그리드 생성 부분을 엔진에서 내부적으로 변경해야 하므로
관련 API 개발 논의 후 다시 답변 드리겠습니다.

**Comment by YunSumin** [comment]
셀 값을 통한 2차원 그리드 생성 관련하여 샌드박스에 샘플이 추가되어 안내 드립니다.
[샌드박스-그리드(2D))](https://sandbox.dtwincloud.com/code/main.do?id=object_grid_cell_size)

해당 샘플은 셀의 가로 세로 크기, 셀의 가로 세로 수를 조합하여 2차원 그리드를 생성하는 샘플입니다.
![image](https://github.com/EgisCorp/XDWorld/assets/82925313/633e356c-55ae-4860-a070-f4c7c114c33e)

샘플 코드 중 SetGridPositionByCellOptions API 활용 부분을 참고 부탁드립니다.
``` javascript
/* 그리드 생성 */
function createGrid(_startPosition, _interval) {

	// 오브젝트를 저장할 레이어 반환
	var layerList = Module.getObjectLayerList();
	var gridLayer = layerList.nameAtLayer("TEST_GRID_COLOR_LAYER");
	if (gridLayer == null) {
		gridLayer = layerList.createObjectLayer({
			name : "TEST_GRID_COLOR_LAYER",
			type : Module.ELT_POLYHEDRON,
			minDistance : 0.0,
			maxDistance : 100000.0
		});
	}

	if (_interval == null) {
		return;
	}

	var cellRowCount = 10;
	var cellColCount = 10;

	// 간격 값을 참조하여 그리드 오브젝트 생성
	var colorGrid = Module.createColorGrid("TEST_GRID_"+_interval+"M");
	colorGrid.SetGridPositionByCellOptions(
		_startPosition,	// 그리드 시작 위치(우상단) 경위도 좌표
		20.0,			// 그리드 고도(m)
		_interval,		// 셀 가로 크기
		_interval,		// 셀 세로 크기
		cellRowCount,	// 셀 가로 개수
		cellColCount	// 셀 세로 개수
	);

	// 셀 색상 랜덤 지정
	var colorList = [
		Module.COLOR_RED,
		Module.COLOR_GREEN,
		Module.COLOR_BLUE,
		Module.COLOR_WHITE,
		Module.COLOR_YELLOW,
	];

	for (var i=0; i <cellRowCount; i++){
		for (var j=0; j <cellColCount; j++){
			colorGrid.SetGridCellColor(j, i, colorList[parseInt(Math.random()*colorList.length)]);
		}
	}

	// 그리드 객체 형성
	colorGrid.Create();

	// 그리드 오브젝트를 레이어에 추가
	gridLayer.addObject(colorGrid, 0);
}
```

아울러 폴리곤 영역 기반의 그리드 생성 샘플도 추가되어 함께 안내드립니다.
[샌드박스-그리드(2D))](https://sandbox.dtwincloud.com/code/main.do?id=object_grid_colorpolygon)

![image](https://github.com/EgisCorp/XDWorld/assets/82925313/232c8944-dd20-4ca4-a2d4-f1b4e7eeab9e)

위 샘플은 JSColorGrid 대신 ColorPolygon을 사용한 코드로,
폴리곤 내부 그리드 형태로 배치된 버텍스 좌표를 기준으로 그리드를 생성하는 샘플입니다.
직사각형 형태가 아닌 폴리곤 영역 내에 그리드 셀이 배치됩니다. 

업데이트 된 샘플 내용 참고 부탁드립니다.

감사합니다.
