### ISSUE TITLE
[급]wms를 이용하여 지도 가시화하는 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#3]
안녕하세요. 바이브컴퍼니입니다.

로컬에 geoserver설치 하였습니다.
로컬에 설치된 geoserver의 wms를 이용하여 지도 가시화하는 방법 문의합니다.

(전에 관련 샘플 코드를 제공해 주셨는데, 저의 부족한 실력으로 성공하지 못했습니다.)

**Comment by YunSumin** [comment]
WMS API는 현재 개편 중에 있어 금주 중 엔진과 함께 샌드박스 샘플이 업데이트 될 예정입니다.
개편 완료 되는대로 다시 연락드리겠습니다.

감사합니다.

**Comment by HyunSeongKil** [comment]
알겠습니다.

**Comment by HyunSeongKil** [comment]
오늘(05-31)중으로 개편된 기능을 확인할 수 있을까요?

**Comment by YunSumin** [comment]
안녕하세요, 이지스 입니다. 업로드가 지연되어 송구드립니다.
금일 WMS API 개선과 관련하여 엔진파일 및 샌드박스 샘플페이지가 업로드 되었습니다.

샘플 페이지는 아래 URL에서 확인해보실 수 있습니다.
http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=layer_wms

엔진 파일은 최신 엔진 파일로 갱신하여 적용 부탁드립니다.
현재 WMS 레이어에 지원하고 있는 좌표는 EPSG:4326, EPSG:5174, EPSG:5180, EPSG:5186 입니다.
만약 다른 geoserver 옵션 설정이 필요하신 경우 추가 문의 부탁드립니다.

감사합니다.

**Comment by HyunSeongKil** [comment]
고맙습니다.
하나 더 문의합니다.

요청하는 파라미터로 스타일 바꾸는 기능도 있나요?
(아래 이미지 참조)

![image](https://user-images.githubusercontent.com/38479834/120154496-eae19780-c22a-11eb-8f31-bc7712c189d2.png)

**Comment by HyunSeongKil** [comment]
하나 더 문의합니다.

sandbox에서 proxy를 이용한 부분 테스트하고 있습니다.
요청하는 url이 쫌 이상하던데....
이게 맞는건가요?

![image](https://user-images.githubusercontent.com/38479834/120187728-29d61400-c250-11eb-9905-7ca631bcbbcc.png)

**Comment by Khaia** [comment]
> 하나 더 문의합니다.
> 
> sandbox에서 proxy를 이용한 부분 테스트하고 있습니다.
> 요청하는 url이 쫌 이상하던데....
> 이게 맞는건가요?
> 
> ![image](https://user-images.githubusercontent.com/38479834/120187728-29d61400-c250-11eb-9905-7ca631bcbbcc.png)

**Comment by YunSumin** [comment]
위 코드에서 사용하는 "./data/proxy.php" 파일은 샌드박스 샘플용으로 쓰고있는 테스트용 프록시 파일입니다.
(파일 전체 경로 : http://www.dtwincloud.com:8080/dt_reference/assets/map/data/proxy.php)

별도 프록시 파일이 있으신 경우 Module.SetProxy(파일경로) 로 설정하셔서 사용하시면 됩니다.

**Comment by HyunSeongKil** [comment]
음.... 제가 궁금했던건...

**1.**
.proxy.php  와 http:// 문자열이 서로 붙어있는게 이상해서 문의한 거였습니다.

...proxy.phphttp://...

아래처럼 요청을 해야 되는거 아닌가 해서요.
...proxy.php?url=http://...


**2.**
하.....근데 이게...
geoserver로 요청하는 url, parameter가 다 보이는데...proxy를 사용하는 의미가 있나 하는 생각이 드네요.

...쩝

**Comment by Khaia** [comment]
Proxy 는 방화벽등으로 외부 인터넷이 막혔을때 특정 포트를 통해서 엔진으로 데이터 전달이 필요할때 사용됩니다.
말씀하신것처럼 URL 파라미터 쿼리 구조가 잘못들어간걸로 보입니다. 엔진 업데이트시 반영예정입니다.
