### ISSUE TITLE
OSM 지원 문의

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#30]
안녕하세요! 3차원 공간상에서 OSM이나 카카오 맵을 베이스맵으로 활용하고 싶은데 활용이 가능할까요???

**Comment by SeongRyong-Choi** [comment]
현재 OSM, BingMaps, Google, ArcMaps, Naver, MapBox를 지원하고 있습니다.

OSM 베이스맵을 사용하는 방법은 다음과 같습니다.

Module.SetPlanetImageryType(60);	// 표준
Module.SetPlanetImageryType(62);	// OpenCycleMap Base
Module.SetPlanetImageryType(63);	//Transport Map Base
Module.SetPlanetImageryType(64);	//Thunderforest Landscape base
Module.SetPlanetImageryType(65);	//Thunderforest Outdoor base

Module.SetPlanetImageryType(0);		// 초기화
