### ISSUE TITLE
성절토 분석 결과 범위 문의

### ISSUE THREAD

**Issue by EgisEunae** [EgisCorp/XDWorld#301]
엔진 버전
: XDWorld Version : 1.50.1 (Released 2023-05-12)

문의 내용
:

성절토 분석 기능을 사용 중입니다.

제가 원하는 것은 선택 영역에 선택한 높이를 기준으로 성토와 절토의 영역을 분석하는 것입니다.

샌드박스에 있는 성절토의 예시에서 높이 값은 해발고도 값이 포함되어 있는 값인 것 같아

선택영역의 평균 해발고도의 값을 적용하여 기능을 적용했습니다.

적용 소스는 아래와 같습니다.

let nCount = Module.getMap().getInputPointCount();
// 성절도 영역 색상 설정
        Module.getEditTerrain().setEditFaceColor({
            slope : new Module.JSColor(150, 255, 0, 0),     // 경사면 색상
            bottom : new Module.JSColor(150, 255, 255, 0)   // 바닥면 색상
        });

        let heightOptionValue = parseFloat($("#trtpSetHeigth").slider("option", "value"));
        let slopeOptionValue = parseFloat($("#trtpSetSlope").slider("option", "value"));

        // 성절토의 높이 값은 해발고도 기준으로 계산하기 때문에 성절토 실행 하기 전에 선택영역에 대한 해발고도를 먼저 구한다.
        let h = 0;  // 해발고도
        for (let i = 0; i < nCount; i++) {
            h += Module.getMap().getTerrHeightFast(Module.getMap().getInputPoints().get(i).Longitude, Module.getMap().getInputPoints().get(i).Latitude);
        }
        h = h / nCount; // 포인트 해발고도의 평균값

        let isValidResult = false;
        isValidResult = Module.getEditTerrain().create(Module.getMap().getInputPoints(), h + heightOptionValue, slopeOptionValue);  // 영역선택시 성절토 실행 함수
        // 성토량, 절토량 출력
        if (isValidResult) {
            let editResultIndex = Module.getEditTerrain().getEditCount()-1;
            $("#trtpFillValue").val(numberWithCommas(Module.getEditTerrain().getAddVolume(editResultIndex).toFixed(3)));
            $("#trtpCutValue").val(numberWithCommas(Module.getEditTerrain().getSubVolume(editResultIndex).toFixed(3)));
        }

        Module.XDSetMouseState(Module.MML_MOVE_GRAB);
        Module.getMap().clearInputPoint();

이렇게 소스를 작성하니 원하는 높이에서 성절토가 분석되는 것 같습니다.

그런데 분석 영역이 선택영역을 벗어나는 것 같아 문의 드립니다.

높이 값과 각도 값을 0으로 하고
![image](https://github.com/EgisCorp/XDWorld/assets/134260650/bf851a65-c2df-4402-a147-fd9c993acab3)
선택 영역을 지정하고 분석을 하면
![image](https://github.com/EgisCorp/XDWorld/assets/134260650/e58b5c9d-643d-4249-b6c2-59841d4e5d95)
분석 결과가 선택 영역을 벗어나 더 넓은 영역을 분석합니다.

선택 영역 내에서만 분석을 실행하려면 높이 값을 다르게 적용해야 할까요?

**Comment by avamk2** [comment]
안녕하세요

지형 편집부분에서는 현재 편집할 영역을 편집을 보장하는 **최소 범주로** 인식합니다.
그래서 해당 영역의 범주로 편집된 이후 주변의 편집하지 않은 지형과 편집된 지형과 단차가 발생하기에 이를 보정하기 위해서 경사면(slope)이 만들어집니다.

문의주신사항은 슬로프를 포함한 **최대 범주로** 지형편집을 요청하신 사항인데 문제는 편집 범위에 따라서 편집을 위한 목표 고도까지 필요한 영역이 구성되지 않으면 목표 성절토 높이까지 도달 하지 못할 수 있습니다. 

추가적으로 DEM은 2차원 그리드 데이터이기 때문에 수직경사도로 (같은 위치에 2개의 높이 중첩이 발생하기에) DEM을 구성할 수 없습니다.  이로 인해서 **편집 영역은 반드시 지정된 영역 이상으로 확장**됩니다.

기존 분석과 다른 방식으로 해야된다면 요구에 대한 사항을 확인이 필요할 것 같습니다.
