### ISSUE TITLE
2D 가시권 분석 mouse mode 82번(MML_ANALYS_VIEWSHED)로 변경 시 지도 이동 

### ISSUE THREAD

**Issue by yoonee25** [EgisCorp/XDWorld#302]
엔진 버전
: 1.50.2

개선 내용
: 2D 가시권 분석 시 사용하는 mouse mode 82번(MML_ANALYS_VIEWSHED)로 변경 시 지도 이동이 가능했으면 좋겠습니다
![image](https://github.com/EgisCorp/XDWorld/assets/48304523/3c05ff86-c715-4d51-ad37-5d89d5ae7de4)

**Comment by hjaejae** [comment]
현재 2D 가시권 분석시 작동 방법이
1. 가시권 분석할 위치 지정
2. 마우스 드래그 후 방향 및 거리 설정
으로 되어있습니다.

지도 이동을 하기 위해서 마우스 드래그가 필요한데 가시권 분석시 마우스 드래그가 들어가 중복이 되어 지도 이동을 제외하였습니다. 

마우스 업일 때 
XDGetMouseState() API를 활용하여 82번(2D 가시권 분석)일때 다시 마우스 상태를 바꾸시면 어떨까합니다.
