### ISSUE TITLE
flowPolygon 높이 변경

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#303]
엔진 버전
: 1.49.2

문의 내용
:

아래 방식으로 플로우 폴리곤을 만들었는데 가시화된 폴리곤의 높이를 수정할 방법이 있을까요? obj.setHeight()로 하니까 변경이 안됩니다.

```
const createFlowPolygons = (temp) => {
	
	let vertex = new Module.JSVec3Array();
	let coords = temp.split(',');
	coords.forEach(function(coord) {
	    let xy = coord.trim().split(' ');
	    let alt = Module.getMap().getTerrHeight(parseFloat(xy[0]), parseFloat(xy[1]));
	    vertex.push(new Module.JSVector3D(parseFloat(xy[0]), parseFloat(xy[1]), alt));
	});
		
	// 플로우 폴리곤 생성
	let polygon = Module.createFlowPolygon("RESERVOIR_POLYGON");
	polygon.color = new Module.JSColor(143, 208, 255);
	
	let result = polygon.create({
		vertex: vertex,
		normaltexture: Module.getSymbol().getIcon("WATER_NOISE")
	});
	
	polygon.image_type = 3;
	polygon.flow_speed = 0.1; // 물흐름 속도
	polygon.opacity = 0.8; // 물투명도
	
	let layer = Module.getObjectLayerList().nameAtLayer("RESERVOIR_POLYGON_LAYER") || Module.getObjectLayerList().createLayer("RESERVOIR_POLYGON_LAYER", Module.ELT_POLYHEDRON);
	layer.addObject(polygon, 0);
	layer.setVisible(true);
}
```

**Comment by YunSumin** [comment]
안녕하세요,

첨부해주신 코드 중 JSFlowPolygon의 지점 별 높이를 설정하는 부분은 
``` javascript
vertex.push(new Module.JSVector3D(parseFloat(xy[0]), parseFloat(xy[1]), alt));
```
의 alt 부분입니다.

각 vertex 별 높이 값을 수정해주시면 지점의 높이가 설정됩니다.

사용하셨던 setHeight API는 두 개의 직선으로 정의되는 평면을 기준으로 높이 값을 생성하는 API입니다.
단순 높이를 변경하시는 경우 안내 드린 alt 값을 변경하는 방법을 사용하시면 보다 간편하게 적용하실 수 있습니다.

감사합니다.

**Comment by suhwna** [comment]
답변 감사합니다.

생성할 때의 높이를 변경하는 게 아니라 생성된 객체의 높이를 변경하고 싶습니다.

수위가 높아지고 낮아지는 걸 표출하려고 합니다.

**Comment by YangHeeBong** [comment]
객체의 전체 높이 변경을 실시간으로 하고 싶다는 뜻인가요?

아니면 객체를 구성하는 정점 높이를 실시간 개별 변경하고 싶다는 뜻인가요?

질문이 모호함으로 정확한 요지 파악이 어려움으로 명확하게 설명해 주시면 답변에 도움이 될 것 같습니다.

현재 JSFlowPolygon는 그리기 속도 향상을 위해서 JSGhostSymol과 다르게 고정적으로 그리는 방식을 채택하고 있어 실시간 

수정이 필요할 경우 삭제 후 생성하는 방법이 필요합니다.

**Comment by suhwna** [comment]
답변 감사합니다, 

객체의 전체 높이 변경하려고 합니다.

**Comment by YangHeeBong** [comment]
JSFlowPolygon를 실시간으로 높이 변경하기 위해서는 생성 모듈과 가시화 모듈 변경이 필요합니다.

급한 일정이 아니라면 다음 정규 엔진 업데이트에 처리 하도록 하겠습니다.

**Comment by suhwna** [comment]
감사합니다.

**Comment by YangHeeBong** [comment]
관련 기능 구현 완료했습니다.

결과는 아래 그림과 같습니다.
![303_1](https://github.com/EgisCorp/XDWorld/assets/82924515/da3fcddd-9fc9-4735-803f-52af6182dc94)
<초기 상태>

```javascript
"flowpolygon".setHeight(100);
```

입력 시 다음과 같은 결과를 얻을 수 있습니다.

![303_2(100)](https://github.com/EgisCorp/XDWorld/assets/82924515/911c906b-eaf0-48e1-aab2-6027a571087c)

관련 기능은 6월 말 정규 엔진 업데이트에 추가 됩니다.
