### ISSUE TITLE
지도에서 영역 지정 후 영역 내 포함된 오브젝트 추출 기능 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#304]
엔진 버전
: 1.50.0

문의 내용
:
안녕하세요!

아래 캡처와 같이 지도에서 영역을 지정한 후 그 영역안에 포함된 오브젝트 정보를 가져올 수 있는 기능이 있을까요??

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/b0fa00a7-75f8-4f70-8435-4d3880ee7ec8)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

입력된 영역 안에 포함된 오브젝트 리스트 반환 기능은 없습니다.
