### ISSUE TITLE
마우스 휠 zoom out 제한

### ISSUE THREAD

**Issue by seepieex** [EgisCorp/XDWorld#305]
엔진 버전
:1.5

문의 내용
:
마우스 휠을 사용하여 zoom을 조절하고 있습니다.

마우스 휠을 이용할때(혹은 기본적으로) zoom out을 control을 제한 하는 방법이 있나요??

특정 범위 이상으로 zoom out을 하고 싶지 않은 상황입니다. 

감사합니다.

**Comment by seepieex** [comment]
마우스 휠 뿐만 아니라 전반적으로 control을 일정 altitude 이상으로 높이지 않는 방법을 알고 싶습니다.
일정 altitude 이하에서만 control이 작동 ( 마우스 휠, 키보드, 마우스 버튼 포함)
감사합니다.

**Comment by hjaejae** [comment]
아래 이슈를 참고하시면 해결이 가능 할 듯 합니다.

https://github.com/EgisCorp/XDWorld/issues/162

**Comment by seepieex** [comment]
자세한 답변 감사합니다!
