### ISSUE TITLE
폴리곤 생성 시 폴리곤의 길이를 설정하는 기능 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#307]
엔진 버전
: 1.52.0

문의 내용
:
안녕하세요!

http://sandbox.dtwincloud.com/code/main.do?id=object_polygon_height

위 예시 처럼 폴리곤의 높이를 조절하는 기능은 있는데
길이를 조절하는 기능은 없더라구요...

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/b0c26771-d391-4b52-a677-abb950489133)
이런 좌표들과 같이 수평으로 봤을 때 보이는 부분이 있습니다!
하지만 폴리곤 생성 기능으로 위 이미지처럼 좌표값을 주었을 때 생성은 정상적으로 되는 듯 하지만
지도에 가시화가 안되는걸 보니 아마 길이가 0이라 그런것으로 추정되는데 혹시 해결 방법이 있을까요???

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다

질문의 의도가 정확히 파악이 안되어 추가 정보가 필요 할것같습니다.

1. 높이와 길이의 차이?
일반적으로 폴리해드론은 2차원 객체로 아래 소스를 통해 높이 조절이 가능합니다.

```javascript
polygon.setHeight(80.0);
```
여기에서 말씀하신 길이라는 건 어떤 길이를 말씀하시는건가요?
가로 세로의 길이는 입력된 정점 좌표가 길이 이기 떄문에 이 길이를 이야기 하시는건가요?
만약 경위도에 대한 길이 조절이라고 하신다면 정점 좌표에 대한 길이 변경으로 재성성 하셔야합니다.

2. 수평 시 가시되는 부분?
먼저 이미지로 올리신 입력 좌표는 총 4개이지만 0,3 좌표가 동일 1,2 좌표가 동일합니다.
이런 좌표는 실제 3차원 공간에서 폴리해드론이 아닌 매우 얇은 선으로 표현 됩니다. 
이런 데이터에서 길이가 0이라고 하신 부분은 어떤 길이를 이야기 하시는건지 의미가 모호 합니다.

**Comment by giyoon99** [comment]
설명이 부족해서 죄송합니다...!

setHeight 함수는 폴리곤이 생성되는 고도에서 부터 높이값을 지정해서 땅 -> 하늘 이런 의미이고

캡처해드린 좌표의 경위도는 동일하지만 고도 값에 차이가 있어 특정 방향으로만 봐야 면으로 표시되는 그런 좌표값 입니다


지금 필요한 기능은 예시로 아래 전광판 기능중 90도 각도로 봤을 때 두깨를 조절하는 기능입니다...!
![image](https://github.com/EgisCorp/XDWorld/assets/88410545/baf0e677-3d3e-4cd9-97bc-cd04a1f60dc2)

전광판 처럼 지도상에서 조절하는 기능말고 소스상에서 지정을 해줄 수 있으면 좋겠습니다


설명에 도움이 될진 모르겠으나 캡처본을 더 첨부합니다..



![image](https://github.com/EgisCorp/XDWorld/assets/88410545/724791c6-4c4b-4cfa-84b5-774bdd46c954)
(정면)

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/3d24d0c6-1feb-44de-9561-919439023939)
(위)

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/b4968417-3084-4375-9034-ffa5cab6dfe5)
(옆)

**Comment by YangHeeBong** [comment]
질문을 정확히 이해하였습니다. 

일단 각 객체에 관해서 설명드리겠습니다.

1. 전팡관에서 사용한 객체
 전광판에 사용한 객체는 JSFigure 객체로 데이터 수정이 가능하도록 작성된 오브젝트로 위에서 언급하신 수정이 실시간으로 수정이 가능하지만 폴리곤 객체에 비해 실시간 수정을 위해서 객체를 가시화 프레임 마다 연산 처리하는 모듈이 존재함으로 연산량이 증가합니다.
2. 폴리곤 객체
 JSPolygon은 JSFigure와 반대로 초기 설정에 좌표값을 기준으로 가시화함으로 실시간 수정이 용이 하지 않습니다. 
하지만 JSFigure 보다 연산량이 적어 가시화 속도를 보장받을 수 있습니다.

JSPolygon으로 두께 설정이 가능하도록 지원은 가능하지만, JSPolygon 수정을 하실경우 삭제 및 생성을 지속적으로 반복하셔야 합니다. 
질의에 대한 이미지를 봐서는 고스트 심볼을 통해 크기 회전을 컨트롤하시는게 좋아 보입니다. 

관련 소스 : http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit

**Comment by giyoon99** [comment]
친절한 답변 감사드립니다!

캡처에 보이는 라인 안쪽을 채우는 폴리곤이나 다른 대체할만한 기능이 필요한 상황입니다

라인과 같은 좌표값들을 지정할 예정이고 색상도 변경되어야 하는 상황입니다...

JSPolygon 두께 설정 기능을 필요할 듯 합니다
그리고 혹시 지원 가능하시다면 기간은 어느정도 소요 될지도 질문 드립니다..!

**Comment by YangHeeBong** [comment]
JsPolygon 두께 설정은 다음주 금요일 중으로 완료 가능합니다. 
이를 해결하기 위해서는 크게 2가지 기능이 추가 되어야 합니다. 

1. 바닥 폴리곤 생성.
2. 입력 값 기준으로 상방벡터 추출 후 벡터 방향으로 좌표 출력.

**Comment by giyoon99** [comment]
http://sandbox.dtwincloud.com/code/main.do?id=object_frustum

혹시 이쪽 기능을 활용할 방법은 없을까요...???

**Comment by YangHeeBong** [comment]
frustum을 화살표로 활용하신다는건가요?? 

답글에 올리신 흰색 화살표 모양 오브젝트는 frustum보다는 

http://sandbox.dtwincloud.com/code/main.do?id=object_arrow 이쪽 기능을 활용하는게 도 유리해 보입니다 

상세 내용은 https://egiscorp.gitbook.io/xdworld-webgl-manual/object/jsarrow 에서 확인 가능합니다.

**Comment by giyoon99** [comment]
화살표는 상관없이 지금 그대로 사용하면 되고

그리드형태 라인안쪽을 채우는 폴리곤이 필요한 상황입니다..

frustum 예시 화면을 보니 tilt, fov_y 값을 0으로 설정하니 얇은 두께로 표현이 되더라구요
그 상황에서 꼭짓점 마다 좌표값을 주어 원하는 형태의 얇은 폴리곤으로 표출만 되면 좋을듯 합니다!


![image](https://github.com/EgisCorp/XDWorld/assets/88410545/07c07ab1-e230-44fe-9941-0b68398a1dc3)
(정면)


![image](https://github.com/EgisCorp/XDWorld/assets/88410545/702e0fb5-1304-41b1-a30f-93f6a2d8ab72)
(측면)

**Comment by YangHeeBong** [comment]
엔진 2023년 7월 14일 엔진 업데이트 내역에 추가될 내용

관련 기능을 아래와 같이 처리 하였습니다.

생성
```javascript
function cretae() 
{
    var path = [];
    path.push(new Module.JSVector3D(129.12486405043842, 35.17410008274932, 10));
    path.push(new Module.JSVector3D(129.12486405043842, 35.17410008274932, 60));
    path.push(new Module.JSVector3D(129.12522538156702, 35.17364593649981, 15));
    path.push(new Module.JSVector3D(129.12522538156702, 35.17364593649981, 65));

    let object = createPlane(path, new Module.JSColor(255, 255, 255, 255));
    if (object == null) return;

    let polygonLayer = Module.getObjectLayerList().createObjectLayer({
        name: "TEST_VERTICAL_POLYGON",
        type: Module.ELT_POLYHEDRON,
    });
    polygonLayer.addObject(object, 0);
}

function createPlane(_path, _color) 
{
    let vertices = [];
    let colors = [];
    let indices = [];

    // 형상 및 색상 설정
    for (let item of _path) 
    {
        vertices.push(new Module.JSVector3D(item.Longitude, item.Latitude, item.Altitude));
        colors.push(_color);
    }

    // Index 설정
    for (let i = 0; i <= vertices.length - 4; i += 2) 
    {
        indices.push(...[i, i + 1, i + 3, i, i + 3, i + 2]);
    }

    var polygon = Module.createColorPolygon("GRADATION_POLYGON");
    let parameter = {
        coordinates: {
            coordinate: vertices,
            index: indices,
        },
        color: colors,
        thickness: 0,
    };
    console.log(polygon.createbyJson(parameter));
    return polygon;
}
```

샘플 소스 결과 입니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/0211dd05-edae-4a48-9053-8073dd5ba8f5)

만약 두께를 설정하고 싶다면 "thickness: 0,"를 "thickness: 10"으로 설정한경우 10m 두께를 가진 객체를 생성하게 됩니다. 
결과는 다음과 같습니다. 

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/cdf67d5c-08d1-49a3-935c-837b2f1ee880)

createColorPolygon에 사용되는 태그에 대한 설명은 다음과 같습니다.
 * coordinates
   * coordinate : 폴리곤 형상 정점 좌표 목록
   * index : 폴리고 가시화 인덱스 값 (현재 사각형 기준으로 "indices.push(입력값)" 같은 값 설정 가능)
 * color : 정점에 가시화 될 색상 값
 * thickness : 두께 값(m)단위

coordinates.coordinate 입력 순서는 아래 그림과 같습니다. 

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/4982531c-40e9-4e59-9ba2-003c4e892232)

coordinates.index는 입력 순서는 아래 그림과 같습니다. 

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/1ec1c308-eaf9-4a07-a2a8-0b1af8982063)

index는 WebGL에서 형상을 표현하는 최소 단위인 삼각형 그리기 순서를 설정하고 "indices.push(입력값)"을 확인하면
아래와 같습니다.

1번 삼각형 : indices[0] = 0; indices[1] = 1; indices[2] = 3;
2번 삼각형 : indices[3] = 0; indices[4] = 3; indices[5] = 2;

1개의 이상의 면으로 구성된 ColorPolygon 생성 하는 방법은 아래 샘플코드를 참조 하시면 됩니다. 

```javascript
function cretae() 
{
    var path = [];
    path.push(new Module.JSVector3D(129.12486405043842, 35.17410008274932, 10));
    path.push(new Module.JSVector3D(129.12486405043842, 35.17410008274932, 60));
    path.push(new Module.JSVector3D(129.12522538156702, 35.17364593649981, 15));
    path.push(new Module.JSVector3D(129.12522538156702, 35.17364593649981, 65));
    path.push(new Module.JSVector3D(129.12563286539853, 35.17332821268188, 20));
    path.push(new Module.JSVector3D(129.12563286539853, 35.17332821268188, 70));
    // 생성 소스
   ... 
}
```

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/85cdfc70-78bc-462f-b6e3-21cddb86c0a3)

외각선 표현을 위해서 좌표값 반환 기능을 추가 하였습니다. 

* JSColorPolygon.toLonlatArray()
  * 기능 : geometry 경위도 좌표 목록 반환
  * 반환 : JSVector3D Array Type (coordinates.coordinate 입력 순서로 경위도 좌표 목록 반환)

반환 좌표를 기준으로 라인 생성 시 아래 결과로 좌표 순서 변경이 필요합니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/d3dc2932-c303-4312-88dc-7ab2e9624e0c)

외각선 처리를 위해서 입력 순서를 아래와 같이 변경 후 가시화 하면 다음과 같은 결과를 얻을 수 있습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/33952b3c-da7d-4da8-b511-90b487413382)

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/2d5e5de1-c632-4e5d-aacb-25a1a60898d6)

**Comment by giyoon99** [comment]
기능 정상 작동 확인했습니다!
감사합니다!!
