### ISSUE TITLE
마우스 조작 종료 기능

### ISSUE THREAD

**Issue by yoonee25** [EgisCorp/XDWorld#308]
엔진 버전
:1.52.0

오류 발생 API
:마우스 조작

오류 내용
:지도 이동 시 캔버스를 벗어나거나 특정 영역 위로 올라가면 마우스 조작이 종료되게 할 수 있을까요?
현재 지도 위에서 드래그하다가 div 영역위로 마우스를 옮기거나 오른쪽 마우스로 회전 중 지도 영역을 벗어났다가 다시 지도 영역으로 돌아오면 마우스 모드가 끝나지 않은건지 조작이 어려운 상태가 됩니다.
![image](https://github.com/EgisCorp/XDWorld/assets/48304523/30437bf6-463d-440e-8004-9bd02ebdbba4)

**Comment by YunSumin** [comment]
안녕하세요,

문의 주신 현상을 해결하기 위해 엔진 내 마우스 버튼 제어 변수가 추가 될 예정입니다.
``` javascript
document.getElementById("interfaceDIV").onmouseover = function() {
	Module.getControl().mouseLeftButtonDown = false;
}
```

위와 같은 예시로 마우스가 Div에 over 되었을 경우
마우스 눌림 상태 제어가 가능하도록 JSControl 내 프로퍼티가 추가됩니다.

해당 업데이트는 이번 달 정기 업데이트에 적용 될 예정입니다.
업데이트 후 다시 회신 드리겠습니다.

**Comment by YunSumin** [comment]
해당 기능이 업데이트 되어 안내 드립니다. [바로가기](https://github.com/EgisCorp/XDWorld#1521-hotfix-2023714)
상세 내용 확인 부탁 드립니다.

감사합니다.
