### ISSUE TITLE
침수시물레이션 관련 문의 입니다.

### ISSUE THREAD

**Issue by jdevil0313** [EgisCorp/XDWorld#309]
엔진 버전
:  1.52.0 

문의 내용
: 
![image](https://github.com/EgisCorp/XDWorld/assets/25459278/dc0b86c7-8bc8-4309-bf2e-78339ddc1db5)
![image](https://github.com/EgisCorp/XDWorld/assets/25459278/2d7fc154-5814-4640-af85-8a3310c62514)
![image](https://github.com/EgisCorp/XDWorld/assets/25459278/9d588a1f-b65a-46b0-a7aa-0f8ef7ee8130)

아스키코드 형태로 수위 데이터를 그리드로 지도위에 표출해주는데 혹시 그리드 셀 하나 선택 시 그리드에 0 값 이상인 수위가 있는
색깔 표시 영역의 좌표를 알 수 있을까요?? 두번째 스샷 네모 형태 물판 말고 세번째 스샷 처럼 색이 있는 모양 테두리 형태로 좌표를 받아와서 물판을 가시화 하고 싶습니다.

**Comment by avamk2** [comment]
안녕하세요 

분석결과가 ESRI ASCII GRID 데이터라는 말씀인거로 생각됩니다.

현재 그리드를 3D로 표현하는 부분에 대해서 기능이 제공되고 있지만 그리드 데이터에 대한 처리 및 가공에 대해서는 제공하지 않습니다. 해당 데이터를 구현하는 로직을 보면 웹코드영역에서 ESRI ASCII GRID 데이터를 float 배열데이터로 파싱하는 과정이 포함되어 있습니다. 초기는 이 데이터를 엔진에서 Rasterize (이미지화)하여 표현하였지만 올해는 해당 기능이 Rasterize 처리도 웹코드 영역으로 현재 밖에서 처리하여 동작하도록 변경되었습니다. 

이는 개발자코드 영역에서 데이터를 직접 제어하는 것으로 엔진에서 처리 의존성을 줄이고자 하는 부분이며 이부분을 Web Worker를 사용하면 엔진화면 처리 부담을 줄이고 표현 데이터를 만들수 있기 때문입니다.

문의주신 기능을 요약하면 Raster to Polygon이라는 데이터 가공에 대한 내용이 됩니다. 해당 기능은 각 Cell이 인근 Cell과 연속성을 가지면 Cell Merge(셀병합)을 거쳐서 하나의 폴리곤으로 만드는 과정이 있습니다. Cell 탐색과정이 Raster 전체를 1회로 끝나는게 아니라 수 또는 수십회 이상 반복하여서 병합과정을 거치는 부분이라 굉장히 많은 시간이 걸립니다.
 이과정을 엔진안에 담게되면 굉장히 오랜시간을 화면이 멈춰진 상태로 있어야 되며 원천 데이터에 대한 취급이라 엔진에서 수행하기에도 적합하지 않다고 생각됩니다.

해당 데이터 가공은 일반적으로 GDAL의 Raster to Vector (polygonize)를 사용하여 입력된 데이터를 사전에 폴리곤 데이터로 가공하고 엔진에서는 좌표를 받아서 런타임으로 폴리곤을 만들어서 가시화 하는 방법이 어떤가 합니다.
