### ISSUE TITLE
Line Effect 문의

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#31]
안녕하세요 
![image](https://user-images.githubusercontent.com/3315478/121830848-f8a21d00-cd00-11eb-984e-1ec0343e7cf0.png)
시점점에서 종점으로 이동한다는 것을 인지 할 수 있게 시작에서 종점으로 Interval 하게 라인이 움직이는 이펙트를 만들어 주실 수 있으신가요??
- sample- 
https://stackoverflow.com/questions/54819023/how-to-use-cesium-js-to-make-a-line-with-flowing-texture-like-a-picture
감사합니다

**Comment by SeongRyong-Choi** [comment]
샌드박스 - 효과 - 바람 표현 - 바람경로

http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=effect_wind

해당 기능을 말씀하시는 건가요?

**Comment by loeaf** [comment]
![image](https://user-images.githubusercontent.com/3315478/122043303-24fb8d80-ce16-11eb-9e90-5761798e70ad.png)
라인으은 선명하게 있고 해당 라인을 따라서 영상과 같이 방향이 표현가능한 이펙트가 있으면 좋겠습니다 ㅎㅎ

**Comment by YangHeeBong** [comment]
연구소 내부에서 라인을 생성 후 파티클 입자를 통해 가시화 하는 이야기가 나왔습니다 추후 샌드 박스를 통해 관련 내용을 공지 하겠습니다.

**Comment by YunSumin** [comment]
금주 포물선 경로 라인 샘플이 추가되어 URL 공유 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_line_arc

시작 점, 끝 점, 최대 고도 등을 설정하여 포물선 라인을 그리는 애니메이션 라인 샘플입니다.
참고 부탁 드립니다.
