### ISSUE TITLE
화면 분할 기능 활성화 시 레이어 setVisible 처리

### ISSUE THREAD

**Issue by EgisEunae** [EgisCorp/XDWorld#310]
엔진 버전
: XDWorld Version : 1.51.2 (Released 2023-06-09)

문의 내용
: 
안녕하세요. 화면분할 기능을 사용하려다 문의사항이 생겨 글을 남깁니다. 

화면을 2개로 분할하여 레이어를 비교할 때, 화면분할이 활성화 된 채로 레이어를 setVisible(false) 하니 먹히지 않고
화면 분할 기능을 비활성화해야 레이어 setVisible(false) 가 됩니다.

현재 화면 분할 시 레이어를 껐다 켰다 하려면 레이어를 생성하고 삭제하는 방법을 적용하여 속도 측면에서 딜레이가 발생합니다.

화면 분할 시에도 레이어 setVisible이 적용되게 하는 방법은 없나요??

아래는
샌드박스의 화면분할 예시에 건물 레이어 on off 라디오 박스를 추가해 테스트 해봤을 때 setVisible이 먹히지 않는 소스입니다.

`<!-- HTML  -->`
`<span>건물레이어 on off</span>`
`<input type="radio" name="layeronoff" onclick="layerOnOff(true)" checked> on`
`<input type="radio" name="layeronoff" onclick="layerOnOff(false)"> off`
`<br>`

`<!-- SCRIPT -->`
`function layerOnOff(_tf){`
`	var layerList = new Module.JSLayerList(false);`
`	var layer = layerList.nameAtLayer("facility_build");`
`       layer.setVisible(_tf);`
`}`

**Comment by avamk2** [comment]
안녕하세요

해당기능은 현재 LayerList 및 Layer 클래스에서 직접 제어가 되지 않습니다. 

Layer.setVisible API는 레이어 자체의 가시 설정이긴 한데 화면분할을 사용할때는 분할 화면에서는 총 4가지 상태를 갖습니다. 
**[ 양쪽 모두 사용, 왼쪽 사용, 오른쪽 사용, 사용하지 않음 ]**
그래서 화면 분할시 이러한 플래그 때문에 setVisible에 대한 기준이 모호해 집니다.

내부적으로 이러한 문제에 대한 해결을 검토해 보고 다시 연락 드리겠습니다.

**Comment by avamk2** [comment]
해당기능에서 대해서 검토해본 결과 다음과 같은 정책으로 수행되게 설정되었습니다.

1. 분할기능 (스트레오, 스플릿 모두)을 사용시에 레이어 목록에 명시되지 않은 나머지 레이어는 모두 Visible이 false로 처리됩니다.
2. 분할기능에 명시된 레이어들은 기능 종료시에 모두 Visible이 True로 처리됩니다.
3. 분할기능 이전에 레이어 Visible 정보를 엔진에서는 보존하지 않기에 기능 종료시에 등록된 모든 레이어를 Visible을 재설정해야됩니다.

위 언급대로 기능사용중 layer.setVisible 기능은 동작하지 않습니다.
