### ISSUE TITLE
히트맵 색상 지정 기능

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#311]
엔진 버전
:1.51.2 

문의 내용
: 안녕하세요. 

http://sandbox.dtwincloud.com/code/main.do?id=effect_heatmap
위 샘플 예제를 보며 히트맵 기능을 구현중입니다.

샘플에서는 히트맵 색상과 포인트별로 모양 고정되어있는것 같은데,

1. 수치값의 범례(범위와 그에 따른 색상)를 지정해주는 기능
2. 각 포인트의 값에 따라 원형 사이즈를 설정할 수 있는 기능

위 두가지 기능을 사용할 수 있을까요?

아래 이미지는 범례와 각 포인트별 수치값 예시입니다.
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/9c4383c6-ab92-4cc4-98ba-5de693179b3f)

**Comment by hjaejae** [comment]
현재 HeapMap관련 API는 다음과 같습니다.

1. Module.getMap().setDistance(_fDistance);
   - 영향력 범위를 조절 하는 API
   -  _fDistance 
       : 포인트의 영향력 범위
       : 단위 m 
       : 기본 값. 1000.0m
![기본](https://github.com/EgisCorp/XDWorld/assets/82991868/503e1311-0a7a-4de7-bc65-d92308cb6376)
![거리조절1](https://github.com/EgisCorp/XDWorld/assets/82991868/d818d024-c030-4196-b65d-4e4571b07bd6)
![거리조절2](https://github.com/EgisCorp/XDWorld/assets/82991868/ca8bdb43-7f94-4c4a-a0d9-12b495741548)

2. Module.getMap().setWeight(_fWeight);
   - 모든 점에 대한 가중치
   -  _fWeight
       : 기본 값 1.0
![가중치1](https://github.com/EgisCorp/XDWorld/assets/82991868/94fad557-303c-4ab7-be93-bc6f3ccac684)
![가중치2](https://github.com/EgisCorp/XDWorld/assets/82991868/296181ff-0e37-47d4-a5e4-27b19a6f4062)

3. Module.getMap().setHeatMapOpacity(_fOpacity);
   - 투명도
   - _fOpacity : 0.0~1.0
![투명도](https://github.com/EgisCorp/XDWorld/assets/82991868/51f2bd4b-2908-46f3-86fc-6901c5fda12d)

4.Module.getMap().setHeatMapColor(_colorCollection)
   - 색상 조정
```javascript
        var pMap = Module.getMap();
	var vColorList = new Module.Collection();
	if(_nIndex==0)
	{
		pMap.setDefaultHeatMapColor();   // 기본 색상
	}
	else if(_nIndex==1)
	{
		vColorList.add(new Module.JSColor(   0, 255, 0 ));   // 가장 바깥쪽
		vColorList.add(new Module.JSColor(  67, 178, 73 ));
		vColorList.add(new Module.JSColor(  98, 187, 70));
		vColorList.add(new Module.JSColor( 139, 198, 67 ));
		vColorList.add(new Module.JSColor( 192, 217, 90 ));
		vColorList.add(new Module.JSColor( 241, 227, 112 ));
		vColorList.add(new Module.JSColor( 244, 200, 111 ));
		vColorList.add(new Module.JSColor( 231, 169, 80 ));
		vColorList.add(new Module.JSColor( 222, 141, 54 ));
		vColorList.add(new Module.JSColor( 213, 113, 41 ));  // 가장 안쪽
		
		pMap.setHeatMapColor(vColorList);
	}
```
![색상조절1](https://github.com/EgisCorp/XDWorld/assets/82991868/7a6906c3-85e0-48bf-95a6-c8d678e7f6b2)

5. Module.getMap().clearHeatMap();
   - 히트맵 초기화

히트맵은 정확한 수치를 보는 용도라기보단 어떠한 지점에 대한 패턴을 보는 용도로 사용됩니다.
요청해주신 그림과 비슷하게 사용하기 위해서는 해당 위치에 점을 더 추가하시면 아래와 같이 좀 더 차이를 둘 수 있습니다.
![영향력](https://github.com/EgisCorp/XDWorld/assets/82991868/91b39a39-d5d7-4943-8441-69b7b7b18339)

위 그림은 왼쪽 점에 3개 오른쪽 점에 1개의 HeatMap 지점을 입력하고 Weight 값을 줄인 상태입니다.
전달해주신 스크린샷을 보면 각각의 점에 대한 값이 있는데 56이라는 숫자의 색상을 나타내기 위해서 56번 점을 찍을수 있습니다.
그러나 현재 쉐이더 변수 갯수 제한이 각각의 환경에 따라 다르기 때문에
56은 반올림하여 6번..
42는 반올림하여 4번..
이런씩으로 입력점에 대해서 줄이는 작업 또한 필요합니다.
지금 현재 최대 점 갯수는 크롬 기준으로 2000개 정도입니다.

더 궁금한 점 있으시면 말씀해주세요

**Comment by kseonok** [comment]
넵 감사합니다!
