### ISSUE TITLE
모바일 환경에서의 카메라 각도 제한 기능

### ISSUE THREAD

**Issue by kkang222** [EgisCorp/XDWorld#312]
엔진 버전
:1.52.0

문의 내용
:모바일과 같은 터치스크린 환경에서 카메라 Tilt 제한기능 -> Module.getViewCamera().setLimitTilt(10);
을 어떻게 줄수 있을까요?

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

touch event에서 tilt 제한 모듈은 없습니다. 

하지만 이번주 금요일 hotfix 엔진 버전에 Module.getViewCamera().setLimitTilt("제한각도")으로 touch event에서도 구현되도록 수정 후 업데이트 하겠습니다.

**Comment by YangHeeBong** [comment]
엔진 2023년 7월 14일 엔진 업데이트 내역에 추가될 내용

Module.getViewCamera().setLimitTilt("제한각도")를 이용하여 Touch event에서도 동작하도록 수정하였습니다.
