### ISSUE TITLE
타일링된 모델링 데이터 카메라 거리에 따라 속도 차이 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#313]
엔진 버전
:1.52.0

문의 내용
:
안녕하세요!

현재 모델링 데이터를 타일맵으로 가시화 중 입니다
![image](https://github.com/EgisCorp/XDWorld/assets/88410545/b1b83bae-b825-499b-a1c5-3e91a4c30455)

특징은 하나의 시설물 안에서 여러 객체로 분리되어 있습니다
![image](https://github.com/EgisCorp/XDWorld/assets/88410545/6efcf551-733e-4547-b22d-c499472473e5)

시야가 멀리 있을 경우 텍스쳐 화질이 좋지 않아서 lod_object_detail_ratio 값을 3으로 주어 멀리서도 고화질의 텍스쳐를
표출하도록 설정 해둔 상태입니다

여기서 궁금한 점은 카메라가 멀리 있을 경우엔 속도 저하가 나타나진 않는데
모델링과 가까워질수록 많은 버벅거림이 발생하고 있습니다
어느 정도 시간이 지나면 다시 빠르게 돌아오기도 합니다..

같은 화질의 텍스쳐를 이미 불러와 있는 상태인 것 같은데 왜 가까이 가면 더 느려지는 것 인지와
해결 방법이 있는지 문의 드립니다

감사합니다!

**Comment by YunSumin** [comment]
안녕하세요,

타일맵 데이터의 경우 서버 기반 서비스 구조로 인해
카메라에서 오브젝트가 멀어지는 경우 메모리가 휘발되는 특성이 있습니다.
따라서 텍스쳐가 이미 불러와 진 상태라도, 카메라에서 멀어지는 경우 메모리 상 반드시 존재한다고 보장할 수는 없습니다.

또한 카메라가 오브젝트에 가까이 다가가는 경우 느려지는 현상은
오브젝트의 LOD 텍스쳐 로드와 관련이 있는 것으로 예상됩니다.

한 오브젝트에는 고화질부터 저화질까지 여러 화질의 텍스쳐가 존재하고(LOD)
카메라가 오브젝트에 가까이 다가가는 경우 보다 높은 화질의 텍스쳐를 로드해야 하므로
텍스쳐 로드 과정에서 버벅임이 발생할 수 있습니다.

다만 이상 설명 드린 부분은 일반적인 타일 맵 로드 시 발생하는 특성이며,
해당 케이스에서 다른 오류 점을 찾기에는 제공해주신 정보 만으로는 확인하기가 다소 어렵습니다.

저희가 접근 가능한 타일맵 주소나 영상 등, 좀 더 자세한 정보를 전달해주신다면
더 면밀한 확인이 가능할 것 같습니다.

감사합니다.
