### ISSUE TITLE
HTML POI 지형이나 모델링에 가려질 경우 숨김처리 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#314]
엔진 버전
: 1.52.1

문의 내용
:
안녕하세요!

HTML POI 기능을 활용하여 지도에 가시화 할 경우
지도 지형이나 모델링 등 데이터에 가려지는 위치일 때에도 그대로 표출되는데
혹시 지형이나 모델링에 가려지면 숨겨지도록 처리가 가능할까요??

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/1b7866ee-5670-4f2b-a70e-12e972a089cf)

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/60a75fc7-c1f2-474b-a35e-5a7133bce15e)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

HTMLObject의 경우 랜더링이 엔진에서 이루어지는것이 아닌 웹이서 이루어집니다.

지도canvas 위에 있는 div에 HTMLObject가 랜더링됩니다.

따라서 해당 기능을 위해서는 고스트심볼을 사용하는것을 추천드립니다.
