### ISSUE TITLE
폴리곤 높이조절(setHeight) false 반환 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#315]
엔진 버전
: 1.52.0

문의 내용
:
안녕하세요!
현재 생성 되어있는 폴리곤 높이값을 변경하려고 하는데
setHeight 함수를 사용하면 return 값이 계속 false로 나오고 있습니다.

API 문서엔 실패 조건이 폴리곤 좌표 설정이 안된 경우로 되어 있는데
이미 화면엔 표출 중이라 좌표 설정이 된 상태인듯한데.... 원인을 몰라서 문의 드립니다!

![image](https://github.com/EgisCorp/XDWorld/assets/88410545/521dc0db-cf17-41bf-b0ed-428ebad84388)

**Comment by avamk2** [comment]
안녕하세요 

기능 재현을 위해서 폴리곤 생성 코드 및 샘플좌표 데이터를 올려주시면 어떤문제인지 진단해보겠습니다.
