### ISSUE TITLE
오브젝트의 좌표 정보를 조회하는 API

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#316]
엔진 버전
: 1.51.2 

문의 내용
: 안녕하세요.

A라는 라인 레이어를 만들고, A 레이어를 똑같이 복사하여 색상만 바꾼 또 다른 레이어를 만들고 싶습니다.
A의 좌표 정보가 따로 변수 등에 저장되어 있지 않을 때, 
A 레이어를 복사하거나 좌표 정보를 가져오는 방법이 있을까요?

A 레이어가 생성될 때 좌표 정보를 setProperty에 저장해서 쓰려고 하였으나, 
저장되는 값의 길이 제한 때문에 실패하여 문의드립니다.

**Comment by hjaejae** [comment]
수 백개이상의 좌표를 setProperty로 속성을 저장하고 getProperty로 확인하였을 때 결과 값이 잘 나오는것을 확인하였습니다.

API 특성상 길이 제한은 딱히 없는걸로 보입니다.

어떤 값을 어떻게 저장하셨는지 테스트 코드를 알 수있을까요?

**Comment by hjaejae** [comment]
제가 테스트한 코드와 콘솔의 결과 값은 아래와 같습니다.

```javascript
        var strCoordinate;
	for(var i=0; i<1000; ++i)
	{
		strCoordinate+= (i*3+1).toString();
		strCoordinate+=","
		strCoordinate+= (i*3+2).toString();
		strCoordinate+=","
		strCoordinate+= (i*3+3).toString();
		strCoordinate+=","
	}
	
	polygon.setProperty("Test", strCoordinate);
	var strProperty = polygon.getProperty("Test");
	
	console.log(strProperty);
```
![Test](https://github.com/EgisCorp/XDWorld/assets/82991868/1f456b7d-d3ca-4101-89e3-a06c745cd3f4)

**Comment by kseonok** [comment]
다시 확인 후, 문자열 길이로 인한 문제가 아닌 것을 확인하였습니다.

setProperty를 한 다음, 바로 getProperty를 하면 제대로 값이 조회되는데,
새로운 변수에 오브젝트를 담으면서 property값이 안불러와지는 것 같습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/779bd302-1437-48bb-98e6-6f1b3ec88bd3)

**Comment by hjaejae** [comment]
해당 오류 상황에 대해서 테스트 완료했습니다.

해당 오류에 대한 수정은 이번주 금요일, 엔진 정규 업데이트 날에 업데이트 하겠습니다.

**Comment by kseonok** [comment]
넵 감사합니다.

**Comment by kseonok** [comment]
혹시 setProperty의 value로 문자/숫자형이 아닌 오브젝트가 들어가도록은 못하나요?

**Comment by YunSumin** [comment]
기능 상으로는 가능하지만 권고하지 않습니다.

숫자/문자형의 경우 단순 값 복사로 데이터가 관리되지만
오브젝트의 경우 메모리 참조 방식으로 데이터가 참조되는 경우 기능 문제가 생길 수 있고
대용량 값을 입력하는 경우 데이터가 엔진 내 메모리를 점유할 수 있기 때문입니다.

또한 해당 문제가 발생하는 경우 외부 데이터와 연계된 문제이므로 엔진팀에서 오류 검출이 어려워
오류 발생 시 문제를 해결해드리기가 어렵습니다.

따라서 오브젝트와 관련된 속성은 엔진 외부에서 관리하시되,
오브젝트 Key 값으로 속성 값을 매칭하는 방식으로 구현하시는 것을 권고 드립니다.

해당 기능은 개발 중 편의를 위해 만들어진 기능이지만
위에 설명 드린 이유로 인해 내부적으로 해당 기능을 제거할지 여부도 논의 중 입니다.

가급적 외부 데이터는 엔진 외부에서 관리 부탁 드립니다.

**Comment by kseonok** [comment]
넵, 감사합니다!

**Comment by YunSumin** [comment]
해당 오류 건에 대하여 엔진 수정이 완료되어 안내 드립니다.  [업데이트](https://github.com/EgisCorp/XDWorld#1530-2023728)
감사합니다.

**Comment by kseonok** [comment]
정상적으로 작동하는거 확인했습니다.
감사합니다,
