### ISSUE TITLE
레이어 removeAll, delLayerAtName 함수 실행 시 HTML POI가 사라지는 오류 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#317]
엔진 버전
: 1.52.1

오류 발생 API
: removeAll, delLayerAtName

오류 내용
: 
안녕하세요!

HTML POI 기능을 활용하여 POI를 띄우고 있습니다.
![image](https://github.com/EgisCorp/XDWorld/assets/88410545/30ad34d0-acbb-479c-a6d6-d5cd96cfb354)

POI를 표출 중에 레이어 removeAll 함수나 delLayerAtName 함수를 사용하게되면 HTML POI 객체들이 사라졌다가
지도 화면을 약간 움직이면 다시 나오는 현상입니다.
![image](https://github.com/EgisCorp/XDWorld/assets/88410545/4d4df018-b52d-4c2e-9593-c8c73d879b82)

해당 함수를 사용 하여도 POI 객체들이 유지되는 방법이 있을까요??

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 이야기하신 질의의 내용으로 어떤 상태인지 정확히 판단이 안 됩니다.

1. HTML Object관리 레이어와 , Object 관리 레이어가 존재하고 Object 관리 레이어를 구성하는 Object를 removeAll, delLayerAtName를 사용했을 시 HTML Object가 불가시화 상태가 되고 마우스 이벤트 시 가시화 상태
2. HTML POI 관리 레이어를 구성하는 HTML Object 2개 이상일 때 개별 HTML Object를 removeAll, delLayerAtName 사용시 HTML Object가 불가시화 상태가 되고 마우스 이벤트 시 가시화 상태

이 두 가지 중 어떤 조건인지 아니면 2가지 이외 상태인지 명확히 질의 해주시면 좋겠습니다.

최근 질의 내용을 보면 저희가 기본적인 정보를 안다는 조건으로 질의 하는 경우가 많은 것 같습니다. 

하지만 저희도 어떤 상태인지 알 수 없기 떄문에 현재 상태에 대해서 상세히 알려주신다면 빠른 문제 해결이 가능합니다.

**Comment by giyoon99** [comment]
설명이 미흡하여 죄송합니다..!

HTML POI 레이어와 관련이 없는 다른 레이어에 removeAll, delLayerAtName 함수 실행 시 해당 문제가 발생하고 있습니다.

HTML POI 레이어와 Object 부분은 따로 건들지 않고
예를 들어 댐 모델링 레이어를 삭제 했을 경우에 HTML POI가 사라졌다가 지도 이동 시 다시 나타나고 있습니다.

확인에 도움이 되도록 영상도 같이 첨부 드리겠습니다.


https://github.com/EgisCorp/XDWorld/assets/88410545/b5be8b87-76f5-4cc3-bc36-d66fbcd91ad6

해당 영상을 보시면 댐 구역 별로 이동 시 문제가 발생 하는데
댐 구역을 이동하게 되면 이전 댐 모델 레이어를 삭제하고 있습니다.(delLayerAtName)
setVisible 함수를 사용했을 때는 문제가 발생하지 않았었는데 delLayerAtName 함수를 사용하니 해당 문제가 발생하였습니다.

**Comment by YangHeeBong** [comment]
원인 파악 후 소스 수정 하였습니다 결과는 아래와 같이 변경 되었습니다. 

엔진은 이번주 금요일 중으로 Hotfix 업데이트 하도록 하겠습니다.

https://github.com/EgisCorp/XDWorld/assets/82924515/95674e75-f077-4177-b51a-6ccb356edb28

**Comment by giyoon99** [comment]
감사합니다!

**Comment by YangHeeBong** [comment]
엔진 업데이트 완료 하였습니다

**Comment by giyoon99** [comment]
정상 작동 확인했습니다
감사합니다!
