### ISSUE TITLE
3D 모델링의 와이어 프레임 전환 기능

### ISSUE THREAD

**Issue by dlsdnjs46-newlayer** [EgisCorp/XDWorld#318]
엔진 버전
: XDWorld Version : 1.51.2 (Released 2023-06-09)

문의 내용
: 안녕하십니까.

교량DT 관련 작업을 진행 하면서 서해대교를 BIM 데이터를 기반하여 3D 모델링을 구축하여 교량 내부에 설치된 센서의 위치를 
확인하기 위해 교량 모델링을 와이어 프레임으로 전환 할 수 있는 기능이 필요해져 문의 드립니다.

현재 확인된 바로는 엔진상에는 xdo 확장자만 와이어 프레임으로 가시화 할 수 있다 하여 구축된 3D 모델링(교량)을 웹에서 '와이어 프레임'으로 전환 할 수 있는 기능에 대해서는 기능 추가가 필요하다는 답변을 받았습니다.

위와 같은 이유로 xdo 외 확장자의 경우 3D 모델링을 와이어 프레임으로 전환 할 수 있는 기능에 대해 요청 드립니다.

**Comment by YunSumin** [comment]
안녕하세요,

와이어 프레임 전환이 필요한 데이터에 대해 상세 정보를 전달해주시면
해당 데이터의 기능 구현에 대해 내부적으로 논의해보겠습니다.

**Comment by dlsdnjs46-newlayer** [comment]
안녕하십니까.

요청 드린 부분에 대해 
Module.getOption().setDisplayOptionOfBuilding(3); 
코드를 적용하니 모델링의 타일맵이 와이어 프레임 형태로 가시화 되는 부분 확인하였습니다.

교량과 센서 타일맵이 별도로 적용된 부분을 이용해 필요에 따라 레이어로 분리하여 와이어 프레임 형태로 가시화 하도록 하였습니다. 

문의 글에 답변 감사드립니다.

**Comment by YunSumin** [comment]
현재 사용하시는 레이어의 타입 정보를 부탁 드립니다.

타일맵을 사용하신다고 명시되어 있어 사용하시는 레이어 타입이 16번으로 예상됩니다.
XDO Real3D (타입 9번) 외 다른 타입 레이어를 사용하시는 것이 맞는지요?

**Comment by dlsdnjs46-newlayer** [comment]
교량 모델링과 센서 모델링 모두 9번 레이어 타입을 사용하고 있습니다.

**Comment by YunSumin** [comment]
9번 레이어 타입은 Real3D 타입으로 .xdo 파일을 사용하는 타일 레이어 타입입니다.
xdo 외의 확장자 모델의 와이어 프레임 출력이 필요하다고 하셨으나,
사용하시는 레이어가 9번 타입이라면 .xdo 파일에 적용 가능한 기존 API를 활용하실 수 있을 것 같습니다.
``` javascript
var layer = Module.getTileLayerList().createXDServerLayer({
	url : "https://xdworld.vworld.kr",
	servername : "XDServer3d",
	name : "facility_build",
	type : 9,
	minLevel : 0,
	maxLevel : 15
});
layer.SetRenderReal3dWireFrame(true);
```

와이어 프레임으로 출력하고자 하는 JSLayer의 SetRenderReal3dWireFrame API를 호출하셔서 적용하실 수 있습니다.
아래는 API 적용 화면입니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82925313/a934de97-194d-49ea-bc6c-85747bb80853)

추가로 와이어 프레임 라인의 색상 적용 API도 함께 안내 드립니다.
``` javascript
layer.SetReal3dWireFrameColor(Module.COLOR_WHITE);
```

**Comment by dlsdnjs46-newlayer** [comment]
layer.SetRenderReal3dWireFrame(true); 
코드를 사용해서 교량 모델링과 센서 모델링이 따로 구분 되는 것을 확인하였습니다.
기존 API를 통해 기능 구현이 가능할 것 같습니다.

상세한 정보와 예시를 통해 답변해 주셔서 감사합니다.

**Comment by YunSumin** [comment]
말씀 감사합니다.
적용하신 후 추가로 문의가 있으신 경우 말씀 부탁 드립니다.

감사합니다.
