### ISSUE TITLE
setTextureCapacityLimit API 용도

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#319]
엔진 버전
: 1.53.0

문의 내용
: 안녕하세요.

샌드박스에서 타겟 경로 이동 예제(http://sandbox.dtwincloud.com/code/main.do?id=camera_trace_path_moving)를 보다가,
```
// 텍스쳐 용량 제한 해제
Module.getOption().setTextureCapacityLimit(false);
```
위 소스를 보게 되었는데, 어떨 때 쓰는 것인지, 해당 예제에서는 왜 사용된 것인지 좀 더 자세히 알 수 있을까요?

**Comment by egiskorea-ryong** [comment]
안녕하세요.

엔진 안정화를 위해 최소 PC 사양에 맞춰 메모리가 512MB로 초기 설정되어있습니다. 

[샌드박스예제](http://sandbox.dtwincloud.com/code/main.do?id=camera_trace_path_moving) 에서는

카메라 이동중 고화질 건물 텍스쳐를 받아오면서 512MB를 넘어갈 경우가 있어 메모리제한을 해제했습니다.

감사합니다.

**Comment by kseonok** [comment]
감사합니다!
