### ISSUE TITLE
line.setUnionMode(true) 기능 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#32]
안녕하세요. 바이브컴퍼니입니다.

라인관련 문의입니다.

### line.setUnionMode(true) 라인을 터레인에 붙이는 기능으로 알고 있습니다.
맞나요?

![image](https://user-images.githubusercontent.com/38479834/121832009-f5f4f700-cd03-11eb-93c5-21c4c2a83af3.png)

**Comment by SeongRyong-Choi** [comment]
해당 기능을 샌드박스에서 확인 후 지형결합 API에 문제가 있어 보완하였습니다.

새로운 엔진을 적용하신 후 확인 부탁드리겠습니다.

샌드박스 예제도 수정하였습니다. 

http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=object_line

감사합니다.

**Comment by HyunSeongKil** [comment]
네
해결되었습니다.
