### ISSUE TITLE
simple_real3d 프로퍼티에 대한 문의

### ISSUE THREAD

**Issue by jangseonghyun** [EgisCorp/XDWorld#320]
엔진 버전
: 1.53.0 (Released 2023-07-28)

문의 내용
: 
안녕하세요.
건물 레이어에 simple_real3d 프로퍼티를 사용했을 때와
setSimpleMode() 함수를 사용했을 때의 결과의 차이가 있어 문의드립니다.

먼저 simple_real3d 프로퍼티를 사용했을 때 아래와 같이 건물이 생성되고
![after](https://github.com/EgisCorp/XDWorld/assets/50700729/eed7255e-5867-44eb-bee1-0121650e69b3)

setSimpleMode()함수를 사용했을 때 아래와 같이 건물에 라인이 그려져 생성됩니다.
![image](https://github.com/EgisCorp/XDWorld/assets/50700729/2b4c85ca-28c9-45ea-bc59-999a9184b359)

simple_real3d 프로퍼티를 사용하여 setSimpleMode()함수를 사용할 때의 결과값을 얻을 수 있는 방법이 있을까요?

**Comment by hjaejae** [comment]
레이어에 SetRenderReal3dEdgeLine(bool _bSet) API를 활용하여 라인을 그릴 수 있습니다.
해당 API는 현재 렌더링 되고있는 객체에만 적용됩니다.
