### ISSUE TITLE
PNG 타일맵 레이어 투명도 조절 기능

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#321]
엔진 버전
: 1.53.0

문의 내용
: 안녕하세요.

png 형태의 타일맵 레이어에 투명도를 주능 기능이 있을까요?

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/3bbc2ae0-2571-4ee0-ac51-51fefaa1b6c3)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

화면상으로 봤을때 XDServer를 활용한 ETLT_PNG_IMAGE 타입의 레이어로 생각됩니다.

정확하게 어떤 레이어인지 확인을 위해서 사용하신 API 알려주시면 감사하겠습니다.

**Comment by kseonok** [comment]
Module.getTileLayerList().createXDServerLayer({
      url: [XDServer URL],
      servername: 'XDServer',
      name: [레이어명],
      type: 10,
      minLevel: 0,
      maxLevel: 14
  });

위와 같은 방식으로 레이어를 호출하였습니다.

**Comment by egiskorea-ryong** [comment]
XDServer를 활용한 ETLT_PNG_IMAGE 타입의 레이어로 확인됩니다.

해당 레이어 타입은 하이브리드 이미지이며 투명값 편집 기능은 없습니다.

혹시 투명값 편집 기능이 필요하신거라면 내부 검토 후 다음 엔진 정기 업데이트에 추가하도록하겠습니다.

감사합니다.

**Comment by kseonok** [comment]
투명값 편집 기능이 필요합니다! 검토 부탁드리겠습니다.ㅎㅎ

**Comment by egiskorea-ryong** [comment]
기능 추가 완료되면 안내 드리겠습니다.

감사합니다.
