### ISSUE TITLE
구 생성 

### ISSUE THREAD

**Issue by yoonee25** [EgisCorp/XDWorld#322]
엔진 버전
: 1.53.1

문의 내용
: 현재 평면 원형, 원 기둥은 폴리곤으로 생성할 수 있는데 3D 구체도 3ds 파일이 아닌 
엔진단에서 생성하는 기능이 있었으면 좋겠습니다~!
![image](https://github.com/EgisCorp/XDWorld/assets/48304523/cf22f237-36b6-46e8-8a90-88b63a9da592)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 폴리곤이라고 이야기 하셨는데 JSPolygon을 이용한 방법을 이야기 하시는건지 JSFigure을 통한 생성인지 알려주실 수 있나요?

**Comment by yoonee25** [comment]
원형의 경우 JSPolygon setCircle 로 생성하고있습니다!

**Comment by YangHeeBong** [comment]
네 알겠습니다. 

추후 관련 내용을 정리해서 알려드리겠습니다.

**Comment by YangHeeBong** [comment]
### 추가된 API
#### - JSPolygon.setSphere(Object)
#### 사용방법
```javascript
let parameter = {
        position: new Module.JSVector3D(lon, lat, alt),
        color: new Module.JSColor(255, 0, 255, 0),
        radius: 40,
        segment: 50,
};

var polygon = Module.createPolygon("GRADATION_POLYGON");
polygon.setSphere(parameter);
```
#### object 구성요소
 * position(JSVector3D Type) : 경도, 위도, 고도로 구성된 좌표
 * color(JSColor Type) : 구를 구성하는 색상 정보 (default 255,255,255,255)
 * radius(Number Type) : 구의 반지름 m 단위 (default 10m)
 * segment(Number Type) : 구를 구성하는 정점의 정밀도 (default 30)

#### 결과
![image](https://github.com/EgisCorp/XDWorld/assets/82924515/07d0efd1-f3e7-456f-8627-655961cfa30f)

위 기능은 정규 엔진 업데이트(2023년 08월 25일)에 추가 예정입니다.
