### ISSUE TITLE
setCircle로 ELT_PLANE 생성 시 RTT 오브젝트 생성

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#323]
엔진 버전
: 1.53.1

문의 내용
: 안녕하세요.

한 점의 좌표를 setCircle을 이용하여 ELT_PLANE 형태의 폴리곤을 생성하는 기능을 구현중입니다.
작년에 사용한 엔진 버전(1.37.22)에서는 지형에 맞게 폴리곤이 생성됐는데, 
현재 엔진(1.51.1)에서는 평평하게 폴리곤이 생성됩니다.

아래는 제가 기능 구현 시 사용한 코드와 엔진 버전별 결과 화면입니다.

지형에 맞게 폴리곤을 생성하고 싶은데, 제가 빠뜨린 부분이 있을까요?
         
 ```
// 폴리곤을 추가할 레이어 생성
 const layerList = new Module.JSLayerList(true);
 layerList.createLayer(_layerNm, Module.ELT_PLANE);

 // 오브젝트 생성
 const object = Module.createPolygon(_objKey);

 // 스타일 정보 등록
 let style = new Module.JSPolygonStyle();

 style.setFill(_option.fillYn);
 if(_option.fillYn) {
     style.setFillColor(_option.fillColor);
 }

 style.setOutLine(_option.outlineYn);
 if(_option.outlineYn){
     style.setOutLineWidth(_option.outlineWidth);
     style.setOutLineColor(_option.outlineColor);
 }

 object.setStyle(style);
 object.setCircle(_option.center, _option.radius, _option.segment);

 // 레이어에 라인 오브젝트 추가
 const layer = Module.getObjectLayerList().getLayerList(true).nameAtLayer(_layerNm);
 if(layer != null){
     layer.addObject(object, 0);
 }
```

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/2047bfc8-f705-490c-aa04-59aee9d8c639)
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/217592f5-9c2d-46b5-9520-346b39d870c1)
▲ 1.37.22

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/5f6bf841-334e-4472-94e0-8800cd5d11f7)
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/d2f2d8f0-ea9e-4d87-b53e-0be9f2f7b900)

▲ 1.51.1

**Comment by YunSumin** [comment]
안녕하세요, 

해당 현상이 발생한 1.51.1 버전 엔진으로 아래와 같이 테스트 한 결과 특이 사항이 없어
원인이 발생하는 다른 요인이 있는지 추가로 확인이 필요할 것 같습니다.
![image](https://github.com/EgisCorp/XDWorld/assets/82925313/013f2213-c1c5-4b38-bb8d-3f93513d5cbb)


첨부해주신 코드 중 실행이 되지 않는 코드가 포함되어 있어
아래와 같이 일부 수정하여 테스트를 진행하였습니다.

``` javascript
// const layer = Module.getObjectLayerList().getLayerList(true).nameAtLayer("CIRCLE_LAYER");
const layer = Module.getObjectLayerList().nameAtLayer("CIRCLE_LAYER");
```

위 코드 부분 적용하신 후 동일한 현상이 발생한다면 JSPolygon의 setUnionMode API 적용을 부탁드립니다.
``` javascript
polygon.setUnionMode(true);
```

감사합니다.

**Comment by kseonok** [comment]
layer를 불러오는 부분은 문의글 작성 중 기존 소스에서 덜 수정하였던 것이였습니다 ㅠㅠ
원 폴리곤 생성 전, 해당 레이어명으로 ELT_POLYHEDRON  형태의 레이어를 먼저 생성했던게 문제였습니다.
레이어명을 다르게하여 해결하였습니다.
감사합니다!
