### ISSUE TITLE
오브젝트 선택 및 위치 관련 문의

### ISSUE THREAD

**Issue by dlsdnjs46-newlayer** [EgisCorp/XDWorld#324]
엔진 버전
: XDWorld Version : 1.51.2 (Released 2023-06-09)

오류 발생 API
:  .getCenter();

오류 내용
: 안녕하십니까.

교량 모델링에 부착된 센서 관련 작업 도중 의문점이 생겨 두 가지 문의를 드립니다.

1. 현재 교량 모델링 위에 센서 모델링을 부착하기 위해서 위치 정보 데이터를 받아 해당 위치에 센서 모델링을 부착 하였을 때 
첨부된 이미지처럼 정확한 위치에 부착되지 않고 어긋나게 나와서 지도 상 좌표 값을 확인하기 위해  .getCenter(); 기능을 사용하였습니다.
![clipboardImage_23_0907_175627_608](https://github.com/EgisCorp/XDWorld/assets/134262055/6aaa1d69-26a5-4e23-a98e-1fa308813f9f)

![좌표값](https://github.com/EgisCorp/XDWorld/assets/134262055/a312c3b8-89d3-4eab-8a98-269e45c78ad3)

 확인된 좌표 값으로 센서 위치를 등록하니 지도 상에 올라오는 실제 위치와 다른 위치 값에 센서 모델링이 표출되었습니다.   

![clipboardImage_23_0907_175338_665](https://github.com/EgisCorp/XDWorld/assets/134262055/278391d9-3139-4d76-aa41-e9eb933bcad4)

해당 기능에 대한 결과 값에 대해 문제가 있는 지 확인을 위해 문의 드립니다.

2. 부착된 센서 모델링을 확인하기 위해 교량 모델링 위에서 마우스 우클릭 후 지도를 회전 하였을 때 마우스 포인터가 모델링에 찍히는 것이 아닌 아래 지도에 찍히는 것 같은 현상으로 인해 확인을 위한 지도 회전에 문제가 있는 것으로 확인됩니다. 이 현상에 대해 질문을 드리니 모델링을 클릭하게 되면 모델링에 포인터가 찍혀야 하는데 무언가 문제가 있어 보인다는 답변을 받아 기능에 대해 문의를 드립니다. 이해를 돕기 위해 아래에 영상 첨부 확인해 주시면 감사하겠습니다.

https://github.com/EgisCorp/XDWorld/assets/134262055/699ade9a-a4b6-4ad0-a829-21d122645d50

**Comment by hjaejae** [comment]
1. getCenter() API를 활용하여 나오는 값은 AABB 기준의 박스입니다. AABB 박스는 X,Y,Z 축에 대한 정렬된 점을 내보내기 때문에 아래와 같은 모양의 객체의 경우 그 중심점이 객체를 벗어날수 있습니다.

![20230911_083724](https://github.com/EgisCorp/XDWorld/assets/82991868/86a78842-55bd-4e80-9f7b-646af5b11930)

2. 아래의 API를 활용하여 3DS를 불러왔다면 rebuild 파라메터를 true 주시고 한번 테스트해보시기 바랍니다.
```javascript
var layerList = new Module.JSLayerList(true);
	var layer = layerList.createLayer("POLYGON_3DS_LAYER", Module.ELT_POLYHEDRON);
	
	var polygon = Module.createPolygon("POLYGON_3DS_LOAD");
	polygon.loadFile({
		position : _position,
		url : _url,
		align : "bottom",
        rebuild : true
	});
	
	layer.addObject(polygon, 0);
```

**Comment by dlsdnjs46-newlayer** [comment]
안녕하십니까.
답변 주셔서 감사합니다.
답변에 대해 추가적인 질의가 있습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/134262055/ccbdc12c-d988-4053-8b1c-a82ace86fa67)

![image](https://github.com/EgisCorp/XDWorld/assets/134262055/a577fccc-dfa4-4e7f-97e4-b56cd121803b)

![image](https://github.com/EgisCorp/XDWorld/assets/134262055/414b9ea0-e843-4958-a914-c28227836017)

![image](https://github.com/EgisCorp/XDWorld/assets/134262055/682954a3-4492-46fc-8f72-9be472a4a288)


1. 위 이미지처럼(빨간색 - 모델링 생성 좌표, 초록색 - POI 출력 좌표) 5가지 방법으로 선택된 레이어에 대한 위치 정보를 넣었을 때도 같은 현상이 발생하여 getCenter() API 기능 외  모델링 객체의 정확한 중심점 좌표를  구할 수 있는 기능이 있는지 질문 드립니다.


2. 현재 모델링 레이어를 불러오는 코드로 
xdWorld.XDLayer.createXDServerLayer(_obj.url, _obj.serverNm, _obj.name, _obj.typeNum, _obj.minLv, _obj.maxLv);

this.createXDServerLayer(globals.xdserver.url, globals.xdserver.servername, 'shdg_main_bridge_230906', 9, 0, 14);
Module.setVisibleRange("shdg_main_bridge_230906", 3.0, 100000.0);

위와 같은 형태로 사용 중 입니다.

rebuild 파라미터를 사용해도 되는 것인지 다른 방법을 사용해야 하는지에 대해 질문 드립니다.

**Comment by hjaejae** [comment]
1. 객체의 중심을 구하는 방법이 AABB와 OBB 등 여러가지 방법으로 구할 수 있습니다.
 다리와 같이 한쪽으로 길게 형성되어있는 객체의 경우 첫 번째 그림처럼 중심에서 한참 벗어난 경우가 생깁니다.
ㄱ자 처럼 꺾인 객체이거나 길이가 긴 객체는 그 중심이라는게 모호하게 되어 현재 상황에 맞는 API는 현재 없습니다.
AABB 박스 중심보다 OBB 박스가 좀 더 정확하나 다리 같은 경우는 오차가 발생 할 것으로 예상됩니다.

2. 3DS가 아닌 서버에서 불러오는객체이군요. 저희 쪽에서 접속할 수 있는 주소가 있으면 테스트를 해보겠습니다.

**Comment by dlsdnjs46-newlayer** [comment]
2. 
http://203.228.54.49:8150/map

현재 개발 중인 서버 주소 입니다.
요청하신 주소가 해당 주소가 맞는 것입니까??

**Comment by hjaejae** [comment]
네~ 맞습니다.
문제점 확인 후 답변드리겠습니다.

**Comment by hjaejae** [comment]
우선 첫번째 문제부터 다시 자세히 말씀드리겠습니다.

전달해주신 주소로 테스트하여 나온 중심점의 경우 AABB와 OBB 모두 다리를 벗어나게 됩니다.

- AABB 
![20230913_132516](https://github.com/EgisCorp/XDWorld/assets/82991868/dfea8135-1135-4486-8afc-2abb66163012)

- OBB
![20230913_101829](https://github.com/EgisCorp/XDWorld/assets/82991868/75fd0783-f387-4f30-b9e5-cd4b4345c01f)

다리의 중앙 도로의 라인을 알 수 있으면 쉽게 구할 수 있으나 3차원 모델에서는 저렇게 벗어나게 됩니다.

두 번째 문의 사항 같은 경우도 객체가 너무 길어 생기는 문제로 판단되었습니다.
이 문제는 객체 생성 단계에서 바운더리 박스가 중앙을 벗어나게 되어 객체가 선택이 안되는 문제가 발생합니다.
회사의 빌더팀에게 문의해서 문제를 해결할 수 있도록 조치하겠습니다.

**Comment by dlsdnjs46-newlayer** [comment]
자세한 설명을 통해 답변 주셔서 감사합니다.

**Comment by dlsdnjs46-newlayer** [comment]
안녕하십니까. 
혹시 생성된 고스트심볼이 클릭 이벤트가 적용되지 않는 것도 말씀해주신 두 번째 문제와 연관성이 있는것입니까??

**Comment by hjaejae** [comment]
고스트 심볼을 어떤 API를 사용해서 생성하신지 알려주시면 좀 더 정확하게 판단 할 수 있을 것 같습니다.

**Comment by dlsdnjs46-newlayer** [comment]
![image](https://github.com/EgisCorp/XDWorld/assets/134262055/e5efa3ea-2867-458d-bf30-0964cb104969)

![image](https://github.com/EgisCorp/XDWorld/assets/134262055/6444d8cf-121f-4f2a-a39d-fc4d14d5d1e1)

위 2가지 기능을 통해 생성하였습니다.

**Comment by hjaejae** [comment]
해결되어서 이슈는 닫습니다.
