### ISSUE TITLE
createXDServerLayer 함수를 사용하여 외부 경로의 데이터를 가지고 올 수 있나요?

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#325]
엔진 버전
: 1.53.1

문의 내용
: 포인트 클라우드 자료를 xd서버에 올리지 않고 NAS서버에 올린 후, NAS경로로 바로 파일을 로딩하고 싶습니다.

이전 XDEMapCreateLayer 함수를 사용하여 url을 외부 경로로 해서 로딩이 가능한데
Module.XDEMapCreateLayer(layerNm, 외부경로/layerNm, 0, false, true, true, 19, 0, 17); 

개선된 createXDServerLayer 함수로는 외부 경로의 데이터를 가지고 올 수가 없는 것 같습니다.

createXDServerLayer 함수로 외부 경로 데이터를 가지고 올 때, 필요한 옵션이 따로 있나요?

현재는 
     Module.createXDServerLayer({
          url: _url,
          servername: _servername,
          name: _name,
          type: _type,
          minLevel: _minLevel,
          maxLevel: _maxLevel
      });

위 옵션으로 설정하여 사용 중입니다.

**Comment by avamk2** [comment]
안녕하세요 유저레이어 사용에 관련된 사항이면 아래 옵션들을 예시로 적용됩니다.

```
var layer = Module.getTileLayerList().createXDServerLayer({
		url : "http://192.168.1.103:8088/map/bldg_ng_dam_level_17_230714",
		name : "bldg_ng_dam_level_17_230714",
		userLayer : true,
		type : 9,
		minLevel : 0,
		maxLevel : 17,		
```

userLayer 옵션을 true로 설정하시고 url 설정만 맞춰 주시면 됩니다.

**Comment by Kor-eunae** [comment]
답변 감사합니다!
