### ISSUE TITLE
CAD 파일(dwg)로 폴리곤 그리는 기능 

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#326]
엔진 버전
: 1.53.1

문의 내용
: 안녕하세요.

cad 파일 내에 있는 도형을 3D 엔진 위에 가시화하고 싶습니다.
가시화 가능 여부와
가시화가 가능하다면, 파일 설정 조건이 있는지에 대해 문의드립니다.

**Comment by hjaejae** [comment]
CAD 파일로 사용되어지고 있는 어떠한 확장자를 사용하고 싶으신지요?
현재 엔진에서는 특별한 경우가 아니면 파일 Parser 기능 제한하고 있습니다.
파서 기능을 위해서 엔진의 덩치가 커지고 초기 로딩 속도가 느려지기 때문입니다.

CAD에서 사용되어지고 있는 포맷중 DWG는 공개 포맷이 아니라 따로 라이브러리가 필요하고
DXF 같은 경우 공개 포맷이라 외부에서 읽을 수 있는 파서 라이브러리들이 있습니다.
이런 라이브러리를 활용하여 3D를 그릴 수 있는 정보를 뽑아내어서 엔진에서 활용 할 수 있습니다.

아래 샌드박스는 점 좌표와 색상을 활용하여 그리드를 만드는 예제 입니다.

https://sandbox.dtwincloud.com/code/main.do?id=object_grid_colorpolygon

```javascript

var grid = Module.createColorPolygon("TERRAIN_ALTITUDE_COLOR");
	grid.set({
		vertex : vertexList,
		color : colorList
	});
```

**Comment by kseonok** [comment]
dwg 확장자로 표현하고 싶습니다. 
dwg 파일을 변환한 사례가 있다면, 어떤 라이브러리를 사용했는지 알 수 있을까요?

**Comment by hjaejae** [comment]
DWG는 AutoDesk 독점 포맷으로 포맷을 사용할려면 AutoDesk의 허가가 필요하여 DWG를 포맷으로 바로 사용한적은 없습니다.
DXF는 공개 포맷이라 DWG를 DXF로 변환하여 사용하였습니다.
DXF는 현재 C++, 자바스크립 등 많은 포맷 Reader가 있어 검색해보면 금방 찾으실수 있습니다.

**Comment by hjaejae** [comment]
아래는 공식 DWG SDK 사이트 입니다.

https://www.autodesk.com/developer-network/platform-technologies/realdwg
