### ISSUE TITLE
지정한 영역 내의 가장 높은 Alt값을 반환받는 기능 문의

### ISSUE THREAD

**Issue by HooYoungJyeon** [EgisCorp/XDWorld#327]
엔진 버전
: 1.51.1

문의 내용
: 안녕하세요, 

![image](https://github.com/EgisCorp/XDWorld/assets/98065800/7ddff979-52c9-433b-9bc4-876cca35a1e3)

위의 그림처럼 sandbox에 있는 '면적 측정' 기능처럼 영역을 지정한 후,

![image](https://github.com/EgisCorp/XDWorld/assets/98065800/61e30ff4-2236-4152-bb3f-af534030d4b9)

sandbox에 있는 '높이 측정'의 결과창 처럼

입력된 영역 내의 정보를 종합 및 분석하여 가장 높은 고도값을 반환해주는 기능이 있는지, 

없다면 기능 업데이트를 요청드릴 수 있는지 궁금합니다!

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 면적 측정 영역에 대해 최고점을 반환받기 위해서는 고도 측정 샘플을 참조하여 구성하면 가능합니다.

현재 관련 샘플을 간단히 작성 중으로 추후 샘플 완료 시 답글로 올리겠습니다.

**Comment by YangHeeBong** [comment]
현재 샌드박스를 통해 [샘플 코드](http://sandbox.dtwincloud.com/code/main.do?id=analysis_polygon_alt)를 구현했습니다.

건물 까지 고도 측정이 필요하시다면

```javaScript
function calculationGrid(_map, _position_list, _rect) {

// 코드내용
alt = _map.getTerrHeight(lon, lat); // 지형 고도만 반환

or 

alt = _map.getLonLatHeight(lon, lat); // 지형 건물 고도 반환

// 코드내용

}
```

둘 중 하나의 API를 사용하시면 됩니다. 

지형 건물 고도 반환 시 결과는 아래와 같습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/510cf21c-99d1-4f2a-9940-322b33fc271f)

샌드박스 샘플내 function calculationGrid(_map, _position_list, _rect) 함수 내 alt = _map.getTerrHeight(lon, lat);

**Comment by HooYoungJyeon** [comment]
답변감사합니다! 테스트 후, 추가 질문사항이 있으면 답글로 올리겠습니다!
