### ISSUE TITLE
성절토, 경사도 분석 결과 투명하게 표출되는 문제

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#328]
엔진 버전
:  1.53.3
오류 발생 API
:  경사도 분석, 성절토 분석

오류 내용
:  
안녕하세요.

PNG 타일맵 레이어 투명도 조절 기능이 필요해 최근 엔진으로 업데이트를 했더니 

기존 경사도 분석과 성절토 분석의 결과 표출에 버그가 발생했습니다.

버그 발생 화면으로

![image](https://github.com/EgisCorp/XDWorld/assets/104063285/c2fa44b0-5754-4391-8c76-b875aa46fd58)

위는 성절토 분석의 결과인데

지형상으로는 분석이 되었는데 원래 성토와 절토 부분이 지정한 색으로 표출이 되었었는데 투명하게 나옵니다.

![image](https://github.com/EgisCorp/XDWorld/assets/104063285/b7b9df93-8816-4504-998a-41b5de8770de)

경사도 분석에서도 동일하게 선택한 부분이 희미하게 표시는 되지만 결과가 보이지 않습니다.

이전 버전의 엔진을 적용하니 해당 버그는 발생하지 않기때문에

최신 엔진에서 발생하는 버그인 것 같습니다.

확인 부탁드립니다.

**Comment by YunSumin** [comment]
안녕하세요, 
문의 주신 성절토 적용 시 영역 색상 표출의 오류 사항을 확인하였습니다.
해당 오류의 수정을 마치는 대로 다시 코멘트 드리겠습니다.

**Comment by egiskorea-ryong** [comment]
안녕하세요.

1.54.0 엔진에 해당 기능이 수정되었습니다.

새로운 엔진으로 업데이트 후 사용 부탁드립니다.

감사합니다.
