### ISSUE TITLE
kmz 파일 테스트 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#33]
안녕하세요. 바이브컴퍼니입니다.

**kmz 파일 로드 및 가시화 테스트 하려고 합니다.**

어떻게 코딩하면 되나요?

**Comment by YangHeeBong** [comment]
저희 연구소 내에 정책적인 부분으로 내용 정리가 끝난 후 이에 대해 답변 드리겠습니다.

**Comment by EgisCorp** [comment]
** 해당 이슈는 기술 지원 사항에서 사업 협의 사항으로 변경하여 금주 월요일 업체 간 회의를 통해 협의 진행하였습니다.
