### ISSUE TITLE
모델링 텍스쳐 관련 문의

### ISSUE THREAD

**Issue by eeeeekl** [EgisCorp/XDWorld#330]
엔진 버전
:: XDWorld Version : 1.51.2 (Released 2023-06-09)

문의 내용
: 안녕하세요
현재 교량의 텍스쳐를 선명하게 하기위해 작업중인데요, 
 lod_object_detail_ratio 값을 높여도 아무런 변화가 없어서 문의드립니다.

![layer1](https://github.com/EgisCorp/XDWorld/assets/145413670/4f8faf50-067f-4fc3-b937-134af1766179)
현재 적용한 교량의 레이어를 XDServer 에서 미리보기로 확인한 텍스쳐이고,

![layer2](https://github.com/EgisCorp/XDWorld/assets/145413670/01975648-beda-49f5-bc53-1c129ff24140)
이게 현재 보여지는 텍스쳐입니다.

같은 소스에서 facility_build 건물레이어로 lod_object_detail_ratio값을 테스트했을때에는 동작이 잘 되는것으로 확인했습니다.

현재 교량의 텍스쳐 이미지 크기는 2048x2048px 사이즈로  제작되었다고 하는데, lod_object_detail_ratio 값으로 텍스쳐의 컨트롤이 되지 않는 이유가 무엇이며, 텍스쳐를 선명하게 하기위한 방법의 무엇인지 문의드립니다!

**Comment by avamk2** [comment]
안녕하세요

2가지 부분에 대해서 확인이 필요합니다.

1. facility_build 라는 레이어에 교량 데이터가 몇 레벨에 지정되어 있는지 알수 있을까요?
2. 교량의 모델의 크기가 대략 어느정도 되는가요? ( 교량 길이, 높이 정도의 치수)

위 사항에 대한 정보와 데이터를 직접 보아야 될거 같습니다.

**Comment by eeeeekl** [comment]
1. facility_build 레이어는 브이월드 건물레이어로 15레벨로 되어있습니다.
 교량레이어는 14레벨로 된 레이어로도 테스트해보고, 10레벨로 된 레이어로도 테스트해보았지만 둘 다 텍스쳐의 변함이 없었습니다!
2. 교량 모델의 크기는 길이 약 7km, 높이 약 208m 정도로 확인됩니다!
![image](https://github.com/EgisCorp/XDWorld/assets/145413670/5e3d86d2-a221-4d24-b007-90f9d3cb859f)

**Comment by YunSumin** [comment]
안녕하세요,

해당 현상의 원인으로 예상되는 부분이 있어 관련된 엔진 환경 설정 API를 안내 드립니다.
아래 API는 텍스쳐 Ratio를 조정할 최소 레벨을 설정하는 API입니다.

Module.getMap().setTileObjectRenewLevel( '텍스쳐 갱신 대상 레벨' );

ex) Module.getMap().setTileObjectRenewLevel(10);
   으로 설정 시 10레벨부터 시작하여 {10, 11, 12, ... , 최대 레벨} 까지의 오브젝트는 텍스쳐가 갱신되며,
   그 이상의 건물은 텍스쳐가 갱신 되지 않습니다. 

현재 디폴트 값은 12레벨이며,
10레벨의 교량 레이어의 경우 12레벨보다 낮은 레벨인 관계로 갱신이 되지 않는 현상이 일어난 것은 아닌가 에상 됩니다.
(디폴트 값은 이후 조정될 수 있습니다.)

감사합니다.

**Comment by eeeeekl** [comment]
말씀해주신 API를 적용 후 테스트 해보았을 때에도 텍스쳐가 갱신되지 않았습니다.
또한, 텍스쳐 갱신 대상 레벨을 조정하지않고 디폴트값으로 둔 상태에서 14레벨의 교량 모델링으로 테스트해보았을때에도 텍스쳐가 갱신되지 않았습니다.

**Comment by hjaejae** [comment]
안녕하세요~
확인해보니 이미지 확장자 문제였습니다.
디폴트로 jpg라는 값을 가지고 있으나 사용하시는 이미지는 대문자 "JPG"였습니다.
textureExt  파라메타로 수정 가능합니다.

레이어 최소 레벨이 10이기 때문에 아래
Module.getMap().setTileObjectRenewLevel(10);
와 함께 테스트 해보시면 됩니다.
```javascript
var layerTemp = Module.getTileLayerList().createXDServerLayer({
		url : "주소",
		servername : "서버",
		name : "레이어 명칭",
		type : 9,
		minLevel : 0,
		maxLevel : 10,
		textureExt : "JPG"   // 레이어 확장자 지정 가능
		});
Module.getMap().setTileObjectRenewLevel(10);
```
