### ISSUE TITLE
좌표정보로만 성절토를 구할 수 있나요?

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#331]
엔진 버전
: 1.53.1

문의 내용
:
안녕하세요.

원래 성절토를 분석하기 위해서는 지도를 클릭하여 Module.getInputPoints() 를 활용하여 분석하는 것으로 알고있습니다만

저는 지도를 클릭하지 않고 lon, lat, alt position 값을 사용하여 성절토를 분석하고 싶습니다.

```
let positionArr = [ 
[new Module.JSVector3D(lon, lat, Module.getMap().getTerrHeight(lon, lat)],
[new Module.JSVector3D(lon, lat, Module.getMap().getTerrHeight(lon, lat)],
[new Module.JSVector3D(lon, lat, Module.getMap().getTerrHeight(lon, lat)]
];
```
위와 같이 위치값 arr가 있는 경우, 위치값만으로 성절토를 구할 수 있나요?

답변 부탁드립니다.

**Comment by egiskorea-ryong** [comment]
안녕하세요.

해당 기능은 메뉴얼에서 확인 할 수 있습니다.

[성절토](https://egiscorp.gitbook.io/xdworld-webgl-manual/analysis/jseditterrain)

위 메뉴얼 사이트에서 create(coordinates, height, angle) → boolean 를 참고하시면 됩니다.

```javascript
var vec_array = new Module.JSVec3Array();
vec_array.push(new Module.JSVector3D(129.132486, 35.175608, 30.0));
vec_array.push(new Module.JSVector3D(129.133182, 35.176425, 30.0));
vec_array.push(new Module.JSVector3D(129.131357, 35.177801, 30.0));
vec_array.push(new Module.JSVector3D(129.128919, 35.177851, 30.0));
```
감사합니다.

**Comment by Kor-eunae** [comment]
답변 감사합니다
