### ISSUE TITLE
div 를 통한 HTML POI 기능 오류 문의

### ISSUE THREAD

**Issue by dlsdnjs46-newlayer** [EgisCorp/XDWorld#332]
엔진 버전
: 1.53.1

오류 발생 API
: HTML POI

오류 내용
: 안녕하십니까.

![image](https://github.com/EgisCorp/XDWorld/assets/134262055/184a2562-320d-462c-ab2a-24e17bc79c4b)

현재 케이블 개수 파악에 효율성을 위해 5번째 케이블 마다 POI 로 표시를 하고자 HTML POI 기능을 사용하였습니다.

 
![image](https://github.com/EgisCorp/XDWorld/assets/134262055/d6bd5ef7-9ebc-4231-a425-7fb295b8eaed)
 
적용한 함수 기능 코드와 

![image](https://github.com/EgisCorp/XDWorld/assets/134262055/6e40089f-3e98-4959-827e-1a0850986c45)

테스트 목적으로 1개의 지점에 POI를 지정한 코드 입니다.

위 테스트 코드를 적용할 시 화면이 전환 된 후 화면이 고정되어 마우스로 화면 이동이 불가능한 상태가 됩니다.
카메라 이동 기능을 통해 적용한 좌표로 이동을 했을 때 POI가 출력된 것은 확인을 하였습니다.

[테스트 용 URL과 확인 방법]
URL : http://203.228.54.49:8150/map

확인방법 : 메인화면 좌측 nav '시뮬레이션' 클릭 -> '케이블 파단' 클릭 -> 방향 선택 후 확인 버튼 클릭 -> 현상 확인

**Comment by dlsdnjs46-newlayer** [comment]
> 엔진 버전 : 1.53.1
> 
> 오류 발생 API : HTML POI
> 
> 오류 내용 : 안녕하십니까.
> 
> ![image](https://user-images.githubusercontent.com/134262055/273075406-184a2562-320d-462c-ab2a-24e17bc79c4b.png)
> 
> 현재 케이블 개수 파악에 효율성을 위해 5번째 케이블 마다 POI 로 표시를 하고자 HTML POI 기능을 사용하였습니다.
> 
> ![image](https://user-images.githubusercontent.com/134262055/273075684-d6bd5ef7-9ebc-4231-a425-7fb295b8eaed.png)
> 
> 적용한 함수 기능 코드와
> 
> ![image](https://user-images.githubusercontent.com/134262055/273076394-6e40089f-3e98-4959-827e-1a0850986c45.png)
> 
> 테스트 목적으로 1개의 지점에 POI를 지정한 코드 입니다.
> 
> 위 테스트 코드를 적용할 시 화면이 전환 된 후 화면이 고정되어 마우스로 화면 이동이 불가능한 상태가 됩니다. 카메라 이동 기능을 통해 적용한 좌표로 이동을 했을 때 POI가 출력된 것은 확인을 하였습니다.
> 
> [테스트 용 URL과 확인 방법] URL : http://203.228.54.49:8150/map
> 
> 확인방법 : 메인화면 좌측 nav '시뮬레이션' 클릭 -> '케이블 파단' 클릭 -> 방향 선택 후 확인 버튼 클릭 -> 현상 확인

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 질문에 대한 소스에 대한 입력된 값과 반환된 값에 대해서 명확히 명시 해주시기 바랍니다.

현재 주신 소스코드로는 어떤 입력값이 들어와서 어떤 반환값이 나왔는지 전혀 알수가 없어 답변드리기 어렵습니다.

또한 확인방법을 통해 사이트 구동시 다음과 같은 결과를 확인하였습니다.

![캡처](https://github.com/EgisCorp/XDWorld/assets/82924515/88270d76-65c9-4c2c-aa87-a647fc7fae58)
<container tag position>
현재 divcontainer 에서 position 항목이 체크 되어 있으면 화면이 고정이 되고 체크를 해제하면 이동이 정상적으로 이루어지고 있습니다.

체크 해제 후 마우스 이동을 통해 HTMLObject 정상적으로 출력되는걸 확인 하였습니다.

![캡처](https://github.com/EgisCorp/XDWorld/assets/82924515/f6da1fa3-2e83-4ecc-85ae-e4297523fbd3)
<test 출력 확인>

이 문제는 엔진 문제보다는 Web site를 구성하는 container에서 발생하는 부분 같습니다. 

현재 divcontainer elemet 반환후 position을 해제 하시면 문제 해결은 가능하지만 정확한 문제 해결을 위해서 

web site를 구성하는 element를 구성 관계에 대해서 먼저 확인 하시기 바랍니다.

**Comment by dlsdnjs46-newlayer** [comment]
답변 감사합니다. 

답변 해주신 내용 토대로 검토하여 다른 코드와 container 부분이 충돌이 나는 듯 하여 수정하니 정상 작동 하는 것을 확인하였습니다.
