### ISSUE TITLE
비디오 객체 사용시 사각형 폴리곤 위에 매핑

### ISSUE THREAD

**Issue by Parster** [EgisCorp/XDWorld#333]
엔진 버전
:1.54.0 (Released 2023-09-26)

문의 내용
:
안녕하십니까 박규호 대리입니다.

비디오 객체 기능 사용 중입니다.

현재 샌드 박스에선 좌표 하나를 기준으로 지면에 매핑시키는 것으로 보았습니다.

기능 중에 좌표 4개(사각형 폴리곤)을 보내서  지면에 매핑시키는 방법이 있을까요 ?

![image](https://github.com/EgisCorp/XDWorld/assets/86399390/ed9b6c91-cf52-4c32-8ac3-9ed88d1f3e65)

**Comment by egiskorea-ryong** [comment]
안녕하세요. 

현재 카메라 Frustum과 피규어 객체에 대해서만 비디오 텍스쳐가 적용되어있습니다.

해당 기능이 필요하시면 추후 기능 개발을 통해 업데이트 하도록 하겠습니다.

감사합니다.

**Comment by YunSumin** [comment]
안녕하세요, 

문의 주신 기능과 관련된 엔진 API가 업데이트되어, 경위도 영역 기반 폴리곤 비디오 텍스쳐 구현 방안에 대해 안내 드립니다.
금일 JSPolygon의 loadTexture에 픽셀 기반 데이터를 적용하는 기능이 추가되었습니다.

업데이트 된 기능을 이용하여 아래 단계를 통해 비디오 이미지를 텍스쳐로 적용하실 수 있습니다.

1. 비디오 엘리먼트 추가 및 비디오 로드
2. 엔진 로드
3. JSPolygon 생성 및 Face에 텍스쳐 설정
4. JSPolygon을 레이어에 추가
5. Interval을 실행하여 재생중인 비디오 이미지를 정기적으로 JSPolygon 텍스쳐로 적용
    (아래 단계가 반복 실행됩니다.)
    1) 비디오와 동일한 크기의 캔버스 생성
    2) 캔버스 컨텍스트를 통해 비디오 이미지를 그린 후 픽셀 데이터 반환
    3) 컨텍스트로부터 픽셀 데이터 반환
    4) loadTexture를 통해 텍스쳐 이미지 업데이트

JSPolygon은 ELT_PLANE 타입 레이어에 추가하시는 경우 RTT 환경으로 렌더링되고,
ELT_POLYHEDRON 타입 레이어에 추가하시는 경우 일반 폴리곤으로 렌더링됩니다.

실행 영상을 첨부 드립니다.
[RTT 폴리곤]

https://github.com/EgisCorp/XDWorld/assets/82925313/d0756f8d-1849-46f3-95bf-b3d7019751f1

[일반 폴리곤]

https://github.com/EgisCorp/XDWorld/assets/82925313/6a362ddf-99b9-41cc-8454-a22433c2e061


(RTT 방식 렌더링의 경우 지형 타일의 LOD에 따라 해상도에 영향을 줄 수 있습니다.)

위 단계를 실행하는 샌드박스 샘플 URL이 추가되었습니다.
https://sandbox.dtwincloud.com/code/main.do?id=object_polygon_rtt_video_image_texture

샘플 페이지 내 코드 참조 부탁 드립니다.

감사합니다.
