### ISSUE TITLE
위도·경도 좌표를 기준으로 건물선택 문의드립니다.

### ISSUE THREAD

**Issue by melacola** [EgisCorp/XDWorld#335]
문의 내용

위도·경도 좌표를 기준으로 건물을 선택하여 표시할 수 있는 방법이 궁금합니다. (ex. 색 변경 or 객체 선택)
 - 지도화면에 로딩이 완료된 건물 객체일 경우만 가능한건가요?

**Comment by avamk2** [comment]
안녕하세요 

위도,경도 기준으로 API 기능적으로 객체를 인식하는 기능을 조사해보았는데 특정목적으로 구성된 기능들은 있어도 범용적인 사용법으로 처리되는건 보이지 않았습니다.
해당 부분에 대해서는 기능 개발 및 API 추가하여 진행하도록 조치하겠습니다.

로딩후 동작의 골조는 기본적으로 클라이언트에서 동작을 기반으로 해서 그렇습니다. 
해당기능을 로딩과 관계 없이 동작으로 바뀔려면 서버기반에서 동작해야되기에 서버에 대한 부하와 사용자 수에 대한 비용을 생각해야되기에 현재로선 넣지 않았습니다.

현재 서버에 대한 기능이 향상되고 인프라에 대한 비용이 충분해 기능 추가도 검토하도록 하겠습니다.
