### ISSUE TITLE
이미지 로드 완료 후 이벤트 작동  문의

### ISSUE THREAD

**Issue by Parster** [EgisCorp/XDWorld#336]
엔진 버전
:XDWorld Version : 1.54.0 (Released 2023-09-26)

문의 내용
:
안녕하십니까 

폴리곤 RTT(http://sandbox.dtwincloud.com/code/main.do?id=object_polygon_rtt_image_changing) 사용시의
이미지 로드 완료 후 이벤트(Fire_EventTextureLoadComplete)가 어떤 상황에서 작동되는지 궁금합니다.

샌드박스에서 콘솔로 진행해보았을 때 변화가 없었습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/86399390/36684cdb-ba5d-4ec1-a755-9d25bc085b18)

**Comment by YunSumin** [comment]
안녕하세요,
문의 주신 내용을 토대로 샌드박스 내 Fire_EventTextureLoadComplete가 동작하지 않는 부분을 확인했습니다.
텍스쳐 로드 시 콜백이 가능하도록 엔진 수정 후 상세 내용 안내 드리겠습니다.

**Comment by Parster** [comment]
넵 감사합니다!

**Comment by YunSumin** [comment]
안녕하세요,
JSPolygon의 텍스쳐 이미지 로드 콜백과 관련하여 금일 엔진이 업데이트 되었습니다.  (v_1.54.1)

아래 업데이트 내용 참조 부탁 드립니다.
(https://github.com/EgisCorp/XDWorld#1541-hotfix-20231013)

이와 관련하여 샌드박스 샘플도 함께 업데이트 되었습니다.
(https://sandbox.dtwincloud.com/code/main.do?id=object_polygon_rtt_image_changing)
코드 내 loadTexture API 중 callback 함수 설정 부분을 참조하시면 됩니다.

감사합니다.
