### ISSUE TITLE
Terrain위에 Text붙이는법 질문

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#34]
![image](https://user-images.githubusercontent.com/3315478/121882644-c669dd00-cd4b-11eb-95c8-97dc2ac74987.png)
이런런식으로 텍스트 화면 표시 기능을 만들었는데 땅에 딱 붙도록 하려면 어떻게 해야하나요??

**Comment by SeongRyong-Choi** [comment]
아래 사진과 같이 POI의 Line이 지형과 맞닿게 하는 걸 말씀하시는 건가요?

![20210615_093302](https://user-images.githubusercontent.com/70614782/121975554-d66dd500-cdbc-11eb-9fb9-4c660bbf10b3.png)

**Comment by loeaf** [comment]
![image](https://user-images.githubusercontent.com/3315478/122043194-085f5580-ce16-11eb-9f9a-9502b00a3da7.png)
alt를 0으로 주니 땅 밑에 파뭍힙니다 ㅎㅎㅎ...

**Comment by YangHeeBong** [comment]
http://localhost:8081/dt_reference/code/main.do?id=object_image_overlab

위 방법과 같이 오버랩 된 이미지 객체 생성 후 처리 하시면 됩니다.
