### ISSUE TITLE
dem on/off 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by jangseonghyun** [EgisCorp/XDWorld#341]
엔진 버전
: XDWorld Version : 1.53.1 (Released 2023-08-04)

오류 발생 API
: Module.getTerrain()

오류 내용
: Module.getTerrain().demRate = 0;

을 사용하여 지형을 비활성화 해줄 때 일정 높이 이하에서 Tilt를 조절하면 해당 사진과 같은 현상이 발생하여 문의드립니다.

![image](https://github.com/EgisCorp/XDWorld/assets/50700729/2df1b82c-1f5d-4c10-8e39-931d638f4c64)

**Comment by hjaejae** [comment]
지형이 안이게 되면서 뒤에 대기효과가 보이는것 같습니다.

대기효과를 해제하는 방법은 아래와 같습니다.
```javascript
Module.getOption().atmosphereRender = false;
```

지형이 안보이는 현상은 현재 엔진에서 구현이 안되는데 좀 더 자세한 상황이나
최신 엔진에서 같은 현상이 일어나는지 다시 확인부탁드립니다.

**Comment by hjaejae** [comment]
다시 확인 결과 지형의 편차가 큰 곳에서 발생하는 문제로 확인되었습니다.

다음 업데이트시 문제가 수정됩니다.

**Comment by hjaejae** [comment]
안녕하세요.

1.55.1 엔진에 해당 기능이 수정되었습니다.

새로운 엔진으로 업데이트 후 사용 부탁 드립니다.
