### ISSUE TITLE
화면의 네 꼭짓점 좌표 조회와, 네 좌표로 바운더리로 위치 이동하는 API

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#343]
엔진 버전
: 1.53.1

문의 내용
: 안녕하세요.

현재 지도 화면의 네 꼭짓점에 해당하는 좌표를 조회하는 API와
4개의 좌표를 통해 해당 바운더리 내로 위치를 이동하는 API가 있나요?

**Comment by YunSumin** [comment]
안녕하세요, 문의주신 내용에 대하여 안내드립니다.

1. 지도 화면 네 꼭짓점에 해당하는 좌표 조회
  해당 기능은 화면 좌표를 통해 지도 좌표를 반환하는 아래 API를 사용하여 반환하실 수 있습니다.
    ``` javascript
    var mapPosition = Module.getMap().ScreenToMapPointEX(screenPosition);
    ```
    이때, 화면의 네 꼭지점은 지도 캔버스의 가로 세로 크기와 일치하므로,
    캔버스 엘리먼트의 가로, 세로 크기를 사용해 변환하실 수 있습니다.
    ``` javascript
    var map = Module.getMap();

    var mapWidth = Module.canvas.width;
    var mapHeight = Module.canvas.height;
  
    var leftTop = map.ScreenToMapPointEX(new Module.JSVector2D(0, 0));
    var rightTop = map.ScreenToMapPointEX(new Module.JSVector2D(width, 0));
    var rightBottom = map.ScreenToMapPointEX(new Module.JSVector2D(width, height));
    var leftBottom = map.ScreenToMapPointEX(new Module.JSVector2D(0, height));
    ```
    화면-지도 좌표 변환은 아래 샌드박스에서 기능을 확인해보실 수 있습니다.
    (만약 화면 좌표에 지형 피킹 지점이 없는 경우(하늘 향해 지면 위쪽으로 향하는 경우) 좌표는 null이반환되느 이 점 참고 부탁드립니다.)
    https://sandbox.dtwincloud.com/code/main.do?id=coordinate_screen_to_map  

2. 4개의 좌표로 생성되는 바운더리 범위의 카메라 이동

    해당 기능은 아래 샌드박스에서 확인하실 수 있습니다.
    https://sandbox.dtwincloud.com/code/main.do?id=camera_set_viewrect

    모니터 특성 상 좌표는 다각형이 아닌 min,max로 구성된 사각 영역으로 설정해야 하며,
    사각 영역을 화면에 전부 포함해야 하므로 카메라 틸트 각도는 지면과 수직하도록 자동 설정됩니다.

감사합니다.

**Comment by kseonok** [comment]
감사합니다!
