### ISSUE TITLE
지도 클릭 시 좌표 반환 이벤트 문의

### ISSUE THREAD

**Issue by 18kiku** [EgisCorp/XDWorld#344]
엔진 버전
:1.54.0

문의 내용
:
안녕하세요.

지도 클릭 시 포인트의 위도 경도 좌표를 반환하는 이벤트가 있는지 문의드립니다.

감사합니다.

**Comment by egiskorea-ryong** [comment]
안녕하세요.

마우스 클릭 지점 좌표반환 이벤트는 Fire_EventAnalysisPos 입니다.

이벤트 반환을 위한 마우스 모드는 Module.MML_RETURN_ANALYSISPOS 입니다.

```javascript
// 마우스 모드 변경
Module.XDSetMouseState(Module.MML_RETURN_ANALYSISPOS);

// 이벤트 등록
canvas.addEventListener("Fire_EventAnalysisPos", function(e){
	console.log(e.lon, e.lat, e.alt);
});
```
