### ISSUE TITLE
폴리곤 생성 후 건물 충돌 체크 및 건물 선택 방법 문의

### ISSUE THREAD

**Issue by Yebin-00** [EgisCorp/XDWorld#345]
엔진 버전
:1.53.2

문의 내용
: 영역을 설정하여 해당 영역 내에 있는 건물의 정보를 받아오고 싶습니다. (key 값)
영역을 폴리곤으로 생성하였을때, 해당 폴리곤과 건물이 충돌하는지 여부를 확인하고 충돌하는 건물은 select 상태로 만들 수 있는 방법이 있을까요?

**Comment by avamk2** [comment]
안녕하세요

제약사항이 있지만 폴리곤 기준으로 객체 선택을 처리하는 기능을 추가하여 업데이트 하였습니다.
