### ISSUE TITLE
폴리곤 비디오 텍스쳐를 이용한 건물 매핑과 직각으로 생성하는 방법 문의

### ISSUE THREAD

**Issue by Young-Ju98** [EgisCorp/XDWorld#346]
엔진 버전
: XDWorld Version : 1.55.1 (Released 2023-11-03)

문의 내용
: 안녕하세요 제가 폴리곤 비디오 텍스쳐를 이용해서 개발하고있는데
[ img_건물매핑 ]과 같이 비디오를 띄웠을때 건물에 매핑 할 수 있는 방법이 있을까요?

그리고 [ img_직각 ]과 같이 지도위에 직각으로 폴리곤을 세워서 비디오를 생성하는 기능도 개발하고있는데
현재는 2개의 좌표에서 약간씩 숫자를 더하거나 빼서 4개의 좌표를 만들어서 생성하였습니다.
혹시 2개의 좌표만으로 폴리곤 비디오 텍스쳐를 생성하는 방법이 있을까요?

[ img_건물매핑 ]
![image](https://github.com/EgisCorp/XDWorld/assets/109942684/f1524359-c186-4b6b-98c2-5fd200eb2584)

[ img_직각 ]
![image](https://github.com/EgisCorp/XDWorld/assets/109942684/46f6fe30-01d1-46f3-8717-a361ad99fc58)

**Comment by hjaejae** [comment]
1. 건물에 매핑을 할 경우  건물 모양이 복잡하고 카메라의 화각, 거리, 각도에 따라서 정교한 설정이 필요한 상황이라 지금은 지원을 하고 있지 않습니다.
2. 2개의 좌표를 이용해서 폴리곤을 만든다는 질문이 폴리곤의 Min, Max만 사용한다는 질문이신지요?
만약 그런 내용이라면 저희가 구하는 방식이랑 사용자가 구하는 방식이랑 큰 차이가 없을 것으로 생각됩니다. Min 값에 높이나 가로 길이를 이용하면 4개의 점을 충분히 사용자도 구할 수 있기 때문입니다.

이런 내용이 아니라면 좀 더 자세한 설명 부탁 드립니다

**Comment by Young-Ju98** [comment]
안녕하세요~ 답변주셔서 감사합니다!
2번의 경우 하단의 사진처럼 빨간 동그라미 좌표 2개와 높이 값만 이용해서 직각으로 세워진 폴리곤을 만드려고 하는 상황이었습니다.
그렇다면 혹시 좌표 2개와 높이만으로 반대편 좌표를 구할 수 있는 식을 알려주실수있나요?

![image](https://github.com/EgisCorp/XDWorld/assets/109942684/92235af6-028f-4ca6-aa42-8b1152559f0c)

**Comment by hjaejae** [comment]
좌표 2개와 높이 값을 알면 사각형 폴리곤을 만들 수 있습니다.
질문하신 내용중에 반대편 좌표라는 질문이 무슨 뜻인지 잘 모르겠습니다.

그리고 첫 번째 질문에 대해서 보충 설명 해드리면 
폴리곤 비디오 텍스쳐는 폴리곤에 비디오를 그리는 API라 건물에는 텍스쳐를 적용 할 수 없고
https://sandbox.dtwincloud.com/code/main.do?id=camera_video_texture 예제를 보시면
지형과 건물에 비디오 텍스쳐를 그리는 예제가 있습니다.
이를 이용해 활용 가능하시면 적용하시면 될것 같습니다.
