### ISSUE TITLE
WMS Layer 관련

### ISSUE THREAD

**Issue by Rach0209** [EgisCorp/XDWorld#347]
엔진 버전
:  Version : 1.52.0 (Released 2023-06-30)

오류 발생 API
: createWMSLayer

오류 내용
: 레이어 자체는 잘 불러와집니다.
그런데 geoserver에서 openlayers map preview 로 확인할 떄는 이미지의 숫자 짤림이 없는데, WMSLayer 호출해서 확인하면 특정 구간만 숫자가 표기가 안되는 현상이 있습니다.
혹시, 엔진의 오류인지 확인 부탁드립니다.
![Screenshot_3](https://github.com/EgisCorp/XDWorld/assets/104557592/36d2c1e7-b5c4-4176-855a-6d20e47aa068)
![Screenshot_4](https://github.com/EgisCorp/XDWorld/assets/104557592/4e40eeb8-052e-4cbf-a3a7-bde8917dfbfb)

**Comment by Rach0209** [comment]
추가로 레이어를 불러올 때는 clearWMSCache(); 를 사용한 후 불러옵니다.

**Comment by hjaejae** [comment]
GeoServer의 미리 보기와 결과가 조금 다를 수 있습니다.
이유는 미리 보기는 전체 한판을 미리 보기 한 결과이고 엔진에서 사용하는 이미지는 256X256 이미지를 불러와서 사용하기 때문입니다.
256X256으로 자를 때 경계에 겹칠 때도 있고 포함 될 때도 있습니다.
폰트의 크기를 조절해서 사용해보시고 결과를 다시 확인해주시면 감사하겠습니다.

**Comment by Rach0209** [comment]
스타일과 폰트는 변경해서 사용해보았는데, 여전히 특정 부분만 안나왔습니다.
로딩이 될 때 자세히 보면, 경계 근처에 있는 것들이 문제가 되는 것 같습니다.
혹시, 경계에 겹쳐지거나 포함될 때 처리를 할 수 있는 방법이 엔진에 따로 있을까요?

**Comment by hjaejae** [comment]
GeoServer의 스타일 문제라 엔진에서 따로 처리 할 수는 없습니다.

제가 비슷한 문제가 있어 해결했던 적이 있는데 아래 사이트를 참고 하였습니다.

https://gis.stackexchange.com/questions/148465/labels-not-displaying-correctly-in-the-centroid-of-the-polygon-in-geoserver-sld

GeoServer 스타일에 여러가지 옵션을 적용해서 해결 할 수 있을 것 같습니다.
