### ISSUE TITLE
레이어 offset 관련 기능 문의드립니다.

### ISSUE THREAD

**Issue by jangseonghyun** [EgisCorp/XDWorld#348]
엔진 버전
: XDWorld Version : 1.53.1 (Released 2023-08-04)

문의 내용
: 특정 레이어를 선택한 후 가로, 세로 값을 입력 했을 때 입력된 수치 만큼 레이어의 위치를 옮기는 기능이 있는지 궁금합니다.

**Comment by YunSumin** [comment]
안녕하세요,
현재 엔진 내 레이어를 임의의 거리만큼 이동시키는 기능은 없습니다.

엔진 개발 팀 내부적으로 기능에 대한 검토가 필요할 것으로 보입니다.
사용하시는 레이어에 대한 자세한 설명을 주시면 검토 후 말씀드리겠습니다.
