### ISSUE TITLE
폴리곤 위치 이동 및 setEditable API 관련 문의

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#349]
엔진 버전
: 1.53.1

문의 내용
: 안녕하세요.

폴리곤을 선택 후 드래그를 통해 위치를 이동시키는 기능이 필요한데,
샌드박스에서 비슷한 예제를 발견하였습니다.
https://sandbox.dtwincloud.com/code/main.do?id=object_figure

폴리곤을 선택했을 때 도형을 편집할 수 있는 UI가 setEditable을 통해 제어되는 줄 알았는데,
setEditable을 true, false 모두 폴리곤을 편집할 수 있는 것 같았습니다.

setEditable의 역할이 무엇인가요?

그리고, 오브젝트를 선택하여 위치 및 모양을 변경시키는 것은
setMouseState(101~110)을 통해 생성한 폴리곤만 가능한가요?

직접 좌표 입력을 통해 생성한 폴리곤은 해당 기능을 사용하지 못하나요?

**Comment by egiskorea-ryong** [comment]
안녕하세요.

1. 
[도형 생성](https://sandbox.dtwincloud.com/code/main.do?id=object_figure) 예제는 마우스로 드래그하여 객체를 생성하는 샘플입니다.

코드상으로 객체를 생성할 경우 레이어에 직접 객체를 추가하지만 

해당 샘플의 경우 마우스로 객체를 생성하기 때문에 어떤 레이어에 추가할지 설정해줘야합니다. (setEditable = true)

별도로 레이어를 생성하여 편집상태로 전환하지 않을 경우 임시 레이어에 객체를 추가합니다. (setEditable = false)

그래서 setEditable은 해당 레이어를 편집상태로 전환하는 기능입니다.


2.
[전광판](https://sandbox.dtwincloud.com/code/main.do?id=object_ledboard) 샘플의 전광판 편집 기능을 참고하시면 될것같습니다.

감사합니다.

**Comment by kseonok** [comment]
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/d891dbb4-3c3f-4703-b397-aefb3ee797ee)
혹시 전광판 샘플 예제와 같이 편집UI가 나오는 것은 Module.createFigure로 만들어진 오브젝트에서만 가능한가요?

Module.createPolygon으로 만들어진 폴리곤도 객체 사이즈, 위치 이동, 방향 변경을 할 수 있는 기능이 있나요?

**Comment by egiskorea-ryong** [comment]
해당 편집 UI는 Figure 객체에만 생성됩니다.

웹에서 별도로 UI를 생성하여 API를 조합하여 해당 기능을 개발 할 수도 있습니다.

[고스트심볼 위치이동](https://sandbox.dtwincloud.com/code/main.do?id=object_ghostsymbol_move)

해당 샘플은 고스트심볼 객체 이동 샘플이지만 JSPolygon 객체도 동일하게 사용할 수 있습니다.

하지만 JSPolygon의 스케일, 회전은 API 추가가 필요합니다.

현재 하시고자하는 기능이 Figure객체와 완전 동일한 편집기능을 원하시는건지 자세하게 설명해주시면 감사하겠습니다.

**Comment by kseonok** [comment]
위치이동 기능만 있으면 될 것 같습니다!

고스트심볼 위치 이동 예제를 참고하여 테스트 하던 중, setPosition은 JSPolygon에서 작동하지 않는 것 같아
오브젝트.position = 위치; 방식으로 위치를 옮겨보려하였는데
아래 이미지와 같이 테두리는 남아있고, 본체(?)만 움직입니다.
혹시 버그일까요..?

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/9333a5fd-df65-4851-afd0-3ef913541bed)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

해당 오류 확인되어 오류 수정 후 1.56.0 버전 배포하겠습니다.

감사합니다.
