### ISSUE TITLE
샌드박스 기능 확인 부탁드립니다.

### ISSUE THREAD

**Issue by melacola** [EgisCorp/XDWorld#350]
오류 내용
:
아래 URL 에 해당하는 예제에서 샐랙트박스에서 2015년 영상이나 다른년도 영상을 선택하면 아래 이미지처럼 보여집니다.
https://sandbox.dtwincloud.com/code/main.do?id=layer_wmts

확인 부탁드립니다.

![image](https://github.com/EgisCorp/XDWorld/assets/11719538/e3b093c1-0b74-45a0-8d98-e5bd1fe532be)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

현재 발생하는 오류는 국토정보플랫폼에서 업데이트로 인해 발생하는 것으로 확인됐습니다. [참고자료](https://map.ngii.go.kr/emapApi/map/wmts_sample07_v6.do)

또한, 국토정보플랫폼에서 지원을 중단한 지도는 샌드박스에서 삭제할 예정이며

위 내용을 바탕으로 샌드박스 샘플을 수정 할 예정입니다.
