### ISSUE TITLE
모델링 파일

### ISSUE THREAD

**Issue by Minho3256** [EgisCorp/XDWorld#351]
엔진 버전
:

문의 내용
: 안녕하세요! 혹시 지도의 일부분을 FBX 파일로 익스포트가 가능할까요??

**Comment by hjaejae** [comment]
FBX 파일은 바이너리 파일 형식에 대한 사양이 공식적으로 제공되지 않아 특정 SDK를 이용해서만 완벽하게 지원할 수 있습니다.
그래서 현재 엔진에서 지원하지 않습니다.

그리고 다른 3D 형식의 파일 Export도 특수한 상황이 아니면 제공하기가 힘듭니다.
3D 형식의 파일을 Export하기 위해서는 특정 라이브러리가 엔진 안에 포함되어야 하고 
그렇게 되면 엔진의 용량이 늘어나거나 복잡도가 올라가서 입니다.

**Comment by avamk2** [comment]
안녕하세요 데이터의 추출부분에서는 저희도 고민하는 부분이지만 생각해야될 문제가 많이 존재합니다.

첫번째로 VWorld 데이터인 경우는 서비스 데이터의 추출 및 사용자PC로 저장 및 재사용에 대해서 금지되고 있습니다.
그래서 해당 데이터가 필요하다면 VWorld 운영처에 데이터 사용 허락을 별도로 받고 보안서약등이 필요한 것으로 알고 있습니다.

두번째로 데이터 추출 범위의 문제입니다. XDWorld에 서비스 데이터는 서비스 속도를 위해서 꼭 필요한 요소부분만 최적화된 포맷으로 서비스하는데 이를 범용 모델링 포맷으로 추출하려면 기존 서비스 데이터 용량보다 많은 메모리가 필요로합니다. 추출의 범위나 데이터용량의로 인한 메모리 부족이 발생하여 페이지 새로고침이나 웹페이지 프리징이 발생 할 수 있습니다.

세번째로 데이터 포맷의 문제입니다. 위에 답변에서 일부 언급되었지만 오픈된 포맷이 아니면 상업적 라이센스 및 SDK가 필요한 경우가 많이 있습니다. 때문에 혹여나 제한적으로 추출기능이 구현되더라도 obj나 3ds, citygml 같은 포맷으로 한정할 수 밖에 없으며 이를 외부 데이터 포맷 변환 툴을 통해서 변환 후 사용하는 방향으로 생각해야될 것입니다. 또한 SDK들의 용량들도 만만하지 않아서 현재도 XDWorld 엔진에 용량으로 인한 초기 로딩 부담이 있는 엔진 파일에 용량이 크게 오르면 데이터 포맷 추출과 관계 없이 초기 로딩의 시간과 동작등의 성능에 영향을 주기에 엔진에 내장하는 방향으로는 진행하지 못합니다.
 
이러한 문제로 현재까지 데이터 추출에 관련된 기능은 엔진에서는 도입하고 있지 않습니다.
