### ISSUE TITLE
createXDServerLayer관련 문의드립니다.

### ISSUE THREAD

**Issue by jangseonghyun** [EgisCorp/XDWorld#352]
엔진 버전
: XDWorld Version : 1.55.2 (Released 2023-11-16)

문의 내용

안녕하세요. 

아래와 같은 방식으로 레이어를 생성한 후 
Module.getTileLayerList().createXDServerLayer({
    url: _url,
    servername: _servername,
    name: _name,
    type: _type,
    minLevel: _minLevel,
    maxLevel: _maxLevel,
    userLayer: _userLayer,
    visible : false
});

Module.getTileLayerList().nameAtLayer('hybrid_img_yw_51cm_2015').setVisible(true);
를 사용하여 최초에 visible값을 true로 변경할 때,

![image](https://github.com/EgisCorp/XDWorld/assets/50700729/1c92c5d0-03cc-43d1-a3f1-20ce4d35fbc6)

![image](https://github.com/EgisCorp/XDWorld/assets/50700729/986f6446-903a-494d-a9f8-e9ecfafc8316)

두번째 사진과 같이 레이어의 일부만 보여지는 현상이 있습니다.

줌인 줌아웃하면 레이어가 제대로 보이며, 이후에는 같은 작업을 반복했을 때 위와 같은 현상이 없습니다.

해결방법이 있을지 문의드립니다.

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

질문을 확인결과 혹시 이미지 파일 순서가 변경된건가요?? 변경된게 아니라 정상적으로 표현하셨다면 의미가 모호합니다. 

일단 이미지 순서가 변경되었다는 기준으로 설명드리겠습니다. 

원인은 가시화 거리에 따른 지형 LOD 가시화 단계로 추측 됩니다.

지형은 카메라 거리에 따라 하위 지형 레벨을 요청하고 가시화 합니다.

그런데 현재 가시화 레벨과 하이브리드 이미지 데이터의 경계선에 위치함으로 가시화가 안되어서 질문과 같은 현상이 나타나는것같습니다.

API [지형 가시화 범위 설정](https://egiscorp.gitbook.io/xdworld-webgl-manual/map/jsmap#setterrlodratio-ratio)을 참조하시면 될것같습니다.

**Comment by jangseonghyun** [comment]
해당 링크 참조하여 반영하였고, 해결되었습니다
감사합니다.
