### ISSUE TITLE
layer addObject 호출 중 기존 HTMLObject 클릭 불가 현상

### ISSUE THREAD

**Issue by 18kiku** [EgisCorp/XDWorld#353]
엔진 버전
: 1.54.0

문의 내용
: 
안녕하세요.
레이어에 addObject함수 사용시 기존 HTMLObject 클릭이 불가능한 현상 문의드립니다.

현재 0.1초마다 레이어 내의 모든 고스트심볼 제거후 생성을 반복하여 차량이 이동하는것처럼 보이는 효과를 주고있습니다.

기존에 추가한 HTMLObject들이 클릭이 되지 않아 개발자도구를 확인해보니 기존에 추가되어있는 HTMLObject들도 _layer.addObject를 사용할때마다 같이 갱신되고있는것 같습니다.
![image](https://github.com/EgisCorp/XDWorld/assets/98327681/5c31c149-ee11-40f9-b384-d2118c79e133)

임시조치로 HTMLObject를 클릭해야할 경우에는 고스트심볼의 재생성을 멈추게 했는데 고스트심볼 재생성중에도 기존 HTMLObject를 클릭할 수 있도록 수정하고싶습니다.

사용한 코드 첨부합니다.
[{ "x": 127.0327, "y": 37.4835, "angle": 338.8059}, {"x": 126.9965, "y": 37.4831, "angle": 153.6233}, ... ]
0.1초마다 위 형태의 좌표 배열을 createSimulation함수에 파라미터로 넘겨서 기존 고스트심볼 객체를 모두 제거하고 1000개 가량의 고스트심볼 객체를 다시 생성하여 레이어에 추가합니다.

```
const createSimulation = (data) => {
	let vehicleLayer = Module.getObjectLayerList().nameAtLayer("VEHICLES");
	if (vehicleLayer == null) {
		vehicleLayer = Module.getObjectLayerList().createObjectLayer({
			name: "VEHICLES",
			type: Module.ELT_GHOST_3DSYMBOL
		});
		vehicleLayer.setMaxDistance(5000);
	}

	// 레이어 clear 후 생성
	vehicleLayer.removeAll();

	const points = JSON.parse(data);
	for (let i = 0; i < points.length; i++) {
		createSumoCar(vehicleLayer, points[i], randomIndex);
	}
};

// sumo에서 넘어오는 좌표배열로 고스트심볼 생성
const createSumoCar = (_layer, point, type) => {
	const _modelID = GLOBAL.vehicleModels[0];
	const modelHalfHeight = Module.getGhostSymbolMap().getGhostSymbolSize(_modelID).Height * 0.5;
	// 고스트심볼 오브젝트 생성
	const vehicle = Module.createGhostSymbol(_modelID + "_copy_" + generateUUID());
	vehicle.setBasePoint(0, -modelHalfHeight, 0);
	vehicle.setScale(new Module.JSSize3D(0.002, 0.002, 0.002));
	vehicle.setGhostSymbol(_modelID);

	const altitude = Module.getMap().getTerrHeightFast(parseFloat(point.x), parseFloat(point.y));
	const position = new Module.JSVector3D(parseFloat(point.x), parseFloat(point.y), altitude + 5);
	vehicle.setPosition(position);
	vehicle.setDirection(point.angle - 90); // 모델에 따라 각도 설정

	_layer.addObject(vehicle, 0);
}
```

감사합니다.

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

HTMLObject를 통해 생성된 오브젝트는 WebGL 내부에서 생성된 오브젝트가 이닌 HTML에서 생성된 Element 입니다.

선택관련해서 엔진과는 무관합니다.

샌드박스 [HTML 미디어 적용](https://sandbox.dtwincloud.com/code/main.do?id=object_html) 에서 49번째 줄에 존재하는 클릭 이벤트를 보시면 Element와 직접적으로 함수와 연결되는걸 확인 가능합니다.
