### ISSUE TITLE
서비스레이어 건물 색상 변경

### ISSUE THREAD

**Issue by Parster** [EgisCorp/XDWorld#354]
엔진 버전
: 1.55.2 (Released 2023-11-16)

문의 내용
:
안녕하십니까

XDServer에서 서비스 중인 LOD1 건물(요청파일형식_XND , 건물파일형식_XDO) 레이어가 있습니다.
건물의 색상 변경하는 함수가 있을까요 ?

![image](https://github.com/EgisCorp/XDWorld/assets/86399390/71723fab-270b-42e3-a956-288fd0ea48ca)

**Comment by avamk2** [comment]
안녕하세요

텍스처가 맵핑되지 않은 서비스 건물에 대한 색상적용은 레이어 기준에서 일괄로 적용가능합니다.

서비스 레이어 리스트 -> 적용할 건물 레이어 -> 건물 텍스처 LOD1 건물에 대한 색상 적용

색상을 적용하는 API는 아래와 같습니다.

` JSLayer::setTileObjectInitColor(JSColor _color) `

**Comment by Parster** [comment]
감사합니다 
소스 적용해봤는데 적용이 잘 되질 않아서 
소스 확인 한번만 부탁드리겠습니다.
![image](https://github.com/EgisCorp/XDWorld/assets/86399390/985ade42-81fe-4f08-9557-6171568bdad3)

**Comment by avamk2** [comment]
컬러색상 적용은 아래 샘플로 ARGB를 설정할 수 있습니다.

```
var RED = new Module.JSColor(180, 255, 0, 0);
var BLUE = new Module.JSColor(180, 0, 0, 255);
var YELLOW = new Module.JSColor(255, 255, 255, 0);
var WHITE = new Module.JSColor(255, 255, 255, 255);
```

**Comment by avamk2** [comment]
처리 특성상 건물 데이터 로딩전에 색상 설정 API를 적용해야 로딩하면서 색상 반영해서 그려지게 될겁니다.

**Comment by Parster** [comment]
소스 적용 부분 확인 부탁드립니다 .

![image](https://github.com/EgisCorp/XDWorld/assets/86399390/47a54e0b-ab23-421b-8dbc-1fc85acb68e2)

**Comment by avamk2** [comment]
해당 부분 확인을 통해서 현재 29번 레이어에서 색상 정보 전달이 누락되어 있음을 확인하였습니다.

해당 사항을 다시 반영하여 수정업데이트를 진행할 예정입니다.

사용하신 코드 방식은 오류가 없기에 엔진을 수정 업데이트로 갱신하면 정상적인 결과를 보실겁니다.
