### ISSUE TITLE
레이어 가시화 관련 문의드립니다.

### ISSUE THREAD

**Issue by jangseonghyun** [EgisCorp/XDWorld#355]
엔진 버전
: XDWorld Version : 1.55.2 (Released 2023-11-16)

문의 내용

안녕하세요.

아래와 같은 방식으로 레이어를 생성한 후
Module.getTileLayerList().createXDServerLayer({
url: _url,
servername: _servername,
name: _name,
type: _type,
minLevel: _minLevel,
maxLevel: _maxLevel,
userLayer: _userLayer,
visible : false
});

Module.getTileLayerList().nameAtLayer('layer_name').setVisible(true);
최초에 레이어를 가시화 할 때, 아래의 이미지와 같이 화면 전체에 깜빡임 현상이 있습니다.
깜빡임 없이 레이어를 가시화 할 수 있는지 문의드립니다.

![image](https://github.com/EgisCorp/XDWorld/assets/50700729/5b5a3f89-d291-48c1-b45a-10249186061a)

**Comment by avamk2** [comment]
안녕하세요 

깜빡임이라는 것이 화면이 순간적으로 검개변했다가 다시 켜지는걸 의미하는 건가요?

아니면 첨부 이미지처럼 일부 지형의 이미지가 흐리게 나오는 것을 의미하는 건가요?
