### ISSUE TITLE
setLODRatio, lod_object_detail_ratio, setVisibleRange의 두번째 파라미터 차이

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#356]
엔진 버전
: 1.53.1

문의 내용
: 안녕하세요.

setLODRatio, lod_object_detail_ratio, setVisibleRange의 두번째 파라미터 모두 LOD를 조절하는 API로 알고 있는데,
각각 차이가 뭔가요? 셋 중 하나만 써도 되는 건가요?

**Comment by hjaejae** [comment]
setLODRatio API와 setVisibleRange의 두번째 파라메터는 같은 의미입니다.
위 두 API는 객채의 보이는 비율을 설정하는 값입니다.
값이 증가할수록 멀리서 보입니다.

lod_object_detail_ratio 프로퍼티는 객체의 텍스쳐의 퀄리티를 결정합니다.
값이 증가할수록 같은 거리에서 보이는 텍스쳐의 퀄리티가 올라갑니다.

**Comment by KIMSEONOK** [comment]
감사합니다!
