### ISSUE TITLE
createHTMLObject로 생성된 Object z-index 설정 문의드립니다.

### ISSUE THREAD

**Issue by 18kiku** [EgisCorp/XDWorld#357]
엔진 버전
: 1.54.0

문의 내용
:
안녕하세요.
createHTMLObject로 생성된 Object z-index 고정 방법 문의드립니다.

#279 해당 이슈에서 html element를 불러와서 z-index를 직접적으로 수정하면 된다는 답변을 확인했습니다.
그래서 Fire_EventCameraMoveEnd 이벤트와 Fire_EventRotateCompass 이벤트가 발생할 때마다 createHTMLObject로 생성된 element 중에서  active 클래스를 가졌다면 z-index를 9999로 변경하도록 했습니다.
```
        canvas.addEventListener("Fire_EventCameraMoveEnd", function(e){
		if ($traffic.hasClass('active')) {
			const $wrapSimulation = $('.wrap-simulation'); // createHTMLObject로 생성한 element
			$wrapSimulation.css('display', 'block');
			setTimeout(() => {
				$('#xdworld .btn-simulation').filter('.active').closest('.wrap-simulation').css('z-index', '9999');
			}, 3000);
		}
	});

	canvas.addEventListener("Fire_EventRotateCompass", function(e){
		if ($traffic.hasClass('active')) {
			const $wrapSimulation = $('.wrap-simulation');  // createHTMLObject로 생성한 element
			$wrapSimulation.css('display', 'block');
			setTimeout(() => {
				$('#xdworld .btn-simulation').filter('.active').closest('.wrap-simulation').css('z-index', '9999');
			}, 3000);
		}
	});
```
z-index를 변경하는 부분에 setTimeout을 3초정도 주면 z-index가 변경은 되는데 지도위에서 마우스를 움직이기만 해도 다시 카메라와의 거리에 따라 z-index가 변경되어버립니다.

z-index를 설정과정을 동작하게 하는 이벤트들에 z-index 고정을 위해 핸들러를 추가하려고 합니다.
위의 두 이벤트를 제외하고 또 어떤 이벤트가 발생할때마다 "HTMLObject z-index 설정 과정"이 동작하는건가요?

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

HTML z-index가 설정되는 이벤트는 지도 가시화가 동작 되는 기준으로 변경됩니다.

하지만 여기에서도 속도 향상을 위해서 몇가지 조건에 부합되어야 합니다.

1. HTMLObject 가시화 출력 스크린 좌표가 동일할 떄 이전 상태 유지
2. 사용자 입력(UI) 처리가 없고 지도 가시화가 일정이상 유지 된 상태이면 이전 상태 유지

이 2가지 조건이 아닌 상태라면 지도 가시화 이벤트 동작 시 지속적으로 [이슈297](https://github.com/EgisCorp/XDWorld/issues/279) 항목을 기준으로 z-index를 재설정합니다. 

만약 HTMLObject가 변화되는 시점에 콜백함수를 처리할 수 있도록 기능을 제공하고있습니다. 

```javascript

function moveCallBack(_item) {
    console.log(_item);
//_item 반환 정보
/*
1. element : 객체 정보
2. viewDistance : 카메라와의 거리
3. x : 스크린 X축 좌표
4. y : 스크린 Y축 좌표 
*/
}

function createHTMLObject() {
// 오브젝트 생성
let parameter = {
        position: new Module.JSVector3D(129.13782351349964, 35.17887462859219, 400.0), // 위치 지점
        container: "divcontainer", // div를 담을 Container 명칭 지정(명칭에 해당되는 div가 없다면 createHTMLObject 작업중 생성)
        canvas: Module.canvas, // 화면 사이즈 설정을 위한 canvas 설정
        element: element, // 엔진 오브젝트와 연동할 HTML Element
        moveChange: moveCallBack, // HTMLObject Rnder 이벤트 발생시 동작하는  콜백
    };
// 오브젝트 레이어 등록
}
```

console.log 결과는 아래 이미지와 같이 나옵니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/136686b4-d428-4cec-adc7-8fe845328a85)

이 방법을 통해 HTMLObject를 실시간으로 변경 가능합니다.

하지만 z-index는 현재 내부 코드 확인 결과 CallBack 이후 z-index가 설정됨으로 몇가지 테스트 이후 CallBack을 통해 z-index 설정 부분을 다음 업데이트를 통해 제공해드리겠습니다.

**Comment by YangHeeBong** [comment]
현재 엔진 적용 후 결과는 다음과 같습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/47b4bee8-6bd1-4b49-b8e0-49065a41842f)
<Index -1 설정 시>
![image](https://github.com/EgisCorp/XDWorld/assets/82924515/3f01ff0c-2bad-454c-8b46-b7f08158d2f7)
<Index 99 설정 시>

``` javascript

let m_zindex = 0;
// 버튼 입력시 발생
function changeIndex(_index) {
    m_zindex = _index;
}
// HTMLObject CallBack
function moveCallBack(_item) {
    _item.element.style.zIndex = m_zindex;
}

function createHTMLObject() {
// 오브젝트 생성
let parameter = {
        position: new Module.JSVector3D(129.13782351349964, 35.17887462859219, 400.0), // 위치 지점
        container: "divcontainer", // div를 담을 Container 명칭 지정(명칭에 해당되는 div가 없다면 createHTMLObject 작업중 생성)
        canvas: Module.canvas, // 화면 사이즈 설정을 위한 canvas 설정
        element: element, // 엔진 오브젝트와 연동할 HTML Element
        moveChange: moveCallBack, // HTMLObject Rnder 이벤트 발생시 동작하는  콜백
    };
// 오브젝트 레이어 등록
}
```
이상입니다.
급한 일정이 아니라면 다음 업데이트 시 정상적으로 업로드 예정입니다.

**Comment by jeonghwanhwang** [comment]
안녕하세요. 확인 감사합니다.
해당사항을 금주중으로 수정 완료해야 하는데 혹시 다음 업데이트 일정을 알 수 있을까요?

**Comment by 18kiku** [comment]
안녕하세요. 확인 감사합니다.
해당사항을 금주중으로 수정 완료해야 하는데 혹시 다음 업데이트 일정을 알 수 있을까요?

**Comment by YangHeeBong** [comment]
정상 일정은 월 마지막 주 금요일이 정상 엔진 업데이트 날짜입니다.
일정에 따라 엔진 Hotfix로 처리 가능하며 급한 부분이라면 내일 중으로 업데이트하도록 하겠습니다.

**Comment by 18kiku** [comment]
급한 일정이어서 핫픽스로 업데이트를 부탁드릴 수 있을까요? 감사합니다

**Comment by YangHeeBong** [comment]
엔진 1.56.0 업데이트 완료했습니다.
