### ISSUE TITLE
createCirclePolygon 문의드립니다

### ISSUE THREAD

**Issue by leepulum727** [EgisCorp/XDWorld#359]
엔진 버전
:1.55.2

오류 발생 API
:createCirclePolygon()

오류 내용
:
![image](https://github.com/EgisCorp/XDWorld/assets/73877693/8fa4519b-8c62-44f0-84dc-7c91543538a0)
function createCirclePolygon( id, _center, _radius, _segment, _fillColor, _outlineColor) {

	var layerList = new Module.JSLayerList(true);
	var layer = layerList.createLayer("COLOR_POLYGONS", Module.ELT_POLYHEDRON);

	// 폴리곤 객체 생성
	var polygon = Module.createPolygon(id);

	// 폴리곤 색상 설정
	var polygonStyle = new Module.JSPolygonStyle();
	polygonStyle.setFill(true);
	polygonStyle.setFillColor(_fillColor);
	if (_outlineColor != null) {
		polygonStyle.setOutLine(true);
		polygonStyle.setOutLineWidth(2.0);
		polygonStyle.setOutLineColor(_outlineColor);
	}
	// 버텍스 폴리곤 형태 설정
	polygon.setCircle(_center, _radius, _segment);
	layer.addObject(polygon, 0);
	polygon.setStyle(polygonStyle);
	polygon.setHeight(50);
	
	// 레이어에 객체 추가
}

위에 소스로 만들었을때 사진처럼나오는데  제대로된 원기둥 형태가 안나오는게 맞는건지 문의드립니다.

**Comment by leepulum727** [comment]
완벽한 원기둥형태가 필요합니다...!

**Comment by hjaejae** [comment]
확인 하였습니다.
다음 엔진 업데이트 시 반영될 예정입니다.

**Comment by HeoTaeYang** [comment]
안녕하세요.
해당 이슈 반영한 버전 업데이트 되었습니다.
