### ISSUE TITLE
미니맵 생성

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#36]
![image](https://user-images.githubusercontent.com/3315478/122044624-ac95cc00-ce17-11eb-95f1-ff2bb89a5647.png)
안녕하세요! 예전에 이렇게 생긴 MapControll을 다른 엔진쪽에서 이용해 왔는데 EGIS쪽에서 유사한 API가 혹시 있을까요?
만약 없다고 하면 혹시 미니맵 같은 기능을 플랫폼쪽에서 제공이 가능할까요?

**Comment by YangHeeBong** [comment]
![image](https://user-images.githubusercontent.com/82924515/123888211-f8a34d80-d98d-11eb-9773-be6ace97d78c.png)
2D 컨트롤은 아래 방법을 통해
   - 켜기 : Module.getNavigation().setNaviVisible(Module.JS_VISIBLE_ON);
   - 끄기 : Module.getNavigation().setNaviVisible(Module.JS_VISIBLE_OFF);

지원 합니다.

엔진은 위 이미지 처럼 고정된 UI만 지원하고 있습니다.
다른 2D 컨트롤 구성은 HTML, CSS를 이용하여 다양한 UI를 웹 프로그램 영역에서 개발하고
엔진 정보(주로 카메라 위치, 회전)를 연동하여 사용 중 입니다.

엔진으로 구성된다면 제한된 기능과 변경 시 엔진 수정이 불가피 함으로 2D UI 영역은 웹 프로그램에서 처리 하고 있습니다.
