### ISSUE TITLE
wms 생성후 호출 가능한 콜백함수 문의

### ISSUE THREAD

**Issue by youkkang** [EgisCorp/XDWorld#360]
let slopeoption = {
		url: strUrl,
		layer: strLayer,
		minimumlevel: numMinlevel,	
		maximumlevel: numMaxlevel,	
		tilesize: numTileSize,		
		crs: strCrs,				
		parameters: {
			version: strVersion
		}
		};	
		wmslayer = layerList.createWMSLayer(layer_nm) 
		wmslayer.setWMSProvider(slopeoption);			
		wmslayer.setBBoxOrder(bBox);
}

로 wms 레이어 호출후, 호출이완료(이미지 로드 완료) 돼면 
부를수 있는 콜백함수가 있을까요?

또 wms로 불러온 레이어의 객체 클릭이벤트 기능도 알려주시면 감사하겠습니다 :)

**Comment by youkkang** [comment]
답변 안주시나요~~

**Comment by avamk2** [comment]
안녕하세요 답변이 늦어서 죄송합니다.

WMS에서 처리가 2D에서는 화면의 지도 범위를 한번에 로딩하는 구조라서 콜백으로 이 완료시점을 처리가능합니다. 
우리엔진에서는 LOD라는 특성때문에 현재는 지형의 타일구조로 요청하는 방식이라 실질적으로는 WMTS에 가깝게 동작 요청하게 됩니다. 이로 인해서 지형은 LOD(상세함을 단계처리)가 들어가기에 화면 중심이 보다 상세하고 주변은 그 상세함이 적은 수준으로 데이터를 연속적인 로딩을 하고 있습니다. 때문에 2D 처럼 콜백이벤트를 이야기하시면 이는 지형타일 하나 규모의 콜백이 무수히 많이 발생할 수 있습니다.  (크롬 개발자 모드를 통해서 WMS 요청 횟수만 보면 확인 가능)

결과적으로 이러한 기능을 추가하면 매우 많은 콜백 요청에 의해서 성능 저하로 이어질수 있기에 현재 개발 사항으로 고려하지 않습니다.

두번째 WMS로 불러온 레이어는 WMS서비스하는 서버측면에서 데이터를 이미지화(레스터라이징)해서 보내주기 때문에 객체에 대한 식별은 엔진에서 불가능합니다. 
현재 이를 식별하는 것을 보셨다면 그것은 다음 단계로 구현했을 것입니다.

1. 엔진에서 마우스 클릭에 대한 클릭된 지점의 좌표(경위도)를 취득
2. WMS서비스하는 서버측에 WFS로 포인트로 공간요청 후 식별된 객체의 공간 정보(GML)을 취득
3. 엔진의 API를 통해서 Polygon 객체를 만들어 지형 오버레이로 등록

WMS를 서비스하는 서버에 각 데이터 특성을 알수 없기에 엔진에서는 이를 따로 제어하는 기능을 구현할 수 없습니다.
 
콜백에 대한 다른 방향으로 생각하는게 있으시면 회신바랍니다.
