### ISSUE TITLE
최신 엔진 지하 오브젝트 묻히는 오류

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#361]
엔진 버전
: 1.56.0

오류 내용
: 안녕하세요.

최신 버전(1.56.0) 엔진으로 업데이트 후 지하에 있거나, 지하를 걸치고 있는 오브젝트가 
지형투명도를 0으로 설정했을 때 지형 아래에 있는 부분은 보이지 않는 현상이 발생합니다.

아래는 기존 사용중이던 시스템에서 최신 엔진으로 교체 및 비교 화면입니다.

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/3653f1f2-a9bc-4da9-a46f-171228a2e58f)
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/348f1bc5-d9ef-48a8-b405-f67a2dcee59e)

**Comment by hjaejae** [comment]
안녕하세요~
해당 내용은 1.52 버전 이후 변경된 내용입니다.
레이어에 지상과 지하 건물을 따로 표현 할수 있는 파라메터가 추가되었습니다.

https://github.com/EgisCorp/XDWorld/issues/297

지하도 보일 수 있게 하는 레이어의  속성을 변경해주시면 됩니다. 감사합니다.

```javascript
var layer = Module.getTileLayerList().createXDServerLayer({
        url : strURL,
	servername : strSaverName,
	name : strLayerName,
	type : 9,
	minLevel : 0,
	maxLevel : 15
});
layer.view_underground = true; // 지하도 보이게 설정
```

변경해보시고 이상이 있으시면 말씀 주세요

**Comment by kseonok** [comment]
view_underground를 true로 설정해줘도 결과가 같습니다.
참고로 해당 레이어는 타일 레이어가 아닌 오브젝트 레이어입니다!

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/e20d4999-a8c9-4357-900f-d45b8c912529)

**Comment by hjaejae** [comment]
오브젝트 레이어에서 말씀해주신 현상이 일어나는 경우는 아래의 코드를 사용했을것으로 판단됩니다.
```javascript
Module.fixedRenderOrder(true);
```

혹시 설정이 되어 있다면 false로 바꿔 주시거나 아래 코드를 사용하시면 될 것 같습니다.

```javascript
Module.setRenderOrder(true);
```

투명 값이 들어갔을 때 렌더링 순서에 따라서 보이는 모습이 달라 질 수 있습니다.
fixedRenderOrder API는 카메라의 위치가 지형 위 아래에 따라 바뀔 수 있는 상황을 고정 시키는 API이며

setRenderOrder API는 타일 레이어와 오브젝트 레이어를 고정시키는 API입니다.

**Comment by kseonok** [comment]
1. fixedRenderOrder false 설정
2. setRenderOrder true 설정
3. view_underground  true 설정
4. fixedRenderOrder true 설정 후 setRenderOrder  true 설정

위 순으로 실행해보았는데, 결과가 똑같습니다 ㅜㅜ


![image](https://github.com/EgisCorp/XDWorld/assets/118805328/e1b3b065-e106-4020-ac10-d23dc3f3d6be)

**Comment by hjaejae** [comment]
이전 답변에서 말씀 드린대로 투명 객체에 대해서는 렌더링 순서가 중요합니다.
확인해본 현재 버전에서는 투명 객체에 대한 렌더링 순서 정책이 변하여 해당 현상이 발생하였습니다.
이전과 마찬가지로 렌더링 할 수 있도록 API를 제공해드리겠습니다.

**Comment by hjaejae** [comment]
최신 릴리즈 엔진에 업데이트 하였습니다.

- JSObject::setAlphaRender(_bSet) API를 이용해 알파 렌더링 할때 입력되지 않도록 고정 할 수 있음
* true: 투명 값이 있을 시 알파 렌더링으로 입력 가능
* false : 투명 값과 상관없이 알파 렌더링으로 입력 불가
* object.setAlphaRender(false); 로 입력시 이전 방식대로 작동합니다.

**Comment by kseonok** [comment]
최신 엔진 테스트 결과, 정상작동 확인했습니다. 감사합니다!
