### ISSUE TITLE
최신 엔진 XDServer POI 가시화 오류

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#362]
엔진 버전
: 1.56.1

오류 발생 API
: XDEMapCreateLayer

오류 내용
:
안녕하세요.

XDServer로부터 POI 데이터를 호출해서 사용중이였는데, 최신엔진으로 교체 후 POI가 표출되지 않는 것 같습니다.
확인 부탁드리겠습니다!

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/a70c067e-5e59-4398-8577-243ed4caf70c)
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/dedc770c-78aa-4694-ba40-190014bdf6cf)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 오류에 대한 내용을 확인 하였습니다. 가시화 레벨이 높은 위치(10~15)에서는 POI가 정상적으로 출력되고 그 보다 낮은 POI가 미출력되는 문제를 확인하였습니다. 관련 내용을 확인하여 수정 후 업데이트 하겠습니다.

**Comment by YangHeeBong** [comment]
![image](https://github.com/EgisCorp/XDWorld/assets/82924515/be098d8d-3164-4165-9529-64b7da280319)
거리에 따른 POI 가시화 모듈을 수정완료했습니다.
오늘 오후 중으로 Hotfix 버전으로 업데이트 하겠습니다.

**Comment by YangHeeBong** [comment]
1.56.2 엔진으로 문제 해결했습니다.
