### ISSUE TITLE
카메라 3인칭 시점에서의 카메라 최소 틸트 조정 기능 방법 문의

### ISSUE THREAD

**Issue by Kiwoohyun** [EgisCorp/XDWorld#363]
엔진 버전
: 1.53.1 (Released 2023-08-04)

문의 내용
: 
안녕하세요. 
카메라가 3인칭일 때와는 달리 1인칭일 때 카메라 최소틸트 조정 함수가 먹지 않습니다.
혹시 방법이 있을까요?

---
카메라 1인칭 시점 함수 - Module.getViewCamera().setMoveMode(true)
카메라 최소틸트 조정 함수 - Module.getViewCamera().setLimitTilt(-10);

**Comment by Kiwoohyun** [comment]
https://sandbox.dtwincloud.com/code/main.do?id=camera_trace_path_moving
위 샌드박스 URL에서  타겟경로 이동같은 기능을 3인칭시점이 아닌 1인칭시점으로 구현했습니다

하지만 1인칭 시점에서 카메라 각도가 0도 보다 크면(바닥으로 향하면) 
![image](https://github.com/EgisCorp/XDWorld/assets/80441700/d560912d-b9a7-48e7-95bc-9be613b1f09b)
매우 드물지만 출력 장애가 있어서 -10도정도로 바닥을 못보도록 카메라 TILT 제한을 걸고 싶습니다
경로이동시 카메라 높이를 적당히 높히면 해결되는 거 같지만 최대한 사람눈높이 시점(바닥과 가깝게) 으로 하고 싶습니다.

3인칭시점에서의 TILT제한 기능을 1인칭시점에서도 구현할 방법이 있을까요?

**Comment by YunSumin** [comment]
안녕하세요,
문의 주신 내용을 토대로 1인칭 시점 이동 시 최소 시야 범위가 낮아 발생하는 현상이라 판단되어
1인칭 시점 이동 최소 범위를 하향 조정하였습니다.

1.57.0 버전 업데이트 내용은 이곳에서 확인하실 수 있습니다. [바로가기](https://github.com/EgisCorp/XDWorld?tab=readme-ov-file#3-1%EC%9D%B8%EC%B9%AD-%EC%B9%B4%EB%A9%94%EB%9D%BC-%EC%9D%B4%EB%8F%99-%EC%8B%9C-%EA%B0%80%EC%8B%9C%EB%B2%94%EC%9C%84-%EC%A1%B0%EC%A0%95--%EC%9D%B4%EC%8A%88-363)

최소 시야 범위를 하향 함으로써,
카메라 틸트를 낮춰 시야가 지면과 가까워지더라도 자동으로 컬링되지 않으므로
지면 아래가 출력 되는 현상을 방지하였습니다.

https://github.com/EgisCorp/XDWorld/assets/82925313/9a259194-ed53-4bfa-8931-64a55d157792

**Comment by woobbi** [comment]
감사합니다.
