### ISSUE TITLE
point object 선택 후 drag & move 기능문의

### ISSUE THREAD

**Issue by HooYoungJyeon** [EgisCorp/XDWorld#364]
엔진 버전
:1.51.1

문의 내용
:
안녕하세요. 

참고한 링크 :  https://sandbox.dtwincloud.com/code/main.do?id=object_ghostsymbol_move

샌드박스에 있는 고스트심볼 이동과 비슷하게, 선택된 poi 오브젝트를 드래그 및 위치이동 하는 기능이나 마우스모드가 있는지 궁금합니다.

sandbox상에서는 +버튼을 트리거로 사용하여 움직이는데, 이것없이도 가능한지 궁금합니다.

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 고스트 심볼 이외 마우스 모드로 오브젝트를 이동하는 기능은 제공하고 있진 않습니다. 

하지만 JSObject 구성하는 API 중 [setPosition](https://egiscorp.gitbook.io/xdworld-webgl-manual/introduce-1/object/jspoint#setposition-position-boolean)을 이용하시면 비슷한 기능을 작성 가능 합니다.

캔버스 마우스 이동 이벤트 시 마우스 좌표를 이용하여 POI를 [setPosition](https://egiscorp.gitbook.io/xdworld-webgl-manual/introduce-1/object/jspoint#setposition-position-boolean)으로 실시간 이동 처리 하시면 됩니다.

**Comment by HooYoungJyeon** [comment]
감사합니다
