### ISSUE TITLE
2d 막대그래프 벨류값 설정문의

### ISSUE THREAD

**Issue by leepulum727** [EgisCorp/XDWorld#365]
엔진 버전
: 1.55.2 (Released 2023-11-16)
문의 내용
:**2d 막대그래프 벨류값 설정(각각의 벨류 및 색상 설정)**

![image](https://github.com/EgisCorp/XDWorld/assets/73877693/e32e8521-062e-48bc-b4b5-deffb73349b1)

function create2dGraph(_data) {
	
	// 그래프 오브젝트 생성
	var graph = Module.createBarGraph("2dGraphBar");
	
	// 범례 추가
	graph.insertLegend("Legend1", "현재수위", new Module.JSColor(200, 124, 181, 236));
	graph.insertLegend("Legend2", "관심수위", new Module.JSColor(200, 67, 67, 72));
	graph.insertLegend("Legend3", "주의수위", new Module.JSColor(200, 255, 153, 000));
	graph.insertLegend("Legend4", "경계수위", new Module.JSColor(200, 255, 051, 000));
	graph.insertLegend("Legend65", "심각수위", new Module.JSColor(200, 153, 051, 204));
	
	// 데이터 추가 (데이터는 범례가 추가된 순서대로 적용됨)
	
	var lastData = _data[_data.length-1]
	
	var maxval =  lastData.srswl +2
	
	var dataValue = [
		[	lastData.wl, 
			lastData.attwl-lastData.wl,
			lastData.wrnwl-lastData.attwl,
			lastData.almwl-lastData.wrnwl, 
			lastData.srswl-lastData.almwl 
		],
		
		
	];
	
	// 데이터 셋 이름 리스트
	var dataSetName = ["현재수위", "관심", "주의", "경보", "심각"],
	
		labelTextOutlineColor = new Module.JSColor(1, 255, 255, 255),
		labelTextFillColor = new Module.JSColor(1, 255, 255, 255)
		;
	
	for (var i=0, len=dataValue.length; i<len; i++) {
		
		var data = new Module.Collection();
		
		// 데이터 정보 입력
		for (var j=0, subLen=dataValue[i].length; j<subLen; j++) {
			data.add(dataValue[i][j]);
		}
		
		// 이름, 데이터 정보로 데이터 셋 입력
		//graph.insertDataSet(_data[i].obsnm, data);
		graph.insertDataSet("", data);
		// 그래프 데이터 셋 이름 출력 옵션 설정
		graph.setDataSetNameFont(dataSetName[i], "Tahoma");	// 폰트 이름
		graph.setDataSetNameTextSize("", 10);	// 텍스트 크기
		//graph.setDataSetNameTextColor(dataSetName[i], labelTextOutlineColor, labelTextFillColor);	// 텍스트 색상
		graph.setDataSetNameTextColor(dataSetName[i],labelTextOutlineColor , labelTextFillColor);	// 텍스트 색상
	}
	
	// 최대, 최소 값 범위 설정(하단,상단,간격)
	graph.setValueRange(0.0, lastData.srswl +2, 1.0);
	
	// 단위 표시 텍스트 설정
	graph.setUnitText("(m)");
	
	// 바 상승 애니메이션 속도 설정
	graph.setAnimationSpeed(0.2);
	
	// 범례 박스 크기 설정
	graph.setLegendBoxSize(new Module.JSSize3D(5.0, 5.0, 5.0));
	
	// 데이터 셋 이름과 그래프 바 간 간격 설정
	graph.setDataSetNameInterval(0.01);
	
	// 그래프 바닥 평면 두께 설정
	graph.setFloorDepth(10.0);
	graph.setFloorColor(new Module.JSColor(150, 250, 250, 250));
		
		
	var a = wlArr.lon.split('-')
	var b = wlArr.lat.split('-')
	
	// 그래프 생성 
	graph.create(new Module.JSVector3D(DMStoDEC(a[0],a[1],a[2]), DMStoDEC(b[0],b[1],b[2]), 100.0),
				 new Module.JSSize2D(100,200),
				 1);	// 0(막대가 가로로 배열된 형태), 1(막대가 쌓인 형태) 
				 
	return graph;
}
위의 그림에는 벨류가 각각 [0.6, 0.9, 1.5, 1.0, 0.8 ]로 들어가지만
제가 표현하고 싶은 것은 [0.6, 1.5, 3.0, 4.0, 4.8] 이렇게 표현되게 하고싶습니다 
함수안의 set에는 설정하는것이 하나의 벨류 밑에 있는 타이틀 설정만 되고 있는거 같은데 각각의 벨류의 텍스트를 설정하는 것이 가능할까요

**Comment by YunSumin** [comment]
안녕하세요,

현재 2D 바 그래프의 경우
column_0 = [legend_0, legend_1, legend_2, legend_3, legend_4]
column_1 = [legend_0, legend_1, legend_2, legend_3, legend_4]
column_2 = [legend_0, legend_1, legend_2, legend_3, legend_4]

형식으로 데이터 입력이 가능합니다.

현재 입력된 상태는
column_0 = [legend_0, legend_1, legend_2, legend_3, legend_4]
와 같이 한 column에 다섯 가지의 범례 값이 포함된 것으로 확인되며,

최종적으로
column_0 = [legend_0]
column_1 = [legend_0]
column_2 = [legend_0]
column_3 = [legend_0]
column_4 = [legend_0]

형태로 표현이 필요하신 것으로 파악됩니다.

[0.6, 1.5, 3.0, 4.0, 4.8] 을 표현하고자 하신다면, 
각 값을 입력할 때 앞 값을 모두 더하여 현재 값으로 입력하시면 아래와 같이 출력이 가능합니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82925313/4096a93b-11de-41df-8dd9-fdc4e36f22d0)

위 화면은 아래의 코드로 구현되었습니다.
``` javascript
// 범례 추가
graph.insertLegend("Legend1", "상태", new Module.JSColor(200, 255, 255, 255));

// 데이터 추가 (데이터는 범례가 추가된 순서대로 적용됨)
var dataValue = [
	[0.6],
	[1.5],
	[3.0],
	[4.0],
	[4.8]
];

// 데이터 셋 이름 리스트
var dataSetName = ["현재수위", "관심", "주의", "경보", "심각"];
var labelTextOutlineColor = new Module.JSColor(255, 0, 0, 0);
var labelTextFillColor = new Module.JSColor(255, 255, 255, 255);
```

현재 파악된 기능이 이와 다르거나, 
추가로 문의가 있으신 경우 말씀 부탁 드립니다.

감사합니다.

**Comment by leepulum727** [comment]
답변 감사합니다.  하나의 컬럼 안에서 표현하려는데 현재 엔진에선 하나의 막대 안에서는 표현이 불가능한 걸까요?
현재 불가능하다면  컬럼 안의 텍스트 설정할 수 있는 기능이 추가 가능한지 궁금합니다.

**Comment by YunSumin** [comment]
현재 컬럼 내 밸류 값 표시 on/off 기능은 없으나 구현은 가능합니다.
다음 엔진 업데이트에 반영하여 다시 안내 드리겠습니다.

**Comment by hjaejae** [comment]
프록시 관련 이슈로 인한 렌더링 중 Abort 현상은 최신 엔진에서 1차적으로 작업을 한 상태입니다.
최신 엔진에서 다시 테스트 해보시고 이상이 있으시면 다시 작업 조치를 할 예정입니다. 

프록시 관련 이슈를 테스트 했을 때 Request 수가 많아지고 그걸 프록시 서버에서 처리를 하지 못해서 발생하는 현상으로 생각됩니다.

옵션 클래스에 SetMaxRequestTileMeshSize(...) API를 사용 중이시라면 해당 값을 1로 테스트 해보시거나 값을 줄여서 테스트 해보시길 바랍니다.

**Comment by YunSumin** [comment]
2D 그래프 컬럼 밸류 텍스트 가시화 on/off 기능이 추가되어 안내 드립니다. [바로가기](https://github.com/EgisCorp/XDWorld?tab=readme-ov-file#2-2d-%EB%B0%94-%EA%B7%B8%EB%9E%98%ED%94%84-%EA%B0%92-%EA%B0%80%EC%8B%9C%ED%99%94-%EC%84%A4%EC%A0%95-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0%EA%B0%80-%EC%B6%94%EA%B0%80--%EC%9D%B4%EC%8A%88-365)

JSBarGraph의 프로퍼티 columnValueVisible, totalColumnValueVisible 를 사용하여
컬럼 내 밸류 텍스트 가시화를 설정할 수 있습니다.

columnValueVisible는 컬럼 중간 범례 별 밸류 텍스트를 가시화하는 옵션이며
totalColumnValueVisible는 컬럼 최상단 총 밸류 텍스트를 가시화 하는 옵션입니다.

* 컬럼 단위 값 가시화 설정
    ``` javascript
    graph.columnValueVisible = false;
    ```
* 총 단위 값 가시화 설정
    ``` javascript
    graph.totalColumnValueVisible = false;
    ```
