### ISSUE TITLE
wms 이미지 로드 후 호출 가능한 콜백함수

### ISSUE THREAD

**Issue by youkkang** [EgisCorp/XDWorld#366]
let slopeoption = {
url: strUrl,
layer: strLayer,
minimumlevel: numMinlevel,
maximumlevel: numMaxlevel,
tilesize: numTileSize,
crs: strCrs,
parameters: {
version: strVersion
}
};
wmslayer = layerList.createWMSLayer(layer_nm)
wmslayer.setWMSProvider(slopeoption);
wmslayer.setBBoxOrder(bBox);
}

로 wms 레이어 호출후, 호출이완료(이미지 로드 완료) 돼면
부를수 있는 콜백함수가 있을까요?

또 wms로 불러온 레이어의 객체 클릭이벤트 기능도 알려주시면 감사하겠습니다 :)

**Comment by hjaejae** [comment]
1. 현재 WMS 호출이 완료된 후 부를 수 있는 콜백 함수는 없습니다.
- 3차원 특성상 WMS 데이터를 잘라서 불러오게 되는데 그 요청 수가 한번에 보통 100개 이상이고 카메라 이동 할 때마다 재요청을 하게 됩니다. 그래서 WMS의 요청 완료에 대한 콜백 함수 기능을 구형하지 않았습니다.
2. WMS로 불러온 레이어의 객체는 이미지 형태이고 그 이미지가 지형에 결합하는 방식이라 객체 클릭이라는 구조상 맞지 않아 클릭 이벤트가 존재하지 않습니다.
