### ISSUE TITLE
영상지도 결함

### ISSUE THREAD

**Issue by woobbi** [EgisCorp/XDWorld#367]
엔진 버전
: 1.56.2 (Released 2023-12-21)

오류 발생 API
: Module.WMTS()

오류 내용
: 영상지도 관련하여 결함이 있습니다.

- 국토정보플랫폼 문제라고 하기에는 관련지도쪽으로 너무 자주 결함이 발생하는거같습니다.
![image](https://github.com/EgisCorp/XDWorld/assets/116481100/fc309a3d-197a-4c1e-9a53-94e0e9d39762)

![image](https://github.com/EgisCorp/XDWorld/assets/116481100/c18f4689-f474-4cdd-bab2-b24d03655b1e)

- 대안으로 xdworld 기존으로 깔려있는 지도를 쓰기에는 tile이 너무 흐립니다. (tile명 = 'tile_mo_HD')
어떤 연관인진 모르겠지만 tile이 흐리니 그위에 올라가는 오버랩한 이미지 및 바닥레이어(조감도) 도 같이 흐립니다.

- 따로 제공받은 지구별 tile 레이어 기준으로는 오버랩한 이미지는 흐리진 않지만 바닥레이어는 여전히 흐립니다.

- 정상적인 지도를 쓰고싶은데 방법이 있을까요?

(샌드박스 샘플코드와는 달리 tile명 = 'tile'이라는 tile을 쓰니 오버랩한 이미지 및 바닥레이어 흐림현상이 없어졌습니다. 해당방법이 맞을까요?)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

### 일단 초기 질문하신  "영상지도 관련하여 결함이 있습니다. 국토정보플랫폼 문제라고 하기에는 관련지도쪽으로 너무 자주 결함이 발생하는거같습니다."

에 대해 답변드리고 하단에 질의하신 3가지에 대해 답변드리겠습니다.

먼저 영상지도 관련 결함에 대해 답변드리겠습니다. 일단 아래 그림을 보시면

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/4f6f788d-2abf-4765-ac69-7bd8a4cd6049)

왼쪽은 현재 엔진에서의 가시화 상태이고, 오른쪽은 GeoServer에서의 가시화 상태입니다. 두 이미지에서 볼 수 있는 공백 영역을 통해 북한 지역에 픽셀 이미지 데이터가 없는 지형 영상임을 알 수 있습니다. 이 데이터를 지도와 연동할 경우, 북한 지역의 데이터가 없어 왼쪽 이미지와 같은 공백이 표현됩니다. 즉, 이 데이터는 전 세계를 포괄하는 것이 아니라 특정 지역에 한정된 데이터임을 알 수 있습니다. 이 문제를 해결하기 위한 두 가지 방법은 다음과 같습니다

- 1. 공백 영역처리를 위한 후 처리 가공
- 2. 하이브리드 데이터로 가공 후 불러오는 방법

### 두 번째 질문에 대한 답변입니다  "대안으로 xdworld 기존으로 깔려있는 지도를 쓰기에는 tile이 너무 흐립니다. (tile명 = 'tile_mo_HD') 어떤 연관인진 모르겠지만 tile이 흐리니 그위에 올라가는 오버랩한 이미지 및 바닥레이어(조감도) 도 같이 흐립니다."에 대한 답변이니다.

지형 영상에서 사용되는 'image.name'에 사용되는 옵션은 크게 3가지입니다.

먼저, 'tile_mo_HD', 'tilme_mo' 는 모바일에서 사용하는 경량 이미지 데이터입니다.
- tile_mo : 모바일 용 일반 영상 이미지(최대 16레벨 지형 영상 지원)
- tile_mo_HD : 모바일 용 영상 이미지(최대 14레벨 지형 영상 지원)
- tile : 일반 영상 이미지(최대 16레벨 지형 영상 지원)

이미지에 따른 영상 품질은 아래와 같습니다. (왼쪽 tile_mo_HD, 오른쪽 tile)

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/29289bb2-0b2e-44cb-9508-b5caa3ffda72)
![image](https://github.com/EgisCorp/XDWorld/assets/82924515/8f47d9fb-3b42-4cf2-b39a-ec6c42395b67)

고품질을 원하시면 'tile' 항목을 사용하시길 권장합니다.

또한 '흐리다'는 표현은 이미지의 정밀도에 관한 것 같습니다.

영상 이미지의 15레벨 타일 기준으로, 가로와 세로의 길이는 약 78m에서 97.5m입니다.
- tile_mo: 최대 16레벨 지형 영상 지원 (가로 세로: 약 39m~48.75m)
- tile_mo_HD: 최대 14레벨 지형 영상 지원 (가로 세로: 약 156m~195m)
- tile: 최대 16레벨 지형 영상 지원 (가로 세로: 약 39m~48.75m)
이에 따라 'tile_mo_HD'는 'tile'보다 이미지가 업스케일링되어 흐릿해짐을 알 수 있습니다.

### 세 번째 질문에 대한 답변입니다. '따로 제공받은 지구별 타일 레이어를 기준으로 하면, 오버랩된 이미지는 흐리지 않지만 바닥 레이어는 여전히 흐립니다.' 

바닥 레이어가 정확히 어떤 의미인지 확실하지 않습니다. 영상 이미지를 말씀하시는 건가요?
따로 제공받은 지구별 타일 레이어는 어떤걸 이야기 하시나요?? 'tile'에 대한 이야기 인가요?
질문에 대한 정보가 너무 부족합니다.

### 네 번째 질문에 대한 답변입니다. '정상적인 지도를 사용하고 싶은데, 어떤 방법이 있을까요?'
여기서 말씀하시는 '정상적인 지도'가 구체적으로 무엇을 의미하는지, 반대로 '비정상적인 지도'는 어떤 의미인가요?

**Comment by woobbi** [comment]
**첫번째 질문**

해당부분은 북한지역이 맞지만 제가말한 부분은 파주시부분입니다.

![image](https://github.com/EgisCorp/XDWorld/assets/116481100/60ef198b-f784-489a-b620-aeb9a9508eb2)

![image](https://github.com/EgisCorp/XDWorld/assets/116481100/83e7e6a9-4fcc-4c18-a92c-c110cf45905a)

**두번째 질문~네번째 질문**

정상적인 지도는 위에 질문처럼 파주시도 표출되며 흐리지 않은 tile표출을 말하는거였습니다. 
mo가 mobile의 mo였군요... 
pc 웹사이트에서 표출할거라 tile을 쓰면 될거같습니다. 자세한 답변 감사합니다.
