### ISSUE TITLE
지하에 있는 오브젝트 선택표시가 안되는 문제

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#368]
엔진 버전
: 1.54.1

오류 발생 API
: 

오류 내용
:
안녕하세요!

지형 아래에 레이어를 표출하고 오브젝트별로 선택이 되는 기능을 구현 중입니다.
지형 위에 있는 경우엔 오브젝트 선택 표시가 잘 보이는데,
지형 아래에 레이어를 생성하고 선택하게되면 선택 표시가 안보이고 오브젝트가 사라지고 있습니다.
![image](https://github.com/EgisCorp/XDWorld/assets/88410545/ff6900ee-1534-4890-bb46-129534aeff81)

해당 레이어에 view_underground 옵션은 true로 적용한 상태인데.. 혹시 따로 적용해줘야하는 옵션이 있을까요??

**Comment by YunSumin** [comment]
안녕하세요, 문의하신 내용을 정확히 확인하기 위해 질문 드립니다.

문의하신 오브젝트가 서버를 통해 요청되는 타일 파이프 레이어인지,
아니면 JSPipe를 이용하여 구현된 오브젝트 타입 레이어인지에 대한 정보가 필요합니다.

나타나는 현상은

1. 지형 아래에 파이프 오브젝트 생성
2. 지형 아래에 위치하는 파이프 클릭
3. 파이프가 보이지 않는 현상 발생
4. 파이프 선택 해제 시 다시 보임

으로 파악됩니다. 맞으신가요?

**Comment by YunSumin** [comment]
JSPipe를 활용한 오브젝트 타입 레이어 전제로 해당 현상을 수정하여,
1.57.1 버전 업데이트 반영하였습니다.  [바로가기](https://github.com/EgisCorp/XDWorld/tree/main?tab=readme-ov-file#1571-202415)

https://github.com/EgisCorp/XDWorld/assets/82925313/911356b9-e7d9-44fc-a7d4-5d65843266c7

**Comment by giyoon99** [comment]
확인이 늦어서 죄송합니다 ㅜㅜ
JSPipe 타입이 맞고, 엔진 업데이트 후 확인해보니 정상 작동 합니다! 감사합니다!!

**Comment by YunSumin** [comment]
첨부 드린 영상은 마우스 선택 전
마우스 모드를 Module.MML_SELECT_POINT로 지정하였으며,
레이어 속성 중  view_underground 속성을 true로 설정하였습니다.

참고하시어 설정된 속성 확인 부탁 드립니다.
