### ISSUE TITLE
ColorPolygon 사용시 toLonLatArray() 배열 순서 문의 및 기능 추가 문의

### ISSUE THREAD

**Issue by Young-Ju98** [EgisCorp/XDWorld#369]
엔진 버전
: 0.56.8 (Released 2023-12-27)

문의 내용
: 안녕하세요~ createColorPolygon을 이용해서 개발을 진행하고있는데 하단 [사진2]처럼 ColorPolygon을 생성한 뒤 toLonLatArray()로 좌표값을 확인 시 [사진1]처럼 8개의 좌표값을 받는데 각 8개의 좌표가 사진 2에서 어느 위치에 해당하는지 알 수 있을까요?

그리고 혹시 BarGraph3D처럼 ColorGrid3D도 setAnimationSpeed() 기능을 추가해주실 수 있나요?

[ 사진1 ]
![image](https://github.com/EgisCorp/XDWorld/assets/109942684/1d0c9001-8f63-4088-aa73-04fc0f85296c)

[ 사진2 ]
![image](https://github.com/EgisCorp/XDWorld/assets/109942684/578b911c-df70-4dcf-b650-85dc1f0d5880)

**Comment by Young-Ju98** [comment]
사진이 안뜨는 것 같아서 사진만 다시 올려요..!
[ 사진 1 ]
![image](https://github.com/EgisCorp/XDWorld/assets/109942684/361ffa69-00bd-48dc-bfb2-d35422da2251)

[ 사진 2 ]
![image](https://github.com/EgisCorp/XDWorld/assets/109942684/f7987e1e-5687-4c73-9c4d-ca51049ce09f)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

### " createColorPolygon을 이용해서 개발을 진행하고있는데 하단 [사진2]처럼 ColorPolygon을 생성한 뒤 toLonLatArray()로 좌표값을 확인 시 [사진1]처럼 8개의 좌표값을 받는데 각 8개의 좌표가 사진 2에서 어느 위치에 해당하는지 알 수 있을까요?"

폴리곤의 다음과 이미지와 같이 생성 되었다면

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/69433d72-dc11-4e28-89d7-d680cc129d23)

다음과 같은 기준으로 좌표점을 반환 하게 됩니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/afb89572-c073-45b4-9a1f-e379a38e69d5)

반환 기준은 OpenGL 또는 DirectX의 기본 그리기 단위(점, 선, 면) 중 면을 기준으로 하며, 이 면은 최소 3개의 점으로 구성된 삼각형으로 반환된 기준점은 초기에 입력한 정점 순서와 삼각분할([관련 내용 링크 참조](http://yoonhada.com/?p=774))에 영향을 받습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/ae9efa28-f4f3-456f-b9fb-53e7791c7d78)

이미지처럼 입력 순서와 방향에 따라 반환되는 toLonlatArray() 값은 달라집니다. 저희 쪽에서 특정 방향을 기준으로 인덱스를 정렬한 후 데이터를 반환할 때, 이 정보를 기준으로 새로운 객체를 생성하면 다른 형태가 출력됩니다. 그러므로 인덱스 정렬을 변경하기는 어렵습니다.

질문에 첨부하신 이미지를 통해 얻을 수 있는 정보가 너무 단편적입니다. 

단순히 colorPolygon 구성을 단일로 처리 하신건지 여려개의 colorPolygon으로 구성하신건지 판단이 어렵습니다.
이미지를 통해 제가 이해한 내용은 다음과 같습니다.

질문의 통해 이해한 내용
1. 4개의 colorPolygon으로 구성되어 있다.
2. 4개의 colorPolygon은 다음과 같은 구성이다.
  - 심각 수위 객체
  - 주의 수위 객체
  - 경계 수위 객체
  - 관심수위 객체
3. 주의 수위의 8개 점에 대한 위치 반환을 원한다.
4. 주의 수위 colorPolygon Class을 통해 toLonlatArray()을 반환 받아 8개 점을 추출
5. 추출된 8개 점이 주의 수위 객체 위치와 다르다??

8개의 정점의 위치가 주의 수위 객체의 실제 좌표와 다른 것인가요. 아니면 다른 이유가 있는 것인가요?
4개의 colorPolygon이 아닌 1개의 colorPolygon으로 작성되었다면 8개 정점 중  고도가 가장 낮은 4개의 점과 입력하신 높이를 적용하면 특정 높이에 대한 객체의 높이 반환은 가능할 것으로 예상됩니다. 하지만 이 방법으로는 처리가 불가능한가요?

만약 질의에 대한 기본적인 환경, 생성 입력 정보, 반환 결과 등과 같은 상세한 내용이 있으면 더 정밀한 답변이 가능할 것 같습니다.

### "BarGraph3D처럼 ColorGrid3D도 setAnimationSpeed() 기능을 추가해주실 수 있나요?"

제가 알고 있는 ColorGrid3D은 아래 그림과 같습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/86febaa8-3649-4541-aed3-207f681acaa3)

이 ColorGrid3D는 애니메이션이 불가능합니다. 그 이유는 속도 향상을 위해 처리된 부분이 존재하기 때문입니다. BarGraph3D는 객체가 적고 렌더링을 통해 높이를 조절하여 각각의 오브젝트로 처리가 가능하지만, ColorGrid3D를 BarGraph3D와 같은 방법으로 사용할 경우 속도가 급격히 느려지는 문제가 발생하여, 그리드로 구성된 데이터 표현이 불가능합니다. 하지만 비슷한 기능을 찾고 계시다면 [시계열 바 참조](https://sandbox.dtwincloud.com/code/main.do?id=effect_time_bar)를 참조하시기 바랍니다."

**Comment by Young-Ju98** [comment]
index: [0, 1, 2, 0, 2, 3]이 방식으로 colorPolygon을 생성한 상태였습니다. 좌표값에 대해서는 다른 방식으로 확인하였습니다!
답변주셔서 감사합니다~
