### ISSUE TITLE
AngleLeft(), AngleRight() 있는지 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#37]
Version 1.3.15.7.2 (2021-06-14)

안녕하세요. 바이브컴퍼니입니다.

api에서 AngleUp(), AngleDown()은 찾았습니다.
근데, AngleLeft(), AngleRight() 기능은 보이지 않던데...

**해당 기능을 하는 api가 있습니까?**

**Comment by YangHeeBong** [comment]
네 해당 API는 

Module.getViewCamera().RotateRight()
Module.getViewCamera().RotateLeft()

입니다.

**Comment by HyunSeongKil** [comment]
카메라가 바라보고 있는 벡터 방향으로 위 아래 좌 우 회전 시키려고 합니다(예: 쿼터니언)

rotate와는 다른 기능입니다.

**Comment by YangHeeBong** [comment]
AngleUp(), AngleDown()은 1인칭 회전으로 RotateRight(), RotateLeft()도 1인칭 회전입니다.

원하시는 이야기가 아래 그림처럼 3인칭 회전을 이야기 하시는 것 같습니다.

![image](https://user-images.githubusercontent.com/82924515/122184606-5aac7f00-cec7-11eb-83e8-4999eac71954.png)

현재 기본 마우스 이벤트가 3인칭 회전으로 현재 API로 3인칭 회전은 없습니다. 추후 API추가 하여 공지하겠습니다.

**Comment by loeaf** [comment]
right left가 다른거 같아요 혹시 right left 값할때 어떤 축을 회전시키나요??? 확인하니 roll값이 회전하는거 같지는 않습니다 ㅎㅎ...

**Comment by HyunSeongKil** [comment]
이 그림에서 z추가, yaw입니다.

![image](https://user-images.githubusercontent.com/38479834/122188294-c9d7a280-ceca-11eb-9f77-b70962ff69ab.png)

**Comment by YangHeeBong** [comment]
네 right left는 Z축(Yaw)으로 회전 up, down은 Y축(pitch)입니다

**Comment by HyunSeongKil** [comment]
네
그럼, Rotate left/right가 z축 회전이라는 말씀이신건가요?

실행화면인데....그럼 이게 맞는건가요???

https://user-images.githubusercontent.com/38479834/122189590-02c44700-cecc-11eb-92c2-e7ad94547391.mp4

**Comment by YangHeeBong** [comment]
아무래도 Top View에서 기능을 동작하셨어 오해의 소지가 있는 것 같습니다.
카메라 Pitch를 조금 내려서 확인하시면 정확히 판단  하실 수 있을 것 같습니다

**Comment by HyunSeongKil** [comment]
흠...

pitch내리니깐 원하는 그림이 나오네요...

top view에서는....어쩔 수 없는 건가.... ㅠㅠ


하여튼
고맙습니다.
해결 되었습니다.

**Comment by YangHeeBong** [comment]
넵 수고하셨습니다 ㅎ
