### ISSUE TITLE
gpuTextureOverflow 오류 문의

### ISSUE THREAD

**Issue by eeeeekl** [EgisCorp/XDWorld#371]
엔진 버전
: 1.54.0

오류 발생 API
:

오류 내용
:  안녕하세요. 
모델링 표출할 때 **gpuTextureOverflow** 오류에 대해서 문의드립니다.
현재 교량 모델의 크기는 이미지 참고 부탁드립니다.
![clipboardImage_24_0105_142052_400](https://github.com/EgisCorp/XDWorld/assets/145413670/03fd9ef4-cbb6-4840-80ec-cb2569235179)
![img](https://github.com/EgisCorp/XDWorld/assets/145413670/14b026d6-8da9-47e8-a8fb-ef1b1fd66b0a)

![image](https://github.com/EgisCorp/XDWorld/assets/145413670/6be173d9-9c0b-44d2-96c1-b173e02fbe3b)
API를 활용하여
![image](https://github.com/EgisCorp/XDWorld/assets/145413670/b877f405-d76a-4340-be22-e803e40e2885)로 설정을 해보았지만 여전히 똑같은 오류가 발생합니다.
텍스쳐 확장자는 textureExt : "dds"  로 지정해두었습니다.

전체 교량의 텍스쳐의 품질을 선명하게 하기 위해서 어떤방법을 써야하는지 문의드립니다!

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

먼저 'gpuTextureOverflow' 로그가 나타나는 이유는 현재 전체 사용 중인 텍스처의 가용 메모리를 넘었을 경우 발생하는 위험 경고 로그입니다.

좀 더 상세하게 설명 드리면, 엔진에서 화면을 가시화하기 위해 GPU 메모리에서 현재 사용되고 있는 이미지 용량이 설정된 용량을 초과한 경우에 발생하는 로그입니다.

이미지에 사용되는 항목은 다음과 같습니다:
 - 지형 이미지
 - 건물 LOD 이미지
    - 건물은 여러 단계 LOD 이미지가 존재하므로 하나의 XDO 파일은 최소 1개 부터 최대 4개로 이미지로 구성
 - POI 심볼 이미지 등등...

기본적으로 512MB로 설정되어 있으며, 질문에서 새로 설정하신 용량은 2GB로 보입니다. 하지만 현재 화면 가시화를 위해 이미지에서 사용된 GPU 메모리가 2GB를 초과한 것 같습니다. 그래픽 카드 성능에 따라 가용 메모리가 다르므로, GPU 가용 메모리가 부족한 PC에서는 로그가 발생하기 전에 시스템이 멈출 수 있습니다. 따라서 좀 더 작은 이미지를 사용하시면 로그 관련 문제를 해결할 수 있을 것 같습니다.

**Comment by YangHeeBong** [comment]
교량에서 실제로 사용되는 이미지는 질문하신 이미지로 구성된 경우, 회색 부분(교량 이미지 제외)이 전부 포함되어 있어 한 픽셀당 4바이트의 정보를 가지게 되므로 용량이 크게 증가합니다.

실제 교량을 가공할 때는 질문에 포함된 이미지 형태가 아닌, 공백이 적은 이미지로 생성됩니다.

현재 이 문제는 단순히 교량 이미지의 문제인지, 전체적으로 사용되는 이미지의 문제인지에 대해 이미지 관련 검수 작업을 권장드립니다

**Comment by hjaejae** [comment]
안녕하세요~ 위에서 설명 드린봐와같이 gpuTextureOverflow 표시가 되는 부분은 경고의 메세지 입니다.
경고 메세지를 띄우지 않게 하기 위한 설정이 가능합니다.
```javascript
Module.getOption().setTextureCapacityLimit(false);
```

위 코드로 사용하시면 메세지가 발생하지 않습니다.
