### ISSUE TITLE
하이브리드 타일 레이어 가시화 문의

### ISSUE THREAD

**Issue by Parster** [EgisCorp/XDWorld#372]
엔진 버전
: 1.57.0 (Released 2023-12-29)

문의 내용
:
안녕하십니까

하이브리드 타일 레이어(레이어 타입 10번) 을 사용하려고 합니다.

현재 하이브리드 레이어의  레벨은 0~15까지 생성 되어 있습니다.

하이브리드 레이어 위치의 dem과 tile이 6레벨까지밖에 없습니다.
 
하이브리드레이어를 15레벨까지 올릴 수 있는 방법이 있을까요?

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

하이브리드 데이터는 지형 데이터에 종속적인 데이터입니다. 

즉 아래와같은 구조를 가지고 있습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/23adf9d8-bb18-40dc-9115-043238ad9b7f)

만약 지형 데이터가 없고 Hybrid 데이터만 가시화 시 지구본 내부가 보여주는 형태로 나타나게 됩니다.

현재 이야기 하신 내용은 WMTS에 가까운것같습니다.

**Comment by Parster** [comment]
XDSERVER에 발행된 하이브리드 레이어를 WMTS로 올리면 된다는 뜻인가요 ?

**Comment by YangHeeBong** [comment]
먼자 WMTS와 HYBRID에 차이점을 아셔야 할 것같습니다. 

이미지 HYBRID 데이터는 선을 제외한 내부 투명 데이터를 포함한 이미지입니다.

단순히 WMTS로 만든 경우 투명처리 때문에 지구본 내부가 보이기 떄문에 WMTS나 지형 영상 가공처럼 만드셔야합니다.

**Comment by Parster** [comment]
넵 제 설명이 어려웠나보네요 .
![image](https://github.com/EgisCorp/XDWorld/assets/86399390/60a65043-4ab7-462b-8407-3b82d7b4e6b5)
10번레이어로 사용하고 있고 
가능한지 여쭤봤습니다 .

하이브리드 이미지데이터로 내부 투명한 선이나 폴리곤이 아니라 이미지를 서비스하고 있습니다.

일부지역만 서비스 할려고 합니다.
![image](https://github.com/EgisCorp/XDWorld/assets/86399390/60a65043-4ab7-462b-8407-3b82d7b4e6b5)


타일과 DEM 레벨보다 높게 올릴 수 있는지 여쭤봤습니다.

**Comment by Parster** [comment]
해당지역을 기본타일이 아니라 하이브리드 이미지로 서비스하려는 이유는 

이미 타일이 전국단위로 가공되어 있고 

로그인한 특정 인원에게만 보여 줘야 합니다.

**Comment by avamk2** [comment]
안녕하세요

이미지를 기본형과 다르게 하이브리드로 분리해서 서비스 해야되는 사유가 어떻게 되는가요?
베이스이미지 서비스 부분에 통합하는 것도 방법으로 보여서요

**Comment by Parster** [comment]
해당지역을 기본타일이 아니라 하이브리드 이미지로 서비스하려는 이유는

이미 타일이 전국단위로 가공되어 있고

로그인한 특정 인원에게만 보여 줘야 합니다.

**Comment by avamk2** [comment]
서비스할때 혹시 "특정 인원"이  권한 받은 유저는 "특정 지역(예: 광주)"에 "특정 유저(광주 권한 부여)"랑 매칭해서 서비스해야 되는가요?
아니면 고해상도 접근 권한으로 "특정 인원"을 핢 수 있는가요?

후자인경우는 엔진의 API를 통해서 지형의 최대레벨 조정으로 할 수 있어 보입니다.

**Comment by Parster** [comment]
서비스 내용은 전자입니다.

그래서 하이브리드로 서비스해서 권한 받은 유저에게만 특정지역을 ON/OFF 가능하도록 하려고 합니다.

**Comment by avamk2** [comment]
저희가 Github로는 현재 기능에 대한 단순 개선 또는 버그 수정등에 대한 수행과 가이드만 해드립니다.
기능에 대한 추가 개발건에 대해서는 개발여부 및 일정을 기재하지 않으니 따로 연락을 해주시기 바랍니다.

**Comment by Parster** [comment]
넵 테스트해 봐주셔서 감사합니다 . 
개발 부탁드릴 일 생길시 따로 연락드리겠습니다.
