### ISSUE TITLE
Module.createHTMLObject()를 이용해 생성한 object에 수직선 기능

### ISSUE THREAD

**Issue by Young-Ju98** [EgisCorp/XDWorld#374]
엔진 버전
: 1.57.0 (Released 2023-12-29)

문의 내용
: 안녕하세요. Module.createHTMLObject()를 이용해 생성한 object도 하단의 사진1처럼 Module.createMultiPoint()의 setBar()나 Module.createPoint()의 setPositionLine()과 같은 수직선을 긋는 기능이 있을까요? 또한 그 수직선이 점선으로 그려지는 기능도 가능할까요??

[ 사진 1 ]
![image](https://github.com/EgisCorp/XDWorld/assets/109942684/7ddda61a-e448-443c-b67e-cb961c2ef0cb)

**Comment by YunSumin** [comment]
안녕하세요,

HTML Object 는 수직 라인 표시 기능을 제공하고 있지 않으나,
HTML Object 중점에서 시작하는 수직 라인을 생성하여
동일한 화면을 구현하실 수 있습니다.

아래는 샌드박스의 HTML Object 생성 코드를 수정하여 수직 라인을 구현한 화면입니다.
왼쪽 코드박스에서 라인 객체를 구현한 부분을 확인하실 수 있습니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82925313/dbd658d1-1155-4ff1-ab12-5b4b70346ced)

샌드박스 코드 중
함수 createDivObject를 아래와 같이 변경하여 구현하였으며,
- HTML Object 좌표
- HTML Object 좌표에서 같은 경위도이면서 고도가 더 아래인 좌표

두 좌표를 활용하여 수직한 라인을 생성합니다.

``` javascript
function createDivObject() {

    var layerList = new Module.JSLayerList(true);
    let layer = layerList.createLayer("HTML_OBJEC_LAYER", Module.ELT_POLYHEDRON);//일반
    layer.setMaxDistance(10000);

    // HTHL Object 위치
    var position = [129.13782351349964, 35.17887462859219, 1500.0];
    
    let element = document.createElement("div");
    let parameter = {
        position: new Module.JSVector3D(position[0], position[1], position[2]),  // HTHL Object 위치 좌표 적용
        container: "divcontainer",
        canvas: Module.canvas,
        element: element,
        verticalAlign: "middle",
        horizontalAlign: "center",
    };
	
    let object = Module.createHTMLObject("div_object");
    let complet = object.createbyJson(parameter);
    if (complet.result == 1) {
        layer.addObject(object, 0);
        createUI(element);		
    }
    
    // 아래부터는 새로 추가된 코드입니다. 수직 라인을 생성 후 저장합니다.
    let line_layer = layerList.createLayer("HTML_OBJEC_LAYER", Module.ELT_3DLINE);
    line_layer.setMaxDistance(10000);
    
    var line = Module.createLineString("div_object_line");
    line.createbyJson({
        coordinates : {
            coordinate : [
                position, // HTML Object 중심점 (라인 시작 지점)
                [position[0], position[1], 0.0]  	// 지면 (라인 끝 지점)
            ],
	        style : "XYZ"
	    }
     });
    line_layer.addObject(line, 0);
}
```

라인이 오브젝트와 동일한 거리에 가시화되어야 하므로
라인이 저장된 레이어와 HTML Object가 저장된 레이어의 minDistance, maxDistance값을 동일하게 설정하였습니다.

**Comment by Young-Ju98** [comment]
알려주신걸로 해보니까 해결됐어요! 답변주셔서 감사합니다~!
