### ISSUE TITLE
MML_RETURN_ANALYSISPOS 마우스모드의 클릭 문의드립니다.

### ISSUE THREAD

**Issue by 18kiku** [EgisCorp/XDWorld#376]
엔진 버전
: 1.57.1 (Released 2024-1-5)

문의 내용
:

안녕하세요.
카메라 각도를 90도 수직으로 바라보게 하고 마우스모드를 MML_RETURN_ANALYSISPOS로 설정하고 클릭 시
화면에서 클릭한 부분이 아닌 다른 위치가 클릭됩니다.
제가 클릭한 부분은 건물이 없는 도로였는데 클릭 시 생기는 노란 점은 다른 위치의 고도가 높은 곳에 생성되었습니다.
축소할수록 클릭한 위치와 반환하는 좌표의 차이가 커지는데 카메라의 위치와 관련이 있는건가요?

아래는 테스트에 사용한 코드입니다.

```
Module.XDSetMouseState(Module.MML_RETURN_ANALYSISPOS);
canvas.addEventListener("Fire_EventAnalysisPos", function(e){
		console.log(e.lon, e.lat, e.alt);
		createPOI(e.lon, e.lat, e.alt)
})
function createPOI(lon, lat, alt) {

	// POI 오브젝트를 추가 할 레이어 생성
	var layerList = new Module.JSLayerList(true);
	var layer = layerList.createLayer("POI_TEST", Module.ELT_3DPOINT);

	// TEXT POI
	var poi_with_text = Module.createPoint("POI_WITH_TEXT");
	poi_with_text.setPosition(new Module.JSVector3D(lon, lat, alt));
	poi_with_text.setText("TEXT");
	layer.addObject(poi_with_text, 0);

	// Image POI
	var img = new Image();
	img.onload = function() {

		// 이미지 로드 후 캔버스에 그리기
		var canvas = document.createElement('canvas');
		var ctx = canvas.getContext('2d');
		canvas.width = this.width;
		canvas.height = this.height;
		ctx.drawImage(img, 0, 0);

		// 이미지 POI 생성
		var poi_with_image = Module.createPoint("POI_WITH_IMAGE");
		poi_with_image.setPosition(new Module.JSVector3D(lon, lat, alt));
		poi_with_image.setImage(ctx.getImageData(0, 0, this.width, this.height).data, this.width, this.height);
		this.layer.addObject(poi_with_image, 0);
	};
	img.layer = layer;
	img.src = "/static/images/3dtool-N.png"

	// Text & image POI
	var img = new Image();
	img.onload = function() {

		// 이미지 로드 후 캔버스에 그리기
		var canvas = document.createElement('canvas');
		var ctx = canvas.getContext('2d');
		canvas.width = img.width;
		canvas.height = img.height;
		ctx.drawImage(img, 0, 0);

		// 이미지 POI 생성
		var poi_with_text_n_image = Module.createPoint("POI_WITH_IMAGE");
		poi_with_text_n_image.setPosition(new Module.JSVector3D(lon, lat, alt));
		poi_with_text_n_image.setImage(ctx.getImageData(0, 0, this.width, this.height).data, this.width, this.height);

		// 텍스트 설정
		poi_with_text_n_image.setText("TEXT");

		this.layer.addObject(poi_with_text_n_image, 0);
	};
	img.layer = layer;
	img.src = "./data/map_pin.png"
}
```

![image](https://github.com/EgisCorp/XDWorld/assets/98327681/933ec396-0b82-4bcb-90e3-e26579bd9cf5)

**Comment by hjaejae** [comment]
안녕하세요~
제공해주신 소스를 활용하여 테스트를 진행해 보았습니다.
테스트 결과는 아래와 같이 이상이 없는 것으로 판단됩니다.

1. 클릭 위치
![20240122_085906](https://github.com/EgisCorp/XDWorld/assets/82991868/dbf78871-3d93-4ba5-8d6a-d555208a8f59)

2. POI 생성
![20240122_085930](https://github.com/EgisCorp/XDWorld/assets/82991868/c92231ce-b627-48f8-bbfc-57c783cd9f44)


혹시 투명한 객체가 생성되어있거나 클릭하는 지점과 카메라 사이에 다른 객체가 존재하나요?

POI 생성 위치와 클릭시 반환되는 위경도 좌표의 차이를 알 수 있을까요?

**Comment by 18kiku** [comment]
안녕하세요~

클릭한 지점에는 ELT_3DLINE 타입의 레이어가 존재합니다
확인해보니 레이어가 있는 위치에서는 공중이 클릭되어 다른 지점의 좌표를 반환하고
레이어가 없는 위치에서는 올바르게 지면의 좌표를 반환하고있습니다.

레이어를 꼭 깔아놔야 하는데 모든 레이어를 무시하고 클릭한 지면의 좌표를 얻을 수는 없나요?

**Comment by hjaejae** [comment]
ELT_3DLINE 레이어 타입에
layer.setSelectable(false); 를 이용하여 선택이 안되게 설정하시고 사용해보시기 바랍니다.

**Comment by 18kiku** [comment]
https://sandbox.dtwincloud.com/code/main.do?id=object_line_Json
https://sandbox.dtwincloud.com/code/main.do?id=object_point_text

두 예제를 참고하여 ELT_3DLINE 타입의 레이어 생성 후 setSelectable(false)로 설정하였고 클릭 시 poi를 생성하도록 이벤트를 추가하여 테스트해봤습니다.
지면을 클릭할 땐 이상이 없지만, 지면에서 떨어진 라인 레이어 클릭 시 공중에 점이 찍히며 poi는 조금 떨어진곳에 생성되고있습니다.

아래는 sandbox에서 테스트한 코드 전체입니다.
`/* 엔진 로드 후 실행할 초기화 함수(Module.postRun) */
function init() {

	// 엔진 초기화 API 호출(필수)
	Module.initialize({
		container: document.getElementById("map"),
		terrain : {
			dem : {
				url : "https://xdworld.vworld.kr",
				name : "dem",
				servername : "XDServer3d",
				encoding : true
			},
			image : {
				url : "https://xdworld.vworld.kr",
				name : "tile_mo_HD",
				servername : "XDServer3d"
			},
		},
		defaultKey : "ezbBD(h2eFCmDQFQd9QpdzDS#zJRdJDm4!Epe(a2EzcbEzb2"
	});

	// 카메라 위치 설정
	Module.getViewCamera().setLocation(new Module.JSVector3D(126.001, 36.9995, 500.0));

	// 폴리곤을 추가 할 레이어 생성
	var layerList = new Module.JSLayerList(true);
	const eltLineLayer = layerList.createLayer("Line_Option", Module.ELT_3DLINE);
	eltLineLayer.setSelectable(false);
	createLine("LINE_1", [[126.0, 37.0, 20], [126.002, 37.0, 20]], 1);
	createLine("LINE_2", [[126.0, 36.9998, -5], [126.002, 36.9998, -5]], 2);
	createLine("LINE_3", [[126.0, 36.9996, 0], [126.002, 36.9996, 1]], 3);
	createLine("LINE_4", [[126.0, 36.9994, 20], [126.002, 36.9994, 20]], 4);
	createLine("LINE_5", [[126.0, 36.9992, 20], [126.002, 36.9992, 20]], 5);
	createLine("LINE_6", [[126.0, 36.9990, 20], [126.002, 36.9990, 20]], 6);
	createLine("LINE_7", [[126.0, 36.9988, 20], [126.002, 36.9988, 20]], 7);
	createLine("LINE_8", [[126.0, 36.9986, 20], [126.002, 36.9986, 20]], 8);
    
    
    Module.XDSetMouseState(Module.MML_RETURN_ANALYSISPOS);
	canvas.addEventListener("Fire_EventAnalysisPos", function(e) {
		console.log(e.lon, e.lat, e.alt);
		let position = new Module.JSVector3D(e.lon, e.lat, 50);
        let point = createPOI(position, {
            text : "POI 텍스트\n테스트 메시지\naAbBcCdDeE\n123456789",
            font : "Consolas",
            fontSize : 15,
            fontColor: "rgba(0, 0, 0, 1.0)",
            backgroundColor: "rgba(255, 255, 255, 0.8)",
            outlineColor: "rgba(200, 200, 0, 0.5)",
            outlineWidth : 1,
        });

        // 레이어에 오브젝트 추가
        let layerList = new Module.JSLayerList(true);
        let layer = layerList.createLayer("POI_TEST", Module.ELT_3DPOINT);
        layer.addObject(point, 0);    
    })
}

function createLine( _id, _coordinate, _type) {
	
	let coordinates = {
			coordinate: _coordinate,						// 정점 배열
			style: "XYZ",
			// style에 따른 배열 관계
			// "XY" = [x, y],[x, y],[..]
			// "XYZ" = [x, y, z],[x, y, z],[...]
			// "XYZARRAY" = [x, y, z, x, y, z ...]
			// "JSVector3D" = JSVector3D 인스턴스
		};

		let object_option = null;

		if (_type == 1) object_option = createNormalLineJson(coordinates);
		else if (_type == 2) object_option = createDashLineJson(coordinates, _type);
		else if (_type == 3) object_option = createDashLineJson(coordinates, _type);
		else if (_type == 4) object_option = createDashLineJson(coordinates, _type);
		else if (_type == 5) object_option = createDashLineJson(coordinates, _type);
		else if (_type == 6) object_option = createDashLineJson(coordinates, _type);
		else if (_type == 7) object_option = createArrowLineJson(coordinates);
		else if (_type == 8) object_option = createOutLineJson(coordinates);

		let line = Module.createLineString(_id)
		console.log(line.createbyJson(object_option));

		let layerList = new Module.JSLayerList(true);
		let lineLayer = layerList.nameAtLayer("Line_Option");
		lineLayer.addObject(line, 0);
    	
}

function createNormalLineJson(_coordinates) {
	let data = {
		coordinates: _coordinates,
		type: 0,											// 실선 생성 		
		union: false,										// 지형 결합 유무
		depth: true,										// 오브젝트 겹침 유무
		color: new Module.JSColor(255, 255, 0, 0),			// ARGB 설정
		width: 1,											// 선 굵기
	}
	return data;
}

function createArrowLineJson(_coordinates) {
	let data = {
		coordinates: _coordinates,
		type: 3,											// 화살표선 생성 		
		union: false,										// 지형 결합 유무
		depth: true,										// 오브젝트 겹침 유무
		color: new Module.JSColor(255, 255, 0, 0),			// ARGB 설정
		width: 5,											// 선 굵기( type 3 일떄 width 1로 설정 시 화살표 X)
	}
	return data;
}

function createOutLineJson(_coordinates) {
	let data = {
		coordinates: _coordinates,
		type: 1,											// 그라데이션 선 생성 		
		union: false,										// 지형 결합 유무
		depth: true,										// 오브젝트 겹침 유무
		color: new Module.JSColor(200, 255, 0, 100),		// fill ARGB 설정
		strokecolor: new Module.JSColor(200, 100, 0, 255),	// stroke ARGB 설정
		strokewidth: 6.0,									// stroke 굵기 설정
		width: 10,											// 선 굵기( type 3 일떄 width 1로 설정 시 화살표 X)
	}
	return data;
}

function createDashLineJson(_coordinates, _type) {

	let union, depth,
		r, g, b, a,
		width, dash;

	union = false;	// 지형 결합 X
	depth = false;	// 지형 겹침 발생 금지

	if (_type == 2) {
		r = 0; g = 255; b = 0; a = 255;		// 녹색
		width = 2;							// 선 굵기
		dash = 5;							// 점선 O
	} else if (_type == 3) {
		depth = true;						// 지형 겹침 발생 
		r = 0; g = 0; b = 255; a = 255;		// 파랑
		width = 3;							// 선 굵기
		dash = 10;							// 점선 O

	} else if (_type == 4) {
		union = true;						// 지형결합 O
		r = 255; g = 255; b = 0; a = 255;	// 노랑
		width = 4;							// 선 굵기
		dash = 15;							// 점선 O
	} else if (_type == 5) {
		union = true;						// 지형결합 O
		r = 255; g = 0; b = 255; a = 255;	// 보라
		width = 5;							// 선 굵기
		dash = 20;							// 점선 O
	} else if (_type == 6) {
		union = true;						// 지형결합 O
		r = 255; g = 255; b = 255; a = 255;	// 하얀
		width = 6;							// 선 굵기
		dash = 25;							// 점선 O		
	}

	let data = {
		coordinates: _coordinates,
		type: 4,										// 점선 생성 
		union: union,									// 지형 결합 유무
		depth: depth,									// 지형 겹침 X
		color: new Module.JSColor(a, r, g, b),			// ARGB 설정
		width: width,									// 선 굵기
		dash: dash,										// 점선 간격(0)
	}
	return data;
}

/* POI 객체 생성 */
function createPOI(_position, _textOptions) {
	
	// POI 생성
	let point = Module.createPoint("TEXT_POI");
	point.setPosition(_position);
	
	let canvas = document.createElement("canvas");
	let ctx = canvas.getContext("2d");
	let boardImage = createBoardImage(ctx, _textOptions);
	point.setImage(boardImage.data, boardImage.width, boardImage.height);
	
	return point;
}

/* 캔버스로 POI 이미지 그리기 */
function createBoardImage(_ctx, _textOptions) {
	
	// 기본 폰트 설정
	let fontname, fontsize,	linewidth;

	fontname = _textOptions.font;
	fontsize = _textOptions.fontSize;
	linewidth = _textOptions.outlineWidth;
	
	// font 설정 옵션
	_ctx.font = fontsize + "px " + fontname;	// 크기 및 폰트 

	// 길이 반환
	let strlist = _textOptions.text.split("\n");
	let width = 0;
	let linecount = 0;

	// 이미지 width와 높이 설정
	for (let item of strlist) {
		let w = _ctx.measureText(item).width
		if (w > width) width = w;
		linecount++;
	}

	_ctx.fillStyle = _textOptions.backgroundColor;		// 백그라운드 

	var rectWidth = width + _textOptions.fontSize;
	var rectHeight = _textOptions.fontSize * (linecount + 1);
	
	_ctx.fillRect(0, 0, width + _textOptions.fontSize, _textOptions.fontSize * (linecount + 1));
	_ctx.strokeRect(0, 0, width + _textOptions.fontSize, _textOptions.fontSize * (linecount + 1));

	_ctx.fillStyle = _textOptions.fontColor;
	_ctx.strokeStyle = _textOptions.outlineColor;
	_ctx.lineWidth = _textOptions.linewidth;
	_ctx.textBaseline = "middle";
	_ctx.textAlign = "center";

	linecount = 1;
	
	for (let item of strlist) {
		_ctx.strokeText(item, (width + _textOptions.fontSize) * 0.5, _textOptions.fontSize * linecount);
		_ctx.fillText(item, (width + _textOptions.fontSize) * 0.5, _textOptions.fontSize * linecount);
		linecount++;
	}
	
	return {
		width : rectWidth,
		height : rectHeight,
		data : _ctx.getImageData(0, 0, rectWidth, rectHeight).data,
	};
}

/*********************************************************
* 엔진 파일을 로드합니다.
* 파일은 asm.js파일, html.mem파일, js 파일 순으로 적용합니다.
*********************************************************/

;(function(){

    var tm = (new Date()).getTime();	// 캐싱 방지
    
	// 1. XDWorldEM.asm.js 파일 로드
	var file = "https://cdn.xdworld.kr/latest/XDWorldEM.asm.js?tm="+tm;
	var xhr = new XMLHttpRequest();
	xhr.open('GET', file, true);
	xhr.onload = function() {

		var script = document.createElement('script');
		script.innerHTML = xhr.responseText;
		document.body.appendChild(script);

		// 2. XDWorldEM.html.mem 파일 로드
		setTimeout(function() {
			(function() {

				var memoryInitializer = "https://cdn.xdworld.kr/latest/XDWorldEM.html.mem?tm="+tm;
				var xhr = Module['memoryInitializerRequest'] = new XMLHttpRequest();
				xhr.open('GET', memoryInitializer, true);
				xhr.responseType = 'arraybuffer';
				xhr.onload =  function(){

					// 3. XDWorldEM.js 파일 로드
					var url = "https://cdn.xdworld.kr/latest/XDWorldEM.js?tm="+tm;
					var xhr = new XMLHttpRequest();
					xhr.open('GET',url , true);
					xhr.onload = function(){
						var script = document.createElement('script');
						script.innerHTML = xhr.responseText;
						document.body.appendChild(script);
					};
					xhr.send(null);
				}
				xhr.send(null);
			})();
		}, 1);
	};
	xhr.send(null);

})();


/*********************************************************
*	엔진파일 로드 후 Module 객체가 생성되며,
*  Module 객체를 통해 API 클래스에 접근 할 수 있습니다.
*	 - Module.postRun : 엔진파일 로드 후 실행할 함수를 연결합니다.
*	 - Module.canvas : 지도를 표시할 canvas 엘리먼트를 연결합니다.
*********************************************************/

var Module = {
	TOTAL_MEMORY: 256*1024*1024,
	postRun: [init]
};`

**Comment by hjaejae** [comment]
친절한 테스트 코드 감사합니다.

테스트 코드로 확인 결과 우선 레이어의 선택 상태를 false로 하였을 때(eltLineLayer.setSelectable(false);)는 정상 작동을 확인하였습니다. false로 하였는데도 같은 현상이 발행되면 getSelectable() API를 통해 값을 다시 한번 확인해보시면 좋겠습니다.

그리고 레이어의 선택 상태가 true일 때는 말씀해주신거와 같은 현상이 발생하였습니다.
이 문제는 다음 업데이트를 통해 수정하겠습니다.

**Comment by hjaejae** [comment]
추가 방법으로는 객체를 클릭 안되도록 하는 방법입니다.
절달해 주신 테스트 코드에서 아래 API를 추가하시면 됩니다.

```javascript
   let line = Module.createLineString(_id)
   line.setPickable(false);   // 객체가 선택 안되도록 변경
   console.log(line.createbyJson(object_option));
```

**Comment by 18kiku** [comment]
setPickable을 false로 설정하니 해결되었습니다.
감사합니다
