### ISSUE TITLE
빌더 프로에서 가공한 xnd 데이터 엔진 가시화

### ISSUE THREAD

**Issue by yoonee25** [EgisCorp/XDWorld#377]
엔진 버전
: 2.0.0 beta for 1.57.1 (Released 2024-1-5)

문의 내용
: 빌더 프로(v.5.0.6) 에서 가공한 xnd 데이터를 웹 엔진에서 가시화할 때 일부가 표출되지않습니다.
대부분 교량 데이터로 분할하여 전달받았음에도 일부가 엔진에서 보이지않아 분할에 어려움이 있습니다.
(좌, 웹 엔진 / 우, 빌더 프로)
![image](https://github.com/EgisCorp/XDWorld/assets/48304523/650ff933-8204-41a3-bfaf-73efc76e434f)
![image](https://github.com/EgisCorp/XDWorld/assets/48304523/e4145f6b-b69a-44fa-9546-f706862cec5f)
![image](https://github.com/EgisCorp/XDWorld/assets/48304523/ff4208d1-05e0-43b0-bc1b-bf6a0d049d10)

엔진에서 데이터 호출 시 다음과 같이 하고있습니다.
```
Module.getTileLayerList().createXDServerLayer({
	url : "openlab-3d.eseoul.go.kr",
	servername : "XDServer",
	name : "bldg_seoul_update",
	type : 29,
	minLevel : 0,
	maxLevel : 15
});
```

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 관련 내용을 확인 하였습니다. 동일하게 일부 데이터가 나타나지 않는 문제를 확인 하였습니다. 

xdo 객체가 가시화 되지 않는 문제를 확인 하고 답변드리겠습니다.

**Comment by YangHeeBong** [comment]
관련 담당자 분에게 결과를 메일로 알려드렸습니다
