### ISSUE TITLE
건물 줌인 했을 때, 건물 통과하지 않게 할 수 있는지 문의드립니다.

### ISSUE THREAD

**Issue by jangseonghyun** [EgisCorp/XDWorld#378]
엔진 버전
: XDWorld Version : 1.55.2 (Released 2023-11-17)

문의 내용
: 안녕하세요.
  건물을 계속 줌인 했을 때, 해당 건물의 내부가 보이는 현상이 있습니다.  
  건물을 통과하지 못하게 막을 수 있는 방법이 있는지 문의드립니다.

https://github.com/EgisCorp/XDWorld/assets/50700729/5b9d54fe-be29-47df-a3c8-35b9146d80a4

**Comment by YunSumin** [comment]
안녕하세요,
문제의 정확한 해결을 위해 몇 가지 추가적인 질문을 드리고자 합니다.

첨부하신 영상 중 피킹 지점을 넘어 반대편 건물이 피킹 지점으로 인식되어 건물이 투과 하는 것처럼 보이는 현상을 확인하였습니다.
마우스로 특정 지점에서 확대 시, 일정 거리 이상 확대되지 않도록 처리 후 다시 답변 드리겠습니다.

감사합니다.

**Comment by YangHeeBong** [comment]
1.58.0 릴리즈 버전을 통해 업데이트 했습니다.

관련 내용은 아래와같습니다.

  * Class JSCamera 구성요소 추가
    * 변수항목
      * collision_type(type boolean) : 휠 이벤트에서 카메라와 선택지점 충돌 유무를 설정합니다.
      * collision_distance(type number) : 휠 이벤트에서 카메라와 선택지점(마우스 이벤트 지점) 보간 거리를 설정합니다.

 ``` javascript
var camera = Module.getViewCamera();
camera.collision_type = true;
camera.collision_distance = 20;
```

**Comment by jangseonghyun** [comment]
감사합니다 해결되었습니다.
