### ISSUE TITLE
지도 배경을 하얗게 하는 방법

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#379]
엔진 버전
:  1.57.1 

문의 내용
: 안녕하세요.

XDWorld 엔진을 이용하여 폴리곤을 생성하는데, 이 때 뒷 배경을 하얀색으로 설정하고 싶습니다.
배경색을 설정할 수 있는 API가 있나요?

**Comment by avamk2** [comment]
질문내용이 추상적이라서 조금더 구체적인 문의가 필요한거 같습니다.

배경색이라는 것이 폴리곤과 어떠한 연관이 있는가요?

**Comment by kseonok** [comment]
![image](https://github.com/EgisCorp/XDWorld/assets/118805328/9b6f9b06-6067-4cce-a8e9-dd5a1fc1445a)


위 이미지는 Module.XDESetPlanetTransparecny(0);을 통해 배경을 검은색으로 설정해둔 상태인데,
이때 배경을 흰색으로 변경할 수 있는 방법이 있을까요?

**Comment by kseonok** [comment]
확인했습니다. 감사합니다!
