### ISSUE TITLE
ZoomIn(), ZoomOut() 동작여부 확인 요청

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#38]
Version 1.3.15.7.2 (2021-06-14)

안녕하세요. 바이브컴퍼니입니다.

**ZoomIn(), ZoomOut()이 동작하지 않습니다.**

```
Module.getViewCamera().ZoomIn();
Module.getViewCamera().ZoomOut();
```

확인 부탁합니다.

**Comment by YangHeeBong** [comment]
원인 분석 결과 
 - 카메라 이동 API 동작 후 마우스 클릭 미 동작 시 중심 좌표( In Out 기준 좌표)가 없어서 생기는 문제
 
해결된 엔진은 다음 배포에 첨부하여 이번 주 또는 다음 주 전달해 하겠습니다.

**Comment by YangHeeBong** [comment]
엔진 업로드 완료 하였습니다.
