### ISSUE TITLE
Module.getObjectLayerList().createObjectLayer() 문의드립니다

### ISSUE THREAD

**Issue by 18kiku** [EgisCorp/XDWorld#380]
``엔진 버전
: 1.54.0

문의 내용
:
안녕하세요.

간헐적으로 createObjectLayer로 레이어가 생성되지 않는 현상이 발생하여 질문드립니다.

설명드리기 전에 사용한 함수를 첨부합니다.
```
const createSimulation = (data) => {
	let vehicleLayer = Module.getObjectLayerList().nameAtLayer("VEHICLES");
	if (vehicleLayer == null) {
		vehicleLayer = Module.getObjectLayerList().createObjectLayer({
			name: "VEHICLES",
			type: Module.ELT_GHOST_3DSYMBOL,
			selectable: false,
			maxDistance: 5000,
		});
	}

	// 레이어 clear 후 생성
	vehicleLayer.removeAll();

	const points = JSON.parse(data);
	// 차랑 모델을 활용한 고스트심볼 오브젝트 추가
	createSumoCar(vehicleLayer, points);
};

// sumo에서 넘어오는 좌표배열로 고스트심볼 오브젝트 생성
const createSumoCar = (layer, points) => {
	for (let point of points) {
		const _modelID = GLOBAL.vehicleModels[0];
		const modelHalfHeight = Module.getGhostSymbolMap().getGhostSymbolSize(_modelID).Height * 0.5;
		// 고스트심볼 오브젝트 생성
		const vehicle = Module.createGhostSymbol(_modelID + "_copy_" + generateUUID());
		vehicle.setBasePoint(0, -modelHalfHeight, 0);

		vehicle.setScale(new Module.JSSize3D(0.002, 0.002, 0.002));
		vehicle.setGhostSymbol(_modelID);

		const altitude = Module.getMap().getTerrHeightFast(parseFloat(point.x), parseFloat(point.y));
		const position = new Module.JSVector3D(parseFloat(point.x), parseFloat(point.y), altitude + 5);
		vehicle.setPosition(position);
		vehicle.setDirection(point.a - 90); // 모델에 따라 각도 설정

		layer.addObject(vehicle, 0);
	}
}
```

createSimulation 함수는 이러한 동작을 수행하기 위해 작성했습니다.
1. "VEHICLES" 레이어 조회. 없다면 생성.
2. 레이어 내의 모든 객체 제거.
3. 인수로 받은 데이터로 고스트심볼레이어(약 1000개) 생성 후 "VEHICLES" 레이어에 추가

차량이 움직이는것처럼 보이는 효과를 주기 위해
createSimulation 함수를 0.1초마다 실행하면서 VEHICLES 레이어의 객체를 지우고 생성하고를 반복했습니다.
그런데 갑자기 모든 레이어가 null을 반환하게 되는 현상이 발생했습니다.
이러한 현상이 발생할 때 createObjectLayer 함수로 새로운 레이어를 생성해도 Module.getObjectLayerList().nameAtLayer()로 조회해보면 모두 null을 반환했습니다.

의심이 가는 부분은 페이지를 장시간 켜놓았다는것 뿐입니다..
혹시 레이어에 고스트심볼을 추가하고 removeAll() 하는 과정을 계속 반복해서 문제가 생긴걸까요?

감사합니다.

**Comment by avamk2** [comment]
안녕하세요.

우선 사용하시는 엔진버전을 최신화 부탁드리겠습니다. 
지난 4개월간 엔진에 성능적, 안정성에 여러가지 개선하면서 외부기능보다 내부적 변화사항이 많이 있습니다.

이 외에도 생각해봐야될 것이

내용상으로는 createObjectLayer는 한번만 호출되고 ( 다른 부분에서 레이어를 삭제 하지 않는다면 ) 계속 nameAtLayer("VEHICLES")를 통해서 레이어를 받는 것으로만 보입니다. 

여기서 한가지 생각해봐야될 사항은 0.1초의 주기적 호출인데

1. 레이어에 객체 삭제
2. Text를 JSON으로 파싱
3. 약 1000개의 배치할 위치에 지형 높이값 계산
4. 약 1000개의 고스트 심볼 생성 및 배치

위 공정이 0.1 초만에 수행이 가능한지 모니터링이 필요로합니다. 
이유는 위 수행이 실제로는 0.2초가 걸리면 타이머 수행시 해당 수행이 타이밍보다 늦어지면 뒤에 등록되는 횟수가 계속 누적될 수 있습니다.   그리고 이 누적이 장시간 지속되면 메모리 힙에서 문제가 생길수도 있습니다.

한 시퀀스 내에서 수행하는 시간 간격을 보고 타이밍을 조금더 느슨하게 맞춰서 동작하는 것을 해보시길 바랍니다.
