### ISSUE TITLE
WMS 레이어 호출 시 지도 전체가 새로고침 되는 현상 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#382]
엔진 버전
: 1.58.0

오류 발생 API
: createWMSLayer

오류 내용
:
안녕하세요!

createWMSLayer 함수를 이용하여 지오서버 WMS 레이어를 가시화 할 때 지도 전체가 새로고침 되는 것 처럼 깜빡이는 현상이
어느순간부터 발생하여서 문의 드립니다.

https://github.com/EgisCorp/XDWorld/assets/88410545/25dea25a-8deb-4485-b6e1-56f58e82bf3e

예전에는 레이어만 on/off 되었던걸로 기억하는데 따로 옵션을 주어서 예전처럼 레이어만 on/off 되도록 가능할까요??

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

"WMS 레이어를 가시화 할 때 지도 전체가 새로고침 되는 것 처럼 깜빡이는 현상이 어느순간부터 발생"에 대해서 설명 드리곘습니다.

WMS Layer는 생성 시 설정된 minimumlevel과 maximumlevel을 기준으로 타일 이미지를 요청하고 처리합니다.
이는 새로고침이 아닌 WMS Layer에서 타일 이미지를 요청 후 가시화되는 과정입니다.

하지만 과거에 엔진과 다르다고 하신 부분은 아래 영상을 통해 설명 가능할 것 같습니다.
 - WMS Layer 생성 정보 차이는
    - 첫번쨰 영상 minimumlevel = 1
    - 두번쨰 영상 minimumlevel = 9;
	
https://github.com/EgisCorp/XDWorld/assets/82924515/7738bb5c-61e1-4e46-a29a-9eb0778dd03e

https://github.com/EgisCorp/XDWorld/assets/82924515/6c39e22b-3d51-48c0-a5b6-646f01c10a0e


minimumlevel이 1인 경우 최상위 타일부터 이미지를 요청하여 가시화하는 반면, minimumlevel이 9인 경우 중간 레벨부터 이미지를 요청해 깜박임이 적다는 점입니다. 


문제 해결을 위해 적절한 레벨 설정이 필요하며, JSLayer의 setVisible API 사용도 다른 해결 방법입니다.

**Comment by giyoon99** [comment]
해당 옵션으로 조절해서 해결 하였습니다 감사합니다!
