### ISSUE TITLE
특정 고도 이상부터 POI 객체가 지형에 가려지지 않는 오류 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#383]
엔진 버전
: 1.58.0

오류 발생 API
: createPoint

오류 내용
:
안녕하세요!
createPoint 함수를 이용하여 POI 객체를 생성하였는데 위성 객체다보니 지구본 전체가 보일 정도의 고도로 카메라를 세팅하고 있습니다.

카메라 고도가 특정 높이 이상 되면 지구 반대편에 있는 객체가 숨겨지지 않고 보이는 문제가 있는 듯 하여 문의 드립니다.

html poi가 아닌 점 참고 부탁드립니다!

https://github.com/EgisCorp/XDWorld/assets/88410545/f3f6723b-f8cc-4fd5-a061-4a884631f227

**Comment by YunSumin** [comment]
안녕하세요, 

업로드하신 영상을 참고하여 지구 반대편에 POI가 있다고 가정,
아래와 같이 코드를 작성하여 현상을 재현해보았으나 문의하신 현상이 일어나지 않았습니다.

``` javascript
var layerList = Module.getObjectLayerList();
var layer = layerList.createObjectLayer({
    name : "TEST",
    type : Module.ELT_3DPOINT
});

var point = Module.createPoint("STATION_POINT");
point.setPosition(new Module.JSVector3D(-52.0, -38.0, 0.0));
point.setText("TEST");

layer.addObject(point, 0);

layer.setMinDistance(1.0);
layer.setMaxDistance(10000.0);
```

특별한 설정이 없다면 기본적으로 레이어의 min/max Distance 값으로 가시화 여부를 결정합니다.
만약 min/max Distance 값을 설정하셨다면 값이 정상적으로 적용되었는지 확인이 필요합니다.

또한 영상으로 문의하시는 경우 활용하시는 API의 값을 알 수 없어
영상의 값을 추정하여 테스트가 진행되오니
설정하신 값을 자세히 알려주시면 오류 확인에 큰 도움이 되는 점 참고 부탁 드립니다.

**Comment by giyoon99** [comment]
setMaxDistance 조절하니 해결되었습니다! 감사합니다
