### ISSUE TITLE
폴리곤 height 값 조회하는 방법

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#384]
엔진 버전
: 1.58.0

문의 내용
: 안녕하세요.

toLonlatArray 를 통해 폴리곤의 좌표 정보를 조회할 수 있는 것을 확인하였습니다.
이 폴리곤의 높이값(기둥값)이 고정적이지 않을 경우,
각 좌표별 기둥의 높이값을 알 수 있는 API도 있나요?

**Comment by egiskorea-ryong** [comment]
안녕하세요.

toLonlatArray API는 경도, 위도, 고도를 반환합니다.

높이값이 서로 다르더라도 입력된 좌표를 바탕으로 경도, 위도, 고도를 반환합니다.

아래는 높이값이 서로 다른 colorPolygon을 생성하여 toLonlatArray API를 통해 반환받은 예시입니다.

![20240219_093928](https://github.com/EgisCorp/XDWorld/assets/70614782/08a74829-f86d-4773-9923-8f271c731fd6)
