### ISSUE TITLE
3D 폴리곤 좌표 정보 조회 방법

### ISSUE THREAD

**Issue by kseonok** [EgisCorp/XDWorld#385]
엔진 버전
:1.58.0

문의 내용
:안녕하세요.

https://sandbox.egiscloud.com/code/main.do?id=object_colorpolygon_color_gradation

위 API처럼 삼각형 좌표를 polygon.set을 통해 생성한 폴리곤에 toLonlatArray를 사용하면,
아래 이미지와 같이 순번 순서가 밑면(또는 윗면)을 한 방향으로 돌며 나오질 않습니다.
밑면의 모든 좌표를 한 방향으로 조회할 수 있는 방법이 있을까요?

![image](https://github.com/EgisCorp/XDWorld/assets/118805328/9f16ca14-55e9-4d4c-9761-aff5509aa669)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

toLonlatArray는 좌표리스트에 입력된 순서대로 좌표를 변환하여 반환합니다.

vertex는 순서대로 입력되었더라도 index에 따라서 바뀔수있습니다.

polygon.set 할 때 사용하신 vertex와 index를 알려주시면 감사하겠습니다.
