### ISSUE TITLE
setVisible 사용시 객체 자동 생성 문의

### ISSUE THREAD

**Issue by HyeonbinLee** [EgisCorp/XDWorld#387]
엔진 버전
: 1.58.0

오류 발생 API
: setVisible

오류 내용
: 안녕하세요

객체를 setVisible로 false 하여 가시화 비활성화 후에,
다른 곳으로 이동했다가 다시 오면 객체가 가시화 활성화되어 있습니다.
해결 방법이 있을까요?

**Comment by YunSumin** [comment]
안녕하세요, 

말씀해주신 내용으로는 오류가 나는 객체 타입을 특정할 수 없어 구체적인 원인 확인이 어렵습니다.
사용하시는 객체 타입(JSPoint, JSPolygon 등)과 활용하신 API에 대하여 추가적인 정보 부탁 드립니다.

덧붙여, JSLayer 중 서비스 레이어의 경우
카메라 시야를 다른 곳으로 이동했을 때  보이지 않는 지역은 동적으로 삭제하도록 구성되어 있습니다.

이후 삭제된 오브젝트가 다시 시야에 들어와 로드 될 때
가시화 비활성화 정보가 없으므로 오브젝트가 다시 보이게 설정되었을 가능성이 있습니다.
만약 서비스 레이어를 활용하시는 경우 이 부분도 함께 검토 부탁 드립니다.

**Comment by HyeonbinLee** [comment]
네 감사합니다!
