### ISSUE TITLE
오브젝트 객체 차폐 기능 문의

### ISSUE THREAD

**Issue by jsh0801** [EgisCorp/XDWorld#388]
엔진 버전
: 1.55.3

문의 내용
:

안녕하세요. 융복합서비스팀 정서해 사원 입니다.
오브젝트 객체 차폐 기능 문의 드립니다.

**`    1. 개요`**
> 가시권 분석 기능을 활용하여 지형 및 건물 레이어에 차폐 영역을 구현하였습니다.
> 위 기능처럼 사용자가 생성한 폴리곤 등의 오브젝트 객체에도 가시권 분석 기능을 적용하여 
> 차폐 영역을 구현하고 싶습니다.
>
> 1). 해당 기능 존재 여부

<hr>

**`    2. 참고자료`**

1). 레이어에 가시권 분석 기능이 적용되어 차폐 영역이 구현된 경우
![123](https://github.com/EgisCorp/XDWorld/assets/110378027/c9369d86-eb66-4417-a0d8-949f16849744)

2). 폴리곤 오브젝트 객체에 가시권 분석 기능이 적용되지 않아 차폐 영역이 구현되지 않은 경우 (빨간색 원)
![1234](https://github.com/EgisCorp/XDWorld/assets/110378027/bd450943-ead0-4049-a705-0be24ad24eb6)

<hr>

감사합니다.

**Comment by hjaejae** [comment]
정확한 소스 코드가 없어 임의로 테스트 한 결과

1. 기본
![20240306_084441](https://github.com/EgisCorp/XDWorld/assets/82991868/23aff394-cea6-4c5a-9011-cfd90a52605d)

2. 폴리곤 건물
![20240306_084755](https://github.com/EgisCorp/XDWorld/assets/82991868/6e3dea25-70f4-4267-8079-b454bd13707a)

사용자가 생성한 폴리곤은 

```javascript
var layerList = new Module.JSLayerList(true);
var layer = layerList.nameAtLayer("POLYGON_LAYER");

...

polygon.setPartCoordinates(vertex, part);
polygon.setHeight(80.0);
layer.addObject(polygon, 0);
```

형식으로 폴리곤을 생성 하였습니다.

질문해주신 분의 스크린 샷을 보니 생성된 면이 반대로 되어있어서 그림자 분석에 적용이 되지 않은듯합니다.

해당 API에서 좌표를 설정 할 때는 좌표 방향이 시계 방향으로 설정 되어 있어야 합니다.

**Comment by jsh0801** [comment]
확인하였습니다.
답변 감사합니다! ^^
