### ISSUE TITLE
오브젝트 드래그 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by jangseonghyun** [EgisCorp/XDWorld#389]
엔진 버전
: XDWorld Version : 1.58.0 (Released 2024-1-26)

오류 내용
:
안녕하세요.
오브젝트를 드래그해서 옮기면 아래와 같이 오브젝트가 분리되는 현상이 있습니다.
해결방법이 있을지 문의드립니다.

![image](https://github.com/EgisCorp/XDWorld/assets/50700729/7d77cd79-f5ee-4d27-8209-79553757cb1b)
![image](https://github.com/EgisCorp/XDWorld/assets/50700729/6e03f9e1-d0ec-46eb-a55b-58aa16037f4f)
![image](https://github.com/EgisCorp/XDWorld/assets/50700729/4a2b5c78-8a85-4d5d-bc24-b28a5fa42a20)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

정확한 문제해결을 위해서 사용하신 코드를 첨부해주시면 감사하겠습니다.

사진상으로만 판단했을때 라인과 폴리곤을 따로 생성한것 같습니다.

그렇기 때문에 폴리곤만 드래그되고 라인은 그대로 남아있는 현상같습니다.

정확한건 사용하신 코드를 첨부해주시면 확인해보겠습니다.

감사합니다.

**Comment by egiskorea-ryong** [comment]
해당 이슈는 웹 코드상에서 발생하는 오류로 확인되어 이슈 등록자와 의사소통 후 종료합니다.
