### ISSUE TITLE
지도 화면 캡처 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#39]
안녕하세요. 바이브컴퍼니입니다.

**sandbox의 지도 캡처를 참고해서 코드를 생성했으나 지도 캡처가 되지 않습니다.**
캡처된(다운로드된) 이미지에는 흰색 화면만 나타납니다.

아래 첨부된 이미지는 지도 캡처를 위해 코딩한 부분입니다.
잘못된 부분이 있을까요?

테스트를 위해 34~36 라인. 주석처리된 부분의 로직을 실행시켜 보았을 때는 흰색 배경에 사각형이 표시되었습니다.

![image](https://user-images.githubusercontent.com/38479834/122158963-7bb1a780-cea8-11eb-9df9-1fc34b8aec41.png)

**Comment by YangHeeBong** [comment]
toBlob 부분에서 의심이 됩니다. 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

위 사이트 web developer 이며 web 관련 문의는 이쪽을 참조 하시면 좋습니다.

**Comment by Khaia** [comment]
안녕하세요?

init.js 에서

canvas:(function() {
                canvas.getContext("experimental-webgl", {
			preserveDrawingBuffer: true
		});
})

webl 옵션을 추가해보시기 바랍니다.

https://developer.mozilla.org/ko/docs/Web/API/HTMLCanvasElement/getContext

**Comment by HyunSeongKil** [comment]
![image](https://user-images.githubusercontent.com/38479834/122180562-7f065c80-cec3-11eb-8878-7e300858980b.png)

이렇게 코드 추가했는데도 지도가 캡처 되지 않습니다. ㅠㅠ

**Comment by HyunSeongKil** [comment]
....여튼 성공했습니다.

고맙습니다~
