### ISSUE TITLE
createLineString 점선 그리기 문의

### ISSUE THREAD

**Issue by DuHyeon2** [EgisCorp/XDWorld#391]
엔진 버전
: 1.59.1 (Released 2024-03-08)

문의 내용
: 안녕하세요
엔진 기능 중 createLineString에 점선 그리기 기능 중
type이 3번 혹은 4번이 점선으로 표출되는걸로 안내되어
실행 결과 점선이 표출되지 않아 문의 드립니다.

![점선 문의1](https://github.com/EgisCorp/XDWorld/assets/83499405/1f1b6384-63fb-4421-a380-995638893f02)
![점선 문의2](https://github.com/EgisCorp/XDWorld/assets/83499405/e98ce269-7f29-4e25-a281-854ee4f4a22e)
![점선 문의5](https://github.com/EgisCorp/XDWorld/assets/83499405/eedf3564-0a8c-4d9c-95ba-1feea0fa18d9)

**Comment by hjaejae** [comment]
안녕하세요~ 
내용을 확인해본 결과 라인 굵기를 1로 설정하면 점선 효과가 발생하지 않는 것으로 확인되었습니다.
위 문제는 해결 후 다시 댓글 드리겠습니다.

굳이 1의 값이 아니라도 된다면 2로 셋팅 후 사용해주시기 바랍니다.

**Comment by DuHyeon2** [comment]
네 감사합니다!
