### ISSUE TITLE
저지대분석 범례

### ISSUE THREAD

**Issue by DuHyeon2** [EgisCorp/XDWorld#392]
엔진 버전
: 1.57.1

문의 내용
: 안녕하세요 

저지대분석 기능 중 범례 표시를 경사 분석처럼 추가할 방법이 따로 있을까 싶어 문의 드립니다

- 저지대 분석
![image](https://github.com/EgisCorp/XDWorld/assets/83499405/9f505a7e-4c79-4946-92b3-2e0941752872)

- 경사 분석
![image](https://github.com/EgisCorp/XDWorld/assets/83499405/8b4984ad-8da3-4e09-9547-33bbee785e52)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

저지대 분석에서 사용하는 API는 분석 전용으로 사용하는 API가 아닌 JSColorPolygon을 이용한 기능입니다.

범례가 표현이 필요하시다면 JSColorPolygon 관련 API를 이용하여 범례 색상을 표현 하시면 가능합니다.
