### ISSUE TITLE
아이콘 선택 관련 문의

### ISSUE THREAD

**Issue by Young-Ju98** [EgisCorp/XDWorld#393]
엔진 버전
: 2.1.0 (Beta Released 2024-02-23)

문의 내용
: 안녕하세요.

지도에 아이콘을 뿌릴때 setDescription()을 통해 특정 날짜를 집어넣어서 아이콘을 그리고 아이콘을 클릭하면 getDescription()을 통해 해당 날짜를 가져오는 기능을 만들고 있습니다.
지도를 실행하고 초반에는 뿌려진 아이콘이 잘 클릭되는데 이런저런 기능들을 누르다 아이콘을 누르면 아이콘이 클릭되지 않는 현상이 발생합니다.
getDescription()을 하면 해당 값이 나오지만 지도에서 아이콘이 클릭되지않고 아이콘을 지우고 다시 그린 다음 클릭해봐도 클릭기능이 안되는것 같은데 어떤 이유때문인지 알 수 있을까요?

![image](https://github.com/EgisCorp/XDWorld/assets/109942684/570b6edc-e87f-49a6-8ce3-38aed957ea44)

**Comment by YunSumin** [comment]
안녕하세요, 

HTML 오브젝트를 사용하여 클릭 이벤트를 활용하시는 것으로 확인됩니다.
업로드 해 주신 에러 코드를 참조한 결과 엔진 내 클릭 이벤트 발생 후(at sendEvent (XDWorldEM.js:1:27180))
HTML 오브젝트에서 addLayerChart 함수를 layer.js 스크립트에서 호출하고 있는 것으로 확인됩니다.
(at HTMLCanvasElement.addLayerChart (layer.js:385:58))

에러는 최종적으로 layer.js의 addLayerChart 함수에서 발생하는 것으로 판단되나
함수의 내용을 확인할 수 없어 addLayerChart 함수에 대한 자세한 내용이 필요합니다.

해당 부분을 확인하시어 addLayerChart에 대한 정보를 추가적으로 알려주시면 자세한 원인을 확인해보겠습니다.
