### ISSUE TITLE
수인한도 / 창문분석 관련 확인 요청드립니다.

### ISSUE THREAD

**Issue by yoonee25** [EgisCorp/XDWorld#396]
엔진 버전
: 2.2.0

오류 발생 API
: Module.getAnalysisGridShadow().startAnalysis

오류 내용
: 
![image](https://github.com/EgisCorp/XDWorld/assets/48304523/5a9da4ec-1a18-4613-abf5-932bdb878600)
(조건 : 
그림자 설정 > Module.getAnalysis().createShadow(2024, 4, 8, 9, 0) 부터 Module.getAnalysis().createShadow(2024, 4, 8, 12, 0) 까지
분석 설정 >     Module.getAnalysisGridShadow().startAnalysis(new Module.JSDateTime(2024, 4, 8, 9, 0, 0), 
                                                                                                   new Module.JSDateTime(2024, 4, 8, 12, 0, 0), 10)) //10분 단위
수인한도 분석 결과를 Module.getAnalysisGridShadow().getResult() api로 추출하여 정리한 텍스트입니다.
https://egiscloud.com/siteData/app/check.mp4
2번째 그리드의 경우 연속 일조 시간(continuevalue)이 10분, 전체 일조 시간(totalvalue)이 110분으로 나타나는데
실제 그림자를 확인할 경우 11시 20분부터 12시 00분까지 40분간 연속 일조로 확인됩니다.
5번째 그리드 역시 연속 일조 시간(continuevalue)이 40분, 전체 일조 시간(totalvalue)이 60분으로 나타나는데
실제 그림자를 확인할 경우  모든 시간에 그림자가 해당 영역에 걸쳐져 일조 시간이 확보되지 않습니다.
이처럼 실제 그림자와 수인한도 분석 결과의 차이로 인해 분석의 신뢰성을 확인하고 싶다는 요청이 있습니다.
(창문 분석도 동일한 상황입니다.)
각 그리드의 분석 시간 단위의 상세 결과값을 확인하거나 내부적으로 어떤 로직에 따라 분석이 진행되는지 알 수 있을까요?

**Comment by egiskorea-ryong** [comment]
안녕하세요.

현재 수인한도분석은 그리드의 절반 이상이 햇빛을 받을 경우 일조량 계산을 합니다.

사용자에 따라 다르게 해석할 수 있는 부분으로 추후 옵션을 추가할 예정입니다.

1. 그리드 영역 일부에 햇빛을 받을 경우에도 일조량 계산
2. 그리드 영역 전체가 햇빛을 받을 경우에만 일조량 계산

위 2가지 옵션을 추가할 예정입니다.

감사합니다.

**Comment by egiskorea-ryong** [comment]
해당 옵션 추가되어 다음 엔진 정기 배포에 포함될 예정입니다.

엔진 정기 배포시 샌드박스 링크와 함께 재답변드리겠습니다.

감사합니다.

**Comment by egiskorea-ryong** [comment]
해당 기능 추가되어 업데이트되었습니다.

```javascript
// true: 그리드 영역 조금이라도 그림자 지면 일조침해
// false: 그리드 영역 절반 이상 그림자 지면 일조침해
Module.getAnalysisGridShadow().strictCalculate = true;
```

[수인한도분석](https://sandbox.egiscloud.com/code/main.do?id=analysis_grid_shadow&engine=beta&worker=true)

감사합니다.
