### ISSUE TITLE
wfs 레이어 예제

### ISSUE THREAD

**Issue by tshgsd** [EgisCorp/XDWorld#397]
엔진 버전
:

문의 내용
: wfs 레이어 예제 샌드박스에 아직 없나요?

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

wfs 기능은 현재 개편중입니다. 

기능 개편 후 wfs 예제에 대한 샌드박스 기능 업데이트 예정입니다.

**Comment by tshgsd** [comment]
언제쯤 개편될까요?

**Comment by YangHeeBong** [comment]
지금 바로 일정에 대한 처리는 힘든 상태입니다. wfs 관련해서 급한 부분이 있으시다면 지금 기능으로는 POI 표현으로 가시화 하는 형태로 샘플 테스트는 안되지만 구성은 가능한 예제는 답변으로 처리 가능합니다.

**Comment by avamk2** [comment]
오래걸려서 죄송합니다. 

샌드박스에 WFS로 공간쿼리 및 GeoJSON으로 응답받아 파싱후 기존 객체 API를 통해서 등록하는 방식으로 샘플을 구성했습니다.

https://sandbox.egiscloud.com/code/main.do?id=layer_wfs


총 3개의 색션으로 

- 타일기반 레이어로 공간을 인식하여 콜백 처리 단계
- 공간 BBOX를 WFS 서버로 URL 호출하는 단계
- WFS 서버에서 응답한 GeoJSON객체를 API를 통해서 등록하는 단계

각 구성으로 사용할 수 있습니다.
