### ISSUE TITLE
커스텀타일레이어 html poi 삭제되지 않는 오류 

### ISSUE THREAD

**Issue by leepulum727** [EgisCorp/XDWorld#398]
엔진 버전
:
XDWorld Version : 2.2.1 (Beta Released 2024-04-22)
오류 발생 API
:
Module.getTileLayerList().createXDServerLayer 커스텀 타일 레이어
오류 내용
:
커스텀타일 레이어로 html poi생성시 생성된 bbox를 넘어갈경우 html poi가 밀리면서 캔버스에서 지워지지 않는 오류가 있습니다

![clipboardImage_24_0502_112739_067](https://github.com/EgisCorp/XDWorld/assets/73877693/dafa5309-03aa-4850-812a-5f27d25a31f6)

**Comment by YunSumin** [comment]
안녕하세요,

HTML 오브젝트는 서비스 레이어가 아닌 오브젝트 레이어에만 적용 가능하며,
해당 현상은 서비스 레이어에 HTML 오브젝트 visible on/off 단계가 존재하지 않아
visible 속성이 갱신 되지 않는 현상으로 보입니다.

HTML 오브젝트는 다른 오브젝트와 다르게 웹 엘리먼트와 1:1 연동되므로
로드와 삭제가 빈번한 서비스 레이어에서는 활용이 어려운 점 양해 부탁 드립니다.

만약 부득이 서비스 레이어의 정보를 HTML 오브젝트로 추가하고자 하시는 경우 아래 과정 참조 부탁 드립니다.

1. HTML 오브젝트 추가를 위해 오브젝트 레이어를 별도로 생성 생성합니다. (JSLayerList의 createObjectLayer)
2. 커스텀 타일 레이어를 추가합니다.
3. 커스텀 타일 레이어의 콜백 발생시 HTML 오브젝트를 생성합니다.
4. 생성한 오브젝트를 커스텀 타일 레이어가 아닌 별도로 생성한 오브젝트 레이어에 추가합니다.

위 단계를 적용해보셔서 문제가 발생하는 경우 추가로 말씀 부탁 드립니다.
향후 HTML 오브젝트의 서비스 레이어 적용에 대해서 내부적으로도 면밀히 검토해보겠습니다.

감사합니다.

**Comment by avamk2** [comment]
안녕하세요

해당 기능에 대한 화면내 가시화 처리 및 화면밖 처리에 대한 부분을 수정하여 업데이트 하였습니다.
