### ISSUE TITLE
2.2.1 (Beta)에서 그림자 생성 함수가 동작하지 않는 오류

### ISSUE THREAD

**Issue by eodnjsdl7638** [EgisCorp/XDWorld#399]
엔진 버전
: XDWorld Version : 2.2.1 (Beta Released 2024-04-22)

오류 발생 API
: Module.getAnalysis().createShadow

오류 내용
: 함수 실행시 리턴되는 반환 값이 true로 나오지만, 그림자가 생성되지 않습니다.

2.21 버전일때
![1](https://github.com/EgisCorp/XDWorld/assets/168795022/f803c3e2-99ba-4f2a-a8f7-169b7f387a80)

1.49 버전일 때
![2](https://github.com/EgisCorp/XDWorld/assets/168795022/9f92b81e-bde1-4787-8c9d-07cbcaa3e353)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

그림자 생성시 그림자를 어떤 형태로 그릴것인지 설정해야합니다.

// 1: 그림자, 2: 초기화, 3: 라인, 4: 면
Module.getAnalysis().setShadowDrawMode(1);

추가적으로 지형 그림자는 Module.getAnalysis().setTerrainAnalysis(true); 로 on/off 할수있습니다.

감사합니다.
