### ISSUE TITLE
태풍 이동 완료 후 마지막 위치에 정지해 있는 기능 요청

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#4]
안녕하세요. 바이브컴퍼니입니다.

moveStart()를 이용하여 태풍을 자동으로 이동시켰습니다.
이동이 완료되면 시작위치로 돌아오도록 되어 있는거 같습니다.
맞나요?

**이동이 완료되면 그냥 그 자리(마지막 위치)에 있으면 좋겠습니다.**
업무 성격상 이 기능이 필요해서 요청합니다.

그럼,...

**Comment by EgisCorp** [comment]
안녕하십니까, 문의주신 내용 답변드립니다.

최근 배포 된 v_0.1.0 버전에
태풍 자동 이동 완료 후 첫 위치로의 복귀 여부를 설정할 수 있도록
JSTypoon의 API setMoveFinishReturn가 추가되었습니다.

<예시> typoon.setMoveFinishReturn(false);

true로 설정 시 첫 위치로 복귀하고, false로 설정 시 마지막 위치에서 정지합니다.
v_0.1.0 버전 엔진으로 적용 부탁드립니다.

감사합니다.

**Comment by HyunSeongKil** [comment]
이게 최근 버전(v_0.1.0)인가요?
![image](https://user-images.githubusercontent.com/38479834/119456638-d5c1c000-bd75-11eb-8909-84232b3c71d2.png)

**Comment by HyunSeongKil** [comment]
확인했습니다.
