### ISSUE TITLE
가시권분석기능 문의사항 

### ISSUE THREAD

**Issue by Parster** [EgisCorp/XDWorld#40]
안녕하세요 이지스 박규호주임입니다.
고스트심볼으로 3DS 파일을 올리고 그 파일에 가시권분석기능을 사용하려고 합니다.
혹시 ELT_GHOST_3DSYMBOL레이어 속성에 변경해줘야 하는 부분이 있는지  궁금합니다.
현재 모습입니다.
![가시권분석 오류](https://user-images.githubusercontent.com/86399390/123216392-7259b800-d504-11eb-914d-5724864c6148.PNG)

**Comment by YangHeeBong** [comment]
현재 조망권 분석 지원
 - 건물 편집
 - 건물 타일 레이어
 - LOD 레이어
 
에 대한 조망 분석을 지원하고 있습니다.

관련 내용을 정리하여 Load Object에 대한 조망권 분석 기능 내용을 처리하겠습니다.
