### ISSUE TITLE
타일 레이어 min lev 설정보다 더 낮은 레벨에도 삭제되지 않는 현상

### ISSUE THREAD

**Issue by leepulum727** [EgisCorp/XDWorld#400]
엔진 버전
:
XDWorld Version : 2.2.3 (Beta Released 2024-05-10)
오류 발생 API
:
 Module.getTileLayerList().createXDServerLayer
오류 내용
:

커스텀 타일 레이어 생성 후 지도 줌 아웃 시 설정한 min lev 보다 레벨이 낮아 졌음에도 삭제되지 않아 레이어 겹치는 현상
(아래 설정은 10 lev)
![image](https://github.com/EgisCorp/XDWorld/assets/73877693/0b95e314-97e5-4a82-bccc-83a8b1bf531d)

**Comment by avamk2** [comment]
안녕하세요

오류사항을 확인하여 5월 24일자 정기배포버전에 수정되어 포함되었습니다.
