### ISSUE TITLE
화면분할기능 투명도 설정 

### ISSUE THREAD

**Issue by eeeeekl** [EgisCorp/XDWorld#401]
엔진 버전
:

오류 발생 API
: 화면분할 

오류 내용
: 
지형투명도 설정 후 화면분할을 실행하면 지도 이동 시 잔상이 남는 현상이 있습니다.
샌드박스의 화면분할 기능에서 Module.XDESetPlanetTransparecny부분만 추가하여 테스트 한 영상 첨부합니다

https://github.com/EgisCorp/XDWorld/assets/145413670/08703bef-a77b-45cd-8f7c-182a8e5e3b0f

**Comment by YunSumin** [comment]
안녕하세요,

문의 주신 내용을 토대로 원인을 확인하여 해당 오류를 수정하였습니다.
수정 내용은 다음 엔진 업데이트에 반영할 예정입니다.
엔진 업데이트 시 다시 안내 드리겠습니다.

감사합니다.

**Comment by YunSumin** [comment]
안녕하세요, 

문의 주신 오류가 수정되어 엔진 2.4.0이 업데이트 되었습니다.
(https://github.com/EgisCorp/XDWorld?tab=readme-ov-file#update)

오류 수정을 위해 엔진 업데이트 부탁드립니다.

감사합니다.

**Comment by eeeeekl** [comment]
엔진 업데이트 후 문제 해결되었습니다! 감사합니다
