### ISSUE TITLE
TextBillBoard 텍스트 문의

### ISSUE THREAD

**Issue by HooYoungJyeon** [EgisCorp/XDWorld#402]
참고한 예제: 
https://sandbox.egiscloud.com/code/main.do?id=object_billboard_text

문의 내용:

안녕하세요. 샌드박스에 있는 billboard를 사용하는과정중, 

텍스트가 깔끔하게 출력되지않고 흐리게 나오는데, 

온전하게 나오게하려면 어떤부분을 수정해야하는지 알고싶습니다.

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 빌보드 텍스쳐는 실제 거리에 따른 폴리곤을 생성해서 표현되고 있습니다. 

즉 아래 그림과 같이 공간상 거리와 폴리곤 크기에 따라 정밀도가 정해집니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/3e8a6eb8-779d-4aa3-949a-309bece1dc0c)

이에 비해 POI는 공간상 거리가 없어 폰트 이미지가 그대로 적용됩니다.

![image](https://github.com/EgisCorp/XDWorld/assets/82924515/74d7d2ee-68f9-48d3-9bbd-67b22c97e8b0)

이로 인해서 POI와 빌보드에 따라 텍스쳐 정밀도가 찾이가 나게 됩니다.

위 질문처럼 정밀도가 높은 폰트를 생성하기 위해서는 현재 생성되고 있는 폰트 이미지 생성크기를 크게 만들고 내부에 들어가는 폰트 사이즈 도 동일하게 크게 설정 후 생성한다면 정밀한 이미지 표현이 가능합니다.

**Comment by HooYoungJyeon** [comment]
답변 감사합니다!
