### ISSUE TITLE
3D POI 기능 문의

### ISSUE THREAD

**Issue by egiskorea01** [EgisCorp/XDWorld#404]
엔진 버전
:2.3.1

문의 내용
:  https://sandbox.egiscloud.com/code/main.do?id=object_geojson_to_poi 
내용을 참고 하였습니다.
현재 POI는 2D만 지원 하는 지 궁금합니다. 
 3D POI로 위치를 표시하고 싶은데 가능한 방법이 있는지, 없다면 추후에 3D POI 기능이 생길 수 있는 지 궁금합니다.

**Comment by YunSumin** [comment]
안녕하세요,

말씀해주신 3D POI는 현재 구체적인 구현 계획은 없으나,
대신 고스트심볼 오브젝트를 거리와 상관없이 같은 크기를 유지하도록 설정하는 옵션을 추후 제공 드릴 예정입니다.

POI 오브젝트는 특성 상 카메라와 대상의 거리와 무관하게 크기가 유지되는데
위 옵션을 활용하신다면 POI의 특성을 유지하면서도 3D 객체 표현이 가능할 것으로 예상됩니다.

차후 기능이 업데이트되면 다시 안내드리겠습니다.

**Comment by YunSumin** [comment]
문의 주신 3D POI 관련하여 활용 가능한 기능이 업데이트되어 안내 드립니다.

아래 URL은 고스트심볼을 활용하여,
카메라-오브젝트 거리와 상관 없이 크기를 고정해 표출하는 샌드박스 예제입니다.
https://sandbox.egiscloud.com/code/main.do?id=object_ghostsymbol_screen_fixed_size

화면 기반으로 크기를 유지하는 POI 특성을 유지하면서 오브젝트를 3차원으로 표출할 수 있습니다.

예제 참고 부탁드립니다.

감사합니다.
