### ISSUE TITLE
커스텀타일레이어 지도 렌더링 지연시간 문의

### ISSUE THREAD

**Issue by csy4723** [EgisCorp/XDWorld#405]
엔진 버전
:XDWorld Version : 2.3.1 (Released 2024-05-31)

문의 내용
:
커스텀 타일 레이어를 정해진 시간마다 갱신하기 위해 `Module.getTileLayerList().nameAtLayer('layerName').ReloadTiles();` 를 사용하고 있습니다. 

그런데 지도 위의 마우스 움직임에 따라 렌더링 지연시간에 차이가 있어 문의 드립니다. 

![shortTime](https://github.com/EgisCorp/XDWorld/assets/96081821/c45622cd-3e42-403d-b8dd-893dba6735ec)
지도 위에서 마우스를 움직일 경우엔, 렌더링에 약 2초 정도 소요되지만 

![댐·하천 물관리 플랫폼 외 페이지 14개 - 개인 - Microsoft_ Edge 2024-06-20 16-08-12](https://github.com/EgisCorp/XDWorld/assets/96081821/dfc82132-9313-44b6-a039-b3fad0e5bc33)
지도 위에 클릭, 이동, 스크롤과 같은 마우스 움직임이 없다면 약 10초 정도로 지연 시간이 늘어납니다.

마우스 움직임이 없을 경우에도 렌더링 시간을 짧게 줄이는 방법이 있는지 여쭙고 싶습니다.

**Comment by YunSumin** [comment]
안녕하세요,

현재 엔진에서는 브라우저에서 마우스나 기타 조작이 없는 경우,
시스템 리소스를 절약하기 위해 화면 갱신을 중단하고 지도 조작이 있을 때 다시 화면 갱신을 시작하고 있습니다.

마우스 움직임이 있을 때 화면 갱신 시간이 빠른 이유는 조작을 인식하여 화면 갱신이 지속적으로 이루어지기 때문입니다.
별도의 조작 없이 API를 통해 화면 갱신을 원하시는 경우에는 아래의 API를 호출하시면 됩니다.
``` javascript
Module.XDRenderData();
```

원하시는 시점에 위 API 호출을 부탁 드립니다.

감사합니다.

**Comment by avamk2** [comment]
안녕하세요

커스텀타일 레이어의 레이어에 객체를 등록하는 부분에서 화면랜더링을 자동으로 호출 할 수 있도록 수정되었습니다.
해당빌드 버전은 금주 엔진 추가배포사항에 포함될 예정입니다.

감사합니다.

**Comment by YunSumin** [comment]
이번 엔진 버전(2.4.1)에서 커스텀 타일 레이어 객체 등록 시 렌더링 상태가 되도록 적용 되었습니다.
최신 엔진으로 업데이트 부탁 드립니다.

감사합니다.
