### ISSUE TITLE
전체 폴리곤 투명도 조절

### ISSUE THREAD

**Issue by egiskorea01** [EgisCorp/XDWorld#406]
엔진 버전
:2.4.0

문의 내용
:
https://sandbox.egiscloud.com/code/main.do?id=object_polygon_height
https://sandbox.egiscloud.com/code/main.do?id=object_polygon_color
을 참조 하였습니다.

polygon 색상 예제 처럼 polygon 오브젝트를 띄웠습니다.
polygon 전체의 투명도는 조절 가능 여부에 대해 문의 드립니다.
레이어 투명도 조절 setAlpha는 polygon 투명도는 적용이 안되는 것 같습니다 .

var polygonStyle = new Module.JSPolygonStyle();
polygonStyle.setFillColor(color); 

을 사용하기에는 polygon Object 수도 많고 Object 색상이 다양해서 전체적으로 한번에 투명도 조절을 적용하고 싶은데 해당 기능이 있을까요 ?

**Comment by hjaejae** [comment]
현재 색상은 RGB 값과 함께 A(투명도 값)이 같이 적용되는 상태입니다.

그래서 색상 변경 시에 
1. 전체 색상 변경
2. 레이어 색상 변경
3. 객체 색상 변경
에 대해서 어떠한 우선 순위로 색상이 적용되어야 하는지에 대해서 논의 중에 있습니다.

레이어 투명 값에 한해서는 현재 특정 레이어 타입에 대하여 적용되어지고 있는 상황이며
일반 JSPoygon도 적용 할 지에 대해서는 내부적으로 논의가 있어야 합니다.
RGB 값이 아닌 투명도 값 조절에 대해서 일반 폴리곤 객체 적용 여부는 논의 후에 적용 시키도록 하겠습니다.

적용이 완료된 후에 알려드리도록 하겠습니다.

**Comment by hjaejae** [comment]
JSLayer의 setAlpha API로 레이어 전체 투명도를 조절 할 수 있도록 변경하였습니다.
