### ISSUE TITLE
반경그리기 문의

### ISSUE THREAD

**Issue by eeeeekl** [EgisCorp/XDWorld#407]
엔진 버전
:

오류 발생 API
:

오류 내용
:
반경그리기 기능이 필요하여 샌드박스에서 확인 중에 
라인이 균일하게 그려지지않는 부분을 확인했습니다. 
이 부분은 오류인건가요?

https://github.com/EgisCorp/XDWorld/assets/145413670/23179f6f-f08c-4f2a-858c-4b79367eede9

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

이야기 하신 현상은 폴리곤과 외각선을 따로 생성 후 그리는 부분에서 발생하는 부분 같습니다. 

이부분은 추후 라인과 폴리곤 개별 가시화 방법이 아닌 다른 방법으로 진행 후 공지 드리겠습니다.

**Comment by EgisCorp** [comment]
현재 일정 상 무리가 없다면 8월 초 작업 후 정식 엔진 배포에 관련 기능을 첨부하겠습니다.
