### ISSUE TITLE
createHTMLObject()로 POI 생성 후 마우스오버 시 z-index 변경 방법 문의

### ISSUE THREAD

**Issue by Young-Ju98** [EgisCorp/XDWorld#408]
엔진 버전
: 2.4.0 (Released 2024-06-28)

문의 내용
: 안녕하세요.
createHTMLObject()로 poi 생성 후 poi에 마우스오버 시 [그림1]처럼 서브 팝업이 뜨는 기능을 구현중인데 각 html레이어에 z-index가 설정되다보니 서브 팝업 위로 아이콘이 뜨는 현상이 있습니다. 혹시 마우스오버 시 해당 아이콘의 z-index를 높일수있는 기능이 있을까요?

[그림 1]
![image](https://github.com/user-attachments/assets/148c393c-01c8-4532-945b-e91f98dce071)

**Comment by YunSumin** [comment]
안녕하세요,

문의 주신 내용은

1. HTML 오브젝트로 POI(파란색 역삼각형 아이콘) 다수 생성
2. POI에 마우스 오버
3. POI 위치에 텍스트 서브 팝업 표출
4. 텍스트 서브 팝업이 POI 아래 묻혀 텍스트 일부가 가림

과정으로 이해하였습니다.

말씀하신 내용으로는 텍스트 오브젝트가 HTML 오브젝트인지 알 수 없어 정확한 답변은 어려우나,
만약 HTML 오브젝트가 아닌 일반 HTML 오브젝트인 경우 z-index 값을 아이콘보다 충분히 크게 높여주시고
만약 HTML 오브젝트인 경우 아래 이슈를 참조하시어 z-index 값이 조정되도록 구성 부탁 드립니다.

아래 이슈는 마우스 이동 시 콜백 함수를 발생하여 특정 엘리먼트의 z-index 값을 임의 조정하는 내용입니다.
https://github.com/EgisCorp/XDWorld/issues/357

혹시 이슈를 통해 해당 현상을 해결할 수 없거나 다른 문의 내용이 있는 경우 말씀 부탁 드립니다.

**Comment by Young-Ju98** [comment]
안녕하세요. 
현재 createHTMLObject()의 파라미터에 element안에 poi를 생성하는 html과 mouseover시 뜨는 서브팝업을 같은 div에 넣어서 html 오브젝트를 생성하였습니다. 
[그림2]와 같이 callback을 통해 mouseover시 display:block이 되는 element의 id값으로 z-index를 변경하려고 코드를 짜봤는데 
[그림3]과 같이 해당 element 안에 있는 아이콘은 z-index에 맞춰 다른 아이콘들 위로 올라오는데 서브팝업인 .poi-hover-ui에 해당하는 부분은 여전히 아이콘들에 가려지는 상황입니다. 코드를 잘못 작성한 것인지 아니면 다른 문제인지 확인해 봐주실 수 있으신가요?

[그림 2]
![image](https://github.com/user-attachments/assets/ac2b50b7-320c-4c5f-a8d9-8368d34c2086)

[그림 3]
![image](https://github.com/user-attachments/assets/80a73aa7-6253-41ad-9e42-af4462ff46a8)

**Comment by EgisCorp** [comment]
createHTMLObject()을 이용해서 작성된 오브젝트는 webGL에서 사용되는 부분이 아닌 HTML element를 이용해서 작성되고 있습니다. 

현재 문제는 개발자 도구 -> elements 내부에서 등록된 ".poi-hover-ui" 를 찾고 실제 z-index를 변경되었는지 확인 하셔야 할 것 같습니다.

**Comment by Young-Ju98** [comment]
아이콘을 감싸는 div에도 z-index를 넣었더니 해결되었습니다. 감사합니다!
