### ISSUE TITLE
setText() visible level 설정 가능 여부

### ISSUE THREAD

**Issue by Young-Ju98** [EgisCorp/XDWorld#409]
엔진 버전
: 2.4.1 (Released 2024-07-05)

문의 내용
: 안녕하세요. poi object에 setText를 했을때 해당 text에 visible level을 설정하는 방법이 있는지 문의드립니다.

**Comment by egiskorea-ryong** [comment]
안녕하세요.

해당 기능은 아래와 같이 사용하시면 가능합니다.

```javascript
var poi_object = Module.createPoint("POI_OBJECT");
poi_object .setPosition(new Module.JSVector3D(126.92522784212862, 37.52163632683868, 13.357510312460363));
poi_object .setImage(ctx.getImageData(0, 0, this.width, this.height).data, this.width, this.height);
poi_object .setText("TEXT");

// 객체 LOD 처리
poi_object .setVisibleRange(true, 0.0, 100.0);
```

자세한 내용은 [메뉴얼](https://egiscorp.gitbook.io/xdworld-webgl-manual/introduce-1/object/jspoint#setvisiblerange-enable-min-max-boolean)을 참고해주세요.

감사합니다.

**Comment by Young-Ju98** [comment]
저건 poi 자체에 visible 처리를 하는것 같은데 제가 문의드린것은 poi는 그대로인데 poi에 추가한 text에 visible level이 설정가능한지 입니다!

**Comment by egiskorea-ryong** [comment]
현재 말씀하신 기능은 없습니다.

POI 객체에서 이미지, 텍스트를 따로 구분하여 LOD 처리하지 않습니다.

감사합니다.

**Comment by avamk2** [comment]
안녕하세요 해당부분에 대해서는 현재 내부개발이 끝났으며 향후 배포버전에 포함됩니다.

**Comment by Young-Ju98** [comment]
감사합니다!
