### ISSUE TITLE
반경 측정과 거리 측정 동시 사용 여부 

### ISSUE THREAD

**Issue by csy4723** [EgisCorp/XDWorld#410]
엔진 버전
: 2.4.1

문의 내용
:  반경 측정과 거리 측정 기능을 위해  각각 MML_ANALYS_AREA_CIRCLE와 MML_ANALYS_DISTANCE_STRAIGHT 마우스 모드를 사용하고 있습니다. 

그런데 거리 측정 후 반경 측정을 하면 거리 라인이 사라지고, 반경 측정 후 거리 측정을 하면 반경 라인이  사라집니다.

각 각 측정 결과가 동시에 보이도록 할 수 있는 방법이 없을까요?

**Comment by avamk2** [comment]
안녕하세요.

 마우스 모드는 사용자가 했던 액션을 기억하는 개념으로 제작된 UI가 아니라서 모드 변경시 기존 동작한 기능을 리셋하게 됩니다. 가장 단편적이지만 가장 명확한 개발입문자를 위한 기능으로 설계했기 때문입니다.

그래서 요청하신 기능처럼 복합적인 기능을 활용하고자하는 분들을 위해서 샌드박스에 샘플로 

거리측정 : https://sandbox.egiscloud.com/code/main.do?id=analysis_measure_distance

반경측정 : https://sandbox.egiscloud.com/code/main.do?id=analysis_measure_radius

위 샘플들이 마우스 모드를 사용하지 않는 마우스 동작을 직접 제어하여 측정 객체를 만들게 됩니다.

이러한 활용으로 저희가 입문용으로 제공하는 기능 이상으로 활용해 보시기 바랍니다.
