### ISSUE TITLE
HTML 오브젝트에 피킹결과 반환 api 가능여부 문의

### ISSUE THREAD

**Issue by Young-Ju98** [EgisCorp/XDWorld#413]
엔진 버전
: 2.5.0 (Released 2024-07-26)

문의 내용
: 안녕하세요. HTML 오브젝트로 레이어를 그린 뒤 해당 레이어에 마우스오버를 하면 서브팝업이 뜨는 기능을 개발하고있습니다.
POI레이어는 PICK함수를 통해 해당 피킹 지점에 대한 정보를 가져오는데 HTML레이어도 해당 기능이 되는것인지 문의드립니다.
혹시 HTML레이어는 해당 기능이 안된다면 어떻게하면 피킹기능을 사용할수있을지도 알려주시면 감사하겠습니다!

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

먼저 명시하고 넘어가야할 개념이 있어서 설명드리겠습니다. 

HTMLObject는 Web Control으로 HTML영역에서 div를 생성 후 관리하는 부분입니다. 

즉 피킹과 같은 마우스 이벤트는 Web Control에서 제공하는 onClick, onmouseover, onmouseout 등과 같은 이벤트로 기능 처리가 가능합니다. 

간단히 [샌드박스](https://sandbox.egiscloud.com/code/main.do?id=object_html) 샘플에서 
```jsscirpt
layer.addObject(object, 0);
// Output string to the HTML Element corresponding to the element tag
element.style.color = "rgba(255,255,255,1)";
element.textContent = "click Me";
// Link HTML Element corresponding to the element tag with onclick event provided by HTML

// 기존 이벤트
//element.onclick = clickdivcontrol;
// 수정 이벤트
element.onmouseover = clickdivcontrol;
```
변경으로 pick 이벤트 처리가 가능합니다.

또한 HTMLObject 을 위치를 알고 싶다면 div에 등록된 style.left와 style.top를 통해 위치 좌표를 얻을수 있습니다.

```
// 정렬에 따른 위치 보간 필요
var mapPosition = Module.getMap().ScreenToMapPointEX(left, top);
```

**Comment by Young-Ju98** [comment]
덕분에 해결되었습니다 감사합니다!
