### ISSUE TITLE
고스트심볼 관련 문의드립니다.

### ISSUE THREAD

**Issue by jangseonghyun** [EgisCorp/XDWorld#414]
엔진 버전
: XDWorld Version : 1.58.0 (Released 2024-1-26)

문의 내용
: 
안녕하세요. 
선택된 지역에 3DS 파일 기반 고스트 심볼 오브젝트를 생성하고 있습니다.
해당 지역에 오브젝트를 생성하기 전에 실제로 건물을 지을 수 있는지 판별 후 생성하려고 하는데, 반환되는 경도, 위도 값으로 해당 기능을 구현하기에는 무리가 있다고 판단돼서, 생성된 오브젝트의 지오메트리를 반환받을 수 있는지 궁금하여 문의드립니다.

<img width="391" alt="image" src="https://github.com/user-attachments/assets/01f1d5de-8bcc-4691-9f47-9985e5cd2312">

**Comment by HeoTaeYang** [comment]
안녕하세요, 문의에 대해 답변 드립니다.

현재 엔진에서는 말씀하신 기능을 제공하고 있지 않습니다.
후처리가 끝난 폴리곤(삼각형) 배열을 반환하는 방식으로, 지오메트리를 제공하는 API를 추가하도록 하겠습니다.

차후 기능이 업데이트되면 다시 안내드리겠습니다.

**Comment by jangseonghyun** [comment]
답변 감사합니다. 
9월 말까지 해당 기능 완료를 요청받았는데, 혹시 계획중이신 예정일이 있을까요?

**Comment by HeoTaeYang** [comment]
안녕하세요,  일정 조율 과정에서 궁금한 점 생겨 질문드립니다.

오브젝트를 생성하기 전 **실제로 건물을 지을 수 있는지 판별**, 즉 주변 오브젝트나 지형과 충돌하는지 확인하는 기능을 원하신다고 이해했습니다.
서비스 구조상 오브젝트의 지오메트리 정보를 받더라도, 결국 충돌 판정은 위경도로 정의된 지구본에서 계산하여야 하므로, 활용하기가 매우 어렵습니다.

만약 **생성하고자 하는 오브젝트와 다른 오브젝트/지형의 충돌 여부 확인**만을 원하신다면, 해당 기능으로 만들어 드릴 수 있습니다.

다시 답변주시면, 일정 안내드리겠습니다.

**Comment by HeoTaeYang** [comment]
친절한 답변 감사합니다.

처음 말씀드렸던 대로, 지오메트리 제공하는 API 추가하겠습니다.

9월 13일까지 작성 후 배포할 예정이니, 일정에 참고바랍니다.

**Comment by jangseonghyun** [comment]
감사합니다

**Comment by plusvolts** [comment]
안녕하세요 서울사무실 김상민 차장입니다. 질문 올리러 들어왔다가 도움될까 싶어서 글 남겨드립니다.  비슷한 기능으로 필지와 객체 포함여부에 대한 충돌 검토하는 API를 22년에 최성룡 과장님이 API로 구현해 주셨던 적이 있습니다. Analysis 클래스의 checkInsideArea 함수였는데 남아있다면 활용하면 좋고 아니면 참고해서 구현해주시면 원하는 기능을 더 쉽게 구현할 수 있지 않을까 싶습니다. 

![image](https://github.com/user-attachments/assets/d8ba8c27-6585-4557-a80c-058a01487e15)

**Comment by HeoTaeYang** [comment]
안녕하세요. 먼저 친절한 답변에 감사드립니다.

언급하신 JSAnalysis::checkInsideArea()는 현재 엔진에서도 사용 가능합니다.
문의의 요구사항을 충족하는 기능이라 판단하여, 아직도 유효하다면 사용하실 수 있습니다.

API 검증 후 다시 말씀드리겠습니다.

**Comment by HeoTaeYang** [comment]
안녕하세요. API 검증이 마무리되어 답변 다시 올립니다.
언급하신 JSAnalysis::checkInsideArea()는 현재 사용 가능합니다.

해당 API의 정보는 아래와 같으며, 문서에도 업데이트할 예정입니다.
```javascript
Boolean JSAnalysis::checkInsideArea(pointList, selectedObject, isCompletely);
```
- `pointList(JSVec3Array)`: 영역의 위치 데이터 리스트
- `selectedObject(JSObject)`: 영역에 포함되는지 아닌지 판별할 오브젝트
- `isCompletely(boolean)`: 오브젝트 충돌 판별 옵션(0: 완전히 영역 안에 포함되어야 true, 1: 일부만 포함되어도 true)
- 영역에 포함될 경우 `true`, 아닐 경우 `false` 반환

적절한 사용법에 관해서는, [오브젝트 영역 포함 판별](https://sandbox.egiscloud.com/code/main.do?id=analysis_object_inside_area)샌드박스를 확인해주시기 바랍니다.
