### ISSUE TITLE
object.setSelectable 함수 적용 안되는 문제

### ISSUE THREAD

**Issue by 2HyeonBin** [EgisCorp/XDWorld#416]
엔진 버전
: 2.6.0

오류 발생 API
: setSelectable

오류 내용
:
안녕하세요!

특정 레이어에 setSelectable(false) 함수를 적용하였을때 해당 레이어 선택 비활성화 기능은 잘 작동합니다.

그러나 특정 오브젝트에 setSelectable(false) 함수를 적용해도 해당 오브젝트가 여전히 선택되고 있습니다.
해당 오브젝트에 getSelectable 함수로 상태 확인 결과 false로 나오지만 오브젝트는 여전히 선택됩니다.

해당 오류 확인 부탁드립니다!
![image](https://github.com/user-attachments/assets/c6aa4fac-620f-4a7d-809c-c36067f5d44e)

**Comment by hjaejae** [comment]
어떤 타입에 레이어와 객체인지 말씀해주시면 더 확실한 테스트가 가능할 것 같습니다.

**Comment by hjaejae** [comment]
오늘 2.6.1 버전에 업데이트 되었습니다.

**Comment by 2HyeonBin** [comment]
감사합니다~😀
