### ISSUE TITLE
xnd 패킹 작업 타일맵 미표출 오류

### ISSUE THREAD

**Issue by 2HyeonBin** [EgisCorp/XDWorld#417]
엔진 버전
: 2.6.1

오류 발생 API
: createXDServerLayer

오류 내용
:
안녕하세요!

xnd로 패킹 작업된 타일맵 데이터가 지도에 표출이 안되고 있습니다.
getObjects() 함수로 확인 결과 오브젝트는 존재하지만 가시화가 되지않습니다.

dat 형식으로 표출 시 대부분의 오브젝트는 가시화가 되지만 일부 오브젝트는 표출되지 않습니다.
(빌더로 확인 시 정상적으로 모두 표출됩니다.)

해당 타일맵 데이터는 필요시 메일로 전달드리도록 하겠습니다!

**Comment by EgisCorp** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

가시화 엔진에서 제공하는 getObjects()를 통해 객체 존재하는지와 빌더 가시화 확인 되었지만, 가시화 엔진에서 비가시화 되는 부분은 시설물 객체 크기와 관련된 부분으로 보입니다.

가시화 엔진에서는 아래 그림처럼 공간 영역을 타일 단위로 나누어 시설물을 저장한 후 가시화하는 방식을 사용하고 있습니다.

![image](https://github.com/user-attachments/assets/0d37b90c-028d-45b0-88db-7e4c94fda28d)

이때 사각형으로 구성된 타일 크기와 시설물 크기를 비교하여, 타일 크기에 비해 너무 작은 시설물에 대해서는 가시화를 진행하지 않고 생략하는 기능이 있습니다.

생략 이유는 좀더 가시화 엔진 성능 향상을 목표로 하고 있습니다.

만약 아래 소스 코드를 추가 후 xnd 패킹으로 작성된 타일맵 데이터가 동일한 증상이 있다면 연락 주시기 바랍니다. 

```javascript
Module.getMap().setDrawLevelVisible(false);
```

**Comment by 2HyeonBin** [comment]
알려주신 "Module.getMap().setDrawLevelVisible(false);" 코드를 추가해도 동일하게 표출이 안되고 있습니다!

**Comment by EgisCorp** [comment]
그럼 타일 데이터를 확인해봐야 할것 같습니다.

외부에서 접근 가능한 서버 정보를 알려주실수 있나요??

보안 데이터라면 ggii9911@egiskorea.com 메일로 보내주시면 테스트 해보겠습니다.

**Comment by 2HyeonBin** [comment]
데이터와 정보 메일 드렸습니다!

**Comment by EgisCorp** [comment]
현재 두 가지 레이어에 대한 오브젝트 박스 정보를 먼저 안내드리겠습니다.

### 1. DAT 시설물 레이어

 ![dat 객체 불러오기](https://github.com/user-attachments/assets/7082f977-4f8d-45c8-b61b-b592bf8331d8)
<dat 레이어 객체 박스 정보>

### 2. XND 시설물 레이어

![xnd 객체 불러오기](https://github.com/user-attachments/assets/241b6f8f-d746-4189-9f30-6e94f746174f)
<xnd 레이어 객체 박스 정보>

각 정보를 통해 XND로 구성된 객체 위치가 어긋남을 확인하였습니다.

세부적으로 데이터 요청 및 객체 생성 모듈을 확인한 결과, DAT와 XND 박스 정보는 동일하지만 추가로 요청된 XDO 파일에서 차이가 발생하는 것을 확인하였습니다.

### 1. DAT 시설물 레이어
DAT 파일 포맷을 구성하는 객체 정보에서 파일 박스 정보를 사용하지 않고, 추가로 요청된 XDO 파일에서 구성된 박스 정보를 적용.

### 2. XND 시설물 레이어
XND에서 구성된 박스 정보를 그대로 사용.

이러한 결과를 얻었습니다.

따라서 추가로 요청 사항이 있습니다.

- 사용하신 빌더의 버전을 알려주시기 바랍니다.
- 만약 최신 빌더가 아닌 과거 버전의 빌더를 사용 중이시라면, 최신 버전 빌더로 재가공한 후 그 결과를 확인해주시기 바랍니다.
- 최신 빌더로 가공된 데이터를 웹 또는 빌더에서 가시화할 때 어느 쪽에서라도 가시화가 정상적으로 이루어지지 않으면, 해당 데이터를 공유해주시기 바랍니다.

**Comment by YangHeeBong** [comment]
원본 파일을 통해 빌더 가공 후 결과 입니다.

### 1. dat 가시화
![dat](https://github.com/user-attachments/assets/f2600a5d-f9ba-4bf7-b117-533f734b2a45)
### 1. xnd 가시화
![xnd](https://github.com/user-attachments/assets/b6865f96-b346-4975-8ffa-d53bbeb78269)

둘다 정상적으로 가공과 가시화가 성공한것을 확인 하였습니다.

빌더 릴리즈 업데이트예정 5.1.9에 관련 내용을 포함해서 처리하도록 하겠습니다. 

불편하시겠지만 3ds -> xdo 가공 -> xnd 가공 순으로 다시 작업 해주시기 바랍니다.

**Comment by 2HyeonBin** [comment]
넵! 감사합니다
