### ISSUE TITLE
위치 이동 문의

### ISSUE THREAD

**Issue by egiskorea01** [EgisCorp/XDWorld#418]
엔진 버전
:2.6.1

문의 내용
:Module.getViewCamera().moveLonLatBoundary() 로 위치 이동을 하고 난 뒤에 Module.getViewCamera().setLocation() 을하면 검은 화면이 나오는데 왜 그러는 건가요 ?

Module.getViewCamera().moveLonLatBoundary(new Module.JSVector2D(129.1882639, 34.9184028), new Module.JSVector2D(128.4499306, 35.6000694));
로 이동 후에
Module.getViewCamera().setLocation(new Module.JSVector3D(129.12089, 35.13420003398368, 500));
로 이동을 하려고 했는데 검은 화면이 나옵니다.

**Comment by EgisCorp** [comment]
안녕하세요. 현재 이슈에 대해서 답변드리겠습니다.

현재 문제는 위치 중심점에 불일치로 생기는 문제로 setLocation 동작 시 위치 중심정 갱신하도록 api를 수정하여 아래 영상과 같이 처리 하였습니다.

https://github.com/user-attachments/assets/79a42b8c-0ea5-42a7-83c7-afed921c7693

추후 엔진 업데이트를 통해 문제 해결이 가능합니다.

**Comment by YangHeeBong** [comment]
이번주 업데이트 예정 2.6.2 릴리즈 엔진에 관련 내용이 적용됩니다.
