### ISSUE TITLE
카메라 이동 시 지형 깨지는 현상

### ISSUE THREAD

**Issue by 2HyeonBin** [EgisCorp/XDWorld#419]
엔진 버전
: 2.6.1

오류 발생 API
: setLocation

오류 내용
: 
안녕하세요!

아래 영상과 같이 카메라 이동 직후 지형이 깨지는 형상이 있습니다.
마우스 클릭 시 바로 정상적으로 돌아오긴 하지만, 별도의 조작 없이도 정상적으로 표출되어야 할 것 같습니다.

엔진 버전별로 테스트 결과 2.4.2 버전까지는 해당 문제가 발생하지 않고
그 이상 버전(2.5.0~)부터 해당 문제가 발생하고 있습니다.

확인 부탁드리겠습니다!

https://github.com/user-attachments/assets/c2b74980-2f8d-471a-819a-9c702f2e2574

**Comment by EgisCorp** [comment]
#418과 동일한 증상으로 관련 답글을 통해 처리하였습니다.

추후 엔진 업데이트를 통해 문제가 해결될 예정입니다.

**Comment by 2HyeonBin** [comment]
넵 감사합니다!
