### ISSUE TITLE
주변 지형을 고려한 평탄화

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#42]
안녕하세요. 혹시 지구계획 관련 기능을만드는데 polygon 자료를 입력으로 하여 해당 영역을 terrain을 평평하게 만들어 주는 기능이 필요합니다. 어떻게 가능할까요??
![image](https://user-images.githubusercontent.com/3315478/124245245-c561e980-db5a-11eb-80fd-1f0c145ab2a6.png)
평평해지는 기준은 평지의 평균 맞큼만 맞추고 차이가 많이나는 부분의 경우 보간이 되어 부드럽게 보이면 좋을꺼 같습니다

**Comment by avamk2** [comment]
안녕하세요 의견주신부분에 대해서 내부적으로 검토를 통해서 알아보았지만 지형 처리에 대해서는 단기간 진행하기 어려우며 요청사항이 추상적인 사항이 많아서 진행하기 어렵다고 판단됩니다.

**Comment by YunSumin** [comment]
금일 회의를 통해 전달해주신 사항을 토대로 참고하실 수 있는 샘플 URL을 전송 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=analysis_terrain_edit

엔진에서 땅을 성토/절토하는 API에 대한 샘플입니다.

코드 중
Module.getEditTerrain().create(Module.getMap().getInputPoints(), height, angle); 부분에서
첫번째 파라미터로 평탄화 하고자 하는 폴리곤 영역의 좌표,
두번째 파라미터로 평탄화 지형 고도 (해발고도로 입력합니다.)
세번째 파라미터로 평탄화 영역 가장자리와 주변 지역의 경사 각도 를 입력합니다.

다만 지형 DEM 데이터를 직접 편집하는 기능이 아니기 때문에
지도를 다시 부르는 경우 편집한 지형이 초기화 되는 점 참고 부탁 드립니다.

**Comment by YunSumin** [comment]
금일 회의를 통해 전달해주신 사항을 토대로 참고하실 수 있는 샘플 URL을 전송 드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=analysis_terrain_edit

엔진에서 땅을 성토/절토하는 API에 대한 샘플입니다.

코드 중
Module.getEditTerrain().create(Module.getMap().getInputPoints(), height, angle); 부분에서
첫번째 파라미터로 평탄화 하고자 하는 폴리곤 영역의 좌표,
두번째 파라미터로 평탄화 지형 고도 (해발고도로 입력합니다.)
세번째 파라미터로 평탄화 영역 가장자리와 주변 지역의 경사 각도 를 입력합니다.

다만 지형 DEM 데이터를 직접 편집하는 기능이 아니기 때문에
지도를 다시 부르는 경우 편집한 지형이 초기화 되는 점 참고 부탁 드립니다.

**Comment by loeaf** [comment]
MinMax Boundary도 좋지만 업무에 필요한 내용은 Multipoint(Polygon) Boundary가 될 꺼 같습니다 ㅎㅎ..
해당 기능을 통해서 절토를 하고 위에 Tile 2DLyer를 씌우고 3d객체를 배치할 수 있다면 문제가 없을것으로 보입니다!
답변 감사합니다!
![image](https://user-images.githubusercontent.com/3315478/125913649-be6e972e-daed-43d0-9264-8d5ffedc46fd.png)

**Comment by YunSumin** [comment]
현재 샘플에서는 boundary 지정과 함께 폴리곤으로도 영역을 설정하실 수 있습니다.

![image](https://user-images.githubusercontent.com/82925313/125914695-da64f554-1fdc-47c8-bab1-638ec6fc62da.png)

create API를 사용하시면 말씀하신 자유영역 성절토가 가능하므로 이점 참조 부탁드립니다.

**Comment by loeaf** [comment]
감사합니다 혹시 polygon 영역을 주어주고 해당 영역에대해서 고도 min, max, avg 또는 값에 대한 분포를 알 수 있는 api가 있을까요???

**Comment by YunSumin** [comment]
JSMap 클래스에 경도, 위도를 입력한 경우 고도값을 반환해주는 API가 있습니다.

Module.getMap().getTerrHeight(경도, 위도);
해당 위치의 DEM 고도 값이 반환 됩니다.

다만 엔진에서 해당 위치의 DEM이 로드 된 상태여야 합니다.
카메라를 지형에서 멀리 두고 호출 할 때 해당 위치의 DEM이 상위 레벨 데이터만 있는 경우
실제 위치와 다소 차이가 있을 수 있습니다.

일정한 rect 영역을 두고 그리드 형태의 경위도 좌표를 구성하신 후에
위 API로 고도값을 반환하여 min, max, avg 분포를 계산하는 방법을 사용하실 수 있을 것 같습니다.

**Comment by loeaf** [comment]
감사합니다 ㅎㅎ 구현해보도록 하겠습니다

**Comment by loeaf** [comment]
크으.... 어메이징 합니다 
혹시 바닥에 색칠되는거는 없앨 수 없을까요?
그리고 연산하는데 시간이 너무 오래걸리는데... 혹시 다른 방안이 있을까요???
![image](https://user-images.githubusercontent.com/3315478/126274990-e47cacb7-319c-4ed5-990d-801c913068f0.png)

**Comment by YunSumin** [comment]
성절토 지면의 색상 설정은 현재 API가 없어 API 추가 후 안내 드리겠습니다.
getTerrHeight API는 지형을 검색할 때 엔진에 로드 된 지형 타일 전체를 대상으로 고도 값을 검색하므로 다른 API에 비해 연산량이 많습니다.
호출하는 버텍스 수를 다소 줄여 호출 부탁드립니다.

**Comment by loeaf** [comment]
제안해주시는 방법에는 아래와 같은 문제가 있어 고민이 필요할꺼 같습니다.
1. 버텍수 조정을 통한 레이어로 가시화 되기위한 폴리곤과의 불일치
2. 현재 하나의 폴리곤에 대해서만 절토가 일어나는 것이 아니라 작으면 200 ~ 300개의 폴리곤에 대해서 절토가 일어날 예정

해당 방법을 고려한다면  클라우드에서 동적으로 해당 터레인정보를 받아오는게 베스트할꺼 같다는 생각이 듭니다... 버텍수 수를 줄인다고 하더라도 레이어를 켰을때 절토에 대한 많은 연산량을 커버할 수 있을꺼 같지는 않습니다. 어떻게 생각하시는지요?

**Comment by YunSumin** [comment]
문의 주신 고도 값 반환 getTerrHeight와 성절토 기능은 엔진 내 전혀 다른 기능이므로 두 API 간 직접적 연관성은 없습니다.

사용하시게 된 getTerrHeight API는 단순 성절토 시 입력할 고도 값을 계산하기 위한 것으로,
성절토를 수행하는 폴리곤 영역 전부를 입력할 필요 없이 일부 샘플링 된 버텍스만으로 유효한 평균 고도 값을 산출할 수 있을 것이라 판단되기에,
폴리곤 전체 버텍스가 아닌 그리드 형태의 경위도 좌표를 구성하셔서 평균을 구하는 방안을 제안 드렸습니다.

말씀하시는 클라우드가 DEM 서버를 말씀하시는 것이라면, 이미 이전에 속도 개선을 위해 시도한 바 있으나,
엔진 내에서 서버 단일 터레인 타일을 받아오는 통신 속도보다
엔진 내부 트리 구조로 구조화 된 타일 에서 데이터를 추출하는 것이 빠른 것으로 확인되어 API를 사용한 방식을 제안 드렸습니다.

따라서 성절토 영역 폴리곤과 getTerrHeight 지형 평균값 호출 버텍스는 꼭 일치하지 않아도 되는 점 검토 부탁 드립니다.

이 외 문의하셨던 성절토 표면 색상 설정 API는 금일 추가되었습니다.

![image](https://user-images.githubusercontent.com/82925313/126602005-183d7d43-f467-4859-85e5-2e1f1a07e22b.png)

지정하시는 색상 알파 값(첫번째 파라미터)를 0~255 사이 값으로 두시면 색상 투명도를 지정하실 수 있습니다.
http://sandbox.dtwincloud.com/code/main.do?id=analysis_terrain_edit 샘플코드 참조 부탁 드립니다.

**Comment by loeaf** [comment]
감사합니다!
