### ISSUE TITLE
모든 레이어 리스트 확인 함수 문의

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#420]
엔진 버전
: 2.6.1

문의 내용
:

시스템 상에 로딩한 모든 레이어를 확인하는 함수와
시스템 상에 로딩한 모든 레이어 중에 visible이 true 인 레이어를 한번에 확인하는 함수가 있나요?

return 되는 값이 레이어 자체의 배열이 아니라 레이어의 이름의 배열이라도 좋습니다.

**Comment by YunSumin** [comment]
안녕하세요,

레이어는 서버 기반으로 서비스 되는 타일 레이어와, 사용자가 오브젝트를 직접 추가할 수 있는 오브젝트 레이어로 나뉩니다.
각 레이어 리스트는 아래와 같이 반환할 수 있습니다.

``` javascript
var tileLayerList = Module.getTileLayerList();
var objectLayerList = Module.getObjectLayerList();
```

위 코드 실행 시 JSLayerList 객체가 반환되며, 객체는 각 타입별 레이어 정보를 포함하고 있습니다.

모든 레이어의 정보를 확인하고자 하는 경우 JSLayerList의 count API를 통해 갯수를 반환하신 후,
인덱스별로 JSLayer 객체를 반환하여 정보를 조회하는 방법을 사용하실 수 있습니다.

``` javascript
var tileLayerList = Module.getTileLayerList();
for (var i=0; i<tileLayerList.count(); i++) {
    var layer = tileLayerList.indexAtLayer(i);
    console.log(layer.getName());
}

var objectLayerList = Module.getObjectLayerList();
for (var i=0; i<objectLayerList.count(); i++) {
    var layer = objectLayerList.indexAtLayer(i);
    console.log(layer.getName());
}
```

위 코드에서는 indexAtLayer를 통해 JSLayer 객체를 순서대로 가져와 레이어 이름을 콘솔에 출력하는 코드입니다.

만약 visible이 true인 레이어만 확인하고자 하신다면,
JSLayer의 getVisible 속성을 반환하여 활용하시면 됩니다.

``` javascript
var tileLayerList = Module.getTileLayerList();
for (var i=0; i<tileLayerList.count(); i++) {
    var layer = tileLayerList.indexAtLayer(i);
    if (layer.getVisible()) {
        console.log(layer.getName());
    }
}

var objectLayerList = Module.getObjectLayerList();
for (var i=0; i<objectLayerList.count(); i++) {
    var layer = objectLayerList.indexAtLayer(i);
    if (layer.getVisible()) {
        console.log(layer.getName());
    }
}
```
