### ISSUE TITLE
jpg 타입 레이어 문의

### ISSUE THREAD

**Issue by 2HyeonBin** [EgisCorp/XDWorld#421]
엔진 버전
:2.6.2

오류 발생 API
:createXDServerLayer

오류 내용
:

안녕하세요!

```js
layer = Module.getTileLayerList().createXDServerLayer({
    url: "url",
    servername: "XDServer",
    name: "name",
    type: 10,
    minLevel: 0,
    maxLevel: 15,
});
```
위 소스처럼 레이어를 불러올때 jpg 타입의 레이어는 타입 번호가 어떻게 되나요?

**Comment by hjaejae** [comment]
jpg 타입의 레이어는 현재 존재하지 않습니다.

아래 사이트에서 "Tile Layer Type List"를 참조하시면 됩니다.
https://egiscorp.gitbook.io/xdworld-webgl-manual/introduce-1/etc/type-list

10번 타입의 명칭이 ETLT_PNG_IMAGE로 되어있지만 보통 하이브리드 이미지 레이어를 통칭하여 정의하고 있습니다.

**Comment by 2HyeonBin** [comment]
그럼 혹시

```js
var container = document.getElementById("MapContainer");
Module.initialize({
  container : container,
  terrain: {
    dem: {
	    url: "url",
	    name: "name",
	    servername: "XDServer",
    },
    image: {
	    url: "url",
	    name: "name",
	    servername: "XDServer"
    },
  },
});
```
위 소스에서 불러온 image를 onoff 할 수 있는 방법은 따로 있을까요?

**Comment by 2HyeonBin** [comment]
답변 감사드립니다!

혹시 색상 조절이 아닌 완전히 숨기고 켤 수 있는 setVisible 같은 기능은 없을까요??

**Comment by hjaejae** [comment]
지형을 완전 안보이게 하기 위해서는 아래의 코드를 쓰시면 됩니다.

```javascript
Module.SetDrawTerrain(true);
```

**Comment by 2HyeonBin** [comment]
넵 답변 감사합니다!!
