### ISSUE TITLE
모바일 거리, 면적, 고도 측정

### ISSUE THREAD

**Issue by HyeonbinLee** [EgisCorp/XDWorld#422]
엔진 버전
: 2.6.2 

오류 발생 API
: XDSetMouseState

오류 내용
:

안녕하세요!

```js
Module.XDSetMouseState(Module.MML_ANALYS_DISTANCE_STRAIGHT);
Module.XDSetMouseState(Module.MML_ANALYS_AREA_PLANE);
Module.XDSetMouseState(Module.MML_ANALYS_ALTITUDE);
```
모바일에서 거리, 면적, 고도 측정이 되지 않습니다.

```js
Module.canvas.addEventListener("Fire_EventSelectedObject", (e) => {
```
위를 사용하여 객체 클릭 이벤트를 사용하였을때도 모바일에서는 객체 선택이 되지 않습니다!

모바일에서 측정 기능, 객체 선택이 가능한 방법이 있을까요?

**Comment by HeoTaeYang** [comment]
안녕하세요.
모바일 환경에서도 클릭 이벤트를 통한 측정 및 객체 선택이 가능하도록, 해당 기능 수정하도록 하겠습니다.

차후 기능이 업데이트되면 다시 안내드리겠습니다.

**Comment by HyeonbinLee** [comment]
넵 감사합니다

**Comment by HeoTaeYang** [comment]
안녕하세요.
요청하셨던 기능을 모바일 환경에서도 사용할 수 있도록, 금일 핫픽스 업데이트를 진행하였습니다.
자세한 내용은 [2.7.1 업데이트](https://github.com/EgisCorp/XDWorld?tab=readme-ov-file#271-20241002) 항목을 확인해주시기 바랍니다.
