### ISSUE TITLE
화면 분할 기능

### ISSUE THREAD

**Issue by Parster** [EgisCorp/XDWorld#424]
엔진 버전
: 2.5.1 (Released 2024-08-09)

문의 내용
: 화면 분할 기능 사용시 중앙에서 truelayer가 가시화 됩니다 . 

화면분할 시 사용 소스 
var option = Module.getOption();
option.setSlideScreenCount(2);
option.setTwoSlideScreenDivideRate(0.5);

option.setTwoSlideScreenLayerList(
	MAPTOOL.global.leftLayer,MAPTOOL.global.rigthLayer
);

변수 값 
MAPTOOL.global.leftLayer : "gwc_wnatl_100"
MAPTOOL.global.rigthLayer : "gwc_wnatl_200"

마우스 드래그 시는  사용 소스
 Module.getOption().setTwoSlideScreenDivideRate()

https://github.com/user-attachments/assets/021da962-afd3-47d9-91bb-05fbfab67374

확인 부탁드립니다.

**Comment by avamk2** [comment]
안녕하세요 해당 부분에 대해서 확인 후 수정하였습니다.

금주 엔진 정규배포에서 반영될 예정입니다.

**Comment by Parster** [comment]
감사합니다.
