### ISSUE TITLE
현 위치 카메라 좌표 반환

### ISSUE THREAD

**Issue by egiskorea01** [EgisCorp/XDWorld#425]
엔진 버전
:2.6.2

문의 내용
:  JSVector3D (lon lat alt) 를 반환하는 getLocation() 말고
현재 카메라의 min_lon min_lat max_lon max_lat 의 정보를 얻을 수 있는 방법이 있는지 문의 드립니다.

참조 코드 
https://sandbox.egiscloud.com/code/main.do?id=camera_set_viewrect

**Comment by YunSumin** [comment]
안녕하세요,

화면 좌상단, 좌하단, 우상단, 우하단의 스크린 좌표를 맵 좌표를 변환하여
출력되는 영역을 계산할 수 있습니다.

금일 동일한 기능을 가진 샘플이 업로드되어 안내드립니다.
https://sandbox.egiscloud.com/code/main.do?id=coordinate_view_rect

카메라는 틸트를 낮추는 경우 보이는 영역이 매우 커질 수 있으므로
일정 각도 이상의 틸트를 주어 활용하시는 것을 권장드립니다.
