### ISSUE TITLE
setAlpahRender API 사용시 오브젝트 투명도 오류

### ISSUE THREAD

**Issue by M0young** [EgisCorp/XDWorld#426]
엔진 버전
: XDWorld Version : 2.7.0 (Released 2024-09-27)

오류 발생 API
: JSObject::setAlphaRender(_bSet)

오류 내용
: obj.setAlpahRender(false); 로 해당 API 사용 후 지형투명도를 조절하면 오브젝트의 알파값이 255로 변경되어 투명도가 사라지게 되는 오류가 있습니다.

**Comment by hjaejae** [comment]
안녕하세요~ 질물은 확인해본 결과
JSObject::setAlphaRender(_bSet) API는 알파값을 변경하는 작업을 하지 않습니다.
단지 알파값이 있는 객체의 그리는 순서를 변경하여 보이는 방법을 변경하는 API 입니다.

좀 더 상세한 상황이네 샘플 소스를 알려주시면 감사하겠습니다.

**Comment by hjaejae** [comment]
내용을 확인하였습니다.
이번 주에 핫 픽스로 업데이트 해드리겠습니다.
