### ISSUE TITLE
createPlaneData 기능 표출 시 데이터 개수 제한이 있는건지 문의 드립니다.

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#427]
엔진 버전
: 2.7.1

문의 내용
:
안녕하세요!

https://sandbox.egiscloud.com/code/main.do?id=effect_time_visualization
위 샌드박스를 참고하여 gridAnal 표출 테스트 중 데이터의 개수 제한이 있는 것 같아서 문의 드립니다.

우선 사용 데이터 형식은 .asc 파일이며 총 144개의 데이터가 있습니다.

2D 형식으로 표출되는 createRasterData 함수로 표출할 경우엔 144개의 데이터가 모두 문제없이 표출되지만,
3D 형식으로 표출되는 createPlaneData 함수로 표출할 경우엔 아무것도 가시화가 안되고 있습니다.

혹시나 싶어 샌드박스와 동일한 개수인 8개의 데이터만 불러온 뒤 테스트 해보니 
정상적으로 표출이 되어 혹시 개수의 제한이 있는건가 싶어서 문의 드립니다!

**Comment by avamk2** [comment]
안녕하세요 

예상하신 대로 3D 가시화 기능은 애니메이션 3D 형상 처리를 위해서 시간배열을 최대 8개까지만  처리하도록 구성되어 있습니다.

장기 개발 계획에 해당 기능에 대한 메모리 사용량과 처리방식에 대한 개선으로 갯수를 늘일 수 있도록 검토하고 있습니다.

**Comment by giyoon99** [comment]
답변 감사드립니다!
그럼 8개 이상 데이터는 지금 당장은 사용이 불가능 한걸로 인지하면 될까요??

**Comment by avamk2** [comment]
네 현재는 그렇습니다.

**Comment by giyoon99** [comment]
넵 감사합니다!
