### ISSUE TITLE
바람길 데이터 생성하려면 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by wavemaker-andropi** [EgisCorp/XDWorld#428]
엔진 버전
: 1.51.3

문의 내용
: 다음 링크를 따라가면 바람길 샘플을 볼 수 있는데, 바람길이 표시되는 지역을 다른 곳으로 바꾸고 싶습니다.
https://sandbox.egiscloud.com/code/main.do?id=effect_wind

![image](https://github.com/user-attachments/assets/4ba3b2d7-5adf-4e91-86a9-bb4258ec347e)

그러려면 어떻게 해야 하나요?

**Comment by YunSumin** [comment]
안녕하세요,

해당 샘플은 기존에 분석된 바람길을 가시화한 것이며,
다른 지역의 바람길을 분석하려면 추가적인 분석 결과 데이터가 필요합니다.

이 샘플은 분석 결과만을 시각화하는 용도로, 표출되는 위치가 고정되는 점 참고 부탁드립니다.

**Comment by avamk2** [comment]
안녕하세요 해당  바람길 분석에 대한 선행시스템은 서버기반 분석시스템을 사용해서 결과를 출력하게 되었습니다.

위에 확인하신 사이트 : https://egiscloud.com/main/main.do

회원가입하시고 메일인증을 받으시면 14일간 체험해보실수 있습니다.

해당기능은 바람길 분석 앱을 통해서 분석해보실수 있으며 분석시 서버기반 분석을 하지만 분석옵션에 따른 처리시간이 어느정도 걸릴수 있습니다. 분석결과는 접속을 끊어도 서버기반 백엔드에서 계속 처리되며 결과는 계정기반 저장됩니다.

이후 결과를 앱에서 확인가능합니다.
