### ISSUE TITLE
일반 사용자 레이어에 특정 영역만 가시화 되도록하는 옵션이 있을까요?

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#429]
엔진 버전
: 2.7.0

문의 내용
:
안녕하세요!

일반 사용자 레이어로 가시화 중인 레이어에 사용자가 입력한 좌표들 기준으로
해당 영역만 표출되도록 가능한 옵션이나 함수가 있을까요??

아래는 예시 이미지 입니다!
![image](https://github.com/user-attachments/assets/040ac41c-58a1-449c-9c84-e96b6106e23c)

![image](https://github.com/user-attachments/assets/b84d9deb-e824-48ca-a783-ac39ef00c027)

**Comment by egiskorea-ryong** [comment]
안녕하세요.  아래 이미지와 같은 기능을 말씀하시는건가요?

![그림1](https://github.com/user-attachments/assets/c4e1b087-db55-4b02-ba20-48882c5804f1)
![그림2](https://github.com/user-attachments/assets/01fda924-7350-4839-9432-8cd6e8146058)

**Comment by giyoon99** [comment]
넵 맞습니다!

사용자 입력 영역에 오브젝트가 걸쳐지는 부분은 오브젝트가 통으로 사라지는 것이 아닌 잘리도록 표현도 가능할까요??

**Comment by egiskorea-ryong** [comment]
객체와 영역이 겹치는 부분을 잘린것처럼 표현하는것은 겹치는 부분의 vertex를 계산하고 이를 바탕으로 새로운 face를 생성해야하는 과정이 필요합니다. 해당 기능은 연산과정이 많이 들어가 원하시는 속도를 얻을 수 없을것입니다 이로인해 아직 검토하고 있지 않는 기능입니다.

문의 주셨던 영역에 걸치는 객체만 렌더링하는 기능은 아래 샘플을 조합하여 구현 가능합니다.
[영역내객체검사](https://sandbox.egiscloud.com/code/main.do?id=analysis_object_inside_area)
[객체콜백](https://sandbox.egiscloud.com/code/main.do?id=layer_tileloaded_callback)

객체 렌더링시 콜백된 정보를 바탕으로 영역내 객체 포함 여부를 체크 후 객체의 object.setVisible(false); 를 통해 영역을 벗어난 객체는 랜더링하지 않도록 할 수 있습니다.

감사합니다.

**Comment by giyoon99** [comment]
넵 답변 감사드립니다!
