### ISSUE TITLE
CreateShadowOutLine 함수 문의

### ISSUE THREAD

**Issue by HyeonbinLee** [EgisCorp/XDWorld#430]
엔진 버전
: 2.7.1 

문의 내용
:

안녕하세요!
그림자 분석 모듈에서
```js
Module.getAnalysis().CreateShadowOutLine(new Module.JSDateTime(year, month, day, hour, minute, 0), new Module.JSColor(0, 0, 0));
```
위와 같은 소스를 사용하는데
혹시 CreateShadowOutLine 이 함수의 다른 설정 값은 뭐가 있을까요?
더 이상 쓰지 않는 함수일까요?

**Comment by avamk2** [comment]
안녕하세요 

다른 설정 값이라는 것은 추가적인 파라메터를 이야기 하는 것인가요?
아니면 같은 기능에 다른 확장 함수들을 이야기 하시는 건가요?
