### ISSUE TITLE
가시권분석(3D) 기능 관련 문의드립니다.

### ISSUE THREAD

**Issue by smpk32** [EgisCorp/XDWorld#431]
엔진 버전
: 2.6.2

문의 내용
:  안녕하세요.

엔진버전을 2.1.0에서 2.6.2로 변경 후 가시권 분석 후에 아래의 이미지와 같이 반투명 영역이 투명하게 보여지는데 
해당 영역이 반투명하게 보여지는 옵션이나 함수가 있는지 문의드립니다!

**2.1.0 버전**
![image](https://github.com/user-attachments/assets/144aa644-7fce-427e-ac96-1ac6820b1b8b)

**2.6.2버전**
![image](https://github.com/user-attachments/assets/11db4cc8-f56c-49a9-9cff-dfdac25904b4)

**Comment by hjaejae** [comment]
오류 확인하였습니다.
다음 업데이트 시에 반영되도록 하겠습니다.
업데이트 되면 알려드리겠습니다.

**Comment by smpk32** [comment]
넵 감사합니다.

**Comment by HeoTaeYang** [comment]
안녕하세요. 해당 문제가 수정되었습니다.
엔진을 2.7.2 버전으로 업데이트 해주시기 바랍니다.

**Comment by smpk32** [comment]
업데이트 후 해결됐습니다. 
감사합니다.
