### ISSUE TITLE
sandbox에 Check object inside area 기능 문의 사항이 있습니다.

### ISSUE THREAD

**Issue by chys-egis** [EgisCorp/XDWorld#432]
문의 내용
: 안녕하세요.

sandbox에 Check object inside area 기능 문의 사항이 있습니다.
떨어져 있는 영역이 1개 이상 일때 내부적으로 영역이 생각과 다르게 잡혀져서 이걸 해결 방법이 궁금합니다.

아래 이미지처럼 좌표값만 가지고는 1개 영역이상을 잡을수 없습니다.
![image](https://github.com/user-attachments/assets/4a174b1f-0e82-45b4-bdea-143723b976ab)
(object가 영역내 있음을 체크는 영역 위 사진과 같이 동작합니다.)
![image](https://github.com/user-attachments/assets/fd843967-f670-4e8c-a5d0-876400c2bd8f)
(object가 위 이미저럼 2개영역을 개별로 인식을 하는 방법이 궁금합니다.)

그리고 좌표값대신 geoserver에서 불러온 레이어가지고도 가능한지 궁금합니다.

---- 위 이미지에 좌표값 공유드립니다.  ----------------
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.128940, 35.170739, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.128960, 35.170838, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.130198, 35.171511, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.130305, 35.171499, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.130885, 35.170779, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.130861, 35.170700, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.129611, 35.170018, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.129517, 35.170033, altitude));

GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.132416, 35.169008, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.133416, 35.167738, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.132508, 35.167327, altitude));
GLOBAL.POINT_LIST.push(new Module.JSVector3D(129.131587, 35.168497, altitude));

**Comment by HeoTaeYang** [comment]
안녕하세요.
영역이 여러 개인 경우, 어떤 영역에 포함되는지 확인할 수 있도록 해당 기능을 수정하겠습니다.

차후 기능이 업데이트되면 다시 안내드리겠습니다.

**Comment by HeoTaeYang** [comment]
안녕하세요. 요청하신 대로, 여러 영역의 경우에도 확인할 수 있도록 기존 API를 수정하였습니다.
자세한 사용법은 [2.7.2 업데이트 항목](https://github.com/EgisCorp/XDWorld?tab=readme-ov-file#2-jsanalysischeckinsidearea-%EA%B8%B0%EB%8A%A5-%ED%99%95%EC%9E%A5)을 확인해주시기 바랍니다.
