### ISSUE TITLE
b3dm, pnts 파일 표출안됨.

### ISSUE THREAD

**Issue by kroonstazy** [EgisCorp/XDWorld#434]
엔진 버전
: 2.7.0

문의 내용
: [샌드박스 예제](https://sandbox.egiscloud.com/code/main.do?id=object_3dtiles)를 참고하여, 보유하고 있는 b3dm 타일셋을 화면에 표출하려고 했으나 표출 되지 않음.

1. 카메라는 모델의 좌표로 이동되는것을 확인
2. 브라우저에서 b3dm 파일은 성공적으로 불러 옴.

b3dm, obj, 등 3D 객체를 불러오는 문서가 더 자세하게 있으면 좋겠습니다.
JS

`Module.XDEMapCreateLayer("tile_pcl_19_yeouido", "3dmap.egiscloud.com", 8080, false, true, false, 19, 0, 19);`

를 사용해서, 다른 타일도 불러올 수 있는지 또한 궁금합니다.

**Comment by hjaejae** [comment]
현재 3DTiles에 관해서는 Beta 버전으로 진행되고 있습니다.
이유는 B3DM에는 여러 공식 및 비공식으로 여러가지 옵션이 있는데 이를 아직 전부 수용하지 않아서 입니다.

데이터가 공유 가능한 데이터이면 hjaejae@egiskorea.com 으로 보내주시면 검토해보겠습니다.

Module.XDEMapCreateLayer API를 사용하여 불러 올 수 있는 데이터 타입은 저희 빌더에서 제작한 데이터들입니다.

https://egiscorp.gitbook.io/xdworld-webgl-manual/introduce-1/etc/type-list
Tile Layer Type List가 현재 해당 API를 이용하여 불러 올 수 있는 데이터들입니다.

**Comment by kroonstazy** [comment]
해당 메일로 b3dm, pnts 타일셋 공유 드렸습니다.

**Comment by hjaejae** [comment]
메일 확인하였습니다.
전달해주신 파일 확인 후 답변드리겠습니다.

**Comment by kroonstazy** [comment]
안녕하세요, 추가 질문 드리고 싶습니다.

[https://sandbox.egiscloud.com/code/main.do?id=layer_drone_lod](https://sandbox.egiscloud.com/code/main.do?id=layer_drone_lod)

해당 예제에서 사용되는 타일의 스펙이나

**Comment by hjaejae** [comment]
해당되는 빌더는 무료로는 공유되지않고 자회사에서 판매중인 제품입니다.
아래 사이트를 참고해주시기 바랍니다.

https://www.egiskorea.com/product/xd-build.html

**Comment by hjaejae** [comment]
전달해주신 파일을 확인해본 결과 몇몇 적용이 안된 부분이 있어 저희 엔진을 수정하였습니다.

수정한 엔진은 금주 에 업데이트 될 예정입니다.

**Comment by kroonstazy** [comment]
감사합니다!

**Comment by HeoTaeYang** [comment]
안녕하세요. 해당 문제가 수정되었습니다.
엔진을 2.7.2 버전으로 업데이트 해주시기 바랍니다.
