### ISSUE TITLE
JSPipe 간소화표현 관련 기능 문의

### ISSUE THREAD

**Issue by dongeon-newlayer** [EgisCorp/XDWorld#435]
엔진 버전
:2.7.0

문의 내용
:

안녕하세요.
https://sandbox.egiscloud.com/code/main.do?id=object_pipe
기존에 `createPipe` 를 사용해 생성된 `JSPipe` 객체의 색깔을 바꾸려고 합니다.

```js
/**
 * JSPipe의 색상을 노란색으로 변경합니다.
 * @param objectName (String) JSPipe 객체 ID (Default: "PipeObject")
 */
function changeColorToYellow(objectName="PipeObject") {
    const YELLOW = new Module.JSColor(255, 255, 255, 0);
    const pipeObject = GLOBAL.Layer.keyAtObject(objectName);
    pipeObject.setColor(YELLOW , YELLOW);
}
```

그런데, 화면에서 **간소화 표현거리** 보다 먼 거리에서 보고 있는 상태에서 색상을 변경할 경우,
색상이 변경되지 않습니다.

화면을 줌인해서 간소화 표현거리보다 가까워지면 색상이 변경되고,
다시 줌아웃을 하면 변경된 색상이 적용됩니다.

```js
pipeObject.setSimplifyRange(range);
```
위 코드를 통해서 간소화 표현거리 제한을 높여 적용시키려고 하니,
멀리서 보았을 때, Pipe의 굵기가 너무 얇게 나와 보기 어려움이 있습니다.

간소화 표현 상태에서는 거리가 멀어져도 화면상에서 어느정도 굵기를 유지하는데,
일반적인 표현 상태에서는 radius 반경 크기를 유지해서 너무 얇게 나오는 것 같습니다.

이와 관련해서 사용할 수 있는 기능이 있는지 알 수 있을까요?

**Comment by YunSumin** [comment]
안녕하세요,

제공해주신 코드를 통해 말씀해주신 현상을 확인하였습니다.
파이프가 라인으로 변경될 때 색상 값이 정상적으로 반영되지 않는 문제를 발견하였으며
해당 부분은 수정되어 다음 엔진 업데이트에 반영할 예정입니다.

업데이트 완료 후 다시 말씀드리겠습니다.
