### ISSUE TITLE
createShadow API 오류

### ISSUE THREAD

**Issue by M0young** [EgisCorp/XDWorld#436]
엔진 버전
: XDWorld Version : 2.7.1 (Released 2024-10-02)

오류 발생 API
: Module.getAnalysis().createShadow

오류 내용
: 폴리곤 객체를 생성한 후에 그림자 기능을 사용하면 아래 이미지와 같은 현상이 일어나는걸 확인했습니다.

![화면 캡처 2024-10-15 112209](https://github.com/user-attachments/assets/e8e1b01d-7fd4-4e1b-937b-8730ac111e1b)

**Comment by hjaejae** [comment]
해당 문제는 저희가 확인하고 수정하였습니다.
이번에 업데이트되는 버전에서 수정되어집니다.

**Comment by HeoTaeYang** [comment]
안녕하세요. 해당 문제가 수정되었습니다.
엔진을 2.7.2 버전으로 업데이트 해주시기 바랍니다.
