### ISSUE TITLE
Module.getAddObject().Add3DPolyhedron 문의 입니다.

### ISSUE THREAD

**Issue by bellpumpkinn** [EgisCorp/XDWorld#437]
엔진 버전
: XDWorld Version : 2.5.1 (Released 2024-08-09)

문의 내용
:
![3dpolyhedron](https://github.com/user-attachments/assets/74138f6d-bbc7-4428-8a20-63b77c8d9c97)
사진과 같이 헥사곤 모양을 띄우는걸 만들어야 하는데,
해당 js파일에는 'Module.getAddObject().Add3DPolyhedron' 으로 헥사곤폴리곤을 만드는것같아서
제 콘솔에서 코드를 확인해보니 Add3DPolyhedron이 안보입니다.

![image](https://github.com/user-attachments/assets/8fa5129b-b51c-4322-bfa0-7ceee83b02fc)

![image](https://github.com/user-attachments/assets/eeb574ef-1807-41d6-9b75-2c3799cb4c94)

메뉴얼에도 나와있지 않던데 어떻게 쓰는지 알 수 있을까요?

**Comment by avamk2** [comment]
안녕하세요 해당 부분은 현재 배포중인 WebGL 엔진 이전에 기술적용 테스트 베이드인 XDMap에서 만들어진 기능입니다.
때문에 API 체계가 XDMap과 현재 엔진과는 다른 부분이 존재합니다.

우선은 해당 육각형 표현은 전국 육각형형태의 그리드를 엔진에서 만들어주는게 아닌 DB작업을 통해서 모든 육각형 그리드 도형들을 수작업으로 구축되었습니다.

이부분에 대해서는 현재 샌드박스안녕하세요 해당 부분은 현재 배포중인 WebGL 엔진 이전에 기술적용 테스트 베이드인 XDMap에서 만들어진 기능입니다.
때문에 API 체계가 XDMap과 현재 엔진과는 다른 부분이 존재합니다.

우선은 해당 육각형 표현은 육각형형태의 그리드를 엔진에서 만들어주는게 아닌 DB작업을 통해서 모든 육각형 그리드 도형들을 수작업으로 구축되었습니다.

이부분에 대해서는 육각형 입체 모델을 올리는 기능은 샌드박스 참고해 주시면됩니다.
object : polygon height -  https://sandbox.egiscloud.com/code/main.do?id=object_polygon_height

높이 처리에 대한 에니메이션 효과는 만들어진 폴리곤에 타이머를 통한 `polygon.setHeight( [number] );` 의 수치를 증감으로 프레임당 높이변화로 그 효과를 줄수 있습니다.

다만 동시에 많은 객체를 등록하고 표현하는 과정에서 속도 저하가 발생할 수 있기에 필요한 부분만 받아서 처리하는 방식도 응용 가능합니다.

이는 WFS 샘플 - https://sandbox.egiscloud.com/code/main.do?id=layer_wfs 로 구현되어 있습니다. 


적용 과정에서 다른 어려운 점이 있으면 연락주시기 바랍니다.
