### ISSUE TITLE
그림자 형태 지정 오류

### ISSUE THREAD

**Issue by HyeonbinLee** [EgisCorp/XDWorld#439]
엔진 버전
: 2.7.2 (Released 2024-10-17)

오류 발생 API
: setShadowDrawMode

오류 내용
:

안녕하세요 

```js
if(value == "shadow"){    // 그림자
    M_SHADOW.api_analysis.setShadowDrawMode(1);
} else if(value == "line") {    // 선
    M_SHADOW.api_analysis.setShadowDrawMode(3);
} else if(value == "plane") {    // 면
    M_SHADOW.api_analysis.setShadowDrawMode(4);
}
```

그림자 분석 기능에서 그림자 형태를 바꾸기 위해 위 함수를 사용하고 있는데,
현재 선, 면으로 형태가 바뀌지 않는 오류가 발생하고 있습니다.

저희 DTCloud 시스템의 그림자 분석 모듈에서도 그림자 형태가 변경 되지 않는 현상을 확인 후,
1.53.1 (Released 2023-08-04) 버전에서 진행해보니 정상적으로 실행되고 있는 것을 확인하였습니다.

**Comment by egiskorea-ryong** [comment]
안녕하세요.

해당 기능과 DTCloud 시스템 확인 하였습니다.

해당 기능은 현재 정상 동작하는 걸로 확인됩니다.

DTCloud 에서는 (선,면) UI에 대해 처리되어 있지 않아 가시화되지 않는 오류였습니다.

아래는 DTCloud 에서 직접 해당 API를 호출하여 테스트한 화면입니다.

![20241018_101013](https://github.com/user-attachments/assets/dcc142b6-11fa-4de3-8611-6bbe5a9e464c)
![20241018_101025](https://github.com/user-attachments/assets/121716f8-9b26-4619-94de-f670d6355bb7)

**Comment by HyeonbinLee** [comment]
헉 api를 호출해보지 않았네요..! 감사합니다

**Comment by HyeonbinLee** [comment]
api 호출하고 슬라이더바 시간대를 변경해보니 다시 그림자 형태가 되돌아가는데 그 부분도 혹시 UI 문제였을까요?

**Comment by egiskorea-ryong** [comment]
시간대를 돌릴 때 clearShadow() 를 사용하셨다면 

설정했던 값들도 초기화 되기 때문에 다시 그림자를 생성하면 원래 형태로 돌아갑니다.

**Comment by HyeonbinLee** [comment]
말씀 해주셨던 내용처럼 createShadow 후에 setShadowDrawMode 설정을 넣어서도 해봤었지만 되지 않았었고 어떻게 해도 먹지 않아서 이슈 남겼었는데 방금 해결 했습니다..! 감사합니다🥹
