### ISSUE TITLE
ifc 파일 가시화 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#44]
안녕하세요. 바이브컴퍼니입니다.

ifc 파일 가시화 테스트를 해 보려고 합니다.
가시화 방법을 알려 주시면 고맙겠습니다.

그럼,...

**Comment by YangHeeBong** [comment]
저희가 서비스 중인 빌더 클라우드 변환 기능을 통해 엔진에 적용 가능한 포맷으로 변환 하여 
가시화가 가능합니다. 
엔진 자체적으로 가시화는 지원 하고 있지 않습니다

**Comment by HyunSeongKil** [comment]
제가 샘플파일을 가지고 있습니다.
이 파일을 등록해 가시화하고 싶은데, 어떻게 하면 될까요?

그럼,...

**Comment by HyunSeongKil** [comment]
추가로....


![image](https://user-images.githubusercontent.com/38479834/126131271-9a531610-6628-4124-a32c-62ebc944aad3.png)


![image](https://user-images.githubusercontent.com/38479834/126131339-5fb3cc74-4c51-4e1f-a681-336ad3d00625.png)

**Comment by avamk2** [comment]
안녕하세요 연구소에 이현수 부장입니다. ifc 즉 BIM 데이터 취급에 관련해서 문의를 주셨는데요. 이건에 대해서는 저희 회사내에서도 장기적으로 연구하고 있는 분야입니다. 

이게 단순한 모델링 데이터로 생각해서 취급하기 어려운게 ifc는 각각의 건축물에 관련된 요소들이 제작에 따라서 모두 포함되어 있습니다. (예: 창문의 창틀, 샷시 심지어는 볼트까지도) 이때문에 **3D 지도상 사용하기 위해서는 의미있는 데이터의 필터링이나 구조물 및 소품에 대한 필터링** 등의 복잡한 작업이 포함되어 있습니다. 

때문에 ifc 포맷은 이것을 처리하고 모델링 데이터로 추출하기 위한 전문적인 도구가 필요하며 이를 위해서 저희는 **"빌더 클라우드"**라는 원시 데이터 가공 및 3D 지도 퍼블리싱 서비스 제품을 가지고 있습니다. ifc의 데이터 정보들이 매우 방대하고 지도상 가시화 및 데이터 컨트롤 부분까지도 결국에는 핸들링과 데이터 최적화가 필요하기에 이것은 WebGL 엔진영역에서 수행할 정도의 시스템자원으로는 수행하기 매우 어려우며 성능적으로도 만족하기 어렵다는 내부연구개발 통한 결론에 도달하였습니다.

ifc는 단순 모델링이 아닌 건물에 포함된 모든정보를 담고있는 추상적인 데이터 집합이며 이것을 가시화 하기 위해서는 데이터 해석 외에도 데이터 분류, 최적화를 위한 필터링, 가시화를 위한 개념적 해석과 활용기능을 검토해야 가능합니다. 이러한 영역까지 한정된 자원만 사용가능하는 Web환경내에서 런타임으로 구현하기는 매우힘들기에 클라우드 서버를 통한 데이터 처리부분이 반드시 필요한 사항입니다. 

결론적으로 위 Flow에서 저희 자사제품인 "빌더 클라우드"를 도입하면 가능합니다. 엔진의 런타임 기능으로 포함은 반대로 불가능합니다.

**Comment by HyunSeongKil** [comment]
제가 의미전달을 잘 못한 듯 합니다.

저 위에 "엔진 내부적으로 꿍짝꿍짝...."이라 표시한건
엔진이 내부적으로 빌더 클라우드(또는 클라우드상의 어떤 서버)와 통신하여 가시화한다.
html/js는 내부적으로 어떤일이 일어 나는지 알지 못한다....는 것을 표현한 것이 었습니다.


엔진의 런타임이 내부적으로 빌더 클라우드와 통신하여 가시화 하는건 가능한 방법인가요?

**Comment by EgisCorp** [comment]
네 엔진 내부에서 빌더 클라우드 서버를 통해 변환된 데이터 가시화가 가능합니다.

빌더 클라우드 데이터 변환 후 서버정보, 변환정보를 엔진 API를 통해 레이어를 설정 후
카메라 가시화 영역을 기준으로 출력할 Tile Level 확인 -> 서버 요청 을 통해 가시화 하는 방법을 사용 중입니다.

간단한 예로 WMS 방식과 유사하게 제공 하고 있습니다.

**Comment by HyunSeongKil** [comment]
그럼 제가 테스트 할 방법이 있나요?

**Comment by YangHeeBong** [comment]
빌더 클라우드 제품을 사용하지 않고 테스트할 방법은 파일 변환 및 정점으로 직접 컨트롤 방법이 있는데 대용량 ifc를 조작 하시는 건 쉽지 않습니다. ifc 변환이 필요하시다면 빌더 클라우드 제품을 고민 해보시거나 다음 주 회의 때 내용 정리를 요청 드립니다.

**Comment by HyunSeongKil** [comment]
제가 알기로는....
저희에게 이지스의 제품 사용 권한이 있는 것으로 알고 있습니다.
자세한건 다시 확인해 보겠습니다.

**Comment by YangHeeBong** [comment]
사용 권한에 대한 지시 사항은 없었습니다.
이 부분에 대해서 정확한 내용이 필요할 것 같습니다.

**Comment by HyunSeongKil** [comment]
이거 얘기하시는건가요?

초반에 받은 계정이 있기는 한데...

![image](https://user-images.githubusercontent.com/38479834/126593604-63127920-eb91-4bc9-a220-bae4001aeb09.png)

**Comment by EgisCorp** [comment]
** 해당 이슈는 기술 지원 사항에서 사업 협의 사항으로 변경하여 금주 월요일 업체 간 회의를 통해 협의 진행하였습니다.
