### ISSUE TITLE
ERR_EMPTY_RESPONSE 5XX

### ISSUE THREAD

**Issue by shafqatjamil** [EgisCorp/XDWorld#440]
엔진 버전
: https://sandbox.egiscloud.com/code/main.do?id=camera_view_mode
WebXR emulator extension overrides native WebXR API with polyfill.
XDWorld Version : 2.8.0 (Released 2024-10-25)
WebXR emulator extension overrides native WebXR API with polyfill.
XDWorld Version : 2.8.0 (Released 2024-10-25)

오류 발생 API
: https://xdworld.vworld.kr/XDServer3d/requestLayerNode?Layer=tile&Level=1&IDX=16&IDY=6&APIKey=1F8C86CC-6DBB-34BA-A92E-571F5D84BB99

오류 내용
: 
(failed)net::ERR_EMPTY_RESPONSE
--

**Comment by avamk2** [comment]
안녕하세요 

해당부분은 http 네트워크에서 데이터 요청에서 서비스 장애 또는 네트워크 장애로 발생하는 문제로 보입니다.

계속되는 데이터 접속이 안된다면

대한민국 밖에서 접속시 VWorld 데이터제공이 안됩니다.
VPN으로 대한민국 밖 라우팅시에도 마찬가지도 안됩니다.

이는 XDWorld 문제가 아닌 위성영상 및 DEM과 3D 건물에 대한 VWorld 접속이 차단되어서 안되는 문제일 것입니다.

**Comment by shafqatjamil** [comment]
Thanks, That make sense.
