### ISSUE TITLE
Module.getOption().object_ahead 레이어별 설정 가능 여부

### ISSUE THREAD

**Issue by Ejeongs2** [EgisCorp/XDWorld#442]
엔진 버전
: XDWorld Version : 2.7.2 (Released 2024-10-17)

문의 내용
: 
let layerList = new Module.JSLayerList(true);
let saleslayer 	= layerList .createLayer("SALES_POI", Module.ELT_3DPOINT); 방식으로 불러오는 layer와

Module.XDEMapCreateLayer("poi_3d", "http://", 0, true, true, false,5, 0, 18) 해당방식으로 불러오는 layer를 사용중에 있습니다.

두개의 레이어를 동시에 사용하면서 특정 레이어만 건물에 가려지는 옵션을 적용하고 싶은데,

샌드박스  Module.getOption().object_ahead = 1;  해당 옵션을 설정할시 모든 layer가 해당 옵션이 적용되는걸로 확인됩니다.
layer별 적용이 가능한지 문의드립니다.

**Comment by HeoTaeYang** [comment]
안녕하세요.
말씀하신 object_ahead 프로퍼티는 JSOption에서 일괄적으로 관리하기 때문에, 현재로써는 layer별로 적용할 수 없는 상태입니다.
기능 변경이 가능한지 검토 후 다시 안내드리겠습니다.

**Comment by Ejeongs2** [comment]
안녕하세요!

layer별 적용이 어렵다면, 혹시 속성별, object 종류등 일부분만 원하는 적용이 가능한지에 대해서 가능성 여부를 알고 싶습니다. 감사합니다.

**Comment by HeoTaeYang** [comment]
안녕하세요.

확인해 본 결과 layer와 속성, object 종류일 경우 모두 기능 수정이 필요합니다.
layer별로 object_ahead 속성을 사용할 수 있도록, JSLayer의 기능을 변경하겠습니다.

기능이 업데이트되는 대로 안내드리겠습니다!

**Comment by HeoTaeYang** [comment]
안녕하세요.
2.8.2 버전 엔진에, JSLayer 별로 해당 기능을 적용할 수 있도록 기능을 수정하였습니다.
아래는 해당 옵션을 사용하는 방법입니다.
```javascript
let layerList = new Module.JSLayerList(true);
let layer = layerList.createLayer("POI_TEST", Module.ELT_3DPOINT);
layer.object_ahead = true;
```
이제 `JSOption.object_layer` 옵션을 별도로 설정하지 않아도 동작합니다.

2.8.2 버전 엔진 파일은 배포 깃의 2.8.2_hotfix 폴더를 확인해주시기 바랍니다.
샌드박스 샘플은 해당 기능이 없는 엔진을 사용하고 있으니, 이점 유의해주세요.
