### ISSUE TITLE
polygon.createTMCoordPlane 속도 개선 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#443]
엔진 버전
:  2.7.3

문의 내용
:
안녕하세요.

침수 시뮬레이션 기능에서 polygon.createTMCoordPlane을 사용하여 폴리곤을 생성합니다.

하나를 생성할 때는 크게 문제가 되지 않는데 이번에 최대 12개를 한 번에 생성하여 10분마다 갱신해야 합니다.

그러다 보니 생성 속도가 너무 느린데 개선할 수 있는 방법이 있을까요?

사용 중인 데이터 예시 입니다. 

```
polygon.createTMCoordPlane({
    llcorner : {
        coordCode : 20,  // 좌표계 5186
        x : 347328.96875,
        y : 288846.75
    },
    grid : {
        col : 1428,
        row : 788,
        cellSize : 5
    },
    gab : 21 // 격자 오차 개선
})
```

**Comment by YunSumin** [comment]
안녕하세요,

오브젝트의 갱신 정보에 대해 추가 정보 부탁드립니다.

만약 오브젝트의 버텍스 구성 변경 없이 위치만 변경되는 경우
(ex : grid col, row, cellSize는 그대로인 상태에서 높이 값만 변경되는 경우)
오브젝트의 갱신 속도를 개선할 여지가 있으나,

오브젝트의 형상이 바뀌는 경우(grid col, row, cell size 등 형태가 변경되는 경우)는
버텍스 정보를 완전히 새로 만들어야하므로 속도 개선이 어렵습니다.

안내드린 경우 중 어느 경우에 해당하시는지 추가 정보 부탁드립니다.

**Comment by suhwna** [comment]
감사합니다 해결했습니다.
