### ISSUE TITLE
Dem 가시화 오류

### ISSUE THREAD

**Issue by ParkJunEgisKOREA** [EgisCorp/XDWorld#444]
엔진 버전
:2.8.0

![image](https://github.com/user-attachments/assets/f51fe90e-f0df-46fa-ac1a-97461827aad8)

오류 내용
: DT에서 Dem 가공 이후 setDemBox를 통해서 가공 레벨과 동일하게 min max Level 지정하여 가시화하였을 때 지형이 깨져서 나옵니다.

**Comment by avamk2** [comment]
안녕하세요 DT에서 샌드박스의 코드를 가져와서 앱코딩으로 사용하는 것이라면

```	terrain : {
				dem : {
					url : "https://xdworld.vworld.kr",
					name : "dem",
					servername : "XDServer3d",
					encoding : false
				},
```

encoding : true로 된 속성을 false 또는 삭제해 주시기 바랍니다.
