### ISSUE TITLE
dem없는 위치에서의 Module.getTerrain().getServerAltitude() 함수 문의

### ISSUE THREAD

**Issue by Kor-eunae** [EgisCorp/XDWorld#445]
엔진 버전
: 2.8.0

오류 발생 API
: Module.getTerrain().getServerAltitude() 

오류 내용
: 
해당 함수를 사용하면
lon, lat 값으로 엔진에서 로딩한 dem에 맞춰 고도값까지 포함된 좌표값을 리턴해주는 것으로 알고 있습니다.

아래의 소스로 좌표 값을 리턴 받도록 구현하여 테스트한 결과,
dem이 있는 위치의 lon, lat 값으로는 좌표값이 잘 리턴이 되지만
dem이 없는 위치의 lon, lat 값으로는 result절을 타지도 않습니다.
dem이 없는 위치라면 result가 null로 리턴이 되어 else 구문의 로직을 실행했으면 하는데 그렇게는 안되나요?

````
getDemLocation(_lon, _lat) {
   return new Promise((resolve, reject) => {
       // 지형 DEM에서 lon, lat 으로 해당 위치의 좌표 조회
       Module.getTerrain().getServerAltitude({
           level: 15,
           positions: [new Module.JSVector2D(_lon, _lat)],
       }, (result) => {
           if (result && result.length > 0) {
               console.log("dem");
               resolve(new Module.JSVector3D(result[0].longitude, result[0].latitude, result[0].altitude));
           } else {
               console.log("no dem");
               const alt = Module.getMap().getTerrHeightFast(_lon, _lat);
               const location = new Module.JSVector3D(_lon, _lat, alt);
               resolve(location); // 에러가 발생하면 원래 방식대로 구한 position 반환
           }
       });
   });
}
````

답변 주시면 감사하겠습니다!

**Comment by YunSumin** [comment]
안녕하세요,

해당 API는 설계된 의도대로 동작한다면 DEM 유무에 상관없이 result가 반환되는 것이 정상입니다.

API가 비정상적으로 종료되었거나 문제가 발생한 것 같습니다.
API 실행 중 result 함수가 실행되지 않을 때 콘솔 창에 메시지가 뜬다면
메시지 내용도 함께 첨부 부탁드립니다.

또한 좌표리스트 및 URL을 별도로 첨부해주시면 자체 테스트도 함께 진행하겠습니다.
