### ISSUE TITLE
worker 사용 문의

### ISSUE THREAD

**Issue by suhwna** [EgisCorp/XDWorld#446]
엔진 버전
: 2.7.2

문의 내용
:

안녕하세요.

모듈 기능에 worker 사용 유무가 있던데 worker를 사용하여 여러 개의 폴리곤을 백그라운드에서 생성되게 할 수 있나요?

가능하다면 worker를 어떻게 사용하나요?

**Comment by hjaejae** [comment]
현재 WebWorker의 기능은 이미지 변환 할 때만 지원합니다.
이미지 변환만 지원하는 이유는  3차원 렌더링시에 이미지 변환이 가장 시간이 많이 걸려서 입니다.
얼마나 많은 데이터를 변환하는지는 모르겠으나 일반적인 폴리곤 생성의 경우 WebWoker로 데이터 전송 후 다시 엔진에서 다운 받는 과정이 더 시간이 많이 소요 될 것으로 판단되어 폴리곤 생성은 현재 WebWorker를 지원 하지 않습니다.

**Comment by suhwna** [comment]
네 감사합니다.
