### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by JustinKim4008** [EgisCorp/XDWorld#448]
API Key 발급은 어떻게 진행되는지 알고 싶습니다.
감사합니다.

**Comment by avamk2** [comment]
안녕하세요 

XDWorld엔진에서 자체적으로 요구하는 API Key는 없습니다.

샌드박스 예제에서 사용되는 defaultKey는 VWorld 3D Data API (영상, DEM, 3D건물) 사용을 위해서 발급 받은 것으로 해당 용도에서 사용을 신청 승인 받아 사용합니다. 해당사용 신청은 공간산업진흥원에 문의해서 사용가능합니다. 다만 24년 현재는 신규 신청으로는 정부기관, 지자체, 공사에서만 발급되는 걸로 알고 있습니다. 그리고 해당 키는 XDWorld 엔진에서 쓰기 위해서 코드레벨에 유출을 방지하고자 암호화를 거칩니다.  25년에는 민간용 공개 논의가 있습니다.

WMTS 같은 경우 API 키는 
https://sandbox.egiscloud.com/code/main.do?id=layer_wmts
https://sandbox.egiscloud.com/code/main.do?id=layer_wmts_hybrid

국토정보 플랫폼에서 API 키 신청을 하여 해당키를 소스코드에 넣어주시면 됩니다. https://map.ngii.go.kr/mi/openKey/openKeyRegist.do
