### ISSUE TITLE
setTwoSlideScreenLayerList 문의 입니다.

### ISSUE THREAD

**Issue by bellpumpkinn** [EgisCorp/XDWorld#449]
엔진 버전
 :XDWorld Version : 2.8.1 (Released 2024-11-01)

문의 내용
:
![image](https://github.com/user-attachments/assets/0a6747a8-4c84-4641-9f99-ebbe81784f2c)
![image](https://github.com/user-attachments/assets/7febd3c8-bd85-4940-89d4-79bc44861889)

안녕하세요.

 GLOBAL.option.setTwoSlideScreenLayerList("facility_build,IC_BIZ_LAYER1","facility_build,IC_BIZ_LAYER2");
에서  IC_BIZ_LAYER1은 빨간색으로 설정을 해뒀고, IC_BIZ_LAYER2는 노란색으로 설정을 해뒀습니다.

둘다 facility_build(건물)들은 다 잘 뜨는데, IC_BIZ_LAYER1 과 IC_BIZ_LAYER2가 합쳐져서 왼쪽에만 노란색으로 구역이 뜹니다.
원래는 왼쪽은 빨간색으로 구역이 뜨고, 오른쪽에는 노란색으로 구역이 떠야하는데,
합쳐져서 왼쪽에만 노란색으로 구역이 뜹니다.
왜 이런지 알수있을까요?
오른쪽 레이어에도 떠서 비교할수있게 확인부탁드립니다.

**Comment by egiskorea-ryong** [comment]
안녕하세요.

샌드박스에서 테스트 결과 정상적으로 동작하는것을 확인했습니다.

[주요 테스트 코드]
```javascript
var layerList = new Module.JSLayerList(true);
var layer = layerList.createLayer("POLYGON_LAYER", Module.ELT_POLYHEDRON);
layer.addObject(polygon, 0);
        
var layer2 = layerList.createLayer("POLYGON_LAYER2", Module.ELT_POLYHEDRON);
layer2.addObject(polygon2, 0);

Module.getOption().setSlideScreenCount(2);
Module.getOption().setTwoSlideScreenDivideRate(0.5);
Module.getOption().setTwoSlideScreenLayerList(
    "facility_build,POLYGON_LAYER2",
    "facility_build,POLYGON_LAYER"
);
```

[테스트 결과 화면]
![20241106_121601](https://github.com/user-attachments/assets/504016f2-ac1b-46c9-9ed3-33f1aa57477a)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

말씀하신 API에 대해 테스트 진행 결과 정상적으로 동작하는것을 확인했습니다.

[주요 샘플 소스]
```javascript
var layerList = new Module.JSLayerList(true);
var layer = layerList.createLayer("POLYGON_LAYER", Module.ELT_POLYHEDRON);
layer.addObject(polygon, 0);        

var layer2 = layerList.createLayer("POLYGON_LAYER2", Module.ELT_POLYHEDRON);
layer2.addObject(polygon2, 0);

Module.getOption().setSlideScreenCount(2);
Module.getOption().setStereoView(true);
Module.getOption().setTwoSlideScreenLayerList(
    "facility_build,POLYGON_LAYER",
    "facility_build,POLYGON_LAYER2",
);
```

[테스트 결과 화면]
![20241107_085447](https://github.com/user-attachments/assets/76175b13-28bc-480b-a5d1-742e058e7a8c)

계속 오류가 발생하신다면 사용하신 소스를 첨부해주시면 검토해보겠습니다.

감사합니다.
