### ISSUE TITLE
네이버 or 카카오 지적 편집도 및 기본 지도이용

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#45]
안녕하세요 서비스에 기본적으로 보여주는 자료 가시화 한계로 인하여 기본 지도로 네이버 카카오 지적 편지도 or 기본 지도가 필요할 것으로 보이는데 해당 기능과 연계 가능한 API가 있을까요?
![image](https://user-images.githubusercontent.com/3315478/126113260-b3e909c7-5365-4258-8839-4a92615a9aaa.png)
![image](https://user-images.githubusercontent.com/3315478/126113285-8aca1aa8-2341-462e-88a2-6ef1532d0d03.png)
감사합니다

**Comment by SeongRyong-Choi** [comment]
현재 OSM, BingMaps, Google, ArcMaps, Naver, MapBox를 지원하고 있습니다.

Naver 베이스맵을 사용하는 방법은 다음과 같습니다.

Module.SetPlanetImageryType(40); // 위성지도
Module.SetPlanetImageryType(41); // 벡터지도
Module.SetPlanetImageryType(42); // 위성지도 + 부가정보(지하철, 지역경계, 도로 등)

**Comment by loeaf** [comment]
![image](https://user-images.githubusercontent.com/3315478/126125700-dfdf3475-6188-4d84-a9d6-3c9d616f7370.png)
지적편집도라고 각 토지에 대한 용도를 볼 수 있는 아주 중요한 맵입니다... 해당 맵에 대해서 지원할 수는 없을까요?

**Comment by SeongRyong-Choi** [comment]
지적편집도는 현재 네이버 서비스 구조를 검토중입니다.

**Comment by SeongRyong-Choi** [comment]
네이버 측에 문의 후 받은 답변입니다.

1. 공개된 URL이 없으며 사용자가 URL로 임의로 사용하시는 것은 금지하고 있습니다.
2. 현재 지적편집도는 API로 제공하고 있지 않습니다.
3. 자바스크립트에서 Naver Maps 라이브러리를 활용하여 사용 가능합니다.

**Comment by avamk2** [comment]
안녕하세요 해당부분에 대한 검토를 하였으며 네이버에 문의를 해보았습니다. 이에 대한답변으로

지적편집도에 대한 문의사항에 대한 답변으로

1. 공개된 URL이 없으며 사용자가 URL로 임의로 사용하시는 것은 금지하고 있습니다.
2. 현재 지적편집도는 API로 제공하고 있지 않습니다.
3. 자바스크립트에서 Naver Maps 라이브러리를 활용하여 사용 가능합니다.

이 사항에서 한가지 명칭을 "지적도"가 아닌 "지적편집도"라고 하는 부분에서 해당 데이터가 민감데이터라서 그렇습니다. 지도사용자가 지적도에 의한 부동산에 관련된 민원이 엄청나게 많기 때문에 토지를 소유한 소유자간 분쟁 근거를 위해서 지도수정요청아나 직간접소송에 영향을 받기에 이부분에 서비스는 지도서비스 업체입장에서 굉장히 민감한 정보로 취급합니다.

그래서 카카오맵이나 네이버맵 모두 지적관련 서비스를 자사 맵내에서만 하게 허용하는 것으로 외부서비스에 의한 책임 부인을 하는 장치로 API로 열어주지 않는것으로 판단됩니다. 지적도 서비스를 위해서는 지리원에 지적도 데이터를 받아서 자체 서비스하는 방법으로 진행해야될 것으로 확인됩니다.
