### ISSUE TITLE
polygon.setWaterEffect 사용 문의

### ISSUE THREAD

**Issue by egiskorea01** [EgisCorp/XDWorld#450]
엔진 버전
: 2.8.1

문의 내용
:
water effect 사용 시 검은 배경이 나타나는 현상이 발생하여 문의드립니다. 이전에는 해당 문제가 없었던 것으로 기억하는데, 원인이 무엇인지 궁금합니다.

아래에 사용한 코드를 첨부드립니다. 

![image](https://github.com/user-attachments/assets/578d678e-c8ab-4c5a-bca7-32ab7bc278e7)

flowEffect();
function flowEffect() {
    var _x = 127.41617675118468;
    var _y = 36.73820743203956;
    var _r = 250;

    var trueLayerList = new Module.JSLayerList(true);
    if (trueLayerList.nameAtLayer("POLYGON_FLOW_EFFECT_LAYER") != null) {
        trueLayerList.delLayerAtName("POLYGON_FLOW_EFFECT_LAYER");
    }

    // 폴리곤 객체 생성
    var polygon = Module.createPolygon("POLYGON_FLOW_EFFECT");

    // 버텍스 반환
    var vertices = getCircleVertices(_x, _y, 10000, _r * 0.7);

    // uv 좌표 계산
    var polygonRect = getPolygonRect(vertices);
    var width = Math.abs(polygonRect.max.lon - polygonRect.min.lon);
    var height = Math.abs(polygonRect.max.lat - polygonRect.min.lat);

    // 폴리곤 최대, 최소 경위도 좌표를 기반으로 uv 텍스쳐 좌표를 0.0~20.0 범위 값으로 정규화
    var uv = new Module.JSVec2Array();
    for (var i = 0; i < vertices.count(); i++) {
        uv.push(new Module.JSVector2D(
            Math.abs(polygonRect.min.lon - vertices.get(i).Longitude) / width,
            Math.abs(polygonRect.max.lat - vertices.get(i).Latitude) / height
        ));
    }

    // part 설정
    var part = new Module.Collection();
    part.add(vertices.count());

    // vertices, part, uv로 폴리곤 생성
    polygon.setPartCoordinatesUV(vertices, part, uv, true);

    // 물 효과 설정
    polygon.setWaterEffect(true, {
        flow_map_url: "https://egiscloud.com/assets/img/dt/waterflow_grid_blur_gradation.png",
        flow_map_width: 512,
        flow_map_height: 512
    });

    // 외곽 라인 숨김
    var polygonStyle = new Module.JSPolygonStyle();
    polygonStyle.setOutLine(false);
    polygonStyle.setOutLineColor(new Module.JSColor(255, 255, 255, 0));
    polygon.setStyle(polygonStyle);

    // 폴리곤을 추가할 레이어 생성
    var layerList = new Module.JSLayerList(true);
    var layer = layerList.createLayer("POLYGON_FLOW_EFFECT_LAYER", Module.ELT_POLYHEDRON);
    layer.setSelectable(false);
    layer.setMaxDistance(10000000.0);

    // 레이어에 객체 추가
    layer.addObject(polygon, 0);
    Module.getMap().clearInputPoint();
}

function getCircleVertices(_centerLon, _centerLat, _centerAlt, _r) {
    // 원 버텍스 입력 후 반환
    var map = Module.getMap();
    map.setCircleInputPoint(new Module.JSVector2D(_centerLon, _centerLat), _r * 500, 20);

    var circleVertices = map.getInputPoints();

    // 고도 적용
    var resultVertices = new Module.JSVec3Array();
    for (var i = 0; i < circleVertices.count(); i++) {
        resultVertices.push(new Module.JSVector3D(circleVertices.get(i).Longitude, circleVertices.get(i).Latitude, _centerAlt));
    }

    return resultVertices;
}

function getPolygonRect(_positions) {
    var min = {
        lon: _positions.get(0).Longitude,
        lat: _positions.get(0).Latitude
    };

    var max = {
        lon: _positions.get(0).Longitude,
        lat: _positions.get(0).Latitude
    };

    for (var i = 1; i < _positions.count(); i++) {
        if (_positions.get(i).Longitude < min.lon) {
            min.lon = _positions.get(i).Longitude;
        } else if (_positions.get(i).Longitude > max.lon) {
            max.lon = _positions.get(i).Longitude;
        }

        if (_positions.get(i).Latitude < min.lat) {
            min.lat = _positions.get(i).Latitude;
        } else if (_positions.get(i).Latitude > max.lat) {
            max.lat = _positions.get(i).Latitude;
        }
    }

    return {
        min: min,
        max: max
    };
}

**Comment by avamk2** [comment]
안녕하세요 

이전 엔진업데이트에서 투명 처리에 대한 업데이트 부분이 있었는데 해당부분과 사용하신 기능간에 처리문제로 보입니다.
내부적으로 문제 확인중에 있으며 수정처리후 업데이트 예정입니다. 

처리되면 이야기드리겠습니다.

**Comment by hjaejae** [comment]
해당 기능은 이미지의 색상 R(Rec), G(green)을 이용해 물의 방향을 정하고 표현하는 기능입니다.
그리고 애니메이션을 만들기 위해서 주위의 픽셀 색상을 참조합니다.

사용하신 이미지는 Blur처리가 되어있어서 R,G값이 흰색이나 투명 값이 주위에 있다 보니 방향성이 없어지고 그래서 검은색으로 표현되는 것 같습니다. 

예전에 사용하신 이미지가 해당 이미지가 한번 맞는지 살펴보시고
표현하고자 하는 곳에는 blur처리가 안된 명확한 RGB값이 있는 이미지가 필요해 보입니다.

**Comment by hjaejae** [comment]
오류가 수정되어 금주에 업데이트 됩니다.

**Comment by HeoTaeYang** [comment]
안녕하세요.
해당 오류가 수정된 버전 배포하여 안내말씀 드립니다.
2.8.3_hotfix 엔진을 사용해주시기 바랍니다.
