### ISSUE TITLE
저지대 분석, 경사도 분석 동시 실행

### ISSUE THREAD

**Issue by HyeonbinLee** [EgisCorp/XDWorld#451]
엔진 버전
: XDWorld Version : 2.7.3 (Released 2024-10-18) 

문의 내용
:
안녕하세요.

저지대 분석의 화살표 유형과 경사도 분석을
```js
Module.getSlope().clearAnalysisData();
```
위 함수로 기존 분석 데이터를 지우고 새로 그리다보니 아래 영상처럼

경사도 분석 후 저지대 화살표 분석을 진행하면 경사도 분석이 사라지고
저지대 화살표 분석 후 경사도 분석을 진행하면 저지대의 화살표만 사라집니다.

https://github.com/user-attachments/assets/79398d9c-5dfd-49ff-9d5a-44ba835fd5cd

사라지지 않고 유지를 할 수 있도록
각각 제어를 할 수 있는 방법이 있을까요?

**Comment by hjaejae** [comment]
clearAnalysisData API는 모든 분석을 삭제하는 API 입니다.

```javascript
Module.getSlope().clearSlope("objectKey");
```
위 API를 활용하여 제어해보시기 바랍니다.

**Comment by HyeonbinLee** [comment]
감사합니다!!!!!!!
