### ISSUE TITLE
건물 오브젝트 고화질 텍스처 랜더링(LOD4) 관련 이슈

### ISSUE THREAD

**Issue by gudfo36** [EgisCorp/XDWorld#453]
엔진 버전
: XDWorld Version : 2.8.0 (Released 2024-10-25)

오류 발생 API
:

오류 내용
:안녕하세요 문의사항은 아래와 같습니다.
3차원 건물 모델링 고화질 텍스처(LOD4)가 카메라가 멀리있는 오브젝트는 잘 불러오는데 가까운 모델의 오브젝트는 텍스처 갱신이 늦거나 잘 안되는 문제가 있습니다.
엔진 함수에서 추가 해야되는 부분이 있는지 아니면 엔진 수정이 필요한 부분인지 알려주시면 감사하겠습니다.

![스크린샷 2024-11-12 161557](https://github.com/user-attachments/assets/ba5aada7-670f-4bc7-a7a5-5fc5f7aea677)

![KakaoTalk_20241112_151719647](https://github.com/user-attachments/assets/86f0d89b-1e90-4ab3-824e-9f1d35a065de)

**Comment by hjaejae** [comment]
지금 현재 객체의 텍스쳐 선명도에 대해서 화면의 중심을 기준으로 레벨이 정해집니다.
스크린샷을 보면 화면 중심에 텍스쳐가 선명하고 중심에서 멀어질수록 텍스쳐의 레벨이 떨어집니다.
현재 이 부분에 대해서는 계속 최적화 중이며 오늘 다시 한번 업데이트 할 예정입니다.

오늘 오후에 릴리즈 될 버전으로도 한번 테스트 해주시기 바랍니다.
