### ISSUE TITLE
다각형을 서로 다른 축을 중심으로 회전시킬 수 있나요?

### ISSUE THREAD

**Issue by shafqatjamil** [EgisCorp/XDWorld#455]
엔진 버전
:2.8.4

문의 내용
:다각형을 서로 다른 축을 중심으로 회전시킬 수 있나요?
`function TraceTarget(target) {

    var layerList = new Module.JSLayerList(true);
    var layer = layerList.createLayer("glTF_Test", Module.ELT_POLYHEDRON);
    var polygon = Module.createGLTF("GLTF_Object");
    polygon.loadFile({
        url: GLOBAL.model_url,
        type: "glb",
        position: target,
        rotate: 180,
        rebuild: true,
        callback: function (e) {
            // polygon.setAnimationByID(0);
            // polygon.setScale(new Module.JSSize3D(1.0, 1.0, 1.0));
            GLOBAL.TRACE_TARGET = Module.createTraceTarget(polygon.getId());
            GLOBAL.TRACE_TARGET.set({
                object: polygon,
                tilt: 160.0,
                direction: 0.0,
                distance: 7.0
            });

            layer.addObject(polygon, 0);

            var camera = Module.getViewCamera();
            camera.setPermitUnderGround(false);
            // camera.setLimitTilt(-360);

            camera.setTraceTarget(GLOBAL.TRACE_TARGET);
            camera.setTraceActive(true);
        }
    });
}`

**Comment by hjaejae** [comment]
아래와 같은 이벤트를 추가하여 이동 및 회전을 할 수 있습니다.
- 이동
```javascript
window.addEventListener("keydown", function (e) {
		if(gTraceTarget !=null)
		{
		       if(e.key == 'w' ) GLOBAL.TRACE_TARGET.move(1.0, 0.0, true);
			else if(e.key == 's' ) GLOBAL.TRACE_TARGET.move(-1.0, 0.0, true);
			else if(e.key == 'a' ) GLOBAL.TRACE_TARGET.move(0.0, -1.0, true);
			else if(e.key == 'd' ) GLOBAL.TRACE_TARGET.move(0.0, 1.0, true);
		}
    });
```
- 회전
```javascript
_canvas.addEventListener("mousemove", function (e) {
        if (g_bMouseDown) {
            // Mouse left button
            if (e.buttons == 2 && gTraceTarget!=null) {
                GLOBAL.TRACE_TARGET.direction += e.movementX * 0.5;
                GLOBAL.TRACE_TARGET.tilt += e.movementY * 0.5;
            }
        }
    });
```

**Comment by shafqatjamil** [comment]
귀하의 빠른 답변에 감사드립니다. 하지만 제 문제는 조금 다릅니다. 현재 3D 모델과 애니메이션을 사용하고 있으며, 귀하의 버퍼 크기 수정 이후 애니메이션은 정상 작동하고 있지만, 모델의 방향이 올바르지 않습니다. 모델을 폴리곤에 할당했을 때 방향을 수정할 방법이 있을까요? 스크린샷을 확인해 주시면 감사하겠습니다. 모델이 표면 위에 서 있는 대신 표면과 평행하게 정렬되어 있는 상태입니다. 모델의 방향을 x축 기준으로 90도 회전시켜야 할 것 같습니다. 현재 폴리곤에서 사용할 수 있는 회전은 y축 기준으로만 가능한 것으로 보입니다.

제 스크립트를 참고용으로 첨부하였습니다. 답변해 주시면 감사하겠습니다.

https://drive.google.com/file/d/1Q8XIrPU2yab2j1u_U4ZQVtG0UoZNEob-/view?usp=sharing

`function mouseOverInterface(_isOver) {
    if (typeof Module == "object") {
        Module.XDIsMouseOverDiv(_isOver);
    }
}

window.onresize = function (e) {
    if (typeof Module == 'object') {
        if (typeof Module.Resize == 'function') {
            Module.Resize(window.innerWidth, window.innerHeight);
            Module.XDRenderData();
        }
    }
};

var GLOBAL = {
    TRACE_TARGET: null,
    MOUSE_BUTTON_PRESS: false,
    KEY_PRESS_w: false,
    KEY_PRESS_s: false,
    KEY_PRESS_a: false,
    KEY_PRESS_d: false,
    url: "./data/2.mp4",
    model_url: './data/full.glb',
    tilt: 25.4,
    pan: 350,
    far: 1500.0,
    bank: 1.0,
    fovWidth: 89,
    fovHeight: 89,
    zoomDelta: 1.0,
    alpha: 255,
    position: 10,
    xAxis: false,
    yAxis: true,
    videoobj: null,
    poiobj: null,
    videoTimer: null,
    layer: null,
    poilayer: null,
    isVideoClear: false,
    isHLS: false,
    vidlon: 127.06010000000023,
    vidlat: 37.51300000000008,
    vidalt: 80.11999994609505,
    vidAngle: 69,
    startLng: 127.06020000000017,
    startLat: 37.513000000000076,
    startAlt: 22.0,
    animation: -1,
    pause: false,
    m_videoElement: null,          // Video element
    m_layer: null,                 // Building billboard object layer
    m_ledboard: null,               // Building billboard object
    NewModel: null

};



var script = document.createElement('script');
script.src = "./engine/XDWorldEM.js";
document.body.appendChild(script);


//write a function to check if coordinates are within a vidLat, vidLon, vidAlt
function isWithinVidCoordinates(lat, lon, alt) {
    if (lat < GLOBAL.vidlat + 0.0001 && lat > GLOBAL.vidlat - 0.0001 && lon < GLOBAL.vidlon + 0.0001 && lon > GLOBAL.vidlon - 0.0001 && alt < GLOBAL.vidalt + 0.0001 && alt > GLOBAL.vidalt - 0.0001) {
        return true;
    }
    return false;
}
function initEvent(_canvas) {
    window.addEventListener("keyup", function (e) {
        GLOBAL["KEY_PRESS_" + e.key] = false;
    });
    window.addEventListener("keydown", function (e) {
        GLOBAL["KEY_PRESS_" + e.key] = true;
        // createBoard();
        if (e.key == "0") setAnimation(0);    // Move down
        else if (e.key == "1") setAnimation(1);    // Move down
        else if (e.key == "2") setAnimation(2);    // Move down
        else if (e.key == "3") setAnimation(3);    // Move down
        else if (e.key == "4") setAnimation(4);    // Move down
        else if (e.key == "5") setAnimation(5);    // Move down
        else if (e.key == "6") setAnimation(6);    // Move down
        else if (e.key == "7") setAnimation(7);    // Move down
        else if (e.key == "8") setAnimation(8);    // Move down
        else if (e.key == "9") setAnimation(-1);    // Move down
    });


    _canvas.addEventListener("mousedown", function (e) {
        GLOBAL.MOUSE_BUTTON_PRESS = true;
        var screenPosition = new Module.JSVector2D(e.x, e.y);
        var mapPosition = Module.getMap().ScreenToMapPointEX(screenPosition);
        clickedLongitude = parseFloat(mapPosition.Longitude).toFixed(6);
        clickedLatitude = parseFloat(mapPosition.Latitude).toFixed(6);
        clickedAltitude = parseFloat(mapPosition.Altitude).toFixed(6);
        isClickedOnVideo = isWithinVidCoordinates(clickedLatitude, clickedLongitude, clickedAltitude);
        console.log('isClickedOnVideo', isClickedOnVideo);
    });
    _canvas.addEventListener("mouseup", function (e) {
        GLOBAL.MOUSE_BUTTON_PRESS = false;
    });

    _canvas.addEventListener("mousemove", function (e) {
        if (GLOBAL.MOUSE_BUTTON_PRESS) {
            if (e.buttons == 2 && GLOBAL.TRACE_TARGET) {
                GLOBAL.TRACE_TARGET.direction += e.movementX * 0.5;
                GLOBAL.TRACE_TARGET.tilt += e.movementY * 0.5;
            }
        }
    });

    _canvas.addEventListener("wheel", function (e) {
        if (e.wheelDelta < 0 && GLOBAL.TRACE_TARGET) {
            GLOBAL.TRACE_TARGET.distance *= 1.1;
        } else {
            GLOBAL.TRACE_TARGET.distance *= 0.9;
        }
    });



}

function renewObjectMoving() {
    if (GLOBAL.TRACE_TARGET == null) {
        return;
    }
    let anim = -1;
    var move_front = 0.0;
    var move_right = 0.0;

    if (GLOBAL["KEY_PRESS_w"]) {
        move_front = 1.0;
        anim = 7;
        
    } else if (GLOBAL["KEY_PRESS_s"]) {
        move_front = -1.0;
        anim = 0;

    }

    if (GLOBAL["KEY_PRESS_a"]) {
        move_right = -1.0;
        anim = 4;

    } else if (GLOBAL["KEY_PRESS_d"]) {
        move_right = 1.0;
        anim = 6;
    }
    GLOBAL.TRACE_TARGET.move(move_front, move_right, true);
    setAnimation(anim);
    Module.XDRenderData();
}

var Module = {
    locateFile: function (s) {
        return "./engine/" + s;
    },
    postRun: function () {
        Module.initialize({
            container: document.getElementById("map"),
            terrain: {
                dem: {
                    url: "https://xdworld.vworld.kr",
                    name: "dem",
                    servername: "XDServer3d",
                    encoding: true
                },
                image: {
                    url: "https://xdworld.vworld.kr",
                    name: "tile",
                    servername: "XDServer3d"
                }
            },
            worker: {
                use: true,
                path: "./worker/XDWorldWorker.js",
                count: 5
            },
            defaultKey: "DFG~EpIREQDmdJe1E9QpdBca#FBSDJFmdzHoe(fB4!e1E(JS1I=="
        });
        Module.getTileLayerList().createXDServerLayer({
            url: "https://xdworld.vworld.kr",
            servername: "XDServer3d",
            name: "facility_build",
            type: 9,
            minLevel: 0,
            maxLevel: 15
        });

        let target = new Module.JSVector3D(GLOBAL.startLng, GLOBAL.startLat, GLOBAL.startAlt)
        var camera = Module.getViewCamera();
        camera.setLocation(new Module.JSVector3D(GLOBAL.startLng, GLOBAL.startLat, GLOBAL.startAlt + 30));


        TraceTarget(target)
        initEvent(Module.canvas);
        setInterval(renewObjectMoving, 50);
        // createBoard()


    }
};


function TraceTarget(target) {

    var layerList = new Module.JSLayerList(true);
    var layer = layerList.createLayer("glTF_Test", Module.ELT_POLYHEDRON);
    var polygon = Module.createGLTF("GLTF_Object");
    polygon.loadFile({
        url: GLOBAL.model_url,
        type: "glb",
        position: target,
        rotate: 180,
        rebuild: true,
        callback: function (e) {
            // polygon.setAnimationByID(0);
            // polygon.setScale(new Module.JSSize3D(1.0, 1.0, 1.0));
            GLOBAL.TRACE_TARGET = Module.createTraceTarget(polygon.getId());
            GLOBAL.TRACE_TARGET.set({
                object: polygon,
                tilt: 160.0,
                direction: 0.0,
                distance: 7.0
            });

            layer.addObject(polygon, 0);

            var camera = Module.getViewCamera();
            camera.setPermitUnderGround(false);
            // camera.setLimitTilt(-360);


            camera.setTraceTarget(GLOBAL.TRACE_TARGET);
            camera.setTraceActive(true);
        }
    });
}

function createBoard() {
    if (GLOBAL.m_ledboard == null)
        GLOBAL.m_ledboard = Module.createFigure("fig");
    else
        return;

    var layerList = new Module.JSLayerList(true);
    GLOBAL.m_layer = layerList.createLayer("videoLayer", Module.ELT_PLANE);
    GLOBAL.m_layer.setEditable(true);
    GLOBAL.m_layer.setMaxDistance(2000000.0);
    // Module.getViewCamera().moveLookAt(new Module.JSVector3D(GLOBAL.vidlon, GLOBAL.vidlat, GLOBAL.vidalt), 10, 46.99967886409463, 10);
    GLOBAL.m_layer.setMaxDistance(30000.0);
    // Building billboard settings
    let json = {
        url: "./data/2.mp4",
        streaming: false,			// true: For streaming video, false: For video file
        xaxis: true,				// horizontal inversion
        yaxis: false				// vertical inversion
    };
    GLOBAL.m_ledboard.setledBoard(json);
    let vidPos = new Module.JSVector3D(GLOBAL.vidlon, GLOBAL.vidlat, GLOBAL.vidalt)
    let vidSize = new Module.JSVector3D(30, 15, 1)
    GLOBAL.m_ledboard.createFigure(vidPos, vidSize, new Module.JSColor(255, 255, 255, 255), 4);
    GLOBAL.m_ledboard.setAngle(GLOBAL.vidAngle);
    GLOBAL.m_layer.addObject(GLOBAL.m_ledboard, 0);    // Insert Building billboard object into 3D plane object layer
}

// Edit Building billboard
function editBoard() {
    Module.XDSetMouseState(Module.MML_SELECT_POINT);
    Module.getMap().setSelectObject(GLOBAL.m_ledboard);
}

function clearBoard() {
    GLOBAL.m_ledboard.isplayer = false;
    GLOBAL.m_layer.removeAll();
    GLOBAL.m_ledboard = null;
    Module.XDSetMouseState(Module.MML_MOVE_GRAB);
}



function setAnimation(_nID) {
    console.log('setAnimation', _nID);
    var layerList = new Module.JSLayerList(true);
    var layer = layerList.nameAtLayer("glTF_Test");
    if (layer == null) {
        console.log('layer is null');
        return
    };
    var pObject = layer.keyAtObject("GLTF_Object");
    if (pObject == null) {
        console.log('pObject is null');
        return
    };
    if (pObject.getType() != "JSGLTF") {
        console.log('pObject is not JSGLTF');
        return
    };
    pObject.setAnimationByID(_nID);
}

`

**Comment by hjaejae** [comment]
네~ 현재는 Y축 기준으로만 회전이됩니다.
다음 업데이트 예정일인 12월 6일에 hotfix로 기능을 추가하여 업데이트 하겠습니다.

**Comment by shafqatjamil** [comment]
감사합니다. 기대하고 있습니다. 혹시 버퍼 크기를 조절할 방법이 있을까요? 다시 오류가 발생하고 있습니다.

XDWorldEM.js:1 Uncaught RangeError: Maximum call stack size exceeded
    at XDWorldEM.wasm:0x719be
    at XDWorldEM.wasm:0x5055f
    at XDWorldEM.wasm:0x36162
    at XDWorldEM.wasm:0x505b8
    at XDWorldEM.wasm:0x36162
    at XDWorldEM.wasm:0x505b8
    at XDWorldEM.wasm:0x36162
    at XDWorldEM.wasm:0x505b8
    at XDWorldEM.wasm:0x36162
    at XDWorldEM.wasm:0x505b8

**Comment by hjaejae** [comment]
API를 이용해서 조절하는 방법은 현재 없습니다.
혹시 어떤 상황에서 발생하는지 구체적으로 알 수 있을까요?
사용하신 파일도 함께 알려주시면 감사하겠습니다.

**Comment by shafqatjamil** [comment]
3D 애니메이션 GLB 모델을 가져올 때 발생합니다. 모델 파일도 함께 공유드립니다.

https://drive.google.com/file/d/1LCnJIl68QyTWtO-yJA_iQnIZ59a6_mEK/view?usp=sharing

**Comment by shafqatjamil** [comment]
여기에 저의 전체 프로젝트를 공유드립니다. Node 버전 20에서 실행 중이며, http-server로 제공하고 있습니다.

https://drive.google.com/file/d/1cnJIJn0zVLRweA-VnBgxYNAv7W7g9j1a/view?usp=sharing

**Comment by hjaejae** [comment]
확인해보겠습니다.

**Comment by shafqatjamil** [comment]
모든 3개의 축에 대해 스케일 옵션을 추가할 수 있을까요?

**Comment by hjaejae** [comment]
안녕하세요~ 금일 엔진이 업데이트 되어 알려드립니다.

- XYZ축에 대한 회전 및 스케일 기능 추가
```javascript
var polygon = Module.createGLTF("GLTF_Object");
	polygon.loadFile({
		url : url,
		type : "glb",
		position : pos,
		rotate : [ 0, 90, 0], // XYZ 축 방향 회적 각도(Degree)
                scale : [ 1.0, 10.0, 1.0], // XYZ축 방향 스케일 변경. (1.0= 원래 크기)
		rebuild : true,
	});
```

중간에 문의하신 오류 내용에 대해서는 확인되지 않아서 수정되지 않았습니다.

**Comment by shafqatjamil** [comment]
정말 감사합니다! 😊
