### ISSUE TITLE
tilte 조절시 poi이동방향 문의

### ISSUE THREAD

**Issue by Ejeongs2** [EgisCorp/XDWorld#456]
엔진 버전
: XDWorld Version : 2.8.3 (Released 2024-11-15)

문의 내용
: 
기존 poi를 올리는 방식인

`function createPOI(_longitude, _latitude, _altitude, _lineColor) {
	
	var layerList = new Module.JSLayerList(true);
	var layer = layerList.createLayer("POI_TEST", Module.ELT_3DPOINT);
		
	// Load POI image
	var img = new Image();
	img.onload = function() {

		// Draw the image on canvas after loading
		var canvas = document.createElement('canvas');
		var ctx = canvas.getContext('2d');
		canvas.width = img.width;
		canvas.height = img.height;
		ctx.drawImage(img, 0, 0);
		
		// Create the Point POI
		var point = Module.createPoint("POI_"+layer.getObjectCount());
		point.setPosition(new Module.JSVector3D(_longitude, _latitude, _altitude));
		point.setImage(ctx.getImageData(0, 0, this.width, this.height).data, this.width, this.height);
		
		// Set up vertical line for the POI
		point.setPositionLine(100.0, _lineColor);
		
		layer.addObject(point, 0);
	};
	img.src = `http://localhost:8080/onestop/resources/js/test/map-house.svg`
}

function lineTest () {
	Module.getViewCamera().setLocation(new Module.JSVector3D(126.92416038220622, 37.52166339268871, 500.0));
			createPOI(
			126.92522784212862, 37.52163632683868, 13.357510312460363,
			new Module.JSColor(0, 0, 255)
		);
}
`
를 사용하였을때는 카메라의 tilt를 이동시키면 poi위치가 중앙에서 뒤쪽으로 가는 방향으로 움직입니다

https://github.com/user-attachments/assets/b10f44e8-186c-400b-9a13-4ab718c2e7cf

`Module.XDEMapCreateLayer("poi_3d", "http://8080", 0, true, true, false,5, 0, 18)` 
형식으로 불러오는 레이어 poi의 경우 카메라의titlt를 이동시키면 poi위치가 중앙에서 앞으로 가는 방향으로 움직입니다

https://github.com/user-attachments/assets/951d8305-0bc0-40ba-b1f5-0cdff398f4a6

`Module.XDEMapCreateLayer("poi_3d", "http://8080", 0, true, true, false,5, 0, 18)`  의 경우에도 title이동시 중앙에서 뒤쪽으로 가는 방향으로 가능한지 문의 드립니다

**Comment by hjaejae** [comment]
위 동영상을 봤을 때 POI는 제자리에 그대로 있는 것 같습니다.
첫 번째 동영상의 POI는 지형보다 높게 떠 있어서 Tilt 값을 낮추면 멀리 가는 것처럼 보이는 것이고
두 번째 동영상의 POI 지형 밑에 있는 것 같습니다. 그렇기 때문에 Tilt를 낮췄을 때 앞을 나오는 것처럼 보이는 것 같습니다. 

![POI](https://github.com/user-attachments/assets/2262326a-8dfa-4d3a-a97a-414e1a59e1e5)

위 그림과 같이 회전을 하게 되면 회전 중심에서 하나의 객체는 멀어지고 다른 하나는 카메라와 가까워집니다.
보여주신 동영상의 POI는 회전하는 중심이 지형이고 하나의 객체는 지형 위쪽 다른 하나의 객체는 지형 아래 쪽에 있어서 설명해주신 현상이 일어나는 것으로 보입니다. 

첫 번째 동영상처럼 작동하기 위해서는 두 번째의 POI 높이를 지형 위쪽으로 해서 만들 필요가 있을 것 같습니다.
