### ISSUE TITLE
폴리곤 setHeight 관련

### ISSUE THREAD

**Issue by minochae** [EgisCorp/XDWorld#458]
엔진 버전
: XDWorld Version : 2.9.0 (Released 2024-11-29)

문의 내용
: createPolygon으로 생성된 객체에 대해 setHeight를 통해 입체 도형으로 생성이 가능한데

이때 입력된 높이 파라미터는 각 꼭지점의 고도값 + 높이로 적용되어 전체 폴리고이 고도에 의해 높낮이가 다른 형상으로 생성됩니다. 

특정 지점의 지형 고도를 기준으로 입체도형을 만들수 있는 API가  추가되었으면 합니다.

즉 특정지점의 지형고도가 10일때 높이 파라미터에 10을 입력하면 모든 꼭지점의 고도가 20이되면 됩니다.

검토부탁드립니다.

![image](https://github.com/user-attachments/assets/f38e7110-e0b5-446b-8f15-899bd3fe2997)

**Comment by HeoTaeYang** [comment]
안녕하세요.
요청하신 API 추가하도록 하겠습니다.
기능을 완성하는 대로 안내드리겠습니다.

**Comment by HeoTaeYang** [comment]
안녕하세요.
방금 전 해당 기능이 포함된 2.9.1(hotfix) 엔진이 배포되었습니다.
엔진의 2.9.1_hotfix 배포 버전을 사용하여 주시기 바랍니다.
