### ISSUE TITLE
카메라 애니메이션 속도를 줄였음에도 불구하고 예제에서 속도가 느려지지 않습니다. 수정해 주실 수 있을까요?

### ISSUE THREAD

**Issue by shafqatjamil** [EgisCorp/XDWorld#459]
카메라 애니메이션 속도를 줄였음에도 불구하고 예제에서 속도가 느려지지 않습니다. 수정해 주실 수 있을까요?
[링크: https://sandbox.egiscloud.com/code/main.do?id=camera_move_path](https://sandbox.egiscloud.com/code/main.do?id=camera_move_path)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

샌드박스 샘플에서 확인 결과 정상동작하는것을 확인했습니다.

```javascript
// 카메라 이동 애니메이션 속도
// 아래 코드를 실행 할 경우 카메라 이동 시 속도가 확연하게 느린것을 확인할 수 있습니다.
GLOBAL.Camera.setAnimationSpeed(1);

// 카메라 자동이동 프레임 속도 조절
// 아래 코드를 실행 할 경우 카메라 자동이동시 속도가 확연하게 느린것을 확인할 수 있습니다.
GLOBAL.Camera.setAutoMoveWaitFrame(20);	// Set automatic movement execution interval
```

* 메뉴얼
[카메라 자동이동 속도 조절](https://egiscorp.gitbook.io/xdworld-webgl-manual/introduce-1/camera/jscamera#setautomovewaitframe-speed-boolean)

[카메라 이동 애니메이션 속도 조절](https://egiscorp.gitbook.io/xdworld-webgl-manual/introduce-1/camera/jscamera#getanimationspeed-setanimationspeed-speed-greater-than-number)

**Comment by shafqatjamil** [comment]
setAutoMoveWaitFrame 값을 증가시키면 카메라가 부드럽게 이동하나요?

**Comment by egiskorea-ryong** [comment]
setAutoMoveWaitFrame 는 카메라 이동을 몇 프레임 마다 할 것인지 설정하는 api 입니다.

값을 증가 시키면 카메라 이동 속도가 느려집니다.

**Comment by shafqatjamil** [comment]
GLOBAL.Camera.setAnimationSpeed(1); // 카메라 이동 애니메이션 속도 감소
GLOBAL.Camera.setAutoMoveWaitFrame(20); // 자동 이동 실행 설정

위 설정으로 카메라 이동 속도는 느려지지만, 부드럽지 않고 흔들리는 문제가 있습니다.

**Comment by egiskorea-ryong** [comment]
사용하신 코드와 동영상을 첨부해주시면 확인해보겠습니다.

**Comment by shafqatjamil** [comment]
저는 현재 [이 링크](https://sandbox.egiscloud.com/code/main.do?id=camera_move_path)를 사용해 테스트 중입니다.
코드의 90번 줄과 91번 줄을 다음과 같이 변경했습니다:
`
GLOBAL.Camera.setAnimationSpeed(1);  // 카메라 이동 애니메이션 속도 감소
GLOBAL.Camera.setAutoMoveWaitFrame(20);  // 자동 이동 실행 설정
`
코드를 실행하면 카메라가 움직였다가 멈추고, 다시 움직였다가 멈추는 현상이 발생합니다. 결과적으로 이동이 부드럽지 않습니다.

**Comment by egiskorea-ryong** [comment]
카메라 자동 이동의 경우 프레임 단위로 속도조절을 하고 있습니다.

처음에 설명 드렸듯이 GLOBAL.Camera.setAnimationSpeed(1); 는 자동이동과는 무관합니다.

자동이동 기능에서 속도조절을 원하시면 GLOBAL.Camera.setAutoMoveWaitFrame(20);  만 사용하시면 됩니다.

해당 API는 지정된 경로에서 이전 지점에서 다음 지점까지 몇 프레임이 지난 후 움직일지 설정하는 것입니다.

현재는 프레임 단위 외에 별도로 자동이동 기능에서 속도를 조절하는 기능은 없습니다.

**Comment by egiskorea-ryong** [comment]
안녕하세요.

이미 구현된 API를 조합하여 원하시는 기능을 구현할 수 있습니다.

SetAutoMoveIntrerval 는 구간 사이의 점 수를 설정하여 해당 구간을 얼만큼 정교하게 이동할 것 인지 설정합니다.

[사용법]
```javascript
...
GLOBAL.Camera.SetAutoMoveIntrerval(1);
GLOBAL.Camera.setAutoMovePosition(vMovePositionList);
GLOBAL.Camera.setAnimationSpeed(10);
GLOBAL.Camera.setAutoMoveWaitFrame(10);
```

setAutoMoveWaitFrame(10); SetAutoMoveIntrerval(1); 값을 조절하여 원하시는 속도를 도출하시면 됩니다.

감사합니다.
