### ISSUE TITLE
WFS 레이어 초기화하는 방법

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#46]
안녕하세요.
지도 상에 WFS 가시화 -> 레이어 중 일부 위치 정보 수정 -> WFS 초기화 및 가시화를 하려고 하는데,
아래와 같은 방법으로 시도하였을 때 레이어가 새로 생성된것은 확인하였지만 가시화가 되지 않습니다.
제가 빠뜨리거나 잘못 사용한 부분이 있을까요?

```
 function loadWFS_3D(layerid) {
    	Module.SetProxy("./proxy.do?url=");
    	
    	var layerList = new Module.JSLayerList(false);
    	var layer = layerList.createWFSLayer(storage+":"+layerid, 0);
    	
    	layer.setProxyRequest(true);
    	
    	layer.setConnectionWFS(url, 0, "");
    	layer.setLevelWFS(7);
    	layer.setLayersWFS(storage+":"+layerid);
    	layer.setWFSPointPositionLine(true);	
    	layer.setWMSVersion("1.0.0");
    	layer.setRequestFeatureCount(1000);
    	layer.setBBoxOrder(true);
    	
    	loadIcon(layerid, "images/maps/layer_icon/"+layerid+".png", function(_icon) {
    		layer.setWFSPointDefaultIcon(_icon);
    	});
    	
        Module.setVisibleRange(storage+":"+layerid, 1.0, 100000000.0);

        layer.setVisible(true);
}
```

1. WFS 로드 후 가시화
```
loadWFS_3D(레이어명);
```

2. 위치 수정 후 레이어 삭제 및 재로드
```
var layerList = new Module.JSLayerList(false);
layerList.delLayerAtName(저장소명 + ":" + 레이어명);

loadWFS_3D(레이어명);
```

2번에서 delLayerAtName() 후 
```
var layerList = new Module.JSLayerList(false);
var layer = layerList.nameAtLayer(저장소명 + ":" + 레이어명);
```
로 테스트 해보았을 때, layer가 null 이 되었고, loadWFS_3D 후에 다시 값이 생기는 것을 확인하였습니다.

**Comment by YunSumin** [comment]
새로 WFS 레이어를 추가하시고 난 후
네트워크 탭에서 지오서버 wfs 레이어로 요청이 지속적으로 가면서도 포인트 표출이 되지 않는다면

전송해주신 loadWFS_3D 함수 중 중 
```
loadIcon(layerid, "images/maps/layer_icon/"+layerid+".png", function(_icon) {
    	layer.setWFSPointDefaultIcon(_icon);
});
```

부분에서 이미지 로드 시 setWFSPointDefaultIcon 이 호출되지 않아
wfs 데이터는 수신하되, 표출할 포인트가 지정되지 않아서 가시화가 되지 않는 것이 아닌가 하는 생각이 듭니다.

반대로 네트워크 탭에 wfs 타일 요청 자체가 없다면 wfs 레이어 호출 부분을 확인해야 하므로,
타일 요청 여부를 확인해 보신 뒤 다시 문의 주시면 더 상세히 원인을 확인해보겠습니다.

**Comment by KIMSEONOK** [comment]
delLayerAtName 후 loadWFS_3D를 했을 때 네트워크 탭에 지속적으로 지오서버 WFS 레이어 요청이 찍혔고,
과장님 말씀대로 loadIcon 내부에 layer.setWFSPointDefaultIcon(_icon);가 호출되지 않았습니다.
디버깅을 걸어 확인해보니 loadIcon 함수 내에서 

```

1. function loadIcon(_iconName, _url, _callback) {
2. 
3.     // 이미지 관리 심볼 반환
4.     var symbol = Module.getSymbol();
5. 
6.     // 이미지 로드
7.     var img = new Image();
8. 	img.onload = function() {
9. 
10.         // canvas를 통해 이미지 데이터 생성
11. 		var canvas = document.createElement('canvas');
12. 		canvas.width = img.width;
13. 		canvas.height = img.height;
14. 
15.         var ctx = canvas.getContext('2d');
16. 		ctx.drawImage(img, 0, 0);
17. 
18. 		var imageData = ctx.getImageData(0, 0, canvas.width, canvas.height).data;
19. 
20. 		// 생성된 아이콘 이미지 콜백 반환
21. 		if (symbol.insertIcon(_iconName, imageData, canvas.width, canvas.height)) {
22. 			var ab = symbol.getIcon(_iconName);
23. 			_callback(ab);
24.         }
25.     };
26.     img.src = _url;
27. }

```
21번째 줄 symbol.insertIcon(_iconName, imageData, canvas.width, canvas.height) 에서 false를 반환합니다.
아래의 이미지는 insertIcon을 탔을 때 디버깅 결과입니다.

![image](https://user-images.githubusercontent.com/49426364/126757323-4c3bd887-edc3-435d-b65c-d183136c0256.png)

**Comment by YunSumin** [comment]
전달해 주신 코드를 토대로 확인해 본 결과
delLayerAtName 로 레이어 삭제 시 JSSymbol에 등록된 JSIcon도 함께 삭제되는 오류가 확인되었습니다.
현재 오류 수정하여 git에 반영하였습니다.  최신 엔진으로 적용하시면 수정 사항을 적용하실 수 있습니다.

symbol.insertIcon API는 이미 동일한 이름(_iconName)의 JSIcon이 있는 경우 false가 반환 됩니다.
아래와 같이 getIcon으로 JSIcon 객체를 반환 받으시고 JSIcon이 존재하지 않는 경우
insertIcon API를 호출하는 하는 방향으로 작성하시면 중복 insert 없이 사용 가능하실 것 같습니다. 

```
/* 포인트 이미지 로드 */
function loadIcon(_iconName, _url, _callback) {

	// 아이콘 유무 확인 후 없는 경우 생성
	var icon = Module.getSymbol().getIcon(_iconName);
	if (icon != null) {
		_callback(icon);
	} else {
		 // 이미지 관리 심볼 반환
		var symbol = Module.getSymbol();

		 // 이미지 로드
		var img = new Image();
		img.onload = function() {
	
			 // canvas를 통해 이미지 데이터 생성
			var canvas = document.createElement('canvas');
			canvas.width = img.width;
			canvas.height = img.height;
	
			var ctx = canvas.getContext('2d');
			ctx.drawImage(img, 0, 0);
	
			var imageData = ctx.getImageData(0, 0, canvas.width, canvas.height).data;
	
			 // 생성된 아이콘 이미지 콜백 반환
			if (symbol.insertIcon(_iconName, imageData, canvas.width, canvas.height)) {
				_callback(symbol.getIcon(_iconName));
			}
		};
		img.src = _url;
	}   
}
```


감사합니다.

**Comment by KIMSEONOK** [comment]
새로운 엔진 교체 후 기존에 사용하던 API에서 오류가 발생하여 테스트를 하지 못하는 상황입니다ㅠㅠ
```
function setLegendColorList() {
	
	var jsSlope = GLOBAL.Slope;
	if (jsSlope == null) {
		return;
	}
	// 경사도 분석 색상 설정
	jsSlope.insertColorList(0,  0, 10, new Module.JSColor(119, 147, 60));
}
```
위 함수를 호출할 때 "Uncaught TypeError: jsSlope.insertColorList is not a function" 라는 오류가 발생하는 상태입니다.

**Comment by YangHeeBong** [comment]
경사 도, 향 기능 변경이 전반적으로 생겨서 아래 url을 참조하시기 바랍니다.

http://sandbox.dtwincloud.com/code/main.do?id=analysis_terrain_direction

파라미터 API 형식에서 Json API 형식으로 변경되었습니다.

변경이유는 경사 분석 기능 요청에 따른 파리미터  변경, 추가가 자주 있고 그로 인해 엔진 버젼마다 API 사용 방법이 변경되는 문제가 발생되었습니다. 

샌드박스에서 아래 함수 위주로 보시면 될 것 같습니다.

function setLegendColorList : 범례적용
function ExcuteSlopeAnalysis : 분석 실행
function createRTTPixel : Callback으로 이미지 생성

**Comment by YangHeeBong** [comment]
하나의 이슈 사항에 다른 이슈 질문의 자제 해주시고 새로운 이슈로 등록을 부탁드립니다.

해당 이슈 제목으로 관련 내용에 답변 하는 시스템이다 보니 이슈 명칭과 다른 명칭에 대한 질문이 들어오면 

관련자가 확인 못하는 문제가 생길 수가 있습니다.

**Comment by KIMSEONOK** [comment]
네 알겠습니다. 덕분에 잘 해결했습니다! 감사합니다ㅎㅎ
