### ISSUE TITLE
고스트심볼 opacity 설정 관련

### ISSUE THREAD

**Issue by minochae** [EgisCorp/XDWorld#460]
엔진 버전
: XDWorld Version : 2.9.0 (Released 2024-11-29)

오류 발생 API
: setOpacity(opacity)

오류 내용
: 값 설정시 고스트심볼이 사라짐 
 값의 범위에 대한 정의가 문서에 없어서 0~255 또는 0~1로 넣어서 테스트 해보는데 모든 값이 다 사라짐
 확인 부탁드리며 문서 업데이트 요청

**Comment by egiskorea-ryong** [comment]
안녕하세요.

고스트심볼에 opacity property가 있습니다.

사용법은 object.opacity = 0.1;  // 값의 범위는 1.0 ~ 0.0 입니다.

메뉴얼에 해당 사항 업데이트 및 값의 범위를 1.0 ~ 0.0 이 아닌 0 ~ 255로 엔진 변경하여 배포하도록하겠습니다.

감사합니다.
