### ISSUE TITLE
오류 확인 요청

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#47]
안녕하세요. 바이브컴퍼니입니다.

특정 pc에서 아래와 같은 오류가 발생하였습니다.
오류 확인 요청합니다.

![image](https://user-images.githubusercontent.com/38479834/127252891-00109cde-3218-4609-bb74-58691e70654e.png)

[pc사양]
![image](https://user-images.githubusercontent.com/38479834/127253655-59dad727-9212-4107-8162-0afd187c23e7.png)

**Comment by YangHeeBong** [comment]
위 에러는 그래픽 카드와 관련이 있습니다. 혹시 그래픽 자원 종류를 알 수 있을까요?

**Comment by HyunSeongKil** [comment]
맥에 부트캠프로 윈 10 깔고 사용하는데
맥 그래픽 카드가 문제겠군요.. 쩝..\
iMac17,1 사용하고 있습니다.

Chipset Model:	AMD Radeon R9 M395X
 Type:	GPU
 Bus:	PCIe
 PCIe Lane Width:	x16
 VRAM (Total):	4 GB

**Comment by avamk2** [comment]
확인해보니 GPU에서 엔진내에 출력되는 스팩정보를 보니 정상적인 제원이 아닌 상황입니다. 같은 장비로 MAC OS에서 구동했을때 잘된다면 해당 GPU용 윈도우용 드라이버가 문제로 보여집니다.

**Comment by Ryu-Joon-Hyuck** [comment]
자체 해결했습니다.

웹 브라우저에서 하드웨어 가속이 사용을 못할 경우,
EGIS map이 표시가 되지 않고, 검은 화면만 나타나는 현상을 발견했습니다.
이럴 경우 하기 링크의 내용을 참고하면 표시가 됩니다.

https://shub.tistory.com/entry/%EA%B5%AC%EA%B8%80-%ED%81%AC%EB%A1%AC-GPU-%EA%B0%80%EC[…]5%88%EB%90%A0%EB%95%8C-%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95
