### ISSUE TITLE
Add3DPoint() 사용 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#49]
안녕하세요. 바이브컴퍼니입니다.

아래 코드 정상 동작하는거 맞나요?
![image](https://user-images.githubusercontent.com/38479834/127421532-d0594431-268e-4b4c-96fe-a221a927fe18.png)

Add3DPoint()함수는 파라미터가 9개 필요하다고 하는데...
![image](https://user-images.githubusercontent.com/38479834/127421802-250aaf30-cd7b-4726-993f-0a638d81baf4.png)

그럼,...

**Comment by YunSumin** [comment]
Module.getAddObject().Add3DPoint API는 
- 레이어 이름(layeName)
- 오브젝트 키(key)
- 경도(lon)
- 위도(lat)
- 고도
- 이미지 픽셀 데이터(imageData)
- 이미지 가로 크기(width)
- 이미지 세로 크기(height)
- 텍스트(text)
파라미터로 구성됩니다.
현재 코드에서는 5번째 고도 값이 없는 것 같습니다. 추가 부탁 드립니다.

**Comment by HyunSeongKil** [comment]
보내주신 샘플에 고도가 없어서 그것도 문의 하려고 했던건데..... ㅋ

**Comment by YunSumin** [comment]
엔진 내부 코드를 확인해 본 결과 위 아홉 파라미터를 사용하시면 될 것 같습니다.
샘플은 현재 깃 이슈와 다르게 별도로 전송된 샘플 같습니다. 샘플에서 고도 부분이 누락된 것 같아 이 부분 추가 부탁 드립니다.
작업에 번거로움을 더한 점 사과드립니다.

**Comment by HyunSeongKil** [comment]
추가로 하나 더 문의합니다.

zoon in/out 에 따라 이미지가 표시/미표시 됩니다.
setMaxDistance()처럼.....뭔가 설정하는게 있는지요?

**Comment by YunSumin** [comment]
입력하신 레이어 이름(layerName)을 활용하여 가시 거리를 조정하실 수 있습니다.

```
// Add3dPoint 파라미터로 넘겼던 layerName 문자열로 레이어 객체를 반환합니다.
var layerList = new Module.JSLayerList(true);
var layer = layerList.nameAtLayer(레이어 이름);

// 레이어 객체를 이용해 레이어 가시 범위를 조정합니다.
layer.setMinDistance(1.0);
layer.setMaxDistance(100000.0);
```

**Comment by HyunSeongKil** [comment]
잘 되네요~
