### ISSUE TITLE
태풍 반경이 요렇게 보이면 되나요?

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#50]
안녕하세요. 바이브컴퍼니입니다.

알려주신 코드를 기반으로 구현해 보았습니다.
태풍 반경이 요렇게 보이는게 맞는건가요?

![image](https://user-images.githubusercontent.com/38479834/127430704-3c5c65f1-06d8-42fa-8b2d-af97402a009b.png)

그럼, ...

**Comment by YangHeeBong** [comment]
지금 2가지 문제가 보입니다.
z-fighting, 알파값 조절
z-fighting 문제로 반경이 겹치는 부분에서 지글 거리는 현상이 나오고 있기 때문에 고도 조절이 필요해 보이며
알파값 조절이 없어서 반경 끝부분이 부드럽게 표현되지 않는 것 같습니다.

**Comment by HyunSeongKil** [comment]
이렇게 되면 알파값은 설정된 거죠?
![image](https://user-images.githubusercontent.com/38479834/127437454-44e0ad8a-7176-4f5f-9ecc-dc5b1a96cc3a.png)


z-fighting....은....
태풍의 고도값을 알 수 없는데....
각 점의 고도값을 임으로 다르게 설정해서 z-fighting 현상을 회피해야 한다는 건가요?

**Comment by YangHeeBong** [comment]
네 z-fighting은 겹침 현상으로 고도 조절로 해결 가능합니다.

**Comment by HyunSeongKil** [comment]
고도값을 얼마 정도의 값으로 조절해야 하나요?


예를 들어 태풍 위치가 10개 있다고 하면
1번째 태풍 높이는 100
2번째 태풍 높이는 200
3번째 태풍 높이는 300
...
10번째 태풍 높이는 10000


이렇게 설정하라는 말씀인가요?

**Comment by YangHeeBong** [comment]
고도 조절은 반경 크기와 구면각에 따라 고도가 다르기 때문에 직접 조절 하셔야 하고

높이는 순차적으로 낮은 높이에서 높은 위치로 또는 지그재그로 설정 하시면 될 것 같습니다.

**Comment by HyunSeongKil** [comment]
임의로 태풍의 고도를 설정하면....

위에서 볼때는 무리없이 잘 보이겠지만
옆에서 보면 태풍마다 고도(높이)가 다르게 보일 수 있겠네요?

**Comment by YangHeeBong** [comment]
네 고도가 다르기 때문에 다른 형태로 보입니다.

바이브에서는 전체 반경 폴리곤 생성, 이미지 생성 해서 표현도 가능하니

바이브 내부적으로 내용을 정리해서 선택하시면 됩니다.
