### ISSUE TITLE
태풍 가시화 관련 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#51]
안녕하세요. 바이브컴퍼니입니다.

3-2 코드만 구현하였는데 지도상에 아무런 변화가 없습니다.

![image](https://user-images.githubusercontent.com/38479834/127442680-980da962-8c85-4f45-b34a-f776fdfee391.png)

1)
3-1 코드 없이 3-2만 구현하면 안되는건가요?

2)
3-2코드 정상 동작하는거 맞나요?
코드를 보면...
vertices같은건.... 값을 push()했는데....어디에도 사용되는 곳이 없고...
화면에는 아무런 변화가 없고.....해서 문의해 봅니다.

**Comment by YangHeeBong** [comment]
코드 부분에 부족한 부분이 있어 아래 소스를 참조 하시면 될 것 같습니다.

function init() {

	let lon, lat, radius;
	lon = 126.92604898457509;
	lat = 37.524222576370335;
	radius = 1000;
	pointCount = 10;
	Module.XDSetCamPositionLonLat(lon, lat, 10000.0, 45);


	var polygon = Module.createPolygon("POLYGON_FLOW_EFFECT");
	var map = Module.getMap();
	map.setCircleInputPoint(new Module.JSVector2D(lon, lat), radius, pointCount);

	var circleVertices = map.getInputPoints();
	var vertices = new Module.JSVec3Array();

	for (var i = 0; i < circleVertices.count(); i++) {
		vertices.push(new Module.JSVector3D(circleVertices.get(i).Longitude, circleVertices.get(i).Latitude, 100));
	}

	// uv 좌표 계산
	var polygonRect = getPolygonRect(vertices);
	var width = Math.abs(polygonRect.max.lon - polygonRect.min.lon);
	var height = Math.abs(polygonRect.max.lat - polygonRect.min.lat);

	var uv = new Module.JSVec2Array();
	for (var i = 0; i < vertices.count(); i++) {
		uv.push(new Module.JSVector2D(
			(Math.abs(polygonRect.min.lon - vertices.get(i).Longitude) / width),
			(Math.abs(polygonRect.max.lat - vertices.get(i).Latitude) / height)
		));
	}

	var part = new Module.Collection();
	part.add(vertices.count());
	polygon.setPartCoordinatesUV(vertices, part, uv, true);

	check = polygon.setWaterEffect(true, {
		flow_map_url: "이미지 URL 경로"[ex]"http://127.0.0.1/image/image.png",
		flow_map_width: 1024,
		flow_map_height: 1024
	});

	console.log(check);

	var polygonStyle = new Module.JSPolygonStyle();
	polygonStyle.setOutLine(true);
	polygonStyle.setOutLineColor(new Module.JSColor(0, 0, 0, 0));
	polygon.setStyle(polygonStyle);

	var layerList = new Module.JSLayerList(true);
	var layer = layerList.createLayer("POLYGON_FLOW_EFFECT_LAYER", Module.ELT_POLYHEDRON);
	layer.setMaxDistance(10000000.0);

	layer.addObject(polygon, 0);
	Module.getMap().clearInputPoint();
}

function getPolygonRect(_positions) {

	var min = {
		lon: _positions.get(0).Longitude,
		lat: _positions.get(0).Latitude
	};

	var max = {
		lon: _positions.get(0).Longitude,
		lat: _positions.get(0).Latitude
	};

	for (var i = 1; i < _positions.count(); i++) {

		if (_positions.get(i).Longitude < min.lon) {
			min.lon = _positions.get(i).Longitude;
		} else if (_positions.get(i).Longitude > max.lon) {
			max.lon = _positions.get(i).Longitude;
		}

		if (_positions.get(i).Latitude < min.lat) {
			min.lat = _positions.get(i).Latitude;
		} else if (_positions.get(i).Latitude > max.lat) {
			max.lat = _positions.get(i).Latitude;
		}
	}

	return {
		min: min,
		max: max
	};
}

추후 setWaterEffect API는 변경 될 예정이면 샌드 박스에서 다시 제공하겠습니다.

**Comment by HyunSeongKil** [comment]
고맙습니다~
