### ISSUE TITLE
태풍관련 이메일 첨부파일 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#53]
안녕하세요. 바이브컴퍼니입니다.

태풍관련 이메일에 첨부파일이 2개 있습니다.

이 파일의 용도는 무엇입니까?
![image](https://user-images.githubusercontent.com/38479834/127470506-1111e7ae-831f-4556-8171-e6461a4b555d.png)

그럼,...

**Comment by YunSumin** [comment]
해당 파일은 물 효과 폴리곤에서 동심원으로 퍼져 나오는 물의 방향을 정의하기 위한 이미지입니다.
