### ISSUE TITLE
마우스 휠 처리 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#55]
안녕하세요. 바이브컴퍼니입니다.

마우스 휠 처리 문의입니다.

div등에서 마우스 휠 이벤트 발생시 맵이 이동되는 현상을 막기위해 아래와 같은 코드를 추가하였습니다.
해서, 해당 문제가 해결되었습니다.

[맵 이벤트 무력화 코드]
![image](https://user-images.githubusercontent.com/38479834/127592661-e8d35bef-2fd2-43e6-b10c-a771cf39f02c.png)

그런데...
angular + material design + &lt;mat-select&gt; 사용시 아래 동영상과 같은 현상이 발생합니다.
위의 이미지와 같은 코드를 추가했으나 동일 현상이 여전히 발생합니다.

해결을 위한 다른방법이 있는지 문의합니다.

[증상]
https://user-images.githubusercontent.com/38479834/127592585-348105cf-152f-47e5-91db-dca7891b2c22.mp4

그럼,...

**Comment by Khaia** [comment]
해당 element tag 에 class="noSroll" 을 정의 하고

jQuery 를 활용해

$(".noScroll").mouseenter(function() {
    Module.XDIsMouseOverDiv(true);
}..mouseleave(function() {
     Module.XDIsMouseOverDiv(false);
});

위와 같이 처리하면 noScroll 클래스를 가진 모든 태그에 일괄 적용됩니다.
