### ISSUE TITLE
3ds 레이어 위치값 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#56]
안녕하세요

.3ds 파일로 지도상에 레이어를 표출할 때 해당 레이어의 위치값을 구할 수 있을까요?

레이어 위치 이동 등 여러 기능에 필요하여 문의드립니다

**Comment by YunSumin** [comment]
레이어 객체(JSLayer)에 포함된 오브젝트(JSPolygon) 정보를 순차적으로 받아오신 후,
JSPolygon의 getCenter API로 중앙 경위도 및 고도 값을 반환 받으실 수 있습니다.

```
var layerList = new Module.JSLayerList(true);
var layer = layerList.nameAtLayer(레이어이름);

for (var i=0; i<layer.getObjectCount(); i++) {
      var object = layer.indexAtObject(i);
      var objectPosition = object.getCenter();      // 각 오브젝트의 중앙 좌표 반환
      console.log(objectPosition);
}
```

위 코드로 적용 및 테스트 부탁 드립니다.

**Comment by giyoon99** [comment]
확인했습니다!
레이어가 로딩되기전 해당 함수를 호출하면 값이 제대로 안나오는듯 하여 사용 시 참고 하시길 바랍니다
감사합니다!
