### ISSUE TITLE
WMS LOD 레벨 확대에 따른 기능결함

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#57]
안녕하세요 
WMS 레이어 가시화할때 풀줌 땅기면 해당 레이어가 사라지는 문제가 있습니다.
해당 부분에 대해서 결함이 있는거 같은데 확인 부탁드립니다
![image](https://user-images.githubusercontent.com/3315478/128668294-aed15375-b2d0-43c4-accd-03be8aa2798e.png)

**Comment by HyunSeongKil** [comment]
그치...이거 나도 문의하려고 했던건데

**Comment by avamk2** [comment]
안녕하세요  

관련샘플 내용중에 maxmumLevel 설정관련이 있습니다. 
http://sandbox.dtwincloud.com/code/main.do?id=layer_wms

기본값이 15레벨인데 VWorld 영상 이미지 최대 레벨이 16레벨이라 16이상으로 수치를 올리시면 위에 문제가 해결될 것으로 보입니다.

**Comment by loeaf** [comment]
위 수치를 조정해도 사라집니다... WMS 요청이 가지 않으면 바닥 텍스처는 사라지지 않고 유지되는게 맞는거 같은데.... 바닥 텍스처가 disable 되내요

**Comment by avamk2** [comment]
사용하신 샌드박스에 아래 링크로 구현하신게 맞다면
http://sandbox.dtwincloud.com/code/main.do?id=layer_wms

`// WMS UI 데이터 입력
	strUrl = document.getElementById("url").value;
	strLayer = document.getElementById("layer").value;
	strCrs = document.getElementById("crs").value;							// [Default EPSG:4326] SRS도 CRS값 적용
	numMinlevel = Number(document.getElementById("minmumLevel").value);		// [Default 0] 
	//numMaxlevel = Number(document.getElementById("maxmumLevel").value);		// [Default 15] 
	numTileSize = Number(document.getElementById("tileSize").value);		// [Default 256] 
    numMaxlevel = 13; // 13레벨 최대적용 강제`
    
    테스트 결과처럼 14레벨 영상 서비스 환경에서 13레벨로 한단계 차이로 인한 영상 누락이 일어납니다.

**Comment by loeaf** [comment]
![image](https://user-images.githubusercontent.com/3315478/129156683-c6d340bc-6aaf-4e9d-9cf8-0063ef84ff17.png)

**Comment by avamk2** [comment]
코드내용으로 문제사항을 확인했습니다. 
해당 부분에 대한 수정본을 추후 엔진업데이트를 진행할 예정입니다.
긴 시간은 걸리지 않을 것으로 생각됩니다.

**Comment by YangHeeBong** [comment]
태그 변경 
   1. minmumLevel -> minimumlevel [태그 미 설정 시 [Default 0]]
   2. maxmumLevel -> maximumlevel [태그 미 설정 시 [Default 20]]
   3. tileSize -> tilesize [태그 미 설정 시 [Default 256]]
   
변경 되었으며 태그 명칭은 전부 소문자로 잘못된 명칭을 다시 수정하였습니다.

**Comment by loeaf** [comment]
![image](https://user-images.githubusercontent.com/3315478/129317407-ce245fa2-be79-44f8-9f91-cc926cddb0b3.png)
감사합니다
