### ISSUE TITLE
3차원 건물 텍스처 변경

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#58]
건물에 대한 텍스처를 이러한 형태로 3차원으로 표현하고 싶은데 유사한 기능이 있을까요?
![image](https://user-images.githubusercontent.com/3315478/129155896-61743767-a57d-4501-8c4a-efea52184afb.png)
![image](https://user-images.githubusercontent.com/3315478/129156022-e579208d-7ec5-48a4-9f9d-3cc7166d7529.png)

**Comment by avamk2** [comment]
안녕하세요 

해당 사항은 3D 모델 제작에 관련된 사항과 엔진내부적 기능 확장 2가지가 필요해서 저희 내부적으로 기능에 대한 지원 방향을 검토 후에 답변을 드리겠습니다.

시간이 필요한점을 양해바랍니다.

**Comment by loeaf** [comment]
동정보는 상단에 라벨로 표출하더라도 호수를 각 층마다 보여줘야하는 부분에 문제가 있습니다
꼭 필요한 기능으로 검토 부탁드립니다
감사합니다

**Comment by avamk2** [comment]
모델에 텍스쳐 적용은 UV 맵핑이라고 하는 정보가 필요로합니다.
UV 맵핑에 관련된 정보 링크 : https://www.spiria.com/en/blog/desktop-software/understanding-uv-mapping-and-textures/

텍스쳐를 가진 모델은 UV 맵핑 좌표 정보를 갖고 있으며 반대로 텍스쳐가 없는 모델링은 UV 맵핑 좌표 정보가 존재하지 않습니다.

![image](https://user-images.githubusercontent.com/82994540/129693610-08e85986-5b1e-43bd-abf5-01f444dd9a77.png)

![image](https://user-images.githubusercontent.com/82994540/129693969-e5464f1c-e315-4e95-8951-dc98509deebe.png)

그래서 UV 맵핑을 위해서는 모델링 툴( 3D MAX, Maya, Blender 등)에서 모델제작단계에서 텍스쳐 이미지를 모델의 원하는 위치에 배치하는 과정에서 만들어지게 됩니다. 허나 이미 만들어진 모델링에서는 아무 이미지를 가져다가 원하는 위치에 맞추는 것은 거의 불가능한 일입니다. 심지어 텍스쳐가 없는 모델 (대표적으로 BIM)은 UV 맵핑 좌표정보가 존재하지 않습니다.

기능적으로 모델링 제작단계에서 하나의 모델 (A)에 건물외형 실사텍스쳐(가), 카툰텍스쳐(나), 호수텍스쳐(다) 식으로 미리 텍스쳐 셋트를 만들어 두었다면. 초기모델 로딩에서 (A) + (가)를 통한 가시화를 진행하다가 API적으로 (나) 또는 (다) 텍스쳐로 교체를 요헝하면 이를 스위칭하여서 바꿀수는 있습니다.
다만 (A)랑 다른 모델 (B)를 가지고 실사텍스쳐(라) 뿐이 없는데 (B) + (다) 조합 같은 경우는 엉뚱하게 나올수 밖에 없게 됩니다.

API 적으로 텍스쳐에 대한 스위칭은 가능하지만 이는 모델링 제작단계에서 미리 준비된 텍스쳐에 대해서만 가능합니다.
텍스쳐 스위칭에 대한 기능은 현재는 API로 존재하지 않지만 짧은 시간에 개발은 가능합니다.

**Comment by loeaf** [comment]
감사합니다
뭔가 다른방법을 찾아봐야겠내요... 일단 참고해서 보고하도록 하겠습니다
