### ISSUE TITLE
Module.canvas.addEventListener event 제거

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#59]
안녕하세요 객체를 선택하는 기능을 아래와 같이 구현하였습니다.
![image](https://user-images.githubusercontent.com/3315478/129321534-28445ca3-10c0-4e27-b924-b8e469024e1e.png)
객제 선택이 안되도록 기존 모드로 되돌릴려고
![image](https://user-images.githubusercontent.com/3315478/129321590-027833dd-6e9b-46ca-806e-9e48e2389a10.png)
아래와 같이 remove 이벤트를 걸어도 안먹는거 같은데 다른 메서드가 존재하나요?

**Comment by avamk2** [comment]
안녕하세요 캐이스를 수집하는 위쪽 코드 부분에 대한 정보가 부족해서 질문을 드립니다.

1. 첫번째 참고에서 해당 이벤트리스너 등록은 어느시점에서 하는건가요?
2. 기존 모드로 되돌린다는 의미는 어떤것인가요?
3. 2번째 이미지에 코드가 어느시점에서 받게 되는건가요?

해당 부분에 대해서 좀더 구체적으로 설명주시면 관련되어서 답변드릴수 있을것 같습니다.
