### ISSUE TITLE
높이정보 없이 특정 영역으로 지도 이동 시키는 방법

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#6]
안녕하세요. 바이브컴퍼니입니다.

특정 도형의 polygon 좌표값을 알고 있습니다.
해서, 중심 좌표와 bbox(envelop, extent,...)정보를 구할 수 있습니다.

bbox정보로 지도 이동시키는 방법 문의합니다.
지도 이동시 해당 도형이 지도에 꽉차게(또는 약간 여유있게?)  표시되면 좋겠습니다.
(alt정보나, zoom정보 없이)

그럼,...

**Comment by newlayerSmd** [comment]
안녕하세요 뉴레이어입니다. 

envelope 값을 가지고 계신다면 아래 api를 사용해보시면 될거 같습니다. 

Module.getViewCamera().moveLonLatBoundary(new Module.JSVector2D(bbox[0], bbox[1]),new Module.JSVector2D(bbox[2], bbox[3])); 데이터 타입은 double형입니다. 

자세한 소스는 아래 링크에서 확인하시면 됩니다.
http://www.dtwincloud.com:8080/dt_reference/code/main.do?id=camera_set_viewrect

그럼 좋은 하루되세요.

**Comment by HyunSeongKil** [comment]
동작하는거 확인 했습니다.

고맙습니다.
