### ISSUE TITLE
건물 높이 지점 클릭에 따른 경관보기

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#60]
아래와 같이 마우스를 클릭했을때 마우스로 클릭한 해당 부분에 대해서 경관을 보는 기능이 있을까요?
![image](https://user-images.githubusercontent.com/3315478/129323627-8948cb33-968f-487a-860c-01c2f4f61a81.png)
위 사진에서 해당 지점을 클릭하면
![image](https://user-images.githubusercontent.com/3315478/129323807-c25bde29-de33-4f5f-a921-1e110b5ec1cc.png)
위 같은 사진과 같이 면에 수직한 방향벡터로 카메라 전환 (카메라를 앞뒤 가중치를 조절하고  있으면 좋을꺼 같습니다.)
![image](https://user-images.githubusercontent.com/3315478/129324317-f66de62f-4c42-494e-b48d-da94c1a1623c.png)
마우스로 노랑색 클릭위치
빨간색 카메라 위치
파랑색(L) 카메라가 뒤로 후퇴하는 길이

그리고 특정한 이벤트를 주었을 시 카메라 복귀

**Comment by avamk2** [comment]
안녕하세요 현재 경관보기 기능에 대해서 먼저 소개드립니다.

http://sandbox.dtwincloud.com/code/main.do?id=camera_landscape

여기 기능에 대한 내용을 모르신다면 질문에 대한 파랑색 L 셋팅을 제외한 기능으로 현재 동작합니다.

파랑색 L에 대한 벡터방향이 어느기준인지에 대해서 말씀 주시면 검토해서 답변드리겠습니다.

**Comment by loeaf** [comment]
검정색 화살표 방향입니다 ㅎ 
![image](https://user-images.githubusercontent.com/3315478/129820226-67ac23d3-6053-457f-a09c-0101be4a32e3.png)
해당위치를 찍는다고 하면 창문에 딱붙어서 바라보는 것일거라 원금감에 차이가 있어서 뒤쪽으로 거리를 두려고 하는겁니다

**Comment by loeaf** [comment]
const polygon = Module.createPolygon(name);
    polygon.loadFile({
      position: new Module.JSVector3D(v3.lon, v3.lat, v3.alt),
      url,
      align: 'bottom',
    });
    파일 형태로 올린 객체는 작동이 안되는거 같은데 어떻게 해야지 작동이 되는가요???

**Comment by loeaf** [comment]
![image](https://user-images.githubusercontent.com/3315478/129877586-b7e0badf-7df0-4ebb-83a4-214cb6d6b0bf.png)
기능을 썻을때 옥상의 경우 바닥에 딱 달라붙어서 이상하게 보이는 경우가 있는데 해당 부분에 대해서도 기준 고도값을 준다던지 하는 방법으로 수정이 필요할꺼 같습니다

**Comment by avamk2** [comment]
조망점 보기 기능에 대한 기능이 현재는 맵서버에서 제공되는 건물모델에 대해서만 현재 적용되어 있는 상태입니다. 사용자 모델에 대해서는 내부적 객체에 대한 인식하는 구조가 달라서 적용은 가능하지만 작업량이 좀 있는 편입니다.

현재는 조망점 보기 기능이 건물의 벽면에 한정해서 바깥면을 보는 개념으로 구성되어 있으며 그렇지 않으면 지상 지점에 의해서 동작하게 되어 있습니다. 내부적 로직상은 건물이면 벽을 기준으로 한다고 생각하고 건물이 아니면 지면으로 인식합니다. 옥상에 대해서는 검토하지 않은 부분이 형상(지오메트리) 기준으로 옥상을 파악하는게 꽤나 까다로운 일이기 때문에 개발 과정에서는 일단 검토되지 않았습니다. 그래서 벽면으로 인식하고 클릭한 지점을 기준으로 카메라가 셋업되었습니다.

위에서 제안을 주신 카메라의 위치 보정과 이사항을 검토해서 2가지 부분이 야기됩니다.

1. 건물모델링이 모델링 작업자에 방식에 따라서 내부면이나 양면작업이 된 부분이면 카메라를 모델 내부로 넣어서 외부로 볼대 해당면에 의해서 시야가 차폐될수 있습니다. 내부면이 보이지 않는 무결성 건물 모델링이면 몰라도 그런 보장이 없다면 이부분 때문에 원하는 기능이 안될 수 있습니다. 이는 조망보는 건물의 모델링 자체를 숨기는 방식이면 일단은 해결은 될듯 합니다.
2. 형상 기준으로 건물의 지붕을 인식하는 부분이 어려운건 과거 완전한 수평으로 지붕이 만들어져 있으면 어느정도 계산이 되지만 현시대 건물들이 지붕을 사선으로 만드는 경우도 많아서 이것이 벽면인지 지붕인이 인식에 대한 문제사항이 발생합니다. 클릭한 지점의 면이 수직으로 어느각도까지를 지붕으로 간주할 지는 꽤나 어려운 일이됩니다.

위에 기능과 종합적으로 보면 건물 벽면으로 클릭한 경우 건물 내부(보정값 만큼 넣어서)에서 외부로 보는 경관을 봐야되며 지붕(옥상)을 클릭한 경우 높이를 올려(사람의 키 또는 일정의 높이 보정값)을 통해서 위로 띄워서 보는걸 원하는 것으로 해석됩니다.

기능적으로 풀어서 정리하면

- 맵서버에서 제공되는 서비스 모델 건물이 아닌 사용자 등록 건물에서 조망보기 가능
- 벽면을 인식한 경우 인식 지점에서 카메라의 시야방향을 기준으로 전후진 보정 기능
- 지붕(옥상)을 인식한 경우는 인식지점에서 카메라의 높이를 보정하는 기능

위 3가지가 필요한 것으로 확인됩니다. 해당 사항이 맞는지 검토 바랍니다.

**Comment by loeaf** [comment]
맵서버에서 제공되는 서비스 모델 건물이 아닌 사용자 등록 건물에서 조망보기 가능
벽면을 인식한 경우 인식 지점에서 카메라의 시야방향을 기준으로 전후진 보정 기능
지붕(옥상)을 인식한 경우는 인식지점에서 카메라의 높이를 보정하는 기능
으로 진행해주시면 될꺼 같습니다
감사합니다!

**Comment by avamk2** [comment]
데이터 적인 측면과 기능 API들을 리파인해야되기 때문에 위에 언급한 대로 시간이 필요한 사항입니다.
해당 부분들을 모두 포함해서 업데이트 되는대로 사용법과 함께 포스팅 하도록 하겠습니다.
