### ISSUE TITLE
바람표현 관련 문의

### ISSUE THREAD

**Issue by Parster** [EgisCorp/XDWorld#62]
안녕하십니까 ! 이지스 박규호 주임입니다.

풍향을 3D 맵에 바람표현 기능 사용하여 가시화하려고 합니다.
![image](https://user-images.githubusercontent.com/86399390/129825456-c2661640-01f1-438e-9200-4f0f81c99516.png)
위 샘플처럼 가시화 진행하려고 합니다.

샘플코드를 보니 
	// 시간대별(windTime) win 파일 이름
	windFileName : ["FT001800.win", "FT003600.win", "FT007200.win", "FT014400.win", "FT021600.win", "FT028800.win"],
win파일을 가져와서 사용하고 있었습니다. 
저 win파일이 어떤  파일이고 어떤 식으로 사용할 수 있는지가 필요합니다.

감사합니다.

**Comment by YangHeeBong** [comment]
안녕하세요 박규호 주임님

.win 파일은 연구소 자체적으로 가공 생성한 포맷으로 목적은 바람의 흐름을 표현하기 위한 부분입니다.

관련 된 내용이 많아 상세 내용은 연구소로 연락 주시기 바랍니다.

**Comment by Parster** [comment]
넵! 감사합니다!
