### ISSUE TITLE
3D 객체 회전 문의

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#63]
안녕하세요!
3차원 객체를 회전 시키고 싶은데 어떻게 해야하나요??
![image](https://user-images.githubusercontent.com/3315478/129868377-2a27b631-1cf7-4584-90db-b3893e56c805.png)

**Comment by avamk2** [comment]
안녕하세요 

API적으로 객체를 편집(이동, 회전)하는 부분에 대해서 코드 검토를 하였습니다. 
원래 존재하는 기능이나 엔진 업그레이드 과정에서 통폐합을 진행하는 부분에서 API와 함께 기능이 누락되었던거 같습니다.

해당부분에 대해서 조속하게 제어기능을 통해서 업데이트에 올려둘 예정입니다.
적용이 되면 API 설명과 함께 포스팅 하겠습니다.

**Comment by loeaf** [comment]
네 감사합니다
