### ISSUE TITLE
keyControl 민감도 조절 및 충돌방지

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#64]
안녕하세요
한번 클릭할때 너무 많이 움직는거 같은데 민감도 조절은 어떻게 하나요?
그리고 건물을 뚫고 지나가는데... 건물을 못뚫고 지나가게 하려면 어떻게 해야하나요?
샘플 샌드캐슬
http://sandbox.dtwincloud.com/code/main.do?id=option_control_key

**Comment by avamk2** [comment]
안녕하세요

키입력에 대한 이동처리에 대한 제어기능은 현재는 글로벌 카메라 속도 제어로 가능하긴 하지만 이는 개발하는 분들이 수시로 이 값을 제어해야되는 불편함이 있다고 판단하여 다음 업데이트에서 키보드 입력에 의한 이동에 한정해서 민감도 수준을 제어 할 수 있는 기능과 API를 포함할 예정입니다.

건물의 벽면 및 바닥면 인식에 관련해서는 예전에 기능을 만들었다가 다시 제거한 사항이었는데 너무 정교한 모델링인 경우는 바닥면 모델 및 벽면 모델에 대한 모델 데이터 구조에 대해서 정의된 약속이 없으면 건물전체에 형상을 모두 바닥방향과 벽면 방향에 대한 계산을 해야되어서 조작이 불가능한 수준에 속도저하를 야기했기 때문입니다.
이부분을 다시 도입하기 위해서는 시스템에 맞는 데이터 구성에 대한 협의 이후에 반영을 정해야되겠습니다.
