### ISSUE TITLE
3차원 객체 이동 문의

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#65]
안녕하세요!
키보드 또는 마우스 제어를 통해서 3차원 관점에서 3차원 객체를 이동시키고 싶은데 해당 기능과 유사한 기능이 있나요?
감사합니다

**Comment by avamk2** [comment]
객체에 대한 이동/회전 편집 사항은 
63번 이슈에서 연결되는 사항으로 확인됩니다. https://github.com/EgisCorp/XDWorld/issues/63#issuecomment-901768350

API 적인 부분과 마우스에 의한 편집제어는 추가될 예정입니다.
키보드를 통한 편집은 편집 API가 추가되면 키보드 이벤트와 엔진 API응용을 통해서 개발가능 할 것으로 예상되어 개발 사항으로는 고려하지 않습니다.

기본적인 기능이 누락된것을 확인하여 기능적용 및 테스트를 확인하여 빠르게 업데이트할 예정입니다.

**Comment by loeaf** [comment]
네 감사합니다
