### ISSUE TITLE
지도상 확대 수준에 따른 축척 계산

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#67]
![image](https://user-images.githubusercontent.com/88410545/131305879-41aab16c-c031-4861-b9f0-8a6210722a78.png)

안녕하세요!
위 이미지에 들어갈 축척을 구하려고 합니다.
함수나 계산법이 있을까요??

**Comment by avamk2** [comment]
안녕하세요 

축척에 대해서 이야기 드리면 3D 화면에서는 일반적으로 원근투영 [Perspective Projection]을 사용합니다. 
![image](https://user-images.githubusercontent.com/82994540/131308970-b3a2ee55-baac-4fed-8a3f-0e54f665bc1d.png)
<원근투영(좌)과 직교투영(우) 비교>

원근투영에서 축적을 표현할 수 없는 이유는

1.  3D에서 원근투영은 화면기준으로 카메라 위치부터 사물까지 거리에 따라서 화면에 출력되는 픽셀의 크기가 달라집니다.  때문에 UI상 축적을 넣어도 이게 3D 공간상 사물이 카메라에 가까우면 픽셀과 픽셀사이에 거리가 매우 짧은 거리이며 반대로 멀면 멸수록 픽셀간 공간의 거리가 매우커집니다. 

![image](https://user-images.githubusercontent.com/82994540/131310265-fcc01ce3-ab2e-4826-a80e-7a49d1fdcdb3.png)
<직교투영에서 거리별 사물의 크기 표현(좌), 원근투영에서 거리별 사물의 크기 표현(우)>

2. 원근투영은 화면의 가운데 픽셀과 가장자리 픽셀의 크기가 다릅니다. 원근투영은 FOV [Field of View] 화각에 의해서 화면 가운데는 1도당 거리가 좁으며 멀어질수록 1도당 거리가 넓어집니다.

![image](https://user-images.githubusercontent.com/82994540/131311008-d646b740-ce77-46f4-8e0f-29d530336f49.png)


정리하면 3D 화면에서는 거리에 따라서 한 픽셀당 거리가 다르며 동시에 화면의 중심과 가장자리 기준에서도 거리가 다르기 때문에 이러한 이유로 이론상 축적을 넣을 수가 없습니다.

**Comment by giyoon99** [comment]
넵 감사합니다!
