### ISSUE TITLE
3ds 레이어 표출 시 .jpg 파일명 대문자로 불러오는 부분 문의

### ISSUE THREAD

**Issue by giyoon99** [EgisCorp/XDWorld#68]
안녕하세요!

현재 .3ds 모델링 데이터를 불러올 때
같이 불러와지는 .jpg 파일이 파일명과 확장자까지 모두 대문자가 아닌 경우엔 로딩이 안되고 있습니다.

대소문자 관계없이 불러오도록 하고 싶은데 방법이 있을지 문의드립니다.
감사합니다!

**Comment by avamk2** [comment]
안녕하세요

.3ds 모델링과 그것을 매게하는 텍스쳐 이미지의 파일명에 대한 이슈로 확인되었습니다. 결론적으로는 엔진과는 전혀 무관한 문제이긴합니다. 

### 원인 
이유는 .3ds 파일에 재질속성에서 텍스쳐 파일명을 정의하는데 이 파일명 정의에서 3ds를 생성 또는 변환하는 도구에서 임의 또는 사용자 정의에 의해서 명칭을 지칭할 수 있습니다. 여기서 일반적인 Windows O/S에서는 **파일명에 대소문자에 의한 별도 파일로 인식하지 않기에 명칭상도 잘 마음대로 부여해 동작**합니다.

다만 이것을 서버에 올려서 **URL 기반으로 파일을 요청할때는 UNIX 표준기반에 의해서 파일의 대소문자를 구분**하게 됩니다. 따라서 Windows O/S 기반에서 무시해서 별탈없던 파일의 대소문자 지정이 UNIX O/S 기반에 업로드되면서 구분이 활성화 되고 .3ds 내부에 존재하는 텍스쳐 파일명 정보의 대소문자와 실제 텍스쳐 이미지 파일명(확장자 포함) 대소문자가 다를경우에 엔진에서는 http 표준 통신에 의해서 URL로 파일명을 조합하여 호출합니다. 그리고 웹서버에서 URL 정보를 수신했을때 **대소문자를 구분하여 없는 파일로 인식하고 HTTP 404 Error를 출력**하게 됩니다.

### 결론
결국은 서버에서 대소문자를 무시할수 있는 서비스가 아니면 엔진에서는 이부분에 컨트롤 할 수 없게 됩니다.

만약 그럼 엔진에서 대소문자를 체해서 처리하면 이라는 해결에 대해서는 엔진에서 abcdef.xyz 라는 파일명에서 a를 A로, b를 B로, .x를 X로 등으로 모든 패턴에 가짓수를 조합해서 404가 발생하지 않을때까지 체크하는 것을 네트워크 처리 및 퍼포먼스에서 큰 문제를 야기합니다.

이부분은 근본적으로는 **서버에서 파일 URL 호출에서 대소문자를 해결해 줄수 있는 서비스가 있거나** 아니면 **서비스 영역에서 모든 파일은 소문자로 업로드를 하는 지침**이 있어야만 해결될 수 있는 문제입니다.

**Comment by giyoon99** [comment]
답변 감사합니다!

혹시 .jpg 파일명 중 대소문자가 섞여서 들어가있는 경우가 아닌

소문자로만 이루어져 있거나 대문자로만 이루어져 있다고 가정했을 때

엔진에서 소문자로 불러올지 대문자로 불러올지 지정할 수 있는 옵션을 추가하는 부분은 불가능할까요??

**Comment by avamk2** [comment]
모듈에 대한 호환성 문제나 엔진의 규칙사항으로 정의여부에 대해서 현재 내부 검토중에 있으며 결정나면 다시 포스트 하도록 하겠습니다.

**Comment by giyoon99** [comment]
넵 감사합니다!!
