### ISSUE TITLE
건물 높이를 지정하여 투명도를 주는 기능

### ISSUE THREAD

**Issue by KIMSEONOK** [EgisCorp/XDWorld#69]
안녕하세요. 이지스 김선옥 주임입니다.
작년에 문의드렸었던 기능이지만 당시 여러 사정으로 인해 제대로 사용해보지 못하고
이번에 다시 사용하게 되면서 몇 가지 질문사항이 생겼습니다.
아래는 이전에 받았던 샘플에서 투명도값만 변경한 코드입니다.

```
Module.canvas.onmouseup = function(e) {
		
	// 마우스 모드가 단면 보기 상태인지 확인
	if (!GLOBAL.isCutBuilding) {
		return;
	}
		
	// 클릭한 화면 좌표를 지도 좌표로 변환해 선택한 지점의 해발 고도를 반환
	var mapPosition = GLOBAL.map.ScreenToMapPointEX(new Module.JSVector2D(e.x, e.y));
	
	if (mapPosition.Altitude < 42.5) {
		return;
	}
		
	var layerList = new Module.JSLayerList(false);
	
	for (var i=0; i<layerList.count(); i++) {
		var layer = layerList.indexAtLayer(i);
		layer.SetReal3dCutHeightAlpha(0);
		layer.SetReal3dCutHeight(mapPosition.Altitude);
	}
		
	createHorizontalPlane(mapPosition.Altitude);
};

```
```
function createHorizontalPlane(_altitude) {
	
	var layerList = new Module.JSLayerList(true);
	var layer = layerList.nameAtLayer("HORIZONTAL_PLANE");
	if (layer == null) {
		layer = layerList.createLayer("HORIZONTAL_PLANE", Module.ELT_POLYHEDRON);
	}
	
	layer.removeAll();
	
	var plane = Module.createPolygon("HORIZONTAL_PLANE_OBJECT");
	
	var vertices = new Module.Collection();
	vertices.add(new Module.JSVector3D(127.14944099595323, 35.81541740456518, _altitude));
	vertices.add(new Module.JSVector3D(127.14953914851579, 35.81500005953601, _altitude));
	vertices.add(new Module.JSVector3D(127.15010117620314, 35.81506167112981, _altitude));
	vertices.add(new Module.JSVector3D(127.15003138554172, 35.815508420867445, _altitude));
	
	var planeStyle = new Module.JSPolygonStyle();
	planeStyle.setFill(true);
	planeStyle.setFillColor(new Module.JSColor(1, 255, 255, 255));
	plane.setStyle(planeStyle);
	
	plane.setCoordinates(vertices);
	plane.setSelectable(false);
	
	layer.addObject(plane, 0);
}
```

1. 투명처리 뒷면에 투영되어 보여야될 모델이 표현되지 않는 문제
![image](https://user-images.githubusercontent.com/49426364/133352515-36210651-0baa-4862-b708-05a7671936b0.png)
  투명화처리를 했을 때 뒤에 가려진(실제로 투영되어 보여야할) 부분들이 투영처리가 되지 않아 투명상태로 가려집니다.
  이 문제는 처음 샘플을 받았을 때에도 이슈가 되었었는데, 투명도 그리기 순서에 의해서 생기는 현상으로 추정하고
  마무리된 것으로 알고 있습니다. 

2. 배경투명화 처리 시 투영처리 안되는 문제
![image](https://user-images.githubusercontent.com/49426364/133354736-372e11b7-f62c-4f42-acd1-535a13265441.png)
  배경지도가 깔려있을 때는 1번 캡처본과 같이 폴리곤 아래로 모델이 보였는데, 
  현재 진행하고 있는 프로젝트 특성 상 Module.XDESetPlanetTransparecny(0.0);을 통해 배경을 없애버리면 
  플리곤 아래로 모델이 보이지 않습니다.

3. 빨간색 라인 제거 방법
  폴리곤과 모델링 데이터가 닿는 부분에 빨간색  라인이 생기는데 이를 없앨 수 있는 방법이 있을까요?

**Comment by YunSumin** [comment]
안녕하세요,

말씀 주신 1번과 2번 항목은 실 데이터로 테스트가 필요할 것 같습니다.
XDEMapCreateLayer로 호출되는 타일 URL 코드를 전송해주시면 테스트 후 다시 답변 드리겠습니다!

3번의 항목은 엔진 가시화를 위해 임의로 넣은 부분이라 제거 가능합니다.
다만 빨간색 라인으로 고정되어 있어 엔진 수정이 필요할 것 같습니다.
아래 두 가지 안 중 선택해주시면 선택하신 안에 맞춰 작업 후 다시 말씀드리겠습니다.

1안) 라인을 유지하되, 색상만 변경기 가능한 API 추가
2안) 라인 제거

감사합니다.

**Comment by KIMSEONOK** [comment]
안녕하세요! 3번 항목은 1안으로 만들어주시면 될 것 같습니다.
혹시 가능하다면 선 색상의 투명도 및 굵기를 조절할 수 있는 기능까지 부탁드리겠습니다.ㅠㅠ

1번, 2번 항목 테스트를 위한 타일 URL은 메신저로 보내드리겠습니다. 감사합니다!
