### ISSUE TITLE
init.js 파일 사용 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#7]
안녕하세요. 바이브컴퍼니입니다.

vworld의 데이터를 이용하는 경우 init.js 파일을 사용하라고 가이드가 되어 있어서 init.js를 사용하려고 합니다.

가이드대로 vworld key 입력 후 지도를 실행시켰는데 globe가 표시되지 않습니다.
브라우저의 개발자 도구 > 네트워크를 확인했는데 vworld로 가는 요청에 예외가 발생했습니다.
해당 예외의 내용으로 vworld에 문의 했습니다.
vworld측에서는 이제 더 이상 사용되지 않는 url이라고 답변을 하였습니다.

...
그럼 이제 어떻게 해야 하나요?
(현재는 init_without_key.js 파일을 이용하여 테스트하고 있습니다)

그럼,...

**Comment by Khaia** [comment]
먼저 현재 git 에 올려진 엔진(최신버전)으로 사용하시기 바랍니다.
현재 올려진 버전이 VWORLD 데이터를 사용하도록 설정되어 있고 vworld key 를 입력하지 않아도 globe 까지 나와야 정상입니다.
재확인 부탁 드립니다.

**Comment by HyunSeongKil** [comment]
네...
알려주신 방법처럼 사용했고
vworld에서 오류없이 데이터 조회하는거 확인했습니다.
![image](https://user-images.githubusercontent.com/38479834/119453611-934ab400-bd72-11eb-9121-16213189c902.png)


수고하세요~
