### ISSUE TITLE
3d 건물 가시화 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#70]
안녕하세요. 바이브컴퍼니입니다.

고객으로 부터 3d 건물 관련 데이터를 받기로 했습니다.
1개의 건물을 바닥, 중간층, 꼭대기 이렇게 3개로 받기로 했습니다.

**건물의 높이(또는 충수)에 따라 바닥, 중간층, 꼭대기를 병합해서 3d 건물을 가시화할 수 있는 문의합니다.**

**Comment by avamk2** [comment]
안녕하세요.

문의하신사항에서 데이터적인 측면에서 병합에 대한 기능은 없습니다. 보통 병합이 정말 필요하면 모델링 툴에서 사전에 union으로 결합하여 하나의 모델로 구성하는게 일반적이기 때문입니다.

허나 다른 접근으로 **층별 기준으로 레이어를 생성하고 해당층에 모든 모델을 등록**하면 레이어 관리기능을 통해서 층별 통합관리가 가능합니다.

![image](https://user-images.githubusercontent.com/82994540/134473936-4b6a6e95-4d73-4e65-a336-de4cab4d6351.png)

실제로 저희가 이런식으로 데이터 관리를 해보았으며 레이어 관리를 통한 선택여부, 가시여부들을 컨트롤하여 실내 모델을 보여준 기능 제작한 적이 있었습니다.

**Comment by HyunSeongKil** [comment]
그럼,...

저희가 바닥, 중간층, 꼭대기 데이터와 층수, 층간높이등의 속성 정보를 드리면
1. 지도상에 가시화가 되고
2. 특정층이나 높이를 선택(클릭)했을 경우 해당 층으로 이동할 수 있는 건가요?

**Comment by kian-choe** [comment]
[공유]
해당 데이터는 바닥, 중간층, 꼭대기에 해당하는 바운더리 박스 형태만 제작되어 지도상에 표출하는 것이라고 합니다.

-답변완료(유선)

**Comment by HyunSeongKil** [comment]
알겠습니다.
