### ISSUE TITLE
상수도 사업 엔진관련 문의

### ISSUE THREAD

**Issue by plusvolt** [EgisCorp/XDWorld#71]
안녕하세요.
서울사무실 김상민 차장입니다.

앞으로 통합엔진으로 관리된다고 들어서 현재 진행하고 있는 서울시상수도시설물 3D구축 사업에도
통합엔진을 적용해서 사용하려고 합니다.

통합엔진으로 적용하여 기능 테스트를 수행해보니

Module.getIndoor() 함수가 존재하지 않는다고 나옵니다. 

그래서 두 가지 사항에 대해서 문의 드립니다.

1. 해당 함수가 수행하는 기능을 통합엔진에 추가 가능한가요?
2. 같은 역할을 하는 다른 함수가 통합엔진에 존재할까요?

**Comment by YunSumin** [comment]
안녕하세요, 차장님

확인 결과 통합 엔진에 실내 이동 기능 모듈이 없어 모듈 추가 후 깃 파일을 업데이트 하였습니다.
API는 기존 쓰시던 함수들과 동일하게 사용하시면 됩니다.

배포 된 최신 엔진으로 활용 부탁 드립니다.

감사합니다!
