### ISSUE TITLE
3차원 데이터(정보) 가시화를 위한 이지스 자체 파일 포맷이 있는지 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#72]
안녕하세요. 바이브컴퍼니입니다.

**3차원 데이터(정보)를 가시화하기 위한 이지스 자체 파일 포맷이 있는지 궁금합니다.**

예를 들어 성능이나 해상도 등의 이유로 .3ds파일을 자체 파일 포맷으로 변환해서 가시화하는 거지요.

이 변환된 파일은 반드시 이지스 솔루션(엔진, 런타임)을 사용해야 한다....뭐 이런 제약이 걸리는 파일 포맷입니다.

**Comment by kian-choe** [comment]
알고 계신 바와 같이 이지스 솔루션에서 obj나 3ds 같은 표준포맷을 바로 읽어서 지도상에 사용할 수 있도록 되어있지만, 아무래도 각 포맷만으로는 다양한 요구사항을 만족시키기에는 한계가 있습니다.
따라서, 자체 포맷을 만들어두고 여러 포맷별 형상을 포함하여 구현이 힘든 기능이나 다양한 효과 등을 위하여 자체 포맷으로 변환하여 사용할 수 있도록 되어있습니다.

그리고, 이 포맷은 확장 가능한 다양한 기능들의 사용을 위하여 이지스 솔루션(엔진, 런타임)에서 작동 할 수 있도록 되어져 있습니다.

다만, 지도데이터(지형, 영상)은 표준 포맷을 사용하고 있습니다.

**Comment by HyunSeongKil** [comment]
알겠습니다.
