### ISSUE TITLE
XDServer scale out 가능 여부 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#73]
안녕하세요. 바이브컴퍼니입니다.

아래 그림처럼 XDServer scale out할 수 있는지 궁금합니다.

![image](https://user-images.githubusercontent.com/38479834/134598831-f7e64feb-fc41-4edf-b58d-2861a8604a33.png)

**Comment by kian-choe** [comment]
XDServer는 서비스를 위한 용도라고 보시면 됩니다.
따라서, 지형, 영상, 3D객체를 위주로 해당 데이터를 읽어서 서비스 하는 것이 주요 기능이구요.
그렇다보니 SW적으로 한 서버에 톰캣을 여러대 설치하거나, HW적인 방법으로 장비를 늘려 scale out을 하는 방법 모두 가능합니다.
다만, 너무 서버쪽 request 분산만 이루어지면 storage에 부하가 많아지는 것을 염두에 두어야 할 것으로 생각됩니다.

그 외 기능인 3D객체나 지형 가공등의 관리자기능은 말씀드린 BuildCloud라는 서버에서 제공되니 서비스와 분리하여 구성하는 것이 어떨까 합니다.

**Comment by HyunSeongKil** [comment]
알겠습니다.
