### ISSUE TITLE
자동 위치 이동 파라미터 설명 요청

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#74]
안녕하세요. 바이브컴퍼니입니다.

아래 이미지는 sandbox의 "원형 경로 이동" 코드중 일부입니다.
http://sandbox.dtwincloud.com/code/main.do?id=camera_move_round_path

각 파라미터 설명을 해 주시면 고맙겠습니다.

![image](https://user-images.githubusercontent.com/38479834/134875529-cb745132-3024-407d-96fe-27fed4f7757d.png)

그럼, ...

**Comment by YunSumin** [comment]
안녕하세요.
파라미터 설명은 순서대로 아래와 같습니다.

- 바라보는 중심점 위치 (경도, 위도, 고도)
- 중심점으로부터 거리
- 이동 시 카메라 고도
- 이동 시작 각도 (degree 단위)
- 이동 끝 각도 (degree 단위)
- 이동 시 회전 방향 설정 : 반시계(false), 시계(true)

이동 시작/끝 각도는 정북 방향 0도를 기준으로 입력합니다.
![image](https://user-images.githubusercontent.com/82925313/135218621-2b7f9827-58e9-4c9b-9ac0-2043341f6731.png)

**Comment by HyunSeongKil** [comment]
고맙습니다.
