### ISSUE TITLE
고스트 심볼 편집 - 3ds 파일 확장자 관련 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#75]
안녕하세요. 바이브컴퍼니입니다.

고스트 심볼 편집 기능관련 문의입니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit

파일명에 확장자를 작성하면 안 되는 것으로 알고 있습니다.
확장자가 소문자이면 정상적으로 파일 로드가 되나 대문자이면 정상적인 처리가 되지 않습니다.

**확장자의 대소문자 관계없이 처리될 수 있도록 하는건....안될까요?**

![image](https://user-images.githubusercontent.com/38479834/135216246-a2cea3f0-6be6-4b4e-b3fb-c850bdc04722.png)

**Comment by avamk2** [comment]
77번과 동일한 이슈 복제사항으로 닫겠습니다.
https://github.com/EgisCorp/XDWorld/issues/77#issue-1010573288
