### ISSUE TITLE
구현 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#76]
안녕하세요. 바이브컴퍼니입니다.

구현 방법 문의입니다.

**2점의 좌표(lon, lat, alt)를 알고 있을 때 한점에서 다른 점을 바라보도록 카메라를 변경하고 싶습니다.**

어떻게 구현하면 될까요?

**Comment by YunSumin** [comment]
안녕하세요, 
문의하신 기능은 JSCamera의 look API로 구현 가능합니다.

bool look (from, to)
- from (JSVector3D) : 카메라 위치 좌표
- to (JSVector3D) : 카메라가 바라보는 지점 좌표

```
var camera = Module.getViewCamera();
var from = new Module.JSVector3D(127.32021, 35.31306, 1600.0);
var to = new Module.JSVector3D(127.32335, 35.31523, 100.0);
camera.look(from, to);
```

**Comment by HyunSeongKil** [comment]
고맙습니다.
