### ISSUE TITLE
고스트 심볼 편집 - 파일 경로 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#77]
안녕하세요. 바이브컴퍼니입니다.

http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit

질문)
**3ds파일이 다른 서버에 있는 경우 파일을 로드할 수 있는 방법은 무엇인가?**

예제에서는 파일이 같은 서버에서 웹서버가 접근할 수 있는 경로에 파일이 있다는 가정인것 같습니다.

3ds파일이 다른 서버있는 경우 로딩할 수 있는 방법을 문의합니다.

예)
let json = {
  ...전략
  fileUrl : 'http://다른서버url/api/downloadFile.do?fileId=abcd',
  ...후략
}

![image](https://user-images.githubusercontent.com/38479834/135219039-98153902-5b4e-435a-8854-0f14f757a58e.png)

**Comment by avamk2** [comment]
안녕하세요 basePath는 URL 상대경로가 아닌 Full URL로 다른서버로 설정하셔도 동작이 가능합니다. 
다만 다른 서버에서 데이터를 가져온다는건 CORS 보안 오류로 차단당할수 있기에 CORS 우회를 할수 있도록 하여야만 가능합니다.

**Comment by HyunSeongKil** [comment]
그럼...

basePath에 full url주고
file에는 아무값도 안 넘기면 되는건가요?

**Comment by avamk2** [comment]
아니요 파일명을 제외한 host 주소 및 파일까지 접근하는 경로 정보까지만 넣어 주시면 됩니다

**Comment by HyunSeongKil** [comment]
음....

제가 처음에 이슈 등록한 내용을 보면....
파일을 다운로드 하여 스트림으로 읽는 구조로 예제를 작성했습니다.

3ds파일이 url로 접근할 수 있는 경로에 없을 수도 있습니다.

**Comment by kian-choe** [comment]
지금의 DT엔진에서는 자체 서버를 통하여 3DS 파일을 요청하고, 이후에 텍스처를 요청하여 표현할 수 있는 형태로 이루어져 있습니다. 
말씀하신 것처럼 외부의 URL로 연결된 3DS 파일을 읽기 위해서는 데이터를 받고 난 이후의 처리 과정과 텍스처의 요청 처리등에 대해 새로이 정의하여야 할 것으로 보입니다. 
DT엔진과 자체 서버의 구성으로 작동하도록 되어있는데, 예제에 그런 제한 사항이 기재되지 않은 점 죄송합니다.

**Comment by kian-choe** [comment]
예제의 URL 에 다음과 같이 설정을 해주시면 될 듯 합니다.

let json = {
...전략
basePath : 'http://다른서버url/api/downloadFile.do?fileId='
file : 'abcd',
...후략
}


다만, DT 엔진 내부의 처리에서 fileName + 확장자(.3ds) 처리가 되어있습니다. 해당 URL에서 확장자 까지 받아서 처리가 가능해야 할 것으로 보입니다.
그리고, 이후에 텍스처 요청이 이루어지게 되는데, basePath를 이용하여 3ds내에 기입되어있는 파일명으로 요청을 하게 됩니다.

**Comment by kian-choe** [comment]
> 예제의 URL 에 다음과 같이 설정을 해주시면 될 듯 합니다.
> 
> let json = { ...전략 basePath : '[http://다른서버url/api/downloadFile.do?fileId=](http://%EB%8B%A4%EB%A5%B8%EC%84%9C%EB%B2%84url/api/downloadFile.do?fileId=)' file : 'abcd', ...후략 }
> 
> 다만, DT 엔진 내부의 처리에서 fileName + 확장자(.3ds) 처리가 되어있습니다. 해당 URL에서 확장자 까지 받아서 처리가 가능해야 할 것으로 보입니다. 그리고, 이후에 텍스처 요청이 이루어지게 되는데, basePath를 이용하여 3ds내에 기입되어있는 파일명으로 요청을 하게 됩니다.

※텍스처의 이미지 확장자는 ".jpg"를 붙여서 요청하게 됩니다.

**Comment by HyunSeongKil** [comment]
그럼, dt 엔진 내부적으로는
http://다른서버url/api/downloadFile.do?fileId=abcd.3ds 라고 요청한다는거죠?

※ .3ds는 엔진이 자동적으로 붙임

**Comment by kian-choe** [comment]
> 그럼, dt 엔진 내부적으로는 [http://다른서버url/api/downloadFile.do?fileId=abcd.3ds](http://%EB%8B%A4%EB%A5%B8%EC%84%9C%EB%B2%84url/api/downloadFile.do?fileId=abcd.3ds) 라고 요청한다는거죠?
> 
> ※ .3ds는 엔진이 자동적으로 붙임

네, 맞습니다.

**Comment by HyunSeongKil** [comment]
> > 그럼, dt 엔진 내부적으로는 [http://다른서버url/api/downloadFile.do?fileId=abcd.3ds](http://%EB%8B%A4%EB%A5%B8%EC%84%9C%EB%B2%84url/api/downloadFile.do?fileId=abcd.3ds) 라고 요청한다는거죠?
> > ※ .3ds는 엔진이 자동적으로 붙임
> 
> 네, 맞습니다.
