### ISSUE TITLE
교량 표출시 데이터 활용 3차원 가시화시 위치

### ISSUE THREAD

**Issue by kimbab** [EgisCorp/XDWorld#78]
-TM 좌표계 3차원 지형과 교량 위치 상태-
![image](https://user-images.githubusercontent.com/6648264/135367184-8e63cedd-28e0-4d8d-8d1c-11165c7c8d3c.png)

-Arc GIS 내 정사영상과 해당 교량 footprint 위치 상태-
![image](https://user-images.githubusercontent.com/6648264/135367231-fa591d46-0401-4ce6-a334-bd5a93d5e2e6.png)

경위도 좌표계 3차원 지형과 교량 위치 상태-
![image](https://user-images.githubusercontent.com/6648264/135367257-8b5d1890-8dc9-48e7-a95c-454b309b3f79.png)

앞의 캡처이미지와 같이 TM좌표계 3차원 지형과 Arc GIS 내 정사영상과 교량 XY위치 결합 상태는
양호하나 경위도 기반 3차원지형에 교량 3DS 모델링 가시화시  불특정 중심점에서 교량의 XY값의
오류가 발생됩니다. 3DS 모델링 원본의 위치값은 정상영상과 비교시 양호한것으로 확인되어,
엔진 가시화시 발생되는 오류로 확인이 필요합니다

현재는 모델링 데이터를 수동으로  변경해서 적용하고 있는중입니다. 
확인 부탁드립니다.

**Comment by avamk2** [comment]
안녕하세요 내용검토하여 모델에 대한 구형 좌표 변환에 대해서 내부적으로 처리하고 있습니다.
정확하게 해당 사항인지는 구현 및 테스트 후에 이야기 드리겠습니다.

**Comment by kimbab** [comment]
감사합니다~~!!
