### ISSUE TITLE
gpuTextureOverflow 엔진 에러 관련 문의

### ISSUE THREAD

**Issue by kangminah0102** [EgisCorp/XDWorld#79]
안녕하세요. 
이지스 강민아 대리입니다.

카메라 자동 이동 시뮬레이션 시 발생하는 에러 관련하여 문의드립니다.

아래와 같이 실행 후 **gpuTextureOverflow** 에러가 발생합니다. 
1.  XDServer를 사용하여 DEM & TILE & Real3D 데이터 호출 
2.  카메라 자동 이동 시뮬레이션을 할때 에러 발생
     -> 카메라 자동 이동 시 사용하는 함수
     (1) Module.getViewCamera().startAutoMove()
     (2) Module.getViewCamera().bPauseAutoMove
     (3) Module.getViewCamera().pauseAutoMove()
     (4) Module.getViewCamera().stopAutoMove()

[ gpuTextureOverflow 에러 화면 ]
![image](https://user-images.githubusercontent.com/91645606/135377161-652f17a5-f019-4c34-b36a-7f4bfb018b25.png)

감사합니다.

**Comment by avamk2** [comment]
안녕하세요 gpuTextureOverflow 오류는 기본적으로 **특정한 동작을 해서 발생하는 오류가 아닌 지도데이터의 텍스쳐용량이 기준치를 초과하면 발생**시키는 _경고 메세지_ 입니다.

일반적으로 지형영상, 오버레이 이미지레이어 (하이브리드 or WMS), 폴리곤 이미지 텍스쳐들도 영향은 있지만 대부분은 3D 모델 텍스쳐에서 결국 한계 초과가 발생합니다. 해당 경고가 발새하면 이후 사용할려는 텍스쳐 이미지를 처리하지 않고 통과됩니다. 그래서 메세지는 뜨지만 프로그램이 종료된다던가 사이트가 먹통이 되진 않습니다.

현재 엔진에서 PC 저사양과 모바일에서 자주 발생하는 메모리부족으로 인한 충돌을 막고자 허용치를 낮게 세팅해둔 상태입니다. 
시스템적 성능이 허용된다면 이를 올릴수 있는 API는 존재합니다.

> var pOption = Module.getOption();
> pOption.setTexturePoolSize(512*1024*1024);  // 512 MB 설정 ( 부족하면 1024로 설정 )

다만 위에서 언급되었듯이 사용하는 장비의 메모리 성능이 낮으면 시스템의 비정상적인 종료 및 새로고침등의 현상이 생기기 때문에 과도한 수치 증가나 필드 테스트 후에 문제가 없을시만 퍼블리싱 해야됩니다.
