### ISSUE TITLE
이슈는 아니지만... 이슈인가???

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#8]
안녕하세요. 바이브컴퍼니입니다.

이슈는 아니지만...이슈인가???

(저희가 지금 진행하고 있는 업무와는 관련이 없습니다)

개인적으로 흥미가 있어서 **Blazor WebAssembly**에 XDWorld WebGL Engine을 적용해 보았습니다.
![image](https://user-images.githubusercontent.com/38479834/119451692-875df280-bd70-11eb-9aa2-06d9190f73fc.png)

초기화 함수 실행되고 지도가 표시됩니다.
그러나, 지도를 제외한 다른것들이 동작을 하지 않습니다.

생각으로는...  Blazor 내부적으로 아래와 같은 코드가 사용되는데
![image](https://user-images.githubusercontent.com/38479834/119451209-f2f39000-bd6f-11eb-92fc-6642f4fd7c8e.png)

이게 XDWorld의 Module과 충돌되는게 아닌가 하는 생각이 드네요.
![image](https://user-images.githubusercontent.com/38479834/119451899-baa08180-bd70-11eb-94dc-51392becad8d.png)

**Comment by iyeti78** [comment]
var Module;
전역변수명이 중복되었네요.
둘중하나는 다른이름으로 바꿔야할것 같습니다.

**Comment by Khaia** [comment]
Blazor 도 Emscripten 으로 컴파일되는 구조라서 Module 변수가 사용되는 것 같습니다.
