### ISSUE TITLE
객체 선택 관련 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#80]
안녕하세요. 바이브컴퍼니입니다.

객체 선택 관련 문의입니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_select

**객체 선택 기능 종료하면 선택된 건물의 상태를 원 상태로 돌리고 싶은데 어떻게 할 수 있나요?**

객체 선택 기능 종료는 Module.XDSetMouseState()를 이용해 다른 상태로 만들면 될 것 같습니다.
근데, 선택된 건물은 현재 빨간색으로 표시가 되는데, 이걸 원 상태로 돌리는 방법을 모르겠습니다.

그럼,...

**Comment by avamk2** [comment]
안녕하세요 아래코드를 수행해 주시면됩니다.

` Module.getMap().clearSelectObj(); `
