### ISSUE TITLE
고스트 심볼 편집 api 문의

### ISSUE THREAD

**Issue by Kiwoohyun2** [EgisCorp/XDWorld#82]
url : http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit

3ds원본 파일이 텍스쳐가 이미 적용된 파일이더라도 가시화를 하면 텍스처가 적용되지 않은 하얀색파일이 뜹니다
텍스쳐가 이미 적용된 파일도 가시화를 했을 때 원본 그대로 뜰 수 있는 방법이 있을까요?
하고자 하는 건 sandbox 코드를 보시면
"""
	// 모델 로드
	loadGhostSymbolModel(GLOBAL.ghostSymbolMap, "TREE", "./data/", "ghost_bluewontree01", function(e) {
		
		// 모델 텍스쳐 설정
		GLOBAL.ghostSymbolMap.setGhostSymbolTexture(e, "./data/", "ghost_bluewontree01.jpg");
		
		// 객체 추가
		GLOBAL.ghostSymbolObject = createGhostSymbol("TREE_OBJECT", e, [129.126128, 35.170648, 6.0]);
		GLOBAL.ghostSymbolLayer.addObject(GLOBAL.ghostSymbolObject, 0);
		
		displayGhostSymbolProperties();
	});
"""

이 부분에서 "모델 로드"부분에 텍스처가 이미 적용된 파일을 적용해서 적용된 상태로 모델이 띄워지고
"모델 텍스쳐 설정"부분에서 이 텍스처에 추가적인 이미지파일을 하나의 파일이 아닌 여러개를 넣고 싶습니다.
최종적으로는 기본 텍스처가 입혀진 3ds파일에 텍스쳐 설정에서 지정한 이미지파일들까지 입혀지는 그림입니다.

**Comment by avamk2** [comment]
안녕하세요. 
질문사항에대 해서 정리가 필요합니다.

1. 고스트 심볼 편집을 위해서 3ds 모델 로딩을 완료
2. 로딩 완료 콜백을 통해서 텍스쳐 이미지를 요청
3. 텍스쳐가 로딩완료 후 적용
4. 고스트 심볼 모델을 지도상 객체로 삽입

위가 저희가 샘플로 제시된 일련에 과정입니다.

모델 텍스쳐 설정에서 현재 고스트 심볼 모델이 저희 시스템적으로는 1개의 모델에 1개의 텍스쳐로 설정되며 3ds 모델에 uv 좌표 정보 (관련 내용 참조 : https://github.com/EgisCorp/XDWorld/issues/58#issuecomment-900115451 )를 그대로 사용하여 텍스쳐를 가져와서 맵핑됩니다.

여기서 이야기 하시는 사항이 아래에서 어떤 것인지 확인이 필요합니다.

1. 모델 제작단계에서 하나의 3ds 안에 (예 건물의 지붕, 벽면, 실내 등이 별개인) 여러 텍스쳐가 있어서 이를 지원이 필요한 것인지?
2. 하나의 3ds에 1개의 텍스쳐를 여러 스타일로 이미지를 준비하여 이를 교체하는 것이 필요한 것인지?
3. 모델 제작단계에서 고려되지 않은 추가적인 이미지를 넣고 싶은 것인지?
4. 기타의견

3번인경우는 https://github.com/EgisCorp/XDWorld/issues/58#issue-968251823 해당 이슈내용과 같이 모델제작 단계에서 준비되지 않으면 불가능합니다.

**Comment by YunSumin** [comment]
금일 고스트 심볼 API 구성이 개편되어 안내드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_ghost_symbol_edit

```
Module.getGhostSymbolMap().insert({
   id : "TREE",
   url : "./data/ghost_bluewontree01.3ds",
   callback : function(e) {
			
      // 텍스쳐 설정
      Module.getGhostSymbolMap().setModelTexture({
         id : e.id,
         face_index : 0,
         url : "./data/ghost_bluewontree01.jpg",
         callback : function(e) {
            console.log(e.id);
         }
   });
});
```

JSGhostSymbolMap 클래스에 insert API가 추가되었으며,
모델을 구분하는 id, 3ds 파일 path 지정 후 콜백함수를 등록하신 후 API를 호출하시면
3ds 모델을 엔진 내에 등록 후 지정한 callback 프로퍼티의 함수가 호출됩니다.

이때는 모델에 텍스쳐가 적용되지 않은 상태로,
setModelTexture API를 통해 face별로 텍스쳐 이미지를 선택하여 적용하실 수 있습니다.
(미 적용 시 텍스쳐가 지정되지 않고 형상만 존재하는 흰색 모델로 출력됩니다.)

다만 위 답변 내용과 같이 시스템 안정성을 위하여
3ds 모델은 가급적 face수가 적은 모델을 사용하시는 것을 권장 드립니다.

기존 사용하시던 API도 동일하게 사용 가능하나,
가급적 개편된 API 활용을 부탁드립니다.

감사합니다.

**Comment by Kiwoohyun2** [comment]
답변 감사합니다

- 기존 사용하던 api처럼 url에 '~경로.3ds' 나 '~경로.jsp' 형태가 아닌 파일이 다운로드되는 api의 url정보를 넣어도 작동되게 하고 싶습니다

- face_index 값 기준이 궁금합니다

**Comment by YunSumin** [comment]
문의주신 내용에 대하여 답변 드립니다.

**1. 요청 경로에 파일 포맷( ex. ".3ds") 이 포함되지 않은 URL 을 넣어도 동작하도록 수정**

   요청 경로에 파일 포맷이 없어도 파일 로드가 가능하도록 금일 엔진 수정되었습니다.
   단, 요청한 파일의 포맷을 알고 있어야 엔진에서 데이터 파싱이 가능하므로
   insert 함수 호출 시 아래와 같이 포맷 형식을 지정해주셔야 합니다.

   ```
   Module.getGhostSymbolMap().insert({
		id : "TEST",
		url : "요청 URL",
		format : "3DS",
		(이하 생략)
   });
   ```
   format 프로퍼티에 설정되는 문자열은 대소문자를 구별하지 않으므로 자유롭게 입력해주시면 됩니다.

**2. face_index 값에 대한 상세**

   face_index는 3DS 모델 자체에 분리되어 있는 Face를 식별하는 번호로 사용됩니다.
   각 Face 별로 텍스쳐를 지정하여 사용할 수 있습니다.

   모델의 Face 수가 궁금하시다면 insert API의 콜백 함수가 호출 된 후
   JSGhostSymbolMap에서 getModelFaceCount API를 사용하시면 됩니다.
   (파라미터로 insert 시 등록한 id를 넣어주셔야 합니다.)
  
   ```
   Module.getGhostSymbolMap().insert({
		id : "TEST",
		url : "요청 URL",
		format : "3DS",
		callback : function(e) {
			
			// 모델 Face 수 반환
			var face_num = Module.getGhostSymbolMap().getModelFaceCount(e.id);
		}
	});
   ```

최신 버전 엔진으로 업데이트 부탁 드립니다.

**Comment by Kiwoohyun2** [comment]
답변 감사합니다!
현재 각각의 텍스처의 face_index를 알 방법이 없어서 임의로 줄 시 텍스처가 뒤죽박죽 입혀지고 있습니다
혹시 face_index값을 알 수 있는 api나 방법이 있을까요?

**Comment by YunSumin** [comment]
문의하신 face_index 값으로 텍스쳐 이미지 지정 시,
3DS 파일에 내장 된 텍스쳐 정보를 참조할 수 있도록 엔진이 업데이트 되었습니다. (2021-11-12)

insert API의 콜백 함수 파라미터에 faceCount, faceTexure 프로퍼티가 추가됩니다.
- id : 모델 등록 ID
- faceCount : 모델 face 수
- faceTexture : 모델 face 별 텍스쳐 이름
   - 0 : 0번째 face 텍스쳐 이름
   - 1 : 1번째 face 텍스쳐 이름
   - ...
   - n : n번째 face 텍스쳐 이름

```
Module.getGhostSymbolMap().insert({
   id : "TREE",
   url : "./data/ghost_bluewontree01.3ds",
   callback : function(e) {
			
      console.log("id : " + e.id);
      console.log("faceCount : " + e.faceCount);
      for (var i=0; i<e.faceCount; i++) {
         console.log("face " + i + " texture name : " + e.faceTexture[i]);
      }

      ...(이하 생략)...
   }
});
```

위 코드 실행 시 아래와 같이 콘솔창에 출력됩니다.
![image](https://user-images.githubusercontent.com/82925313/141424445-c6a2c68c-eedb-4bde-b9d9-8e09244d0bc4.png)
(텍스쳐 이름이 지정되지 않은 Face인 경우 빈 문자열로 표시됩니다.)

엔진 업데이트 적용 부탁 드립니다.
감사합니다.
