### ISSUE TITLE
init.js 파일 수정 요청

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#9]
안녕하세요. 바이브컴퍼니입니다.

init.js파일에 아래 코드 추가해 주세요.
(기존에는 코드가 있었는데 이번 버전에는 빠져 있네요)
마우스 오른쪽 버튼으로 지도 이동하는데 계속 context menu가 뜨네요..ㅡㅡ;;

![image](https://user-images.githubusercontent.com/38479834/119457324-84660080-bd76-11eb-8edf-41f606198b58.png)

아...
수정하는김에....
window.onresize 이벤트 처리도 추가해 주세요~~
(저는 사용방법을 알지만,...다른 분들은 모를 수 있으니...)

그럼,...

**Comment by YunSumin** [comment]
안녕하세요, 이지스 입니다.
말씀해주신 건의사항을 반영하였습니다.
init.js 파일은 엔진 활용을 위한 참고용 소스로, 향후에도 조금씩 변경될 수 있음을 양해 부탁드립니다.
감사합니다.

**Comment by HyunSeongKil** [comment]
네...
