### ISSUE TITLE
그림자 표출 오류 문의입니다.

### ISSUE THREAD

**Issue by giwon1130** [EgisCorp/XDWorld#90]
https://user-images.githubusercontent.com/92919334/138251519-b62bc3f3-bb8d-4176-b2d5-deed0f251d44.mp4

해당영상처럼 일정 부분의 그림자가 표출이 안되는 오류입니다.

**Comment by hjaejae** [comment]
해당되는 부분을 수정하였습니다.
 최신 버전으로 다시 테스트 부탁드립니다.
