### ISSUE TITLE
이미지 표출시 z-index(가시화 우선순위) 설정 문제

### ISSUE THREAD

**Issue by giwon1130** [EgisCorp/XDWorld#97]
https://user-images.githubusercontent.com/92919334/139027049-d6b642a7-86f6-4801-b3df-e76225c67fae.mp4

안녕하세요 임기원입니다.
영상 가운데에서 확인 가능하듯이 현재는 이미지가 겹쳐 있을 때 카메라 위치에 따라 가시화 우선순위가 변경되는 상태입니다.
혹시 우선순위를 설정하여 어느 위치에서든 같은 우선순위를 가져갈 수 있을까요?

**Comment by avamk2** [comment]
안녕하세요 

현재 POI의 표현을 엔진내에서 하기 때문에 눈으로는 DIV 같은 2D 컨테이너로 보이지만 실제로는 내부에 3D 객체로 들어가서 깊이값이 적용됩니다. 단순 Z-Index 레벨의 깊이가 아니라 물리적 깊이를 계산하는 구조입니다.
그래서 이것을 무시하면 객체의 컨테이너에 담긴 순서대로 그려버리기 때문에 생각하신 우선권에 대한 처리가 생각대로 핸들링이되지 않습니다.

현재 POI에 대한 스크립트 기반 DIV를 입력받을 수있도록 하는 부분에 대해서 연구중에 있습니다. 결과가 나오면 포스트해 드리겠습니다.

**Comment by avamk2** [comment]
안녕하세요 

DIV 기반의 웹을 지도 공간와 연동하는 기능에 대해서 구현되어 알려드립니다.
http://sandbox.dtwincloud.com/code/main.do?id=object_html_control

웹의 DIV 컨테이너 하나가 하나의 위치정보와 매칭하여 다양한 웹 기반 요소를 응용하실수 있습니다.
