### ISSUE TITLE
Module 초기화 완료 상태 확인 방법 문의

### ISSUE THREAD

**Issue by HyunSeongKil** [EgisCorp/XDWorld#98]
안녕하세요. 바이브컴퍼니입니다.

**Module 초기화 완료 상태 확인 방법 문의입니다.**

샘플 코드를 보면 Module 초기화 완료 후에 init() 호출하도록 되어 있습니다.
init()이 호출되었다는건 Module 초기화 완료 되었다는 의미인데...

init()함수가 아닌 다른 곳에서 Module초기화 완료 되었는지 판단하고 싶습니다.

예)
if(null === Module || undefined === Module){
  console.log('Module 초기화전...');
}

방법이 있을까요?

**Comment by YunSumin** [comment]
샌드박스에 공통적으로 사용하는 init 함수는 Module 객체의 postRun 프로퍼티와 연결 된 함수로,
엔진 초기화 후 활용이 가능해질 때 자동으로 호출되도록 구성되어 있습니다.

```
var Module = {
	TOTAL_MEMORY: 256*1024*1024,
	postRun: [init],
	canvas: (function() {

		// Canvas 엘리먼트 생성
		var canvas = document.createElement('canvas');
                ...(생략)...
	})()
};
```

postRun 프로퍼티에 init 함수 외 다른 함수를 연결하여 사용하실 수 있습니다.

postRun 연결 함수가 호출 되기 전의 Module 객체는 API 구성이 완전히 이루어지지 않은 상태이므로
반드시 연결 함수가 호출 된 후 Module 객체 활용 부탁 드립니다.
