### ISSUE TITLE
지도 종류 문의

### ISSUE THREAD

**Issue by loeaf** [EgisCorp/XDWorld#99]
안녕하세요! 3D 지도인대
2D회색이나 2D야간지도 모양을 쓰고 싶은데 가능할까요?
![image](https://user-images.githubusercontent.com/3315478/139425571-69332e4c-b729-4c27-89cf-0c0c3ed5626f.png)

**Comment by avamk2** [comment]
안녕하세요 
출처가 어디인지 모르겠으나 3차원 지형을 만드는 영상자료가 확보되면 이것을 선택하는 기능은 가능합니다.

**Comment by loeaf** [comment]
출처가 vworld 입니다 ㅎㅎ...
https://map.vworld.kr/map/ws3dmap.do
![image](https://user-images.githubusercontent.com/3315478/139788474-bf52829b-c06f-442c-b3ea-7591b2621a62.png)

**Comment by loeaf** [comment]
3차원 지도 바닥에 저러한 타일 이미지를 깔고 싶습니다

**Comment by SeongRyong-Choi** [comment]
안녕하세요.

브이월드 데이터는 브이월드에서 API Key를 발급받으신 후 사용할수있습니다.

http://sandbox.dtwincloud.com/code/main.do?id=layer_vworld_wmts

샌드박스 예제에서 API Key 입력 후 실행부탁드립니다.

감사합니다.
